### ISSUE TITLE
java.lang.RuntimeException: error converting -1dp using EnumConverter

### ISSUE THREAD

**Issue by thillerson** [robolectric/robolectric#1015]
Within a fragment we have a widget with a dimen set to -1dp, which Android interprets as match_parent.

When building an activity using the fragment, we get the exception in this gist: https://gist.github.com/thillerson/9749262

**Comment by OleksandrKucherenko** [comment]
I found the cause of the problem:
- anybody try to TRIM the line from white-spaces during the XML parsing?! 

mistake is in code (https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/res/Attribute.java):
```java
 public boolean More ...isResourceReference() {
  return value.startsWith("@") && !isNull();
}
```

value may contain white-space at the beginning!

**Comment by jongerrish** [comment]
Robolectric 4.0 and binary resources has vastly improved resource handling. Please give that a try and reopen if its still an issue.
