### ISSUE TITLE
Failed to create RenderScript Context

### ISSUE THREAD

**Issue by thillerson** [robolectric/robolectric#1034]
Not sure where to leave this issue. It's against the support-4.4 branch on @erd's fork. When we start up an Activity, we get the following stack trace: https://gist.github.com/thillerson/10066558.

Sorry if this issue is unhelpful, I can try to provide more information if needed.

**Comment by GuillaumeLachaud** [comment]
I am having this issue on Robolectric 3.0. Is Renderscript supported ?

**Comment by erd** [comment]
No. Renderscript will not work under Robolectric.

**Comment by komalgit** [comment]
Any update on this? I am using Robolectric version 4.1, facing same issue 
android.renderscript.RSDriverException: Failed to create RS context.

RenderScript rs = RenderScript.create(mContext); <-- Fails at this line

**Comment by Elektro33rus** [comment]
Hi guys, as far as I can see this has been fixed, however in the latest version of robolectric I still get the same error

**Comment by utzcoz** [comment]
Hi @komalgit @Elektro33rus , as https://github.com/robolectric/robolectric/issues/1034#issuecomment-140876900 said, it's sad that RenderScript doesn't work now under Robolectric now. If your code depends on RenderScript, what about trying mocking likes https://github.com/oppia/oppia-android/pull/2422? If you can provide an example to reproduce this problem, I can take look at it to check whether Robolectric can fix this problem.

**Comment by Elektro33rus** [comment]
@utzcoz In my app there is a class that extends Application, various helper classes are initialized in it, and RenderScript is initialized in one of them. My problem is that when I run the test, MyAppApplication is created first (which extends Application), and everything crashes at this point

I tried to use @Before - but it gets executed after MyAppApplication is created

**Comment by hoisie** [comment]
@Elektro33rus please file a new issue with more details and repro instructions. This issue is 7 years old and we should not piggy back on it.

https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues
