### ISSUE TITLE
Cannot use with PowerMock because of different ClassLoader

### ISSUE THREAD

**Issue by WonderCsabo** [robolectric/robolectric#1058]
This is my simple test:

``` java
@RunWith(RobolectricTestRunner.class)
@PrepareForTest(ServerPointPackage.class)
public class PowerMockRobolectricTestCase {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    static {
        PowerMockAgent.initializeIfNeeded();
    }

    @Test
    public void test() {
        mockStatic(ServerPointPackage.class);

        when(ServerPointPackage.getCount()).thenReturn(2);
    }
}
```

Unfortunetaly i get the following error when i run the test:

`PowerMockRule can only be used with the system classloader but was loaded by org.robolectric.bytecode.AsmInstrumentingClassLoader`

Are there any workarounds for this?

**Comment by jaredsburrows** [comment]
Have anyone got `Gradle` + `PowerMock` + `Robolectric` to work?

**Comment by WonderCsabo** [comment]
@jaredsburrows if you look at my Maven example i referenced two comments earlier, you can easily integrate those changes in the [official Robolectric Gradle example project](https://github.com/robolectric/deckard-gradle), it should work.

**Comment by jaredsburrows** [comment]
@WonderCsabo What? to simply add the dependencies as `provided`?

 - `org.powermock:powermock-module-junit4`
 - `org.powermock:powermock-module-junit4-rule`
 - `org.powermock:powermock-api-mockito`
 - `org.powermock:powermock-classloading-xstream`

**Comment by WonderCsabo** [comment]
You should add those in the  `testCompile` scope just like the other Robolectric deps in the Gradle project and my Maven project.

And of course you have to modify the Java classes to actually use the deps.

**Comment by jaredsburrows** [comment]
@WonderCsabo Yes I have used `PowerMock + Gradle` before. I was asking if you can use the `RobolectricGradleTestRunner` with `PowerMock`?

**Comment by WonderCsabo** [comment]
I never tried that, but it should work, since the only difference between `RobolectricGradleTestRunner` and the standard `RobolectricTestRunner` is that the former looks for the manifest, package name etc differently (according to the Gradle project structure and build variants).

**Comment by jaredsburrows** [comment]
I have already tried using the `RobolectricGradleTestRunner` with `PowerMock` and it does not work. This is why I asked if anyone had it working.

**Comment by WonderCsabo** [comment]
Sorry, but you should tell much more details then "does not work", if you want me to help you on that problem. :wink:

**Comment by jaredsburrows** [comment]
What more details do you want?

I am looking at your branch here: https://github.com/WonderCsabo/deckard-maven/blob/PowerMock/src/test/java/com/example/activity/MainActivityTest.java/

I am using `Gradle` not `Maven`
I use `RobolectricGradleTestRunner` 
I use `Robolectric 3.0-rc3`
I can easily work with `Mockito` but I am trying to run existing PowerMock tests with `RobolectricGradleTestRunner`

**Comment by WonderCsabo** [comment]
There are multiple changes here, because with PowerMock

* i never tried `Gradle`
* i never tried `Robolectric 3`

Both *should* work with my example in theory, but theory and practice is only equal in theory. :smile: If you can share the created project, i can try it later.

**Comment by jaredsburrows** [comment]
You have:

    @RunWith(RobolectricTestRunner.class)
    @PowerMockIgnore({ "org.mockito.*", "org.robolectric.*", "android.*" })
    @PrepareForTest(Static.class)

I tried:

    @RunWith(RobolectricGradleTestRunner.class)
    @PowerMockIgnore({ "org.mockito.*", "org.robolectric.*", "android.*" })
    @PrepareForTest({...)

Here is the repo, I was able to get one test to pass, it only used easy mock though:
https://github.com/NonameDev/MathApp/blob/master/app/src/test/java/burrows/apps/math/data/DataFetcherTest.java

**Comment by WonderCsabo** [comment]
I created an [example](https://github.com/WonderCsabo/deckard-gradle/commit/0dbec9ab3af768774570690d217731a832836baa) with Robolectric 3 and `RobolectricGradleTestRunner`, which seems to be working.

**Comment by jaredsburrows** [comment]
What about `verifying` and `replaying`? Also I am using `PowerMock + EasyMock`, I am not sure if that matters or not.

That test seems very simple.

Please look at mine on a `test branch`: 
https://github.com/NonameDev/MathApp/tree/test/robolectric_powermock/app/src/test/java/burrows/apps/math/data

and the `build.gradle`:

https://github.com/NonameDev/MathApp/blob/test/robolectric_powermock/app/build.gradle

**Comment by WonderCsabo** [comment]
@jaredsburrows i am not using `EasyMock` at all, sorry.

**Comment by jaredsburrows** [comment]
@WonderCsabo Ok. I am guessing PowerMockito works by not PowerMock + EasyMock.

**Comment by WonderCsabo** [comment]
@jaredsburrows i just looked at your test, and you are definitely missing:

```java
@Rule
public PowerMockRule rule = new PowerMockRule();
```

You also using the `RobolectricGradleTestRunner` incorrectly, since it expects:

```@Config(sdk = 18, constants = BuildConfig.class)

(the second param is needed for this runner, the first param is needed because Robolectric does not support API 22)

Finally, you cannot instrument classes with PowerMock which are already instrumented by Robolectric. Hence `Log` and `URL` cannot be instrumented with PowerMock.

I quickly [fixed](https://github.com/WonderCsabo/MathApp/commit/7379d4b4dca456bf2bee475cf4faaf672881a464) these problems in my fork (withouth verifying the correctness of the tests).

**Comment by jaredsburrows** [comment]
@WonderCsabo 
The tests run fine without using the `RobolectricGradleTestRunner`, that is why I did not use the `Rule`.

Also, I am using the `Robolectric` configuration file instead of annotating ever single test. Please see here: https://github.com/NonameDev/MathApp/blob/master/app/src/test/resources/robolectric.properties. I am emulating API 21. `Robolectric` does support up to 21.

**Comment by WonderCsabo** [comment]
`RobolectricGradleTestRunner` and `Rule` has no connection. My simple tests are failing without it, that is definitely needed. Also i am pretty sure you cannot instrument the android classes with `PowerMock` and Robolectric at the same time.

About `@Config`: yeah, i used the IntelliJ JUnit runner, and did not set the current folder correctly.

**Comment by jaredsburrows** [comment]
@WonderCsabo 
I just ran your branch, everything works with the `Rule`. 

When I change the sdk to `21`, they fail like this:

    burrows.apps.math.data.DataFetcherTest > testGetEquationsNullData FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

    burrows.apps.math.data.DataFetcherTest > testGetVersionNullData FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

    burrows.apps.math.data.DataFetcherTest > testGetVersion FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

    burrows.apps.math.data.DataFetcherTest > testGetEquations FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

Thank you for your help thus far.

**Comment by WonderCsabo** [comment]
I think those failures are not related to this `PowerMock` integration, but a bug in `Robolectric` itself.

**Comment by jaredsburrows** [comment]
Thank you.

I upvoted your answers on StackOverflow for this. I guess we can use this issue to also show others how to setup it up with Gradle.

It seems only not work with 21. I have tested with 18 and 19, I made an issue here: https://github.com/robolectric/robolectric/issues/1855
