### ISSUE TITLE
Make it easier to reset the static state of Shadows

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1072]
From a discussion on the mailing list:

```
It would be really nice if this mechanism in Robolectric was extensible. What
if instead of  calling the method named reset() it looked for static methods on
registered shadows with a @Reset annotation? (as per effective Java 2nd edition
item 35: Prefer annotations on naming patterns) Then custom shadows could add
a @Reset-annotated method and have that automatically called for them by
Robolectric.

There is another way you could do it which would be less error-prone (in the
sense of you could make a mistake in the reset() method), and I think is what
Powermock does: You could use a custom classloader to unload and reload the
static class between tests, which would guarantee it was in the initial state. I
assume that would be slower and more complicated?
```

**Comment by lexs** [comment]
Seems like this functionality is broken after the switch to the annotation processor, would be cool if we could reflectively check this for user provided shadows.

**Comment by lexs** [comment]
Removed here: https://github.com/robolectric/robolectric/commit/16c355c72262eee2c299928dde749c0c0a745877

**Comment by erd** [comment]
> Seems like this functionality is broken after the switch to the annotation processor, would be cool if we could reflectively check this for user provided shadow.

We purposefully removed this functionality in favor of the `@Resetter` annotation.

**Comment by lexs** [comment]
I know, but I was under the impression that `@Resetter` won't work for user-provider shadows? Didn't actually verify this though.

**Comment by arturdm** [comment]
@lexs I don't know if you managed to reset the static state of your custom Shadow class but if someone still needs it for robolectric-3.0 here's how I did it trying to shadow the `android.support.design.widget.Snackbar` class and using `robolectric-processor`.

Add [android-apt](https://bitbucket.org/hvisser/android-apt) plugin and configure its `apt` extension in your `build.gradle` (`com.example.shadows` will be the package name of the generated `Shadows` class):

```gradle
buildscript {
  dependencies {
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
  }
}

apply plugin: 'android-apt'

apt {
  arguments {
    'org.robolectric.annotation.processing.shadowPackage' 'com.example.shadows'
  }
}

dependencies {
  apt 'org.robolectric:robolectric-processor:3.0'
}
```

Add `@Resetter` annotation to a `public static void()` method of your Shadow class:
```java
import android.support.design.widget.Snackbar;
import org.robolectric.annotation.Resetter;

@Implements(Snackbar.class) public class ShadowSnackbar {
 
  @Resetter public static void reset() {
     // reset your static state here
  }
}
```

Build your project and you should see a generated `com.example.shadows.Shadows` class with a helper `shadowOf` method and `META-INF/services/org.robolectric.internal.ShadowProvider` service provider's configuration file which references the generated `Shadows` class. Robolectric will load the generated class at runtime and apply your shadows. Those generated files should also end up in your artifact if you publish your custom Shadows as a library.

If you keep your custom Shadows in test scope only you can try changing the `robolectric-processor` scope to `testApt` like this:

```gradle
dependencies {
  testApt 'org.robolectric:robolectric-processor:3.0'
}
```

Hope it helps.
