### ISSUE TITLE
Use Aether API

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1073]
[Aether](http://eclipse.org/aether/) is the new hotness for repository APIs. We should switch to use it.

**Comment by jaredsburrows** [comment]
@erd, Is this still something you would like to do?

**Comment by erd** [comment]
Yes, that's why I've left it open.

**Comment by erd** [comment]
With the dependency caching and the ability to use a repository other than Maven Central, I don't think this feature is as pressing as it once was.
