### ISSUE TITLE
NullPointerException when using ValueAnimator

### ISSUE THREAD

**Issue by adamstyrc** [robolectric/robolectric#1101]
I am using an animation for my fragment to roll in from right side and push left side fragment to left by changing width and margins of their view containers (as the animation) 

A bit of code:

    private void animMarginChange(final View animatedView, final int newHorizontalMargin) {
        final LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) animatedView.getLayoutParams();
        ValueAnimator animation = ValueAnimator.ofInt(params.rightMargin, newHorizontalMargin);
        animation.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                params.leftMargin = (Integer) valueAnimator.getAnimatedValue();
                params.rightMargin = (Integer) valueAnimator.getAnimatedValue();
                animatedView.setLayoutParams(params);
            }
        });
        animation.setDuration(ANIM_DURATION);
        animation.start();
    }

When going through test I get:

java.lang.NullPointerException
	at android.animation.ValueAnimator.initAnimation(ValueAnimator.java:455)
	at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1038)
	at android.animation.ValueAnimator.end(ValueAnimator.java:964)
	at org.robolectric.shadows.ShadowValueAnimator.start(ShadowValueAnimator.java:59)
	at android.animation.ValueAnimator.start(ValueAnimator.java)
	at pl.araneo.farmadroid.view.MasterDetailLayout.animMarginChange(MasterDetailLayout.java:102)

Is ValueAnimator not supported by Robolectric ? If not, are there any plans to handle it ?

**Comment by erd** [comment]
This should be fixed by 1bfabfee74bbf76693e0ac1aac02feabba6f36ed.
