### ISSUE TITLE
NPE when getSystemService called in a Service instance

### ISSUE THREAD

**Issue by lsycxyj** [robolectric/robolectric#1105]
When I tried to call getSystemService in a Service instance, it threw a NPE. It's called in onCreate:

```
Vibrator  vibrator = (Vibrator) getSystemService(VIBRATOR_SERVICE);
```

And I created the Service instance like this:

```
@Test
public void test() throws Exception{
        FooService service = new FooService();
        service.oncreate();//NPE in this line
        //... intent declaration
        service.onStartCommand(intent, 0, 1);
}
```

But when I tried to modify my original code from getSystemService, which was called by the Service instance itslef, to xxApplication.getSystemService(XXX), which was called by application, it didn't throw any Exception.
So, how can I test a service properly without modifying my original code?
Thank you very much.

**Comment by yfaway** [comment]
It helped me with similar issues. Thanks very much.
