### ISSUE TITLE
ContentResolver only reads string literal for authority from manifest.

### ISSUE THREAD

**Issue by emir-hasanbegovic** [robolectric/robolectric#1149]
### strings.xml
```xml
 <string name="authority">my_authority</string>
```
### AndroidManifest.xml
```xml
<provider
    android:name=".MyProvider"
    android:authorities="@string/authority"
    android:exported="false" />
```
### MyTest.java
```java
final ContentResolver contentResolver = Robolectric.getShadowApplication().getContentResolver();

final ArrayList<ContentProviderOperation> contentProviderOperations = getContentProviderOperations();
final Resources resources = mContext.getResources();
final String authority = resources.getString(R.string.authority);

try {
    contentResolver.applyBatch(authority, contentProviderOperations);
} catch (RemoteException e) {
    fail(e.getMessage());
} catch (OperationApplicationException e) {
    fail(e.getMessage());
}
```

## Expected 
We expect that the provider gets instantiated and that the batch gets applied

## Actual
Inside `ShadowContentResolver.java` in the `private static ContentProvider getProvider(String authority)` method when the call to `manifest.getContentProviders()` returns, the `ContentProviderData`'s authority is "@string/authority" and not "my_authority" and therefore the provider never gets created and the apply batch never occurs

**Comment by erd** [comment]
Consolidating this into #1329.
