### ISSUE TITLE
Broadcast permissions resolution

### ISSUE THREAD

**Issue by roman-mazur** [robolectric/robolectric#1184]
Current implementation of `sendBroadcast(intent, permission)` seems to compare the passed permission with what is passed to `registerReceiver(..., permission, ...)`, which is wrong.

In the first case we specify what permission must be used by packages that receive a broadcast (what is set in `uses-permission`).
In the second case we specify what permission must be used by a sender (it's actually the same as declaring a `permission` attribute of receiver element in the manifest).

And it's wrong to assume that these permissions should match: `<uses-permission>` element and `android:permission` attribute are different things.

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
