### ISSUE TITLE
Shadow parcel, unable to read values

### ISSUE THREAD

**Issue by georgepapas** [robolectric/robolectric#1190]
Robolectric 2.3 

I have simple test case which obtains a parcel, writes a string then reads from the parcel.

The read always returns null.  Looking into this a little, it seems that ShadowParcel$ByteBuffer always returns null due to the index always equalling the buffer size, causing the this condition to always return null.

```
 T value = (index < buffer.size()) ? (T) buffer.get(index++).second
          : defaultValue;
```

Or am I just missing something obvious?

**Comment by mttkay** [comment]
I just bumped into this. Why is ShadowParcel so stateful? It looks overdone. I believe the Parcel contract is: you read what you write. Isn't this as simple as keeping a `Stack` for every type you write, which you push onto in the writer method and pop from in the reader method?
