### ISSUE TITLE
Configuration MavenCentralImpl?

### ISSUE THREAD

**Issue by emilesvt** [robolectric/robolectric#1192]
As in most organizations, we have our own Maven repo (a Nexus instance) and block all outgoing traffic to public repos like repo1 or oss at Sonatype.  We had jobs failing due to the downloading of dependencies failing because there was no .m2/settings.xml with the appropriate configuration, nor was Robolectric honoring the repo configuration in the Gradle script.

Is there a way to configure which repo to leverage for Robolectric and if not, it should probably be introduced in some fashion.

**Comment by erd** [comment]
I know this is old but you should be able to do this by creating a custom test runner and override `getJarResolver` to return a `DependencyResolver` that points to your local Nexus instance. Take a look at `MavenDependencyResolver` for inspiration.

**Comment by erd** [comment]
I know this is old but you should be able to do this by creating a custom test runner and override `getJarResolver` to return a `DependencyResolver` that points to your local Nexus instance. Take a look at `MavenDependencyResolver` for inspiration.
