### ISSUE TITLE
Inconsistent notification getContentTitle/getLatestEventInfo behavior

### ISSUE THREAD

**Issue by kschults** [robolectric/robolectric#1199]
I have a test that looks something like

```
@Test
public void test() {
    doThings();

    Notification notification = notificationManager.getNotification("MY_TAG", 3);

    ShadowNotification shadowNotification = Robolectric.shadowOf(notification);
    Assert.assertEquals("Title!", shadowNotification.getContentTitle());
    Assert.assertEquals("Title!", shadowNotification.getLatestEventInfo().getContentTitle());
}
```

When I run the full test suite, the first assert fails because `getContentTitle()` returns `null`. (And the second succeeds if I remove the first.) However, if I run just the single file with this test, the second assert fails because `getLatestEventInfo()` returns `null`.

**Comment by jaredsburrows** [comment]
@kschults When is the last time you have tried this?

**Comment by kschults** [comment]
It's been a while. November/December probably. I'm not in a situation where I can test it out anytime soon, unfortunately.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
