### ISSUE TITLE
Constructor used to create Looper in ShadowLooper does not initialize all internal state

### ISSUE THREAD

**Issue by battags** [robolectric/robolectric#1201]
One of my applications has some code to enable StrictMode and that code throws a null pointer exception when under test.

I've traced it to the fact that some internal state is not set when Robolectric creates a Looper.  According to ShadowLooper, it uses the default constructor:
https://github.com/robolectric/robolectric/blob/master/src/main/java/org/robolectric/shadows/ShadowLooper.java#L39

which does not initialize a number of internal variables that StrictMode references.

I created my own ShadowLooper that uses the constructor that takes a boolean:
private static Looper createNewLooper() {
        try {
            final Constructor<Looper> c = Looper.class.getConstructor(boolean.class);
            return c.newInstance(false);
        } catch (final Exception e) {
            throw new RuntimeException(e);
        }
    }

This eliminated the NullPointerException that was being thrown (since it actually initializes the internal variables). There's probably some optimizations that can be done (i.e. not attempting to find the constructor each time that method is called, etc.)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
