### ISSUE TITLE
null fields in a PackageInfo

### ISSUE THREAD

**Issue by karlicoss** [robolectric/robolectric#1210]
I have a code which gets the info about content providers in runtime:

```
PackageManager packageManager = getPackageManager();
PackageInfo packageInfo = packageManager.getPackageInfo(getPackageName(), PackageManager.GET_PROVIDERS);
ProviderInfo[] providers = packageInfo.providers;
```

The problem is despite the content providers do load and work correctly, the packageInfo does not seem to store any info about them, so the `providers` variable is `null` which results in a NPE later. If I run the code not under the Robolectric (version 2.3), but on a device, everything works just fine and the `providers` variable does store info about providers.

It actually happens not just to content providers, but to activities, services, receivers and all that stuff. So, it's a bug in Robolectric, right? I could even try to fix that and make a pull request, but I want to be sure first :) I could also post a minimal example if you need to.

**Comment by mukherjis** [comment]
I have a fix for this issue sitting the pull request: https://github.com/robolectric/robolectric/pull/1456
