### ISSUE TITLE
Support testing "isFromAndroidSdk" classes

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1237]
The Google Maps team would like to be able to test code under the following packages com.google.android.maps & com.google.android.gms but these are determined to be "from android sdk" here:-

https://github.com/robolectric/robolectric/blob/97f217806c29ac3a9d82adf7cb06d8ef4a3fe0d6/src/main/java/org/robolectric/bytecode/Setup.java#L86

It is possible to over ride this method in a custom subclass of Setup that we provide by overriding RobolectricTestRunner.createSetup() but I'm wondering if we could make this more configurable (e.g: on @Config annotation), passing the android SDK packages through the constructor of Setup (then we just need to override RobolectricTestRunner.createSetup() passing in the packages through the constructor. Or maybe we just decide not to shadow these classes at all and perhaps users should just use mockito for these dependencies?

Thoughts on how to proceed?

**Comment by erd** [comment]
We've made this a lot better by splitting out all non-core Android shadows into separate packages. You can also configure things at a more fine grained level via `InstrumentationConfiguration.Builder`.
