### ISSUE TITLE
FragmentTransaction.replace() with a custom animation does not quite work

### ISSUE THREAD

**Issue by dhleong** [robolectric/robolectric#1258]
Using the support lib and AssertJ-Android this sort of test works fine:

``` java
        activity.onSignInFailed();
        assertThat(frags).hasFragmentWithTag("signin");

        final SigninFragment frag = getFragment(activity, "signin");

        frag.signIn();

        assertThat(frags)
            .doesNotHaveFragmentWithTag("signin")
            .hasFragmentWithTag("signedin");
```

so long as the transaction looks like:

``` java
        getSupportFragmentManager().beginTransaction()
            .setTransitionStyle(FragmentTransaction.TRANSIT_FRAGMENT_FADE)
            .replace(R.id.container, fragment, tag)
            .commit();
```

However, if I use `setCustomAnimations` instead of `setTransitionStyle`, the old fragment remains in the `FragmentManager` and doesn't seem to even get torn down. I should be able to work around this by subclassing and overriding the method that does the replace, but filing this here to hopefully save others from some headaches here.

I'm using a 2.4 snapshot

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
