### ISSUE TITLE
Resource.obtainTypedArray returns empty array

### ISSUE THREAD

**Issue by samuelcai** [robolectric/robolectric#1283]
I'm using 2.3 (Update: tried 2.4 snapshot at 9/25, still same issue)
Let's say I define two arrays in a xml:

```
<integer-array name="site_ids">
        <item>@integer/site_id1</item>
        <item>@integer/site_id2</item>
</integer-array>
<array name="site_icons">
        <item>@drawable/site_icon1</item>
        <item>@drawable/site_icon2</item>
</array>
```

I can get the site_ids array without problem, but getting site_icons returns empty array:
Robolectric.application.getResources().getIntArray(R.array.site_ids); //returns an array with 2 items
Robolectric.application.getResources().obtainTypedArray(R.array.site_icons); //no crash, but return empty array

**Comment by adamos486** [comment]
I'm seeing this in Robolectric 3.0. Is there any eta on when this will be addressed? Or even a simple workaround?

**Comment by guitcastro** [comment]
+ 1

**Comment by andretietz** [comment]
+1

**Comment by luckcoolla** [comment]
+1
org.robolectric:robolectric:3.0

For both arrays length is 0:

    <array name="slide_need_show_logo">
        <item>0</item>
        <item>0</item>
        <item>0</item>
        <item>0</item>
        <item>0</item>
        <item>0</item>
        <item>0</item>
    </array>

    <string-array name="slide_title">
        <item>@string/slide_0_title</item>
        <item>@string/slide_1_title</item>
        <item>@string/slide_2_title</item>
        <item>@string/slide_3_title</item>
        <item>@string/slide_4_title</item>
        <item>@string/slide_5_title</item>
        <item>@string/slide_6_title</item>
    </string-array>

**Comment by OleksandrKucherenko** [comment]
Robolectric 3.1.4 - issues is still not fixed
