### ISSUE TITLE
Robolectric with OkHttp's SPDY Support

### ISSUE THREAD

**Issue by rossimo** [robolectric/robolectric#1285]
How can I can configure Robolectric to make OkHttp's SPDY support available? It seems the crux of the issue is that the "com.android.org.conscrypt.OpenSSLSocketImpl" class isn't available during OkHttp's platform detection. Is there something I can configure to make that class available for Robolectric tests?

**Comment by erd** [comment]
The latest version of 3.0-SNAPSHOT uses an android-all jar that includes SPDY support for KitKat and Lollipop.
