### ISSUE TITLE
Combining Contenprovider with addOnAccountsUpdatedListener

### ISSUE THREAD

**Issue by weiznich** [robolectric/robolectric#1314]
I try to query a content provider, that also implements addOnAccountsUpdatedListener. The Listener itself query also the contentprovider if he is called. This causes a stackoverflow because recursive calling. 

It seems like robolectric is creating a new contentprovider and accountmanager on each query.

[Stacktrace](http://zero.azapps.de/?fcd76cb274aae437#XpdaIvkXngpG3shi69ThBdZxsNNg63eHBgSn3iQhIxI=)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
