### ISSUE TITLE
Robolectric pausing looper on worker thread

### ISSUE THREAD

**Issue by santialvarezcolombo** [robolectric/robolectric#1319]
Hi! I have been using Robolectric for a while now and find it really amazing. I don't know if this is a bug, I can't find the way to make it work, or if simply you didn't intend Robolectric to work this way. 

I am working on a multithreaded Java library (with android dependencies). For my tests, I create a HandlerThread which has its own Looper. When I want to get a handler to handleMessages using the Looper of the HandlerThread, messages are never received. I've tried calling:

``` java
Robolectric.runBackgroundTasks();
Robolectric.runUiThreadTasksIncludingDelayedTasks();
```

But as expected, nothing happened. I've also tried to unpause the looper, but this does nothing as well.

Is this the expected behaviour of Robolectric? Why does it stops Loopers of a thread that is not the main?

Thank you.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
