### ISSUE TITLE
registerReceiver doesn't work with spy

### ISSUE THREAD

**Issue by sailesha** [robolectric/robolectric#1320]
Doing registerReceiver doesn't work with Mockito spy. For example:
  Foo spy = Mockito.spy(new Foo());
  Robolectric.application.registerReceiver(spy, filter);
  Robolectric.application.unregisterReceiver(spy);
Result:
  Exception that spy was never registered.

registerReceiver is registering the original object and not the spy.

**Comment by jaredsburrows** [comment]
@sailesha  When is the last time you have tried this? What is the status?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
