### ISSUE TITLE
ShadowProgressDialog getMessage returns empty String.

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#1327]
Hello, my issue seems related to #536
I have a progress dialog declared with 

    private void displayProgressBar() {
        progressDialog = new ProgressDialog(this);
        progressDialog.setCancelable(false);
        progressDialog.setMessage("message");
        progressDialog.setTitle("title");
        progressDialog.setIndeterminate(true);
        progressDialog.show();
    }

("this"  is an activity).

In my robolectric tests, I am calling

ProgressDialog progressDialog = (ProgressDialog) ShadowProgressDialog.getLatestDialog();
ShadowProgressDialog shadowProgressDialog = Robolectric.shadowOf(progressDialog);

then when running shadowProgressDialog.getMessage(); and shadowProgressDialog.getTitle();
the title one returns back the correct String, but the message one returns an empty String ("");

**Comment by jy-z-cheng** [comment]
Depends on the progress style, the ProgressDialog sets the message differently.

From android.app.ProgressDialog:
```
@Override
public void setMessage(CharSequence message) {
    if (mProgress != null) {
        if (mProgressStyle == STYLE_HORIZONTAL) {
            super.setMessage(message);
        } else {
            mMessageView.setText(message);
        }
    } else {
        mMessage = message;
    }
}
```

As a result, we need to mirror this logic in our shadow. `ShadowProgressDialog.getMessage()` should call `ShadowAlertDialog.getMessage()` when the progress style is horizontal, and get the message from the message view if the progress style is horizontal.
