### ISSUE TITLE
Support for String resources in manifest

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#1329]
Hello,

I have a receiver registered like this in my androidmanifest.xml file :

```
    <receiver android:name="com.follower.service.verification.SmsReceiver">

        <intent-filter>
            <action android:name="@string/sms_received_action"/>
        </intent-filter>
    </receiver>
```

and in a separate file i keep my intent like this :

```
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="sms_received_action">android.provider.Telephony.SMS_RECEIVED</string>
        </resources>
```

This works with android, but it doesn't seem to work with robolectric as calling the 

 shadowApplication.getReceiversForIntent(intent);  doesn't return anything.

(where intent is the intent with action "android.provider.Telephony.SMS_RECEIVED")

**Comment by athkalia** [comment]
Any updates on this ?

**Comment by zachmccormick** [comment]
Great catch!  I'll put this on my to-do list for the weekend.  I sort of
forgot about this mini project

--
Zach McCormick
317-443-2799

**Comment by jaredsburrows** [comment]
@zachmccormick What is the status of this? I have never had an issue with meta data in the `AndroidManifest.xml`.

**Comment by zachmccormick** [comment]
Not sure - I haven't tested this in a while, but I remember it not resolving resource references in fields that should support it.  Unfortunately I don't have time to test this again anytime soon :-(

**Comment by athkalia** [comment]
Same here, last time I checked it wasn't working, probably on robo 2.4

**Comment by jaredsburrows** [comment]
For sure I know that the `@integer/google_play_services_version` works as all my applications use it.

@erd @athkalia  @zachmccormick  We can close this issue if you only see that issue.

I have not tested the receiver.

**Comment by nebiros** [comment]
Any news on this one?. I'm facing it right now, seems like robolectric can't handle `resValue`s, this is my config:

```groovy
// build.gradle
resValue "string", "APP_NAME", "Blah (qa)"
```
```
// AndroidManifest.xml
<application
      android:name=".BlahApp"
      android:allowBackup="true"
      android:icon="@mipmap/ic_launcher"
      android:label="@string/APP_NAME"
      android:theme="@style/BlahTheme">
```

And this is the exception:
```
android.content.res.Resources$NotFoundException: no such label com.ride.playstore.staging:string/APP_NAME
```

I found a workaround here: http://michiganlabs.com/android-resources-generated-gradle-resourcesnotfoundexception-robotlectric-testing/#.VyD1SKMrK34, but is an ugly one, :(.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-


testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}


We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.
