### ISSUE TITLE
Robolectric failing to delete tmp files

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#1330]
We are seeing that the tmp folder after Robolectric has run is cluttered with temporary files that are never deleted.  This is Robolectric 2.3, and I've attached an image that shows this.   This is a long over due followup to the google group posting.

https://groups.google.com/d/msg/robolectric/wNLwX-smxU0/qciMORMAIrIJ

We are having to resort to running a cron job on the build machine to remove these files.

![image](https://cloud.githubusercontent.com/assets/177042/4723491/1845cb72-5948-11e4-8f5b-f63ad457ef9c.png)

**Comment by snakelizzard** [comment]
Still reproduced for 3.0-rc2

**Comment by hbjastad** [comment]
This bug has clearly not been fixed - why was it closed?
