### ISSUE TITLE
Problems with Annotation processor with incremental builds

### ISSUE THREAD

**Issue by kriegfrj** [robolectric/robolectric#1366]
The Robolectric Annotation Processor is set up to generate all of the boilerplate `shadowOf()` methods that provide the compile-time type safety. However, I didn't convert the Robolectric code base to use these yet - they are still using the hand-generated methods in `org.robolectric.Robolectric`.

One of the main reasons for this is because while working on source within Eclipse, incremental builds are happening & RAP was getting invoked for these incremental builds. This was useful because you can see any constraint violations pretty much immediately & they appear in your IDE. 

The problem is that it seemed on each of these incremental build runs it would also regenerate the source file. Because RAP was not designed to build this file incrementally, it recreates the whole file from scratch each time - which means it only incorporates the `shadowOf()` methods for the shadows that happened to be processed on that run. This obviously broke any other dependent classes that were using the `shadowOf()` methods for any other shadows. So as you were working on one part of the code, the incremental compilation would break for other parts of the code until you did a full rebuild.

Upon reflection, the global generated `reset()` method will also get redefined each time. This will be less obvious because it won't result in a compile error as the `reset()` method will always be generated (even if empty) - however, it could result in mysterious test failures for any tests that rely on static state being reset. Again, this won't be a problem when building from scratch (eg, in Travis), but could present problems to the developer as they are working on a project if they are using incremental building.

I'm assuming that similar problems will exist for IDEA.

A couple of possible solutions to this issues:

* Find a way to turn off the source code generation for incremental builds.
* Find a way to support incremental generation for the generated source code.

The first is probably the simplest, but will require a manual intervention to rebuild the sourcce any time changes are made that will affect the generated source. Fortunately this doesn't happen often (and won't happen at all except for developers working *on* Robolectric, as opposed to developers merely using Robolectric).

The second would be the best option as it would reduce or eliminate the need for manual interventions. However, I'm not sure how difficult it would be to set this up. It could be as simple as adding persistence to `RoboModel` to preserve state between builds. We'd also need to add a "clean" command so that the persistent state can be cleared if desired - eg, by running `mvn clean`. Having just now thought this through it doesn't seem as difficult as it might have at first.

I'll try and look at this in the next week or so, but I thought I'd raise it as an issue in case anyone else was having some problems as a result.

**Comment by erd** [comment]
I don't think I've ever run into this with IntelliJ. Is this still an issue for you? We did move the codebase to use the generated `shadowOf` methods everywhere. Maybe that was the difference?

**Comment by kriegfrj** [comment]
The difference was when I was trying to get validation, generation and compilation all to work in the same compilation phase. I since realised that this couldn't work due to the dependency on the generated code, and so a separate generate-sources was a necessary prerequisite anyway.

An incremental annotation processor would theoretically speed up incremental builds which might in turn speed up development. and might be useful at some point. However
