### ISSUE TITLE
ShadowColor's parseColor doesn't work with 'black'

### ISSUE THREAD

**Issue by Rave-Yori-Kvitchko** [robolectric/robolectric#1370]
Trying to parseColor on 'black' gives error. Robolectric tries to parse it as "#llaacckk". Culprit is likely this code:

Line 15 in ShadowColor

if (colorString.charAt(0) == '#' && colorString.length() == 4 || colorString.length() == 5) {

Probably needs parenthesis around the two length checks.

**Comment by danielrees18** [comment]
@erd This issue has been resolved with #1523
