### ISSUE TITLE
ClassCastException on test setup

### ISSUE THREAD

**Issue by bspeice** [robolectric/robolectric#1385]
Hello all,

I don't know if I'm just building my activities in a strange way, but I'm getting a ClassCastException trying to start an activity (ActionBarActivity). The stack trace is below:

```
java.lang.ClassCastException: java.lang.ExceptionInInitializerError cannot be cast to java.lang.RuntimeException
    at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:68)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
    at org.robolectric.util.ActivityController.create(ActivityController.java:111)
    at org.robolectric.util.ActivityController.create(ActivityController.java:122)
```

I've created a [branch](https://github.com/MinimalBible/MinimalBible/tree/9e638859843ce0b941b44d38fb4f203b5dead71a) for the code that's currently triggering the issue. Please run `./gradlew test` in order to reproduce.

The test in question is just trying to start an activity, and add a fragment, but errors out before we can get to the fragment. I'm sure I'm doing something wrong, but I believe it should still be qualified as a bug that I am getting another exception, instead of the original being thrown.

The test itself is available [here](https://github.com/MinimalBible/MinimalBible/blob/9e638859843ce0b941b44d38fb4f203b5dead71a/app-test/src/test/java/org/bspeice/minimalbible/test/activity/downloader/BookListFragmentTest.java), with the Activity in question [here](https://github.com/MinimalBible/MinimalBible/blob/9e638859843ce0b941b44d38fb4f203b5dead71a/app/src/main/java/org/bspeice/minimalbible/activity/downloader/DownloadActivity.java). All links have the exact commit ID specified.

Additionally, it should likely be noted that Robolectric is testing activities that exist in a separate Gradle module. I don't think this would cause an issue, as everything compiles (so all the references are valid) but that might be useful information.
Happy to help however I can.

**Comment by mttmllns** [comment]
Really seems odd to me that a `gradlew clean ; gradlew testDebug` fails but `gradlew clean testDebug` doesn't.  What am I not understanding about gradle?

Hoping Xavier has some input: https://code.google.com/p/android/issues/detail?id=78090
