### ISSUE TITLE
getNextStartedActivity() also returns activities started with startActivityForResult()

### ISSUE THREAD

**Issue by RomainGx** [robolectric/robolectric#1388]
Since there are 2 methods available, `getNextStartedActivity()` and `getNextStartedActivityForResult()`, I would have expected that `getNextStartedActivityForResult()` would only return intents of activities launched with `startActivityForResult()`, and `getNextStartedActivity()` only intents of activities launched with `startActivity()`.
So all is OK for `getNextStartedActivityForResult()`, but not `getNextStartedActivity()`. Indeed, `getNextStartedActivity()` also returns activities launched with `startActivityForResult()`.

Is it a bug or a feature? :)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
