### ISSUE TITLE
Missing Annotation functions

### ISSUE THREAD

**Issue by PatrickMcAfee** [robolectric/robolectric#1402]
When I call Config.annotationType(), I get a NoSuchMethodError.  The annotationType() function is part of the base Annotation in the JDK (https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Annotation.html) and should be getting inherited automatically.  I've confirmed from the classfile that the method is straight up missing.  Any idea what's going on here, or am I missing something?

I'm using the latest libraries from maven.

**Comment by PatrickMcAfee** [comment]
Turned out to be related to a separate library I was using.  Sorry for letting this languish so long, I just saw it and remembered.

**Comment by erd** [comment]
No worries! Thanks for closing this!
