### ISSUE TITLE
Set exception level for logs?

### ISSUE THREAD

**Issue by charlesmunger** [robolectric/robolectric#1412]
There are lots of cases where libraries and engineers are calling Log.w and Log.e (and occasionally Log.wtf) for error cases - how do we feel about adding a parameter to @Config that takes a log level, for which any log messages at or above it would throw an AssertionError?
```
@Config(exceptionLevel = Log.WARN)
public class SampleTest {
    @Test
    public void doSomethingDangerous() {
        Log.e(TAG, "Uh oh! Error condition!");
    }
}
```

That code is a passing test case today, but would be a failing one with my proposal.

**Comment by jaredsburrows** [comment]
I agree with @JakeWharton, for logging you can do the following:

1. Set your `robolectric.properties` for logging/debugging  - http://robolectric.org/configuring/
2. Do what @athkalia does with `-Drobolectric.logging=stdout`
3. You can do what I do, add to your `allProjects`:

    // print errors from test in the terminal
    tasks.withType(Test) {
        testLogging {
            exceptionFormat 'full'
        }
    }

4. Run your tests with `gradlew test --info`

@charlesmunger Can we close this? @erd

**Comment by erd** [comment]
I'm not a fan of adding yet another attribute to the @Config annotation. I think Jake's callback based approach would be better.
