### ISSUE TITLE
AsyncTask shadow does not behave as expected for get() with timeout

### ISSUE THREAD

**Issue by mehmetf** [robolectric/robolectric#1428]
I have a code path where I rely on AsyncTask.get(0 millis) to determine whether the task has executed or not. A timeout exception in my case is okay since it just means execution is pending.

When testing this functionality, I was surprised to see that my tests were hanging. I traced the code and found that SimpleFuture object simply waits forever until the task has run. That is exactly the opposite of get with timeout intention: https://github.com/robolectric/robolectric/blob/master/robolectric-utils/src/main/java/org/robolectric/util/SimpleFuture.java#L44

IMO, this code should be:

``` java
if (!hasRun) {
  this.wait(unit.toMillis(timeout));
  if (!hasRun) {
    throw new TimeoutException();
  }
}
return result;
```

Please let me know about the rationale about this if it was by design.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
