### ISSUE TITLE
openRawResource() returns null for library resources

### ISSUE THREAD

**Issue by nolanlawson** [robolectric/robolectric#1430]
If you have an app that depends on a library, and that library tries to call `openRawResource(R.raw.some_file_in_the_library)`, then it will return null.

I have a sample app/library to reproduce this, but I'll create the issue first so I can link back to it.

I'm using Robolectric 2.4.

**Comment by tigerpenguin** [comment]
I am also seeing this in 3.0 as well. I think this is due to the way library resources are merged during compile time. For the quick and dirty fix, the method below seems to work (from https://github.com/robolectric/robolectric/issues/1070)

In your custom test runner, set the res directory to the generated/merged directory
```
@Override
    protected AndroidManifest getAppManifest(Config config) {
        String manifest = "src/test/AndroidManifest.xml";
//        String res = "src/main/res";
        String res = "../app/build/intermediates/res/staging/debug";
        String asset = "src/main/assets";
        return new AndroidManifest(Fs.fileFromPath(manifest), Fs.fileFromPath(res),
                Fs.fileFromPath(asset));
    }
```
You'll replace whatever build flavor/type you are using in the above code for the res directory (in my case, staging/debug), but you'll actually see all the raw files there if you browse that folder. I am hoping this will be fixed in Robolectric so we don't have to do this (or if there's a way to fix it that I don't know, please share!).

**Comment by gabrielmoreira** [comment]
I resolved for my case. It's because org.robolectric.manifest.AndroidManifest#getRClassName

AndroidManifest are doing this:
```java
rClassName = packageName + ".R";
```
But my package name is changed on gradle ```applicationIdSuffix '.debug'```

So, in my custom RobolectricGradleTestRunner, im doing this:
```java

public class CustomRobolectricRunner extends RobolectricGradleTestRunner {

   ...

   protected AndroidManifest getAppManifest(Config config) {

      ...

      return new AndroidManifest(androidManifestFile, resDirectory, assetsDirectory) {
            @Override
            public String getRClassName() throws Exception {
               return br.com.myapp.R.class.getName();
            }
         };
  }
}
```

**Comment by fernandocamargoti** [comment]
Thanks, @gabrielmoreira, I had the same problem. I think Robolectric should handle this case. It's not rare to use a package sufix.

**Comment by Dima564** [comment]
+1

**Comment by RyanNewsom** [comment]
I ran into this issue on a library module today. This workaround was posted by @ymka [here](https://github.com/dlew/joda-time-android/issues/37#issuecomment-75898305) and I made very slight modifications. I couldn't get the custom RobolectricTestRunner to work but this is working for me.
1) create a resources folder in app/src/test/ and place your resource file there
   - make sure you don't put it in app/src/java or it will not work

```java 
InputStream in = this.getClass().getClassLoader().getResourceAsStream("myFile.json");
        Context context = mock(Context.class);
        Resources resources = mock(Resources.class);
        when(resources.openRawResource(anyInt())).thenReturn(in);
        when(context.getResources()).thenReturn(resources);
```

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.
