### ISSUE TITLE
Bundle#getParcelable returns actual type instead of Parcelable[]

### ISSUE THREAD

**Issue by WonderCsabo** [robolectric/robolectric#1440]
Take the following code:

``` java
// Activity 1

Intent intent = new Intent(this, Activity2_.class);
intent.putExtra("accounts", new Account[] { new Account("Robo", "superuser") });

startActivity(intent);

// Activity 2

Account[] accounts = (Account[]) getIntent().getParcelableArrayExtra("accounts");
```

This fails on a real device because `getParcelableArrayExtra` returns a `Parcelable[]` and not an `Account[]`. However, on a `Robolectric` test, this passes, because an object of type `Account[]` is returned (AFAIK the same object is returned which was put in the first place).

Actually i would expect Android to return the desired type, but Roboletric should mimic the real behavior and return `Parcelable[]` here.

**Comment by WonderCsabo** [comment]
I just checked the code for `ShadowBundle`, and it seems it totally relies on the real `Bundle` behavior, so i do not know why Robolectric does not work like Android code. But as you can [see](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.2_r1/android/os/Parcel.java#Parcel.readParcelableArray%28java.lang.ClassLoader%29), `getParcelableArray` indeed returns a `Parcelable[]` and not `SubClass[]` (like Robolectric do).

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
