### ISSUE TITLE
Is it possible to test Abstract Activity?

### ISSUE THREAD

**Issue by glebPrischepa** [robolectric/robolectric#1441]
Hey, I am getting InflateException while testing Activity.

For example,

I have an Android library project. It is called "AndroidLibrary".
There is an abstract Activity. It is called "MyAbstractActivity".
This Activity does all hard work. UI is populated here.

Also, there is another project "ChildProject" that uses that "AndroidLibrary".
There is "ChildActivity" that extends "MyAbstractActivity" and has a few overriden methods.
And does not populate UI at all.

I am trying to test ChildActivity using Robolectric.
I use config
***
@Config(manifest = "..//ChildProject//AndroidManifest.xml")
// Robolectric finds this manifest file successfully.
***
I am getting issue when next line is being performed
Robolectric.buildActivity(ChildActivity.class).create().get();

Robolectric throws InflateException.
I see that Robolectric is trying to inflate view by path "..//ChildProject//res//..AndroidLibrary//res//layout//home.xml".

Obviously this path is incorrect. That is why I am getting exception.

Does it make sense?
Is there any workaround to test such Activity (ChildActivity)?
Could you suggest me another way?

Thanks in advance.
Looking forward to your replies.

**Comment by erd** [comment]
This should be fixed by switching to `RobolectricGradleTestRunner` in 3.0.
