### ISSUE TITLE
Support for test-only resources

### ISSUE THREAD

**Issue by jhansche** [robolectric/robolectric#1442]
I may have missed this somewhere in the documentation, but so far have not found anything in the Robolectric API or documentation to explain the correct way to do this.

I'm trying to test a few isolated layout scenarios, and I'd like to define those layouts in XML as they would be in the app, but I do not need the test-only layouts to exist in the main app.  Placing the files into `src/test/res/layout/foo.xml` does not cause the layout to be available via `R.layout.foo`.  In internal robolectric tests, test layout files are found in `src/test/resources/res/layout/foo.xml`, but I still don't see how those XML files become accessible via `R.layout`.  What is the proper way to load a test-only layout (or other resources, like drawables, etc)?  And is this documented anywhere?

**Comment by erd** [comment]
It's currently not possible to have test-only resources as this requires support from the build tools.

**Comment by ross-eskridge-lenovo** [comment]
Can you at least support debug only resources?
