### ISSUE TITLE
Support appcompat-v7

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1446]

**Comment by simtse** [comment]
Hello @erd , so I guess these fixes to the v7 ActionBarActivity will only be available in 3.0 of Robolectic and not in 2.4?

**Comment by erd** [comment]
Yes, only 3.0.

**Comment by nenick** [comment]
The old depricated ActionbarDrawerToggle used android.R.attr.homeAsUpIndicator instead of R.id.home
So a workaround which works for me is to shadow this class and use the original attr value.

    import android.content.res.TypedArray;
    import android.graphics.drawable.Drawable;
    import android.support.v7.app.ActionBarDrawerToggle;

    import org.robolectric.RuntimeEnvironment;
    import org.robolectric.annotation.Implements;

    @Implements(ActionBarDrawerToggle.class)
    public class ShadowActionBarDrawerToggle {

        public Drawable getThemeUpIndicator() {
            final TypedArray a = RuntimeEnvironment.application.obtainStyledAttributes(new int[]{android.R.attr.homeAsUpIndicator});
            final Drawable result = a.getDrawable(0);
            a.recycle();
            return result;
        }
    }

**Comment by LeFrenchTouch** [comment]
Thanks a ton for documenting a fix nenick!!

**Comment by karlicoss** [comment]
Sorry, I don't really get it guys.. Has any `ActionBarActivity` support been implemented and merged into 3.0-SNAPSHOT?

**Comment by nenick** [comment]
ActionBarActivity and Robolectric works together. Here is a basic example https://github.com/robolectric/robolectric-samples/tree/master/android-appcompat-v7

**Comment by erd** [comment]
@karlicoss Yes, it should work. Please open issues for anything you find in appcompat that doesn't work as you'd expect.

**Comment by karlicoss** [comment]
Thanks for the link guys, I managed to localize the problem. I was getting weird FileNotFoundExceptiions while inflating the layout for ActionBarActivity, turns out, inflating is ok, the problem is rather in the `<include layout=.../>` tag. I'll open an issue or make a PR once I investigate that.

**Comment by ajhuntsman** [comment]
FYI - I filed a new issue re: ActionBarActivity with 3.0-SNAPSHOT: https://github.com/robolectric/robolectric/issues/1636

**Comment by yousufsyed** [comment]
It worked for me a after updating the following in the build.gradle file:
dependencies {
    .....
    compile 'com.android.support:appcompat-v7:22.0.0'
    .....
}

android {
....
    buildToolsVersion '21.1.2'
.....
}

**Comment by hidroh** [comment]
@karlicoss I'm having the same problem with FileNotFoundException when using `<include layout=.../>` tag as well. Did you manage to work around it?

**Comment by karlicoss** [comment]
@hidroh not really. Didn't have much time to investigate, so I just inlined this layout. I have a separate flavor for robolectric tests in my project, so it didn't affect the production code, just some copy-pasting, but it was only a single test that caused crashes, so it's not that bad (at least, yet).
