### ISSUE TITLE
When SharedPreferences instance is a static, Robolectric cannot restore key/values

### ISSUE THREAD

**Issue by mikerott** [robolectric/robolectric#1458]
Say my Activity class looks like this, with "prefs" field being static, and therefore initialized only on the first constructor call (like a singleton might be):

    public class TestActivity extends Activity {
	
    	private static SharedPreferences prefs;

    	@Override
    	public void onCreate(Bundle savedInstanceState) {
    		super.onCreate(savedInstanceState);
    		if (prefs == null) {
    			prefs = this.getApplicationContext().getSharedPreferences("MyPrefs", Context.MODE_PRIVATE);
    		}
    	}
    	
    	public String getSharedPrefValue(final String key) {
    		return prefs.getString(key, null);
    	}

    }

And my test is as such:

    @Config(emulateSdk = 18)
    @RunWith(RobolectricTestRunner.class)
    public class OneTest {
    	
    	private TestActivity activity;
    	
    	@Before
    	public void setup() throws Exception {
    		
    		activity = Robolectric.buildActivity(TestActivity.class).create().get();
    		
    		SharedPreferences prefs = Robolectric.application.getSharedPreferences("MyPrefs", Context.MODE_PRIVATE);
    		SharedPreferences.Editor editor = prefs.edit();
    		editor.putString("someKey", "someValue");
    		editor.commit();
    
    	}
    
    	@After
    	public void tearDown() throws Exception {
    		SharedPreferences prefs = Robolectric.application.getSharedPreferences("MyPrefs", Context.MODE_PRIVATE);
    		prefs.edit().clear().commit();
    	}
    	
    	@Test
    	public void test1() {
    		assertEquals("someValue", activity.getSharedPrefValue("someKey"));
    	}
    	
    	@Test
    	public void test2() {
    		assertEquals("someValue", activity.getSharedPrefValue("someKey"));
    	}
    	
    }

The second test will fail.  I have not yet inspected Robolectric source to see how this scenario could be supported.  Reason I need it is because of what I alluded to above; we have singletons that hold a prefs field, effectively making the prefs field a static.

Any way to support this?

Robolectric 2.4, JUnit 4.9, Android 5.0.

**Comment by JakeWharton** [comment]
You have written your activity in a way that is not conducive to testing. I don't think Robolectric needs changed, I think your application needs changed. In your example there is absolutely no reason for that variable to be static.

**Comment by mikerott** [comment]
I don't disagree.  :)  I won't claim it's good code.  What I showed is an example of the legacy code I now want to test.  The legacy is that the prefs field is held in a singleton, which effectively makes it a static.  Certainly I can refactor, but in the meantime, it would be nice for Robolectric to support this case.  Your thoughts?

**Comment by JakeWharton** [comment]
This requires that a different class loader be used for each test method. Certainly not impossible, Robolectric is already doing classloader isolation for replacing the `android.*` classes. I believe JUnit has a way for you to run individual tests in a forked JVM which would allow this? I would have to do some searching for that though. Plus it will dramatically slow down your execution time.

**Comment by mikerott** [comment]
I poked around.  You can indeed specify forkMode="perTest", but only via surefire plugin (in maven) or the junit task (in ant).  No way to do it in junit annotations or in the Eclipse launch configuration.  Meh, it's due for a refactoring anyway.  :)

Thanks for the quick replies and good advice... and awesome test framework!
