### ISSUE TITLE
Fix bug when using a custom android namespace prefix than "android"

### ISSUE THREAD

**Issue by christophpickl** [robolectric/robolectric#1461]
when defining a manifest XML with some namespace prefix which differs from the common "android" one like this ``<manifest xmlns:a="http://schemas.android.com/apk/res/android"/>``, instead of ``<manifest xmlns:android="http://schemas.android.com/apk/res/android"/>``, roboelectric will crash with a NPE:

    java.lang.NullPointerException
	at org.robolectric.manifest.AndroidManifest.resolveClassRef(AndroidManifest.java:385)
	at org.robolectric.manifest.AndroidManifest.parseActivity(AndroidManifest.java:233)
	at org.robolectric.manifest.AndroidManifest.parseActivities(AndroidManifest.java:212)
	at org.robolectric.manifest.AndroidManifest.parseAndroidManifest(AndroidManifest.java:152)

the __reason__ is obviously that the code is expecting the prefix to be always "android":

    String activityName = resolveClassRef(activityAttrs.get(ActivityData.getNameAttr("android")));

    private String resolveClassRef(String maybePartialClassName) {
        return (maybePartialClassName.startsWith(".")) ? packageName + maybePartialClassName : maybePartialClassName;
    }

__proposed solution__: dynamically parse the defined prefix and use that instead of the hardcoded values.

i've already implemented the solution in this commit:
https://github.com/christophpickl/robolectric/commit/9616ca8e32f8f99ea42b4a2efab5c62a89771513

also fixed a minor bug in ActivityData (using hardcoded "android" value instead of constructor passed value, which was required for the original bugfix):
https://github.com/christophpickl/robolectric/commit/5ce4299c9b3a014382b24dcdffd797ab441327b9

**Comment by jaredsburrows** [comment]
## The view:

    <?xml version="1.0" encoding="utf-8"?>
     <LinearLayout xmlns:a="http://schemas.android.com/apk/res/android"
        a:orientation="vertical"
        a:layout_width="fill_parent"
        a:layout_height="fill_parent">
        <com.example.view.MyTextView
            a:id="@+id/myTextView"
            a:layout_width="wrap_content"
            a:layout_height="wrap_content"/>
    </LinearLayout>

## The Test:

	@Test
	public void testOne() {
		Activity activity = Robolectric.buildActivity(Main.class).create().get();
		
		MyTextView subject = (MyTextView) activity.findViewById(R.id.myTextView);
		assertNotEquals(null, subject);
	}

@christophpickl This is no longer an issue in Robolectric 3.0-rc3. We can close this @erd.

**Comment by christophpickl** [comment]
great, much appreciated! thank you.
oh, yeah... how stupid of me not to test first ;)

**Comment by jaredsburrows** [comment]
@christophpickl @erd Can you close this issue?

**Comment by christophpickl** [comment]
done
