### ISSUE TITLE
Environment Variables Unused

### ISSUE THREAD

**Issue by niedzielski** [robolectric/robolectric#1477]
Setting environment variables have no effect. I have a test, `FooTest`, in a module, `foo-module` which I execute like so:

    gradle --debug -Dtest.single=FooTest -Drobolectric.logging=stdout :foo-module:test

  `robolectric.logging=stdout` is not passed to the tests. Setting the property in a test runner works fine:

    public class TestRunner extends RobolectricTestRunner {
        static {
            System.setProperty("robolectric.logging", "stdout");
        }

        public TestRunner(Class<?> testClass) throws InitializationError {
            super(testClass);
        }
    }

I'm using [android-unit-test](https://github.com/JCAndKSolutions/android-unit-test) which may also be contributing to the problem.

**Comment by erd** [comment]
The gradle test plugin needs to pass the environment variables to the JVM running the tests. Please open an issue against the android-unit-test project.
