### ISSUE TITLE
Unable to test custom attributes with RoboAttributeSet

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1478]
I'm trying to test custom button class with own attributes.

Here is example of the test project:
https://github.com/emartynov/RobolectricIssue

Here is test class that fails:
https://github.com/emartynov/RobolectricIssue/blob/master/app/src/test/java/com/bijdorpstudio/myapplication/CustomButtonTest.java

Note:
If I would be able to debug I would provide better information. How do you debug Robolectric with AndroidStudio?

**Comment by andrewlord1990** [comment]
I have used `RoboAttributeSet` with custom attributes before and it works fine.

Please be aware I am using slightly different Robolectric syntax to you as you are using an older version of Robolectric. First thing I would do is try updating to Robolectric 3.0 to see if that fixes it.

See what I have in my test below:

```java
private static final String PACKAGE = "com.example";


Resources resources = RuntimeEnvironment.application.getResources();
ResourceLoader resourceLoader = Shadows.shadowOf(resources).getResourceLoader();

List<Attribute> attributes = new ArrayList<>();
attributes.add(new Attribute(PACKAGE + ":attr/myCustomDrawableAttribute", "@drawable/my_drawable_image", PACKAGE));
attributes.add(new Attribute(PACKAGE + ":attr/myCustomIntegerAttribute", "1", PACKAGE));
attributes.add(new Attribute(PACKAGE + ":attr/myCustomTextAttribute", "message", PACKAGE));

AttributeSet attributeSet = new RoboAttributeSet(attributes, resourceLoader);
MyCustomView view = new MyCustomView(RuntimeEnvironment.application, attributeSet);

assertThat(view.getCustomNumberView().getText().toString()).isEqualTo("1");
assertThat(view.getCustomTextView().getText().toString()).isEqualTo("message");
```

I have simplified the code, as it is separated across different methods in reality.

The main difference I can see is how the `RoboAttributeSet` has been created, I create it from the attributes and the `ResourceLoader`. Hopefully, either an update to Robolectric 3.0 or by changing how you create the `RoboAttributeSet` should get this working for you.

**Comment by xian** [comment]
This should work if you use `Robolectric.buildAttributeSet()` I believe... please reopen if not.

**Comment by LeiWangAndroid** [comment]
Hi, @xian , 

I have tried with new way `Robolectric.buildAttributeSet()`, but somehow it will never get value for CustomAttribute, but works fine for Android attribute, for example
`
        val roboAttributeSet = Robolectric.buildAttributeSet()
                .addAttribute(android.R.attr.text, titleString)
                .addAttribute(R.attr.sc_messageText, messageString)
                .build()

        val typedArray = context.obtainStyledAttributes(roboAttributeSet, intArrayOf(android.R.attr.text, R.attr.sc_messageText))
        Assert.assertEquals(typedArray.getString(1), messageString)`

In here, the result for `typedArray.getString(1)` will be always `null`

I am on Robolectric 4.3.1, not sure what is wrong here, please help, thanks.
