### ISSUE TITLE
Context.getDir() fails because applications data dir is not created

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1485]
The following commit partially exposes this bug:-
https://github.com/robolectric/robolectric/commit/15c1a6e605dce93123442f71e8f543d321592556

However, the Robolectric tests pass because the bug is obscured because ShadowContextTest.setup() calls context.getFilesDir().listFiles(); which creates the data directory. If this code is removed from setup tests will fail.

The contract of Context.getDir() is that it will return a directory under the applications data directory as defined by ApplicationInfo.dataDir and create the directory if it doesn't exist. It shouldn't require calling context.getFilesDir() before hand.

**Comment by erd** [comment]
Should be fixed by #1489.
