### ISSUE TITLE
DateUtils.formatDateTime() incorrectly returning null

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1492]
DateUtils.formatDateTime() is incorrectly returning null, this can be traced down to DateIntervalFormat.formatDateRange() which is returning null.

This is working at https://github.com/jongerrish/robolectric/commit/4493afc2be0859035a5b22bb98a6e9a97f9ff63a but failing at head.

Root cause is that native method: libcore.icu.DateIntervalFormat#formatDateInterval() is being called and returning null.

Below shows two tests that expose it, first is through DateUtils, the second is through DateInterval

@RunWith(TestRunners.WithDefaults.class)
public class ShadowDateUtilsTest {
  
  @Test
  public void DateUtils_FormatDateTime() {

    String actual = DateUtils.formatDateTime(RuntimeEnvironment.application, 1420099200000L, DateUtils.FORMAT_NUMERIC_DATE);

    assertEquals("1/1/2015", actual);
  }

  @Test
  public void testDateInterval_FormatDateRange() {

    String actual = DateIntervalFormat.formatDateRange(Locale.getDefault(), TimeZone.getDefault(), 1420099200000L, 1420099200000L, DateUtils.FORMAT_NUMERIC_DATE);

    assertEquals("1/1/2015", actual);
  }
}

**Comment by jongerrish** [comment]
We'll also need to implement this as a velocity template, since DateIntervalFormat was only introduced in KitKat. In JB the formatting is done in Java:-

https://github.com/android/platform_frameworks_base/blob/jb-mr2-release/core/java/android/text/format/DateUtils.java#L865

Interestingly enough if I set @Config(emulateSdk = 18) then the code still fails returning a null value, I'm not sure why and I'm not sure how to switch the source jars out to Jelly Bean when debugging in tests.

**Comment by jongerrish** [comment]
This is the commit that switched to ICU implementation:- https://github.com/android/platform_frameworks_base/commit/6139e64cd6f86c4e3983de976cb0aa976b0d313c

**Comment by erd** [comment]
Should be fixed by #1498.
