### ISSUE TITLE
Provide an option for disabling SmsManagerShadow in the build

### ISSUE THREAD

**Issue by gruszczy** [robolectric/robolectric#1505]
Our apps don't link to SmsManager code and so we can't import SmsManager. Most of the time it doesn't cause problems, but when using Shadows.shadowOf() it won't build, because it imports SmsManager. It would be great to have an option when building your own version of Robolectric jars, to now include SmsManager code.

**Comment by erd** [comment]
I'm hesitant to add this feature since SmsManager is in the public SDK.

**Comment by gruszczy** [comment]
The proposal goes like this: by default Robolectric would build everything, as it is now and that's what would go into your official release jar. So, nothing changes here.

The build flag/option would allow to disable ShadowSmsManager (or maybe better, any Shadow you want, but let's not go too crazy), so if your Android flavor doesn't include SmsManager, you can use the flag/option to disable it. Please consider the fact, that we might not be able codebase that decides to have reduced sdk. Any other developer that takes AOSP and builds for his device without including SmsManager, will encounter the same issue. Missing SmsManager is never an issue for developers that build for phones (which are probably 99.9% of users), but for custom Android builds that build against real sources, like us, it is.

**Comment by erd** [comment]
I don't think there's enough of a benefit to add this type of feature. If you want to omit a shadow, or change what's included in Robolectric, I would suggest maintaining a private fork of the project.
