### ISSUE TITLE
Handler.postDelayed(Runnable, int) doesn't respect the delay

### ISSUE THREAD

**Issue by gruszczy** [robolectric/robolectric#1509]
I have an activity that in onCreate calls:

mHandler.postDelayed(mRunnable, 60000);

When I run a robolectric test and call Robolectric.setupActivity(..), the runnable is immediately run. This is unfortunatey, because the runnable finishes the activity. The delay should be respected.

**Comment by gruszczy** [comment]
Maybe this is a wrong description of the problem. Unless I pause the main looper, the handler will be run independent of the delay. The problem is, if the looper is paused, broadcast don't seem to be delivered. I need to do the following:

       ShadowLooper.unPauseMainLooper();
        ShadowApplication.getInstance().sendBroadcast(intent);

I tried remove ShadowLooper.unPauseMainLooper() and instead of that calling idleMainLooper (with or without interval), and runUiThreadTasks, but neither gets the broadcast delivered to my receiver. Am I doing something wrong?

**Comment by jaredsburrows** [comment]
Can you take a look at Robolectric 3 and the the AsyncTaskTest here: https://github.com/robolectric/robolectric/blob/c19dbbca184afbea5bb74c260e44f90104e696e6/robolectric/src/test/java/org/robolectric/shadows/ShadowAsyncTaskTest.java.

Try pausing:

    Robolectric.getBackgroundThreadScheduler().pause();
    Robolectric.getForegroundThreadScheduler().pause();

Then run your post handler.

Then:

ShadowApplication.runBackgroundTasks();

Try to use the new APIs.

**Comment by erd** [comment]
> When I run a robolectric test and call Robolectric.setupActivity(..), the runnable is immediately run. This is unfortunatey, because the runnable finishes the activity. The delay should be respected.

After you create an `Activity` the loopers are set to idling. This means that any runnable posted will be run immediately. The delay is respected in that runnables with a shorter delay will be run first, but the loopers do not respect the delay in terms of wall-clock time. If you don't want runnables to be automatically run, you can pause the loopers. I realize that this is very different from how real Android works. We're looking at overhauling the schedulers in #1879.

> The problem is, if the looper is paused, broadcast don't seem to be delivered.

That's new to me.

**Comment by gruszczy** [comment]
Hmm.. It seems that since January I changed the tests. There is other issue I am facing that seems related to scheduling. I have a view with looping animation that gets started when it gets attached to the window. When the animation finishes, it immediately starts itself.

In my test the first three lines are:
        ShadowLooper.pauseMainLooper();
        Robolectric.getForegroundThreadScheduler().pause();
        Robolectric.getBackgroundThreadScheduler().pause();
after which I setup the activity. This triggers the animation to go into an endless loop. Do I need to do something more to pause the animations?

**Comment by kriegfrj** [comment]
There are known problems with animation which we think are related to the scheduling core. #1879 is hopefully going to address them.

**Comment by kriegfrj** [comment]
@gruszczy, I think that the issue you raised in the OP might have been resolved by PR #1891. Are you in a position to try this out and see if it fixes your issue?

**Comment by gruszczy** [comment]
I'm afraid not any more, I moved away from the project that used Robolectric.

**Comment by erd** [comment]
Fixed by #1891.
