### ISSUE TITLE
Resources not being imported while testing library depending on another library

### ISSUE THREAD

**Issue by vekexasia** [robolectric/robolectric#1515]
Hello there, i've 2 project libraries. 
- "mainlib"
- "corelib"

"mainlib" depends on "corelib" and "corelib" also contains some "strings" .. 

While launching tests on mainlib all the (corelib).R.strings aren't accessible. If i switch "mainlib" from "com.android.library" to "com.android.application" all the tests works just fine :)

Is this the intended behavior ?

**Comment by serj-lotutovici** [comment]
I'm getting the same error... any progress on this issue?

**Comment by serj-lotutovici** [comment]
Also I've noticed that when running the tests form Android Studio it works, but from the terminal it throws a `java.lang.ClassNotFoundException`

**Comment by vekexasia** [comment]
Make it a com.android.application and it will work fine :)

**Comment by serj-lotutovici** [comment]
Yea, but this is not the behaviour I'm expecting... The library module should remain a library...

**Comment by commjoen** [comment]
I have the same issue. I have a module which I want to test (android Library) and it depends on the zxing libraries. But it only gives me the `java.lang.ClassNotFoundException`

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.
