### ISSUE TITLE
Support native libraries in tests

### ISSUE THREAD

**Issue by xgouchet** [robolectric/robolectric#1516]
I'm using Robolectric to perform test on an Android Application, and a couple of classes use NDK for a few methods. 

When I try to write tests for those methods, I get an UnsatisfiedLinkError : 

    java.lang.UnsatisfiedLinkError: no "foo" in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
        at java.lang.Runtime.loadLibrary0(Runtime.java:849)
        at java.lang.System.loadLibrary(System.java:1088)
        at com.foo.MyClass.<clinit>(MyClass.java:45)

How can I tell Robolectric where to find the natif libfoo.so library ? 

I'm working with Android Studio 1.0.2, robolectric:2.3 on a Debian 64 computer

**Comment by erd** [comment]
> How can I tell Robolectric where to find the natif libfoo.so library ?

We don't currently support loading native libs in a test.

**Comment by erd** [comment]
Consolidating this into #1171.
