### ISSUE TITLE
Getting OOM error

### ISSUE THREAD

**Issue by mnbsharma** [robolectric/robolectric#1521]
Hi I am getting OOM error when using robolectric-2.0-alpha-3...

Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] java.lang.OutOfMemoryError: GC overhead limit exceeded
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at java.util.BitSet.initWords(BitSet.java:166)
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at java.util.BitSet.<init>(BitSet.java:161)
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at com.android.dx.ssa.SsaBasicBlock.<init>(SsaBasicBlock.java:127)
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at com.android.dx.ssa.SsaMethod.makeNewGotoBlock(SsaMethod.java:239)
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at com.android.dx.ssa.SsaBasicBlock.insertNewSuccessor(SsaBasicBlock.java:453)
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at com.android.dx.ssa.SsaConverter.edgeSplitSuccessors(SsaConverter.java:249)
Error:Android Pre Dex: [robolectric-2.0-alpha-3-20130412.000302-32-jar-with-dependencies.jar] at com.android.dx.ssa.SsaConverter.edgeSplit(SsaConverter.java:136)

**Comment by erd** [comment]
2.0-alpha-3 is more than two years old. Please upgrade to something newer.

**Comment by jongerrish** [comment]
Also, why are you running Dex on the robolectric jar? Robolectric runs on
the JVM and shouldn't be dexed.
