### ISSUE TITLE
Build 3.0 error

### ISSUE THREAD

**Issue by PawelKozela** [robolectric/robolectric#1524]
Hi guys,

I'm getting a strange error while trying to install - like a dll does not exist, however, when I check, it's well there:

Results :

Failed tests:
  SQLiteLibraryLoaderTest.shouldExtractNativeLibrary:44
Expecting file:<C:\Users\Pawel\AppData\Local\Temp\robolectric-libs\sqlite4java.dll> not to exist
  ShadowResourcesTest.getThemeValueShouldSupportDereferenceResource:425 expected:<-1677[7216]> but was:<-1677[6961]>
  ShadowResourcesTest.getThemeValueShouldSupportNotDereferencingResource:439 expected:<[1717044]4> but was:<[6656]4>

Tests in error:
  SQLiteLibraryLoaderTest.shouldRewriteExistingLibraryIfThereAreChanges:73 » FileNotFound
  ShadowContextTest.getDatabasePath_shouldAllowAbsolutePaths:161 » IllegalArgument

Any idea ?

**Comment by erd** [comment]
I think the tests are just flaky. I've seen `ShadowContextTest.getDatabasePath_shouldAllowAbsolutePaths` fail from time to time.
