### ISSUE TITLE
getLastSentTextMessageParams always returns null when sent using sendMultipartTextMessage

### ISSUE THREAD

**Issue by Ridermansb** [robolectric/robolectric#1530]
I'm trying to create a test where I need to catch the last sent message (recipient mainly)

Sent 

    smsManager.sendMultipartTextMessage(recipient, null, messageParts, null, null);

However shadowSmsManager.getLastSentTextMessageParams(); always returns null

when use

    smsManager.sendTextMessage(recipient, null, messageParts.get(0), null, null);

this works.

How to retrieve the last message when sent using sendMultipartTextMessage?

**Comment by erd** [comment]
This is because `sendMultipartTextMessage` is not shadowed, so the params are not available. PRs are welcome!
