### ISSUE TITLE
After Android.onCreateOptionsMenu() returns false, Fragment.onOptionsItemSelected() is not being called.

### ISSUE THREAD

**Issue by WojciechKo** [robolectric/robolectric#1545]
I have Activity with single Fragment.
In Activity I create `delete` and `save` menu. `delete` menu is handled by `MyActivity` and `save` menu in `MyFragment`.
Problem is when I call in test:  

    activity.onOptionsItemSelected(new RoboMenuItem(R.id.menu_save));

It doesn't call Fragment.onOptionsItemSelected() after return false like it does on Android device.
The same with `TestMenuItem` from 2.4 and `RoboMenuItem` from 3.0-SNAPSHOT
Am i doing something wrong, or is it a bug?

### MyActivity:  

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        if (savedInstanceState == null) {
            getSupportFragmentManager()
                    .beginTransaction()
                    .replace(R.id.container, MyFragment.newInstance())
                    .commit();
        }
    }
    
    
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.action_delete, menu);
        getMenuInflater().inflate(R.menu.action_save, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean result = super.onOptionsItemSelected(item);
        if (item.getItemId() == R.id.menu_delete) {
            onDeleteOptionSelected();
            return true;
        }
        return result;
    }
    
### MyFragment:  

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean result = super.onOptionsItemSelected(item);
        if (item.getItemId() == R.id.menu_save) {
            onSaveOptionSelected();
            return true;
        }
        return result;
    }

**Comment by erd** [comment]
Could you try replacing the call to:

    activity.onOptionsItemSelected(new RoboMenuItem(R.id.menu_save));

with 

    shadowOf(activity).clickMenuItem(R.id.menu_save)

(assuming you're using 3.0-SNAPSHOT). I would suggest avoiding `RoboMenuItem` since it's a completely fake implementation of `MenuItem`.

**Comment by erd** [comment]
Are you calling `setHasOptionsMenu(true)` on your `Fragment` instance?
