### ISSUE TITLE
PreferenceManager.getDefaultSharedPreferences causes NPE

### ISSUE THREAD

**Issue by eygraber** [robolectric/robolectric#1547]
After updating to the 3.0 Snapshot, my RobolectricTestRunner's TestLifecycle (DefaultTestLifecycle) createApplication returns an Application that when used to make a call to PreferenceManager.getDefaultSharedPreferences(app), causes a NPE. Running the same code in Robolectric 2.4 does not throw the NPE.

**Comment by jenzz** [comment]
Any updates on this? Or is there a temporary workaround we can use to avoid the crash?

**Comment by jaredsburrows** [comment]
@eygraber  Any update?

**Comment by eygraber** [comment]
Haven't revisited this in a few months

**Comment by jaredsburrows** [comment]
@jenzz @eygraber This works just fine:

    @Test
    public void test_getDefaultSharedPreferences() {
        PreferenceManager.getDefaultSharedPreferences(RuntimeEnvironment.application);
    }

@erd We can close this.
