### ISSUE TITLE
Cannot compile tests that call `Shadows.shadowOf(...)` in 3.0-SNAPSHOT

### ISSUE THREAD

**Issue by jhansche** [robolectric/robolectric#1549]
It seems that any test that attempts to call `Shadows.shadowOf()` for a supported object type (e.g., `View`) fails to load the `Shadows` class because of some classes that are `@hide` in the Android platform.  The errors are similar to:

    /path/to/MyTest.java:184: error: cannot access ActivityThread
            Assert.assertTrue(shadowOf((View) mView).didRequestLayout());
                              ^
      class file for android.app.ActivityThread not found

The cast of `(View) mView` was added only to show that it's actually a View object, and should be calling `Shadows.shadowOf(View)`.  I'm not accessing `ActivityThread` at all, but looking at the class in the IDE, it is documented as `@hide`, and it cannot be accessed from within my application code.  Opening the Shadows class in the IDE also shows several errors related to the classes that cannot be loaded, including `ActivityThread`.

The same error occurs for other calls to `shadowOf()`, each with a different problem class:

    /path/to/MyTest.java:184: error: cannot access ActivityThread
            Assert.assertTrue(shadowOf((View) mView).didRequestLayout());
                              ^
      class file for android.app.ActivityThread not found
    /path/to/MyTest.java:193: error: cannot access AlertController
            ShadowAdapterView shadow = shadowOf(mView);
                                       ^
      class file for com.android.internal.app.AlertController not found
    /path/to/MyTest.java:211: error: cannot access DisplayManagerGlobal
            shadowOf(mView).performItemClick(2);
            ^
      class file for android.hardware.display.DisplayManagerGlobal not found
    /path/to/MyTest.java:222: error: cannot access EmojiFactory
                    transcript.add("onItemClick " + shadowOf(view).innerText() + ", " + position + ", " + id);
                                                    ^
      class file for android.emoji.EmojiFactory not found
    /path/to/MyTest.java:227: error: cannot access GeoPoint
            shadowOf(mView).performItemClick(2);
            ^
      class file for com.google.android.maps.GeoPoint not found
    /path/to/MyTest.java:239: error: cannot access ItemizedOverlay
                    transcript.add("onItemClick " + shadowOf(view).innerText() + ", " + position + ", " + id);
                                                    ^
      class file for com.google.android.maps.ItemizedOverlay not found
    /path/to/MyTest.java:289: error: cannot access WindowManagerImpl
            assertThat(Shadows.shadowOf(v.findViewById(R.id.ad_container)).innerText()).isEmpty();
                              ^
      class file for android.view.WindowManagerImpl not found
    /path/to/MyTest.java:305: error: cannot access WindowManagerGlobal
            assertThat(Shadows.shadowOf(v.findViewById(R.id.ad_container)).innerText()).isEqualTo("1, MREC_1, UNKNOWN");
                              ^
      class file for android.view.WindowManagerGlobal not found

These tests compiled fine in robolectric 2.4, using `Robolectric.shadowOf(...)`.  Is there something else that I missed in the [2.4-to-3.0 migration](https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide-%28Draft%29)?

**Comment by jhansche** [comment]
I also tried bumping the android gradle plugin version to 1.1.0-rc2, using robolectric-gradle-plugin 1.0.0-SNAPSHOT, and the same errors occur during compile.

**Comment by erd** [comment]
Are you sure you're using the most recent 3.0-SNAPSHOT? This issue should have been fixed over a month ago. We should only be generating shadowOf methods for classes that are public in the Android SDK (anything that is annotated with @Implements(isInAndroidSdk = false) won't generate a shadowOf method).

**Comment by jhansche** [comment]
Hmm, then no I'm not sure -- I just updated my dependency to 3.0-SNAPSHOT.  I'll clear out my local cache and resync to make sure I'm getting the latest snapshot.  Will follow up once I can test that out.

**Comment by jhansche** [comment]
You're right.. I must have had a cached artifact in ~/.m2/repository.  Cleared that out, and it grabbed the latest files.  Now getting an error on `org.apache.maven.wagon.ResourceDoesNotExistException` while running the unit tests:

```
    Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'org.robolectric:shadows-core:jar:19': Cannot find parent: org.robolectric:robolectric-shadows for project: null:shadows-core:jar:null for project null:shadows-core:jar:null
      org.robolectric:shadows-core:jar:3.0-SNAPSHOT

    from the specified remote repositories:
      sonatype (https://oss.sonatype.org/content/groups/public/),
      central (http://central)

    Path to dependency:
    	1) org.apache.maven:super-pom:pom:2.0

        Caused by:
        org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.robolectric:shadows-core:jar:19': Cannot find parent: org.robolectric:robolectric-shadows for project: null:shadows-core:jar:null for project null:shadows-core:jar:null
          org.robolectric:shadows-core:jar:3.0-SNAPSHOT

        from the specified remote repositories:
          sonatype (https://oss.sonatype.org/content/groups/public/),
          central (http://central)

        Path to dependency:
        	1) org.apache.maven:super-pom:pom:2.0

            Caused by:
            org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file for artifact 'org.robolectric:shadows-core:jar:19': Cannot find parent: org.robolectric:robolectric-shadows for project: null:shadows-core:jar:null for project null:shadows-core:jar:null

                Caused by:
                org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.robolectric:robolectric-shadows for project: null:shadows-core:jar:null for project null:shadows-core:jar:null

                    Caused by:
                    org.apache.maven.project.ProjectBuildingException: POM 'org.robolectric:robolectric-shadows' not found in repository: Unable to download the artifact from any repository

                      org.robolectric:robolectric-shadows:pom:3.0-SNAPSHOT

                    from the specified remote repositories:
                      sonatype (https://oss.sonatype.org/content/groups/public/),
                      central (http://central)

                     for project org.robolectric:robolectric-shadows

                        Caused by:
                        org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

                          org.robolectric:robolectric-shadows:pom:3.0-SNAPSHOT

                        from the specified remote repositories:
                          sonatype (https://oss.sonatype.org/content/groups/public/),
                          central (http://central)

                            Caused by:
                            org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
```

Is Robolectric trying to fetch artifacts from Maven at runtime?  ¬_¬

**Comment by erd** [comment]
Yes - Robolectric fetches a version of android-all and the matching shadows at runtime. The shadow fetching is new, but Robolectric has fetched the android-all jar at runtime since ~2.0.

**Comment by jhansche** [comment]
So what would cause this to suddenly start failing in 3.0 then?  I have a corporate nexus server configured in my `~/.m2/settings.xml` and in my build.gradle.  So I shouldn't have to hit oss.sonatype.org at all (that repo is already configured as a proxy in my nexus server).

The root of the problem though, from what I can tell, is that the oss-parent versions available in oss.sonatype are 8 and 9.  But this is trying to fetch version "7", and that can't be found.

**Comment by erd** [comment]
> Also, with the new unit test support in 1.1.0, Android is already adding the mockableAndroid.jar to the classpath, so we shouldn't be adding android-all anymore (only if using 1.1.0, of course).

Using the mockable android.jar is a completely separate thing from using Robolectric.
