### ISSUE TITLE
ShadowApplication.setComponentNameAndServiceForBindService supports only one Binder

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#1561]
In the case where your test-case will require multiple ServiceConnection, all of them will get the same Binder.
This is because (org/robolectric/shadows/ShadowApplication.java:283): 
  serviceConnection.onServiceConnected(componentNameForBindService, serviceForBindService);
does not map the ServiceConnection with a specific `Intent`

**Comment by erd** [comment]
It looks like this was resolved with the above commits. Please re-open if this is not the case.
