### ISSUE TITLE
Robolectric 3.0-SNAPSHOT with AppCompat-v7:21 runs about 3x slower than without AppCompat

### ISSUE THREAD

**Issue by shekibobo** [robolectric/robolectric#1566]
I'm not sure if the problem is coming from AppCompat or from Robolectric's implementation of the AppCompat APIs, but here has been my experience so far:

1. Upgrade to Robolectric 3.0-SNAPSHOT -> Tests still run at a reasonable speed
2. Following the [material design guide](http://android-developers.blogspot.com/2014/10/appcompat-v21-material-design-for-pre.html) by changing my `FragmentActivity`s to `ActionBarActivity`s and using `getSupportActionBar()` instead of `getActionBar()` -> Test run about 3 times slower (up from 8 minutes for 700 tests to 24 minutes)

Regular non-robolectric tests appear to be running at normal speed. If I can provide any more information that will be useful let me know.

**Comment by erd** [comment]
In order to make AppCompat work, we had to implement more realistic resource loading. The resource loading causes more disk io and make your tests slower.

**Comment by kingargyle** [comment]
@erd can any type of caching be implemented.  We noticed a big slowdown when going from Robolectric 2.3 to 2.4, and hearing that there is even more slowdown when going to 3.0 makes me hesistant to do an upgrade.  We sped some things up by running with a forkCount = 2, but that isn't solving the underlying issue.

**Comment by jongerrish** [comment]
I think we should profile it and see what the hot spots are. I can probably
take a look t this when I'm back from my vacation. Its super important to
us as well, or if you're able to do it and post some results that would be
helpful.

**Comment by kingargyle** [comment]
One potential sore point we have found in at least 2.4 has been around Robolectric.buildActivity().  On average it takes about 400ms to just do a simple, Robolectric.buildActivity(FragmentActivity).create().get().    Tests around Fragments have similar performance issues as well.

We've taken to trying to use Mockito when possible to Mock the Activities or Fragments, but it isn't always possible or you end up writing a ton of mock matchers to handle the conditions.

**Comment by erd** [comment]
Consolidating this into #1601 (which is more general).
