### ISSUE TITLE
Mocking System.currentTimeMillis

### ISSUE THREAD

**Issue by solganik** [robolectric/robolectric#1590]
Hi, I`m using robolectric 2.4 with mockito.
During testing of my App, I need to set time in order to test time specific functionality.
From what i had observed from the sources of robolectric, especially ShadowWrangler class, calls to 
System.currentTimeMillis sould be intercepted, and provided via ShadowSystemClock, but it did not work for me.
I had also tried with robolecric and powermockito, but could not make it working, even with 
powermock-classloading-xstream.

Thanks.

**Comment by pjakubczyk** [comment]
Wrap System.currentTimeMillis to TimeProvider (or any other name) class. Then Mock the provider. much easier

**Comment by sasha-stratoscale** [comment]
Hi it would help for source that is under my control, but wont help in case that the call is originated from jars i`m using.

**Comment by erd** [comment]
> From what i had observed from the sources of robolectric, especially ShadowWrangler class, calls to 
> System.currentTimeMillis sould be intercepted, and provided via ShadowSystemClock, but it did not work for me.

This is true for 3.0, but not 2.4. `InstrumentingClassLoader` had a bug where the return value of intercepted methods in `ShadowWrangler` were not being honored.

**Comment by erd** [comment]
ShadowSystemClock should work correctly in 3.0-SNAPSHOT, so I'm going to close this. If you still have issues after upgrading to 3.0, please re-open.

**Comment by tmrudick** [comment]
Still having an issue mocking currentTimeMillis with 3.0. The ShadowSystemClock methods are getting called from other shadows but not from my own code under test.

For example:
```java
@Test
public void testCurrentTime() {
    // Calls use ShadowSystemClock
    new Notification();

    // Does not call out to ShadowSystemClock
    mSomeClassUnderTest.doSomethingWithCurrentTime();
}
```

The first case uses ShadowWrangler as expected. However, in the second case, ShadowWrangler never gets invoked at all.

Any ideas about why this might be happening?
