### ISSUE TITLE
Testing for Recreate

### ISSUE THREAD

**Issue by saadfarooq** [robolectric/robolectric#1597]
How can I test in robolectric that the activity was recreated ? In the simplest form, the code might look like: 

    public void onSomeEvent(SomeEvent event) {
      // do something
      recreate();
    }

Right now, testing such a method fails saying the activity was destroyed. Is there a way to check for this ?

**Comment by kingargyle** [comment]
The way I've done this in the past is to use Mockito, and then spy on the activitity and do something link.

doNothing().when(spyActivity).recreate()

spyActivity.onSomeEvent(mockEvent)

verify(spyActivity).recreate();

Which would verify that the recreate was called.

I checked the ShadowActivity and it doesn't have a method currently for wasRecreated() or isRecreating().

**Comment by saadfarooq** [comment]
Thanks. That does work. I think the main problem was that I was trying to test it after pushing an event to a bus and spying doesn't help in that case because the original activity is registered on the bus and gets the callback.
