### ISSUE TITLE
Not able to inflate a fragment

### ISSUE THREAD

**Issue by blundell** [robolectric/robolectric#160]
Pretty simple:

LayoutInflater inflater = (LayoutInflater) getSystemService(LAYOUT_INFLATER_SERVICE);
inflater.inflate(layoutId, null);

The layoutId I'm passing resolves to:

```
<RelativeLayout
   >
    <fragment
        android:id="@+id/vehicleSummaryFragment"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        class="com.my.package.RandomFragment" />
```

   <RelativeLayout />

The error is :

Caused by: java.lang.RuntimeException: couldn't find view class fragment

The error seems to be caused by the pickViewMethod() method in the class: com.xtremelabs.robolectric.res.ViewLoader.java

The pickViewMethod() to resolve the fragment in the above XML should reference the class attribute I assume?

**Comment by Jeff-Stapleton** [comment]
I can't get this to work.  Was this ever solved?
