### ISSUE TITLE
Robolectric with Android Studio 1.1.0

### ISSUE THREAD

**Issue by guitcastro** [robolectric/robolectric#1600]
I tried to use Robolectric with the new Android Studio 1.1. Running tests using command line work fine but for the IDE Integration work we had to follow the items 3, 4 and 5 of this guide: http://tools.android.com/tech-docs/unit-testing-support.

So I think it´s a good idea to update the documentation.

**Comment by erd** [comment]
Could you please open the issue in the https://github.com/robolectric/robolectric.github.io repository?
