### ISSUE TITLE
Robolectric 2.4 test execution time is much slower than 2.3

### ISSUE THREAD

**Issue by borgelino** [robolectric/robolectric#1601]
We just upgraded to Robolectric 2.4 and have noticed our tests now take almost twice the time to run compared to 2.3.
With exactly the same code base and same Gradle task being run (also double checked that it's the same amount of tests being run - about 600),

2.3: Total time: 1 mins 54.083 secs
2.4: Total time: 3 mins 49.955 secs

Also did profiling in both scenarios and it's the 'test<variant>' task that is twice as slow, so definitely Robolectric test execution.

Other environment details,
Android grade plugin 1.1.2
Android Studio 1.1
SDK build tools 21.1.2
Android unit test feature used
Not using Robolectric Gradle plugin - have a custom test runner instead extending RobolectricTestRunner instead to support running the tests from IDE as well

Let me know what other info I can provide to help find the root cause.
Created a thread about it as well - https://groups.google.com/forum/#!topic/robolectric/AmZITpyAMzc

**Comment by erd** [comment]
If you have a chance, could you try running your tests vs 3.0-SNAPSHOT?

**Comment by kingargyle** [comment]
I haven't had time to run against 3.0 yet, but saw the same issue.  Nearly double the test time execution.  I had tracked it down to a slower performance of the ActivityController life cycle.  Taking nearly 400ms to build up an activity each time. 

One thing we did to speed up the tests from the command line was to use Maven surefires forking ability.  We fork about 4 jvms processes to run the tests, and this lets us run nearly 2000 tests in about 2 minutes using robolectric.   if we use the single jvm process, it will take nearly 9 minutes to run the same test suite.

**Comment by erd** [comment]
There was a recent commit (84b2bfacec7a140c91cf6a20eecbb54a254dd5f0) that attempted to optimize how resources were loaded. I was curious how much of an improvement it made. Things that happen in `ActivityController` are out of our control, since we are calling into Android to have it initialize an activity.

**Comment by borgelino** [comment]
I haven't had a chance to test against 3.0-SNAPSHOT yet, but will give it a go as soon as I can.
Surely something must have changed in Robolectric itself though to cause this performance degrade? We are still using the same Android jars, environment, etc - the only difference is the version of Robolectric.

**Comment by erd** [comment]
> Surely something must have changed in Robolectric itself though to cause this performance degrade?

Robolectric parses a larger variety of resources than it used to (and parses even more types of resources in 3.0-SNAPSHOT), which most likely explains the slowdown.

**Comment by erd** [comment]
There's not one thing that causes the slowdown. I'm more than happy to look at PRs that improve test run time.
