### ISSUE TITLE
AsyncTask's doInBackround() method is run on main thread

### ISSUE THREAD

**Issue by ubuntudroid** [robolectric/robolectric#1604]
Consider the following test with a synchronization lock `private final Object mSync = new Object()`:

```java
@Test
public void testAsyncInBackground () {
   synchronized (mSync) {
      new AsyncTask<Void, Void, Void>() {
         @Override
         protected Void doInBackround ( Void... params ) {
            assertThat(Looper.myLooper(), not(Looper.getMainLooper())); // results in a failure!!!
            synchronized (mSync) {
               mSync.notify();
            }
         }
      }.execute(new Void[0]);
   }
   synchronized (mSync) {
      mSync.wait();
   }
}
```

Upon running it you'll notice, that `doInBackround()` is executed on the main thread and not on a background thread. Rewriting it as follows the test succeeds:

```java
@Test
public void testAsyncInBackground () {
   synchronized (mSync) {
      AsyncTask.execute(new Runnable() {
         assertThat(Looper.myLooper(), not(Looper.getMainLooper()));
         synchronized (mSync) {
            mSync.notify();
         }
      }
   }
   synchronized (mSync) {
      mSync.wait();
   }
}
```

**Comment by RomainPiel** [comment]
I just had the same problem, this can be fixed by using `executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR)` instead of `execute()`.

**Comment by joshk0** [comment]
I'm still having this issue on robolectric 3.0 from Maven Central. Am I on crack here?

**Comment by erd** [comment]
Robolectric runs all AsyncTasks on the same thread, but enqueues the work on different queues (i.e. `getBackgroundThreadScheduler` / `getForegroundThreadScheduler`), so you can run the job synchronously and assert on the effects.

**Comment by joshk0** [comment]
If that's as-designed, is there documentation about that? The javadoc isn't especially forthcoming.
