### ISSUE TITLE
ActivityNotFoundException not thrown by startActivityForResult

### ISSUE THREAD

**Issue by martijndebruijn** [robolectric/robolectric#1615]
Robolectric does not check against the package manager when performing a startActivityForResult.

When you enable checking against the packageManager by using ShadowApplication.getInstance().checkActivities(true); only during the startActivity the check is performed and not during the startActivityForresult.

It would be great if the check could be added to the startActivityForResult too.

Related issues:
https://github.com/robolectric/robolectric/issues/693
https://github.com/robolectric/robolectric/pull/703

**Comment by jongerrish** [comment]
Yep, sounds cool. Want to send a PR?

**Comment by jongerrish** [comment]
We should probably make this the default, especially now that we process the merged manifest.

**Comment by aballano** [comment]
Hi there, I just came here for the same reason as the initial post, so I just tested in v4.3.1 and I can confirm that `shadowOf(ApplicationProvider.getApplicationContext<Application>()).checkActivities(true)` does make a call to `startActivityForResult` **from a Fragment** to crash with `ActivityNotFoundException` 👍

**Comment by utzcoz** [comment]
@aballano Thanks for pointing out that this problem is fixed by https://github.com/robolectric/robolectric/pull/703. @martijndebruijn Feel free to reopen it if latest Robolectric doesn't fix this problem.
