### ISSUE TITLE
Unable to intercept http responses in fragment

### ISSUE THREAD

**Issue by hggz** [robolectric/robolectric#1618]
I have an activity with a fragment. There's an async task inside that fragment that executes on onCreateView. I can get a reference to the fragment just fine however when I let that async task execute, I get the usual exception about no pending responses being available.

In my test I tried preventing robolectric from intercepting http requests, and I also tried adding the appropriate pendingHttpResponse with what ever should be sent back. Despite adding these two lines, I still receive the same error. Does anyone have any idea why this is happening?

Note: The http responses are made with apache's protocol so Robolectric should be able to pick these up. Also, I've tested intercepting and adding pending http responses in other activities without fragments, and it behaves as expected.

**Comment by jaredsburrows** [comment]
So you want to intercept the http responses that robolectric is intercepting? So you actually want to receive data from the your AsyncTasks instead of mocking it out or letting robolectric intercept them?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
