### ISSUE TITLE
org.robolectric.Config.properties not picked up

### ISSUE THREAD

**Issue by vkislicins** [robolectric/robolectric#1621]
I've tried the following paths with no success:
```
appname/src/test/org.robolectric.Config.properties
appname/src/test/res/org.robolectric.Config.properties
appname/src/test/resources/org.robolectric.Config.properties
```

example of my properties file:
```
manifest: aaa/AndroidManifest.xml
res: ../main/res/
```

Output in console is showing No manifest file found at ./AndroidManifest.xml with aaa nowhere to be seen

**Comment by erd** [comment]
`src/test/resources` is the right place, but I think this issue (https://code.google.com/p/android/issues/detail?id=64887) is preventing the gradle plugin from adding resources to the classpath.

**Comment by erd** [comment]
Closing this since it will be fixed in the next release of Studio.
