### ISSUE TITLE
3.0-SNAPSHOT: Theme.AppCompat.Light.DarkActionBar is not found

### ISSUE THREAD

**Issue by ajhuntsman** [robolectric/robolectric#1636]
Our tests were working fine until we upgraded our ActionBar from the deprecated v4 up to v7. So perhaps there is some other theme-related tweak we need to make, in order to accommodate Robolectric?

Our compileSdkVersion is 21. And, our Robolectric tests are in a separate module within the same project (per http://blog.blundell-apps.com/android-gradle-app-with-robolectric-junit-tests/)

```
dependencies {
        classpath 'com.android.tools.build:gradle:1.1.3'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'com.novoda:gradle-android-command-plugin:1.3.0'
        classpath 'org.robolectric:robolectric-gradle-plugin:1.0.1'
    }
```

Our MainActivity extends android.support.v7.app.ActionBarActivity. Here's the style being used:

```
<style name="AcmeHoloLight" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/white</item>
        <item name="windowActionBar">false</item>
    </style>
```

```
java.lang.RuntimeException: Could not find any resource  from reference ResName{org.acme.myapp:style/Theme_AppCompat_Light_DarkActionBar} from style StyleData{name='AcmeHoloLight', parent='Theme_AppCompat_Light_DarkActionBar'} with theme null
	at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getParent(ShadowAssetManager.java:454)
	at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getAttrValue(ShadowAssetManager.java:392)
	at org.robolectric.shadows.ShadowResources.getOverlayedThemeValue(ShadowResources.java:295)
	at org.robolectric.shadows.ShadowResources.findAttributeValue(ShadowResources.java:284)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:187)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:51)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:489)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:484)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:479)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:380)
	at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:147)
	at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:138)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
	at org.acme.myapp.activity.MainActivity.onCreate(MainActivity.java:464)
	at android.app.Activity.performCreate(Activity.java:5133)
```

**Comment by erd** [comment]
There is a working example of this in the `robolectric-samples` repo - look at `android-appcompat-v7`. I would try moving the tests into the same module as the code you are testing. I suspect that it's not able to find the resources for your app.

**Comment by nenick** [comment]
@ajhuntsman What did you mean with `separate module` is this a `application -> library` relation or `java -> application`

**Comment by ajhuntsman** [comment]
I'm using IntelliJ and Gradle. I had all of my Robolectric tests in a Java module, as a peer of my Android app module, but followed the standard packing naming convention.

Per @erd above, I just now moved my tests into my Android app module, into the `/src/test/` directory (which previously did not exist). Notably, I have an Espresso test in the `/src/androidTest/ directory`.

Now, I'm getting this warning in the console:
`WARNING: No manifest file found at ./AndroidManifest.xml.Falling back to the Android OS resources only.` and a subsequent NPE when trying to access files in `/src/test/resources`.

**Comment by erd** [comment]
> Now, I'm getting this warning in the console:
> WARNING: No manifest file found at ./AndroidManifest.xml.Falling back to the Android OS resources only.

If you're using 3.0-SNAPSHOT and Gradle, you should switch to `RobolectricGradleTestRunner`. I've added some documentation here: https://github.com/robolectric/robolectric/wiki/Running-tests-in-Android-Studio

> and a subsequent NPE when trying to access files in /src/test/resources

I believe that the Android Gradle plugin does not yet support test resources (https://code.google.com/p/android/issues/detail?id=64887). It looks like this is slated to be fixed in 1.2.

**Comment by ajhuntsman** [comment]
Thanks for the help @erd ! I'm hoping Android Gradle plugin 1.2 comes out soon; it looks like they try to publish releases every month or so.

I am getting a Gradle compile issue now for `RobolectricGradleTestRunner` and `@Config`. Is there some other Gradle dependency needed?

Also, IntelliJ seems to have lost the robolectric 3.0 dependency and when I search for it via Maven it cannot be downloaded. Is it better to check out the source, build a jar, and explicitly add it as jar library?

**Comment by nenick** [comment]
What kind of compile issue? Missing class?

**Comment by erd** [comment]
> Is it better to check out the source, build a jar, and explicitly add it as jar library?

You can always build it from source, but the easiest thing is to use the SNAPSHOT.

> Also, IntelliJ seems to have lost the robolectric 3.0 dependency and when I search for it via Maven it cannot be downloaded.

Make sure you have Sonatype's snapshot repo in your build.gradle (the exact URL is in Robolectric's README). Try refreshing your dependencies via `gradle --refresh-dependencies`.

**Comment by ajhuntsman** [comment]
Thanks guys; I ran the refresh-dependencies, and I already had the correct Sonatype repo defined for the 3.0-SNAPSHOT, but the problem remains. The compiler is only complaining about 2 Robolectric classes:

`@Config`
`RobolectricGradleTestRunner`

Here's my dependencies section, if that helps:
```
dependencies {
    // Fabric.io
    compile('com.crashlytics.sdk.android:crashlytics:2.2.0@aar') {
        transitive = true;
    }
    
    compile 'com.amazonaws:aws-android-sdk-core:2.1.10'
    compile 'com.amazonaws:aws-android-sdk-mobileanalytics:2.1.10'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:support-v4:+'
    compile 'com.android.support:support-v13:+'
    compile 'com.google.code.gson:gson:2.3'
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'org.jsoup:jsoup:1.8.1'
    compile 'javax.validation:validation-api:1.1.0.Final'
    compile 'com.android.support:support-annotations:21.0.3'

    // Robolectric
    testCompile 'junit:junit:4.10'
    testCompile 'org.apache.maven:maven-ant-tasks:2.1.3'
    testCompile ('org.robolectric:robolectric:3.0-SNAPSHOT') {
        exclude group: 'io.fabric'
    }

    // Espresso
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.0'
    androidTestCompile 'com.android.support.test:testing-support-lib:0.1'
}
```

**Comment by ralphpina** [comment]
@ajhuntsman I just had this issue. Like you, I have my robolectric tests in a separate Java module. This issue is fixed by adding a `project.properties` file to your android app under `/app/src/main/`. See #1334 for a more detail explanation.

After you fix that, you'll likely an error like this:
`java.lang.IllegalArgumentException: AppCompat does not support the current theme features`. That will be because you have `<item name="windowActionBar">false</item>` in your theme without `<item name="windowNoTitle">true</item>`. You can see the fix [here](http://stackoverflow.com/questions/29784124/java-lang-illegalargumentexception-appcompat-does-not-support-the-current-theme).
