### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by houssine91** [robolectric/robolectric#1639]
started with robolectric in android studio. I would run a simple example, but i have this error

Running tests Test running started junit.framework.AssertionFailedError: No tests found in com.example.myApp.AuthenticationActivityTest at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191) at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176) at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555) at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

## Test class ##
    @RunWith(RobolectricTestRunner.class)
    public class AuthenticationActivityTest {
    
    @Test
    public void checkAccountType() throws Exception{
        String accType = new AuthenticationActivity().getResources().getString(R.string.account_type);
        assertThat(accType,equalTo("com.example.myApp"));
    }
    }

## Gradle file ##
apply plugin: 'com.android.application'
apply plugin: 'org.robolectric' //Robolectric

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.example.myApp"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'LICENSE.txt'
    }
    }
    dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    androidTestCompile 'junit:junit:4.12' //Robolectric
    androidTestCompile 'org.robolectric:robolectric:2.4' //Robolectric
    }

**Comment by senkir** [comment]
You can check your configuration from the command line to see if gradle itself is setup correctly or if it's Android Studio.  If it doesn't run from the command line you'll need to add any missing plugins for gradle support. (such as robolectric's own https://github.com/robolectric/robolectric-gradle-plugin ).

If the command line is working but android studio isn't, then it's your run configuration for junit.  make sure your package and working directories point to your unit tests.

**Comment by houssine91** [comment]
I created a test that extends ActivityInstrumentationTestCase2 (without robolectric). When I run tests with `./gradlew connectedAndroidTest`, I cannot get in the output directory the result of robolectric tests (i got only the tests without  robolectric)

**Comment by erd** [comment]
Please take a look at the samples repository if you want to see a working setup (https://github.com/robolectric/robolectric-samples). Please note that the samples are based on 3.0-SNAPSHOT.

**Comment by IgnacioGarcia198** [comment]
Reproduced it by subclassing a parent test class, but it is only reproduced when running tests from the terminal like ./gradlew build

```
@RunWith(AndroidJUnit4::class)
open class DatabaseTest {
    protected lateinit var db: StoreDatabase

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(
            context, StoreDatabase::class.java
        )
            .build()
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        db.close()
    }

    @Test
    @Ignore("just avoiding")
    fun dummyTest() {}
}
```

Subclasses of this test reproduce the issue when run from the terminal if you remove the dummyTest I added.
