### ISSUE TITLE
Snapshot builds are currently broken

### ISSUE THREAD

**Issue by nenick** [robolectric/robolectric#1643]
Until now the dependency `org.robolectric:shadows-core:jar:18:3.0-SNAPSHOT` was at
https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/shadows-core/3.0-SNAPSHOT/

But since the latest snapshot build the dependency is missing. Did you drop it or just a build error?

**Comment by erd** [comment]
It's a build error - I'm currently looking at it.

**Comment by felipecsl** [comment]
right now I can't run tests neither with 3.0-SNAPSHOT nor 3.0-rc1.
Any update on an ETA for this?

**Comment by felipecsl** [comment]
OK I was able to make it work using `@Config(emulateSdk = 21, reportSdk = 21)` and robolectric `3.0-rc1`

**Comment by erd** [comment]
@felipecsl 3.0-rc1 had a bug that was causing it to try and load shadows-core from 3.0-SNAPSHOT (which was not available on Maven Central at the time). I pushed out a 3.0-rc2 this afternoon which should resolve that issue. I would suggest testing against 3.0-rc2 until the snapshot builds are working again (even then, the rc builds will be more stable).

**Comment by nenick** [comment]
fixed by https://github.com/robolectric/robolectric/pull/1658

**Comment by oliviadodge** [comment]
Hi, I'm still running into a similar issue using "org.robolectric:robolectric:3.2.2" dependency: 

Unable to get resource 'org.robolectric:android-all:pom:7.1.0_r7-robolectric-0' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: oss.sonatype.org

Unable to get resource 'org.robolectric:shadows-core:pom:3.2.2' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: oss.sonatype.org

Anyone know how to fix this? 

Thanks in advance!

**Comment by xian** [comment]
@oliviadodge -- sorry, not sure, the file appears to be in the correct place: https://oss.sonatype.org/content/groups/public/org/robolectric/android-all/7.1.0_r7-robolectric-0/android-all-7.1.0_r7-robolectric-0.pom

Are you using maven or gradle? Can you [paste](https://gist.github.com/) in your build file?

**Comment by oliviadodge** [comment]
I didn't paste that part, but it's also looking in maven (see below). I think it's to do with the proxy. When I specify settings.xml in .m2 with proxy host/port etc. it works. Not sure if there is a better way to do that though as I'd prefer not to have that in .m2.

Downloading: org/robolectric/android-all/7.1.0_r7-robolectric-0/android-all-7.1.0_r7-robolectric-0.pom from repository central at http://repo1.maven.org/maven2
Error transferring file: repo1.maven.org

Downloading: org/robolectric/shadows-core/3.2.2/shadows-core-3.2.2.pom from repository central at http://repo1.maven.org/maven2
Error transferring file: repo1.maven.org

**Comment by xian** [comment]
This sounds like a problem with `MavenDependencyResolver`/`maven-ant-tasks`. Sounds like your network requires a proxy to reach outside URLs?

**Comment by oliviadodge** [comment]
Yes, that's probably it. Will talk to my manager about allowing this URL. Thank you so much!

**Comment by itsmortoncornelius** [comment]
I have the same issue with 3.7.1
Not able to use Robolectric. Specifying sdk not working.

Setup Kotlin, Android Studio 3.0.1
