### ISSUE TITLE
getApplicationContext() returns null

### ISSUE THREAD

**Issue by yugacohler** [robolectric/robolectric#1657]
I have some code which calls getApplicationContext() on a passed in context. In my test, I pass in Robolectric.buildActivity(Activity.class).create().get() as that context. The call to getApplicationContext() returns null.

Why is this the case? Is there any way I can bypass it?

Thanks!

**Comment by erd** [comment]
> Why is this the case?

Try using `Robolectric.setupActivity`. Or call `attach` on the `ActivityController` in your example.

**Comment by erd** [comment]
I'm not able to reproduce this issue. Feel free to re-open this issue if you can create a simple example that demonstrates this behavior.
