### ISSUE TITLE
How to use roboelctric with android-library plugin?

### ISSUE THREAD

**Issue by vijayrawatsan** [robolectric/robolectric#1667]
I keep getting
java.io.FileNotFoundException: build/intermediates/bundles/debug/AndroidManifest.xml (No such file or directory)
For library projects AndroidManifest.xml is not present in build/intermediates/bundles/debug/
Any documentation or reference github project will be appreciated.

**Comment by nenick** [comment]
> For library projects AndroidManifest.xml is not present in build/intermediates/bundles/debug/

But there should be an AndroidManifest.xml

Please try the following example with a library module if it works for you too
 https://github.com/nenick/AndroidStudioAndRobolectric/tree/library

**Comment by vijayrawatsan** [comment]
This uses an 
https://github.com/nenick/AndroidStudioAndRobolectric/blob/library/app/build.gradle#L1
