### ISSUE TITLE
XmlFileBuilder#getAttributeValue doesn't resolve enum values

### ISSUE THREAD

**Issue by hzsweers** [robolectric/robolectric#1669]
Example: Trying to retrieve the value of `textStyle` on a TextView.

In xml it could be `android:textStyle=“bold"`

The result of `getAttributeValue(<android_namespace>, "textStyle")` should be `0x1`, but instead Robolectric returns its text value of `bold`.

This isn't too bad, but it would be nice to be consistent with what the platform returns in real code.

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding resource-related issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
