### ISSUE TITLE
ShadowWrangler#getMethod can't resolve "getNonResourceString"

### ISSUE THREAD

**Issue by hzsweers** [robolectric/robolectric#1670]
`TypedArray#getNonResourceString` is a valid resource retrieval method, but Robolectric can't seem to find it and just returns null when one tries to use it.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
