### ISSUE TITLE
ShadowPreference doesn't implement getContext()

### ISSUE THREAD

**Issue by hzsweers** [robolectric/robolectric#1671]
Real Preferences have a getContext() method, but the current [ShadowPreference implementation](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowPreference.java) currently doesn't. This breaks verifying custom styleable attributes on custom preference objects.

**Comment by erd** [comment]
Methods that aren't shadowed simply call through to the underlying android object. If anything, `ShadowPreference` might need a constructor that calls the underlying `Preference` constructor. Could you provide some code that demonstrates the error you are seeing?

**Comment by hzsweers** [comment]
Sure. I have an annotation processing library that generates boilerplate `TypedArray` stuff for custom styleable attributes.

[An example of it in use](https://github.com/hzsweers/barber/blob/master/sample%2Fsrc%2Fmain%2Fjava%2Fio%2Fsweers%2Fbarber%2Fsample%2Ftesting%2FCustomPreference.java)

[Corresponding Robolectric test](https://github.com/hzsweers/barber/blob/master/sample/src/test/java/io/sweers/barber/sample/PreferenceTest.java)

The generated code looks like this:

```java
public class CustomPreference$$Barbershop<T extends io.sweers.barber.sample.testing.CustomPreference> implements Barber.IBarbershop<T> {
  protected WeakHashSet lastStyledTargets = new WeakHashSet();

  @Override
  public void style(final T target, final AttributeSet set, final int[] attrs, final int defStyleAttr, final int defStyleRes) {
    this.lastStyledTargets.add(target);
    if (set == null) {
      return;
    }
    TypedArray a = target.getContext().obtainStyledAttributes(set, attrs, defStyleAttr, defStyleRes);
    // Retrieve custom attributes
    if (a.hasValue(0)) {
      target.titleColor = a.getColor(0, -1);
    }
    if (a.hasValue(1)) {
      target.summaryColor = a.getColor(1, -1);
    }
    a.recycle();
  }

  protected boolean hasStyled(final T target) {
    return this.lastStyledTargets.contains(target);
  }
}
```

The problem occurs via NPE on this line:

```java
TypedArray a = target.getContext().obtainStyledAttributes(set, attrs, defStyleAttr, defStyleRes);
```

Because `target.getContext()` returns null. This is because Robolectric is unable to find this method for some reason. I assumed it was because it wasn't implemented, but I understand now that I misinterpreted how `ShadowPreference` worked.

Let me know if you need any other info!

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
