### ISSUE TITLE
Environment.isExternalStorageRemovable() throwing NPE

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1674]
The original question is coming form SO:
http://stackoverflow.com/questions/29596177/robolectric-fails-from-nullpointerexception-because-of-calls-to-storage

I was able to reproduce it:
https://github.com/emartynov/robolectic-experiments/blob/master/robolectric-3.0-test/src/main/java/com/bijdorpstudio/myapplication/FileUtils.java
https://github.com/emartynov/robolectic-experiments/blob/master/robolectric-3.0-test/src/test/java/com/bijdorpstudio/myapplication/FileUtilsTest.java

The fix should be quite trivial and simple. I will take a try at evening today

**Comment by erd** [comment]
I added implementations for `isExternalStorageRemovable` and `isExternalStorageEmulated`. Let me know if the API works for you.

**Comment by emartynov** [comment]
Thank you Erich! Works perfectly!
