### ISSUE TITLE
FileNotFoundException / android.view.InflateException  when resource name conflict

### ISSUE THREAD

**Issue by trinitron01** [robolectric/robolectric#1676]
There seems to be an issue with loading resources with name conflicts. For example (this comes from a Float Label Library - https://github.com/IanGClifton/AndroidFloatLabel )  : 

I have an xml file with resource id declarations : 

```
    <item type="id" name="float_label" />
    <item type="id" name="float_label_edit_text" />
```

I have xml  layout  file called float_label, same name as one of the ids.

Content of the xml layout file  (note the ids of the view) : 

```
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android">

    <TextView
        android:id="@id/float_label"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:focusable="false"
        android:focusableInTouchMode="false"
        android:lines="1"
        android:textIsSelectable="true"
        android:textAppearance="?android:attr/textAppearanceSmall" />

    <!-- The default EditText includes 7dp of top spacing (4dp optical), so we offset by that to tighten up the Views -->
    <EditText
        android:id="@id/float_label_edit_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="-7dp"
        android:inputType="text|textAutoCorrect|textCapSentences|textAutoComplete" />

</merge>

```

Inflating this layout in a test results in a 

```
java.io.FileNotFoundException: 
java.lang.RuntimeException: java.io.FileNotFoundException: 
    at org.robolectric.res.XmlLoader.parse(XmlLoader.java:39)

```

or

```
 android.view.InflateException: XML  ...

(sorry, not yet implemented): Error inflating class <VIEW THAT INFLATES THE LAYOUT>
```

The only solution is to change the name of the layout to something different. Then all the tests pass.

I am using 'org.robolectric:robolectric:3.0-rc2' gradle plugin 1.1.0 and tests are annotated with defaults :

```
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, emulateSdk = 21)
```

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
