### ISSUE TITLE
ShadowOf is not working for me on 3.0-SNAPSHOT

### ISSUE THREAD

**Issue by javicps** [robolectric/robolectric#1678]
Something as simple as the sample from the web does not work for me (using robolectric-3.0-SNAPSHOT)

	Intent expectedIntent = new Intent(activity, MainActivity.class);
	assertThat(shadowOf(activity).getNextStartedActivity()).isEqualTo(expectedIntent);

Eclipse or maven do not recognize the token shadowOf. I know that additional Shadow classes now should be downloaded from diferentes sources, but this seems that is not working even when shadowing Activity.

**Comment by javicps** [comment]
Maybe this is related: https://groups.google.com/forum/#!topic/robolectric/sos66H-tx-M
If it is the case, sorry for repost.

**Comment by erd** [comment]
The Google Groups post is old. There were issues with the SNAPSHOT build, but it should be back up and running. Could you try using version '3.0-rc2' while I track this down?

**Comment by javicps** [comment]
I tried that one too, robolectric-3.0-rc2.jar downloaded from sonatype at: https://oss.sonatype.org/index.html#nexus-search;quick~robolectric
Do i need to download a version with dependencies?

**Comment by erd** [comment]
How are you building your project? Are you checking the jars into your repo?

**Comment by erd** [comment]
Please take a look at the `robolectric/robolectric-samples` repository. It has a collection of working examples that build against 3.0-rc2. I was able to update the version to 3.0-SNAPSHOT and run all of tests successfully.

**Comment by javicps** [comment]
Thank you, I will try. Seems odd, because I can referr to the Robolectric class without problem, but can't use shadowOf.

**Comment by jongerrish** [comment]
Shadows.shadowOf

**Comment by javicps** [comment]
Solved in Eclipse by downloading jars form shadows.core and robolectric utils.
Thank you big time :)
