### ISSUE TITLE
Builds failing only on Travis

### ISSUE THREAD

**Issue by flyingtoaster0** [robolectric/robolectric#1682]
I recently created a branch on my project and migrated to Robolectric 3.0 RC2. Everything worked fine locally, but Travis was having trouble running my build. On RC2, about 80% of the time, Travis will fail my first 1 to 4 tests with and EOFException. The stack trace is the same for every test that fails in this manner. It looks like the following:

```
com.package.activities.MainNavigationTest > shouldHaveThreeTabs FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: java.io.EOFException
```

I then made a commit with debug enabled, and found the following interesting line when Travis ran my build:

```
18:49:28.959 [DEBUG] [TestEventLogger]         Caused by:
18:49:28.959 [DEBUG] [TestEventLogger]         org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.robolectric:shadows-core:jar:18': Failed to build model from file '/home/travis/.m2/repository/org/robolectric/shadows-core/3.0-rc2/shadows-core-3.0-rc2.pom'.
18:49:28.960 [DEBUG] [TestEventLogger]         Error: 'no more data available - expected end tags </compilerArguments></configuration></plugin></plugins></build></project> to close start tag <compilerArguments> from line 234 and start tag <configuration> from line 229 and start tag <plugin> from line 225 and start tag <plugins> from line 126 and start tag <build> from line 112 and start tag <project> from line 2, parser stopped on START_TAG seen ...<compilerArguments>\n... @235:1' for project org.robolectric:shadows-core
18:49:28.960 [DEBUG] [TestEventLogger]           org.robolectric:shadows-core:jar:3.0-rc2
```

It looks like, for some reason, that the line after the <compilerArguments> tag from the pom.xml in shadows-core can't be parsed on Travis. I've included the whole debug log from Travis. The first failure occurs at line 12354. Let me know if you need more info!

**Comment by erd** [comment]
We tweaked the pom.xml files to not have line breaks in the `<compilerArguments>` sections (fd1d9bf875c84f47f2ec3b76dece24caac9ee4a4), but beyond that, I have no idea what we could do here.

**Comment by chetbox** [comment]
I'm seeing this in Travis occasionally:

```
com.package > myTest FAILED
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException
            Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException
                Caused by: org.apache.maven.project.ProjectBuildingException
                    Caused by: java.io.EOFException
```

Running the build again usually seems to work.

**Comment by grandstaish** [comment]
Has anything regressed here? I get this failure on Travis 80% of the time, and build times are really long, so you can imagine how much time is being wasted on restarting builds :(

**Comment by gabrieloshiro** [comment]
I have this on Bitrise. Any news?
