### ISSUE TITLE
Compilation error with library test

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1683]
I'm trying to add unit tests to the library. Unfortunately I have compilation errors:
```
Gradle: error: package R does not exist
```
Here is test class:
https://github.com/emartynov/material-dialogs/blob/robolectric-tests/library/src/test/java/com/afollestad/materialdialogs/DialogInitTest.java

I'm not sure if it is Robolectric or android gradle plugin

**Comment by emartynov** [comment]
I found workaround here:
https://github.com/nenick/AndroidStudioAndRobolectric/issues/6

Should I close issue?

Because after fix application I got test fail since it can not find `AndroidManifest.xml`. Which was also workarounded

**Comment by nenick** [comment]
Do you have a Mac? When yes see also "Note for Mac Users" at http://robolectric.org/getting-started/

**Comment by emartynov** [comment]
This is run from console `gradle test`

**Comment by erd** [comment]
From your test:

    @RunWith(RobolectricTestRunner.class)
    @Config(constants = BuildConfig.class, emulateSdk = 21, manifest = "src/main/AndroidManifest.xml")

If you're using 3.0-rc2 + Gradle, you should switch to use `RobolectricGradleTestRunner`. This will allow you to drop the `manifest` from your @Config annotation. Additionally, Robolectric was using the wrong path for assets and resources when used with library projects. I pushed a fix yesterday (dee6667eef43caeafce91986244f0d38da93a76d) that may solve your problems.

**Comment by emartynov** [comment]
Thanks Erich! Why I use `RobolectricTestRunner` instead of `RobolectricGradleTestRunner` because I'm able to specify `AndroidManifest.xml`. If I use gradle runner it can not find manifest. I got suggestion to add tests tasks dependency to assemble task. I will just try to reproduce and create another issue.

Thank you for great library and support!
