### ISSUE TITLE
OverlayConfig#constants when is Void overrides a valid baseConfig#constants

### ISSUE THREAD

**Issue by laminina** [robolectric/robolectric#1697]
Setting the Config.constants in the configProperties file won't take any effect IFF there is another set of @Config properties at UnitTest's Class or Method level with absence of constants property.

Reason: overlayValue has by default -> java.lang.Void which is different than the nullValue:
      this.constants = pick(baseConfig.constants(), overlayConfig.constants(), null); null does not equal Void.class

Therefore when overlayValue is not equal that nullValue the baseValue it's overridden by the overlayValue and I lose my BuildConfig.class

**Comment by laminina** [comment]
The fix I'm proposing is in Config.java when picking the constants the null value should be Void.class instead of null.

**Comment by erd** [comment]
Send a PR and I'll take a look at it.

**Comment by laminina** [comment]
Here you go! https://github.com/robolectric/robolectric/pull/1707
