### ISSUE TITLE
ShadowContextWrapper doesn't implement getApplicationInfo

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1705]
I'm adding tests to library that provides material dialogs for pre-lollipop:
https://github.com/emartynov/material-dialogs/tree/robolectric-tests

I'm getting now:
```
java.lang.NullPointerException
	at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:148)
```
here
https://github.com/emartynov/material-dialogs/blob/robolectric-tests/library/src/test/java/com/afollestad/materialdialogs/DialogInitTest.java#L19

I assume that is because library project. Could you help how to resolve?

**Comment by nenick** [comment]
There are two things which should be changed and then retry.
remove `manifest = "src/main/AndroidManifest.xml"` and use the `RobolectricGradleTestRunner` instead of `RobolectricTestRunner`

**Comment by emartynov** [comment]
Thanks for suggestion. If I follow your suggestion I get next one:
```
java.lang.RuntimeException: java.lang.RuntimeException: build/intermediates/manifests/full/debug/AndroidManifest.xml not found or not a file; it should point to your project's AndroidManifest.xml
```

**Comment by nenick** [comment]
I tried your project. From command line it don't miss the Manifest if I apply following part to `library/build.gradle` and start tests with `./gradlew test`
```
// add compile main sources for test runs https://github.com/nenick/AndroidStudioAndRobolectric/issues/7
afterEvaluate { project ->
    android.libraryVariants.each { variant ->
        tasks.getByName("test${variant.name.capitalize()}") {
            dependsOn "assemble${variant.name.capitalize()}"
        }
    }
}
```

In Android Studio I get the missing Manifest error, but it is expected because I have Mac and must set `$MODULE_DIR$` as working directory. With this working directory or a custom RobolectricGradleTestRunner the missing Manifest error is gone.

But I have the null pointer too.

**Comment by emartynov** [comment]
Thanks for verification!

**Comment by erd** [comment]
I looked a bit more closely, and it looks like `ShadowContextWrapper` doesn't implement `getApplicationInfo`, which is why you're getting null in your tests. I don't think this has anything to do with it being a library project.

**Comment by fishstix** [comment]
Hi,
I'm on a Mac and getting the RuntimeException, not finding the AndroidManifest.xml file.  I'm using RobolectricGradleTestRunner and have tried every variation of @Config to no avail.  I've updated the "MODULE_DIR" within AndroidStudio and also tried various ways of running from the command line to no avail.
