### ISSUE TITLE
Java 8 version support

### ISSUE THREAD

**Issue by jmodrako** [robolectric/robolectric#1708]
Just one simple question, does Roboletric support JDK 8?

**Comment by lexs** [comment]
Yes, while Robolectric itself targets JDK 7 there are no compatibility issues with JDK 8.

**Comment by erd** [comment]
Yep - it works fine with Java 8.

**Comment by ZiglioUK** [comment]
Apologies for commenting on a closed issue but Java 8 support doesn't work with "android-all"

>     api group: 'org.robolectric', name: 'android-all', version: '8.1.0-robolectric-4514284'

It looks like a desugaring issue with some Android APIs. 
I'm not aware of any way to enable Java 8 for a subset of classes in the project.

> :app:transformClassesWithDesugarForDebug
> Exception in thread "main" java.lang.IncompatibleClassChangeError: android.telecom.Connection and android.telecom.Connection$Listener disagree on InnerClasses attribute
> 	at java.lang.Class.getDeclaringClass0(Native Method)
> 	at java.lang.Class.getDeclaringClass(Class.java:1235)
> 	at java.lang.Class.getEnclosingClass(Class.java:1277)
> 	at java.lang.Class.getSimpleBinaryName(Class.java:1443)
> 	at java.lang.Class.getSimpleName(Class.java:1309)
> 	at java.lang.invoke.MethodType.toString(MethodType.java:797)
> 	at java.lang.String.valueOf(String.java:2994)
> 	at java.lang.invoke.MemberName.getName(MemberName.java:844)
> 	at java.lang.invoke.MemberName.toString(MemberName.java:831)
> 	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:863)
> 	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
> 	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
> 	at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1004)
> 	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toMethodHandle(LambdaDesugaring.java:609)
> 	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toJvmMetatype(LambdaDesugaring.java:586)
> 	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:401)
> 	at org.objectweb.asm.ClassReader.a(Unknown Source)
> 	at org.objectweb.asm.ClassReader.b(Unknown Source)
> 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
> 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
> 	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
> 	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
> 	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
> 	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
> 
> 
>  FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> > com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --output /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/desugar/debug/15.jar --input /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --output /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/desugar/debug/21.jar --input /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --output /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/desugar/debug/17.jar --input /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --output /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/desugar/debug/5.jar --input /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --output /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/desugar/debug/7.jar --input /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --output /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/desugar/debug/1.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/classes/debug --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/1.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/9.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/10.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/13.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/21.jar --classpath_entry /Users/emanueleziglioli/git/software/ContextHub2/app/build/intermediates/transforms/stackFramesFixer/debug/22.jar --bootclasspath_entry /Users/emanueleziglioli/Library/Android/sdk/platforms/android-27/android.jar --bootclasspath_entry /Users/emanueleziglioli/Library/Android/sdk/platforms/android-27/optional/org.apache.http.legacy.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/resources.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/rt.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/jsse.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/jce.jar --bootclasspath_entry /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/jre/lib/charsets.jar --min_sdk_version 27 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}
>
