### ISSUE TITLE
Wrong asset path in library project when using RobolectricGradleTestRunner (Robolectric 3.0-rc2)

### ISSUE THREAD

**Issue by DaimonPl** [robolectric/robolectric#1709]
When using Robolectric 3 in library project (com.android.library) with android gradle plugin 1.2 (I haven't checked older versions) wrong asset path is being set:
```
robolectric path: build/intermediates/assets/debug/
real path:        build/intermediates/bundles/debug/assets/
```
It looks that RobolectricGradleTestRunner needs to set different path for library projects (application projects are fine)

**Comment by erd** [comment]
I pushed a fix for this yesterday b1124255f216b3dfe5da153a861b69c32219fed0. Could you take a look and see if it fixes your issues? If not, feel free to re-open this issue.

**Comment by DaimonPl** [comment]
Just by looking at code changes it should do the job.

Any idea when rc3 would be available on maven? I tried SNAPSHOT from maven but repository does not seem to work with SNAPSHOT

**Comment by erd** [comment]
It'll probably be a few weeks. There are still quite a few known issues that I want to fix.
