### ISSUE TITLE
Cannot use robolectric.properties on Robolectric 3.0-rc2

### ISSUE THREAD

**Issue by kageiit** [robolectric/robolectric#1718]
With robolectric 2.4, test resources and `org.robolectric.Config.properties` could be placed inside the `src/androidTest/resources` directory and found correctly.

It is not clear where to place the `robolectric.properties` file when using robolectric 3.0-rc2. The configuration cannot be found when placed inside the resources directory.

**Comment by erd** [comment]
It should go either in `src/main/resources` or `test/main/resources` (somewhere accessible to ClassLoader. getResourceAsStream). There is currently a bug in the android gradle plugin that prevents test/main/resources from working. See #1621 for more information.

**Comment by kageiit** [comment]
Solved this by creating a custom test runner that copies the test resources to the test classes directory. Works great. Thanks for the info!
