### ISSUE TITLE
ShadowIntentFilter does not override equals anymore

### ISSUE THREAD

**Issue by laminina** [robolectric/robolectric#1725]
Noticed in this commit #1398 https://github.com/robolectric/robolectric/commit/8b0ff059fe5f99169398bef3fc076240b2b0996b

That equals implementation was removed in the ShadowIntentFilter. Currently whenever we have 
assertEquals(thisIntentFilter, thatIntentFilter) is failing because it ends up doing the Object#equals implementation.

Is there any reason it was removed, I'm trying to avoid  having to check each member of the IntentFilter right now we just do intentFilter equals thatIntentFilter, but maybe it was removed to fix something greater than this. I have a branch where I brought it back (added priority and also to the hashcode). I'm having trouble adding the test though. It seems is not doing the equals implementation of the shadow. But before investing more time on this, can we add the equals to the ShadowIntentFilter, or should we have this logic in our projects? 

Thanks! :)

**Comment by DaimonPl** [comment]
If you look at android sources, android.content.IntentFilter also does not implement equals

So it's actually very good change as previous behaviour in robolectric could lead to runtime bugs (i.e. writing code which assumes that IntentEquality is based on something more than instance equality which would work in tests but fail on device)

**Comment by laminina** [comment]
perfect. This works :) thanks!
