### ISSUE TITLE
Support API 22

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1728]
Add support for Android 5.1 (Lollipop MR1)

**Comment by jaredsburrows** [comment]
Yes, it would be nice to stop "checking" and default to the either the latest Robolectric supports which is `21` or use what is in the `AndroidManifest.xml`.

There was once a similar issue for the Robolectric Gradle plugin with the same idea: https://github.com/robolectric/robolectric-gradle-plugin/issues/149.

**Comment by erd** [comment]
If you don't specify `sdk` in a @Config annotation, Robolectric does default to the `targetSdkVersion` in your manifest.

**Comment by jaredsburrows** [comment]
@erd  Then you receive something like this:

    com.test.test.MainFragmentTest > test FAILED
        java.lang.UnsupportedOperationException: Robolectric does not support API level 22.

**Comment by jongerrish** [comment]
Looks like Lollipop MR1 is available on aosp:

https://github.com/android/platform_frameworks_base/blob/lollipop-mr1-release/core/java/android/os/Build.java

**Comment by oriolblanc** [comment]
Any news on this issue?

**Comment by jaredsburrows** [comment]
Any update on this? What needs to be included? @jongerrish

**Comment by jongerrish** [comment]
We need to build an android-all-5.1-robolectric-0.jar @erd would you be able to do this? I know it needs signing to be accessible through maven central. If you make a list of the instructions I'd be happy to do it in the future.

Once this is done we just need to configure the project to output shadows for 5.1 then fix any failing tests.

**Comment by jaredsburrows** [comment]
Yes! Good idea @jongerrish.

Please add to our Wiki!

**Comment by castillobg** [comment]
Hi! Is there a version that supports API level 22?

**Comment by erd** [comment]
This was solved by #2030.
