### ISSUE TITLE
NotFoundException: not such label

### ISSUE THREAD

**Issue by cmonfortep** [robolectric/robolectric#1747]
I'm trying to execute some tests with org.robolectric:robolectric:3.0-SNAPSHOT and I'm having this error:
```
android.content.res.Resources$NotFoundException: no such label com.my.packageINT.debug:string/app_name
	at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:104)
	at org.robolectric.util.ActivityController.attach(ActivityController.java:49)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
(....)
```

My project is build with Android Studio, com.android.tools.build:gradle:1.1.3 and has flavors and buildtypes.

Looking for an answer I found different possible solutions without solving the problem.

I've tried some custom RobolectricRunners:
https://github.com/nenick/AndroidStudioAndRobolectric/blob/master/app/src/test/java/com/example/myapplication/CustomRobolectricRunner.java
and this:
https://github.com/nenick/AndroidStudioAndRobolectric/blob/flavors/app%2Fsrc%2Ftest%2Fjava%2Fcom%2Fexample%2Fmyapplication%2FCustomRobolectricRunner.java
and this:
http://stackoverflow.com/questions/22102176/resourcesnotfoundexception-when-using-robolectric-with-gradle

Always with the same error as result :(

**Comment by erd** [comment]
Use `RobolectricGradleTestRunner` - it's documented at http://robolectric.org/getting-started.

Also, If you use flavors that have applicationIds that are different from your Java package name, you'll need to specify your Java package name in the `packageName` attribute in the @Config annotation.

**Comment by cmonfortep** [comment]
Hi @erd, I've used RobolectricGradleTestRunner.class and changed the packageName using @Config the first time I was configuring Robolectric, but the error is similar:

````
@RunWith(RobolectricGradleTestRunner.class)
@Config(packageName = "com.my.package", constants = BuildConfig.class)
````

````
android.content.res.Resources$NotFoundException: String resource ID #0x7f0701bf
	at android.content.res.Resources.getText(Resources.java:244)
	at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:361)
	at android.content.res.Resources.getText(Resources.java)
	at android.content.res.Resources.getString(Resources.java:330)
	at org.robolectric.shadows.ShadowContext.getString(ShadowContext.java:33)
	at org.robolectric.shadows.ShadowContextWrapper.getString(ShadowContextWrapper.java:78)
	at android.content.Context.getString(Context.java)
	at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:108)
	at org.robolectric.util.ActivityController.attach(ActivityController.java:49)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
````

**Comment by erd** [comment]
Ok, I'll take a look.

**Comment by michaeltweed** [comment]
I'm seeing this issue as well (and have tried all the suggested steps). I have multiple flavors and have a strings.xml file in each. I'm currently using org.robolectric:robolectric:3.0-rc2. Is there any progress update? Thanks

**Comment by cmonfortep** [comment]
To add more info, I have some resources in the default path (main/res) and other resources in other paths (flavour/res)...

in my gradle file I have this declared as sourcerts:
```
    sourceSets.flavour {
        res.srcDirs = ['res', 'src/flavour/res']
        assets.srcDirs = ['assets','src/flavour/assets']
    }
```

**Comment by qazt482** [comment]
I'm having issues with this too! Any update?

**Comment by jaredsburrows** [comment]
@cmonfortep I am seeing this too but in a brand new project.

**Comment by jaredsburrows** [comment]
I am tagging this issue, https://github.com/robolectric/robolectric/issues/1623, here as well.

Read the issue and here is @Egorand 's answer that works for me:

Create your own `CustomBuildConfig.java`:

        public static final class CustomBuildConfig {
                public static final boolean DEBUG = BuildConfig.DEBUG;
                public static final String APPLICATION_ID = "com.correct.package.name";
                public static final String BUILD_TYPE = BuildConfig.BUILD_TYPE;
                public static final String FLAVOR = BuildConfig.FLAVOR;
                public static final int VERSION_CODE = BuildConfig.VERSION_CODE;
                public static final String VERSION_NAME = BuildConfig.VERSION_NAME;
        }

And pass to your `CustomBuildConfig` to `@Config`:

       @Config(constants = CustomBuildConfig.class)

**Comment by michaeltweed** [comment]
@jaredsburrows I have just tried this and unfortunately it is still not working. I have set the     APPLICATION_ID to 'com.mypackage.name' and my tests are still giving the error: 

    android.content.res.Resources$NotFoundException: no such label com.mypackage.name:string/my_string


I also do not change my application ID across my flavors, the only files which change are resource and java files. This is affecting me in an Android Library project, where my Application ID is defined by the 'package' in the Android Manifest (see http://stackoverflow.com/a/27375066/1319750).

**Comment by jaredsburrows** [comment]
@michaeltweed  I never saw this notification. Do you have your code on Github?

**Comment by dschuermann** [comment]
@jaredsburrows thanks for your CustomBuildConfig. This works for me!

In our app the debug build has applicationIdSuffix in build.gradle defined as ".debug".
Looks like Robolectric is using the applicationId instead of the packageName to find the R.java.
Also: http://tools.android.com/tech-docs/new-build-system/applicationid-vs-packagename

**Comment by erd** [comment]
@dschuermann If your applicationId and packageName are different, you can specify the packageName in the @Config annotation and Robolectric will use this instead of the applicationId.

**Comment by jaredsburrows** [comment]
@dschuermann It was from @Egorand :) I am glad there is a work around.

**Comment by dschuermann** [comment]
Now solved by using the new packageName annotation parameter from https://github.com/robolectric/robolectric/pull/1875

See https://github.com/open-keychain/open-keychain/commit/85a47d22f9bb1e4aaf5770c67416a5532977658e

Thanks. This issue is now resolved for me

**Comment by dschuermann** [comment]
I needed to revert the commit. The tests were running fine locally but throwed the old Resource not found error when run on Travis. Not sure why...

**Comment by emce** [comment]
I can't pass through this in any way - all proposed configurations and workarounds are not working...
