### ISSUE TITLE
Failed to resolve: org.roboelectric:roboelectric:3.0

### ISSUE THREAD

**Issue by hronik1** [robolectric/robolectric#1767]
Following the getting started per http://robolectric.org/getting-started/ and just trying to add roboelectric as a Test Compile dependency by adding testCompile "org.robolectric:robolectric:3.0". However this fails with the output in the title.

I am using gradle/Android Studio and compiling against sdk version 21.

**Comment by erd** [comment]
3.0 isn't quite released yet - 3.0-rc2 is the latest release candidate.

**Comment by hronik1** [comment]
Thanks, that worked! Would you mind updating the documentation so that other people don' have the same problem?
