### ISSUE TITLE
Eliminate usage raw types

### ISSUE THREAD

**Issue by kriegfrj** [robolectric/robolectric#1774]
There is a lot of code in Robolectric that uses raw types. Generates lots of compiler warnings.

I think it would be good if these could be tidied up/eliminated. Not only does this make the code cleaner, it can help to catch silly (and sometimes obscure) bugs if appropriate type constraints are put in place. The compiler is the best bug-finding friend that we have (even better than unit tests!) - best if we give it as much information as we can to help it do its job as best as it can.

Where it is not possible to put tighter constraints in place, then simply using wildcards will at least clean up the warnings.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
