### ISSUE TITLE
SystemClock.elapsedRealtime() throws NullPointerException when used in Custom Application class

### ISSUE THREAD

**Issue by stephanenicolas** [robolectric/robolectric#1779]
Against current robolectric master, if you use `SystemClock.elapsedRealtime()` inside a custom application class, robolectric throws a `NullPointerException` with the following stack trace : 

```
 Exception in thread "xxx" java.lang.NullPointerException
    	at org.robolectric.shadows.ShadowSystemClock.now(ShadowSystemClock.java:20)
    	at org.robolectric.shadows.ShadowSystemClock.uptimeMillis(ShadowSystemClock.java:41)
    	at org.robolectric.shadows.ShadowSystemClock.currentThreadTimeMillis(ShadowSystemClock.java:51)
    	at android.os.SystemClock.currentThreadTimeMillis(SystemClock.java)
```
Note : I think this is a good bug as using time stamps is often a requirement in Application classes to benchmark application startups and address performance issues.
Note 2 : a simple workaround is to create an application class for unit tests that extends the application class and doesn't use `SystemClock.elapsedRealtime()`

Thx guys for all your work on Robolectric, it's simply great to have it working with Gradle and Android Studio like this.

**Comment by lexs** [comment]
I'm guessing this code is executed in the constructor of your `Application` because it should work fine in and after `onCreate()`?

**Comment by stephanenicolas** [comment]
Right. I think the problem comes from the system clock shadow using the application that is not built yet. 
I am wondering why we need the application class for a system clock call. Android doesn't seem to be doing this at all.

**Comment by stephanenicolas** [comment]
Digging a bit into the code, I can see that there might be a couple of issues. I had the feeling that the time should be set in Robolectric at high level time entity, independent from the scheduler of the ui thread, but that this  one should use it, same as background scheduler.

However, I am not so involved into Robolectric and might be wrong on that. 
Nevertheless, a quick workaround for this issue could be simply to support the application being null without crashing. 

If you guys agree on that, I would happy to submit a PR so that it can be merged for next RC. 
@erd , @lexs , WDYT ?

**Comment by stephanenicolas** [comment]
I am closing the issue as the PR got merged. Thx a lot ! 
Do you have any ETA for next RC so that we can be sure our app is ready for 3.0 ?
