### ISSUE TITLE
Visibility on LinearLayout

### ISSUE THREAD

**Issue by javicps** [robolectric/robolectric#1792]
Something odd happens when I'm trying to check if a LinearLayout (with visiblitiy gone as default) is visible.

This code:

``` java
    LinearLayout element = (LinearLayout) activity.findViewById(R.id.linear);
    assertEquals(LinearLayout.GONE, element.getVisibility());
```

returns failure (as if linear layout is visible, which is not)

But if I try to check the same with a gone edittext:

``` java
    EditText element = (EditText) activity.findViewById(R.id.textview);
    assertEquals(EditText.GONE, element.getVisibility());
```

returns success

I init my activity like this:

```
    activity = Robolectric.buildActivity(NewActivity.class).create().start().resume().visible().get();
```

What can be happening?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
