### ISSUE TITLE
Calling Resources#getValue on an XML resource fails

### ISSUE THREAD

**Issue by tec27** [robolectric/robolectric#1793]
I have a project that includes various XML files as resources in the `res/xml/` directory. It then calls `Resources#getValue` on these resource ID's in order to get back a `TypedValue` with their information. On an actual device, these calls succeed, but in Robolectric, they fail, saying that the resource could not be found. Even though Robolectric claims to not be able to find the resource, however, calling `Resources#getXml` on the same ID works just fine.

I did a bit of debugging into why this was happening, but I'm not 100% sure as to what the proper solution is. What I found:
- The getValue calls eventually get down to a `PackageResourceLoader` for my library.
- PackageResourceLoader [seems to assume](https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/res/PackageResourceLoader.java#L60) that all XML files are Preference data.
- This assumption results in the XML files being added to `preferenceData` in XResourceLoader, rather than `data`, which means the `get` call [here](https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/res/XResourceLoader.java#L53) returns null.

So it seems like the XML resources need a more complex load step that can split between Preferences and non-Preferences. But it also seems like `XResourcesLoader#getValue` should check all the various ResBundles it contains, since I _believe_ getValue is able to return TypedValue for all of those types in real Android (and making that happen would fix my issue, even if it meant my resources were under the wrong ResBundle).

**Comment by lexs** [comment]
Which version are you on?

XML files are also added to xmlDocuments which means that `Resources.getXml()` would succeed but as you say `getValue()` will not. This is of course because we don't treat the directories differently (which Android does not?).

The solution seems to be a larger refactoring of `ResourceLoader` to handle resources closer to how Android does it. Do you have a smallish test case of what you'd expect to work?

**Comment by tec27** [comment]
This is on snapshot at 77ae4054c6fd36bd2efa66068c63c7a4635a1593 (but I'm sure is still broken at HEAD as well).

I did some more digging as well, and understand what's going on slightly better with this code. All the other types just happen to work, because they add to the ResBunch that gets looked up during getValue, with the exception of Plurals and things in the `xml/` folder. Making a simple change to PreferencesLoader to also add things to the ResBunch along with its own ResBundle, e.g.:
```java
resBundle.put("xml", xmlFile.getName().replace(".xml", ""), topLevelNode.getChildren().get(0), xmlContext);
resBunch.put("xml", xmlFile.getBaseName(),                                                                             
        new FileTypedResource<>(xmlFile.getPath(), ResType.LAYOUT), xmlContext);
```

makes things work for me, but doesn't entirely make sense logically (since these things aren't actually Preferences, they shouldn't go through the PreferencesLoader) and may break other things.

In any case, my basic use case is:

- I have an arbitrary, non-preferences XML file in res/xml/
- I have a factory class that wants to create objects based on that XML and cache the results, similar to how Drawable loading works in Android:
```java
Resources res = context.getResources();
TypedValue value = new TypedValue();
res.getValue(R.xml.test_xml, value, true);
long cacheKey = (((long) value.assetCookie) << 32) | value.data;
if (cache.has(cacheKey)) {
  return cache.get(cacheKey);
} else {
  MyTestClass instance = MyTestClass.create(context, R.xml.test_xml);
  cache.put(cacheKey, instance);
  return instance
}
```

So I basically just need getValue to return something reasonable, ideally with a stable assetCookie and data per resource. I *believe* that already works as is, since drawables would be somewhat broken without it working, but I'm not entirely certain. It seems like that shouldn't require any major refactoring of ResourceLoader to make work, but maybe I'm ignorant as to how much the current structure differs from Android's actual loading.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
