### ISSUE TITLE
Robolectric is picking up wrong application package

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1797]
I have next project structure:
```
app
android library1
android library 2
```

Both libraries have Robolectric tests.

Right now one test for fragment in app project fails because of:
```
android.content.res.Resources$NotFoundException: no such theme <library 2 package>:style/AppTheme
```

So Robolectric is trying to use package form library module for the  application module

**Comment by emartynov** [comment]
I'm sorry for firing false issue. Unfortunately I used `BuildConfig` from library project (android studio import suggestion). As soon as I fixed it everything started working.

**Comment by erd** [comment]
No worries :) Thanks for looking into it!
