### ISSUE TITLE
Robolectric is taking wrong build type for AndroidManifest.xml

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1798]
I have build structure:
```
app
android library1
android library2
```

I also have specific build type for calculating code coverage. I get test failure:
```
java.lang.RuntimeException: java.lang.RuntimeException: build/intermediates/manifests/full/release/AndroidManifest.xml not found or not a file; it should point to your project's AndroidManifest.xml
```

So Robolectric is looking for different build type when it looks for android manifest.

If I run test for build configuration release then I get error from #1797

**Comment by erd** [comment]
How are you running your tests? What @Config settings are you using in the test? Can you create a small sample project that reproduces the issue and share it?

**Comment by emartynov** [comment]
Erich, I run it from command line and form android studio. I also tried to clean run it from parent folder and app folder.

I will try if I can repro with small repo.

**Comment by emartynov** [comment]
I'm sorry for firing false issue. Unfortunately I used `BuildConfig` from library project (android studio import suggestion). As soon as I fixed it everything started working. Sorry again!

**Comment by erd** [comment]
No worries!

**Comment by dgmltn** [comment]
Thanks @emartynov , this helped me too. While I was moving some tests to a new module, the BuildConfig from the old module got automatically imported. Deleting that import fixed this issue for me!
