### ISSUE TITLE
Script to run tests under Wine

### ISSUE THREAD

**Issue by kriegfrj** [robolectric/robolectric#1820]
In the wake of #1817 (which is in turn the most recent in a series of bugs I have fixed that are regressions on Windows) @erd asked if there was a way we could check for such regressions in the future short of getting Windows CI support on Travis. I floated the idea of using Wine (https://www.winehq.org) to do this. I did a bit more research into Wine and Travis and I reckon this might work, so I'm creating this issue to track the idea. I would envisage implementing this in two stages:
- A script (either a shell script or a Maven plugin) which runs the tests using the Windows JDK(s) under Wine.
- Some extra bits in Travis to install Wine, then install the Windows JDK under Wine, and finally to run the above script.

The first would give the Unix developers a way to ensure their changes have not introduced any regressions on Windows (whereas at the moment they only find out after their changes have been merged and a Windows user tries them out). The second would allow the CI to detect issues without requiring a full Windows instance.

If done right there could be a fair bit of reuse between Unix and Wine (eg, you should be able to share the Maven repository and maybe the Maven installation itself.

**Comment by kriegfrj** [comment]
I have managed to write some simple scripts that allow you to get Wine set up and running Java. These scripts are available at https://github.com/kriegfrj/winejava-test. I have managed to test the full Robolectric test suite using winejava on Fedora 20 using wine 1.7.something. So this is in a state now where people might be able to find it useful for testing under Windows on their own machines. I would be happy if people could try it out and let me know how it works for them.

Note that JDK 8 doesn't seem to install cleanly under wine so this is still a Java 7 thing for the moment.

Unfortunately I have run into some complications when trying to integrate this into the Robolectric build. The problem:

- Travis CI VMs use Ubuntu 12.
- Default version of Wine for Unbuntu 12 is wine1.4, and the JVM seems to die when run under this version of Wine.
- The latest version of Wine seems to fix the dying problem, but installing it requires moving away from the container-based workers so that sudo can be used. Unfortunately the Robolectric build/test seems to get abruptly terminated during the final test phase when run on the standard (non-container) workers.

I think the solution will be to ask the Travis team to whitelist the ubuntu-wine PPA so that the latest version of Wine can be installed on the container-based workers.

**Comment by kriegfrj** [comment]
I have submitted a couple of whitelist requests to the Travis team to ask them to include the ubuntu-wine ppa so that the latest versions of Wine can be installed in the container workers. Hopefully they will get to this soon and I can integrate the Wine tests with the Travis build.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
