### ISSUE TITLE
AndroidManifest's MetaData is not modifiable when there is no MetaData

### ISSUE THREAD

**Issue by stephanenicolas** [robolectric/robolectric#1824]
After commit : https://github.com/robolectric/robolectric/commit/fe3a25ac91f9021c1e57e1cb888b4c94d26b70d0

There has been a change in method : `getApplicationMetaData()`. 
In the case it is null, it should not return `Collections.emptyMap()` as this is immutable.

**Comment by erd** [comment]
What's the use case for the manifest data being modifiable after parsing?

**Comment by stephanenicolas** [comment]
In RoboGuice, we use application meta data to determine where to find some stuff that an annotation processor has generated. 

In the test variants, we must add some additional stuff to the original meta data of the manifest of the app itself. We don't want to do it in the app itself as it would couple production and tests, so we create a manifest out of the original manifest and the add some stuff in its meta data.

**Comment by stephanenicolas** [comment]
@erd let me know if there is anything better I can do for that PR.

**Comment by erd** [comment]
Fixed by #1825.
