### ISSUE TITLE
addInstrumentedPackage does not allow to specify one single class

### ISSUE THREAD

**Issue by mtotschnig** [robolectric/robolectric#1832]
Until 3.0-rc2 I was able to use a custom runner which has overriden createSetup to return a custom InstrumentingClassLoaderConfig (formerly Setup) that overrides shouldInstrument

    public boolean shouldInstrument(ClassInfo info) {
           return super.shouldInstrument(info) ||
                    info.getName().equals("my.package.org.MyActivity");
        }

When updating to 3.0-rc3 I tried to use the new mechanism

    public InstrumentationConfiguration createClassLoaderConfig() {
        return InstrumentationConfiguration.newBuilder()
                .addInstrumentedPackage("my.package.org.MyActivity")
                .build();
    }

This works for most test classes, but it breaks the test class my.package.org.MyActivityTest, since this class is now also considered to be instrumented, and that leads to 

    java.lang.IllegalArgumentException: Test class can only have one constructor

when running the test. It should still to be possible to specify an exact class name for instrumentation, instead of the current comparison made with startsWith.

**Comment by lexs** [comment]
As a workaround you can use the `@Instrument` annotation, even if this is awkward for non-test classes.

**Comment by karlicoss** [comment]
I have a patch for that, and could make a PR, like, tomorrow.

**Comment by mtotschnig** [comment]
@lexs the @Instrument annotation would work, but it would require us to add both robolectric and junit to the app compile options, which lifts it up into the 65k limit while dexing. So unfortunately not practical for us at the moment.

**Comment by jongerrish** [comment]
Dmitrii,

Would you mind posting a PR for this?

Jonathan

**Comment by karlicoss** [comment]
@jongerrish oops, almost forgot. Here it is https://github.com/robolectric/robolectric/pull/1836

**Comment by jongerrish** [comment]
Wow, thanks for the fast response. As soon as the build goes green I'll
merge.

**Comment by karlicoss** [comment]
By the way, a small remark: one should understand that if he wants to shadow a non-android class, it is most likely a dirty hack and something temporary. I did that myself several times to quickfix some weird issues with third-party libraries which somehow interfered with my tests. Later I encapsulated these libraries behind interfaces, injected production implementations in the real Application, and test implementations (mostly, no-ops and mocks) in the test Application. (Personally, I prefer Dagger 2 for injections, Mockito for mocking).

**Comment by jongerrish** [comment]
Agree with you there.

**Comment by erd** [comment]
Agreed @karlicoss. +1

**Comment by erd** [comment]
Sounds like this should be fixed by #1836.
