### ISSUE TITLE
"Could not Dispatch event" error when using otto

### ISSUE THREAD

**Issue by rubsnick** [robolectric/robolectric#1833]
I'm update my robolectric to RC3 and now test that pass in RC2 are failing all with the same error.

`java.lang.RuntimeException: Could not dispatch event: class com.domain.app.event.net.GetAddEvent to handler [EventHandler public void com.domain.app.fragment.Fragment.onGetAddEvent(com.domain.app.event.net.GetAddEvent)]: java.lang.IllegalStateException: Illegal connection pointer 14073. Current pointers for thread Thread[pool-1-thread-1,5,main] [14165, 14201]`

If I go back to RC2 I'm having inflate exception errors for my Toolbars that are using calligraphy in the toolbar layout.  Any suggestions would be appreciated.

**Comment by jongerrish** [comment]
Could it be related to this commit:- https://github.com/robolectric/robolectric/commit/4dd0d23ce039ba08687f85e62a6c39d3f8741c84

**Comment by jongerrish** [comment]
Sometimes there is a connection pointer in the map, but not the right one:-

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-2-thread-1,5,main] [53]

Othertimes there is no connection pointer in the map:-

java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-2-thread-1,5,main] []

See: org.robolectric.shadows.ShadowSQLiteConnection.Connections#connectionsMap

**Comment by nenick** [comment]
@rubsnick Please try if my answer works for you https://github.com/robolectric/robolectric/issues/1890#issuecomment-111726535

**Comment by utzcoz** [comment]
Please test it with latest Robolectric version to check whether it has been fixed, and the Robolectric version related to this issue is too old. Feel free to reopen this issue if you find that this issue still exists with latest Robolectric 4.9. Thanks.
