### ISSUE TITLE
Reading XML attribute with backslashes does improper escaping

### ISSUE THREAD

**Issue by metalhead8816** [robolectric/robolectric#1835]
<View
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:customAttribute="\\d+" />

Reading customAttribute from Android produces "\d+". (Seen in toString() as "\d+")
Reading customAttribute from Robolectric produces "\\d+". (Seen in toString() as "\d+")

**Comment by metalhead8816** [comment]
Ugh. GitHub removed my escaping too. Point is that Robolectric seems to be appending extra escaping. More than is necessary.

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding resources-related issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
