### ISSUE TITLE
Renaming files with version 3.0-rc3

### ISSUE THREAD

**Issue by llfbandit** [robolectric/robolectric#1841]
File deletion works much better with rc3 now, but there's still a problems with file renaming.

Tested with J.W. DiskLruCache class when validating an edition (renaming dirty record to a clean one) on windows 8.1.

**Comment by lexs** [comment]
What is the actual problem? Is this something specific to Windows?

**Comment by llfbandit** [comment]
Sorry, my case is only related to windows.
I close the issue.

**Comment by lexs** [comment]
No I don't think you have to close the issue. It's just that I don't know what the issue is as I don't personally use Windows for development.

**Comment by llfbandit** [comment]
The File#renameTo method was failing on windows with Robolectric because of the locking file from this OS.
So, there's nothing related to robolectric because an unclosed stream from upper layers in my own source code was the problem. Windows is more restrictive on this part than linux.

Thanks for persistence !
