### ISSUE TITLE
Junit version

### ISSUE THREAD

**Issue by ismail-s** [robolectric/robolectric#1843]
Is there a reason why the junit version is 4.8.2? Another import in my project is using 4.12 which is resulting in conflicts.
Aldo, 4.8.2 is from way back in 2010, according to http://mvnrepository.com/artifact/junit/junit.

**Comment by erd** [comment]
No good reason that I know of. We just haven't had any motivation to bump the version number.

**Comment by jaredsburrows** [comment]
Simply just add the latest version to your dependencies:

    dependencies {
        testCompile 'junit:junit:4.12'
    }

**Comment by jaredsburrows** [comment]
@erd Either @ismail-s can make a pull request for this or we can just close this.

**Comment by ismail-s** [comment]
Just close it. I will try out the suggestion above, but if it doesn't work,
I will work around it by making the other local library I am using use the
older version of junit.

**Comment by jaredsburrows** [comment]
@ismail-s  You should be fine by added JUnit 4.12 to your project. You or a collaborate such as @erd are the only ones that can close this issue.
