### ISSUE TITLE
Not possible to test partial execution of animations with rc3

### ISSUE THREAD

**Issue by holmari** [robolectric/robolectric#1844]
The following test case will fail. It worked with Robolectric 2.4. Now, if you pause the scheduler, and run an animation afterwards, it will be finished even if its length is longer than the advanced duration.

```
@Test
  public void test_whenAnimationIsPlayedPartially_ValuesAreAsExpected() {
    final ValueAnimator animator = ValueAnimator.ofInt(0, 10);
    animator.setDuration(200);

    Robolectric.getForegroundThreadScheduler().pause();

    animator.start();

    Robolectric.getForegroundThreadScheduler().advanceBy(100);

    assertThat(animator.isRunning()).isTrue();
    assertThat(animator.getAnimatedFraction()).isLessThan(10.f);
  }
```

Also, infinite animations are played infinitely, which blocks test execution.

**Comment by jongerrish** [comment]
Is this issue fixed with #1821 ? If its still an issue with Robolectric 4.0 please reopen.
