### ISSUE TITLE
application.onCreate happens too late

### ISSUE THREAD

**Issue by t-rad679** [robolectric/robolectric#1852]
I guess it could be intentional, but, during setupApplicationState, the call to application.onCreate is the last thing to happen.  This seems counter intuitive; as the application object will often need to be fully initialized in order to create many of the other objects needed...in my case, it is a BroadcastReceiver defined in the AndroidManifest.  This is causing an NPE when initializing Robolectric, and I am unable to run my tests as a result.   If this is intended behavior, please let me know and give me the workaround, if you have one.  In any case, thank you for your time.

**Comment by jaredsburrows** [comment]
You are initializing your `BroadcastReceiver` in your `Application#onCreate()`? Why not register in your `MainActivity`?

**Comment by jaredsburrows** [comment]
@erd Issues like these just clutter the repos "issues". We should be able to close out many issues like these.

**Comment by erd** [comment]
The work that is done before `onCreate` in `setupApplicationState`, sets up the system so we can create the application. Could you share some code that shows the problem?

**Comment by xian** [comment]
Please reopen if this is still an issue. Thanks!
