### ISSUE TITLE
The shadow when call `Application.startActivity()` directly and got by `ShadowApplication.getInstance()` are two instance

### ISSUE THREAD

**Issue by Ponyets** [robolectric/robolectric#1856]
I'm writing a testcase with 3.0-SNAPSHOT, in which application context startActivity directly. I call `ShadowApplication.getInstance().peekNextStartActivity()`,  the return is null.
I debug and dig into it, find that the shadow application created by TestRunner to call startActivity method  and the shadow application I got by call `ShadowApplication.getInstance()` are different.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
