### ISSUE TITLE
Robolectric throws NotFoundException for resource of type raw

### ISSUE THREAD

**Issue by abusuioc** [robolectric/robolectric#1863]
Issue #1814 addresses a similar issue, but it was closed and it seems I cannot re-open it.

The issue, in my case, has to do with layout files having a reference to a raw type resource.
The exception thrown by Robolectric is:

> java.lang.RuntimeException: huh? ResName{ch.tutti:raw/ic_favorites} at
> org.robolectric.shadows.Converter.convertAndFill(Converter.java:99)

Browsing the code, it's clear that the raw case is not taken into account. The other types return nothing anyway, so could the "raw" case also return nothing instead of throwing an exception?

**Comment by erd** [comment]
Which version of Robolectric are you using?

**Comment by abusuioc** [comment]
My bad for not mentioning.
I'm using the latest available version, the 3.0-rc3 .

**Comment by colabug** [comment]
Having the same issue for a drawable in the raw folder. Worked well when specified in Java, but not in XML.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
