### ISSUE TITLE
BitmapDrawables always equal when compared

### ISSUE THREAD

**Issue by dpkirchner** [robolectric/robolectric#1872]
This test fails, but I think it should succeed:

```
    @Test
    public void testDupe() {
        Resources resources = Robolectric.setupActivity(Activity.class).getResources();
        Bitmap bitmap = Bitmap.createBitmap(1, 1, Bitmap.Config.RGB_565);
        BitmapDrawable drawable = new BitmapDrawable(resources, bitmap);

        Bitmap testBitmap = Bitmap.createBitmap(1, 1, Bitmap.Config.RGB_565);
        BitmapDrawable testDrawable = new BitmapDrawable(resources, testBitmap);
        assertNotEquals(drawable, testDrawable);
    }
```

The problem appears to be `ShadowDrawable#hashCode` and `ShadowDrawable#equals` both rely on the just the bounds, intrinsicWidth, and intrinsicHeight of the drawable. I'm not sure what the best solution would be but I suspect including `this.realBitmapDrawable.getBitmap().hashCode()` would be enough.

This is based on an older 3.0-SNAPSHOT but the code appears unchanged since that snapshot was made.

**Comment by erd** [comment]
We probably shouldn't be shadowing `hashCode` and `equals` and just let the code fallback the real implementation.

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) no longer shadows `equals()` for bitmaps. Thank you!
