### ISSUE TITLE
Cant find projects src files

### ISSUE THREAD

**Issue by jonneymendoza** [robolectric/robolectric#1873]
Hi. 

i am using the latest 3.0 of robolectric along with Android stidio 1.2 and trying to run my unit tests but i get an error that states how it cannot find any class referenced in my main src folder?

Here is my test code

@Config(constants = BuildConfig.class, emulateSdk = 18 )
@RunWith(RobolectricGradleTestRunner.class)
public class LoginTest {

    private NetworkDeligatorImpl networkDeligator;

    @Before
    public void setup() throws Exception {
        networkDeligator = new NetworkDeligatorImpl();
    }

    @Test
    public void testLogin() throws IOException, LMExceptionError {

        CustomerAccountRequest customerAccountRequest = new CustomerAccountRequest();

        customerAccountRequest.setPassword("Password01");
        customerAccountRequest.setRememberMe(true);
        customerAccountRequest.setUsername("jono1408@gmail.com");

        CustomerAccount customerAccount = networkDeligator.login(customerAccountRequest);

        Assert.assertNotNull(customerAccount);
        Assert.assertEquals(true, customerAccount.isValid());
    }

}

Error i get:

/Users/me/Work/Project/projectLib/src/test/java/com/jon/project/BillingdetailsTest.java:27: error: cannot find symbol
        JRActivity activity = Robolectric.setupActivity(JRActivity.class);
        ^
  symbol:   class JRActivity

**Comment by erd** [comment]
I don't think this is an error with Robolectric. It is most likely an issue with how your project is configured. Please take a look at http://robolectric.org/getting-started/ or the sample projects in the repo `robolectric-samples`. The sample projects repo has several good examples on how to setup a project with Robolectric.

**Comment by jonneymendoza** [comment]
my project is configured as per normal . not sure how this is anything to do with my project configurations as its configured by androids gradle default way????
