### ISSUE TITLE
KXmlParser java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

### ISSUE THREAD

**Issue by Pratyul** [robolectric/robolectric#1876]
I get this error whenever I call XmlPullParser.next. 

java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V
	at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1145)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)

I am using 3.0-rc3

**Comment by erd** [comment]
It doesn't look like we are instrumenting classes in `org.kxml2` so the added `arraycopy` intrinsics added by Google are not getting replaced.

**Comment by tcw48** [comment]
Any update or work around for this?

**Comment by zsperske** [comment]
An update or workaround would be greatly appreciated.

**Comment by Pratyul** [comment]
For now I added the sdk version as 19 for the particular test class. 
That seems to be working and is a possible workaround

**Comment by AstralStorm** [comment]
Showed up again with robolectric 4.0-alpha-2. Using the modified android-kxml2 package from #630 or changing sdk level works around it.
