### ISSUE TITLE
index.html report is always empty

### ISSUE THREAD

**Issue by shawnlu123** [robolectric/robolectric#1878]
Hi
I am trying to integrate jacoco code coverage when I noticed that in each module, the consolidated test report "index.html" is always empty.
However the package specific reports are not.
![screen shot 2015-06-08 at 2 08 33 pm](https://cloud.githubusercontent.com/assets/10440206/8045456/4706f92c-0de8-11e5-8e37-d89058b60214.png)
Can someone please give me some clue how to consolidate them to "index.html"? Thanks!

**Comment by erd** [comment]
I'm going to close this since it is not directly related to Robolectric.
