### ISSUE TITLE
Inconsistent with Android in loading multi-typed custom attributes

### ISSUE THREAD

**Issue by tec27** [robolectric/robolectric#1881]
Robolectric's resource loader seems to be inconsistent with the Android framework in how it loads custom style attributes when those attributes have multiple types (e.g. they accept both a reference to a typed array as well as a single color, or accept both a color or a string, etc.)

Example:
In `attrs.xml`, declare a custom attribute on a custom styleable view:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <declare-styleable name="MyCustomView">
    <attr name="myCustomAttr" format="reference|color" />
  </declare-styleable>
</resources>
```

Then, in your custom view class you obtain these styled attributes:

``` java
public MyCustomView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
  super(context, attrs, defStyleAttr, defStyleRes);
  TypedArray typed = context.obtainStyledAttributes(attrs, R.styleable.MyCustomView,
        defStyleAttr, defStyleRes);
  // ...
}
```

Given the above declarations, XML declarations such as the below will work fine:

``` xml
<com.package.MyCustomView
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  app:myCustomAttr="#ffffff" />

<com.package.MyCustomView
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  app:myCustomAttr="@color/myCustomColor" />
```

These will work because Robolectric is essentially expecting that "reference|color" means "a reference to a color, or a literal color value". It basically discards the "reference|" part of that declaration, assuming that by resolving references it will end up at a color value, and thus when obtaining styled attributes can simply try to convert directly from the XML string value to a color.

Thus, when you try to reference something other than a color:

``` xml
<com.package.MyCustomView
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  app:myCustomAttr="@array/myColorArray" />
```

You get a stack trace where Robolectric is clearly trying to parse an array reference into a color value:

```
Caused by: java.lang.NumberFormatException: Color value '@com.package:array/myColorArray' must start with #
    at org.robolectric.shadows.ResourceHelper.getColor(ResourceHelper.java:43)
    at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:259)
    at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:255)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:157)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
    at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.$$robo$$obtainStyledAttributes(Context.java:472)
    at android.content.Context.obtainStyledAttributes(Context.java)
```

The difference between Robolectric and Android here is seemingly that Robolectric tries to eagerly convert the values. That is, it wants to generate a `TypedArray`-like structure where it knows (from the `R.styleable` entry) exactly what types each of the values have and pre-convert them to those types. Android's `TypedArray` usage, however, lets application code inspect the types of the attributes it has loaded via `TypedValue` and only then do a conversion. For example, my custom view has code like:

``` java
TypedValue colorValue = new TypedValue();
typed.getValue(
    R.styleable.MyCustomView_myCustomAttr,
    colorValue);

if (colorValue.type == TypedValue.TYPE_REFERENCE) {
  return getResources().getIntArray(colorValue.data);
} else {
  // It must be a single color
  return new int[] { colorValue.data };
}
```

It seems like Robolectric should be lazier when it reads these resources (or at the very least, handle the case where a reference doesn't get recursively resolved to a literal value and not try to convert it).

For the time being, my workaround is to split my custom attribute into two: one that is meant to be an array reference, and one that is a single color reference.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
