### ISSUE TITLE
Mock network response in Robolectric 3

### ISSUE THREAD

**Issue by ChrisZou** [robolectric/robolectric#1883]
Hi, I'm using robolectric 3.0-rc3 to do unit testing. I wonder how can it mock network response. I did some search and found something like `Robolectric.addPendingHttpResponse()` or `Robolectric.addHttpResponseRule`. But none of them seem to exist in robolectric 3. And the API documentation I found in robolectric.org seems to be of version 2.4.

**Comment by erd** [comment]
> I wonder how can it mock network response

If you're starting from scratch (no existing tests), I would recommend using Square's mockwebserver (https://github.com/square/okhttp/tree/master/mockwebserver). It is networking library agnostic so should work however use choose to make networking requests.

> But none of them seem to exist in robolectric 3

Those classes have moved to an add-on module (see http://robolectric.org/using-add-on-modules). In particular, the networking stuff has moved to `org.robolectric:shadows-httpclient`. The methods that were on `Robolectric` have moved to `FakeHttp`.

> And the API documentation I found in robolectric.org seems to be of version 2.4.

The docs will be updated once 3.0 is finalized.

**Comment by ChrisZou** [comment]
I see. @erd Thank you!

**Comment by zwebie** [comment]
@erd why do you recommend using mockwebserver and not FakeHttp?

**Comment by erd** [comment]
@zwebie FakeHttp only works with HttpClient, since it stubs the method calls. Mockwebserver will work with all HTTP libraries since it runs an actual server for the tests.

**Comment by martinbaciga** [comment]
You can add this to your build.gradle file:

```
testCompile 'org.robolectric:shadows-support-v4:3.0'
testCompile 'org.robolectric:shadows-httpclient:3.0'
```

And then on your test you will find this method _addPendingHttpResponse_ on FakeHttp class. 
Here's an example:


```
@Test    
public void shouldReturnRequestsByRule_MatchingMethod() throws Exception {
        FakeHttp.setDefaultHttpResponse(404, "no such page");
        FakeHttp.addHttpResponseRule(HttpPost.METHOD_NAME, "http://some.uri",
                new TestHttpResponse(200, "a cheery response body"));

        HttpResponse response = requestDirector.execute(null, new HttpGet("http://some.uri"), null);

        Assert.assertNotNull(response);
        Assert.assertEquals(response.getStatusLine().getStatusCode(), 404);
 }
```
