### ISSUE TITLE
Robolectric classloader doesn't load Android classes when Clojure imports them

### ISSUE THREAD

**Issue by alexander-yakushev** [robolectric/robolectric#1887]
Let me briefly describe my setup. I have a single JUnit test file with a single test. That test file is marked with `@RunWith(RobolectricTestRunner)` and its single purpose is to execute the Clojure code and Clojure tests. Hence, Clojure is loaded after Robolectric is loaded.

The problem is all `android.*` classes that are required by Clojure code appear to be loaded with the basic `AppLoader` classloader. All other classes (Clojure and Java classes) are loaded with Robolectric's instrumented classloader. Any Android classes that are loaded before Clojure (e.g. required in my top-level JUnit test file) are loaded with Robolectric's classloader all right. Another weird thing is that if I launch a Clojure REPL in that environment, and call `Class.forName` manually with Robolectric's loader, the class is correctly loaded by Robolectric.

I've tracked the issue down to the place where `Class.forName(classname, true, instance_of_robolectric_loader);` is called, and it successfully returns a Class object, but calling `klass.getClassLoader()` on it returns Sun's `AppLoader`. So it appears that Robolectric's classloader fails to load the class and silently passes the loading to the parent loader.

My question: is there any way to make Robolectric's classloader more verbose so that it tells me what's going on and why it refuses to load Android classes at that certain point of time?

Once again, the time sequence:
- Entry point - JUnit test case - Android classes are correctly loaded by Robolectric
- Clojure loading is initiated - Android classes are loaded by top-level loader
- Clojure finishes loading, produces a REPL - Android classes can be correctly loaded by Robolectric again.

**Comment by lexs** [comment]
What class is loaded with the `Class.forName()` call? Classes may be delegated to the parent class loader (such as Java classes).

What is the crash you are seeing? A stack trace could tell us more what is going wrong.

**Comment by alexander-yakushev** [comment]
Like I've said, only `android.*` classes fail to be loaded with Robolectric's classloader. By "failed to be loaded" I mean that `Class.forName()` is called on them with robolectric's classloader, but the class that comes out of it returns Sun's classloader on `klass.getClassLoader()`.

Crash that I see is the usual `java.lang.RuntimeException: Stub!` when I try to call any Android stuff. Which is understandable because Android classes I try to use are loaded with Sun's classloader. Other than that I don't see any other exceptions which is why I created the issue.

Another minor detail: for example, I can create a new `android.app.Activity` object just fine from Clojure. I think because there is a list of Android classes Robolectric loads on initialization, and Activity is one of them. So since Activity is already loaded, `Class.forName()` on it returns a correct class loaded by Robolectic's classloader.

**Comment by shurane** [comment]
@alexander-yakushev is it possible to post a minimal setup that can recreate the issue for us?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
