### ISSUE TITLE
Doesn't work with some view animation libraries, stuck in Robolectric.setupActivity

### ISSUE THREAD

**Issue by ChrisZou** [robolectric/robolectric#1889]
Hi, I was using a third-part library called [CircularProgressView](https://github.com/rahatarmanahmed/CircularProgressView) and robolectric (3.0-rc3) for unit test. I found that unit test will stuck in `Robolectric.setupActivity`.

```Java
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        CircularProgressView progressView = (CircularProgressView) findViewById(R.id.progress_view);
        progressView.startAnimation();
    }
}

@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class MainActivityTest {
    @Test
    public void testMainActivity() {
        MainActivity mainActivity = Robolectric.setupActivity(MainActivity.class);
        Assert.assertNotNull(mainActivity);
    }
}
```

The program will stuck in `setupActivity()` and the assertion will never be reached. And if I comment out `progressView.startAnimation();`, then everything works fine. I don't know if its a problem of CircularProgressView or of Robolectric, but would you take a look at this?

**Comment by erd** [comment]
See #1879.

**Comment by erd** [comment]
This is essentially the same issue as #1877.
