### ISSUE TITLE
ShadowMultiDex on 3.0-rc3 no longer shadowing

### ISSUE THREAD

**Issue by dpkirchner** [robolectric/robolectric#1906]
Best I can tell ShadowMultiDex is not being used when running tests. The exception I get suggests that the Android version of MultiDex is used instead:

```
Caused by: java.lang.RuntimeException: Multi dex installation failed (/Users/dpk/Documents/project/app/. (Is a directory)).
	at android.support.multidex.MultiDex.install(MultiDex.java:178)
	at android.support.multidex.MultiDexApplication.attachBaseContext(MultiDexApplication.java:39)
	at android.app.Application.attach(Application.java:181)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:131)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
```

The test code worked prior to 3.0-rc3 and indeed works when I tell gradle to load 3.0-rc2, as long as I'm using ShadowMultiDex from the latest master as suggested here:

https://github.com/robolectric/robolectric/issues/1328

Deleting that ShadowMultiDex from my project so it falls back to the jar-provided version doesn't fix the problem, FWIW.

**Comment by erd** [comment]
I just tested this by modifying `robolectric-samples/android-api-21` to use the `multidex` library and `shadows-multidex` add-on and didn't see any problems. Could you put a sample project up on github so I can take a look?

**Comment by erd** [comment]
I wasn't able to reproduce this. Feel free to re-open if you can provide a sample project that demonstrates the problem.

**Comment by markcerqueira** [comment]
@erd - would it be possible for you to share the modified version of android-api-21 that you mentioned not seeing any problems? I'm trying to get multi-dex working but documentation and examples appear to be pretty sparse on the matter.

Thanks!

**Comment by dpkirchner** [comment]
Thanks, the shadows-multidex hint was what I needed.

@markcerqueira You'll need to include this line in your build.gradle:

    testCompile "org.robolectric:shadows-multidex:3.0"

**Comment by markcerqueira** [comment]
@dpkirchner - I have that line my build.gradle, but I still see this exception when I run my tests.

```java
Could not load class: org.robolectric.shadows.ShadowMultiDex
java.lang.RuntimeException: Could not load class: org.robolectric.shadows.ShadowMultiDex
	at org.robolectric.annotation.Config$Implementation.parseClass(Config.java:147)
	at org.robolectric.annotation.Config$Implementation.parseClasses(Config.java:156)
	at org.robolectric.annotation.Config$Implementation.fromProperties(Config.java:135)
	at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:362)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:177)
```

**Comment by markcerqueira** [comment]
Solved my issue with some help from @jaredsburrows. Thanks Jared!

My gradle file has these lines:

```gradle
  testCompile('org.robolectric:robolectric:3.0-rc3')
  testCompile('org.robolectric:shadows-multidex:3.0')
````

And I remove the shadows= from the roboelectric.properties file because that is only used for custom shadows.

**Comment by jaredsburrows** [comment]
@markcerqueira that's good! Can you close this and your stackoverflow issue?

**Comment by markcerqueira** [comment]
@jaredsburrows - this issue appears to be closed already (I did not re-open it). I will go ahead and close the StackOverflow issue now. Cheers and thanks again for the help!

**Comment by dpkirchner** [comment]
I can confirm this issue has been resolved in the 3.0 release.

**Comment by Aeiric** [comment]
any one solved this problem?could you paste your code?thanks!!

**Comment by vjscode** [comment]
@Aeiric 
You will have to add the following lines
`    testCompile 'org.robolectric:robolectric:3.0'`
`    testCompile('org.robolectric:shadows-multidex:3.0')`

My application class has this

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

**Comment by Aeiric** [comment]
@vjscode @dpkirchner @markcerqueira  thanks,but a new question is "NoClassDefFoundError " ,it appears when my Activity uses other class which is Android Library .This is in issue  #1796~ Seems opened.I've no good idea.-.-

**Comment by Aeiric** [comment]
@vjscode the third library "Realm"(https://realm.io/docs/java/latest/#robolectric)  says "This means that for now it is not possible to test Realm using Robolectric." So I was blocked where i use the realm in my Activity ,so  i guess if "mock" works.But i don't know how to mock an Object which the data comes from realm and the code is in the Activity ,or  custom shadow an object.
My tests bolcked in these places like
   **@Override
    protected void onResume() {
        super.onResume();
        if (UserManager.isUserLogin()) {
            onBackPressed();
        }**
Here is the class,the "UserManager" imports class "DBUser" which imports "Realm"
**public class UserManager {
    private static DBUser loginUser;

    static {
        initLoginUser();
    }

    public static DBUser getLoginUser() {
        if (isUserLogin()) {
            return loginUser;
        } else {
            return null;
        }
    }

    public static void initLoginUser() {
        loginUser = HBRealm.getInstance().findFirst(DBUser.class);
    }

    public static boolean isUserLogin() {
        if (loginUser != null && !loginUser.isValid()) {
            initLoginUser();
        }
        if (loginUser == null || TextUtils.isEmpty(loginUser.getUserId())) {
            return false;
        }
        return true;
    }

    public static String getUserId() {
        if (isUserLogin()) {
            return loginUser.getUserId();
        } else {
            return null;
        }
    }

    public static String getUserName() {
        if (isUserLogin()) {
            return loginUser.getUserName();
        } else {
            return null;
        }
    }** 
 any good ideas to "mock" or "shadow",thanks a lot!

**Comment by jongerrish** [comment]
Don't shadow your own code.

In fact prefer not to shadow any code (other than framework code - any then
contribute that back to Robolectric).

You should refactor this class above to not use statics, i.e: inject an
instance of UserManager class into your Activity or whatever and use a mock
in tests.

**Comment by Aeiric** [comment]
@jongerrish thanks,but the code blocked in Activity like
**@Override
protected void onResume() {
super.onResume();
if (UserManager.isUserLogin()) {
onBackPressed();
}**
Actually blocked at line "if (UserManager.isUserLogin())",how to mock  ,can you give some clear code?

**Comment by jongerrish** [comment]
Don't use static methods?

**Comment by Aeiric** [comment]
@jongerrish ,the static method is used a lot in the project ,and the code can not be easily changed.So any good ideas to deal with this ?thanks~~

**Comment by jongerrish** [comment]
If you own the code then you can change it, no?

With Mockito you cannot mock static methods, that's just the way the
language works. You could try Power Mock but this doesn't work with
Robolectri yet.

Your best bet is always to design your application for testability.

**Comment by Aeiric** [comment]
thanks any way,but it does not works for me~ .I joined the project recently and these static methods in the  project are not changed easily.I am looking for some good ways to solve that~
