### ISSUE TITLE
Create Wiki page to explain "Reporting issues for Robolectric"

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#1907]
## Background:
@erd:

> I'd prefer creating a wiki page that we can link to that explains what information we need and how to write a good issue. If people had an idea of what information we needed, it might help to improve issue quality. When someone opens an issue with a stacktrace, we can kindly refer then to the wiki page. If they don't follow up in a reasonable amount of time (~7 days or so), we'll close the issue.

## Example outline:

**For Robolectric Snapshot:**
These should be marked with 3.1(You can do this Erich since you are an "owner")

**Example explanation:**
This is not a support forum. Robolectric Github issues contains known issues with Robolectric and tracks enhancement requests, for people working directly with source code. Please search existing issues (including closed ones) before submitting new reports. 

**Users should include when creating issues:**
 - Include a meaningful summary
 - Details about the device
 - Android version
 - Reproduction steps.

**Comment by erd** [comment]
You should be able to edit the wiki directly. If not, I created a page for you to place the content in:

https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues
