### ISSUE TITLE
NullPointerException at ShadowDownloadManager.java:52

### ISSUE THREAD

**Issue by ajhuntsman** [robolectric/robolectric#1908]
I'm on 3.0-rc3 and getting this, which I never use to get:

`java.lang.NullPointerException
	at org.robolectric.shadows.ShadowDownloadManager.query(ShadowDownloadManager.java:52)
	at android.app.DownloadManager.query(DownloadManager.java)`

**Comment by kriegfrj** [comment]
Can you post a little bit more of your stack trace, and/or some code to reproduce the problem? Thanks!

**Comment by ajhuntsman** [comment]
On app startup, my MainActivity builds an adapter, which is used in my navigation drawer. Each item in the adapter represents a file which may be downloaded if it's not already installed.

My adapter uses AsyncTask to query my own FileService, to determine if any file downloads are happening in the background. In turn, my FileService queries the Android Download Manager by status, to see if any files are downloading.

Here's the snippet from my FileService method which is throwing the Robolectric exception:
`// Query the download manager by status types
        List<Long> downloadIDs = new ArrayList<>();
        DownloadManager.Query query = new DownloadManager.Query();
        query.setFilterByStatus(DownloadManager.STATUS_PENDING | DownloadManager.STATUS_RUNNING | DownloadManager.STATUS_PAUSED);

        // Note: the cursor will be null if the download manager is disabled
        Cursor cursor = App.getDownloadManager().query(query);
        while (cursor != null && cursor.moveToNext()) {
            downloadIDs.add(cursor.getLong(cursor.getColumnIndex(DownloadManager.COLUMN_ID)));
        }

        if (cursor != null) {
            cursor.close();
        }`

This is the last line of my code in the stack trace:
`Cursor cursor = App.getDownloadManager().query(query);`

Which produces this stack trace:
`java.lang.NullPointerException
	at org.robolectric.shadows.ShadowDownloadManager.query(ShadowDownloadManager.java:52)
	at android.app.DownloadManager.query(DownloadManager.java)
	at org.acme.myapp.service.file.FileService.getDownloadingFiles(FileService.java:447)`

**Comment by jaredsburrows** [comment]
@kriegfrj I have been working on this: https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues to help people report issues.

**Comment by kriegfrj** [comment]
:+1: to the issue report wiki!

**Comment by jaredsburrows** [comment]
@kriegfrj Feel free to add to it!

**Comment by erd** [comment]
The above PR should fix the NPE. Looking at the code, thought, it doesn't seem like `ShadowDownloadManager` will handle the case where you are only calling `setFilterByStatus`.
