### ISSUE TITLE
Differences between Robolectric 2.4's getUiThreadScheduler() and 3.0's getForegroundThreadScheduler()?

### ISSUE THREAD

**Issue by harrisonhe309** [robolectric/robolectric#1909]
In my tests, I'm running into a concurrency issue that I never ran into with getUiThreadScheduler(). In my test, I add two runnables to a handler. The first runnable sets up an object, and the second one sets the listener up for the object. While debugging, I noticed that with Robolectric 3.0, it executed the second runnable first in advanceToLastPostedRunnable(), whereas in Robolectric 2.4 it would execute the first one. This is causing a fair amount of my unit tests to fail from NullPointerExceptions as it tries to set up the listener on an uninitialized null object - so my question is, in order to modify the tests, could anybody provide any clarity on any potential changes from getUiThreadScheduler() and getForegroundThreadScheduler()?

The code in questions:

        Robolectric.getUiThreadScheduler().pause();
        myClass.start();            // adds two runnables, one to initialize an object and one that uses the object
        assertEquals(Robolectric.getUiThreadScheduler().size(), 2);
        Robolectric.getUiThreadScheduler().unPause();

**Comment by erd** [comment]
`getUiThreadScheduler` and `getForegroundThreadScheduler` are the same method, but there have been some changes (with still more to come) to how the underlying schedulers work. See #1879 for details and links to other issues.
