### ISSUE TITLE
No tests found when running parameterized tests with --tests flag

### ISSUE THREAD

**Issue by hidroh** [robolectric/robolectric#1912]
I'm using 3.0-rc3. Android Gradle plugin `--tests` flag as described [here](http://tools.android.com/tech-docs/unit-testing-support) works perfectly for me when running tests annotated with `@RunWith(RobolectricGradleTestRunner.class)`, but I get the following message when trying to use the same flag to run tests annotated with `@RunWith(ParameterizedRobolectricTestRunner.class)`:

```
Execution failed for task ':app:testDebug'.
> No tests found for given includes: [xxx.SomethingTest]
```

The parameterized tests still run when all tests are executed of course. They are just not executed when attempted individually.

Is this by design or an issue?

**Comment by kageiit** [comment]
I don't think it has anything to do with Robolectric. This is a known Gradle issue: https://issues.gradle.org/browse/GRADLE-3112

**Comment by erd** [comment]
Thanks for the info @kageiit

**Comment by hidroh** [comment]
Thanks @kageiit for clarifying :+1:
