### ISSUE TITLE
Robolectric does not instantiate views in onCreate() causing NPE in any activity that accesses a view in onCreate

### ISSUE THREAD

**Issue by Earthblood** [robolectric/robolectric#1916]
Using: org.robolectric:robolectric:3.0-rc3

I have a base Activity that initializes a navigation drawer in it's onCreate method by setting an adapter on an ExpandableListView and setting a drawerListener on a DrawerLayout. Any tests on activities that extend from this class fail when building the activity because the previously mentioned views are null and presumably will not be injected until onContentChanged() is called.

e.g.
Robolectric.buildActivity(MyActivity.class).create() //causes NPE

I am not sure whether this is a bug or by design. How should this be handled?

**Comment by jaredsburrows** [comment]
Are you new to Robolectric? What have you tried? Can you show us your actual test and code?

This works fine for me:

    MainActivity mainActivity = Robolectric.buildActivity(MainActivity.class).create().start().resume().visible().get();

**Comment by Earthblood** [comment]
No, I have been using robolectric for a few years now. I am aware that buildActivity works fine normally, but if you call a method on a view in onCreate() you get a NPE.

I have listed an example of my code here:
http://stackoverflow.com/questions/31059009/robolectric-leaving-null-views-in-oncreate-of-activity

**Comment by Earthblood** [comment]
I think the issue I am seeing relates to using a DrawerLayout. Here is an example layout, activity and test that generates a Null Pointer

mail_layout.xml

<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <ExpandableListView xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/left_drawer"
        android:layout_width="@dimen/navdrawer_width"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:listSelector="@color/android:transparent"
        android:choiceMode="singleChoice"
        android:divider="@android:color/transparent"
        android:dividerHeight="0dp"
        android:groupIndicator="@android:color/transparent"/>

</android.support.v4.widget.DrawerLayout>




public class MainParentActivity extends RoboActionBarActivity {

    @InjectView(R.id.title) TextView title;

    @InjectView(R.id.drawer_layout) DrawerLayout drawer;
    @InjectView(R.id.left_drawer)  ExpandableListView drawerList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        title.setText("my title");

    }
}


@ContentView(R.layout.main_layout)
public class MainActivity extends MainParentActivity {


    @InjectView(R.id.title) TextView title;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);


    }
}


@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class)
public class MainActivityTest  {
    
        @Test
        public void shouldNotCrash(){
    
            final MainActivity mainActivity =  Robolectric.buildActivity(MainActivity.class).create().get();
            assertNotNull(mainActivity);
        }
}

**Comment by Earthblood** [comment]
This issue went away now that I switched to the org.robolectric:robolectric:3.0-SNAPSHOT version

**Comment by jaredsburrows** [comment]
Nice!
