### ISSUE TITLE
Add support sendOrderedBroadcast(Intent intent, String receiverPermission, BroadcastReceiver resultReceiver, Handler scheduler, int initialCode, String initialData, Bundle initialExtras)

### ISSUE THREAD

**Issue by gruszczy** [robolectric/robolectric#1917]
Only sendOrderedBroadcast(Intent intent, String receiverPermission) is available, the more complex one doesn't do anything.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
