### ISSUE TITLE
SetCookie() fails for domain started with dot (.)

### ISSUE THREAD

**Issue by Ali-Rezaei** [robolectric/robolectric#1918]
I faced with a problem with setCookie(String url, String value) method when url starts with a dot (.) in the beginning. (such as .test-int.com). 

setCookie works properly when I test the app with this domain in dalvik vm, but it fails when I use Robolectric for testing in jvm. When I debugged I realized that it fails in ShadowCookieManager class in getOrigin(String url) method:

``` java
private CookieOrigin getOrigin(String url) {
    if (!(url.startsWith(HTTP) || url.startsWith(HTTPS))) {
      url = HTTP + url;
    }
    URI uri;
    try {
      uri = new URI(url);
    } catch (URISyntaxException e) {
      throw new IllegalArgumentException("wrong URL :" + url, e);
    }
    int port = (uri.getPort() < 0) ? 80 : uri.getPort();
    boolean secure = "https".equals(uri.getScheme());
    return new CookieOrigin(uri.getHost(), port, uri.getPath(), secure);
  }
```

host is null for uri and ofcourse getHost() returns null. (for domains which starts with dot as explained above)

**Comment by Ali-Rezaei** [comment]
For some unknown issue for me when I want to setCookie() for following String, it fails.

String cookieValue = "V; MAX-AGE=;";
cookieManager.setCookie(cookie.getDomain(), cookieValue);

When I getCookies() later from cookieManager, result is null. ( it just happens for following cookieValue )

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
