### ISSUE TITLE
android.os.Bundle doesn't implement equals() or hashcode(), but ShadowBundle does

### ISSUE THREAD

**Issue by charlesmunger** [robolectric/robolectric#1930]
This means that code that wouldn't work on real android (Set<Bundle>) works in Robolectric. This should be fixed.

**Comment by jaredsburrows** [comment]
So people do not have to search: https://github.com/robolectric/robolectric/blob/76a55f5c9386bbe455ec0f664b288870f507b3cb/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowBundle.java


Isnt that kind of the point of the Shadows? They offer "extra" insight just for testing.

Are you saying you are creating a "set" of `ShadowBundles`, thinking that someone by mistake would have created a set of actual `Bundles`?

In theaorry you should be able to `extend Bundle` and implement: https://github.com/robolectric/robolectric/blob/76a55f5c9386bbe455ec0f664b288870f507b3cb/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowBundle.java#L47

    private static Map getUnderlyingMap(Bundle bundle) { 
      return ReflectionHelpers.getField(bundle, "mMap"); 
    }

**Comment by erd** [comment]
> Isnt that kind of the point of the Shadows? They offer "extra" insight just for testing.

In the spirit of a "more real" robolectric, we've been removing this sorts of enhancements that make shadows behave differently than real android.

**Comment by jaredsburrows** [comment]
I guess the Shadow was too helpful :(
