### ISSUE TITLE
Unable to locate resource in repository

### ISSUE THREAD

**Issue by papo2608** [robolectric/robolectric#1941]
Hi,

if i execute my roboelectric test I get following error on my MAC:

Downloading: com/ximpleware/vtd-xml/2.11/vtd-xml-2.11.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
Unable to locate resource in repository
Downloading: com/ximpleware/vtd-xml/2.11/vtd-xml-2.11.pom from repository central at http://repo1.maven.org/maven2
[INFO] Unable to find resource 'com.ximpleware:vtd-xml:pom:2.11' in repository sonatype (https://oss.sonatype.org/content/groups/public/)

What's the problem? I tried a lot but the error is still occurring.

Roboelectric v3.0
gradle v2.4
androidBuildToolsVersion = '21.1.2'
androidMinSdkVersion = 15
androidTargetSdkVersion = 21
androidCompileSdkVersion = 21

BR,
Partrick

**Comment by alienscience** [comment]
I had the same problem. If you wait long enough the build will continue and try maven central.

**Comment by erd** [comment]
I don't think this is anything we can fix in Robolectric. I verified that com.ximpleware:vtd-xml:2.11 exists in Maven Central, so maybe there's some kind of sync issue with Sonatype?
