### ISSUE TITLE
Add support for android.support.v7.widget.PopupMenu

### ISSUE THREAD

**Issue by jonchui** [robolectric/robolectric#1944]
Many of our tests are using ShadowPopupMenu#getLatestPopupMenu, which extends the non-support lib version. 

Once we switch to the v7 support lib version of PopupMenu (:to support pre L devices), this no longer works. 
1. The way other teams have solved this seems to be to have their classes expose a getter for the PopupMenu. 
2. I'm creating a new ShadowPopupMenuSupperLib and ExtendedShadowApplication which extends ShadowApplication, to expose the new support lib PopupMenu (see http://cl/98246668). 

Any other tips or ideas? I guess i could also extend robolectric itself? but there are many other similar functions, #getLatestAlertDialog, #getLatestToast, etc.

**Comment by jongerrish** [comment]
I think we should add a ShadowPopupMenu in the support library module.

Do you want to summit a PR?

**Comment by jonchui** [comment]
Yup, can do that. 

However, doesn't seem like we have a v7 support lib? just v4?

Also, I believe i'd have to add a function to ShadowApplication, analogous to #getLatestPopupMenu, but that returns the support lib version?

**Comment by erd** [comment]
> However, doesn't seem like we have a v7 support lib? just v4?

We haven't had a need for a v7 lib yet, so we haven't created one. I don't mind adding the infrastructure for the v7 lib if you want to create a PR for `ShadowPopupMenu`.

> Also, I believe i'd have to add a function to ShadowApplication, analogous to #getLatestPopupMenu, but that returns the support lib version?

They don't necessarily have to be in `ShadowApplication` - they could just as easily be in `ShadowPopupMenu`. As long is there a static member that holds onto the last dialog shown, we should be good.

**Comment by jongerrish** [comment]
Erich, lets create the infrastructure for this, I think it will help
contributions for v7 stuff.

Hopefully the mvn build can handle aars, I think I had that problem last
time.

I'll help John with his PR.

Jonathan.

**Comment by erd** [comment]
I've pushed a branch named `shadow-appcompat-v7` to github that has the skeleton code for an appcompat-v7 add-on. When I run the `ShadowPopupMenu` test, I get: 

    java.lang.NoClassDefFoundError: android/support/v7/appcompat/R$attr

which looks similar to what people are reporting in #1737. Apparently aars don't contain compiled `R.class`, so `InstrumentingClassLoader` dies when it can't resolve the class. We could try and work around this in the classloader, but that might cause other issues.

**Comment by jongerrish** [comment]
There is an R.txt in the root of the aar, we could probably parse that.

**Comment by KevinLeighCrain** [comment]
@jonchui Any news on supporting v7 AlertDialog shadows?

**Comment by kschults** [comment]
Any update on this? It was in every milestone from 3.1 to 3.4, but nothing since. It would be really nice to have a shadow for the support AlertDialog.

**Comment by jongerrish** [comment]
We're generally of the policy that we don't want to support custom shadows for the support library. The support library team are really pro-testing so if you have any testing needs that are not fulfilled there please create a bug on the Google issue tracker. If you do, let me know and I might be able to help getting it prioritized.
