### ISSUE TITLE
Support calling a fragment's onDestroyView()

### ISSUE THREAD

**Issue by gkylafas** [robolectric/robolectric#1945]
According to the [Android docs of Fragment.onSaveInstanceState](http://developer.android.com/reference/android/app/Fragment.html#onSaveInstanceState%28android.os.Bundle%29):

> this method may be called at any time before `onDestroy()`

which means that it may be called after `onDestroyView()` and before `onDestroy()`. In that case, calling any `findViewById()` inside `onSaveInstanceState()` always returns `null` and will likely result in app crashes because of `NullPointerException`.

Unfortunately, there is no way at the moment to trigger this case with Robolectric and write a test to handle it. Ideally, we should  be able to run something like this:

``` java
FragmentController.of(fragment)
    .pause().stop().destroyView().saveInstanceState(bundle).destroy();
```

or

``` java
activityController.pause().stop().destroyFragmentsView().saveInstanceState(bundle).destroy()
```

**Comment by dlew** [comment]
`createView()` should also be supported along with this.

**Comment by MGaetan89** [comment]
`FragmentController` is now deprecated, and so is the underlying `android.app.Fragment` API.
The recommended alternative is to use [`FragmentScenario`](https://developer.android.com/guide/fragments/test).
We can probably close this issue?

**Comment by MGaetan89** [comment]
Closing this issue, since both `FragmentController` and `android.app.Fragment` are now deprecated.
You should be able to achieve what you want with `FragmentScenario`.
