### ISSUE TITLE
View.startAnimation locks up test

### ISSUE THREAD

**Issue by mttkay** [robolectric/robolectric#1947]
In a unit test for a view, we bumped into a problem with RL 3.0 where the test would lock up as soon as it hit `view.startAnimation`. I thought the problem might be because there is no shadow implementation for that method in `ShadowView`, oddly enough though it does have a passing unit test?

In any event, the test will call the real implementation of `View.startAnimation` since the shadow doesn't provide it, which will cause the test to lock up and eventually fail with a time out.

I tried to shadow this method myself, but realized that (unlike in Robolectric 1), you cannot provide shadow subclasses anymore that add `@Implementation`s?

> It is important Shadow methods are implemented on the corresponding Shadow of the class in which they were originally defined. Otherwise Robolectric's lookup mechanism will not find them

http://robolectric.org/extending/

That's a pretty big step backwards, since one has to patch the library directly now. It didn't install cleanly on my machine though so I gave up :-/

Maybe someone else can have a look?

**Comment by erd** [comment]
We've attempted to make animations more realistic, but there are some issues with how animation timing interacts with Robolectric. Some things work, some things don't. The relevant discussion issue is #1879.

**Comment by utzcoz** [comment]
Please test it with latest Robolectric version to check whether it has been fixed, and the Robolectric version related to this issue is too old. Feel free to reopen this issue if you find that this issue still exists with latest Robolectric 4.9. Thanks.
