### ISSUE TITLE
Error when compiling using Retrolambda and SourceCompatibility 1.8

### ISSUE THREAD

**Issue by jjvargas** [robolectric/robolectric#1948]
I am using Retrolambda and this options on Gradle 

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

When I try to run the tests with Roboelectric I get 

Error:Execution failed for task ':mcompileDebugUnitTestJavaWithJavac'.
invalid source release: 1.8

**Comment by erd** [comment]
Could you provide any additional information? I've used Retrolambda with Robolectric all the time without any issues. Without more information, or a sample project to look at, there's not much we can do.

**Comment by michaldrabik** [comment]
I am having similar issue. My build.gradle looks like this: 

    android {
      compileSdkVersion 22
      buildToolsVersion "22.0.1"

    compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
      applicationId "com.sample.sample"
      minSdkVersion 16
      targetSdkVersion 22
      versionCode 1
      versionName "0.1"
    }

    buildTypes {
      debug {
        minifyEnabled false
      }
      release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      }
    }
    }

    dependencies {
      libs here
    }

Sample test look like this:

    @RunWith(RobolectricGradleTestRunner.class)
    @Config(constants = BuildConfig.class, sdk = 21)
    public class MainActivityTest {

      private MainActivity activity;

      @Before
      public void setup() {
    activity = Robolectric.buildActivity(MainActivity.class).create().get();
      }

      @Test
      public void checkActivityNotNull() throws Exception {
        assertNotNull(activity);
      }

I have JAVA7_HOME and JAVA8_HOME set in Windows Env. Variables

**Comment by ZeroBrain** [comment]
ref issue of retrolambda : https://github.com/evant/gradle-retrolambda/issues/120

it occurred in this case:
Android Gradle - 1.3.0
Robolectric - 3.0
RetroLambda - 3.x

**Comment by erd** [comment]
From looking at the issue linked above, it looks like it was a bug with Retrolambda + Android Gradle 1.3.0. Feel free to re-open if the newest Retrolambda doesn't solve the problem.

**Comment by ZeroBrain** [comment]
@erd Retrolambda was fixed : https://github.com/evant/gradle-retrolambda/issues/120
