### ISSUE TITLE
sendOrderedBroadcast can not be called from a BroadcastReceiever onReceive() that was invoked by sendOrderedBroadcast()

### ISSUE THREAD

**Issue by leviyehonatan** [robolectric/robolectric#1949]
I have a project which calls sendOrderedBroadcast and invokes a broadcastReceiver which is registered. 

it seems as if the second (internal) call from the broadcast receiver is not being made using the Shadow handler for the sendBroadcastReceiver.

I would like to be able to do that call so i can test my project!

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
