### ISSUE TITLE
FragmentController does not have detach()

### ISSUE THREAD

**Issue by dlew** [robolectric/robolectric#1952]
It has an `attach()` method (though [I've been having problems with that](https://github.com/robolectric/robolectric/issues/1951)), therefore it should have a `detach()` as well (so you can simulate the entire lifecycle).

**Comment by xian** [comment]
Looks like `FragmentController.attach()` is a no-op, do we want to keep it?

**Comment by jongerrish** [comment]
I was planning to remove it also from the public API of all the controllers
as we are going to automatically attach components when you build them as
components without attached bar context are kinda useless now.

**Comment by utzcoz** [comment]
Hi @hoisie, I found the `attach()` method is removed from `FragmentController`, maybe this issue can be closed.

**Comment by MGaetan89** [comment]
`FragmentController` is now deprecated, and so is the underlying `android.app.Fragment` API.
The recommended alternative is to use [`FragmentScenario`](https://developer.android.com/guide/fragments/test).
We can probably close this issue?

**Comment by MGaetan89** [comment]
Closing this issue, since `FragmentController` is now deprecated, and the `attache()` no longer exists.
The recommend alternative is to use `FragmentScenario`.
