### ISSUE TITLE
testing sendBroadcast multiple applications/services 

### ISSUE THREAD

**Issue by leviyehonatan** [robolectric/robolectric#1953]
it would be very helpful for me to be able to sendBroadcast/sendOrderedBroadcast and be able to spawn more than one applicaiton/service as i have scenarios covering that. is it supported by any way? what about using ParallelUniverse?

**Comment by erd** [comment]
Robolectric is meant for unit testing and only supports testing one application at a time. Keep in mind that services do not run unless you start them yourself. What you're describing would be better tested via Espresso.

**Comment by leviyehonatan** [comment]
i am not sure we understand each other since he project runs pretty well on the robolectric environment and its possible to create more than one service using ServiceController, and i need the capabilities of controlling the WifiManager and all the different shadows... are you sure we understand each other correctly?

**Comment by erd** [comment]
> are you sure we understand each other correctly?

I don't think so. Are you trying to create two services via `ServiceController` and then send have a broadcast intent delivered to both? If not, could you show me some sample code from the test you're trying to write?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
