### ISSUE TITLE
Upgrading Roboletric 3.0-rc3 to Roboletric 3.0 has error

### ISSUE THREAD

**Issue by soulkeykim** [robolectric/robolectric#1956]
Roboletric 3.0-rc3 has no problem.
However, after upgrading Roboletric 3.0, it has been error like below.   

org.mockito.exceptions.base.MockitoException: 
    Cannot mock/spy class com.google.android.gms.maps.GoogleMap
    Mockito cannot mock/spy following:
      - final classes
      - anonymous classes
      - primitive types

from 
       testCompile 'org.robolectric:robolectric:3.0-rc3'
to
      testCompile 'org.robolectric:robolectric:3.0'

Could you please tell me something about this?

**Comment by hidroh** [comment]
I had the same upgrade problem, though it was a mistake to mock those in the first place. Just curious why it does not throw exceptions in 3.0-rc3?

**Comment by soulkeykim** [comment]
I don't know I just used 'mock(GoogleMap.class);', and It works fine on rc3.

**Comment by erd** [comment]
By default, Robolectric does not attempt to instrument anything outside of the standard android sdk. If you want to use shadows for Google maps, you need to add `testCompile 'org.robolectric:shadows-maps:3.0'` to your build.gradle. See http://robolectric.org/using-add-on-modules for more information.

**Comment by aguestuser** [comment]
Not sure this shoudl be closed... I am using the Google maps shadows (and have the exact line you specified in my Gradle build file. Up until recently I was using v3.0-rc2 and my tests calling `mock(GoogleMap.class)` ran just fine. Upon upgrading to v3.0 all of those tests fail with the same error as @soulkeykim. Sounds like an issue to me... unless I'm missing something? Is proper usage documented anywhere? (And sorry for wasting your time if it is!)

**Comment by aguestuser** [comment]
FWIW: Upgrading also gives me a set of other newly failing tests involving modules, including errors connecting to the GoogleApiClient which I'm assuming is in the `shadows-play-services` module (error: `Cannot mock/spy class com.google.android.gms.maps.GoogleMap`) and some bizarro life-cycle errors that I'm not even close to understanding in my Activity tests (ie: `Method onDestory_cleansUpResources() should be public`)... Hunting for appropriate places to seek help or mention those as issues now. Sorry if they're off-topic on this thread.

**Comment by erd** [comment]
Robolectric used to cast a very wide net when determining if a class should be instrumented. Robolectric 3.0 only instruments classes in packages for which we have shadows. Since we don't have any shadow classes in the package `com.google.android.gms.maps`, the classes contained inside are not instrumented (part of the instrumentation process strips classes of `final` modifiers).

If you want to contribute a shadow for `GoogleMap`, I'd be happy to help you get started.

**Comment by aguestuser** [comment]
I'd love to contribute a shadow for `GoogleMap`! Huge fan of the project and would love to help in any way I can. How do I get started? (Note: will only be able to give time to it in fits and starts between work on production code, but the production code all revolves around mobile maps -- so this is probably not that hard to make the case for putting time toward!) Thanks very much for asking! :)
