### ISSUE TITLE
Regarding #1956 Robolectric 3.0 still issue

### ISSUE THREAD

**Issue by soulkeykim** [robolectric/robolectric#1957]
I used 'testCompile 'org.robolectric:shadows-maps:3.0'', but still remains same issue.

How can I get GoogleMap class, because it is not involved in the library (shadows-maps)?

org.mockito.exceptions.base.MockitoException: 
    Cannot mock/spy class com.google.android.gms.maps.GoogleMap
    Mockito cannot mock/spy following:
      - final classes
      - anonymous classes
      - primitive types

**Comment by erd** [comment]
If you are using Google Maps fromPlay Services, you will need to create your own shadow. Robolectric currently does not have shadows for these classes. There is some information on creating your own shadow here: http://robolectric.org/custom-shadows.

In the future, please try posting to the mailing list first (robolectric@googlegroups.org) for support questions.
