### ISSUE TITLE
FragmentController for use with support.v4.app.Fragment

### ISSUE THREAD

**Issue by andrewlord1990** [robolectric/robolectric#1959]
We use support library Fragments and so are unable to use FragmentController, there is a SupportFragmentTestUtil but no SupportFragmentController.

**Comment by jongerrish** [comment]
Right, would you be willing to submit a PR? I'd love to have a support lib
version.

**Comment by andrewlord1990** [comment]
Potentially, not sure when I would get to it and I haven't contributed to Robolectric before, so would need to set everything up. Will post on here if/when I start on it.

**Comment by jaredsburrows** [comment]
+1

**Comment by jaredsburrows** [comment]
@andrewlord1990 Here is the original issue for the `FragmentController` here: https://github.com/robolectric/robolectric/pull/1874 and here is the PR: https://github.com/zhongyu05/robolectric/commit/787591baab85e879a1ab0d985cf23fab567b0602.

You should be able to swap out the `Fragment` wit the v4 `Fragment`.

**Comment by andrewlord1990** [comment]
I should be able to get to this next week. Thanks for the extra details.

**Comment by andrewlord1990** [comment]
ComponentController is package visibility, which means my SupportFragmentController can't extend it. I therefore think

**Comment by jaredsburrows** [comment]
Sounds good.
