### ISSUE TITLE
Link in Activity Lifecycle links to page that does not exist

### ISSUE THREAD

**Issue by markcerqueira** [robolectric/robolectric#1961]
Not sure if this is the right place to log bugs on issues with the documentation. If not, please let me know and I'll close this and open elsewhere. 

On this page: http://robolectric.org/activity-lifecycle/

The link with text "ActivityController Java Docs" links to this page: 

http://robolectric.org/javadoc/org/robolectric/util/ActivityController.html

Which does not exist.

**Comment by erd** [comment]
Could you re-open this issue against `robolectric/robolectric.github.io`? That's the repo for the docs.

**Comment by markcerqueira** [comment]
Noted and done. Thanks @erd!
