### ISSUE TITLE
ShadowObjectAnimator.isRunning() returns false after ShadowObjectAnimator.start()

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#1964]
Hi, this test fails on 3.0 but shouldn't (it doesn't on 2.4).

```
@Test
public void This_Works_On_2_4() throws Exception {
    // To run on 2.4: RuntimeEnvironment.application -> Robolectric.application 
    ObjectAnimator animator = ObjectAnimator.ofFloat(new TextView(RuntimeEnvironment.application), "rotation", 360f).setDuration(1500);

    animator.start();

    assertThat(animator.isRunning(), is(true));
}
```

Possibly related:
https://github.com/robolectric/robolectric/issues/1235

**Comment by kriegfrj** [comment]
Possibly a duplicate or related to #1809?

**Comment by xian** [comment]
Verified, passes on sdk 24 and 25, fails on others.

**Comment by utzcoz** [comment]
Hi @alixwar , thanks for reporting this issue, but it's too old with a very old Robolectric version. Feel free to reopen it if you find that this issue still exists. Thanks.
