### ISSUE TITLE
install-dependencies.sh fails with a poor error message when an old version of Android Support Repository is installed

### ISSUE THREAD

**Issue by avh4** [robolectric/robolectric#1968]
From the Android SDK, I had "Extras / Android Support Repository Rev. 14" installed, but the dependency needed by robolectric is in Rev. 16 of that package.

Running `./scripts/install-dependencies.sh` gives the following error message.

```
java.io.FileNotFoundException: /Users/me/tools/android-sdk-macosx/extras/android/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:121)
	at sun.tools.jar.Main.extract(Main.java:1004)
	at sun.tools.jar.Main.run(Main.java:305)
	at sun.tools.jar.Main.main(Main.java:1288)
```

After executing the following command, the script completes successfully:

```bash
echo y | ~/tools/android-sdk-macosx/tools/android update sdk --no-ui --filter extra-android-m2repository --all
```

It would be preferred to give a hint about how to correct the error instead of simply failing with `FileNotFoundException`.

**Comment by jaredsburrows** [comment]
@erd This is not really an issue, the message is clear. Eventually the build should be moved to Gradle anyways. You will see a similar message with Gradle as well. Developers should always keep up-to-date with the latest repositories.

**Comment by erd** [comment]
This has nothing to do with Gradle vs Maven.

**Comment by jaredsburrows** [comment]
@erd  I am just saying. Besides, he wants the scripts to print out a message if he doesn't have his environment setup correctly. The exception shown is already showing that. We should keep issues in Robolectric related to the code for testing.
