### ISSUE TITLE
context.getSystemService(Context.BLUETOOTH_SERVICE) returns null

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1970]
From API18 you should access bluetooth service through BluetoothManager (http://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html). This case is not covered by Robolectric now

**Comment by jaredsburrows** [comment]
@emartynov Can you should use an example test?

**Comment by emartynov** [comment]
@jaredsburrows I don't get, sorry! Do you want example of accessing BluetoothManager?

**Comment by jaredsburrows** [comment]
You said that the for API 18, Robolectric is not accessing the Bluetooth Manager? Are you seeing is in a test or in the source code of Robolectric?

**Comment by emartynov** [comment]
It comes form here http://stackoverflow.com/questions/31715709/roboletric-returns-null-bluetooth-manager

I debugged Robolectric
