### ISSUE TITLE
get error after adding library into project

### ISSUE THREAD

**Issue by tux-world** [robolectric/robolectric#1972]
Hi. after successful import this library into project and using that. i get this error:

Error:(14, 38) error: package com.afollestad.materialdialogs does not exist
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

but import library is ok when i using this sample:

        new MaterialDialog.Builder(this)
                .title("title")
                .content("content")
                .positiveText("agree")
                .negativeText("disagree")
                .show();
i can hold ctrl and click on MaterialDialog Intellij show MaterialDialog class correctly

**Comment by erd** [comment]
Can you provide some additional debugging information or a sample project on Github? Otherwise, we're not going to be able to help debug it.

**Comment by tux-world** [comment]
I'm was forced to use source in project, this library dont support force use gravity to right without change phone language. i dont like this opration. because we use english language on phone but out software direction is rtl.

**Comment by tux-world** [comment]
I'm was forced to use source in project, this library dont support force use gravity to right without change phone language. i dont like this opration. because we use english language on phone but out software direction is rtl. i dont know why you are remove or dont support this option. only for this option and only have one item as gravity = "right" i'm forced to use source :(

**Comment by jaredsburrows** [comment]
What does this have to do with Robolectric? Those errors are not from Robolectric @erd .

**Comment by erd** [comment]
If you need help getting Robolectric working in your project, please post on the mailing list.
