### ISSUE TITLE
error initiating an activity to test

### ISSUE THREAD

**Issue by jonneymendoza** [robolectric/robolectric#1976]
Hi i get the following error when i try to initiate my activity using this code below:
```
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class)
public class BillingdetailsTest {

    private EditText cardTextField;

    @Before
    public void setup() {
        TestActivity activity = Robolectric.setupActivity(TestActivity.class);
        cardTextField = new EditText<Object>(activity.getApplicationContext());
        BillingEditTextWatcher textWatcherNoneAmex = new BillingEditTextWatcher(EditText.TYPE_CARD_NUMBER, cardTextField);
    }

    @Test
    public void testCardInput() {
        String cardTest = "4111 1111";
        String cardTestTwo = "4111 1";
        String cardTestThree = "4111 1111 2222 3333";
    }
}

```
It fails on this line:
```
TestActivity activity = Robolectric.setupActivity(TestActivity.class);
```
Here is the exception i get:
```
XML file jar:/Users/jonathan/.m2/repository/org/robolectric/android-all/4.4_r1-robolectric-1/android-all-4.4_r1-robolectric-1.jar!/res/layout/screen_action_bar.xml line #-1 (sorry, not yet implemented): Error inflating class com.android.internal.widget.ActionBarContainer
android.view.InflateException: XML file jar:/Users/jonathan/.m2/repository/org/robolectric/android-all/4.4_r1-robolectric-1/android-all-4.4_r1-robolectric-1.jar!/res/layout/screen_action_bar.xml line #-1 (sorry, not yet implemented): Error inflating class com.android.internal.widget.ActionBarContainer
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:286)
	at android.app.Activity.setContentView(Activity.java:1928)
	at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:216)
	at android.support.v7.app.ActionBarActivityDelegateICS.setContentView(ActionBarActivityDelegateICS.java:110)
	at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:76)
```
Any ideas?

**Comment by erd** [comment]
Which version of Robolectric are you using?

**Comment by jonneymendoza** [comment]
robolectric:robolectric:3.0-rc3

**Comment by erd** [comment]
Please upgrade to the 3.0 release.

**Comment by jonneymendoza** [comment]
i just upgraded to 3.0 but still get the same error

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:108)
	at android.support.v7.app.ActionBarActivityDelegateICS.onCreate(ActionBarActivityDelegateICS.java:57)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:98)

**Comment by jaredsburrows** [comment]
Are you setting a theme in `values.xml`? `AndroidManifest.xml`?

For this test, you can use `RuntimeEnvironment.application` instead of launching an `Activity`.

**Comment by erd** [comment]
It sounds like your `TestActivity` extends `ActionBarActivity`, but does not have a theme set in the manifest that descends from `Theme.AppCompat`. If you need a generic context to create your `cardTextField`, use `RuntimeEnvironment.application` as @jaredsburrows mentions.

**Comment by jonneymendoza** [comment]
It has a theme set on the main androidManifets.

The activtity launches fine when running the app

**Comment by guillaume-tgl** [comment]
I have a similar issue. I'm using Robolectric 3.0 and I'm trying to test a fragment that contains a `FloatingActionButton`.

I'm starting my fragment with: `FragmentTestUtil.startFragment(fragment, TestAppCompatActivity.class);`

And here is my `TestAppCompatActivity`:

```
public class TestAppCompatActivity extends AppCompatActivity {

    public TestAppCompatActivity() {
        super();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        setTheme(R.style.Theme_AppCompat);
        super.onCreate(savedInstanceState);
    }
}
```

I'm using AppCompat 23.1.0 and I have the same exception:
```
Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
	at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:34)
	at android.support.design.widget.FloatingActionButton.__constructor__(FloatingActionButton.java:108)
	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at com.thegrizzlylabs.pyfl.ui.map.MapFragment.onCreateView(MapFragment.java:91)
```

**Comment by mpost** [comment]
I am seeing the same problem as @guillaume-tgl. When updating to the design support library 23.1.1 i get the same error `You need to use a Theme.AppCompat theme...`.

**Comment by guillaume-tgl** [comment]
Interesting thing, I was able to debug my app and find out that this exception is thrown when the current theme does not contain the attribute `R.attr.colorPrimary`. By debugging I noticed that the them contains this attribute until I call `GooglePlayServicesUtil.getErrorDialog`.
This only happens when running tests, not when I run the app on a device.

Not sure if that will be helpful, given that `GooglePlayServicesUtil`is not open source..

**Comment by mpost** [comment]
@guillaume-tgl We are not making use of the Google Play Services so our problem stems from the regular support library. While it is good to hear that you could solve the problem i wonder if the `GooglePlayServicesUtil.getErrorDialog` call really changes your theme on such a fundamental level?

I have opened a new issue for the Theme.AppCompat problem at https://github.com/robolectric/robolectric/issues/2169. So far we had no luck in allocating the correct theme in robolectric tests.

**Comment by guillaume-tgl** [comment]
@mpost have you tried to debug your app and see if your theme has this `R.attr.colorPrimary`attribute in the different activity lifecycle methods?

**Comment by mpost** [comment]
@guillaume-tgl You mean check during runtime on a device? I am using the colorPrimary in my app so it is available during runtime.

I have taken a screenshot of the theme during runtime on the device:

![theme-app](https://cloud.githubusercontent.com/assets/73655/11681382/f5a40306-9e5e-11e5-9956-123f2d9717dd.png)

And during runtime when executing a robolectric test

![theme-robolectric](https://cloud.githubusercontent.com/assets/73655/11681386/f94af596-9e5e-11e5-95d7-f0d8182988c6.png)

Apparently the theme used in robolectric is not the same as used in production on device. In fact the theme ids look very generic as if they are hardcoded values.

**Comment by guillaume-tgl** [comment]
I meant during Robolectric tests using the same check that makes tests fail. For example:

    int[] APPCOMPAT_CHECK_ATTRS = { R.attr.colorPrimary };
    context.obtainStyledAttributes(APPCOMPAT_CHECK_ATTRS).hasValue(0)

I used this test to check where the AppCompat issue was happening

**Comment by mpost** [comment]
There are two checks that are performed by the support libray: one for the `R.attr.colorPrimary` (in the `android.support.design.widget.ThemeUtils`) and one for the `android.support.v7.appcompat.R.styleable.Theme_windowActionBar` as i have described in #2169.


Running the following code in a robolectric tests reveals that `colorPrimary` is available but the `Theme_windowActionBar` is not:

```java
int[] APPCOMPAT_CHECK_ATTRS = { R.attr.colorPrimary };
boolean hasColorPrimary = activity.obtainStyledAttributes( APPCOMPAT_CHECK_ATTRS ).hasValue( 0 );
// hasColorPrimary == true

TypedArray a = activity.obtainStyledAttributes( android.support.v7.appcompat.R.styleable.Theme);
boolean hasWindowActionBar = a.hasValue( android.support.v7.appcompat.R.styleable.Theme_windowActionBar );
// hasWindowActionBar == false
```

I am running this code right before the robolectric `ActivityController.resume()` method.

**Comment by mpost** [comment]
Apparently it was the missing R file of the design support library (packages as an .aar). A common problem when working with robolectric. I have added it in a gradle build step and now the resources are found as expected.

**Comment by Egorand** [comment]
@mpost could you please give more detail on how you solved this?

**Comment by caltseng** [comment]
I believe it is here. 

https://github.com/robolectric/robolectric/issues/1737#issuecomment-121318761
