### ISSUE TITLE
SpannableStringBuilder.equals() shadow implementation is not complete

### ISSUE THREAD

**Issue by illarionov** [robolectric/robolectric#1978]
robolectric:3.0 SDK 21

A result of the `SpannableStringBuilder.equals()` is differs from the result on a real device if the spannable string has any spans attached to it.

The following test incorrectly fails with roboelectric.

    @Test
    public void testSpannableString() throws Exception {
        SpannableStringBuilder spannableString = new SpannableStringBuilder("test");
        spannableString.setSpan(new UnderlineSpan(), 0, spannableString.length(), 0);
        assertFalse(spannableString.equals("test"));
    }

**Comment by erd** [comment]
If the shadow implements `equals`, we should probably remove it and let it call through to real Android.
