### ISSUE TITLE
RuntimeEnvironment.getPackageManager throws ClassCastException

### ISSUE THREAD

**Issue by ernestkamara** [robolectric/robolectric#1982]
RobolectricPackageManager is not compatible with PackageManager even though its implements some PackageManager methods.

```
com.sun.proxy.$Proxy20 cannot be cast to android.content.pm.PackageManager
java.lang.ClassCastException: com.sun.proxy.$Proxy20 cannot be cast to android.content.pm.PackageManager
    at org.robolectric.RuntimeEnvironment.getPackageManager(RuntimeEnvironment.java:23)
    at org.robolectric.shadows.ShadowContextWrapper.getApplicationInfo(ShadowContextWrapper.java:61)
    at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java)
    at android.widget.RemoteViews.getApplicationInfo(RemoteViews.java:2676)
    at android.widget.RemoteViews.<init>(RemoteViews.java) 
```

Here is a snippet of the source code

```
public class RuntimeEnvironment {
    public static Application application;

    private static String qualifiers;
    private static Object activityThread;
    private static RobolectricPackageManager packageManager;

    public static Object getActivityThread() {
        return activityThread;
    }

    public static void setActivityThread(Object newActivityThread) {
        activityThread = newActivityThread;
    }

    public static PackageManager getPackageManager() {
        return (PackageManager) packageManager;
    }

    public static RobolectricPackageManager getRobolectricPackageManager() {
        return packageManager;
    }

    public static void setRobolectricPackageManager(RobolectricPackageManager newPackageManager) {
      if (packageManager != null) {
        packageManager.reset();
      }
      packageManager = newPackageManager;
    }

    public static String getQualifiers() {
        return qualifiers;
    }

    public static void setQualifiers(String newQualifiers) {
        qualifiers = newQualifiers;
    }
}
```

**Comment by ernestkamara** [comment]
@erd any comment on this?

**Comment by jaredsburrows** [comment]
@ernestkamara  What is the problem here? What are you trying to do with `RobolectricPackageManager`?

**Comment by ernestkamara** [comment]
@jaredsburrows am trying to cover a test case in my RemoteViewsFactory class where NameNotFoundException is expected to be thrown when fetching the Drawable of a given app is not found.

Implementation snippet:
```
 public class MyRemoteViewsFactory implements RemoteViewsFactory {
     // some stuff here!

 Drawable appIcon;
        @Override
        public RemoteViews getViewAt(int position) {
            RemoteViews remoteViews = new RemoteViews("my.package", 1);

            // some other stuff here!
            Drawable appIcon
            try {
                appIcon = mContext.getPackageManager().getApplicationIcon("package.name");
            } catch (PackageManager.NameNotFoundException e) {
                return getLoadingView();
            }

            // some other stuff here!
           return remoteViews;
        }
  }
```
Test snippet 
```
@RunWith(MyTestRunner.class)
@Config(sdk = 21, constants = BuildConfig.class)
public class HoneycombAndUpGameWidgetServiceTest extends MyBaseTestCase {

    @Before
    public void setUp() {
         // some setup stuffs
    }
   @Test (expected = PackageManager.NameNotFoundException.class)
    public void testRemoteViewShouldThrowNameNotFoundExceptionForAppIcon() throws PackageManager.NameNotFoundException {
        Item item = new MockItem().setId(1234).setPackageName("package.name");
        List<Item> items = new LinkedList<>();
        items.add(item);

        RobolectricPackageManager packageManager = EasyMock.createMock(RobolectricPackageManager.class);
        EasyMock.expect(packageManager.getApplicationIcon(item.getPackageName()))
                .andThrow(new PackageManager.NameNotFoundException("Foo"));


        MyRemoteViewsFactory factory = new MyRemoteViewsFactory(mMyTestApplication, items);
        replayAll();
        RuntimeEnvironment.setRobolectricPackageManager(packageManager);

        RemoteViews remoteViews = factory.getViewAt(0);
        assertEquals(mMyTestApplication.getPackageName(), remoteViews.getPackage());

        verifyAll();
        resetAll();
    }
}
```
Running the test snippet above throws a ClassCastException as mentioned above.

**Comment by jaredsburrows** [comment]
@ernestkamara  There is no need to mock anything. Just use `Robolectric`:

Here is an example: 

    @Test
    public void getPackageVersion_existing_package() {
        PackageInfo packageInfo = new PackageInfo();
        packageInfo.packageName = "testGetPackageVersion";
        packageInfo.versionName = "2.0";
        packageInfo.applicationInfo = new ApplicationInfo();
        packageInfo.applicationInfo.packageName = "testGetPackageVersion";
        packageInfo.applicationInfo.name = "testGetPackageVersion";

        RobolectricPackageManager robolectricPackageManager = RuntimeEnvironment.getRobolectricPackageManager();
        robolectricPackageManager.addPackage(packageInfo);

        PackageManager packageManager = (PackageManager) robolectricPackageManager;

        assertThat(packageUtils.getPackageVersion(packageManager, "testGetPackageVersion"), is("2.0"));
    }

Create a `PackageInfo` object, add to the `RobolectricPackageManager`.

**Comment by jaredsburrows** [comment]
@erd Can we close this?

**Comment by ernestkamara** [comment]
Thank for the example @jaredsburrows, but it doesn't fix my problem since DefaultPackageManager.getApplicationIcon() returns null instead of throwing PackageManager.NameNotFoundException as in RobolectricPackageManager. 
I wanted to test that my "default view" is loaded if PackageManager failed to load the icon from a given package name.

**Comment by jaredsburrows** [comment]
My example was just an example of how to actually use the package manager in Robolectric. Your class needs to use the Robolectric context, `RuntimeEnvironment.application`.

**Comment by jaredsburrows** [comment]
@erd Can we not close this?

**Comment by jaredsburrows** [comment]
@erd Can we not close this?

**Comment by xian** [comment]
Please reopen if this is still an issue in 3.3. Thanks!
