### ISSUE TITLE
Robolectric Custom ShadowContextWrapper

### ISSUE THREAD

**Issue by HIFILEO** [robolectric/robolectric#1984]
# Problem
I want to create a custom ShadowContextWrapper and implement getExternalFilesDirs() so it's compatible with AppCompat KitKat.

However when I do so I get the following error:
>
java.lang.IllegalArgumentException: attempted to invoke public java.io.File robolectric.ShadowContextWrapper.getExternalFilesDirs(java.lang.String) on instance of class org.robolectric.shadows.ShadowApplication, but ShadowApplication doesn't extend ShadowContextWrapper
>

For those who are curious, here's the error output when SDK is 21 not 18 in robolectric test:
>
java.lang.NullPointerException
at android.app.ContextImpl.ensureDirsExistOrFilter(ContextImpl.java:2388) at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:1046) at android.content.ContextWrapper.getExternalFilesDirs(ContextWrapper.java:216) at android.support.v4.content.ContextCompatKitKat.getExternalFilesDirs(ContextCompatKitKat.java:29) at android.support.v4.content.ContextCompat.getExternalFilesDirs(ContextCompat.java:220)
>

# Code
```
/**
* Shadow for {@link android.content.ContextWrapper}.
*/
@Implements(ContextWrapper.class)
public class ShadowContextWrapper extends org.robolectric.shadows.ShadowContextWrapper {
    public static final String TAG = ShadowContextWrapper.class.getSimpleName();

    @Implementation
    public File getExternalFilesDirs(String type) {
        Log.d(TAG, "Custom Shadow: " + Thread.currentThread().getStackTrace()[1].getMethodName());
        return Environment.getExternalStoragePublicDirectory(type);
    }
}
```

**Comment by erd** [comment]
It's not currently possible to extend one of Robolectric's shadows for the purpose of implementing extra methods. You can create custom shadows for classes that don't have one, but you're not able to extend an existing shadow. I'd be happy to look at a pull-request, if you want to contribute your changes.

**Comment by HIFILEO** [comment]
So your suggestion is to create a pull request that implements the method "getExternalFilesDirs" in the "ShadowContextWrapper" and put a pull request. Correct?

**Comment by erd** [comment]
Yep.
