### ISSUE TITLE
Activity navigation isn't implemented

### ISSUE THREAD

**Issue by 1zaman** [robolectric/robolectric#1990]
All the `startActivity()` and `startService()` methods seem to be shadows to only store it's `Intent` to verify that it has been called. No actual `Activity` or `Service` is started. That makes it quite hard to test `Activity` navigation, especially when it's of a complex sort (e.g. a chain of events starting and finishing Activities). Navigating back to an `Activity` cannot be simulated at all.

Since all of the methods are shadowed and mocked it's technically possible to test any specific navigation implementation, but the tests will be tied to the implementation instead of the results. This is in contrast to Espresso, where actual `Activity` navigation is performed. It would be nice if Robolectric would also support this feature, as this seems to be the one feature that it does not currently simulate.

**Comment by jaredsburrows** [comment]
Can you show us an example?

**Comment by 1zaman** [comment]
@jaredsburrows: Example of what? How do I show an example of the lack of a feature? Can _you_ show an example of `startActivity()` or `startService()` starting an actual `Activity` or `Service` in a Robolectric test, and retrieve a reference to these components? Or `finish()` actually finishing an `Activity` and calling the appropriate callback methods?

**Comment by jaredsburrows** [comment]
I think `Navigating back to an Activity cannot be simulated at all.` is true. I have not seen any examples for that.

**Comment by erd** [comment]
This is by design. We're not trying to simulate Android, only make it easier to write unit tests.
