### ISSUE TITLE
NPE in MenuInflater.inflate when using nested menus

### ISSUE THREAD

**Issue by Achran1000** [robolectric/robolectric#1991]
If your menu xml has an <item> with a nested <menu>, it will NPE with the following error (those line numbers are from v21 of the SDK).

java.lang.NullPointerException
    at android.view.MenuInflater$MenuState.setItem(MenuInflater.java:440)
    at android.view.MenuInflater$MenuState.addSubMenuItem(MenuInflater.java:500)
    at android.view.MenuInflater.parseMenu(MenuInflater.java:163)
    at android.view.MenuInflater.inflate(MenuInflater.java:110)

It looks like the issue is that MenuInflater#addSubMenuItem() calls:

``` java
SubMenu subMenu = menu.addSubMenu(groupId, itemId, itemCategoryOrder, itemTitle);
setItem(subMenu.getItem());
```

But RoboMenu#addSubMenu() returns a RoboSubMenu, and RoboSubMenu#getItem() returns null.  Maybe just returning a "new RoboMenuItem()" would be viable?

---

Example to replicate this:

MainActivity.java:

``` java
  public void attemptToInflateMenu(MenuInflater inflater, Menu menu) {
    inflater.inflate(R.menu.menu_main, menu);
  }
```

MainActivityTest.java

``` java
  @Test
  public void validateNestedMenuInflation() throws Exception {
    Menu menu = new RoboMenu(activity);
    MenuInflater inflater = new MenuInflater(activity);
    activity.attemptToInflateMenu(inflater, menu);
  }
```

menu_main.xml

``` java
  <menu xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        tools:context=".MainActivity">
      <item
          android:title="SubmenuContainer">
          <menu>
              <item
                  android:title="SubmenuItem" />
          </menu>
      </item>
  </menu>
```

**Comment by erd** [comment]
I don't believe we shadow `MenuInflater`, so unless you're manually creating a `RoboMenu`, I don't think that is the culprit.

**Comment by Achran1000** [comment]
Yeah, we are manually creating our own RoboMenu.  The relevant snippet of our actual test is the following:

``` java
public class ExtendedTestMenu extends RoboMenu { ... }

@Test
public void verifyInflationState() {
    Menu menu = new ExtendedTestMenu(activity);
    MenuInflater menuInflater = new MenuInflater(activity);

    menuInflater.inflate(R.menu.foo, menu);
    ...
}
```

What's the suggested alternative?  Thanks!

**Comment by jongerrish** [comment]
We improved some of the menu handling code a while back...

Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
