### ISSUE TITLE
Handler doesn't execute Runnables when using Robolectric 3

### ISSUE THREAD

**Issue by virl** [robolectric/robolectric#1993]
Handler for custom background thread (with looper) doesn't execute Runnables when used from inside test class.
Looper created successfully for the thread.

In test class, I'm waiting for async result via CountDownLatch.

How can I fix that?

Test class:

```
@Config(constants = BuildConfig.class, sdk = 16)
@RunWith(RobolectricGradleTestRunner.class)
public class DispatchQueueTest
{
    @Test
    public void testDispatch() throws InterruptedException
    {
        DispatchQueue queue = new DispatchQueue();
        final CountDownLatch latch = new CountDownLatch(1);
        queue.dispatch(new Runnable()
        {
            @Override
            public void run()
            {
                latch.countDown();
            }
        });

        Assert.assertTrue("queue dispatch timeout", latch.await(1000, TimeUnit.MILLISECONDS));
        queue.close();
    } // testDispatch
}
```

Tested class:

```
public class DispatchQueue implements Executor
{
    public static DispatchQueue main = new DispatchQueue(new Handler(Looper.getMainLooper()));

    private Handler handler;

    public DispatchQueue(Handler handler)
    {
        this.handler = handler;
    }

    public DispatchQueue()
    {
        final CountDownLatch latch = new CountDownLatch(1);

        Thread thread = new Thread(new Runnable()
        {
            @Override
            public void run()
            {
                Looper.prepare();
                ;

                DispatchQueue.this.handler = new Handler();
                latch.countDown();

                Looper.loop();

                //Logger.debug("DispatchQueue finished");
            }
        });

        thread.setDaemon(true);
        thread.start();

        try
        {
            latch.await(5, TimeUnit.SECONDS);
        }
        catch(InterruptedException ex)
        {
            Logger.error("Dispatch thread start failed.");
            return;
        }
    } // DispatchQueue()

    public void close()
    {
        this.handler.getLooper().quit();
    }

    public Handler getHandler()
    {
        return handler;
    }

    public void execute(Runnable runnable)
    {
        dispatch(runnable);
    }

    public boolean dispatch(Runnable runnable)
    {
        if(handler == null)
            return false;

        return handler.post(runnable);
    } // dispatch

    public Runnable dispatchAfter(long delayMs, Runnable runnable)
    {
        if(handler == null)
            return runnable;

        handler.postDelayed(runnable, delayMs);

        return runnable;
    }

    public void cancel(Runnable runnable)
    {
        if(handler == null)
            return;

        if(runnable == null)
            return;

        handler.removeCallbacks(runnable);
    }
} // DispatchQueue
```

**Comment by virl** [comment]
@kriegfrj please help. Also see #1994

**Comment by nolanlawson** [comment]
Running into this same issue, I think. I have a `HandlerThread` that I'm using to `postDelayed()`, but its `Runnable` never gets run.

I've tried all of:

```java
    Robolectric.flushForegroundThreadScheduler();
    Robolectric.flushBackgroundThreadScheduler();
    ShadowLooper.runUiThreadTasks();
    ShadowLooper.runUiThreadTasksIncludingDelayedTasks();
    while (Robolectric.getBackgroundThreadScheduler().runOneTask()) { }
    while (Robolectric.getForegroundThreadScheduler().runOneTask()) { }
```

But still no luck. :confused: Robolectric 3.0 here.

**Comment by jkasten2** [comment]
Since your creating your own thread, looper, and handler you will need to advance the runnables with your own code your self. You can use Roboletric's shadowOf method to access the internals of your looper to do this. Something like the following should work for your example test.
```Java
shadowOf(queue.getHandler().getLooper()).getScheduler().advanceToNextPostedRunnable();
```

**Comment by virl** [comment]
@jkasten2 It's ugly. Why Robolectric doesn't allow to test asynchronous code like Xcode do?

**Comment by jkasten2** [comment]
From a quick look it seems like it would be possible to add this to Robolectric as it's [ShadowLooper](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowLooper.java) keeps track of all loopers by thread.

I wouldn't use that line in each of your tests, to keep things clean just add a static helper method and call it passing in your DispatchQueue or a Looper instance.

**Comment by virl** [comment]
@jkasten2 
> call it passing in your DispatchQueue or a Looper instance

You don't understand: I shouldn't pass any Looper instance, because the code that I test can *change implementation* by introducing multiple loopers inside it, etc.

So Robolectric must allow me to test async code as *black box*, not requiring me to expose its threading internals.

**Comment by acherkashyn** [comment]
Running into this same issue right now. I'm starting my own looper thread and posting to it via handler using sendMessageDelayed(). This code works perfectly fine on a real device, handleMessage() is called just fine. But not with Robolectric, unfortunately. And I'm specifically want to test that a certain action takes place after predefined delay. Is there any way to tie my Looper to Robolectric to have it deliver message to the handler after a delay without having to manually advance the queue as described in one of the previous comments?

**Comment by virl** [comment]
Robolectric devs, please change all that async paradigm to something like XCTestExpectation on iOS — so we can test complex async behaviour without manually managing any loopers or threads.

http://nshipster.com/xctestcase/

**Comment by kriegfrj** [comment]
@acherkashyn, I have a branch where this is almost working. See #2166 for more info. If it doesn't already work for you I'm hoping to have it ready in the next couple weeks. One tip that might help is to set your test to use a global scheduler, look in RoboSettings for more details.

**Comment by virl** [comment]
@kriegfrj I think such async testing should be enable by default like in Xcode tests, because today there are so much async code in apps.

**Comment by kriegfrj** [comment]
Hi @virl, it will probably end up as the default at some point, however because there is a significant body of installed code already which may depend on the old behavior we have made it optional for now, at least until we can evaluate any backward compatibility issues. It's pretty easy to make it the default for your project if that's what you want.

**Comment by virl** [comment]
@kriegfrj Thanks. How to make it default btw?

**Comment by kriegfrj** [comment]
Setting the `robolectric.scheduling.global` system property to `true` will tie all loopers to the same scheduler instance, which is accessible in `RuntimeEnvironment.getMasterScheduler()`.

**Comment by cvoronin** [comment]
This method (RuntimeEnvironment.getMasterScheduler()) is not included in [Release 3.0](https://github.com/robolectric/robolectric/releases/tag/robolectric-3.0), is it?

**Comment by kriegfrj** [comment]
No, sorry.

**Comment by vj12354** [comment]
I had similar issue while using Hander.postDelay 200 millis and robolectic 3.0 failed my test until used:
`ShadowLooper.runUiThreadTasksIncludingDelayedTasks();`

So try it, I'm sure it should work.

Cheers,

**Comment by ScottPierce** [comment]
@vj12354 `ShadowLooper.runUiThreadTasksIncludingDelayedTasks();` doesn't seem to be working for me.

Has anyone else gotten this to work?

**Comment by virl** [comment]
Any progress on fixing it? Robolectric really have broken paradigm regarding testing async code.

**Comment by kriegfrj** [comment]
Sorry, no progress. I haven't touched Android for a year.

I think that my solution would have solved most of what you have quite rightly called "ugly".

**Comment by virl** [comment]
@kriegfrj Tying everything to master scheduler is strange solution, because wouldn't it introduce possibility of deadlocks and out-of-order code execution?

**Comment by kriegfrj** [comment]
Tying everything to the master scheduler actually has the opposite effect on code execution order - by having all looper threads and the async task executors synchronised to the same master scheduler, their tasks will always run in the same repeatable order. Without a single master scheduler, the order in which they run depends on the order in which you advance each of the individual schedulers, and if you have individual schedulers then each thread ends up with a view of the system time that might not be consistent with the other threads.

On the other hand, the first point you raised is true - there are certain types of multithreaded code that would deadlock if tested with a single master scheduler. If, for example, you had two runnables on two threads (A & B), and thread A's runnable was supposed to wait for thread B's, but thread B's runnable which issued the notify() (or equivalent) was not scheduled to run until after thread A's, then it would deadlock.

I didn't consider this a major problem because: 1. such code is rare in most Android apps, 2. such apps can't be tested on Robolectric as they currently stand anyway (so my solution would at least have been an incremental improvement), 3. I made it configurable for backwards compatibility, so if you need individual control over the schedulers to avoid deadlock you can get it, and 4. such problems are generic to testing multithreaded code in a repeatable way anyway - they are not specific to Robolectric.

**Comment by virl** [comment]
> by having all looper threads and the async task executors synchronised to the same master scheduler, their tasks will always run in the same repeatable order

This paradigm is fundamentally wrong, because in production these tasks run in ***unpredictable*** order, often waiting for each other and accessing same volatile data. This paradigm eliminates real-life properties (and bugs) from the tested code when it is executed under test, thus making tests fundamentally incorrect.

> and if you have individual schedulers then each thread ends up with a view of the system time that might not be consistent with the other threads

In other words, exactly like when it will be when code executes on user's device.

> 1. such code is rare in most Android apps

It is not rare, because any Android app can use library (graphical or networking, like mine) that needs such code.

Anyway, the entire approach for testing framework that it makes part of the app's code to behave not as intended is wrong.

> such apps can't be tested on Robolectric as they currently stand anyway (so my solution would at least have been an incremental improvement)

But they should be, because async code with callbacks, handlers and executors is commonplace nowadays (both in libraries and in android apps). Even Xcode's XCTest framework allow to test such code correctly: http://nshipster.com/xctestcase/

Just deprecate ShadowLooper entirely as suggested here: #2977

> I made it configurable for backwards compatibility, so if you need individual control over the schedulers to avoid deadlock you can get it

Control over individual schedulers doesn't help, because tests don't have access to internal schedulers of an app's classes or libraries's classes. Because loopers and handlers usually are ***implementation detail*** and are not exposed as external API (and should not).

> such problems are generic to testing multithreaded code in a repeatable way anyway

They are not generic to it, because multithreaded code should not be tested by assuming specific execution order of multiple threads.

**Comment by kingargyle** [comment]
I'll just play devil's advocate here, and say that type of testing being discussed here is really delving into the realm of Integration testing and not true unit testing.  In these cases I would think that espresso is a better choice if you need to test the actual behavior of scheduling threads and dependent jobs.

I feel Robolectric is best used when trying to test the smallest unit possible and only having it wire up just enough so you don't have to mock everything out.   It does a good job of simulating Android but it isn't true android.  Just my two cents.

**Comment by virl** [comment]
@kingargyle Thanks for the comment.

> type of testing being discussed here is really delving into the realm of Integration testing and not true unit testing

No, it is not, because integration testing assumes testing coupling between several modules/subsystems.
What is discussed here is Robolectric support for testing ***asynchronous code*** and it turns out it doesn't support it properly, because it requires violation of tested code's encapsulation: it requires the test to depend on implementation details of tested code, to know exactly what loopers are used internally. And workaround that it proposed in this thread just makes tests invalid because removes one async bugs and introduces completely others.

What are we discussing, people? Xcode's XCTest have async code testing support for ages already!

> I feel Robolectric is best used when trying to test the smallest unit possible

1. I want to test my smallest code unit that writes objects to Realm, which uses internal loopers not exposed to test's code.
2. I want to test my smallest code unit that uses networking library (with local test server) with async callbacks and internal loopers.

**Comment by kingargyle** [comment]
@virl see the realm portion is where I think we have the discrepenancy, I would say as soon as you are trying to write data back into realm, you are entering the  realm of an integration test.   I would mock out the interfaces to Realm, and just make sure the calls were made.

I view it as the same thing if I use an Event Bus or Job Queue for executing Asynchronus code, or using RXJava and RXAndroid.    As soon as I have to execute or depend on a particular framework to get code to execute, then it starts to become an integration test.   Now I'll contradict myself a bit here, in saying that depending on Robolectric to inflate views and load resources is also getting into integration testing, but like anything this a trade off.    I just think in your particular case there are other ways to actually test the bits of the code instead of testing the whole execution of all the dependent items.

In my Event Bus/Job Queue scenario, I would test the individual POJOs to make sure they did what was necessary, and if they need to interact with other pieces, make sure they called it.   The full interaction between the pieces, I would have as espresso tests that ran on an actual device or emulator.   

Again I just think it is different expectations on how much Robolectric should try to simulate a true android device.   I'm not a committer on the project or anything, so I have no final say on how they will address this particular issue, so take what I say with a grain of salt.  It's just how I approach testing when using Robolectric.   You still need the types of tests you are talking about, I just not sure that Robolectric is the best place for them and there are other ways to test the underlying code.

**Comment by virl** [comment]
@kingargyle 
> I would say as soon as you are trying to write data back into realm, you are entering the realm of an integration test

No, I'm not, because it's not me who writing data to realm — it's the code that I'm testing. Realm (and loopers) is just implementation detail of it.

It's not my component and I'm not testing interaction between my components.

Anyway, even if it was, it cannot be justification for Robolectric for breaking Loopers and not breaking Threads and Executors at the same time.

> I would mock out the interfaces to Realm, and just make sure the calls were made.

It is unrealistic, because it requires mocking an ***implementation*** of extremely complex third-party library. Also it implies that test's code should depend on implementation of that library, which can change without notice in any minor version.
Thus your suggestion is wrong, sorry. :)

Properly it is solved just by creating in-memory Realm without mocking anything.

> The full interaction between the pieces, I would have as espresso tests that ran on an actual device or emulator.

It's not usable, because it is very slow compared to executing on desktop JVM.

> I just think it is different expectations on how much Robolectric should try to simulate a true android device

Threads and Executors are working in Robolectric properly. Handlers and Loopers (which are essentially modified Executors) are not. So there is no "trying to simulate android", just don't break Loopers please!

> You still need the types of tests you are talking about, I just not sure that Robolectric is the best place for them and there are other ways to test the underlying code.

No, there are no other ways, because testing on device/emulator is extremely slow.

> It's just how I approach testing when using Robolectric.

You cannot properly test async code with callbacks/listeners using your approach, because it requires the test to depend on tested code's implementation and modifies tested code's asynchronous behaviour (order of execution in event queue).

Anyway, on iOS the XCode's XCTest framework properly solved these issues ages ago: http://nshipster.com/xctestcase/

**Comment by kingargyle** [comment]
@virl Somebody has already started a project to allowing for Mocking Realm, so that might be of help to work around some of the issues.  Check, https://github.com/juanmendez/Mocking-Realm for more information.

I'm not saying that espressor testing is quick, it is just an option.   Many places have robolectric tests, and longer running emulator/integration tests.

Anyways, we have different philosophies on how much something should be tested and where it should be tested.  There are needs for both approaches, it just depends on how much time they want to put into fixing these issues along with all the other issues they have.  Great thing is, the code is open source, so we could always try to supply a patch to fix the issue.  Might help move it along quicker as well.

**Comment by virl** [comment]
@kingargyle 
> Somebody has already started a project to allowing for Mocking Realm, so that might be of help to work around some of the issues.

I don't need mocking of the Realm, I don't use it. I'm developing Android networking library and need to test my async code on desktop JVM. But it happens that Realm (which is almost pure Java and already have support for x86 in NDK) doesn't work on Robolectric partly due to the same causes as my tests.

> I'm not saying that espressor testing is quick, it is just an option.

It's not an option, it is flaw of Robolectric's implementation of Loopers. And it is prohibitively slow compared to iOS's XCTest and Robolectric.

> Anyways, we have different philosophies on how much something should be tested and where it should be tested.

No, we have different view on should async code tests be fast (desktop JVM, my position) or impossible (prohibitively slow on device/emulator, your position).

> Great thing is, the code is open source, so we could always try to supply a patch to fix the issue.

No thanks, I have limited resources and other work to do for implementing such large fix in existing complex library for free. 
So I'll just wait when some large company become enraged with this flaw and I wil justl use their fork (or another solution entirely).

**Comment by TarasMazepa** [comment]
Sorry for reviving this thread but just wanted to give a hint to @virl . You can write your async Android code using RxJava which has awesome features(http://reactivex.io/) and has very good testing infra(http://www.baeldung.com/rxjava-testing).

**Comment by virl** [comment]
@TarasMazepa RxJava doesn't help, because Robolectric cannot work with it on background threads due to issues described in this thread.

**Comment by TarasMazepa** [comment]
You do not need Roboelectric to test RxJava background threads. As I mentioned before this library has good testing infra, with which you will love to write tests for background work :)

**Comment by virl** [comment]
@TarasMazepa Does it work with Android code without Emulator, like Robolectric?

**Comment by TarasMazepa** [comment]
See "5. Testing Time-Based Observable" section of article http://www.baeldung.com/rxjava-testing

**Comment by TarasMazepa** [comment]
Yes it works without emulator

**Comment by virl** [comment]
@TarasMazepa Without emulator with Android apps?

**Comment by TarasMazepa** [comment]
But you will need to rewrite Handler based code to RxJava based

**Comment by virl** [comment]
@TarasMazepa Does RxJava work with Android apps without emulator?

**Comment by TarasMazepa** [comment]
RxJava is just a library which you can use in your Java code. It is not testing framework, but have good tools to test RxJava specific code even in JUnit tests. It will not substitute you Roboelectric. But if you will write your code using RxJava (not handlers) it would be much easier to test in for example Roboelectric

**Comment by virl** [comment]
> But if you will write your code using RxJava (not handlers) it would be much easier to test in for example Roboelectric

No, it won't. Because Robolectric doesn't support proper testing of asynchronous code.

**Comment by TarasMazepa** [comment]
:) ok

**Comment by Mawee72** [comment]
Good

**Comment by sezya-kot** [comment]
Hi guys,

I have no idea that is solved or not, but I had the same issue. As I see from your sample code:

> `public static DispatchQueue main = new DispatchQueue(new Handler(Looper.getMainLooper()));`

try to use `new Handler(ShadowLooper.getMainLooper());`

After you post something with delay for example -> `getHandler().postAtTime(anyRunnable(), anyLong())`

and only after that this method will work: `ShadowLooper.runUiThreadTasksIncludingDelayedTasks();`

Your posted task should be invoked after this method.

**Comment by virl** [comment]
@sezya-kot It is not a solution, because component that uses Looper usually is not accesible from the test's code due to incapsulation.

**Comment by sezya-kot** [comment]
@virl, to have ability to test something you need to write testable code. Testable means everything should be delivery to the component as dependency. Sorry that I couldn't help.

**Comment by virl** [comment]
@sezya-kot No, testable means that **external dependencies** of the component must be mockable.
But not the component's **implementation detail**, because unit tests should not require update when the component's implementation changes with its external API remain intact.

On iOS+Xcode I can test asynchronous code on host machine (without emulator, only through simulator that runs as macOS desktop app) without any problems. So it's Robolectric broken architecture that prevents that on Android.

**Comment by jongerrish** [comment]
GradleRobolectricTestRunner has been removed, instead you can simply use RobolectricTestRunner. You also no longer need to specify @Config(constants = ..., manifest = ...)

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
