### ISSUE TITLE
How can I unpause all loopers?

### ISSUE THREAD

**Issue by virl** [robolectric/robolectric#1994]
I want to test my async code manually, with events and CountDownLatch. For that, I need all loopers to execute as if they in Android app, without any pauses or custom scheduling.

How can I achieve that?
Currently if I post Runnable to handler of background thread, it gets executed only if I call this:
```
ShadowLooper shadowLooper = Shadows.shadowOf(queue.getHandler().getLooper());
shadowLooper.unPause();
```

**Comment by virl** [comment]
@kriegfrj please help. Also see #1993

**Comment by kriegfrj** [comment]
Sorry @virl, I have been looking into this and similar issues but won't be near a computer for a couple of weeks. Workaround in the meantime would probably be to unpause all the loopers at the start of each test. Sorry I can't be of more help at the moment.

**Comment by virl** [comment]
@kriegfrj thanks. How can I unpause all loopers? Also how can I unpause them from the test if I don't have direct access to them from the test?

**Comment by kriegfrj** [comment]
Hey @virl, please note that Robolectric as yet does not officially support muli-threaded testing (I'm working on it) so what you are trying to do is cutting-edge and will be difficult to get working.

As for accessing the loopers: as of pull request #1931 it is possible to get a reference to the looper for a thread using ShadowLooper.getLooperForThread() (which returns null if the thread doesn't have a looper). It is also possible to get references to all Java threads from the standard Java runtime methods (Google it if you need). Putting these two together, it is possible to find all of the loopers and unpause them. It could be more convenient (I'll be working on that again when I return) but at least that should get you started. Hope this helps - sorry I'm not in a position to offer more help at the moment.

**Comment by virl** [comment]
@kriegfrj 
When I try to unpause looper after runnable has been submitted to it — it works. But if I try to unpause it BEFORE submitting Runnable — it doesn't work.

> please note that Robolectric as yet does not officially support muli-threaded testing (I'm working on it) so what you are trying to do is cutting-edge and will be difficult to get working.

But multi-threaded testing is basic need, not something cutting-edge.
Don't "work on it", just give us an option to turn off robolectric's Looper shadowing entirely so loopers will just work as in normal app. That will be enough for multi-threaded testing.

**Comment by virl** [comment]
@kriegfrj Also more on my use case: basically what I'm testing is network client/server class that creates ServerSocket and listens for connections and client connects to it and exchanges some data with it.

Unit test for such class cannot work from single thread (because sockets are blocking and you need 2 threads per socket, 1 thread for test = 5 threads total). Loopers doesn't work, but I've managed to create working unit test by using serial Executor instead of loopers in my network class.
But anyway, other parts of my app can use loopers only, so I need a way to enable normal looper functioning for test cases.

**Comment by jaredsburrows** [comment]
@virl This is not a support forum. @erd  Can we close this?

@virl Please refer to https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues

**Comment by erd** [comment]
@viri if you need help getting your test setup, please post your issue on the mailing list: robolectric@googlegroups.com.
