### ISSUE TITLE
New version of Google Play Services issue with Robolectric

### ISSUE THREAD

**Issue by xtien** [robolectric/robolectric#1995]
I'm having an issue after Google Play Services got an update. I replaced the version in my local repository with the new one, I think robolectric needs that. Now I get

java.lang.NullPointerException
    at com.google.android.gms.common.GooglePlayServicesUtil.zzh(Unknown Source)
    at com.google.android.gms.common.GooglePlayServicesUtil.zzd(Unknown Source)
    at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
    at com.google.android.gms.common.api.zzg$zze.zznn(Unknown Source)
    at com.google.android.gms.common.api.zzg$zzi.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Process finished with exit code 255

GooglePlayServicesUtil is called, not the shadow. I've checked that there is a shadow class of gpsu.

**Comment by erd** [comment]
What version of play services are you using, specifically?

**Comment by xtien** [comment]
It upgraded to 7895000

**Comment by xtien** [comment]
I'm using my own build of Robolectric 3.0, because there were issues in RC2 and RC3. I did rebuild it when this issue came up, but this didn't seem to make a difference.

**Comment by jaredsburrows** [comment]
Use this:

        // Force success
        ShadowGooglePlayServicesUtil.setIsGooglePlayServicesAvailable(ConnectionResult.SUCCESS);

You can change the `ConnectionResult`.

**Comment by jaredsburrows** [comment]
@erd Can we close this?

**Comment by xtien** [comment]
thanks.

**Comment by jaredsburrows** [comment]
@xtien @erd Just to clarify, I have this working with Google Play Services `7.5.0` and not `7.8.0`. See that issue here: https://github.com/robolectric/robolectric/issues/1992.

**Comment by rekire** [comment]
@jaredsburrows where do I need to add this line of code?

**Comment by androchentw** [comment]
This works with Google Play Services `8.1.0` for me, too. Thanks!

@jaredsburrows Before the code you call `GoogleApiAvailability.getInstance()
        .isGooglePlayServicesAvailable(context)`

or just
```
@Before public void setUp() {
    // Force success every time
    ShadowGooglePlayServicesUtil.setIsGooglePlayServicesAvailable(ConnectionResult.SUCCESS);
}

@Afeter public void tearDown() {
    // reset to the default value
    ShadowGooglePlayServicesUtil.setIsGooglePlayServicesAvailable(ConnectionResult.SERVICE_MISSING);
}
```

**Comment by antucg** [comment]
I found a solution and this is to go use again GooglePlayServicesUtil.isGooglePlayServicesAvailable(activity) istead of GoogleApiAvailability.getInstance() .isGooglePlayServicesAvailable(context). If you open the implementation of ShadowGooglePlayServicesUtil you can see it implements GooglePlayServicesUtil, and not GoogleApiAvailability, so ShadowGooglePlayServicesUtil.setIsGooglePlayServicesAvailable won't do anything. I know it is deprecated but until a new Shadow class is created this is the way I found to make it work.

**Comment by jaredsburrows** [comment]
@antucg `GooglePlayServicesUtil` is deprecated.

**Comment by antucg** [comment]
Yes I know, but it's the only solution I found until the Shadow class is created. Other option is to implement it ourselves.

**Comment by gkylafas** [comment]
Well, the solution should be as simple as adding the following class to Robolectric (which is nothing more than a simple copy&rename of the existing `ShadowGooglePlayServicesUtil` class):

````java
package org.robolectric.shadows.gms;

import android.content.Context;
import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.GoogleApiAvailability;
import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;

@Implements(GoogleApiAvailability.class)
public class ShadowGoogleApiAvailability {
    private static int availabilityCode = ConnectionResult.SERVICE_MISSING;

    @Implementation
    public static int isGooglePlayServicesAvailable(Context context) {
        return availabilityCode;
    }

    public static void setIsGooglePlayServicesAvailable(int availabilityCode) {
        ShadowGoogleApiAvailability.availabilityCode = availabilityCode;
    }
}
````

and then calling
```java
ShadowGoogleApiAvailability.setIsGooglePlayServicesAvailable(ConnectionResult.SUCCESS)
```
where appropriate.

**Comment by jtuchek** [comment]
@gkylafas thanks!

**Comment by gkylafas** [comment]
@jtuchek You 're welcome! Bear in mind, though, that version 3.1 comes with a formal implementation of ShadowGoogleApiAvailability, so you shouldn't need to write your own.

**Comment by jaredsburrows** [comment]
@gkylafas Send a PR?

**Comment by gkylafas** [comment]
@jaredsburrows As I said, shadows-play-services 3.1 already includes [ShadowGoogleApiAvailability](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-play-services/src/main/java/org/robolectric/shadows/gms/common/ShadowGoogleApiAvailability.java#L18) and is much more featureful than my simple version here. :-)

**Comment by jaredsburrows** [comment]
@gkylafas You commented on my issue here: https://github.com/robolectric/robolectric/issues/2436. I was not able to get it to work.

**Comment by gkylafas** [comment]
@jaredsburrows Well, yes. As I said in #2436, I had to explicitly add the shadow class to the config like this:

```java
@Config(..., shadows = {ShadowGoogleApiAvailability.class})
public class MyTest {
...
}
```

**Comment by jaredsburrows** [comment]
@gkylafas Alright. Thanks for the clarification!

**Comment by ber4444** [comment]
Not working for me, please have a look: https://stackoverflow.com/questions/48123570/java-lang-noclassdeffounderror-org-robolectric-internal-shadowextractor
