### ISSUE TITLE
Android java.lang.NoClassDefFoundError: R$string

### ISSUE THREAD

**Issue by jonneymendoza** [robolectric/robolectric#1999]
Hi, whenever i run a unit test, i get this error when it tries to retrieve a string value from a custom config.xml file.
# **Background:**

The project itself is a library apk project that uses and references another library APK project.

The error occurs when the project itself tries to initiate a new object that is a subclass of a super class contained on the referenced library apk project.
# **The Issue explained more below**

The specific line of code that fails with the error is a static variable defined below:

```
      protected static final String ANDROID_CONFIG_ID =  LibraryApplication.getApplication().getString(R.string.api_checkout_config_id_override);
```

it fails with the following error:

```
    java.lang.NoClassDefFoundError: com/jon/commonlib/R$string
```

commonLib is the referenced library apk if you are wondering.
# **Here is my unit test**

```
    @RunWith(RobolectricTestRunner.class)
    @Config(constants = BuildConfig.class, manifest=Config.NONE)
    public class TestSearchShows {

        @Test
        public void testSearchJsonFile(){
            EventsTestHelper testHelper = new EventsTestHelper(RuntimeEnvironment.application);

            try {
                ShowsList showList = testHelper.getShowList(new SearchEvent());

                if(showList.getShows().size() < 0){
                    Assert.fail("show list is empty");
                }

            } catch (IOException e) {
                e.printStackTrace();
                Assert.fail(e.toString());
            }
        }


    }
```

The EventsTestHelper is the sub class for a super class called NetworkHelper which looks like this:

```
    public abstract class NetworkHelper<T, P, S> implements NetworkConstants {

    protected static final String ANDROID_CONFIG_ID = LibraryApplication.getApplication().getString(R.string.api_checkout_config_id_override);

    //other stuff ....

    }
```

I use robolectric version 3.0 the latest for runing ,my unit tests.

If i was to run the code live and call and initiate the sub class, it works perfectly fine, no crashes

Kind regards

jonnney

**Comment by jonneymendoza** [comment]
Anyone?

**Comment by jongerrish** [comment]
Are you using Gradle? If so I believe you'll want to use
GradleRobolectricTestRunner

**Comment by jonneymendoza** [comment]
no such thing as GradleRobolectricTestRunner i can see and all examples point to using RobolectricTestRunner

**Comment by jongerrish** [comment]
Sorry, this one:-

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricGradleTestRunner.java

**Comment by asarazan** [comment]
I can confirm that I'm using RobolectricGradleTestRunner and also getting this issue. It seems that whenever a dependency (e.g. com.levelmoney.core) tries to use one of its own resources (e.g. com.levelmoney.core.R.String.hello_world), Robolectric fails.

**Comment by jonneymendoza** [comment]
Hi is there any fix for this? still having same issue

**Comment by treelzebub** [comment]
Also experiencing this using RobolectricGradleTestRunner, accessing two ContentProviders that are in separate libraries. They are both mocked the same way. One passes, one fails with NoClassDefFoundError.

**Comment by asarazan** [comment]
Is there any update or planned progress here? It's starting to become impossible to test without running afoul of this bug.

For example, any AppCompat resources will trigger it-- which means pretty much all `ActivityController`-based tests are out of the question.

**Comment by jonneymendoza** [comment]
No update. It's a pain and I am thinking of ditching this test framework as its not 100 percent compatible with my needs.

**Comment by asarazan** [comment]
For me it's way better than waiting ~7 minutes for the emulator to boot up on CircleCI :-)

**Comment by jonneymendoza** [comment]
Well it doesn't matter how long  it takes if it can't work  correctly

**Comment by nenick** [comment]
Workaround is exist here: https://github.com/robolectric/robolectric/issues/1796#issuecomment-145159854

**Comment by jaredsburrows** [comment]
@jonneymendoza @jongerrish This is a duplicate.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
