### ISSUE TITLE
Views are not drawn

### ISSUE THREAD

**Issue by 1zaman** [robolectric/robolectric#2007]
The drawing callbacks for views are not called in Robolectric 3.0. This causes custom view animations to not work properly. For example, calling `setCurrentItem()` in a `ViewPager` does not result in `onPageScrollStateChanged()` being called with the `SCROLL_STATE_IDLE` state in it's `OnPageChangeListener`, as would occur in the Android runtime.

**Comment by erd** [comment]
This is being worked on #1962.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by antonshkurenko** [comment]
Will it be solved at any time?

**Comment by utzcoz** [comment]
@antonshkurenko Could you check latest Robolectric 4.8.2 for this problem? If this problem still exists, please file a new issue with a minimal reproducible app. Thanks.
