### ISSUE TITLE
Incorrect resource qualifier matching

### ISSUE THREAD

**Issue by davehawkey** [robolectric/robolectric#2009]
It appears the qualifier matching in Robolectric (ResBundle.java) is not correct as it selects resources based on the most atom matches.

For example, if I use qualifiers = "sw600dp-port",  it could select a resource in sw600dp-land because "sw600dp" matches, rather than using the default value. Also, qualifiers = "sw800dp" will not match "sw600dp".

This makes it really hard to test code that uses multiple values across different resource folders.

**Comment by jongerrish** [comment]
Dave, would you be up for sending a PR?

**Comment by davehawkey** [comment]
I'll look into it but not sure when I'll have a chance.

I think the qualifier logic in the platform is in native code and probably
needs to be ported to java. On quick glance I believe the logic is in
ResTable_config::match, ResTable_config::isBetterThan, and
ConfigDescription::parse.

Probably not a trivial change.
