### ISSUE TITLE
FLAG_KEEP_SCREEN_ON is not propagated from resource attribute

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#2012]
The issues comes from SO question:
http://stackoverflow.com/questions/32303361/test-for-keepscreenon-attribute

I've tried to reproduce it and also looked to Robolectric sources.
Flag is there if you set it programmatically:

```
        getWindow().addFlags( WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON );
```

but missed if it is set in resource attributes:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                ...
                android:keepScreenOn="true"
                ...
                tools:context=".MainActivity">
```

**Comment by jongerrish** [comment]
Resource handling has been vastly improved with Robolectric 4.0 and binary resources, give that a try..

Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
