### ISSUE TITLE
MediaPlayer.create returns null after upgrading to Robolectric 3.0 from 2.4

### ISSUE THREAD

**Issue by vanniktech** [robolectric/robolectric#2018]
I just updated to the newest Robolectric version 3.0 from 2.4.

After the migration I executed our tests and all went green except one test:

`MediaPlayer.create` always returns null. It does not matter with which Context I try to initialize it:

```java
RuntimeEnvironment.application.getApplicationContext()
RuntimeEnvironment.application
ShadowApplication.getInstance().getApplicationContext()
```

Is there any workaround for that?

**Comment by jaredsburrows** [comment]
What does your code and test look like? You could initiate `MediaPlayer` and use the setters/getters. The only issue I have is the `start()`.

**Comment by vanniktech** [comment]
There were some things internally wrong. After using the Runner provided by Robolectric and not our custom one this one did work.
