### ISSUE TITLE
Detect violations of StrictMode

### ISSUE THREAD

**Issue by 1zaman** [robolectric/robolectric#2019]
It would be nice if Robolectric detected (and reported an assertion failure on) violations of thread and VM policies defined in [`StrictMode`](https://developer.android.com/reference/android/os/StrictMode.html). It can only be properly implemented after we support multi-threaded code (see point 5 of #1879). Also we might want to have an option to cause an assertion failure if the UI thread is put to sleep (as suggested in point 4).

**Comment by jaredsburrows** [comment]
@1zaman Someone asked something similar here: https://github.com/robolectric/robolectric/issues/1919 about correctly detection violations as well.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
