### ISSUE TITLE
Bad pattern character 'h' in h:mm a

### ISSUE THREAD

**Issue by jshvarts** [robolectric/robolectric#2024]
Hi,

What is the purpose of this class? https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowICU.java.vm

It seems to affect my test with targeting Lollipop SDK. I am running into this exception writing a Robolectric 3.0 test for a layout with a DatePicker:

Caused by: java.lang.IllegalArgumentException: Bad pattern character 'h' in h:mm a
at libcore.icu.ICU.getDateFormatOrder(ICU.java:314)
at android.widget.DatePicker$DatePickerSpinnerDelegate.reorderSpinners(DatePicker.java:947)
at android.widget.DatePicker$DatePickerSpinnerDelegate.**constructor**(DatePicker.java:702)

**Comment by erd** [comment]
It shadows some locale handling code in AOSP that does not well in Robolectric.

**Comment by jshvarts** [comment]
Thanks, Erich. 

Correct me if I am not on the right path but I decided to extend the ShadowICU to overcome the error above (Caused by: java.lang.IllegalArgumentException: Bad pattern character 'h' in h:mm a)

Tried creating this custom shadow:

@Implements(value=libcore.icu.ICU.class, isInAndroidSdk=false)
public class CustomShadowICU extends ShadowICU {
    @Implementation
    public static String getBestDateTimePattern(String skeleton, Locale locale) {
        return skeleton;
    }
}

However, I get a compile error trying to import libcore.icu.*. What dependency can I use to import that package (I use Gradle)? I tried many. 

compile "org.robovm:robovm-rt:1.7.0" fixed the test but I started getting proguard build issues. 

Any help would be greatly appreciated!

**Comment by jshvarts** [comment]
To reiterate, I've never had this issue until I added a custom layout with a DatePicker widget.

**Comment by erd** [comment]
It's part of AOSP. It's available in Robolectric because we load a custom version of Android when tests are run. I don't think you'll be able to create a custom shadow. If you can find a simple test which exposes the problem, I'm happy to commit your fix above.

**Comment by nbarraille** [comment]
I'm having the same issue. To repro just try to inflate a custom view that extends `DatePicker` while targeting SDK 21

**Comment by mpost** [comment]
I am seeing a similar error when running against a holo theme. Using a material based theme on target 21+ seams to work as well.

**Comment by alixwar** [comment]
I'm seeing this in 3.0 on target 19

**Comment by kserko** [comment]
A bit late to the party, but in case anyone else finds themselves in the same situation, I resolved this by following @jshvarts's approach as described [here](https://github.com/robolectric/robolectric/issues/2024#issuecomment-138723229) but instead of doing 
`compile "org.robovm:robovm-rt:1.7.0"` I tried `testCompile "org.robovm:robovm-rt:1.7.0"`. This approach ignores this library when building the app (so no proguard issues) but still provides the desired libcore library when running tests

**Comment by xian** [comment]
I believe this has been fixed for some time, please re-open if not. Thanks!
