### ISSUE TITLE
java.lang.NullPointerException occurs when check permission 

### ISSUE THREAD

**Issue by SidneyXu** [robolectric/robolectric#2028]
In my application, i wrote the following code in onCreate() method and application broken down with the exception message: java.lang.NullPointerException occurs

```java
PackageManager packageManager = context.getPackageManager();
packageManager.checkPermission(permission,
                    context.getPackageName()) == PackageManager.PERMISSION_GRANTED;
```

I found it is because my application contains no permission, and `org.robolectric.res.builder.DefaultPackageManager` doesn't check whether `requestedPermissions` is null or not in line 660.

```java
  @Override
  public int checkPermission(String permName, String pkgName) {
    PackageInfo permissionsInfo = packageInfos.get(pkgName);
    if (permissionsInfo == null) {
      return PackageManager.PERMISSION_DENIED;
    }
    for (String permission : permissionsInfo.requestedPermissions) {
      if (permission != null && permission.equals(permName)) {
        return PackageManager.PERMISSION_GRANTED;
      }
    }
    return PackageManager.PERMISSION_DENIED;
  }
```

**Comment by eric-kansas** [comment]
Confirmed. Also getting the NPE issue with packageManager.checkPermission from our SDK. 

Our code is as follows:
'''
PackageManager packageManager = context.getPackageManager();
packageManager.checkPermission(android.Manifest.permission.READ_PHONE_STATE, context.getPackageName());
'''

The suggested fix above seems accurate.

**Comment by jaredsburrows** [comment]
What line? What are you using for `context`?
