### ISSUE TITLE
SNAPSHOT build is broken?

### ISSUE THREAD

**Issue by bguertin** [robolectric/robolectric#2031]
The 3.1-SNAPSHOT build on sonatype has not been updated since July 9th: https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/

**Comment by erd** [comment]
It seems like the Javadoc generator is failing:

[ERROR] Exit code: 1 - /home/travis/build/robolectric/robolectric/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowIntent.java:17: error: reference not found
[ERROR] * {@link #setClass(android.content.Context, Class)}
[ERROR] ^
[ERROR] /home/travis/build/robolectric/robolectric/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowIntent.java:20: error: reference not found
[ERROR] *         {@link #setClass(android.content.Context, Class)}
[ERROR] ^
[ERROR] /home/travis/build/robolectric/robolectric/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowIntent.java:22: warning - Tag @link: can't find setClass(android.content.Context, Class) in org.robolectric.shadows.ShadowIntent
[ERROR] /home/travis/build/robolectric/robolectric/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowIntent.java:22: warning - Tag @link: can't find setClass(android.content.Context, Class) in org.robolectric.shadows.ShadowIntent
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/travis/build/robolectric/robolectric/robolectric-shadows/shadows-core/target/apidocs' dir.

**Comment by erd** [comment]
SNAPSHOT builds should be working again.
