### ISSUE TITLE
Test hangs

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#2035]
I'm trying to reproduce an issue from SO:
https://github.com/emartynov/robolectic-experiments/blob/master/robolectric-3.0-test/src/test/java/com/bijdorpstudio/myapplication/MainActivityTest.java#L48

However test hangs on the `Button.performClick()`. I've tried to pause execution to understand line which hangs it. But stack trace was quite unclear.

Suggest please what to do next.

**Comment by jongerrish** [comment]
I think you should call ShadowView.click(pickerButton);

What are you doing in your click handler?

**Comment by emartynov** [comment]
I'm showing DatePickerDialog https://github.com/emartynov/robolectic-experiments/blob/master/robolectric-3.0-test/src/main/java/com/bijdorpstudio/myapplication/MainActivity.java#L56

**Comment by jongerrish** [comment]
Can you step into your click handler or did it never reach it?

**Comment by emartynov** [comment]
Ok, playing a bit with debugger and breakpoints in different places, I found `dialog.updateDate()` a point in test where it hangs.
I was thinking that it is because I'm updating the button text in date set listener. And whole test is starting from performing click on that button. So I was thinking that is because of the some threading issue in tests. I commented button text setting and test still hangs.

I'm investigating further

**Comment by emartynov** [comment]
But even having empty handler code hangs test. So looking further

**Comment by nenick** [comment]
@emartynov Maybe its the same issue I have reported at  https://github.com/robolectric/robolectric/issues/1838

Did you wait for about 10 minutes before stopping the test? For me that action finish after a while. Can you try 3.0-rc2 and check if the test still hangs? When not then I guess its the same base issue reported at https://github.com/robolectric/robolectric/issues/1877

**Comment by emartynov** [comment]
Hey @nenick, sorry for delay (was on vacation) and yes, it is my issue. If I leave test running it will finish after around 2-3 minutes. Closing this as duplicate of #1838
