### ISSUE TITLE
gradle 1.4.0-beta2 breaks robolectric.properties

### ISSUE THREAD

**Issue by sneuberger-amazon** [robolectric/robolectric#2041]
I upgraded to "com.android.tools.build:gradle:1.4.0-beta2" (because lint is broken for some java constructs in 1.3.1) and the robolectric test runner can no longer find robolectric.properties.

The tests work when run from the command line, but if you run them from within Android Studio, this line is null https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L407.

This breaks tests completely for me, because robolectric.properties is where I specify @Config's "constants" field. Any idea for a workaround other than annotating every test class?

Looking at the release notes at http://tools.android.com/tech-docs/new-build-system, the first couple bullet points sound suspect:
> - Instead of processing java resources during the packaging of the APK,
moved this upfront before the obfuscation tasks. This will allow
the obfuscation tasks to have a chance to adapt the java resources
following packages obfuscation
> - made java resources extraction from libraries incremental tasks.

**Comment by sneuberger-amazon** [comment]
Workaround for me is to use 1.4.0-beta1.

It looks like the bug is a regression of https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=136013, so I added a comment there.

**Comment by emartynov** [comment]
Looks like I have similar but with beta4 of android gradle plugin

**Comment by jaredsburrows** [comment]
We should wait until it's release.

**Comment by jaredsburrows** [comment]
@sneuberger-amazon I am using the `2.0.0` release and `robolectric.properties` works fine with `3.0.0`. Can we close this? @jongerrish

**Comment by jaredsburrows** [comment]
@sneuberger-amazon @erd @jongerrish Since this is a non-issue, can we close this?
