### ISSUE TITLE
Bouncycastle 1.46 vs 1.52

### ISSUE THREAD

**Issue by xtien** [robolectric/robolectric#2051]
In older versions of Android, Bouncycastle 1.46 is built-in. This means you can't use a later version, because of an incompatibility in the versions of BC later than 1.46. People use Spongycastle as a workaround. In recent versions of Android, there's no BC built-in so you can use BC 1.52. This poses a problem for Robolectric, because on the one hand, you want to support BC 1.46, otoh you don't want to prevent people from using a newer version of BC. Currently, Robolectric includes BC 1.46. I use BC 1.52 so I built a version of Robolectric that does not have BC 1.46. 

The issue is in Android. First, they included a crippled BC 1.46, then they didn't upgrade to a later version, now they don't use BC but there's no backward compatibility. I don't know how Robolectric should solve this issue, other than advising people who don't want to use BC 1.46 to build their own Robolectric version.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
