### ISSUE TITLE
Use Android AOSP DecimalFormat instead of JavaSE

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#2071]
Hi guys,

The issue comes from the SO http://stackoverflow.com/questions/32864889/test-android-decimalformat-with-robolectric.

I was able to reproduce it https://github.com/emartynov/robolectic-experiments/commit/ec428e5e6a266e0160763aacddb56f13b22d7d11#diff-a581cd91cb29842cc78baada52bbbb59R85

Is it correct that Robolectric loads JavaSE `DecimalFormat` instead of AOSP version?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
