### ISSUE TITLE
setViewFocus has unexpected behavior

### ISSUE THREAD

**Issue by jcogilvie** [robolectric/robolectric#2077]
When I call `ShadowView.setViewFocus`, it does not actually focus the view.  It merely calls my `OnFocusChangedListener` with the value I passed.  

I know that we can use `View.requestFocus()` and `View.clearFocus()` (sometimes) to do what I'm asking, but the method is misleading.  It should either force-focus the view (whereas `requestFocus` can fail/return false) or if it's behaving as expected, it should be renamed to something that better matches its behavior (like `invokeFocusChanged`).

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
