### ISSUE TITLE
ShadowImageView.draw(Canvas) does not call onDraw

### ISSUE THREAD

**Issue by jcogilvie** [robolectric/robolectric#2098]
I have a test case where my class (which extends ImageView) overrides onDraw.  I'm trying to mock a Canvas and pass it into draw() so I can verify things that are called on it.

ImageView does some magic in draw(), among which it calls onDraw().  ShadowImageView only does this:  

``` Java
  @Implementation
  public void draw(Canvas canvas) {
    if (imageDrawable != null) {
      imageDrawable.draw(canvas);
    }
  }
```

It should probably also call onDraw(canvas).

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
