### ISSUE TITLE
Resources$NotFoundException if you have a package suffix (v3.0)

### ISSUE THREAD

**Issue by nolanlawson** [robolectric/robolectric#2110]
Follow-up to https://github.com/robolectric/robolectric/issues/1150.

Robolectric throws a `android.content.res.Resources$NotFoundException` if you add a suffix to a debug build. I'm told there are workarounds involving `packageName = 'whatever'`, but nothing is working for me except removing the suffix.

To repro the issue, here's [a fork](https://github.com/nolanlawson/deckard/commit/121a5c2b14da1ab914d28663c698ab71d0a083e0) of the Deckard project.  Steps to repro:

```
git clone https://github.com/nolanlawson/deckard.git -b repro-resource-not-found
cd deckard
./gradlew test
```

**Comment by pepyakin** [comment]
I can confirm that issue. But removing a suffix is not working for me. My root package (where all java files lies) is "com.some.app", but my `applicationId` is "com.some.some". When I set `applicationId "com.some.app"` it works.

**Comment by andrewlord1990** [comment]
We had this issue, as we have suffix of ".dev" for debug builds.
Setting:

`packageName=com.ocado.mobile.android`

in the `robolectric.properties` file fixed the problem for us.

However, we had a problem with `robolectric.properties` actually being used at all. So to test that setting packageName fixes the tests, try it in `@Config` annotation on test first.

To make `robolectric.properties` be parsed and used correctly we had to add Gradle code found here:
https://code.google.com/p/android/issues/detail?id=136013#c10

**Comment by thuytrinh** [comment]
We encountered the same issue. Our app has a suffix ```.debug``` for Debug build and the package is totally different from the ```applicationId```.

**Comment by thuytrinh** [comment]
@andrewlord1990 where did u put the `robolectric.properties` file?

**Comment by IlyaEremin** [comment]
get same error when run tests on flavor with different `applicationId`. Fixed by `packageName` in config. But this is not so cool to add in every test `packageName` =\

**Comment by andrewlord1990** [comment]
It should go in:

`src/test/resources`

As I explained in my above comment, when I added this there was a problem with the file not being found, so I had to add the Gradle code found at https://code.google.com/p/android/issues/detail?id=136013#c10.

**Comment by andrewlord1990** [comment]
@IlyaEremin If you add
````
packageName={packageName}
```
to the file `src/test/resources/robolectric.properties`

Then, add https://gist.github.com/andrewlord1990/25a9da2b8079c968aa57 to your project and add `apply from: 'build-test-fixes.gradle'` to your module `build.gradle`.

Then, you won't need the config annotation anymore.

**Comment by IlyaEremin** [comment]
@andrewlord1990 thanks, I'll tried soon

**Comment by thuytrinh** [comment]
@andrewlord1990 :+1:

**Comment by john1jan** [comment]
Add 
@Config(constants = BuildConfig.class, sdk = 21, packageName = "com.example.package")

the package name should be same as you given in AndroidManifest.xml

check this for details http://tools.android.com/tech-docs/new-build-system/applicationid-vs-packagename

**Comment by andrewlord1990** [comment]
I think this issue can be closed.

**Comment by IgorGanapolsky** [comment]
What is the fix for **Resources$NotFoundException** error?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
