### ISSUE TITLE
Robolectric doesn't unescape strings in XML as Android does

### ISSUE THREAD

**Issue by vgrichina** [robolectric/robolectric#2124]
See here https://github.com/robolectric/robolectric/issues/962#issuecomment-152675317

There has been a fix for similar issue, but it is incomplete. Codes like `\u0020` don't get unescaped properly.

**Comment by ahabbaba9** [comment]
Hey all.
Is there an update on this issue?

**Comment by michael-mohemian** [comment]
👍

**Comment by joaquini** [comment]
👍
