### ISSUE TITLE
Shadows for Design Support Library

### ISSUE THREAD

**Issue by MichaelEvans** [robolectric/robolectric#2127]
Right now testing any custom views that inflate something in the design support library throw an exception like:

```
android.view.InflateException: XML file build/.../layout/test_layout.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.design.widget.CoordinatorLayout
    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.view.View.inflate(View.java:18415)
```

**Comment by nenick** [comment]
Maybe just a configuration issue. Do you use RobolectricGradleTestRunner? And don't specify the AndroidManifest.xml location by self.

**Comment by MichaelEvans** [comment]
```
@Config(
    constants = BuildConfig.class,
    sdk = 21,
    packageName = "com.example.foo"
)
@Ignore
@RunWith(RobolectricGradleTestRunner.class)
```

I'm not specifying the AndroidManifest location at all.

**Comment by jaredsburrows** [comment]
@MichaelEvans @nenick `@Ignore`? Show all of your code in order to reproduce that error.

**Comment by MichaelEvans** [comment]
Oops, sorry - I added the `@Ignore` because of the test failure. 

Fails in my `@Before` method:

```
    @Before
    public void setUp() throws Exception {
        myTestView = new MyTestView(RuntimeEnvironment.application, null);
    }
```

MyTestView:

```
public SponsoredOfferView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
}

private void init() {
        inflate(getContext(), R.layout.my_test_view_layout, this);
        ButterKnife.bind(this);
}
```

my_test_view_layout.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="?attr/colorPrimary"
            android:elevation="@dimen/toolbar_elevation"
            app:layout_scrollFlags="scroll|enterAlways"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
            app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar" />
    </android.support.design.widget.AppBarLayout>

 ... bunch of other views ...

</android.support.design.widget.CoordinatorLayout>
```

**Comment by jaredsburrows** [comment]
I think there is something wrong with your code or test. All my apps use the `CoordinatorLayout` just fine without issues. Have you tried not using this new view you created? I am sure it has to do with this view that your wrote.

Also, I confused as to why you are using Butterknife for views inside of a view? Does this view extend `view`?

**Comment by sonnguyen1187** [comment]
can you try with android.support.v7.widget.GridLayout ? 

what current problem i have "android.content.res.Resources$NotFoundException: Couldn't find ResName{package:attr/columnCount} attr data

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
