### ISSUE TITLE
ShadowLocationManager missing location jitter allowance

### ISSUE THREAD

**Issue by tvoyle** [robolectric/robolectric#2130]
The location manager allows a certain amount of jitter (100ms) from the location provider.

see: 
https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/LocationManagerService.java#139

This means that simulateLocation in ShadowLocationManager will not pass through locations which android would

see:
https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowLocationManager.java#L403

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
