### ISSUE TITLE
View.getLocationInWindow() is not affected by View.setTranslationX/Y()

### ISSUE THREAD

**Issue by pingpongboss** [robolectric/robolectric#2132]
Version: 3.1 SNAPSHOT (at commit 2d89eeaf869ed87367992f36279499f9d3a6b103)

Let's say for some view, `view.getLocationInWindow(int[])` gets you `{100, 200}`.
Now do `view.setTranslationX(50)`.
The next time I call `view.getLocationInWindow(int[])` I expect to get `{150, 200}`. This is what happens when you run this on a device. 
However, in Robolectric, the 2nd call still returns `{100, 200}` even though `view.getTranslationX()` correctly reports `50`.

The test should look like:

```
  private View view;

  @Before
  public void setUp() {
    Activity activity = Robolectric.setupActivity(Activity.class);
    activity.setContentView(R.layout.some_layout);

    View view = activity.findViewById(R.id.some_id);

    activity
        .getWindow()
        .getDecorView()
        .measure(
            MeasureSpec.makeMeasureSpec(WINDOW_WIDTH, MeasureSpec.EXACTLY),
            MeasureSpec.makeMeasureSpec(WINDOW_HEIGHT, MeasureSpec.EXACTLY));
    activity.getWindow().getDecorView().layout(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT);
  }
```

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
