### ISSUE TITLE
AndroidManifest.xml not found if using ABI splits

### ISSUE THREAD

**Issue by csdodd** [robolectric/robolectric#2144]
I have a project that uses [ABI splits](https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide/apk-splits).

This causes AndroidManifest.xml to end up in a slightly different location than that expected by `RobolectricGradleTestRunner`.

 ABI Split State | AndroidManifest.xml location
------------- | -------------
ABI Split Disabled | `build/intermediates/manifests/full/[flavor]/[type]/AndroidManifest.xml`
ABI Split Enabled | `build/intermediates/manifests/full/[flavor]/[abi]/[type]/AndroidManifest.xml`

`RobolectricGradleTestRunner` fails to find AndroidManifest.xml when ABI splits are enabled because it has no concept of which ABI directory to look in (not that it actually matters which one is chosen).

I fixed this by making a local copy of `RobolectricGradleTestRunner` and ensuring the path to the manifest file takes into consideration the ABI directory. It could be possible to fix this by setting ABI in `BuildConfig` (the same way flavor and type are read). I might give it a go myself.

**Comment by adauvalter** [comment]
I'm facing the same problem. Could you please post you solution here?

**Comment by csdodd** [comment]
You need to make your own TestRunner (by copying the code within `RobolectricGradleTestRunner`).

Then inside of `getAppManifest` change the code to include the abi:

    final String  abi = "x86"
    if (FileFsFile.from(BUILD_OUTPUT, "manifests").exists()) {
        manifest = FileFsFile.from(BUILD_OUTPUT, "manifests", "full", flavor, abi, type, "AndroidManifest.xml");
    } else {
        manifest = FileFsFile.from(BUILD_OUTPUT, "bundles", flavor, abi, type, "AndroidManifest.xml");
    }

When you run robolectric it prints to console all the paths it is currently using so you'll easily be able to see if your changes were done correctly or not.
