### ISSUE TITLE
Config parses BuildConfig with quotes around it

### ISSUE THREAD

**Issue by shubhamchaudhary** [robolectric/robolectric#2146]
My properties file is:
```
application=DummyApp
packageName=com.application
constants=com.application.BuildConfig
sdk=21
```

I am getting `java.lang.RuntimeException: Could not load class: "com.application.BuildConfig"`. This is being thrown [here in code](https://github.com/robolectric/robolectric/blob/master/robolectric-annotations/src/main/java/org/robolectric/annotation/Config.java#L145).

Upon further debugging, I figured that it is because the parser adds quotes around the values read for "constants" property [here](https://github.com/robolectric/robolectric/blob/master/robolectric-annotations/src/main/java/org/robolectric/annotation/Config.java#L138).

So it reads constants as `""com.application.BuildConfig""`, which can't be loaded, since it isn't there.

Any information regarding this, plus anything that I might be doing wrong in my properties file?

**Comment by jaredsburrows** [comment]
Why are you specifying `packageName`? What is in your `DummyApp`?

**Comment by shubhamchaudhary** [comment]
This is my current config:
```
application=com.application.DummyApp
constants=com.application.BuildConfig
packageName=com.application
sdk=21
```
It works. I think it was because of unqualified application name

I needed package name because I have multiple build flavor with resources and applicatonIdSuffix. This is used by robolectric to figure out correct resources.

DummyApp is just mocking some stuffs for tests.
