### ISSUE TITLE
How can I shadow custom PackageManager or custom Context

### ISSUE THREAD

**Issue by marcel-paduch** [robolectric/robolectric#2147]
Hey,
I have custom PackageManager in my code and robolectric can't find all methods. How can I create shadow package manager?
All documentation regarding this issue is deprecated in 3.0

**Comment by jaredsburrows** [comment]
This is not a support forum. Only post issues here. @erd Can we close?

Why not work on creating testable code, so you can pass in a context.

**Comment by xian** [comment]
From Robolectric 3.3 on, see the [Migration Guide](http://robolectric.org/migrating/#packagemanager).
