### ISSUE TITLE
"error: cannot access Global" with API Level 16 while calling shadowOf

### ISSUE THREAD

**Issue by leenasn** [robolectric/robolectric#2148]
Hi all,

I've a test to check whether a service has been service or not using getNextStartedService(), but am getting the following error:

`AlarmManagerReceiverTest.java:25: error: cannot access Global
 assertNotNull(shadowOf(RuntimeEnvironment.application).getNextStartedService());`

The test is:

`public class AlarmManagerReceiverTest {

```
@Test
public void startServiceForTheScheduledAlarm(){
    AlarmManagerReceiver alarmManagerReceiver = new AlarmManagerReceiver();
    alarmManagerReceiver.onReceive(RuntimeEnvironment.application, null);
    assertNotNull(shadowOf(RuntimeEnvironment.application).getNextStartedService());
    assertEquals(shadowOf(RuntimeEnvironment.application).getNextStartedService().getComponent().getClassName(),
            SampleIntentService.class.getName());
}
```

}`

If I change the API Level to 19, the error doesn't appear. Can you help me to fix the issue? 

Thanks,
Leena

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
