### ISSUE TITLE
Cannot create paramterized test with instrumented class

### ISSUE THREAD

**Issue by marcel-paduch** [robolectric/robolectric#2150]
Hi,
I use custom test runner in my project because I need to shadow some non android classes, but I also need to use parameterized tests, but parameterized test runner is declared final thus I cannot extend it. 
What should I do in this case?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
