### ISSUE TITLE
Data-driven testing

### ISSUE THREAD

**Issue by realdeadfish** [robolectric/robolectric#2151]
Hi! I'd like to use robolectric to write data-driven tests. Unfortunately, [most](https://github.com/TNG/junit-dataprovider) [of the libraries](https://github.com/junit-team/junit/wiki/Parameterized-tests) [out there](https://github.com/Pragmatists/junitparams) require a custom test runner which naturally conflicts with the requirement of having an instance of the `RobolectricTestRunner` executing the tests. Is there anything that could work with Robolectric that I missed?

**Comment by karlicoss** [comment]
There is a `ParametrizedRobolectricTestRunner` class https://github.com/robolectric/robolectric/blob/9867a2f60d696d35f791df2a2ecdcf0f0f6ab64c/robolectric/src/main/java/org/robolectric/ParameterizedRobolectricTestRunner.java . Although I personally never used it, but it looks suitable for you.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
