### ISSUE TITLE
Android studio 2.0 compatibility

### ISSUE THREAD

**Issue by legarspol** [robolectric/robolectric#2161]
Hi !
Just to let you know that some issue spawn while having the instant run activated in the app.
Not sure who should be warned. An issue ticket got created here:
https://code.google.com/p/android/issues/detail?id=194996

**Comment by jaredsburrows** [comment]
@legarspol Can we close this?
The `code.google` current status:
```
Status: 	Released
Owner: 	c...@google.com
Closed: 	Dec 2015
```
