### ISSUE TITLE
ShadowSystemClock.setCurrentTimeMillis() to optionally assert

### ISSUE THREAD

**Issue by kriegfrj** [robolectric/robolectric#2167]
Per #2122, @charlesmunger and I managed to figure out that `SystemClock.setCurrentTimeMillis()` cannot succeed when called from user code within standard Android, which means that if your code calls it it is (probably) a programming error. Therefore, it would be good if the shadow implementation of this method could optionally assert to alert the developer to the existence of this programming error.

However, on some rooted Android installations, it is possible to (successfully) invoke `setCurrentTimeMillis()` from user code, so some Robolectric users may conceivably still wish to test for the documented behaviour.

Ideally, I think that we should have three different levels of emulation (similar to what I did in `ShadowMediaPlayer`, ref #1472):
- SILENT: do nothing, return false.
- EMULATE: set the wall clock time, return true.
- ASSERT: throw an assertion with an appropriate warning message.

Actually, I'm thinking that this scheme could also be rolled out into other shadows (eg, `ShadowLooper`), so maybe we should look at an overall policy for handling method calls in invalid states.

**Comment by kriegfrj** [comment]
> Actually, I'm thinking that this scheme could also be rolled out into other shadows (eg, 
> `ShadowLooper`), so maybe we should look at an overall policy for handling method calls in invalid
> states.

Came up with a draft of such a policy which I have posted on the Github Robolectric wiki [here](https://github.com/robolectric/robolectric/wiki/Error-and-invalid-state-handling-in-Robolectric-(draft-policy)). Comments welcomed & appreciated.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
