### ISSUE TITLE
Should getProtectionDomain() return null?

### ISSUE THREAD

**Issue by winniehell** [robolectric/robolectric#2172]
`Class.getProtectionDomain()` should always return null [on Android](https://developer.android.com/reference/java/lang/Class.html#getProtectionDomain%28%29). However it returns an instance of `ProtectionDomain` when using Robolectric.

Please compare this [instrumentation test](https://gitlab.com/winniehell/robolectric-sandbox/blob/f6584b2101714058c7973a70f38400cd877af5db/app/src/androidTest/java/de/winniehell/myapplication/ProtectionDomainTest.java#L14-17) &#40;which passes) to this [Robolectric test](https://gitlab.com/winniehell/robolectric-sandbox/blob/f6584b2101714058c7973a70f38400cd877af5db/app/src/test/java/de/winniehell/myapplication/ProtectionDomainTest.java#L15-18) &#40;which fails).

This is especially a problem when combining Robolectric with [FlyWay](http://flywaydb.org/) which [uses](https://github.com/flyway/flyway/blob/7b6aa70b07803a956fd00253f5b6080f93141f21/flyway-core/src/main/java/org/flywaydb/core/internal/util/ClassUtils.java#L112-L114) this method to decide whether a migration is run on an Android device.

**Comment by winniehell** [comment]
After a second thought, I am not sure this is an issue on Robolectric side. It might not be a good idea if Robolectric behaves the same as a real device, because it runs on a different VM.

So rather a question than a bug...

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
