### ISSUE TITLE
robolectric doesn't look at config-package_name when have packagename in the code AndroidManifeast

### ISSUE THREAD

**Issue by elad2109** [robolectric/robolectric#2178]
I want to add robolectric to an existing and live android-dagger project

The problem is that the package name in the AndroidManifest is not aligned with the R file physical path.

robolectric searches for the R file according to the manifest "package_name" attribute.

I thought to use @Config over my robolectric test

```
@Config(manifest = " --my---path/AndroidManifest.xml",
        sdk = 21,
        packageName = "com.google.andorid.apps.ridematch",
        application = TestApplication.class)
```

but apparently robolectric still takes the package name from the AndroidManifeast and not from the  "packageName" annotation.

I think it make sense that if a test has a manifest and a packagename in config annotation, the later which is very specific to a test should override the AndroidManifeast attribute "packagename".

I wanted to debug this in the robolectric open source,
but wasn't sure where was the problematic code.

It was a chance for me to first contribute to a github open-source project

my tries:

try 1)  
I thought the bug is in code:

```
@Test
  public void shouldAssignThePackageNameFromTheManifest() throws Exception {
    AndroidManifest appManifest = newConfigWith("com.wacka.wa", "");
    Application application = defaultTestLifecycle.createApplication(null, appManifest, null);
    shadowOf(application).bind(appManifest, null);

    assertThat(application.getPackageName()).isEqualTo("com.wacka.wa");
    assertThat(application).isExactlyInstanceOf(Application.class);
  }
```

so I wrote this code:

```
@Test
  public void shouldAssignThePackageNameFromConfigWhenHaveConfigAndManifest() throws Exception {
    AndroidManifest appManifest = newConfigWith("com.wacka.wa", "");

    Properties properties = new Properties();
    properties.put("packageName", "com.robolectric.MyTestClass");
    properties.put("application", "com.robolectric.TestTestApplication");
//    properties.put("application", "FakeApp");

    Config config = Config.Implementation.fromProperties(properties);
    Application application = defaultTestLifecycle.createApplication(null, appManifest, config);
    shadowOf(application).bind(appManifest, null);

    assertThat(application.getPackageName()).isEqualTo("com.robolectric.MyTestClass");
    assertThat(application).isExactlyInstanceOf(TestTestApplication.class);
  }
```

In "bind" I made non null config-package name override appManifest package name.

but I couldn't find who calls "defaultTestLifecycle.createApplication"

try 2)  
I started looking at this class and its tests:

  @Override
  protected AndroidManifest getAppManifest(Config config) {

I saw this test:

```
 @Ignore
  @Config(constants = BuildConfig.class, packageName = "fake.package.name")
  public static class PackageNameTest {

    @Test
    public void withoutAnnotation() throws Exception {
    }
  }
```

and I have added mine:

```
 @Ignore
  @Config(constants = BuildConfig.class, packageName = "fake.package2.name", manifest = "//java/com/google/android/apps/ridematch/environments/debug:AndroidManifest.xml")
  public static class PackageNameConfigAndManifestTest {

    @Test
    public void withoutAnnotation() throws Exception {
    }
  }
```

but the test passed, so the bug is not there.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
