### ISSUE TITLE
qualifier ignored for raw resources

### ISSUE THREAD

**Issue by mannaz** [robolectric/robolectric#2179]
When writing tests containing resources from the res/raw-\* folder the qualifier is ignored and the resources are always loaded from the general resource folder.

![raw resource folders with qualifiers](https://cloud.githubusercontent.com/assets/252129/11812884/c9cf0e26-a33e-11e5-90e5-1bfe4f2e2668.png)

```
@Test
public void testRawResourceContentGeneral() {
    assertEquals("File content for raw file without qualifiers", "General", readRawResourceFile(mActivity, R.raw.file));
}

@Test
@Config(qualifiers = "de")
public void testRawResourceContentWithQualifier() {
   // this test fails
    assertEquals("File content for raw file with DE qualifier", "Deutsch", readRawResourceFile(mActivity, R.raw.file));
}
```

See [example project](https://github.com/mannaz/android-studio-robolectric-example/blob/master/app/src/test/java/com/example/joshskeen/myapplication/MyActivityTest.java) for further details.

using robolectric 3.0

**Comment by jaredsburrows** [comment]
Could you try using `assets` directory instead of `res/raw`?

**Comment by mannaz** [comment]
Thanks for the hint. The assets folder does not support qualifiers. Of course I could place the files in `assets` folder with a language qualifier postfix (i.e. "file-de", "file-nl" ...) and load the filename by using string resources in the localized `res/value` directories. But this is just a workaround for my distinctive problem and not a fix for the robolectric error.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
