### ISSUE TITLE
Travis build failed 

### ISSUE THREAD

**Issue by Harlber** [robolectric/robolectric#2185]
As the question title,travis wouldn't be able to build after using robolectric in [my project](https://github.com/Harlber/Moose)
How do I solve this problem?<b>Thanks in advance!</b>

**Comment by hidroh** [comment]
Try to add `exceptionFormat 'full'` to your `build.gradle` so that you can see the stacktrace of failed tests in travis console.

```groovy
android.testOptions.unitTests.all {
    testLogging {
        events 'passed', 'skipped', 'failed', 'standardOut', 'standardError'
        exceptionFormat 'full'
    }
}
```

**Comment by Harlber** [comment]
ye,we discussed in this [issue](https://github.com/hidroh/materialistic/issues/209)
I set the same settings as yours.I found the problem.Travis build failed due to one of test case running failed! .<b>Thank you for your advice and your's materialistic!</b>  @hidroh
