### ISSUE TITLE
Android namespace is required to be declared with xmlns:android prefix

### ISSUE THREAD

**Issue by mgryszko** [robolectric/robolectric#219]
If not (e.g. using xmlns:a prefix), views are not found by Robolectric

**Comment by IgorGanapolsky** [comment]
@mdumrauf What is `Robolectric.application`?  Cannot resolve symbol **application**.

**Comment by westonized** [comment]
@IgorGanapolsky nowadays it's `RuntimeEnvironment.application`

**Comment by mdumrauf** [comment]
@IgorGanapolsky just like @westonized said. My comment is from 2013 so you might be using a different framework version.
