### ISSUE TITLE
Tests crashing Randomly 

### ISSUE THREAD

**Issue by weiznich** [robolectric/robolectric#2198]
When running robolectric tests I randomly get the message:

```
Process 'Gradle Test Executor 1' finished with non-zero exit value 10
```

This happens after a few hundred to one thousand tests. The last test before the test is always a other on.
Source code to reproduce[Mirakel](https://github.com/MirakelX/mirakel-android/)
I could also provide a detailed output of ./gradlew testDebugUnitTest --info --debug, if it is needed.

Robolectric Versions tried: 3.0 and 3.1-Snapshot

**Comment by jaredsburrows** [comment]
What is the error message?

**Comment by weiznich** [comment]
The strange thing is that there is no other error message than mention in the first post.
```
…
de.azapps.mirakel.AllTestsSuite > de.azapps.mirakel.model.list.ListMirakelTest.testSetSyncState10[16] PASSED

754 tests completed, 1 failed
:new_ui:testFdroidDebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':new_ui:testFdroidDebugUnitTest'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 10

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```
Running gradle with --stacktrace did also shown only a exception that Gradle Test Executor has crashed.

**Comment by weiznich** [comment]
Any suggestion on this?

**Comment by jaredsburrows** [comment]
What is the error message? - run `gradlew testDebug --info --debug`
What is the test your are running?
Provide source for the test.
Provide source the code you are testing.

**Comment by weiznich** [comment]
> What is the error message? - run gradlew testDebug --info --debug

There is no error message further than  
```Process 'Gradle Test Executor 1' finished with non-zero exit value 10```
(If you don't believe me there is the [full output](http://zero.azapps.de/?1415edfbe2eda8d8#oQx7Zk7HVVk24iEBiz+lQ2h/N7Xcw10OHCY0v+5/MQs=) )

>What is the test your are running?

I run this [test suite](https://github.com/MirakelX/mirakel-android/blob/master/new_ui/src/test/java/de/azapps/mirakel/AllTestsSuite.java)

>Provide source for the test.
[Here](https://github.com/MirakelX/mirakel-android/blob/master/new_ui/src/test/java/de/azapps/mirakel/)

>Provide source the code you are testing.

[Here](https://github.com/MirakelX/mirakel-android/)

**Comment by jaredsburrows** [comment]
- I am looking at your project now. Any reason you hold a "copy" to all the projects via your own repo: `http://maven.azapps.de/artifactory/mirakel/`? It makes it very slow to setup.

- I would build your builds tools from `23.0.1` to `23.0.2`.

- I get all of these warnings trying to run the project:
```
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
It is no longer possible to set the Jacoco version in the jacoco {} block.
To update the version of Jacoco without updating the android plugin,
add a buildscript dependency on a newer version, for example: buildscript{    dependencies {
        classpath"org.jacoco:org.jacoco.core:0.7.4.201502262128"    }}
```

- I can't run your project as it is coupled to the `local.properties`. :
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/noname/repo/mirakel-android/new_ui/build.gradle' line: 64

* What went wrong:
A problem occurred evaluating project ':new_ui'.
> /Users/noname/repo/mirakel-android/new_ui/local.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 44.642 secs
```

**Comment by weiznich** [comment]
> I am looking at your project now. Any reason you hold a "copy" to all the projects via your own repo: http://maven.azapps.de/artifactory/mirakel/? It makes it very slow to setup.

There was a problem with dependencys where vanish, so we decide to mirror them.

>    I would build your builds tools from 23.0.1 to 23.0.2.
>    I get all of these warnings trying to run the project:

There is already a [patch](https://gerrit.azapps.de/r/#/c/3476/1) for this, but it is not merged

> I can't run your project as it is coupled to the local.properties

There is a local.properties.dist in new_ui. Simply copy this. You will also need a debug.keystore in new_ui. See the keystore.prop file for the exact keystore config.(Ordinary debug keystore)
The keystore is also needed in the dashclock folder.

**Comment by weiznich** [comment]
Are there any news on this?
Are there additional informations needed? 

If there is anything missing let me know.

**Comment by jaredsburrows** [comment]
@weiznich Did you ever update your `build.gradle` files? I couldn't debug your tests.

**Comment by weiznich** [comment]
@jaredsburrows The patch mentioned above is already merged. Furthermore you must copy mirakel/new_ui/local.properties.dist to mirakel/new_ui/local.properties and also copy a debug keystore to mirakel/new_ui/debug.keystore and mirakel/dashclock/debug.keystore.

What is the exact error message?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
