### ISSUE TITLE
Robolectric does not know \p{LATIN} char property name

### ISSUE THREAD

**Issue by kinston123** [robolectric/robolectric#2200]
Sorry for cross-posting: I have already sent this to the mailing-list.

I have a regex 

```
final public static Pattern ONLY_LATIN_LETTERS = Pattern.compile("[\\p{LATIN}\\p{S}\\p{P} ]*");
```

that works fine on an Android device.
When I run tests with Robolectric I get an exception when the pattern is created because LATIN is not recognized as character property name. If I use:

```
final public static Pattern ONLY_LATIN_LETTERS = Pattern.compile("[\\p{IsLatin}\\p{S}\\p{P} ]*");
```

it works with Robolectric but it throws an exception on the device.

I'm using:

```
testCompile "org.robolectric:robolectric:3.0"
testCompile "org.robolectric:shadows-support-v4:3.0"
testCompile "org.robolectric:shadows-multidex:3.0"
testCompile 'junit:junit:4.8.2'
```

Thank you

**Comment by jaredsburrows** [comment]
Instead of `\p{LATIN}` can you try `\p{L}`?

Also, do not compile `junit` with your code. Do this:

From:
`compile 'junit:junit:4.8.2'`

To:

`testCompile 'junit:junit:4.12'`

**Comment by kinston123** [comment]
Right sorry the "compile 'junit:junit:4.8.2'" was wrong. I tried the \p{L}: same problem. And more in general the problem is that there are cases when to run a test with Robolectric would not tell us what it is going to happen on a real phone.

**Comment by apinder** [comment]
Tested with \p{L} and it works fine in Robolectric not tested on a device though. I've not seen the {LATIN} syntax anywhere so not sure which (if any) regex engines support it.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
