### ISSUE TITLE
ResourceParser.XmlResourceParserImpl.getResourceId(...) cannot resolve id attribute with "@+id"

### ISSUE THREAD

**Issue by zbigniew-malinowski** [robolectric/robolectric#2210]
When Robobinding (MVVM library) parses menu xml resource, it looks for _android:id_ attribute using 

```
XmlResourceParser.getAttributeResourceValue(...). 
```

Android implementation can handle both _@id/some_id_ and _@+id/some_id_ formats, but Robolectric's one (_ResourceParser.XmlResourceParserImpl_) does not work with the latter.

It looks like the method tries to strip "@" from qualified name candidate, but should also strip "@+":

```
  if (possiblyQualifiedResourceName.startsWith("@")) {
    possiblyQualifiedResourceName = possiblyQualifiedResourceName.substring(1);
  }
```

File: [org.robolectric.res.builder.ResourceParser](https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/res/builder/ResourceParser.java#L833)

Am I right? If so, I can fix this and make a pull request. 

Just to clarify: _"@id/"_ references existing id and _"@+id/"_ defines a new id and then references it. I'm currently using workaround with defining ids in another resource file.

**Comment by zbigniew-malinowski** [comment]
I've made a [pull request](https://github.com/robolectric/robolectric/pull/2234) solving this problem, please take a look.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
