### ISSUE TITLE
Invalid parent for android-all and other modules

### ISSUE THREAD

**Issue by snakelizzard** [robolectric/robolectric#2214]
Most of robolectic modules configured to have

```
  <parent>
    <groupId>org.sonatype.oss</groupId>
    <artifactId>oss-parent</artifactId>
    <version>7</version>
  </parent>
```

while there is only 8 & 9 versions are available at https://oss.sonatype.org/content/groups/public. This cause for example fail in MavenDependencyResolver if you do not have android-all in local cache.

**Comment by erd** [comment]
We can update this for robolectric and newer versions of android-all, but unless it's a serious issue, I don't want to go back and rebuild android-all for all API levels that we support.

**Comment by snakelizzard** [comment]
Well, I believe, if you will clean your maven cache, it is not possible to run any tests, unless you have `robolectric.offline` setting enabled. So my opinion, it is quite an issue for those who trying robolectric first time.

**Comment by xian** [comment]
It's present here though:
https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom

Are you still seeing issues with this? Please reopen if so. Thanks!
