### ISSUE TITLE
Broadcast receivers are initialized before application

### ISSUE THREAD

**Issue by 1zaman** [robolectric/robolectric#2217]
`ParallelUniverse` tries to associate the resources with the shadow of the `Application` instance before calling it's `onCreate()` callback. This also involves initializing a list of the broadcast receivers registered in the manifest, as well as delivering any sticky broadcasts to their appropriate targets. This can be problematic in case where the broadcast receivers are dependent on the initialization performed in the `onCreate()` callback of the registered `Application` implementation.

**Comment by georgepapas** [comment]
Any movement on this issue? We are seeing the same thing when a receiver is dependant on Dagger Components.

**Comment by jongerrish** [comment]
Hey,

There are other priorities right now, eg API 24 support and fixing the
resource clashing issues. We'd very much welcome a pull request however :-)

J.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by realdadfish** [comment]
This is even more problematic as the initialization of the receivers happens before `Application.onCreate`, so one has to resort to create a `TestApplication` and set up initialization code within the `init {}` block instead of the expected `onCreate` to resolve initialization issues.

**Comment by MGaetan89** [comment]
Is this happening with Robolectric 4.14.1?
Are you able to provide a small reproduction project?

**Comment by realdadfish** [comment]
Yes, this is happening with the most recent version as well. I found another, simpler workaround, I configured a specific test manifest that does not contain the problematic receiver:

In `src/test/resources`

```xml
<?xml version="1.0" encoding="utf-8"?><!--
 Needed because Robolectric will try to instantiate broadcast receivers
 before we're able to set up the test environment properly, see also
 https://github.com/robolectric/robolectric/issues/2217
 -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-sdk android:targetSdkVersion="29" />
</manifest>
```

and my test

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(manifest = "TestManifest.xml")
class MyTest { ... }
```

**Comment by realdadfish** [comment]
For a reproducer I would have to include some application-specific details. We're using Koin for DI, so the receiver is implementing `KoinComponent` and uses `by inject()` on properties to access the Koin graph (which is not existant unless specifically created in a test's `@Before` method).
