### ISSUE TITLE
./scripts/install-robolectric.sh fails on clean checkout

### ISSUE THREAD

**Issue by bfranz** [robolectric/robolectric#2224]
Sorry, for the churn, I couldn't find a forum, so this is my outlet.

I basically cloned the repo, ran ./scripts/install-dependencies.rb which seemed to pass and then
./scripts/install-robolectric.sh which repeatedly fails with different errors.

The first time, I had a bunch of
java.lang.NoClassDefFoundError: Could not initialize class android.content.res.Configuration
    at org.robolectric.shadows.ShadowResources.setSystemResources(ShadowResources.java:98)
    at org.robolectric.shadows.CoreShadowsAdapter.setSystemResources(CoreShadowsAdapter.java:89)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:89)
...

When running the script a second time, I am getting
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /usr/local/google/TeraByte/robolectric/robolectric/src/test/java/org/robolectric/res/ResourceLoaderTest.java:[55,11] error: cannot access ShadowRemoteCallbackList
[ERROR]   class file for ShadowRemoteCallbackList not found
/usr/local/google/TeraByte/robolectric/robolectric/src/test/java/org/robolectric/shadows/ShadowWifiInfoTest.java:[21,4] error: cannot access ShadowArrayAdapter
[ERROR]   class file for ShadowArrayAdapter not found
/usr/local/google/TeraByte/robolectric/robolectric/src/test/java/org/robolectric/shadows/ShadowAnimationUtilsTest.java:[31,31] error: cannot access ShadowLayoutAnimationController
[ERROR]   class file for ShadowLayoutAnimationController not found
/usr/local/google/TeraByte/robolectric/robolectric/src/test/java/org/robolectric/shadows/ShadowTouchDelegateTest.java:[27,25] error: cannot access ShadowTouchDelegate
[ERROR]   class file for ShadowTouchDelegate not found
...

**Comment by erd** [comment]
> Sorry, for the churn, I couldn't find a forum, so this is my outlet.

The mailing list is at `robolectric@googlegroups.com`

I'm stumped. I don't think I've ever seen an error like that before.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
