### ISSUE TITLE
ShadowGeocoder missing in Robolectric 3.0?

### ISSUE THREAD

**Issue by gabga** [robolectric/robolectric#2228]
I am trying to create a test with Robolectric 3.0 for some code that uses `android.location.Geocoder` but the `ShadowGeocoder` that is mentioned in the API documentation (here: http://robolectric.org/javadoc/3.0/org/robolectric/shadows/maps/ShadowGeocoder.html) doesn't seem to be present in the released package.

Also, there seems to be no `shadowOf(android.location.Geocoder)` neither in the documentation nor in the package.

**Comment by erd** [comment]
You need to include the `shadows-maps` add on package:

    compile 'org.robolectric:shadows-maps:3.0'

The `shadowOf` method will be in the class `org.robolectric.shadows.maps.Shadows`

**Comment by gabga** [comment]
Thanks for the answer. Is there any reason why it is not included in the main package? 

This should maybe be documented somewhere.

**Comment by erd** [comment]
We split out any shadow that was not part of the base Android SDK into add-on modules to avoid pulling in unnecessary dependencies. Theoretically, it should be possible to create a set of shadows for any library and have Robolectric pick it up at runtime.

> This should maybe be documented somewhere.

http://robolectric.org/using-add-on-modules/
