### ISSUE TITLE
Robolectric tests missing from Jacoco coverage.

### ISSUE THREAD

**Issue by dampcake** [robolectric/robolectric#2230]
When using the built-in Android Unit Test coverage there is no reported coverage for Robolectric Tests. Standard JUnit tests report fine.

**Demo Project**: 
https://github.com/dampcake/Robolectric-JaCoCo-Sample

**To Reproduce**:
`./gradlew testDebugUnitTestCoverage`

**Output**:
`app/build/reports/jacoco/testDebugUnitTestCoverage/index.html`

**Expected Result**:
100% Coverage

**Actual Result**:
Coverage reported for standard JUnit Tests.
No reported coverage for Robolectric Tests.

**Comment by elsennov** [comment]
+1 same here. Hope somebody could help.

**Comment by WarrenFaith** [comment]
+1 Same here. I tried jacoco 0.7.5 and 0.7.4

**Comment by dampcake** [comment]
dampcake/Robolectric-JaCoCo-Sample@f9884b96ba5e456cddb3d4d2df277065bb26f1d3
Show how to use the fix from Jacoco 0.7.6.

**Comment by alixwar** [comment]
This is now an issue again with JUnit5: https://github.com/robolectric/robolectric/issues/3397

**Comment by huxaiphaer** [comment]
Anybody with an answer?

**Comment by fo2rist** [comment]
@huxaiphaer `includeNoLocationClasses = true` helped in my case. Answered in [another thread](includeNoLocationClasses)

**Comment by huxaiphaer** [comment]
Where is this placed, the link you provided has nothing to show. @fo2rist

**Comment by mannodermaus** [comment]
@huxaiphaer, this is the issue in question: https://github.com/robolectric/robolectric/issues/3397
