### ISSUE TITLE
Trying to use robolectric 3.1 SNAPSHOT Gives these errors

### ISSUE THREAD

**Issue by manorit** [robolectric/robolectric#2231]
Unable to resolve artifact: Failed to resolve artifact, possibly due to a repository list that is not appropriately equipped for this artifact's metadata.
15:25:11.279 [DEBUG] [TestEventLogger]       org.robolectric:shadows-core:jar:3.1-20160122.190808-114
15:25:11.279 [DEBUG] [TestEventLogger] 
15:25:11.279 [DEBUG] [TestEventLogger]     from the specified remote repositories:
15:25:11.279 [DEBUG] [TestEventLogger]       sonatype (https://oss.sonatype.org/content/groups/public/),
15:25:11.279 [DEBUG] [TestEventLogger]       central (http://repo1.maven.org/maven2)
15:25:11.279 [DEBUG] [TestEventLogger] 
15:25:11.280 [DEBUG] [TestEventLogger]     Path to dependency: 
15:25:11.280 [DEBUG] [TestEventLogger]      1) org.apache.maven:super-pom:pom:2.0
15:25:11.280 [DEBUG] [TestEventLogger]      2) org.robolectric:shadows-core:jar:23:3.1-SNAPSHOT
15:25:11.280 [DEBUG] [TestEventLogger]         at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:268)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:168)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:751)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:52)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.robolectric.internal.dependency.CachedDependencyResolver.getLocalArtifactUrls(CachedDependencyResolver.java:43)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.robolectric.internal.InstrumentingClassLoaderFactory.getSdkEnvironment(InstrumentingClassLoaderFactory.java:42)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
15:25:11.280 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:155)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
15:25:11.281 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:25:11.281 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
15:25:11.281 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:25:11.281 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:606)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
15:25:11.281 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
15:25:11.282 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
15:25:11.282 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
15:25:11.282 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:25:11.282 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
15:25:11.282 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:25:11.282 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:606)
15:25:11.282 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:25:11.282 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:25:11.282 [DEBUG] [TestEventLogger]         at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
15:25:11.282 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
15:25:11.282 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
15:25:11.282 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
15:25:11.282 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:745)
15:25:11.282 [DEBUG] [TestEventLogger] 
15:25:11.282 [DEBUG] [TestEventLogger]         Caused by:
15:25:11.283 [DEBUG] [TestEventLogger]         org.apache.maven.artifact.resolver.ArtifactResolutionException: Failed to resolve artifact, possibly due to a repository list that is not appropriately equipped for this artifact's metadata.
15:25:11.283 [DEBUG] [TestEventLogger]           org.robolectric:shadows-core:jar:3.1-20160122.190808-114
15:25:11.283 [DEBUG] [TestEventLogger] 
15:25:11.283 [DEBUG] [TestEventLogger]         from the specified remote repositories:
15:25:11.283 [DEBUG] [TestEventLogger]           sonatype (https://oss.sonatype.org/content/groups/public/),
15:25:11.283 [DEBUG] [TestEventLogger]           central (http://repo1.maven.org/maven2)
15:25:11.283 [DEBUG] [TestEventLogger] 
15:25:11.283 [DEBUG] [TestEventLogger]         Path to dependency: 
15:25:11.283 [DEBUG] [TestEventLogger]          1) org.apache.maven:super-pom:pom:2.0
15:25:11.283 [DEBUG] [TestEventLogger]          2) org.robolectric:shadows-core:jar:23:3.1-SNAPSHOT
15:25:11.283 [DEBUG] [TestEventLogger]             at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:221)
15:25:11.283 [DEBUG] [TestEventLogger]             at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
15:25:11.283 [DEBUG] [TestEventLogger]             at org.apache.maven.artifact.resolver.DefaultArtifactResolver$ResolveArtifactTask.resolveArtifact(DefaultArtifactResolver.java:456)
15:25:11.283 [DEBUG] [TestEventLogger]             at org.apache.maven.artifact.resolver.DefaultArtifactResolver$ResolveArtifactTask.run(DefaultArtifactResolver.java:433)
15:25:11.283 [DEBUG] [TestEventLogger]             ... 3 more

**Comment by wbervoets** [comment]
Did you manage to workaround this issue?

Wim

**Comment by sinistance** [comment]
same here, got this error :(

**Comment by wbervoets** [comment]
Still an error on 3.1-rc1

1) org.robolectric:android-all:jar:4.1.2_r1-robolectric-0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=4.1.2_r1-robolectric-0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=4.1.2_r1-robolectric-0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:android-all:jar:4.1.2_r1-robolectric-0

2) org.robolectric:shadows-core:jar:16:3.1-rc1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1-rc1 -Dclassifier=16 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1-rc1 -Dclassifier=16 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:shadows-core:jar:16:3.1-rc1

**Comment by jongerrish** [comment]
I think we should just package all the dependency jars in a single download and load them from a data directory. Robolectric tests shouldn't have a dependency on an external server and your tests shouldn't break if that server is down.

Should we make org.robolectric.internal.dependency.LocalDependencyResolver the default?

As a work around you can set this manually via these system properties:-

-Drobolectric.offline=true -Drobolectric.dependency.dir=/path/to/android-all/and/shadow-core/jars

**Comment by jaredsburrows** [comment]
@manorit Are you still seeing this? I just tried the latest `3.2-SNAPSHOT` and it works fine.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
