### ISSUE TITLE
PackageManager does not resolve Intents properly

### ISSUE THREAD

**Issue by cperry-gpsw** [robolectric/robolectric#2236]
Given application package `com.example`, and the following Activity declaration in an AndroidManifest.xml file:

``` xml
<activity
    android:name=".activity.ExampleActivity"
    android:screenOrientation="sensor">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
</activity>
```

The following test fails:

``` java
@Test
public void testPackageManager() {
      PackageManager packageManager = getApplicationContext().getPackageManager();

      Intent intent = new Intent(Intent.ACTION_MAIN);
      intent.addCategory(Intent.CATEGORY_LAUNCHER);

      List<ResolveInfo> resolveInfos = packageManager.queryIntentActivities(intent, PackageManager.MATCH_ALL);
      assertThat(resolveInfos).isNotEmpty();
}
```

I ran the test in debug and inspected the contents of the PackageManager (which happens to be org.robolectric.res.builder.DefaultPackageManager). The field `resolveInfoForIntent` is storing information for the Activity but it's stored wrong, the Intent is stored simply as (the string representation being spit out in the debugger):

> Intent{action=com.example.activity.ExampleActivity, extras=Bundle[{}]}

If I change the Intent in my test to this then the test passes:

``` java
Intent intent = new Intent("com.example.activity.ExampleActivity");
```

Of course this is obviously wrong, the action should be:

> android.intent.action.MAIN

and the category should also be there, which it is not.

**Comment by mohitagrawal** [comment]
Is there any plan to fix this issue?

**Comment by jongerrish** [comment]
Hopefully https://github.com/robolectric/robolectric/pull/3449 will fix the issue as we're switching to using the framework IntentFilter.matches() code. I can add the test above to verify tonight.

**Comment by jongerrish** [comment]
OK, I just pushed a commit to that branch to verify that this test works.

The thing is you will also need to call in your tests

shadowOf(packageManager).setQueryIntentImplicitly(true);

I guess this is a vestige of when we didn't parse the manifest, we'd like to switch this on by default but it might break people. I think we'll @Deprecate it in 3.5 (coming out soon) and switch it on and remove it in 3.6.

**Comment by mohitagrawal** [comment]
@jongerrish - Sounds good. Thanks for quick response.

**Comment by jongerrish** [comment]
We made query intents implicitly the default and there has been a big overhaul on PackageManager support.

Mind verifying this with Robolectric 4.0 and reopen if its still an issue?
