### ISSUE TITLE
ShadowRemoteViews shouldn't NPE on nonexistent views

### ISSUE THREAD

**Issue by thenuge** [robolectric/robolectric#2244]
RemoteViews fails silently when you pass it a view ID that doesn't exist. (This may not have been a good idea, but that ship has sailed.) To preserve that behavior, ViewUpdater in ShadowRemoteViews should just return instead of throwing a NPE in the same situation. The current behavior is not only inconsistent with real Android behavior, but is internally inconsistent -- calling a shadowed method crashes, whereas calling a non-shadowed method fails silently.

Happy to do the change myself if there's agreement that it should happen.

**Comment by erd** [comment]
It's preferable that the behavior of the shadow match the behavior of Android (if possible).

**Comment by hoisie** [comment]
It seems like this was resolved in #2314; ShadowRemoteViews doesn't exist any more.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
