### ISSUE TITLE
ShadowMessenger may do more harm than good

### ISSUE THREAD

**Issue by thenuge** [robolectric/robolectric#2246]
I don't have a lot of context for the purpose of this class, but ShadowMessenger as currently implemented has a few problems:
- It only shadows one of two constructors: `Messenger(Handler target)` but not `Messenger(IBinder target)`. This leads to surprises when you have one constructed in each way and they don't behave the same way.
- The shadowed constructor prevents the real Messenger from initializing its internal `IMessenger mTarget` field properly, which results in NPEs in many situations, as `send` is the only other shadowed method.
- ShadowMessenger seems to mostly be doing what Messenger does anyway: it sets a Handler on a Message and then calls `message.sendToTarget`, which in turn calls `handler.sendMessage`. Messenger, similarly, calls `mTarget.send` on its IMessenger, which in the case of a Handler calls `handler.sendMessage`.

I started trying to come up with a way to add a shadow for the 2nd constructor, only to realize that I was just reimplementing Messenger. It's a pretty simple class, and ShadowMessenger doesn't seem to be adding any functionality. Any objections to removing it? In my own tests, I've replaced ShadowMessenger with an empty class shadowing Messenger to essentially revert it to the Android version, and things seem to be working fine. Am I missing the true purpose of this class?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
