### ISSUE TITLE
NoClassDefFoundError at Activity

### ISSUE THREAD

**Issue by elsennov** [robolectric/robolectric#2250]
Hi, i was trying to add unit test to my library. Then i got this issue

```
id.co.coralshop.skyfish.activities.UnderMaintenanceActivityTest > shouldShowEmptyScreen FAILED
    java.lang.NoClassDefFoundError at UnderMaintenanceActivityTest.java:29
        Caused by: java.lang.ClassNotFoundException at UnderMaintenanceActivityTest.java:29
```

Although i have followed the sample code in deckard, i still got the issue.
Here is my UnderMaintenanceActivityTest

```
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class UnderMaintenanceActivityTest {

    @Test
    public void shouldShowEmptyScreen() throws Exception {
        Activity activity = Robolectric.setupActivity(UnderMaintenanceActivity.class);
        View view = activity.findViewById(R.id.empty_container);
        Assert.assertEquals(View.VISIBLE, view.getVisibility());
    }

}
```

UnderMaintenanceActivityTest line 29 is this

```
Activity activity = Robolectric.setupActivity(UnderMaintenanceActivity.class);
```

And here is my gradle for robolectric

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
    testCompile "org.robolectric:robolectric:3.0"
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile 'org.apache.maven:maven-ant-tasks:2.1.3'
    compile 'com.android.support:support-v4:23.1.1'
}
```

Could anybody help? Is there any specific way to implement robolectric in library? Thank you.

**Comment by ncalexan** [comment]
I am seeing somewhat similar `NoClassDefFoundError`.  I recently upgraded a library which I think bumped my `com.android.tools.build:gradle` version from 1.3 to 1.5.  What version of the Android Gradle plugin are you using?  Has this changed recently for you?

**Comment by elsennov** [comment]
@ncalexan I used the 1.5 from the beginning. It seems that robolectric cannot test the library.

**Comment by ncalexan** [comment]
On Tue, Feb 16, 2016 at 7:45 PM, Elsen Novraditya <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> I used the 1.5 from the
> beginning. It seems that robolectric cannot test the library.
>
It may be a *transitive* library issue: it appears that I /can/ access B
from A's tests, where A has a dependency on B; but perhaps I cannot access
C from A's tests, where A has a dependency on B and B has a further
dependency on C.

I will try to confirm this.

**Comment by elsennov** [comment]
@ncalexan If i test on the android application project type, it works. But, if i test on the android library project, it doesn't work.

**Comment by ncalexan** [comment]
On Tue, Feb 16, 2016 at 8:00 PM, Elsen Novraditya <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> If i test on the android
> application project type, it works. But, if i test on the android library
> project, it doesn't work.
>
I agree -- this is what I am seeing.  This wasn't the case for me before --
at least I don't think it was -- so I wonder what has changed?  I do know
that the 1.3 -> 1.5 transition re-worked the DEX process, and presumably
other things in the Android Gradle plugin.  I wonder if Robolectric is
looking for compiled JAR files at a path that has changed?

**Comment by jongerrish** [comment]
GradleRobolectricTestRunner has been removed, instead you can simply use RobolectricTestRunner. You also no longer need to specify @Config(constants = ..., manifest = ...)

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
