### ISSUE TITLE
Shadows for com.android.support:customtabs

### ISSUE THREAD

**Issue by REggar** [robolectric/robolectric#2251]
The (fairly) new Custom Tabs library (com.android.support:customtabs) fails with prewarming. It would be a nice enhancement to build in support for this into Robolectric.

An example of how to use the new custom tabs library can be found here:
https://github.com/GoogleChrome/custom-tabs-client/blob/master/Using.md

**Comment by REggar** [comment]
I got it working with the following (hacky) custom shadow:
https://gist.github.com/REggar/81f2b2df161aac2f4b7b

I had to use a override the package name as CustomTabsSession is protected.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while.

We're generally of the policy that we don't want to maintain shadows for the support library.

The support library team are very pro testing so if you have any testing needs there let me know and we can ask the team if they can support your needs.
