### ISSUE TITLE
Debug.isDebuggerConnected() support needed

### ISSUE THREAD

**Issue by trevjonez** [robolectric/robolectric#2253]
In trying to write meaningful unit tests for multithreaded systems I find that I must make the main thread sleep just long enough for the background work to finish before making assertions on the results.(usually via callback)

The unfortunate downside is that if I sleep on the main thread with a shared variable to watch if the background thread crashes I never reach the callbacks thus the test becomes stuck in a loop.

The next step was to add a max timeout to the sleep loop which works fine in a CI environment. The issue then is that when debugging you have to manually go set the max delay time to some arbitrarily high number or comment out the max timeout portion of the loop. Both require ongoing vigilance and leave us open to human error.

The issue is the timeout gets triggered while debugging and the test ends with my generic timeout failure and junit continues to clean up thus killing the thread you were debugging on.

Given that the code is strictly used inside of unit tests I don't see why this would be an issue to monitor if the debugger is attached. Even with an environment variable to determine things, that still pushes responsibility back onto humans to manage. (leads to errors.)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
