### ISSUE TITLE
ShadowIntent missing implementation on 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by NicoloParolini** [robolectric/robolectric#2270]
We're trying to move on Marshmallow, so I've moved to 3.1-SNAPSHOT which has (should have?) API 23 support. However when I try to build our project the ShadowIntent methods are missing. By looking at code the ShadowIntent from 3.0 has all the implementations while the one from 3.1-SNAPSHOT is empty. Is there anything I need to do before I can use 3.1-SNAPSHOT? Does it support API 23 yet?

Thank you

**Comment by jongerrish** [comment]
I think the shadow intent code was remove so that it the real android code
is used instead. What about shadow intent are you missing?

**Comment by NicoloParolini** [comment]
All of them, first that come to mind are getComponent(), getAction() and getExtras()

**Comment by jongerrish** [comment]
These methods are all available on the real intent, you don't need the
shadow,

http://developer.android.com/reference/android/content/Intent.html

**Comment by NicoloParolini** [comment]
That is true, but it would mean refactoring a few thousands tests to move from shadow intent to real intent... as the original ShadowIntent had them implemented I hoped it would be the case for the new release as well. Does this mean this is not correct? Will the 3.1 release remove the ShadowIntent method implementation?

**Comment by jongerrish** [comment]
Yes.

Agree it's a pain to migrate these changes, I have to do the same for our
codebase ;-)

In general we want to move away from shadow code to invoking real android
code where possible for fidelity purposes.

**Comment by NicoloParolini** [comment]
Ok I removed the shadowIntent and now I am able to build. However I also had to create the GL interface as per https://github.com/robolectric/robolectric/issues/1932. Is that supposed to happen as well?

**Comment by karlicoss** [comment]
@NicoloParolini  it is not supposed, but that's what currently happens on snapshot

**Comment by NicoloParolini** [comment]
Ok thanks all folks I suppose my ShadowIntent quest has ended :)
