### ISSUE TITLE
Resources.getQuantityText() throws UnsupportedOperationException

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2288]
… but Resources.getQuantityString() and Resources.getText() both work.

**Comment by jongerrish** [comment]
Confirmed this works with binary resources.

Anyone facing this issues should upgrade to Robolectric 4.0.1 and configure Gradle as follows:-

testImplementation "org.robolectric:robolectric:4.0.1"

android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}

Add to your gradle.properties

enableUnitTestBinaryResources=true

(I've added a test to CTEsque to verify this)
