### ISSUE TITLE
Please provide a "jar with dependencies" for Robolectric 3.x?

### ISSUE THREAD

**Issue by perezd** [robolectric/robolectric#2292]
It was really nice to have this for 2.x...and it'd make my life easier. I'm trying to use robolectric with Bazel.io

Could this be added?

**Comment by jongerrish** [comment]
You should still be able to use Robolectric with Bazel, in fact, a jar with
dependencies would be dangerous as you still need to consider avoiding
multiple versions of the same class on the class path. These only way
around this would be to use jarjar.

**Comment by perezd** [comment]
the amount of dependencies I'm having to pull in is huge...ant and maven
ant tasks starts ballooning. not even sure why they are needed since I'm
not using maven or ant

**Comment by jongerrish** [comment]
You only need the runtime dependencies, so none of the ant or maven tasks,
unless you're using the maven dependency resolver.

It's more than just about convenience, you still need to deal with multiple
versions of the same class on the class path however.

I guess instructions with links to the deps required at runtime would be
helpful?

**Comment by perezd** [comment]
It would be, yes. I'm getting hit with maven issues at runtime...I'm using
the RobolectricTestRunner.class so I guess thats maven-based? I'm in a
situation where I'm not using maven or gradle..are there options for me?

**Comment by jongerrish** [comment]
Robolectric by default fetches the android jars at runtime from maven.

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/dependency/MavenDependencyResolver.java

You can avoid this and use the local dependency resolver by setting the
robolectric.offline system property

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L94

Which is what I do on my projects, but you'll need to download the jars
locally yourself

**Comment by perezd** [comment]
Which jars do I need? Is that documented? Thanks for the guidance!

**Comment by jongerrish** [comment]
Here are the list of jars we use... you'll need to match them up with the
versions etc defined in the pom.xml files (we don't use maven)

Also, as I said, we don't use maven at run time to resolve the android
dependencies, so if you do the same you'll need to fetch those and store
them locally.

apache_ant
apache_httpclient
asm
asm-tree
asm-util
bouncycastle
icu4j:core
jakarta_commons_codec
json
objenesis
sqlite4java
tagsoup
vtd_xml

Here are those jars:-

                "android-all-6.0.0_r1-robolectric-0.jar",
                "android-all-5.1.1_r9-robolectric-1.jar",
                "android-all-5.1.1_r9-robolectric-0.jar",
                "android-all-5.0.0_r2-robolectric-1-render.jar",
                "android-all-5.0.0_r2-robolectric-1.jar",
                "android-all-4.4_r1-robolectric-1.jar",
                "android-all-4.3_r2-robolectric-0.jar",
                "android-all-4.2.2_r1.2-robolectric-0.jar",
                "android-all-4.1.2_r1-robolectric-0.jar",
                "json-20080701.jar",
                "shadows-core-3.1-SNAPSHOT-16.jar",
                "shadows-core-3.1-SNAPSHOT-17.jar",
                "shadows-core-3.1-SNAPSHOT-18.jar",
                "shadows-core-3.1-SNAPSHOT-19.jar",
                "shadows-core-3.1-SNAPSHOT-21.jar",
                "shadows-core-3.1-SNAPSHOT-22.jar",
                "shadows-core-3.1-SNAPSHOT-23.jar",

**Comment by roman-mazur** [comment]
That said, for sqlite4java you also need native binaries for different
platforms.

**Comment by perezd** [comment]
Thanks for this, why is it not enough to simply have these jars available
on the classpath?

**Comment by jongerrish** [comment]
Because they are loaded by Robolectric's special classloader which
instruments the classes making it possible to hook in the shadowing
behavior.

You compile against the android sdk jar, this is your target SDK, then you
can use Robolectric to run against other versions, swapping in and out the
different versions at run time. This is also what makes it possible to run
tests against multiple versions of the sdk.

**Comment by xian** [comment]
We've got instructions here for fetching dependencies for hermetic builds:
http://robolectric.org/blog/2017/03/01/hermetic-builds/

**Comment by perezd** [comment]
Thanks, this assumes I can use gradle...I was hoping for something like a maven artifact.
