### ISSUE TITLE
shadow changes are invisible to tests until mysterious maven incantations are performed

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2296]
Yuck.

**Comment by jongerrish** [comment]
Yeah, this is fowl. To TDD shadow changes I usually copy the shadow to a static inner class of the test to iterate on it, its awful but I've not found a better way.

I started to migrate the project to Bazel (http://http://bazel.io/) which should provide faster incremental builds, but it doesn't really solve this problem until there is an IDE story for Bazel.

**Comment by erd** [comment]
Yeah. It sucks. It works, but no one is really happy with it.

There is some additional discussion in #1422 that is tangentially related.

**Comment by jongerrish** [comment]
I think this is fixed when @xian killed off the velocity templates.
