### ISSUE TITLE
Use Layoutlib for high fidelity graphics implementations

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2298]
Many of android.graphics.\* classes use native code resulting in a lot of brittle Shadows.

I propose we integrate Layoutlib a JVM implementation of the android graphics library which is used in Eclipse / Android Studio for layout preview rendering.

@erd @xian @ngbravo

**Comment by ngbravo** [comment]
@yuzhong-google

**Comment by mag** [comment]
@jongerrish I am always in favor of eliminating shadows in favor of more realistic behavior, so I'm excited by this proposal!

Could you elaborate on the brittle shadow problem & show a few examples?

Also wondering what other benefits (and drawbacks) we'd get from real rendering. What would you want to do with the rendered images? Implement something like [Facebook's screenshot-tests](https://facebook.github.io/screenshot-tests-for-android/#creating-a-screenshot) stuff?

Also wondering about performance. Would this slow tests down if it was always turned on?

**Comment by jongerrish** [comment]
The shadows in the graphics packages are not very faithful implementations, rather just enough to stop the tests crashing. I've found they are also a lot of work to maintain across api versions.

Pros:
* Easier to support new api versions.
* More faithful behaviour in tests
* Potential to do real rendering, we have a prototype. (so unlocks the door to screen shot tests on the JVM).

Cons:
* Probably slower to some degree

**Comment by yuzhong-google** [comment]
In terms of performance, the prototype rendering test we have takes about 2-3 seconds to inflate a full xml layout file. But for smaller unit tests like ShadowTextPaintTest, the slow is not noticeable.

**Comment by erd** [comment]
I think this would be great!

**Comment by ngbravo** [comment]
Together with @jongerrish we wrote a first draft for a [design doc](https://docs.google.com/a/google.com/document/d/1RxxgxLDssfXg0nBKcufU0q56kQJ083vv0hem51X2ROY/edit?usp=sharing) (you'll need to request access).

Contributions, comments, suggestions and clarifications are very welcome.

**Comment by ngbravo** [comment]
The doc has been updated to specify how exactly are we going to integrate and instrument layoutlib delegates.

**Comment by erd** [comment]
I read through the doc this weekend and it seems like a reasonable approach.

**Comment by ngbravo** [comment]
Work on this will be done in https://github.com/ngbravo/robolectric/tree/layoutlib-integration.

A proper PR will be done once this has become stable.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
