### ISSUE TITLE
Custom styling widget can't test

### ISSUE THREAD

**Issue by infinityzero** [robolectric/robolectric#2302]
Create the very simple project and test with following steps in Android Studio 1.5.1.
1. Create the new android project (Blank Activity without Fragment)
2. Click Build Variants tab > Select Unit Tests
3. Add `testCompile 'org.robolectric:robolectric:3.0'` in app/build.gradle
4. Add the following test class:

```
@Config(constants = BuildConfig.class, sdk = Build.VERSION_CODES.LOLLIPOP)
@RunWith(RobolectricGradleTestRunner.class)
public class ExampleUnitTest {
    @Test
    public void addition_isCorrect() throws Exception {
        MainActivity mainActivity = Robolectric.setupActivity(MainActivity.class);
        TextView textView = (TextView) mainActivity.findViewById(R.id.helloText);
        System.out.println(textView.getText());
    }
}
```

```
5.Right click on `ExampleUnitTest` class > Click Run 'ExampleUnitTest' I get the unit test passed and it is ok.
```

Now, add the following style in `values/styles.xml`:

```
<style name="MyTextView" parent="TextAppearance.AppCompat.Title">
    <item name="android:textColor">#990000</item>
</style>
```

and apply it to TextView (`layout/content_main.xml`) looks like:

```
<TextView
            android:text="Hello World!"
            android:id="@+id/helloText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:theme="@style/MyTextView"/>
```

When I run the test again with above modified codes, running unit test didn't finished even I have waiting a few minutes.

So, stop the test and then test again with command `./gradlew test -i` in Android Studio Terminal get the following [logs](https://gist.github.com/infinityzero/86ac7246c840b37ec83f). 

**Test is still executing at 54% and there are never finished(failed or passed).**

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
