### ISSUE TITLE
ShadowContentObserver does not follow ContentObserver contract

### ISSUE THREAD

**Issue by groakley** [robolectric/robolectric#2307]
I'm trying to test code that relies on content change notifications being posted onto the correct handler. From the Android documentation:

> If a Handler was supplied to the ContentObserver constructor, then a call to the onChange(boolean) method is posted to the handler's message queue. Otherwise, the onChange(boolean) method is invoked immediately on this thread.

The real implementation looks like this:

```
private void ￼dispatchChange(boolean selfChange, Uri uri, int userId) {
￼    if (mHandler == null) {
￼￼        onChange(selfChange, uri, userId);
    } else {
        mHandler.post(new NotificationRunnable(selfChange, uri, userId));
    }
}
```

The shadow implementation is simply:

```
@Implementation
public void dispatchChange(boolean selfChange, Uri uri) {
  realObserver.onChange(selfChange, uri);
}
```

Was there motivation for not following this contract in the shadow? Or was this just an oversight?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
