### ISSUE TITLE
Text Input Layout not yet implemented

### ISSUE THREAD

**Issue by shubhamchaudhary** [robolectric/robolectric#2311]
Got the following exception: 
```
android.view.InflateException: XML file build/intermediates/res/merged/internal/debug/layout/fragment.xml line #-1 
(sorry, not yet implemented): Error inflating class android.support.design.widget.TextInputLayout
```

Any plans or workaround to run these tests while still using TextInputLayout

**Comment by erd** [comment]
We don't yet support the design support library. I've opened up #2312.

**Comment by kingargyle** [comment]
for a temporary solution until the design library is fully supported here is a gist that implements a bare bones shadow.

https://gist.github.com/kingargyle/3b62f02f0e5c8f028499a41fc6d9c362
