### ISSUE TITLE
Add support for design support library

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#2312]
Supporting this as an add-on library would be useful.

**Comment by jaredsburrows** [comment]
:+1: `23.2.1` is the latest.

**Comment by martofeld** [comment]
@erd @jaredsburrows  Any update on this?

**Comment by jongerrish** [comment]
I think, in general where a library is pure Java we don't really want to add a bunch of shadow that need support. What specifically in the design library are you having trouble testing?

**Comment by akaN44** [comment]
@jongerrish The CoordinatorLayout, I always get : 
```
android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/my_fragment.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.design.widget.CoordinatorLayout
```

**Comment by akaN44** [comment]
Actually an empty shadow with constructor do the trick at least for the view inflation. 
```
@Implements(CoordinatorLayout.class)
public class ShadowCoordinatorLayout extends ShadowViewGroup {
    
    public void __constructor__(Context context) {}

    public void __constructor__(Context context, AttributeSet attrs) {}

    public void __constructor__(Context context, AttributeSet attrs, int defStyleAttr) {}
}
```

**Comment by Flaque** [comment]
@jongerrish Many parts of this library aren't pure Java. Examples: TabLayout, AppBarLayout

**Comment by jongerrish** [comment]
@Flaque - Just checked the source code for those classes and there are no native methods there. Am I missing something?
