### ISSUE TITLE
can not import the org.robolectric.shadows.httpclient.FakeHttp

### ISSUE THREAD

**Issue by AaronPlay** [robolectric/robolectric#2313]
My Configuration is
dependencies {
    testCompile "org.robolectric:shadows-multidex:3.0"
    compile 'org.robolectric:robolectric:3.0'
}

And my shadows-core-3.0-sources.jar in gradle's cache did not contain anything about httpclient.

**Comment by iceAnson** [comment]
i have the same problem,how to fix?
