### ISSUE TITLE
Dialogs don't get a real measure/layout pass

### ISSUE THREAD

**Issue by tec27** [robolectric/robolectric#2320]
Activities now get a real layout pass thanks to the `dispatchResized` call in `ActivityController`, which is great! But unfortunately, Dialogs don't get the same treatment. This means that if you have components inside your dialog that depend on having a size in order to do things properly (e.g. RecyclerView inflating child views), this won't work correctly in your test.

The fix here should be rather simple: Dialogs create a new `Window`, so we should be able to just do the same `dispatchResized` logic as in ActivityController when they are shown. I started down the path of implementing this, but quickly ran into the issue that `RuntimeAdapter` and co (needed for making that call) are not available to `robolectric-shadows` code (the dependency goes the other way).

I'd be happy to implement this if someone has thoughts/recommendations on how to structure things.

**Comment by jongerrish** [comment]
Is there something you can do with CoreShadowsAdapter, perhaps pass in the RuntimeAdapter there as state?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
