### ISSUE TITLE
[RuntimeException] Could not find any resource

### ISSUE THREAD

**Issue by adamstyrc** [robolectric/robolectric#2326]
I'm using Robolectic 3.0.

I have created default Android project targeting api 15-23 so I'm using 'com.android.support:appcompat-v7:23.1.1' so my Activities inherits from AppCompatActivity and also the main theme style is:
`<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
...`

I tried to create test for an Activity which would look like:
```
@RunWith(RobolectricGradleTestRunner2.class)
public class SplashActivityTest {

    @Test
    public void clickingLogin_shouldStartLoginActivity() {
        SplashActivity activity = Robolectric.setupActivity(SplashActivity.class);
...
    }
}
```

Because there was warning saying there is no AndroidManifest.xml I created my own **RobolectricTestRunner**:

```
public class RobolectricGradleTestRunner extends RobolectricTestRunner {
    public RobolectricGradleTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    protected AndroidManifest getAppManifest(Config config) {
        String manifestPath = "src/main/AndroidManifest.xml";
        String resPath = "src/main/res";
        return createAppManifest(Fs.fileFromPath(manifestPath),
                Fs.fileFromPath(resPath),
                Fs.fileFromPath("src/main/assets"),
                "");
    }

    @Override
    protected int pickSdkVersion(Config config, AndroidManifest manifest) {
        return 21;
    }
}
```

From here on I get:
`java.lang.RuntimeException: Could not find any resource  from reference ResName{:style/Theme_AppCompat_Light_DarkActionBar} from style StyleData{name='AppTheme', parent='Theme_AppCompat_Light_DarkActionBar'} with theme null`

I also tried to use:
```
        return createAppManifest(Fs.fileFromPath(manifestPath),
                Fs.fileFromPath(resPath),
                Fs.fileFromPath("src/main/assets"),
                "android");
```

but then obviously I get:
`android.content.res.Resources$NotFoundException: no such label android:string/app_name`

It seems that resource merging is broken. I also read that there is problem with AppCompat lib. Is there any solution ? For now I can't write even simplest test

**Comment by jongerrish** [comment]
You should use

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricGradleTestRunner.java

**Comment by adamstyrc** [comment]
Thank you! That helped!

I also had to specify below for my test class:
`@Config(constants = BuildConfig.class)`
