### ISSUE TITLE
False positive result for unmarshalling data from a Parcelable

### ISSUE THREAD

**Issue by harkin** [robolectric/robolectric#2329]
I've encountered a bug where a robolectric test is incorrectly passing.

[Here's a gist](https://gist.github.com/harkin/8fda556cbd985283a640) containing a small code sample that exemplifies this bug. Running both tests in that gist, the `RoboExampleTest` will incorrectly pass while the `ExampleTest` running on a device will correctly fail. 

The bug in that gist is [here](https://gist.github.com/harkin/8fda556cbd985283a640#file-example-java-L15). I'm specifying the wrong `ClassLoader` for the list I want to read; I should be using `Name.class.getClassLoader()`. When the test is run using robolectric the data is unmarshalled correctly despite this bug, but on real devices it will throw a `ClassNotFound` exception. 

I'm using robolectric 3.0 and ran the test on multiple different devices targeting Lollipop and Marshmallow.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
