### ISSUE TITLE
Unable to resolve artifact: Missing:

### ISSUE THREAD

**Issue by guitcastro** [robolectric/robolectric#2333]
I was using Robolectric 3.1SNAPSHOT for a while. But today all my tests began to fail with error:

```
Downloading: org/robolectric/shadows-core/3.1-SNAPSHOT/shadows-core-3.1-20160308.173916-215-21.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
Unable to locate resource in repository
```

Indeed the file does not exist in the [repository](https://oss.sonatype.org/content/groups/public/org/robolectric/shadows-core/3.1-SNAPSHOT/).

Any ideias?

**Comment by guitcastro** [comment]
Everything is working now :)

**Comment by PabloDxCode** [comment]
@guitcastro what did you do for solve it?

**Comment by idsqueretaro** [comment]
> @guitcastro what did you do for solve it?

x2
