### ISSUE TITLE
when I run all tests,custom shadows is invalid？

### ISSUE THREAD

**Issue by geniusmart** [robolectric/robolectric#2343]
when I run all tests,custom shadows is invalid,but when I run single test,that's ok.Code is here:

RealObject is Person.java
```
public class Person{
    private String name;
    public Person(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }
}
```
ShadowObject is ShadowPerson.java
```
@Implements(Person.class)
public class ShadowPerson {

    @Implementation
    public String getName() {
        return "geniusmart";
    }
}

```
the test:
```
@RunWith(CustomShadowTestRunner.class)
@Config(constants = BuildConfig.class,shadows = {ShadowPerson.class})
public class ShadowTest {
    @Test
    public void testCustomShadow(){
        Person person = new Person("genius");
        assertEquals("geniusmart", person.getName());
    }
}
```
CustomShadowTestRunner.java
```
public class CustomShadowTestRunner extends RobolectricGradleTestRunner {

    public CustomShadowTestRunner(Class<?> klass) throws InitializationError {
        super(klass);
    }

    @Override
    public InstrumentationConfiguration createClassLoaderConfig() {
        InstrumentationConfiguration.Builder builder = InstrumentationConfiguration.newBuilder();
        builder.addInstrumentedClass(Person.class.getName());
        return builder.build();
    }
}
```
when I run the single test,it's ok.
![run a test](https://cloud.githubusercontent.com/assets/7712056/13689912/61ae3412-e767-11e5-98bb-f8f5dbff27b4.jpg)

but run all test,
![run all test](https://cloud.githubusercontent.com/assets/7712056/13689925/75e3e36e-e767-11e5-8347-e75b29f4b32d.jpg)
the result is:
```
junit.framework.ComparisonFailure: 
Expected :geniusmart
Actual   :genius
```
that is why?

**Comment by jongerrish** [comment]
You need to hook it up using @Config(shadows = {})

@see http://robolectric.org/custom-shadows/

**Comment by geniusmart** [comment]
@jongerrish That is not my question,I have done just like you said,my question is run a single test and all test results are different,it is failure when i run all tests.I have updated my issue,please look at.

**Comment by jongerrish** [comment]
Which line is failing? This one:

 assertEquals("geniusmart", person.getName());

or this one:

 assertEquals("geniusmart", shadowPerson.getName());

Have you tried debugging this? Does the flow ever enter
Person.getName() or does it get redirected through the shadow?

**Comment by geniusmart** [comment]
@jongerrish 
this one is failing:
assertEquals("geniusmart", person.getName());
I have tried debugging this,when I run single test, it get redirected through the shadow,but when I run all tests,it get redirected through the realObject.

**Comment by jongerrish** [comment]
What test runner are you using?

Would it fail if you just duplicated testCustomShadow() as testCustomShadow2()
so the tests are identical?

**Comment by geniusmart** [comment]
Runner is CustomShadowTestRunner.I code in the issue.

I doubt that is the problem of CustomShadowTestRunner.

testCustomShadow(),testCustomShadow2()? I don't see what you mean.

The code in the issue is all of my code.or this is my project:
https://github.com/geniusmart/LoveUT

**Comment by jongerrish** [comment]
So if you run the entire ShadowTest testCustomShadow() fails. If you just
run testCustomShadow() then testCustomShadow() passes?

Do you really need a custom test runner? You shouldn't need to add the
instrumentation.

**Comment by jongerrish** [comment]
There is only ShadowTest in that package:-

https://github.com/geniusmart/LoveUT/tree/master/sample/src/test/java/com/geniusmart/loveut/shadow

**Comment by geniusmart** [comment]
all tests in com.geniusmart.loveut

not in com.geniusmart.loveut.shadow

**Comment by geniusmart** [comment]
@jongerrish 
all tests in package "com.geniusmart.loveut" , not in "com.geniusmart.loveut.shadow".

it bothered me for a long time.

**Comment by wyvx** [comment]
I experience the same bug.
One test class uses a custom test runner (extension of **RobolectricGradleTestRunner**), which adds a single instrumented class:
```
public class CustomTestRunner extends RobolectricGradleTestRunner {

    public CustomTestRunner(final Class<?> klass) throws InitializationError {
        super(klass);
    }

    @Override
    public InstrumentationConfiguration createClassLoaderConfig() {
        final InstrumentationConfiguration.Builder builder =
                InstrumentationConfiguration.newBuilder();
        builder.addInstrumentedClass(MyClass.class.getName());
        return builder.build();
    }
}
```
I did some testing to gather more info...
Running the test class that uses this TestRunner by itself succeeds.
Running more test classes makes the one using custom test runner fail ONLY if it is NOT the 1st.

Let's say **CustomTest** is the one using **CustomTestRunner**. Running:
```
CustomTest
MyFirstTest
MySecondTest
```
Will succeed. But running:
```
MyFirstTest
CustomTest
MySecondTest
```
Will result in **CustomTest** failing. As if it is ignoring *addInstrumentedClass*.

Not that one can easily manipulate the order of tests, I fiddled with creating and removing tests to confirm this behavior.

**Comment by geniusmart** [comment]
@jongerrish @wyvx 
Thank you for your answer to my quesion.
I have already solved the problem , the solution is:
invoke `addInstrumentedClass` and  `addInstrumentedPackage ` in my custom Test Runner.
Code is here : [CustomShadowTestRunner.java](https://github.com/geniusmart/LoveUT/blob/master/sample/src/test/java/com/geniusmart/loveut/myshadow/CustomShadowTestRunner.java) .

Perhaps this is because there are such logic in [InstrumentationConfiguration.java ](https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/bytecode/InstrumentationConfiguration.java):
```java
  private boolean isInInstrumentedPackage(ClassInfo classInfo) {
    final String className = classInfo.getName();
    for (String instrumentedPackage : instrumentedPackages) {
      if (className.startsWith(instrumentedPackage)) {
        return true;
      }
    }
    return false;
  }
```
