### ISSUE TITLE
Avoid loading the native library when running the unit test

### ISSUE THREAD

**Issue by twmht** [robolectric/robolectric#2344]
Hi, 

I am testing a class which loads a jni library.

Something like this

```
public class myClass {
    static {
        System.loadLibrary("myjni-lib")
    }
    protected native TreeMap<Integer, byte[]> postData(byte[] byteData, String type);
    public boolean upload() {
    // do something
    }
}
```

I do not want to test jni library, but it still loads the library and throws

```
java.lang.UnsatisfiedLinkError: no myjni-lib in java.library.path
```

How can I avoid Robolectric to load the jni library?

It seems that mocking the System class is a bad idea, because System class may be used with Robolectric?

Thank you

**Comment by jaredsburrows** [comment]
@twmht Use a `try/catch` for now.

**Comment by Russel-Zhang** [comment]
@jaredsburrows 
Good trick! Adding a try/catch will solve most of the test failures.

**Comment by joebowbeer** [comment]
See Issue 1171

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by xianghu** [comment]
cool
