### ISSUE TITLE
android-all jar download race (tests failing when maxParallelForks > 1)

### ISSUE THREAD

**Issue by NicoloParolini** [robolectric/robolectric#2346]
When running from a cleaned cache (both ~/.gradle/caches/ and ~/.m2/repository/ empty) with parallel mode enabled, tests fail with this exception:

```
    Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for   artifact 'org.robolectric:shadows-core:jar:16': Failed to build model from file '/Users/nicoloparolini/.m2/repository/org/robolectric/shadows-core/3.0/shadows-core-3.0.pom'.
            Error: 'no more data available - expected end tags </configuration></plugin></plugins></build></project> to close start tag <configuration> from line 131 and start tag <plugin> from line 128 and start tag <plugins> from line 119 and start tag <build> from line 105 and start tag <project> from line 2, parser stopped on TEXT seen ...</generatedSourcesDirectory>\n        </con... @133:14' for project org.robolectric:shadows-core
    org.robolectric:shadows-core:jar:3.0

    from the specified remote repositories:
    sonatype (https://oss.sonatype.org/content/groups/public/),
            central (http://repo1.maven.org/maven2)

                    Path to dependency:
                    1) org.apache.maven:super-pom:pom:2.0

            Caused by:
            org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.robolectric:shadows-core:jar:16': Failed to build model from file '/Users/nicoloparolini/.m2/repository/org/robolectric/shadows-core/3.0/shadows-core-3.0.pom'.
            Error: 'no more data available - expected end tags </configuration></plugin></plugins></build></project> to close start tag <configuration> from line 131 and start tag <plugin> from line 128 and start tag <plugins> from line 119 and start tag <build> from line 105 and start tag <project> from line 2, parser stopped on TEXT seen ...</generatedSourcesDirectory>\n        </con... @133:14' for project org.robolectric:shadows-core
    org.robolectric:shadows-core:jar:3.0

    from the specified remote repositories:
            sonatype (https://oss.sonatype.org/content/groups/public/),
                    central (http://repo1.maven.org/maven2)

                            Path to dependency:
                            1) org.apache.maven:super-pom:pom:2.0

                    Caused by:
                    org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file for artifact 'org.robolectric:shadows-core:jar:16': Failed to build model from file '/Users/nicoloparolini/.m2/repository/org/robolectric/shadows-core/3.0/shadows-core-3.0.pom'.
            Error: 'no more data available - expected end tags </configuration></plugin></plugins></build></project> to close start tag <configuration> from line 131 and start tag <plugin> from line 128 and start tag <plugins> from line 119 and start tag <build> from line 105 and start tag <project> from line 2, parser stopped on TEXT seen ...</generatedSourcesDirectory>\n        </con... @133:14' for project org.robolectric:shadows-core

    Caused by:
    org.apache.maven.project.ProjectBuildingException: Failed to build model from file '/Users/nicoloparolini/.m2/repository/org/robolectric/shadows-core/3.0/shadows-core-3.0.pom'.
    Error: 'no more data available - expected end tags </configuration></plugin></plugins></build></project> to close start tag <configuration> from line 131 and start tag <plugin> from line 128 and start tag <plugins> from line 119 and start tag <build> from line 105 and start tag <project> from line 2, parser stopped on TEXT seen ...</generatedSourcesDirectory>\n        </con... @133:14' for project org.robolectric:shadows-core

    Caused by:
    java.io.EOFException: no more data available - expected end tags </configuration></plugin></plugins></build></project> to close start tag <configuration> from line 131 and start tag <plugin> from line 128 and start tag <plugins> from line 119 and start tag <build> from line 105 and start tag <project> from line 2, parser stopped on TEXT seen ...</generatedSourcesDirectory>\n        </con... @133:14

```

All the requested files are there and in good shape. When the tests are run in single thread mode everything is fine. This has gotten worse with 3.1, but is happening with 3.0 as well.

This attached project will trigger the issue.
[Robotest.zip](https://github.com/robolectric/robolectric/files/167273/Robotest.zip)

I thought it was a Gradle issue, but apparently its not:
[https://discuss.gradle.org/t/running-unit-tests-with-android-plugin-in-parallel-mode-causes-error-while-reading-dependencies/15060](https://discuss.gradle.org/t/running-unit-tests-with-android-plugin-in-parallel-mode-causes-error-while-reading-dependencies/15060)

**Comment by cpoopc** [comment]
i had met the same issue

**Comment by jaredsburrows** [comment]
I tried to reproduce this with @hidroh's project here. I git cloned the project and set the `maxParallelForks` to 2. What does your build.gradle look like?

**Comment by NicoloParolini** [comment]
Pretty stock stuff:
    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 21
        buildToolsVersion "21.1.2"

        defaultConfig {
            applicationId "com.robolectrictest.robotest"
            minSdkVersion 21
            targetSdkVersion 21
            versionCode 1
            versionName "1.0"
        }

        testOptions.unitTests.all {
            testLogging {
                events "failed", "skipped"
                showStackTraces = true
                exceptionFormat = "full"
            }
            maxParallelForks = 8
            forkEvery = 20
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        testCompile 'org.robolectric:robolectric:3.0'
        androidTestCompile 'junit:junit:4.12'
    }

**Comment by scottdweber** [comment]
Has anyone found a solution or workaround for this problem? We are seeing the same problem in our build pipeline.

**Comment by scottdweber** [comment]
Just for completeness-sake, turns out that the problem is downloading the dependencies from Maven. As long as the dependencies are already downloaded and cached locally, all is well. I followed the article below about testing with robolectric in offline mode to workaround the problem by downloading the dependencies using maven command-line prior to starting the tests via Gradle.

http://codeblast.com/2015/05/13/using-robolectric-in-offline-mode/

**Comment by mcclurej06** [comment]
This seems to be resolved. After changing the robolectric version in the example NicoloParolini provided to 3.8, the tests execute successfully.

**Comment by xian** [comment]
Race condition while downloading `android-all.jar` I'm guessing… first thread (or process?) starts downloading via `MavenDependencyResolver`, which creates an empty or truncated file, which the second thread (or process?) uses prematurely.

**Comment by neyguvj** [comment]
I still have this problem on robolectric 4.1
