### ISSUE TITLE
How do I costomize and build my robolectric plugin?

### ISSUE THREAD

**Issue by hiteshmehata** [robolectric/robolectric#2359]
I want to modify few classes in robolectric and build my own plug-in in our test project. I could not find any documents with steeps anywhere. Can someone help?

**Comment by jongerrish** [comment]
Here are the contributor guidelines:- http://robolectric.org/contributing/

**Comment by hiteshmehata** [comment]
Thank. But how do I refer and use the same in the Gradle file.

**Comment by jaredsburrows** [comment]
@hiteshmehata There is no Robolectric plugin. Are you talking about forking and creating a custom Robolectric build or your own shadows? @jongerrish @xian Can we close this? This is not an issue. 

@hiteshmehata Please use https://groups.google.com/forum/#!forum/robolectric for discussions.

**Comment by xian** [comment]
@hiteshmehata please reopen this issue with more information if you like. Thanks!
