### ISSUE TITLE
InflateExcpetion: Error inflating class Seekbar (sorry, not yet implemented)

### ISSUE THREAD

**Issue by priyakar** [robolectric/robolectric#2380]
I am trying to test a fragment in an activity which has a custom drawable for the seekbar track. The test is crashing with the above error. Can anyone please suggest anything that can help get the test to run?
Thanks in advance.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
