### ISSUE TITLE
Latest 3.1 snapshot causes MultipleArtifactsNotFoundException

### ISSUE THREAD

**Issue by alexamster** [robolectric/robolectric#2385]
Running tests used to work (with 3.1 snapshot) but stopped working with the latest.

Failure looks like: 

**BlahTest > testOnDetach STANDARD_ERROR**
    Downloading: org/robolectric/shadows-core/3.1-SNAPSHOT/shadows-core-3.1-20160323.114747-255-21.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Unable to locate resource in repository

**BlahTest > testOnDetach FAILED**
    org.apache.tools.ant.BuildException
        Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException

This is after a clean build.

**Comment by guitcastro** [comment]
+ 1

**Comment by konzeptteam** [comment]
+1

**Comment by LucasCFerraz** [comment]
+1

**Comment by jbruchanov** [comment]
+1

**Comment by papcio28** [comment]
+1

**Comment by jbruchanov** [comment]
Guys, is there any simple workaround or gradle settings which can prevent this situation of broken snapshot build ?
Seems it's happening almost weekly/every couple days like for 30min ~ 1hr (probably because server doesn't publish all built dependencies in same time, usually happens like ~11:00GMT)
I can't use last official release, because there is broken ParametrizedTestRunner

I tried
- Explicit gradle version of snapshot
- put gradle dependency `changing = false`
- make all dependency jars locally stored (seems still downloading the missing dependency)
- not sure about following one, as it's already broken and caches can't be in some "must be refreshed" state
```
configurations.all {
   resolutionStrategy.cacheChangingModulesFor 36, 'hours'
   resolutionStrategy.cacheDynamicVersionsFor 36, 'hours'
}
```

none of those helped :/

**Comment by punksta** [comment]
+1

**Comment by Longi94** [comment]
+1

**Comment by MarcqGuillaumeVO2** [comment]
+1

**Comment by MarcqGuillaumeVO2** [comment]
I think the problem for "https://oss.sonatype.org/content/groups/public/org/robolectric/shadows-core/3.1-SNAPSHOT/" is due that the repository is incomplete.

It lacks all the "shadows-core-3.1-20160323.062302-254-XX.jar" for the last Snapshot. 

Can you launch a new building? plz

**Comment by jbruchanov** [comment]
Something what could help...
delete your robolectric maven local repository usually in ```~/.m2/repository/org/robolectric/``` or similarly on windows ```your_user\.m2\repository\org\robolectric\```
Then download this https://www.dropbox.com/s/o3v1awz5g064y8c/robolectric.zip?dl=0
and extract it into that directory...

**Comment by gofabian** [comment]
> I think the problem for "https://oss.sonatype.org/content/groups/public/org/robolectric/shadows-core/3.1-SNAPSHOT/" is due that the repository is incomplete.
>
>It lacks all the "shadows-core-3.1-20160323.062302-255-XX.jar" for the last Snapshot. 

The problem seems to be solved. The jars are available now.

**Comment by MarcqGuillaumeVO2** [comment]
I confirm, it's good :) 
Thx a lot

**Comment by rburgst** [comment]
IMHO it would still make sense to make an intermediate release. Many of us are using 3.1 for our day to day testing. I don't need the daily latest changes, I just need "something better than 3.0".
Depending on a SNAPSHOT is IMHO less than desirable (as it also causes repeated downloads of new builds).

**Comment by alexamster** [comment]
+1 for releasing 3.1. Like others I'm forced to use 3.1 for testing, and having the snapshot break every few weeks is incredibly frustrating. 

However this specific problem has been fixed so I'm closing the issue.
