### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 1 with Content Provider

### ISSUE THREAD

**Issue by twmht** [robolectric/robolectric#2387]
hi,

This issue is related to #1890 , but the solution does not work if I test my content provider.

Here is my content provider which calls the singleton of `MY_DB` to insert data.

```
    @Override
    public Uri insert(Uri uri, ContentValues values) {
        long rowId = -1;

        switch (mURIMatcher.match(uri)) {
            case MY_DATA:
                rowId = MY_DB.getInstance(mContext).getWritableDatabase().insert(MY_DB.DATA_TABLE, null, values);
                break;
        }

        Uri resultUri = null;
        if (rowId > 0) {
            resultUri = ContentUris.withAppendedId(uri, rowId);
        }
        return resultUri;
    }

```

`getInstance` of `MY_DB` is like this.

```
    public static MY_DB getInstance(Context context){
        if(sInstance == null){
            sInstance = new MY_DB(context, DATABASE_NAME, null, DATABASE_VERSION);
        }
        return sInstance;
    }
```

I have two test cases, the second test case fails due to the `java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-4-thread-1,5,main] []`.

Here is my testcases

```
    @Before
    public void setUp() throws Exception {
        mContext = RuntimeEnvironment.application;
        ShadowLog.stream = System.out;
        MyProvider np = new MyProvider();
        ShadowContentResolver.registerProvider(AUTHORITY, np);
        cr = mContext.getContentResolver();
        np.onCreate();
    }

    @Test
    public void testInsertOpenData() throws Exception {
        Uri dbUri = Uri.withAppendedPath(Uri.parse(AUTHORITY), PATH);
        ContentValues values = new ContentValues();
        values.put("version", 1);
        cr.insert(dbUri, values);

        Cursor cursor = MY_DB.getInstance(mContext).getReadableDatabase().query(MY_DB.DATA_TABLE, null, null, null, null, null, null);
        assertThat(cursor.getCount(), is(equalTo(1)));
    }

    @Test
    public void testInsertOpenDataViaPackageName() throws Exception {
        Uri dbUri = Uri.withAppendedPath(Uri.parse(AUTHORITY), PATH);
        ContentValues values = new ContentValues();
        values.put("version", 1);
        cr.insert(dbUri, values);
        Cursor cursor = MY_DB.getInstance(mContext).getReadableDatabase().query(MY_DB.DATA_TABLE, null, null, null, null, null, null);
        assertThat(cursor.getCount(), is(equalTo(1)));
    }

    @After
    public void tearDown() {
        resetSingleton(My_DB.class, "sInstance");
    }

    public static void resetSingleton(Class clazz, String fieldName) {
        Field instance;
        try {
            instance = clazz.getDeclaredField(fieldName);
            instance.setAccessible(true);
            instance.set(null, null);
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }

```

I found that `resetSingleton` does not effect in the process which loads `MyProvider`.

It seems that `MyProivder` runs in different process.

Any suggestions?

Thank you

**Comment by twmht** [comment]
MyProvider runs in the different process

**Comment by jongerrish** [comment]
You are not closing your database, just nulling it out, you need to close the db correctly, see 

e.g:

  @Before
  public void setUp() throws Exception {
    database = SQLiteDatabase.create(null);
  }

  @After
  public void tearDown() throws Exception {
    database.close();
  }

Not sure what you mean by runs in a different process. All your test code runs in the same process, I don't see you spawning a new process in your example code.

**Comment by twmht** [comment]
I think the content provider runs in different process.

the singleton of `My_DB` is not set to null when runs content provider in the second test case, even I set it to null via `tearDown`.

what I expect is that when calls `insert` with content resolver in the second test case,  the flow of `My_DB.getInstance(mContext)` is as follows

```
 public static MY_DB getInstance(Context context){
        if(sInstance == null){
            Log.w(TAG, "the entry point after tearDown()")
            sInstance = new MY_DB(context, DATABASE_NAME, null, DATABASE_VERSION);
        }
        return sInstance;
    }
  ```

that is, it is null and return the new instance.

But it does not return new instance in the second test case:

```
    @Override
    public Uri insert(Uri uri, ContentValues values) {
        long rowId = -1;

        switch (mURIMatcher.match(uri)) {
            case MY_DATA:
// MY_DB.getInstance(mContext) returns the old instance, so throws the exception
                rowId = MY_DB.getInstance(mContext).getWritableDatabase().insert(MY_DB.DATA_TABLE, null, values);
                break;
        }

    }
```

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by AstralStorm** [comment]
This still happens in Robolectric 4.2.1. As per android docs, you do not know when to close the database in one of these and they're reaped with the process itself.
Consequently, Robolectric is supposed to hold the whole ContentProvider instances alive and not just databases until told to terminate them. It does not do that.

**Comment by HeyItsMedz** [comment]
Can confirm I am also still getting this issue when having more than one test in a class that involves the database

`java.lang.IllegalStateException: Illegal connection pointer 111. Current pointers for thread Thread[SDK 28 Main Thread,5,SDK 28] []`

**Comment by im-not-josh** [comment]
I had a very very similar issue with some unit tests I have been fixing. For me, I needed a combination of closing the DB after each test, resetting the instance AND closing cursors after using them to have the tests pass.

**Comment by blinkmacalahan** [comment]
> I had a very very similar issue with some unit tests I have been fixing. For me, I needed a combination of closing the DB after each test, resetting the instance AND closing cursors after using them to have the tests pass.

Doing this worked for me! I had a Singleton for my SqliteOpenHelper so I used mocks to replace the singleton value with one that was created in @Before and torn down in @After.
