### ISSUE TITLE
Unresponsive Roboelectric tests

### ISSUE THREAD

**Issue by Plastix** [robolectric/robolectric#2396]
I am unable to run Roboelectric tests on my system because they hang indefinitely. Running unit tests through Android Studio and Gradle has the same effect. 

My main development environment is running:

- OSX `10.11.4`
- Android Studio `2.0.0-beta7`
- JDK `1.8.0_40`
- Android SDK `23`
- Gradle Tools `2.0.0-beta7`
- Roboelectric `3.1-SNAPSHOT`

I have also tested using Android Studio `1.5` and Roboelectric `3.0` but it has the same effect. 

A discussion of this issue came up https://github.com/artem-zinnatullin/qualitymatters/issues/145 as well.

**Comment by vanniktech** [comment]
Having the same with `10.11.2`, Android Studio `2.1.0-alpha4`, Gradle Tools `1.5.0` and Robolectric `3.0.0` and JDK 1.6.0

**Comment by Plastix** [comment]
Turns out this is an issue with the AndroidDevMetrics gradle plugin.
