### ISSUE TITLE
ShadowActivity.clickMenuItem causes action view UI side effects to not happen

### ISSUE THREAD

**Issue by awfurtado** [robolectric/robolectric#2399]
ShadowActivity.clickMenuItem ends up instantiating a new RoboMenuItem based on the original menu item's resource id. However, if that menu item is associated with an action view (e.g. a search action view), the RoboMenuItem won't retain that information. So the expected UI side effects when the menu item is clicked, such as having the search action view to expand, won't happen.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
