### ISSUE TITLE
@Config Annotation isn't working correctly when running tests via gradle cli.

### ISSUE THREAD

**Issue by podarsmarty** [robolectric/robolectric#2410]
In my application I have applicationIdSuffix set to ".debug" for a build variant. In my test, I am setting the package name to be the same as in my AndroidManifest.xml using '@Config(packageName = "com.package.name")'
It doesn't work for some reason (afaik it should in robolectric 3.0 though...)

By removing the applicationIdSuffix it works fine. However, if I set the packageName on a global level in robolectric.properties instead it works as expected.

What is weird is that this issue does not happen when running the test via Android Studio but only when running via gradle cli. It fails with 'java.lang.RuntimeException: no ResourceLoader found for com.package.name'

**Comment by jongerrish** [comment]
This should be fixed now....

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
