### ISSUE TITLE
Specifying @Config.packageName does not set the package override.

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2413]
The following test fails:-

  @Test
  @Config(manifest = Config.DEFAULT, packageName = "some.other.package.name")
  public void packageNameOverride() {
    assertEquals("some.other.package.name", RuntimeEnvironment.application.getPackageName());
  }

both with and without a manifest specified. Setting packageName should set the applications package name in all cases.

**Comment by jongerrish** [comment]
Fixed by https://github.com/robolectric/robolectric/commit/9b3e1a99218e50bc53aaed77ef3c12d26ed18856

**Comment by IgorGanapolsky** [comment]
DEFAULT is not a member of `Config`.  Only:
**String DEFAULT_MANIFEST = "--default";
  String DEFAULT_PACKAGE_NAME = "";
  String DEFAULT_ABI_SPLIT = "";
  String DEFAULT_QUALIFIERS = "";
  String DEFAULT_RES_FOLDER = "res";
  String DEFAULT_ASSET_FOLDER = "assets";
  String DEFAULT_BUILD_FOLDER = "build";**
are

**Comment by Malachiasz** [comment]
It's permanently broken as for Robolectric 4.2
Config.java says:

  /**
   * Java package name where the "R.class" file is located. This only needs to be specified if you
   * define an {@code applicationId} associated with {@code productFlavors} or specify {@code
   * applicationIdSuffix} in your build.gradle.
   *
   * <p>If not specified, Robolectric defaults to the {@code applicationId}.
   *
   * @return The java package name for R.class.
   * @deprecated To change your package name please override the applicationId in your build system.
   *     Changing package name here is broken as the package name will no longer match the package
   *     name encoded in the arsc resources file. If you are looking to simulate another application
   *     you can create another applications Context using {@link
   *     android.content.Context#createPackageContext(String, int)}. Note that you must add this
   *     package to {@link org.robolectric.shadows.ShadowPackageManager#addPackage(android.content.pm.PackageInfo)}
   *     first.
   */
  @Deprecated
  String packageName() default DEFAULT_PACKAGE_NAME;
