### ISSUE TITLE
How to configure Roboelectric to (not) run app

### ISSUE THREAD

**Issue by benmarten** [robolectric/robolectric#2414]
I have integrated Robotelectric into one of my projects. Running the tests will launch the actual app, meaning the applications onCreate method is called.

When I scaffold a brand new project and integrate Robolectric, and run the test it does not actually step into the actual app code. Here's the code of the new project:

	@RunWith(RobolectricGradleTestRunner.class)
	@Config(constants = BuildConfig.class, sdk = 21)
	public class ExampleUnitTest {
	  @Mock
	  Context context;

	  @Test
	  public void addition_isCorrect() throws Exception {
	    initMocks(this) // initializes the mockes objecs by annoation
	    assertNotNull(context);
	    assertEquals(4, 2 + 2);
	  }
	}

Does anyone know why my first setup is behaving like this?

**Comment by jongerrish** [comment]
You're not specifying a manifest or application attributes in your @Config.
Robolectric will read the application class from your manifest. If you have
a Test* prefixed Application class it will use that and lastly you can
explicitly specify the appication class using @Config(application =

I recommend not using your real application in unit tests, you want to keep
unit tests small and focussed.

**Comment by benmarten** [comment]
That did indeed solve the issue! Thanks so much for your ultra fast help :) Appreciated!

@Config(application = UnitTestApp.class, constants = BuildConfig.class, sdk = 21)
