### ISSUE TITLE
ShadowLocalBroadcastManager incorrectly checks the IntentFilter

### ISSUE THREAD

**Issue by saiimons** [robolectric/robolectric#2417]
When using the LocalBroadcastManager, some of my receivers are triggered in conditions where they should not.
The reason for this is that the filter is checked using [matchAction and matchData](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-support-v4/src/main/java/org/robolectric/shadows/support/v4/ShadowLocalBroadcastManager.java#L63) instead of the [match](http://developer.android.com/reference/android/content/IntentFilter.html#match%28java.lang.String, java.lang.String, java.lang.String, android.net.Uri, java.util.Set<java.lang.String>, java.lang.String%29) as in the [actual LocalBroadcastManager](https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/content/LocalBroadcastManager.java#L231).

As a result I have false positive / false negative in my tests.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
