### ISSUE TITLE
Robolectric Releases - Please release in a timely fashion

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#2426]
@erd @jongerrish 
**It has almost been a year since Robolectric 3.0 has been released:**
https://github.com/robolectric/robolectric/releases (July 2015).

**Look at the diff between the Robolectric 3.0 release and the master branch:**
https://github.com/robolectric/robolectric/compare/robolectric-3.0...robolectric:master

**It is so big, Github has to truncate it.**

**By releasing more often:**
- It would allow people to test against newer APIs such as API 22 and API 23
- It would cut down on the duplicated issues that are reported
- There are 285+ issues here, with little to no attention, are they still valid?
- I believe people would contribute more if their issues were answered faster and pull requests were merged faster

I think that @jongerrish has spent a lot of time and effort into provided API 23 support, it would be nice to run my unit tests against it.

**Comment by erd** [comment]
The right venue for this feedback is not Github issues.
