### ISSUE TITLE
ShadowPreferenceManager no longer exists?

### ISSUE THREAD

**Issue by rreed** [robolectric/robolectric#2428]
What it says on the tin. Cannot find any replacement for `ShadowPreferenceManager.getDefaultSharedPreferences(foo)`, and the history and docs don't seem to indicate that it was changed intentionally. If this is unintentional, here's an issue. If this was intentional, sweet, but now what? :)

**Comment by jongerrish** [comment]
Just use the same method on the real PreferenceManager.

**Comment by erd** [comment]
Like @jongerrish mentions, you should be able to call methods on the real `PreferenceManager` in your tests. If that doesn't work for you, let us know.
