### ISSUE TITLE
Custom Shadow not invoked for ExoPlayer video view

### ISSUE THREAD

**Issue by Kisty** [robolectric/robolectric#2435]
### Description

Absolutely love Robolectric but I can't seem to make a shadow for EMVideoView (a video wrapper for ExoPlayer, part of the ExoMedia library). The video view itself extends RelativeLayout so it should be a shadow correct?

The problem is that the shadow class methods never get invoked on inflation nor when the tests are operating on the real object. Am I missing something here?
### Steps to Reproduce

https://gist.github.com/Kisty/d529505ca17b89971380546730387021

Thanks!
### Robolectric & Android Version

Robolectric 3.0
Android API 21

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
