### ISSUE TITLE
NPE thrown in Robolectric.buildActivity().withIntent() in 3.1-rc1

### ISSUE THREAD

**Issue by SimonHaenle** [robolectric/robolectric#2440]
### Description
We currently get a NPE when we Execute Robolectric.buildActivity(SomeActivity).withIntent(SomeIntent).setup.get():

java.lang.NullPointerException
        at android.content.ContextWrapper.getPackageName(ContextWrapper.java:131)
        at android.content.ComponentName.__constructor__(ComponentName.java:77)
        at android.content.ComponentName.<init>(ComponentName.java)
        at android.content.Intent.__constructor__(Intent.java:3996)
        at android.content.Intent.<init>(Intent.java)

### Robolectric & Android Version
3.1-rc1
API Level 22

**Comment by jongerrish** [comment]
You need to have a set base context now. What context are you passing in to the constructor of Intent() ?

I would use Robolectric.application

**Comment by SimonHaenle** [comment]
It seems like Robolectric.appliation does not exist in 3.1 rc1. I tried passing RuntimeEnvironment.application, but still get NPE.

**Comment by SimonHaenle** [comment]
Intent intent = new Intent(RuntimeEnvironment.application, MyClass.class);
intent.putExtra("frontendId", "second id");
subject = Robolectric.buildActivity(MyClass.class).withIntent(intent).setup().get();

**Comment by SimonHaenle** [comment]
If anyone reads this and has the same Problems, I managed to fix it by passing the following base Context to the Intent: ShadowApplication.getInstance().getApplicationContext()

**Comment by jongerrish** [comment]
@SimonHaenle To get the application context, just prefer to call RuntimeEnvironment.application and avoid the use of Shadows. Its the same difference in the end but we've removed getApplicationContext() from ShadowApplication at head as we slim down the API.

new Intent(RuntimeEnvironment.application, DestinationActivity.class)

or, just use a constructor that doesn't take a context, e.g:

new Intent("MyAction")

As a reminder, all contexts must now have an attached base context, so either RuntimeEnvironment.application, Robolectric.buildActivity(), Robolectric.buildService() etc. This is what the framework requires.
