### ISSUE TITLE
Merge RobolectricGradleTestRunner + RobolectricTestRunner

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2441]
RobolectricTestRunner is actually MavenRobolectricTestRunner.
RobolectricGradleTestRunner extends RobolectricTestRunner and overrides functionality specific to Gradle.

Ideally we would like to support other build systems such as Buck or Bazel.

Users code should not be tied to the build system they are using.

Merge RobolectricTestRunner and RobolectricGradleTestRunner into a single class that detects the build system being used and switches out a MavenStrategy or GradleStrategy accordingly.

Users will then be free to switch out build systems without changing their code, or even use two separate build systems on the same tests.

**Comment by mag** [comment]
This seems like a great idea. I've always thought it was awkward that our test runner is tied to the build system chosen. I also definitely think we should be thinking about supporting other build systems.

I'm wondering two things:

1. How will you detect the build system? 
2. I'm academically curious about the use case of having a single project buildable by 2 different systems. Is this something you've wanted in the past, or do you know of projects that want it? Given the pain I've felt over the past few years getting my tests running on just a single build technology, I wonder why anybody would take this on given the inherent complexities!

**Comment by ulfjack** [comment]
Bazel team is investigating open sourcing an internal android_robolectric_test rule. Bazel can set in Bazel-specific environment variables to pass in any Bazel-specific data to the test runner. IIUC, The gradle variant already uses env variables for some stuff; it would be best if the RobolectricTestRunner could be rewritten such that it doesn't actually need to know about the build system, as long as the build system sets a specific set of env variables.

If we have to provide Bazel-specific code, it might be preferable to maintain that code in the Bazel project / next to the android_robolectric_test rule, and have a mechanism in RobolectricTestRunner to inject the class (e.g., using an env variable or system property with a class name).

**Comment by jongerrish** [comment]
This has now been implemented.

RobolectricGradleTestRunner has been marked @Deprecated please switch to RobolectricTestRunner
