### ISSUE TITLE
guava - warning: Cannot find annotation method  - Warnings as errors causes builds to fail

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#2446]
### Description
```
/Users/<>/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0-rc2/93e17f60bc524c2610b41c494bb829c11ca89436/guava-19.0-rc2.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
```

### Steps to Reproduce
./gradlew testDebug

### Robolectric & Android Version
Robolectric Version: 3.1-rc1
Android Version: N/A

**Comment by jaredsburrows** [comment]
It looks like Robolectric is using Guava 19.0-rc2. 19 now released. I have tried both. I have even tried rolling back to 16.0.1, like here: https://github.com/robolectric/robolectric/blob/ef76bd75ff3fe62962a3c7a5f1e399474f85eeed/pom.xml#L106.

**Comment by jaredsburrows** [comment]
Based on this old post from Gradle: https://issues.gradle.org/browse/GRADLE-784. Specifically: https://issues.gradle.org/browse/GRADLE-784?focusedCommentId=16577&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16577, you can add `testCompile 'com.google.code.findbugs:jsr305:1.3.9'` to silence the warnings.

**Comment by jaredsburrows** [comment]
@jongerrish Can I make PR for this?

**Comment by jaredsburrows** [comment]
@jongerrish @erd Can I make PR for this?

**Comment by xian** [comment]
Please do! Thanks Jared!

On Fri, Jul 8, 2016 at 20:09 Jared Burrows <notifications@github.com> wrote:

> @jongerrish <https://github.com/jongerrish> @erd <https://github.com/erd>
> Can I make PR for this?
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/robolectric/robolectric/issues/2446#issuecomment-231511570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACdamyzFa2Kbp9dqNMX96bCMdajhNs5ks5qTxD5gaJpZM4IZNax>
> .
>
-- 
--X

**Comment by jaredsburrows** [comment]
@xian I do not remember where I ran into this issue. I am going to close this for now. `3.1.1` is already out.
