### ISSUE TITLE
RobolectricTestRunner should extend Junit (or Junit4), not simulate it

### ISSUE THREAD

**Issue by oozkarao** [robolectric/robolectric#2451]
There are quite a bit helper tools/utils available to run along with Junit4 tests to help set-up environments, do logging, get perf stats, etc. Most of these tools do not work on roboelectric tests merely since they expect Junit4 as the test runner, and fail when they see RoboelectricTestRunner instead. I did not look into the source code, but it looks like this test runner does not extend Junit4, but rather replaces it, causing these issues.

Alternative:
RoboelectricTestRunner could also stay away from overriding the runner at all, and just be an additional hook, so it wouldn't have to deal with the issues of being a test runnner.

**Comment by jongerrish** [comment]
We're kind of stuck with this for the time being, but we will be building a Robolectric implementation for Nitrogen and we'll take a look at removing the need for a custom test runner when we do it.
