### ISSUE TITLE
ShadowDialog getTitle always returns empty string

### ISSUE THREAD

**Issue by rlazo** [robolectric/robolectric#2466]
### Description

ShadowDialog.getTitle uses ShadowWindow to get the window's title. Sadly, it always returns an empty string

https://github.com/robolectric/robolectric/blob/78ef7facd8df6c2c2f8dafedfbc2d1af19f3558e/robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowWindow.java.vm#L51
### Steps to Reproduce

Here is a very simple AndroidStudio project that reproduces this bug

https://dl.dropboxusercontent.com/u/281222/SimpleDialog.zip

the test itself couldn't be more straightforward

```
    DialogFragment fragment = new MyDialogFragment();
    fragment.show(activity.getSupportFragmentManager(), null);
    activity.getSupportFragmentManager().executePendingTransactions();

    Dialog dialog = fragment.getDialog();
    ShadowDialog shadowDialog = Shadows.shadowOf(dialog);

    assertTrue("Expected 'MyTitle', got '" + shadowDialog.getTitle().toString() + "'",
            shadowDialog.getTitle().toString().equals("MyTitle"));
```
### Robolectric Version

3.1 SNAPSHOT (works in 3.0)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
