### ISSUE TITLE
NullPointerException in Parcel.nativeReadFloat()

### ISSUE THREAD

**Issue by rekire** [robolectric/robolectric#2467]
### Description
I'm writing an unit test with unmock which takes classes from this robolectric jar:
https://oss.sonatype.org/content/groups/public/org/robolectric/android-all/6.0.0_r1-robolectric-0/android-all-6.0.0_r1-robolectric-0.jar

### Steps to Reproduce

I'm right now testing a parcable for that I use this code:

    MyParcelable data = new MyParcelable(...);

    Parcel parcel = Parcel.obtain();
    data.writeToParcel(parcel, 0);

    // After you're done with writing, you need to reset the parcel for reading:
    parcel.setDataPosition(0);

    // Reconstruct object from parcel and asserts:
    MyParcelable sut = MyParcelable.CREATOR.createFromParcel(parcel);

In the last line it crashes with this stack trace:

> java.lang.NullPointerException
> 	at android.os.Parcel.nativeReadFloat(Parcel.java)
> 	at android.os.Parcel.readFloat(Parcel.java:1636)
> 	at com.example.MyParcelable.<init>(MyParcelable.java:225)
> 	at com.example.MyParcelable$1.createFromParcel(MyParcelable.java:233)
> 	at com.example.MyParcelable$1.createFromParcel(MyParcelable.java:230)
> 	at com.example.MyParcelable.checkParcelableCode(MyParcelable.java:297)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310)
> 	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
> 	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)

This is my line 225:

    this.total = in.readFloat();

Before that line I execute multiple times `in.readString()` and `in.readInt()` which runs fine.

### Robolectric & Android Version
I'm using the jar which contains the 6.0.0_r1 in its name, since this is a unit test there is no Android Version however I'm targeting API 23.

**Comment by jongerrish** [comment]
This is not a Robolectric issue sorry.

https://github.com/bjoernQ/unmock-plugin

**Comment by rekire** [comment]
I agree with you that this is not oblivious, but the other calls of ShadowParcel work fine just the `Parcel.nativeReadFloat()` call fails, AFIK that method is implemented by you guys. Isn't it? As far I see that the crash is in [ShadowParcel.java.vm](https://github.com/robolectric/robolectric/blob/78ef7facd8df6c2c2f8dafedfbc2d1af19f3558e/robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowParcel.java.vm), you might check it at least once.

**Comment by jongerrish** [comment]
I don't think shadow code is called with this framework is it? Don't see it
in the stack trace at least

**Comment by rekire** [comment]
I guess you are right. I missed that the line numbers didn't match. I opened a [bug](https://github.com/bjoernQ/unmock-plugin/issues/20) there.

Thank you for taking that time.
