### ISSUE TITLE
How do i test recyclerview lazy scroll

### ISSUE THREAD

**Issue by spurdow** [robolectric/robolectric#2477]
### 
1. add lazy scroll to recyclerview
2. programmatically scroll to position 
   ### 

3.0 , latest

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by luongvo** [comment]
@spurdow maybe it relates to https://github.com/robolectric/robolectric/issues/3552
