### ISSUE TITLE
PendingIntent.send() does not supply the correct resultCode to broadcast listener

### ISSUE THREAD

**Issue by olaf-a** [robolectric/robolectric#2481]
### Description

I have a test for a class that sends a text message. The message sending is fine, and with the ShadowSmsManager I can get the parameters. When I call getSentIntent and call send on that PendingIntent, my broadcast receiver is called, but calling getResultCode() always returns 0, no matter what I supply as parameter to the send() method.
### Steps to Reproduce

Make sure that an sms text message was send with a SentIntent.

```
final PendingIntent messageSentIntent = PendingIntent.getBroadcast(mContext, smsId, smsSentIntent, PendingIntent.FLAG_UPDATE_CURRENT);
smsManager.sendTextMessage(receiverNumber, null, messageContent, messageSentIntent, null);
```

then in the test run:

```
final ShadowSmsManager shadowSmsManager = shadowOf(SmsManager.getDefault());
final ShadowSmsManager.TextSmsParams lastSmsParams = shadowSmsManager.getLastSentTextMessageParams();

lastSmsParams.getSentIntent().send(RuntimeEnvironment.application.getApplicationContext(),
                                           SmsManager.RESULT_ERROR_GENERIC_FAILURE, null);
```

In the broadcast receiver for the Intent in smsSentIntent call:

```
public void onReceive(final Context context, final Intent intent) {
    final int resultCode = getResultCode();
}
```

The result of getResultCode is 0, although we supply RESULT_ERROR_GENERIC_FAILURE (which is 1).
### Robolectric & Android Version

Robolectric 3.1-rc1

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
