### ISSUE TITLE
Java 8 Travis build continually times out.

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2486]
### Description

The build often times out, we should either find the root cause and fix this or remove the build for now.

### Steps to Reproduce

Check previous continuous build results, here is an example:-

https://travis-ci.org/robolectric/robolectric/jobs/135127555

### Robolectric & Android Version

Java 8 build only.

**Comment by karlicoss** [comment]
does this happen on particular test? Or just randomly?

**Comment by jongerrish** [comment]
The last test ran on latest failed Java 8 build.
Terminates before finishing the shadows tests.

org.robolectric.shadows.ShadowAppWidgetManagerTest
Killed

Results :

Tests run: 12936, Failures: 0, Errors: 0, Skipped: 15

Compared to 14782 tests run on Java 7 that are run before the support lib tests.

**Comment by jongerrish** [comment]
Now a Java 7 build failure due to a suspected test timeout:

Running org.robolectric.shadows.ShadowDialogPreferenceTest
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by jaredsburrows** [comment]
@jongerrish @xian We have fixed this here: https://github.com/robolectric/robolectric/pull/2570.
