### ISSUE TITLE
Marshmallow support in 3.1

### ISSUE THREAD

**Issue by michael-shim-qm** [robolectric/robolectric#2495]
3.1 claims to support Marshmallow but I can still see apache http functions are being used in several places. They are supposed to be changed to HttpURLConnection series. Because of this, we still need to use gradle statment   useLibrary 'org.apache.http.legacy'.

**Comment by jongerrish** [comment]
What usages are you referring to?

I only see usages from the shadows-httpclient module which is optional and you can drop it if you don't use apache

**Comment by jaredsburrows** [comment]
@michael-shim-qm I have been using Robolectric since 2.4. I have used 2.4, 3.0 and 3.1 and I have never had to use `'org.apache.http.legacy'`. This is on your end.
