### ISSUE TITLE
How to use the Robolectric test runonuithread inside thread?

### ISSUE THREAD

**Issue by vsay01** [robolectric/robolectric#2514]
### Description

I have an implementation that triggered in onResume(); I want to test the piece of code that inside the thread.
Here is the piece of code I want to test:

```
new Thread() { 
    public void run() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                  tv.setVisibility(View.GONE);
            }
        });
    }
 }.start();`
```

If I put it inside only the **runOnUiThread**, 

```
 runOnUiThread(new Runnable() {
            @Override
            public void run() {
                  tv.setVisibility(View.GONE);
            }
        });
```

then it is working.

One possible solution I have is to call a method that return Runnable so that the piece of code executed.

```
mActivity.runOnUiThread(mActivity.getRunnableMethod());
```

Are there any other way using Robolectric so that even inside another Thread, the runOnUiThread will be executed?
Or
How Robolectric test the code inside thread?
### Robolectric & Android Version

org.robolectric:robolectric:3.0

Related opened issue: [#2479](https://github.com/robolectric/robolectric/issues/2479)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
