### ISSUE TITLE
Application override no longer working in 3.1

### ISSUE THREAD

**Issue by grantbdev** [robolectric/robolectric#2515]
### Description
I just upgraded from Robolectric 3.0 to Robolectric 3.1. My tests are supposed to communicate with a [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) and I need to change the resource string that the app uses to connect to the server. The trick I was using with overriding the application class to do this string replacement for tests worked on 3.0 not on 3.1.

### Steps to Reproduce
My tests are configured with a custom application class: `@Config(application = TestApp.class)`.
In TestApp.class, which extends from my custom application class, I have this override:
```
@Override
public Resources getResources() {
    Resources resources = spy(super.getResources());
    when(resources.getString(R.string.my_api_url)).thenReturn(MyMockServer.serverUrl);
    return resources;
}
```
The bulk of the above method is using methods provided by Mockito.

With Robolectric 3.0, if I called getString(R.string.my_api_url) in an activity it would return the mock server URL. With Robolectric 3.1, it returns the production server URL.

To see this in a short test:
```
@Test
public void checkResources() {
    someActivity = Robolectric.setupActivity(SomeActivity.class);
    String url = someActivity.getString(R.string.my_api_url);
    assertEquals(url, MyMockServer.serverUrl);
}
```

This test passes with 3.0 and fails with 3.1 with everything else the same.

However, this does pass on 3.1:
```
@Test
public void checkResources() {
    someActivity = Robolectric.setupActivity(SomeActivity.class);
    String url = RuntimeEnvironment.application.getString(R.string.my_api_url);
    assertEquals(url, MyMockServer.serverUrl);
}
```

So it is not a fault with Mockito. TestApp.getResources() is not getting called by the activity like it used to.

### Robolectric & Android Version
Worked with Robolectric 3.0 and `@Config(sdk = 21)`
Fails with Robolectric 3.1 and `@Config(sdk = 21)` or `@Config(sdk = 23)`

If anyone knows a workaround to achieve the same effect with 3.1, that would be appreciated.

**Comment by jongerrish** [comment]
You should avoid spying/mocking Android framework classes (other than maybe simple listener classes etc), it's brittle and you can break when there are either changes to the internals of Robolectric or the Android framework (e.g between API versions).

I'd probably have the server URL provided by some configuration object that you can mock, or use a fake.

**Comment by grantbdev** [comment]
I adjusted my sever URL strategy and I now have my use case working without a test application class or spying Resources.

However, the issue was not spying/mocking, it is that the overrided method on the test application class configured in Robolectric was not being called as it used to be. If that was not an intended use case, feel free to close this.

**Comment by jongerrish** [comment]
Yes, it is not recommended to override android methods like this.
