### ISSUE TITLE
Why are you using Guava 19.0-rc2 ? 

### ISSUE THREAD

**Issue by bobymicroby** [robolectric/robolectric#2523]
Since December last year there is Guava 19, is there any reason you are still
using the RC ?

**Comment by jongerrish** [comment]
I doubt it. Want to send a PR to update it?

**Comment by bobymicroby** [comment]
Forking :)

**Comment by jongerrish** [comment]
Fixed in https://github.com/robolectric/robolectric/commit/76f0e9000585a48c85fe0924ad71372740861966
