### ISSUE TITLE
InstrumentingClassLoader fails as a parent ClassLoader

### ISSUE THREAD

**Issue by ejona86** [robolectric/robolectric#2526]
### Description

`InstrumentingClassLoader` does not work properly as a parent class loader, due to missing `loadClass(String, boolean)` overload which is [called by `ClassLoader.loadClass(String, boolean)`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/ClassLoader.java/#411). Instead of overriding [`loadClass(String)`](https://github.com/robolectric/robolectric/blob/7f2814c/robolectric/src/main/java/org/robolectric/internal/bytecode/InstrumentingClassLoader.java#L110), `InstrumentingClassLoader` should override `loadClass(String, boolean)`.

This can produce very weird behavior since multiple class definitions for the same class will exist, including `ServiceLoader` throwing `java.util.ServiceConfigurationError` "Provider X not a subtype" since the extending class and its ancestors were loaded from the normal class loader but the class doing the call is loaded from `InstrumentingClassLoader`
### Steps to Reproduce

These two lines return different classes, but they shouldn't:

``` java
Class<?> class1 = Class.forName("some.class", false,
    this.getClass().getClassLoader());
Class<?> class2 = Class.forName("some.class", false,
    new ClassLoader(this.getClass().getClassLoader()){});
System.out.println(class1 == class2);
```
### Robolectric & Android Version

3.1 SNAPSHOT, commit 78ef7facd8d

**Comment by ejona86** [comment]
My previous test didn't quite precise enough, because it depended a lot on the environment and order of operations happening outside of the code snippet. This unit test should work:

```java
class OnlyUsedByChildClassLoaderTest {}

@Test
public void testChildClassLoaderReturnsSameInstanceAsParent() throws Exception {
  // Must not use .class. This class must be loaded from the child first
  String name = getClass().getName() + "$OnlyUsedByChildClassLoaderTest";
  // Note that reversing this line and the next line produces different results
  Class<?> fromChild = Class.forName(name, false,
      new ClassLoader(getClass().getClassLoader()) {});
  Class<?> fromIntrumented = Class.forName(name, false,
      getClass().getClassLoader());
  // Just a sanity test
  assertThat(fromIntrumented).isSameAs(OnlyUsedByChildClassLoaderTest.class);
  // The real verification
  assertThat(fromChild).isSameAs(fromIntrumented);
}
```

**Comment by jongerrish** [comment]
I believe this has been fixed.
