### ISSUE TITLE
junit tests hang then aborted under Jenkins

### ISSUE THREAD

**Issue by gkraft4** [robolectric/robolectric#2527]
### Description

We are running our Android Robolectric junit tests on a Jenkins (Windows) v1.651.1 server.   Our tests randomly hang, then get timed out and aborted more often than not.   Our Robolectric junits seem to run fine in Android Studio on our laptops (ie., Linux, OS X, Windows).
https://issues.jenkins-ci.org/browse/JENKINS-23865
### Steps to Reproduce

gradlew -d -a :myProduct:testMyUnitTest
### Robolectric & Android Version

org.robolectric:robolectric:3.0
android-sdk_r25.1.7-windows
jdk1.7.0
Using JDK 7 file service org.gradle.internal.nativeintegration.filesystem.jdk7.WindowsJdk7Symlink

**Comment by hzsweers** [comment]
We are seeing this as well

**Comment by gkraft4** [comment]
We have moved from a Windows based Jenkins server to a RHEL7 Linux server, and our Robolectric junits are no longer hanging then aborting!   :-)

**Comment by ScottPierce** [comment]
I'm seeing my tests hang as well, but they eventually finish, and it's in Android Studio: https://github.com/robolectric/robolectric/issues/3287

**Comment by utzcoz** [comment]
Please try the latest Robolectric version, and feel free to reopen it if it still exists.
