### ISSUE TITLE
Robolectrics does not support native libraries like those that are bundled with Realm. 

### ISSUE THREAD

**Issue by Aeiric** [robolectric/robolectric#2529]
### Description

When i use Realm in my project,a question appears "NoClassDefFoundError".Is Robolectrics support these third libraray now?And will these be possible ?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
