### ISSUE TITLE
Using getExternalFilesDirs

### ISSUE THREAD

**Issue by lordcodes** [robolectric/robolectric#2531]
### Description

I use `File[] getExternalFilesDirs` in my app, which I do through `ContextCompat`. When the Robolectric tests run it simply throws a `NullPointerException`. Apparently, this is due to the `ShadowContextWrapper` not implementing the `File[] getExternalFilesDirs` (it only has the singular `File getExternalFilesDir` method).
How do I go about using this method in my app, whilst still allowing my tests to run? I understand if it isn't supported in Robolectric yet, just would be nice to still be able to use it without all my tests failing.
### Robolectric & Android Version

Robolectric 3.0
Android SDK 21

**Comment by jongerrish** [comment]
Can you upgrade to Robolectric 3.1.

ShadowContextWrapper has been removed at this point.

Im not sure if getExternalFilesDir has been fully implemented, it needs a
shadow in Environment I think which is what ContextImp delegates through to.

**Comment by cpfeiffer** [comment]
getExternalFilesDir() appears to work, while getExternalFilesDir**s**() does not (tested with 3.1.2).

Environment.getExternalStorageState() however returns "removed", not sure if that is desired.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
