### ISSUE TITLE
Roboelectric and vector drawables

### ISSUE THREAD

**Issue by sentinelweb** [robolectric/robolectric#2535]
I am using some vector drawables in my app but only for v21 and up - they are in the resource folder drawable-anydpi-v21 and also have fallback bitmap versions for the other api levels (drawable-hdpi.mdpi,...).

When I run a robolectric with this config

    `@Config(sdk = 16, application = MyApp.class, constants = BuildConfig.class, packageName = "com.company.app")`

I get the following error on inflate of the views using these drawables

```
    Caused by: android.content.res.Resources$NotFoundException: File ./app/build/intermediates/data-binding-layout-out/dev/debug/drawable-anydpi-v21/ic_info_outline_white_24dp.xml from drawable resource ID #0x7f02010e
    Caused by: org.xmlpull.v1.XmlPullParserException: XML file ./app/build/intermediates/data-binding-layout-out/dev/debug/drawable-anydpi-v21/ic_info_outline_white_24dp.xml line #-1 (sorry, not yet implemented): invalid drawable tag vector
```

the relevant parts of the build.gradle are:

```
android {
          compileSdkVersion 23
          buildToolsVersion "23.0.3"
          defaultConfig {
            applicationId "com.company.app"
            minSdkVersion 16
            targetSdkVersion 23
            versionCode 79
            versionName "0.39"
            // Enabling multidex support.
            multiDexEnabled true
            vectorDrawables.useSupportLibrary = true
            testApplicationId "com.example.app.test"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
          }
          testOptions {
            unitTests.returnDefaultValues = true
          }
       }
       dependencies {
        compile 'com.android.support:support-vector-drawable:23.4.0'
        testCompile "org.robolectric:robolectric:3.1"
        testCompile "org.robolectric:shadows-multidex:3.1"
        testCompile "org.robolectric:shadows-support-v4:3.1"
       }
```

So it looks as though even though i have specified sdk=16 Robolectric seems to take the drawables from drawable-anydpi-v21. 

 1. Is this a bug is roboelectric?  or
    
 1. Is there a better way to specify what the APK level is? or

 1. Is there a way to let roboelectric read the vector tag? or

 1. Some other way of doing it?

**Comment by jongerrish** [comment]
I think you are running into https://github.com/robolectric/robolectric/issues/2520
