### ISSUE TITLE
Unit Test Unable to locate resource in repository

### ISSUE THREAD

**Issue by TonyGravano** [robolectric/robolectric#2537]
Hi,

There are unit tests in my Android Studio project that I've recently taken over, I don't have much knowledge on how the unit tests work but on when the previous person ran the test they worked fine for him. I've provided a text doc with the errors in, it seems to be the data cannot be received from the roboelectric jar file.

[TestError.txt](https://github.com/robolectric/robolectric/files/341214/TestError.txt)

I firstly thought it was something to do with my proxy settings however I have thoruoughly checked these and they work fine. Unfortunately I do not know how to reproducethe issue.

In my build.gradle I current have testCompile('org.robolectric:robolectric:3.0') as my RoboElectric version and im curently using Android Studio 2.1.2. Any information would be helpful as i'm not sure this is a RoboElectric problem but you guys will know alot more than me.

**Comment by jongerrish** [comment]
Honestly not sure what is going on there but it seems to come up fairly often.

We have an outstanding task to remove the code to download these dependencies as this should be done by the build system instead and we should just load them locally:-

https://github.com/robolectric/robolectric/issues/2502

**Comment by TonyGravano** [comment]
Is there nothing I can change in order to resolve this error?

**Comment by jongerrish** [comment]
We use local directories to resolve these dependencies -Drobolectridc.offline=true -Drobolectric.dependency.dir=<path_to_local_dir>
