### ISSUE TITLE
Config manifest is useless in 3.0

### ISSUE THREAD

**Issue by cloudchou** [robolectric/robolectric#2539]
### Description

I try to config manifest and assets directory for my local unit test. but it's useless. it seems that it can not change anyting.
### Steps to Reproduce

``` java
public class ManifestConfigTest {

    @Test
    @Config(manifest = "build/intermediates/manifest/AndroidTest/debug/AndroidManifest.xml")
    public void testManifestConfig() throws PackageManager.NameNotFoundException {
        String packageName = RuntimeEnvironment.application.getPackageName();
        PackageManager packageManager = RuntimeEnvironment.application.getPackageManager();
        PackageInfo packageInfo = packageManager.getPackageInfo(packageName, PackageManager.GET_ACTIVITIES);
        System.out.println(packageInfo.activities);
        System.out.println(packageName);
        System.out.println(packageInfo.versionCode);
        System.out.println(packageInfo.versionName);
    }
}
```

it won't read manifest from build/intermediates/manifest/AndroidTest/debug/AndroidManifest.xml
### Robolectric & Android Version

Roblectric&3.0

**Comment by jongerrish** [comment]
If you're using gradle then you'll want:-
@RunWith(RobolecreicGradleTestRunner.class)
@Config(constants = Config.class)

**Comment by trevjonez** [comment]
The new 2.2.0-alpha5 plugin is handling the manifest differently which breaks robolectric tests, some of which would likely be fixable if this feature worked as documented.

**Comment by jaredsburrows** [comment]
Specifying `manifest` in `3.0`, `3.1`, and `3.1.1` works for me.

**Comment by xian** [comment]
Do we need better docs? Looks like `Config.manifest` is only used in Maven configurations, and `Config.constants` is only used in Gradle configurations?

**Comment by jaredsburrows** [comment]
@xian I have used `manifest` in Gradle tests. Either way Android development with Maven is rare. The main focus should be with Gradle.

**Comment by jaredsburrows** [comment]
@cloudchou @xian I just tested `manifest` with `robolectric.properties` and `@Config` and it doesn't seem to work. It would be nice to remove support for `robolectric.properties` and add support for `manifest` to `@Config` for gradle.

**Comment by navatm** [comment]
Is there a workaround for replacing the manifest in a Gradle unittest?

**Comment by chrisjenx** [comment]
Whats the status on this?

**Comment by xian** [comment]
Looking at it now, sorry for the long wait.

**Comment by xian** [comment]
You can now specify `@Config(manifest = "AlternateManifest.xml")`, which will use a resource file named `AlternateManifest.xml`.

**Comment by IgorGanapolsky** [comment]
@xian Where should this resource file be placed on the relative path?

**Comment by robross0606** [comment]
Seriously, the documentation is REALLY lacking here.  We keep seeing things like "some/random/path/to/manifest.xml" which is not at all helpful.  How about an actual example that makes sense since Android Studio uses Gradle which is all based on configuration by convention anyway.  How do you *actually* reference a manifest file in a typical Android Studio project?

**Comment by robross0606** [comment]
AH, I see it now.  I was missing the extra setting in `includeAndroidResources` setting in my gradle file.

**Comment by IgorGanapolsky** [comment]
@jongerrish Are there any Google samples with Robolecric, since google is supporting it?  At I/O 18 there was zero mention of Robolectric...

**Comment by trevjonez** [comment]
> At I/O 18 there was zero mention of Robolectric...

not quite true: https://youtu.be/wYMIadv9iF8

**Comment by jongerrish** [comment]
There are none yet, but there will be, the delay is that along with the
Jetpack repackaging and the alignment of Robolectric supporting the unified
(on+off device) API, internally we still have a bit of grunge work to do.
We hoping to have the all complete along with samples this summer
culminating in a final release of Robolectric 4.0 and androidx.test.*
simultaneously.

In the meantime, the best working examples are in our integration tests
module:

https://github.com/robolectric/robolectric/tree/master/integration_tests/androidx_test

**Comment by IgorGanapolsky** [comment]
@jongerrish Thank you, looking forward to it, especially that Robolectric runs much faster than Espresso!  Also, given that I work on middleware portion of my company's app, I don't want to write UI tests.

**Comment by jongerrish** [comment]
Yeah, Robolectric is the way to do fast unit tests for sure. Binary
resource support saves around 2 seconds on the average single test run in
the interactive use case, so is even faster... Good news for TDD 😃

It's actually funny that Espresso has always been a synonym for real device
or emulator based tests, but with Robolectric 4.0 we're bringing initial
support for Espresso off device too.... Yes... Espresso now becomes simply
a set of APIs for view matching and view actions.

Over all our plan is a two pronged initiative: Improve Robolectric fidelity
+ Improve emulator speed.
