### ISSUE TITLE
getAttributeValue(null, "style") on an AttributeSet returns wrong value

### ISSUE THREAD

**Issue by unparalleled** [robolectric/robolectric#2548]
### Description

It looks like robolectric treats the style attribute as a resource.

`getAttributeValue()` on AttributeSet then calls `getAttributeValue()` on ResourceParser which constructs a new Attribute object and calls `qualifiedValue()`

```
  public String qualifiedValue() {
    if (isResourceReference()) return "@" + getResourceReference().getFullyQualifiedName();
    if (isStyleReference()) return "?" + getStyleReference().getFullyQualifiedName();
    else return value;
  }

  public boolean isResourceReference() {
    return value.startsWith("@") && !isNull();
  }
```

At this point, value starts with `@style/...` so `isResourceReference()` returns true and the periods in the style name are replaced with underscores as well as prepending the package name.
### Steps to Reproduce

In the constructor of a custom view:

```
public CustomView(Context context, AttributeSet attrs, int defStyleAttr) {
  String styleString = attrs.getAttributeValue(null, "style");
}
```

Expected:@style/Component.Button.A
Actual: @com.example:style/Component_Button_A
### Robolectric & Android Version

ANDROID_BUILD_SDK_VERSION=23
testCompile "org.robolectric:robolectric:3.0"
testCompile "org.robolectric:shadows-multidex:3.0"

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
