### ISSUE TITLE
Testing dynamically created textviews - 

### ISSUE THREAD

**Issue by nishashirawala** [robolectric/robolectric#2550]
### Description
I created a separate adapter class and within that, I created textview dynamically
TextView textView1 = new TextView(this.getContext());

I would like to unit test this adapter class, and mock this textview. How can I do this?

### Robolectric & Android Version
Robolectric version - 3.0
Android version 
        - minSdkVersion 21
        - targetSdkVersion 23
        - compileSdkVersion 23
        - buildToolsVersion "23.0.3"

**Comment by jongerrish** [comment]
Don't mock text view. In general don't mock Android classes, its bad practice.

If you want to test how your adapter interacts with the dymanically created text view, give the text view an ID, then in your test, get the text view by ID and assert behaviour on it. e.g: that its text has some value.

**Comment by nishashirawala** [comment]
I already tried that. Not sure what I am doing is wrong.
I gave ID to the textview in the adapter, and in the adapter unit test I have following..

mainActivity = Robolectric.setupActivity(MainActivity.class);
 TextView restaurantName = (TextView) mockMainActivity.findViewById(R.id.restaurant_name);

But this restaurantName stays null

**Comment by jongerrish** [comment]
Are you adding the view to the activity? You need to call Activity.setContentView() at some point, probably in Activity.resume().

I'd suggest stepping through with a debugger, you can check out the view hierarchy that way and verify that your view is attached.
