### ISSUE TITLE
Intent.equals(Intent) no longer works in Robolectric 3.1

### ISSUE THREAD

**Issue by MiguelLavigne** [robolectric/robolectric#2553]
### Description
As of 3.1 the ShadowIntent class was stripped of all of its implementation including its own implementation of `equals`.  Being that the `Intent` class doesn't implement its own version we no longer can use `Intent.equals(Intent)` during tests.

I know Robolectric is trying to step away from shadows so I'm wondering what would be the best alternative to getting this working again with the new code?  I know we can extract our own equals if we want but I'm curious of more integrated solutions.

### Steps to Reproduce
```
@RunWith(RobolectricGradleTestRunner.class)
@Config(
        sdk = 16,
        constants = BuildConfig.class,
        packageName = BuildConfig.APPLICATION_ID
)
public class ExampleUnitTest {
    @Test
    public void testIntent() throws Exception {
        Intent a = new Intent(Robolectric.setupActivity(Activity.class), MainActivity.class);
        Intent b = new Intent(Robolectric.setupActivity(Activity.class), MainActivity.class);
        assertThat(a, is(b));
    }
}
```

Test output
```
Expected: is <Intent { cmp=io.sweers.vectordrawablesadness/.MainActivity }>
     but: was <Intent { cmp=io.sweers.vectordrawablesadness/.MainActivity }>
```
### Robolectric & Android Version
Robolectric 3.1

**Comment by jongerrish** [comment]
I recommend using Squares assertj for android, we'll probably introduce it into Robolectric's tests at some point.

https://github.com/square/assertj-android/blob/master/assertj-android/src/main/java/org/assertj/android/api/content/IntentAssert.java

**Comment by MiguelLavigne** [comment]
That's great, didn't think of that one.  Thank you!
