### ISSUE TITLE
shadow-multi-dex and other shadows are depending on Android aars

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#2556]
### Description
Some of the shadow libraries are using `compile` to depend on Android libraries. As a result, when I try to test using 3.1.1, I get the following error during compile:
```
Module 'org.robolectric:shadows-play-services:3.1.1' depends on one or more Android Libraries but is a jar
Module 'org.robolectric:shadows-multidex:3.1.1' depends on one or more Android Libraries but is a jar
```
### Steps to Reproduce
Create any Android Gradle project, and depend on shadow-multi-dex:
```
testCompile "org.robolectric:shadows-multidex:3.1"
```
Set your compiler args to _treat warnings as errors_.
### Robolectric & Android Version
Robolectric 3.1
Android version: n/a

**Comment by xian** [comment]
Thanks for the fix @menny!

**Comment by RomanMinenok** [comment]
Guys, any possibility to push this into next next release (e.g. `3.1.2`) ASAP? For now looks like I need to copy paste `ShadowMultiDex` to avoid relying on snapshot version.

**Comment by jongerrish** [comment]
Ya, we'll push a release this week. Tomorrow probably.

**Comment by tomerorian** [comment]
any update on this?

**Comment by RomanMinenok** [comment]
+1, please make the release if possible
