### ISSUE TITLE
The latest Robolectric version

### ISSUE THREAD

**Issue by NeilConcur** [robolectric/robolectric#2572]
Hi,

What is the latest Robolectric version? The readme file says 3.1 but I know there is 3.1.1.
Please advise.

**Comment by jongerrish** [comment]
3.1.1 is a minor increment on 3.1 and thus the latest version.

README.md is just an example of how to integrate Robolectric into your project, not necessarily the canonical source of truth of what the latest version is.

Are you thoughts that we should keep README.md up to date with the latest version, or change the text at all? Feel free to submit a PR with any text changes to make this more clear.
