### ISSUE TITLE
Continued OutOfMemory / Performance Issues in 3.1.1

### ISSUE THREAD

**Issue by nickcapurso** [robolectric/robolectric#2584]
We have a fairly large unit test suite of ~1600 tests. Robolectric 3.0 had worked fine, but we upgraded to 3.1 for Marshmallow support. After experiencing significant performance issues we upgraded to [3.1.1](https://github.com/robolectric/robolectric/issues/2522).

Although it seems like tests might execute faster in 3.1.1, our machines quickly run out of memory and tests slow to a crawl. We have also tried the `forkEvery` gradle option and increasing Android Studio's memory/heap size with no success.

---

Here's a screenshot of `jvisualvm` monitoring our tests under 3.1.1 - you can see the memory just hits an upper bound after a few minutes and GC is constantly running:

<img width="1436" alt="screen shot 2016-07-27 at 11 48 39 am" src="https://cloud.githubusercontent.com/assets/5898509/17215965/c6865c7c-54ac-11e6-95de-dd9325307d3c.png">

The `Perform GC` button has no effect, leading me to believe references are getting leaked and can't be garbage collected?

---

For comparison, here is what the graphs looked like for our tests under 3.0,
<img width="1435" alt="screen shot 2016-07-27 at 2 02 49 pm" src="https://cloud.githubusercontent.com/assets/5898509/17216047/084df034-54ad-11e6-8499-47a9d5d68173.png">
Memory usage rises and falls expectantly.

---

We have not yet tried 3.2, but have the root cause of the memory leaks been identified? If so, where can a snapshot version be found (or do we need to build ourselves)?

**Comment by NeilConcur** [comment]
I also have the same problem and adding tearDown() to every test suite seems to ease the pain a little bit; however, it is still a major problem. Any input is appreciated.

**Comment by kingargyle** [comment]
Some general tips where I ran into performance issues in the past.

1. Have a tearDown method, that finishes any activities that you created.
2. If you are using or testing Fragments, then you want to make sure you remove them in an @After statement or tearDown method.  Something like the following:

```
  @After public void destroyFragment() {
    if (fragment != null) {
      FragmentManager manager = activity.getSupportFragmentManager();
      manager.beginTransaction().remove(fragment).commit();
      activity.finish();
      fragment = null;
      activity = null;
    }
  }
```

This will help make sure those items are GC and removed after a test is done.  If you don't finish the activities and remove transactions they hang around.

**Comment by NeilConcur** [comment]
@kingargyle Thank you for the pointers and I have them already. I guess my biggest question is why the test cases ran fine with 3.0.0 and created memory issues after 3.0.0?

**Comment by dhaag23** [comment]
I'm running the 3.2-SNAPSHOT and am experiencing the OOM as well on a fairly large suite (~4000 tests) and it did not happen on 3.0.

**Comment by NickCapurso** [comment]
@dhaag23 Good to know, we hadn't tried 3.2 snapshot out yet, but it looks like the issues haven't been fixed.

@kingargyle Thanks for your suggestion. However, we actually already have tearDowns for activity/fragment cleanups due to previous memory issues we've had in the past. In this case, we're hitting OOM issues even before 20% of our tests have even ran.

**Comment by KevinLeighCrain** [comment]
@NickCapurso I have run into the same issue using Robolectric `3.1.1`. A work around is I increased the max heap size for test options attribute inside `app/build.gradle` file:

```
android {
    ...
    testOptions {
        unitTests {
            all {
                include '**/*Test.class'
                // configure max heap size of the test JVM
                maxHeapSize = "4096m"
            }
        }
    }
}
```

`4096m` max heap size may be large for some `32/64 bit` operating systems, so I wouldn't recommend this as a final solution.

**Comment by NeilConcur** [comment]
@NickCapurso Does jvisualvm tell you which objects get created or which objects are not getting garbage collected?

**Comment by NickCapurso** [comment]
@NeilConcur We did try using the Heap Dump functionality to compare our tests running on 3.1.1 vs 3.0, but there wasn't anything that stuck out (though you can imagine the amount of objects that might be on the heap at any given point in time). 

That said, Heap Dump seems to only output the objects in memory at that particular point in time, which is pretty limited.

**Comment by NeilConcur** [comment]
Anybody has a solution or comment?

**Comment by jongerrish** [comment]
Usually with a profiling tool you can inspect the heap and have an idea of
what objects are leaking.

It could be a Robolectric bug or it could be state from your own
application.

**Comment by jaredsburrows** [comment]
@NickCapurso Can you try applying https://github.com/robolectric/robolectric/issues/2068#issue-109132096?

**Comment by hoisie** [comment]
While upgrading to 3.1 I ran into an issue where resource caching was broken and caused performance degradation (See #2623 for details). I'm not sure if other people have been running into this issue as well.

The most common way this can happen if you subclass `RobolectricTestRunner`, override `getAppManifest`, and use the three-argument constructor of AndroidManifest. The fix is to use the four-argument constructor of AndroidManifest.

**Comment by mohitagrawal** [comment]
+1
Still seeing this in 3.3 version.

**Comment by KenVanHoeylandt** [comment]
I have the same issue on a project with thousands of tests and version 3.3
When attaching VisualVM and looking at the diff of 2 snapshots, there is an enormous growth of `int[]` instances growing over 0.6 GB very quickly.

**Comment by miketrewartha** [comment]
We've been chasing memory issues in our Robolectric suite as well, with the intent of getting memory usage low enough to run on CircleCI. We're also using RoboGuice for dependency injection right now (switching to Dagger 2 soon). Anyways, it's pretty obvious from a heap dump that the two libraries contribute significantly to our memory issues during tests. 

![screen shot 2017-07-14 at 9 50 48 am](https://user-images.githubusercontent.com/4084686/28219662-fcea2d20-6879-11e7-8a23-f44447e6ffde.png)

I've been poking around and found `RoboGuice.Util.reset()`. After tossing that into the clean-up for our tests, our memory usage dropped quite a bit! So FYI, if you're using RoboGuice in addition to Robolectric, give that a shot.

Here are our results. Note that I've capped the heap to ~3.2GB for both of these runs.

**Before** using `RoboGuice.Util.reset()`, the heap would grow to the max about 2/3 of the way into our suite, then the JVM would start GCing like crazy.

![screen shot 2017-07-14 at 9 55 18 am](https://user-images.githubusercontent.com/4084686/28219883-cb35f6f0-687a-11e7-904b-391a162bf42c.png)

**After using `RoboGuice.Util.reset()`, the heap is a good size smaller and never hits our ~3.2GB max. As a bonus, there isn't any crazy GC going for the last 1/3 of the suite, which brings the runtime from 12 mins down to 6 mins!

![screen shot 2017-07-14 at 9 55 30 am](https://user-images.githubusercontent.com/4084686/28220137-9710e1a4-687b-11e7-85d8-941430eadb05.png)

**Comment by miketrewartha** [comment]
We've made some more significant progress on this. We're now able to run our whole test suite with only 1GB of heap space. We're pretty stoked about this, considering it used to take 8GB!

![screen shot 2017-07-17 at 5 51 48 pm](https://user-images.githubusercontent.com/4084686/28320810-cc77ff92-6b8e-11e7-9877-9b8e3159b5b3.png)

After we trimmed down our memory usage as described above, we went after the next biggest thing: `class org.robolectric.shadows.ShadowCursorWindow`. In our case, it was consuming ~550MB by the end of the test suite. It holds onto a `WindowData`, which is backed internally by a `ConcurrentHashMap<Number, Data>`. That map seems to be holding `Cursor` data and we've got a lot of `ContentProvider`s in our app, so we made sure any `Cursor`s in our test suite were closed appropriately. That helped some, but not too much. Then we found PR #800, which talked some about this. We decided to replace `ShadowCursorWindow` with a version that can clear the map. We then called the `clear()` method in our test runner's `afterTest(Method method)` method and our memory usage dropped very significantly.

With max heap size capped at 2GB, here are the before/after results:

**BEFORE:**
![screen shot 2017-07-18 at 8 10 19 am](https://user-images.githubusercontent.com/4084686/28321548-bd47c8c0-6b90-11e7-9533-33b21d1e6828.png)

**AFTER:**
![screen shot 2017-07-18 at 7 56 34 am](https://user-images.githubusercontent.com/4084686/28321564-c7b7fed8-6b90-11e7-9445-6ae34fee6b54.png)

We don't have time to look into this anymore and/or issue a PR to fix it, but we wanted to bring it to your attention in case you guys get the opportunity. If we get some time later, we'll loop back and create a PR.

**Comment by qsjh898** [comment]
@jaredsburrows I have already applied your solution  #2068 (comment) , but still getting OOM while running my total 260 tests. Besides, I use Robolectric 3.2.2.

**Comment by xian** [comment]
Thanks much for the detailed info here! Robolectric 4.0 has very a different memory use profile. If you're still seeing problems after upgrading, please open a new issue.

**Comment by calvarez-ov** [comment]
Opened #6872 as this is still an issue.
