### ISSUE TITLE
Custom shadow implementing private method

### ISSUE THREAD

**Issue by saantiaguilera** [robolectric/robolectric#2586]
### Description

Creating a custom shadow and implementing a private method will never get the shadow called

Case

``` Java
@Implements(SomeClassOfMyProject.class)
public class ShadowSomeClassOfMyProject {

    //Other methods...

    @Implementation
    @SuppressWarnings("unused")
    private void googleApiClientConnect(final GoogleApiClient.ConnectionCallbacks connectionCallback) {
        connectionCallback.onConnected(new Bundle());
    }

}
```

Where SomeClassOfMyProject has the same signature for the method (being private).
Im using a CustomRobolectricRunner which is implemented like this:

``` Java
public class CustomRobolectricTestRunner extends RobolectricGradleTestRunner {

    public CustomRobolectricTestRunner(Class<?> klass) throws InitializationError {
        super(klass);
    }

    @Override
    protected ShadowMap createShadowMap() {
        return super.createShadowMap()
                .newBuilder()
                .addShadowClass(ShadowSomeClassOfMyProject.class)
                .build();
    }

    @Override
    public InstrumentationConfiguration createClassLoaderConfig() {
        return InstrumentationConfiguration.newBuilder()
                .addInstrumentedClass(SomeClassOfMyProject.class.getName())
                .build();
    }

}
```

Finally, im adding this CustomRobolectricTestRunner to a test suite by

``` Java
@RunWith(CustomRobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.JELLY_BEAN_MR2, shadow = the shadow..., stuff...)
public abstract class AbstractRobolectricTest {
```
### Robolectric & Android Version

3.0 , All.

**Comment by jongerrish** [comment]
Avoid shadowing your own code and avoid creating custom test runners is my advice.

Why can't you use a mocking library like Mockito?

**Comment by saantiaguilera** [comment]
Well, i cant remember now, but I think because (since its a project already far developed) I couldnt mock the stuff (Eg MyApplication does a lot of stuff being one of them that one. I could've created a MyApplicationTest and use that one which does all the same except that particular thing, but that removed me a feature from another tests.). Of course if I can use mockito I will use it, but I remember well this wasnt a case.

Anyways, I solved the problem with another solution, so there was no need for this :)

**Comment by jongerrish** [comment]
Robolectric requires all shadow methods to be public which is why this
doesn't work. I heard the reason was for performance but not sure if that
is a valid concern or not. I think running the robolectric annotation
processor on your shadows would have flagged this issue, but I think a lot
of people don't do this, so it is an opaque failure. We'll have a think
about how we can make this better.

**Comment by jongerrish** [comment]
I created the following tracker story for this:
https://www.pivotaltracker.com/story/show/134374649
