### ISSUE TITLE
3.1.2 release not tagged

### ISSUE THREAD

**Issue by seadowg** [robolectric/robolectric#2588]
There's a missing/not pushed tag (as far as I can see) for the 3.1.2 release available on Maven Central. @xian and @jongerrish would you be able to add one?

**Comment by kingargyle** [comment]
A Change log would be nice to have as well.  Even if it is just a Changelog.md file that is updated periodically with the major fixes.

**Comment by jongerrish** [comment]
Done, thanks!

A changelog is a great idea, we'll see about that for the next release, if
you have some spare time a script to generate one would be most welcome :-)

**Comment by kingargyle** [comment]
@jongerrish there appears to be a project that allows for this already.  I haven't run it but it might be useful.

https://github.com/skywinder/github-changelog-generator

**Comment by hidroh** [comment]
+1 for change log, currently it's at robolectric.blogspot.com, e.g. [3.1.3 change log](http://robolectric.blogspot.com/2016/10/robolectric-313-is-released.html), which unfortunately is not linked from this repository or the main website robolectric.org.

Alternatively, they can be put as tag message, or in wiki, at least watchers get notified with changes.
