### ISSUE TITLE
Support API level 24

### ISSUE THREAD

**Issue by pbismobica** [robolectric/robolectric#2594]
Would you be able to provide ETA, when Robolectric will support API level 24? 

Kind regards,
Przemek

**Comment by mvdan** [comment]
Have you seen #2554?

**Comment by pbismobica** [comment]
Yes, I did. It doesn't answer my question though.

**Comment by mvdan** [comment]
The first rule of open source is not to ask for ETAs :)

**Comment by jaredsburrows** [comment]
Duplicate of https://github.com/robolectric/robolectric/issues/2554.

**Comment by xian** [comment]
Robolectric 3.2 supports API 24.
