### ISSUE TITLE
removeSessionCookies(ValueCallBack) in RoboCookieManager not implemented

### ISSUE THREAD

**Issue by sebdomdev** [robolectric/robolectric#2598]
### Description

RoboCookieManager extends the abstract class CookieManager and overrides its removeAllCookies method. However the implementation of the method is empty. Therefore, code that uses that method causes unintended behavior and cannot be tested with robolectric (because Cookeis are not being removed).
### Steps to Reproduce

CookieManager cookieManager = CookieManager.getInstance();
cookieManager.setCookie("test", "testValue");
cookieManager.removeAllCookies(null);
assertThat(cookieManager.getCookie("test")).isNull();

//This assertion fails because the "test" cookie doesn't get deleted.
### Robolectric & Android Version

Robolectric version 3.1.1
Android SDK 23

**Comment by mrtowel** [comment]
You can create CustomRoboCookieManager where you override #removeAllCookies and then create CustomShadowCookieManager. CustomShadowCookieManager.getInstance could return CustomRoboCookieManager instance.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
