### ISSUE TITLE
Error inflating class android.support.v7.widget.ActionBarOverlayLayout

### ISSUE THREAD

**Issue by dhiren-mudgil-olx** [robolectric/robolectric#2602]

**Comment by jaredsburrows** [comment]
How are you reproducing this? Can you show us code?

**Comment by niltonvasques** [comment]
@jaredsburrows I got same error here.

You can see the problematic code at this commit https://github.com/niltonvasques/flux-android-sample/commit/0276a597e6245f8f8db5d3304f538ee5b4e79f94

**Comment by jaredsburrows** [comment]
@niltonvasques This doesn't say much. All my github projects use robolectric and api 24. For example, https://github.com/jaredsburrows/android-gif-example.

**Comment by jongerrish** [comment]
Likely fixed with Robolectric 4.0 + binary resource support.

Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
