### ISSUE TITLE
ShadowLocationManager should not allow duplicate listeners

### ISSUE THREAD

**Issue by ecgreb** [robolectric/robolectric#2603]
### Description

`ShadowLocationManager` should not allow the same `LocationListener` to be registered more than once.
### Steps to Reproduce

Register the same location listener multiple times via `LocationManager`. Then call `ShadowLocationManager#simulateLocation(Location)`. Notice that the location listener is invoked once for each time it was registered.

This is not the behavior of the Android framework. No matter how many times the same listener is registered the callback is invoked only once. See sample test below.
### Robolectric & Android Version

Robolectric 3.1.2
Android 23
#### Test

``` java
    @Test public void shadowLocationManager_shouldNotRegisterDuplicateListeners() {
        LocationManager lm = (LocationManager) application.getSystemService(LOCATION_SERVICE);
        TestListener listener = new TestListener();
        lm.requestLocationUpdates(GPS_PROVIDER, 0, 0, listener);
        lm.requestLocationUpdates(GPS_PROVIDER, 0, 0, listener);
        shadowOf(lm).simulateLocation(new Location(GPS_PROVIDER));
        assertThat(listener.locationCount).isEqualTo(1);
    }

    public class TestListener implements android.location.LocationListener {
        private int locationCount = 0;

        @Override public void onLocationChanged(Location location) {
            locationCount++;
        }

        @Override public void onStatusChanged(String provider, int status, Bundle extras) {}

        @Override public void onProviderEnabled(String provider) {}

        @Override public void onProviderDisabled(String provider) {}
    }
```
#### Output

```
org.junit.ComparisonFailure: 
Expected :1
Actual   :2
```

**Comment by ecgreb** [comment]
This should be an easy fix and I would be happy to implement but I am currently unable to run robolectric tests locally due to #2379 "Shadows not a subtype" error.

**Comment by jongerrish** [comment]
What is the root cause? Look at the first error in the logs, this error is
a consequence of the Robolectric runtime not setting up correctly and blows
up all subsequent tests, but the first error is the key one.

**Comment by ecgreb** [comment]
Ok here is the first error in the output. Looks like its coming from [`ShadowDisplayManagerGlobal`](https://github.com/robolectric/robolectric/blob/78ef7facd8df6c2c2f8dafedfbc2d1af19f3558e/robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowDisplayManagerGlobal.java.vm) but I'm still not quite sure how to fix.

I have not attempted to build the project since multi-API shadows and velocity templates were introduced some time ago so its possible I'm missing something obvious.

```
org.robolectric.MultiApiRobolectricTestRunnerUriTest > startsWith[17] FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: supportedModes

        Caused by:
        java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: supportedModes

            Caused by:
            java.lang.RuntimeException: java.lang.NoSuchFieldException: supportedModes

                Caused by:
                java.lang.NoSuchFieldException: supportedModes
```

**Comment by jongerrish** [comment]
Looks like you are accessing a method / field that doesn't exist on an
older version of the Android runtime. This is why the velocity templates
exist, you'll need to check what runtime version the field was introduced
and add #if greater than API version checks around it.

**Comment by ecgreb** [comment]
Ok that makes sense. But right now I'm just trying to build `master` and I have yet to make any local edits.

It appears the [proper checks are in place](https://github.com/robolectric/robolectric/blob/78ef7facd8df6c2c2f8dafedfbc2d1af19f3558e/robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowDisplayManagerGlobal.java.vm#L31-L33) but for some reason `$api` is not getting properly set?

```
#if ($api >= 23)
ReflectionHelpers.setField(result, "supportedModes", new Display.Mode[] { new Display.Mode(0, 0, 0, 0.0f) });
#end
```

If I checkout the tag `robolectric-3.1` and build using Maven I do not run into the same issue so perhaps it is something about the Gradle environment?

**Comment by jongerrish** [comment]
How are you building the project?

**Comment by ecgreb** [comment]
I've got it working now 🎉

I believe the problem was failing to run `gradle install` prior to `gradle test`. Running the commands verbatim as they appear in `.travis.yml` appears to have done the trick.

The "Building and Contributing" section of the README should probably be updated specify that `install` must be run prior to `test` and also that the script `install-robolectric.sh` no longer exists.

Thanks for your help and I'll get started on the fixing the issue in `ShadowLocationManager`.
