### ISSUE TITLE
android:nextFocusDown not supported by robolectric, throws exception, (sorry, not yet implemented): Error inflating class <unknown>

### ISSUE THREAD

**Issue by Aleksandarf** [robolectric/robolectric#2605]
### Description

following exception is thrown,

android.view.InflateException: XML file build\intermediates\res\merged\standard\debug\layout\transfer_select.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
### Steps to Reproduce

Use android:nextFocusDowm in xml.
### Robolectric & Android Version

Robo 3.0 and 3.1
### workaround

do the same thing programmaticaly, that is view.setNextFocusDownId(...)

**Comment by jongerrish** [comment]
Should be fixed with Robolectric 4.0 and binary resources. Please reopen if its still an issue with binary resources enabled.
