### ISSUE TITLE
Except and actual are the same,but the test result is failed

### ISSUE THREAD

**Issue by xiachunle** [robolectric/robolectric#2606]
### Description

Except and actual are the same,but the test result is failed
### Steps to Reproduce

1.create MainActivity
2.create SecondActivity
3.MainActivity--->SecondActivity (By Button)
<img width="713" alt="2016-08-15 9 15 58" src="https://cloud.githubusercontent.com/assets/11811777/17665428/8682435e-632d-11e6-901e-4515d9b8331e.png">
### Robolectric & Android Version

Robolectrie Vesion 3.1.2
Android Studio Version 2.0

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
