### ISSUE TITLE
android.view.InflateException: XML file ... line #-1 (sorry, not yet implemented): : Error inflating class com.caverock.androidsvg.SVGImageView

### ISSUE THREAD

**Issue by varris** [robolectric/robolectric#2609]
I am using kind of old library SVGImageView for a while and have layout like 

> ```
>         <com.caverock.androidsvg.SVGImageView
>             android:id="@+id/undo_button"
>             android:layout_width="30dp"
>             android:layout_height="30dp"
>             android:layout_gravity="center"
>             android:layout_margin="8dp"
>             android:visibility="invisible"
>             svgimageview:svg="@raw/ic_undo"/>
> ```

as you see I have "@raw/ic_undo" and because of that I have an error

Caused by: java.lang.RuntimeException: huh? ResName{com.imvu:raw/ic_undo}
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:101)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)

Looking at Converter.java I see convertAndFill doesn't accept ref type "raw".
Why do you have such limitation?
What is work around?
I cannot use robolectric for UI testing because of that strange limitation.

I am using robolectric 3.0 and Android 6.0.1

**Comment by varris** [comment]
no work around ?

**Comment by jaredsburrows** [comment]
Any reason you arent using `AppCompatImageView` or `ImageView`?

**Comment by varris** [comment]
It takes SVG files.

**Comment by jaredsburrows** [comment]
So does `AppCompatImageView` and `ImageView`.

**Comment by varris** [comment]
They take VectorDrawable which is not exactly SVG.
I have a plan to use VectorDrawable, but currently, I stuck with SVG and SVGImageView

**Comment by jongerrish** [comment]
I suspect this has been fixed with Robolectric 4.0 and binary resources.

Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by asadaltaf583** [comment]
Can we use this SVG with StickerView in android
