### ISSUE TITLE
java.util.Locale.toLanguageTag() shouldn't exist before Lollipop

### ISSUE THREAD

**Issue by jfarfel** [robolectric/robolectric#2614]
### Description

A test using java.util.Locale.toLanguageTag() passes even with @Config(sdk = {VERSION_CODES.JELLY_BEAN}).

But java.util.Locale.toLanguageTag was added in API level 21 (Lollipop): https://developer.android.com/reference/java/util/Locale.html#toLanguageTag()
### Steps to Reproduce

This test passes, but should fail:

```
@Test
@Config(sdk = {VERSION_CODES.JELLY_BEAN})
public void thisShouldFail() {
    Locale.getDefault().toLanguageTag();
}
```
### Robolectric & Android Version

Robolectric 3.1

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
