### ISSUE TITLE
ShadowAlarmManager replaces existing Alarm when PendingIntent id's differ

### ISSUE THREAD

**Issue by DanDevine** [robolectric/robolectric#2616]
### Description

When submitting multiple alarms to the AlarmManager which have the same Intent (i.e. passes Intent Filter test), and which have PendingIntents with differing IDs, the ShadowAlarmManager replaces the existing alarm instead of adding a second matching alarm.
### Steps to Reproduce

```
Intent toLaunch = new Intent("com.foo.bar.AlarmReceiver.NOTIFICATION_EVENT");
PendingIntent pendingIntent = PendingIntent.getBroadcast(this, 1, toLaunch, PendingIntent.FLAG_ONE_SHOT);
alarmManager.setExact(AlarmManager.RTC_WAKEUP, alarmTime, pendingIntent);

toLaunch = new Intent("com.foo.bar.AlarmReceiver.NOTIFICATION_EVENT");
pendingIntent = PendingIntent.getBroadcast(this, 2, toLaunch, PendingIntent.FLAG_ONE_SHOT);
alarmManager.setExact(AlarmManager.RTC_WAKEUP, alarmTime + 5000, pendingIntent);
```
### Robolectric & Android Version

Tested against SDK 19 and Robolectric 3.0Assuming that the times are not identical, there should be 2 separate Alarm events in the queue due to the differing PendingIntent id's.   Please don't assume everyone just sets the Id field to 0.

I found this bug report, because my test isn't matching the real 'on-device' behavior.  When I set two distinct alarms on the device using the above code, I get two distinct events.  When checking the scheduled alarms with 3.0, I get only one....
### Suggested Fix

Not seeing immediately where the PendingIntent requestCode is stored, however this is conceptually what I think is the correct behavior.

```
private void internalSet(int type, long triggerAtTime, long interval, PendingIntent operation) {
    Intent intent = Shadows.shadowOf(operation).getSavedIntent();
    for (ScheduledAlarm scheduledAlarm : scheduledAlarms) {
        Intent scheduledIntent = Shadows.shadowOf(scheduledAlarm.operation).getSavedIntent();
        if (scheduledIntent.filterEquals(intent) && scheduledAlarm.operation.requestCode == operation.requestCode) {
            scheduledAlarms.remove(scheduledAlarm);
            break;
      }
    }
    scheduledAlarms.add(new ScheduledAlarm(type, triggerAtTime, interval, operation));
  }
```

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
