### ISSUE TITLE
Resource caching may be broken due to instability of AndroidManifest#hashCode

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#2623]
### Description

In certain situations, resource caching may be broken due to the instability of the
`AndroidManifest#hashCode` method. The `hashCode` method is dependent on the
package name of the app. If a custom RobolectricTestRunner class is used, it's possible
to construct an `AndroidManifest` object with the package name initially null. After the
manifest file is parsed, the package name gets set, and `hashCode` will return a different
value. Because the resource cache is partly keyed on the `AndroidManifest`, this could
cause resources to be reloaded before each test run.

### Steps to Reproduce

Clone https://github.com/hoisie/robolectric-caching-problem-demo
Run `./gradlew testDebug`
All XML resources are reloaded before each test run

### Robolectric & Android Version

Robolectric 3.1+
Any Android version

**Comment by hoisie** [comment]
There are two other ways I can think of to solve this. The first way is to remove the three-argument constructor of AndroidManifest and require the package name upfront in the constructor. The other way would be to remove the package name from the hash code calculation. I'm not sure about the implications of these, though.

**Comment by cesar1000** [comment]
I ran into this same issue and addressed by parsing the manifest immediately. Thanks for tracking this down! In my opinion, it makes sense that the constructor parses the manifest immediately when the package name is missing, since the class is only partially initialized otherwise.

**Comment by xian** [comment]
We got some appreciable perf wins from lazily parsing manifests, at least in the past. May not be hugely consequential, but I'm gonna change it to use stable keys instead of eagerly parsing.
