### ISSUE TITLE
Error converting bytecode to dex

### ISSUE THREAD

**Issue by ashik94vc** [robolectric/robolectric#2626]
### Description

```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
```

I think its most probably caused by thoughtworks xstream library which uses JDK 8
### Version

Robolectric : 3.1.1

Android: API 24

**Comment by jaredsburrows** [comment]
How are you reproducing this? Are you applying the robolectric dependency to this "java" module?

**Comment by drawers** [comment]
You will also get this error message if you mistakenly put `androidTestCompile "org.robolectric:robolectric:$roboelectricVersion"` instead of `testCompile`. See http://stackoverflow.com/q/43125268

**Comment by ashik94vc** [comment]
I fixed this issue by using different version of stream library.
