### ISSUE TITLE
ContextImpl.getExternalCacheDirs seems broken

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#2642]
### Description

When calling `context.getExternalCacheDirs()` (available since API level 19), the call will crash with some exception.
In API 19: java.lang.NullPointerException
In API 20: Not supported by Robolectric, so that's fine.
In API 21:java.lang.NullPointerException
In API 22: WORKS!
In API 23: java.lang.NoClassDefFoundError (but that's because of `javax/microedition/khronos/opengles/GL`).
### Steps to Reproduce

clone https://github.com/menny/deckard/tree/mount-service
and run `./gradlew testDebugUnitTest`
### Robolectric & Android Version

Latest `master` robolectric.

**Comment by simoarpe** [comment]
Any updates on this?

**Comment by jongerrish** [comment]
Any chance you can get a PR together for this? We're pushing a release our
in next couple of days so that's the only way we could squeeze that in.

**Comment by simoarpe** [comment]
Thank you for your quick response. 
I'm on a tight schedule these days, but if I find some time I'll be glad to make a PR.

**Comment by hoisie** [comment]
Seems like this was fixed in https://github.com/robolectric/robolectric/pull/5288
