### ISSUE TITLE
Robolectric's dependency on protobuf-java-2.6.1.jar may cause compile issues

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#2643]
### Description

We had some tests that constructed protobuf objects fail because Robolectric includes protobuf-java-2.6.1.jar as a transitive dependency. Our protobufs are generated with protobuf nano. The multiple versions of protobuf in our classpath caused compile failures. The compilation errors were fairly obscure -- that the `build()` method was undefined.

Robolectric depends on robolectric-utils which depends on com.google.android.apps.common.testing.accessibility.framework which depends on protobuf-java-2.6.1.
### Steps to Reproduce

Run ./gradlew build -d and notice for protobuf-java-2.6.1.jar. 
### Robolectric & Android Version

3.1+

**Comment by mssdev** [comment]
i have the same problem it shows up in  my console as this 
Conflict with dependency 'com.google.protobuf:protobuf-java'. Resolved versions for app (2.5.0) and test app (2.6.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

and i kept commenting out things until i realized it was robolectric 3.1 and 
testCompile 'org.robolectric:shadows-multidex:3.1'
I tried to exclude things but could not come up with a solution
Did you figure anything out?

**Comment by hoisie** [comment]
You might be able to use:

```gradle
testCompile('org.robolectric:shadows-multidex:3.1') {
    exclude group: 'com.google.protobuf'
}
```

**Comment by wuziq** [comment]
Had the exact same issue.  I'm using protobuf-lite-3.0.0, and was getting the build() symbol not being found.  Excluding com.google.protobuf from robolectric helped.  Thanks.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
