### ISSUE TITLE
Stop downloading dependencies during tests

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#2646]
### Description

Stop downloading dependencies during tests and use gradle to cache, not `.m2` folder.

```
burrows.apps.giphy.example.ui.adapter.GiphyAdapterTest > testOnBindViewHolderOnAdapterItemClick STANDARD_ERROR
    Downloading: org/sonatype/oss/oss-parent/4/oss-parent-4.pom from repository central at http://repo1.maven.org/maven2
    Transferring 4K from central
    Downloading: com/ibm/icu/icu4j/53.1/icu4j-53.1.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
> Building 97% > :testDebugUnitTest > 15 tests completed    Transferring 5K from sonatype
    Downloading: com/ibm/icu/icu4j/53.1/icu4j-53.1.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Downloading: com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Downloading: com/almworks/sqlite4java/sqlite4java/0.282/sqlite4java-0.282.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Downloading: com/google/android/apps/common/testing/accessibility/framework/accessibility-test-framework/2.1/accessibility-test-framework-2.1.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Downloading: com/google/guava/guava/19.0/guava-19.0.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 9482K from sonatype
> Building 97% > :testDebugUnitTest > 15 tests completed    Transferring 152K from sonatype
    Transferring 2254K from sonatype
    Transferring 126K from sonatype
> Building 97% > :testDebugUnitTest > 15 tests completed    Unable to locate resource in repository
```
### Steps to Reproduce

./gradlew testDebug
### Robolectric & Android Version

3.1.2

**Comment by jaredsburrows** [comment]
It looks like some of the dependencies are `provided` instead of in the `compile` scope.

**Comment by jaredsburrows** [comment]
@xian @jongerrish Can we add them as `compile` dependencies instead of `provided`?

**Comment by jaredsburrows** [comment]
**For those that are still having this problem, download all the dependencies and transitive dependencies up front for your CI:**

```
    task downloadDependencies(type: Copy) {
        description "Downloads all dependencies."
        group "build"

        from {
            // Use of closure defers evaluation until execution time
            project.configurations
                .findAll { configuration -> configuration.canBeResolved }
                .collect { configuration -> configuration.resolvedConfiguration.lenientConfiguration.files }
        }
        into "$project.buildDir/dependencies"
    }
```

**Example:**

```
Step 1: gradlew downloadDependencies
Step 2: gradlew assembleDebug testDebug
```

**Comment by jongerrish** [comment]
Nice! :-)

On May 12, 2017 2:53 PM, "Jared Burrows" <notifications@github.com> wrote:

*For those that are still having this problem, download all the
dependencies and transitive dependencies up front for your CI:*

    task downloadDependencies(type: Copy) {
        description "Downloads all dependencies."
        group "build"

        from {
            // Use of closure defers evaluation until execution time
            project.configurations
                .findAll { configuration -> configuration.canBeResolved }
                .collect { configuration ->
configuration.resolvedConfiguration.lenientConfiguration.files }
        }
        into "$project.buildDir/dependencies"
    }

*Example:*

Step 1: gradlew downloadDependencies
Step 2: gradlew assembleDebug testDebug

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/2646#issuecomment-301194623>,
or mute the thread

**Comment by jaredsburrows** [comment]
@jongerrish This is still an issue:

<img width="715" alt="screen shot 2017-08-20 at 12 10 54 pm" src="https://user-images.githubusercontent.com/1739848/29497651-a7eb786c-85a0-11e7-86f4-b15faabc4ea0.png">


Can I make a PR to just add these as `compile` dependencies?

**Comment by jaredsburrows** [comment]
@jongerrish @xian Can I please make a PR to fix this?

**Comment by jongerrish** [comment]
Of course. PRs always welcome.

@xian was doing something related so sync with him first.

**Comment by jaredsburrows** [comment]
@jongerrish Using the latest `"org.robolectric:robolectric:3.5.1"`, I was actually not able to reproduce this. Closing!

**Comment by HowardSchmaeu** [comment]
just saying: i got this Error today with the robolectric:3.8 Version

**Comment by JcMinarro** [comment]
Me too.
Robolectric version 3.8

**Comment by ChristopherME** [comment]
Me too.
Roboelectic version 4.3.1
