### ISSUE TITLE
PointF equals does not work properly in Robolectric

### ISSUE THREAD

**Issue by WaseemTheDream** [robolectric/robolectric#2652]
### Description

PointF equals doesn't return true when it is compared with a PointF having the same underlying x,y coordinates.
### Steps to Reproduce

```
    PointF pointA = new PointF(0.5f, 0.5f);
    PointF pointB = new PointF(0.5f, 0.5f);
    if (!pointA.equals(pointB)) {
      throw new IllegalStateException("wut.");
    }
```

in a Robolectric test throws the exception.
### Robolectric & Android Version

Robolectric 3.0, Android 6.0

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
