### ISSUE TITLE
Spinner IllegalArgumentException - Support Library 24.*

### ISSUE THREAD

**Issue by mgoovaer** [robolectric/robolectric#2654]
### Description

Robolectric tests fail when interacting with a Spinner:

_java.lang.IllegalArgumentException: Spinner adapter view type count must be 1
at android.widget.Spinner.setAdapter(Spinner.java:439)
at android.support.v7.widget.AppCompatSpinner.setAdapter(AppCompatSpinner.java:389)_
### Steps to Reproduce

Tests running in SDK 22

```
Spinner memberSpinner = (Spinner) findViewById(R.id.member_spinner);
memberSpinner.setAdapter(memberSpinnerAdapter);
```

^will crash on the setAdapter line. Adapter has items set to it, custom class extending "BaseAdapter"
### Robolectric & Android Version

Robolectric version: 3.1.2
Support Library Version: 24.2.1

This is not an issue on Support Library 23.3.0

**Comment by mgoovaer** [comment]
Any update on this?

**Comment by landoulsi** [comment]
Same issue here with 
Robolectric: 3.4.2
Support Library: 25.4.0

**Comment by jongerrish** [comment]
Try with Robolectric 4.0 and binary resource mode. Resource handling is now way more accurate. If its still an issue there please reopen and we'll prioritize.
