### ISSUE TITLE
Robolectric detect wrong path of manifest file

### ISSUE THREAD

**Issue by Khang-NT** [robolectric/robolectric#2662]
### Description

I got a Warning

> No such manifest file: build/intermediates/manifests/full/debug/AndroidManifest.xml  

No manifest file follow this path. In my situation, I think this path should be:

> build/intermediates/manifests/aapt/debug/AndroidManifest.xml
### Robolectric & Android Studio Version

Robolectric: 3.1.2
Android Studio 2.2
Build #AI-145.3276617, built on September 15, 2016
JRE: 1.8.0_76-release-b03 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Gradle: 2.2.0

**Comment by hidroh** [comment]
This has been reported in #2581

**Comment by jongerrish** [comment]
This should be fixed now with the build system API supported by Android Studio. Please try with Robolectric 4.0 (and binary resources enabled)

Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
