### ISSUE TITLE
RoboSharedPreferences never resets shouldClearOnCommitFlag

### ISSUE THREAD

**Issue by wbonnefond** [robolectric/robolectric#2675]
### Description

`RoboSharedPreferences` should reset the `shouldClearOnCommitFlag` to false after it makes a commit. The current behavior calls `.clear()` every time `.commit()` is called, causing the preferences to be wiped out.

I would submit a pull request with the change and tests, but I am unable to get the project to build and run in IntelliJ. 

The fix should go after this line: https://github.com/robolectric/robolectric/blob/21b0dc3dbadf96bd5267f382ff136f242fd52263/robolectric-shadows/shadows-core/src/main/java/org/robolectric/fakes/RoboSharedPreferences.java#L176
### Steps to Reproduce

Create a new SharedPreferences.Editor, call `clear()`, put 3 values with unique keys, call `commit()`, put 3 more values with unique keys, call `commit()`, see that only the last 3 values are in the preferences.
### Robolectric & Android Version

All Android and Robolectric versions.

**Comment by jongerrish** [comment]
We've replaced RoboSharedPreferences in favor of the real Android framework code so I'm hping this issue is fixed now. Want to give it a try with Robolectric 4.0 and reopen if its still an issue?
