### ISSUE TITLE
ShadowDrawable does not understand support vectors

### ISSUE THREAD

**Issue by hzsweers** [robolectric/robolectric#2682]
### Description

`ShadowDrawable` does not have any robo data for support vectors. This hurts in testing as it renders the APIs useless, such as verifying the source resId.

<img width="1382" alt="screen shot 2016-10-17 at 4 11 47 pm" src="https://cloud.githubusercontent.com/assets/1361086/19441103/b8bf87e0-9484-11e6-982d-853bb8db1239.png">
### Steps to Reproduce

Use a support vector drawable, such as what's returned by `AppCompatResources#getDrawable()` on API < 23
### Robolectric & Android Version

3.0-3.1.2-master
targeting android 21-23

**Comment by NathanSass** [comment]
@hzsweers Did you ever figure out any workarounds for this?

**Comment by hzsweers** [comment]
Nope!

**Comment by kschults** [comment]
Still an issue in 3.5.1.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
