### ISSUE TITLE
Support for API level 25

### ISSUE THREAD

**Issue by PopTudor** [robolectric/robolectric#2687]
Hello,
as the title says, can you please update the support to API 25 ?
thanks !

**Comment by kibotu** [comment]
apparently there is not even api24 support... :/

**Comment by xian** [comment]
Workin on it! :-)

**Comment by martinbaciga** [comment]
Hi @xian, i need to work with API level 25. Do you know when this will be supported? 

Thanks.

**Comment by jongerrish** [comment]
We have API 24 support already but we want to keep supporting Java 7 so
have a few more build tweaks to go but we're close.

API 25 has hit AOSP so we'll work on that right after.

**Comment by martinbaciga** [comment]
Ok thanks @jongerrish

**Comment by xian** [comment]
Robolectric 3.2 supports API level 25. Thanks for your patience!

**Comment by martinbaciga** [comment]
Cool! Thanks guys!
