### ISSUE TITLE
No output has been received in the last 10 minutes

### ISSUE THREAD

**Issue by PLNech** [robolectric/robolectric#2691]
### Description

Since a few builds, Travis fails to run our robolectric-based testsuite with the following message:
>No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

It seems to be a timeout in the resolution of runtime dependencies by Robolectric:
```
com.algolia.search.saas.BrowseIteratorTest > testCancel STANDARD_ERROR
    Downloading: org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar from repository central at http://repo.maven.apache.org/maven2
    Transferring 28K from central
    Downloading: org/robolectric/shadows-core-v21/3.1.2/shadows-core-v21-3.1.2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 2609K from sonatype
    Downloading: org/robolectric/robolectric-annotations/3.1.2/robolectric-annotations-3.1.2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 9K from sonatype
    Downloading: org/robolectric/robolectric-resources/3.1.2/robolectric-resources-3.1.2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 149K from sonatype
    Downloading: org/robolectric/robolectric-utils/3.1.2/robolectric-utils-3.1.2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 49K from sonatype

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

However, running the tests locally works as expected.  

Do you have any idea what could be the issue here and if I can do something to solve it?
I see that I can use Robolectric in offline mode, but I couldn't find a simple way to download all of Robolectric's dependencies myself.

### Steps to Reproduce
- See the last builds on the `feat/searchFacets` branch: https://travis-ci.org/algolia/algoliasearch-client-android/builds/169209786
- See the last build of the master branch, where only some jobs succeeded and the others resulted in the same error: https://travis-ci.org/algolia/algoliasearch-client-android/builds/170392556

### Robolectric & Android Version
- `robolectric:3.1.2`
- `compileSdkVersion 24`
- `buildToolsVersion "24.0.3"`
- `targetSdkVersion 24`

**Comment by PLNech** [comment]
Using `travis_wait` as [recommended in case of a build timing out](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received), the build finishes successfully.

Still, what could explain this issue only appears on Travis but not when running tests locally?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
