### ISSUE TITLE
ModuleVersionNotFoundException with gradle 2.12

### ISSUE THREAD

**Issue by nitishgoyal13** [robolectric/robolectric#2694]
### Description
Web Facets/Artifacts will not be configured properly</b> Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':media-planner-api:runtime'. Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find BIDMat:BIDMat:1.1.0-cuda7.5

I am using gradle 2.12 version

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
