### ISSUE TITLE
CHANGELOG for new releases

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#2699]
Guys,

It would be great to get documented what is changed in new version.

I saw new version 3.1.4, but I don't have clue how different it from 3.1.2, that I used before. Especially it is critical when after the update all your Robolectric tests stop working.

**Comment by emartynov** [comment]
Fix for failing tests for me was remove `packageName` from `@Config` section

**Comment by mnonnenmacher** [comment]
FYI, Robolectric changelogs are published on blogspot (and linked on Twitter):
http://robolectric.blogspot.de/
https://twitter.com/robolectric

For example the one for 3.1.4 is here:
http://robolectric.blogspot.de/2016/10/robolectric-314-is-released.html

But I would also prefer to have better visibility for this, for example as a file in the repo or at least an easy to find link on the homepage and in the readme file.

**Comment by xian** [comment]
We're now posting release notes again [here](https://github.com/robolectric/robolectric/releases), sorry for the lapse!

**Comment by emartynov** [comment]
Thank you! Appreciate all your hard work!
