### ISSUE TITLE
Running tests with contants = BuildConfig.class defined runs forever

### ISSUE THREAD

**Issue by bschnack** [robolectric/robolectric#2715]
### Description
I am trying to set up RoboElectric and every time I try to run the tests, the tests will either hang or fail to set up. If I add "constants = BuildConfig.class" then it will run forever and there will be no special output to tell me what is happening.

build.gradle:
```
dependencies {
    testCompile 'junit:junit:4.12'
    testCompile "org.robolectric:robolectric:3.1.4"
    testCompile "org.robolectric:shadows-support-v4:3.1.4"
    testCompile "org.robolectric:shadows-multidex:3.1.4"
    testCompile "org.robolectric:shadows-play-services:3.1.4"
}
```

Test.java:
```
package <packagename>;

import android.os.Build;

import org.junit.Assert;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

import <packagename>.BuildConfig;

@RunWith(RobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.M, constants = BuildConfig.class)
public class Test {
    @org.junit.Test
    public void testAddition() throws Exception {
        Assert.assertEquals(2, 2);
    }
}
```

### Steps to Reproduce
Every time I run with the configuration I describe above, it will run forever and the only output is:

> /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:59042,suspend=y,server=n...
> objc[65764]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java (0x1080774c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10818e4e0). One of the two will be used. Which one is undefined.
> Connected to the target VM, address: '127.0.0.1:59042', transport: 'socket'

### Robolectric & Android Version
I am using version 3.1.4 and the Android Versions info is:
        minSdkVersion 17
        targetSdkVersion 25

EDIT: I moved over my build.gradle files and my test into a brand new project and it worked, so I guess this is a more complicated issue and I just want to know how to debug it.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
