### ISSUE TITLE
WarmUp robolectric before the tests run

### ISSUE THREAD

**Issue by OleksandrKucherenko** [robolectric/robolectric#2718]
### Description
I start a new project and from the beginning the team select robolectric as test framework.
When i run the simplest robolectric test, it execution time is really bad in compare to other tests... 
if jUnit tests completed in ms, robolectric takes ~20sec... this is x1000 time bigger in compare to other tests.

Do we have any ability to warmup the robolectric before the tests execution?! force it to load all the classes and etc.?

### Steps to Reproduce
Run the unit test in IDE with only one simplest call. 

```
   public void testCreateApplicationInstance() throws Exception {
        final EasyParkApp application = (EasyParkApp) RuntimeEnvironment.application;
         assertThat(application).isNotNull();
  }
```

Execution time is ~20s, all the dependencies already downloaded...

### Robolectric & Android Version
robolectric 3.1.4
android api 25

**Comment by jongerrish** [comment]
Robolectric 4.0 and binary resources should vastly improve startup time (we see around 20-35% improvement internally).

Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
