### ISSUE TITLE
Update Android M(23) SDK revision to r3

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#2721]
### Description

According to [AndroidSdk.groovy](https://github.com/robolectric/robolectric/blob/master/buildSrc/src/main/groovy/AndroidSdk.groovy), the SDK revision for Android M (SDK 23) is r1 (6.0.0_r1). I was trying to debug a test that uses SDK 23 Android Studio and had difficulties because the SDK sources in Android Studio are for SDK 23 r3. When I stepped into the Android sources from my test, the line numbers didn't match up.

It seems beneficial to update M to the most recent revision that is available in Android Studio.

**Comment by jongerrish** [comment]
I agree. Are the other APIs up to date also? (18-22?)

**Comment by hoisie** [comment]
These are the current versions in Robolectric:
```groovy
    static final Map<Integer, String> versions = [
            16: "4.1.2_r1-robolectric-0",
            17: "4.2.2_r1.2-robolectric-0",
            18: "4.3_r2-robolectric-0",
            19: "4.4_r1-robolectric-1",
            21: "5.0.0_r2-robolectric-1",
            22: "5.1.1_r9-robolectric-1",
            23: "6.0.0_r3-robolectric-0",
    ]
```

Comparing that to the SDK manager, it seems like 23, 19, 18, 17, and 16 are out of date. 22 and 21 seem to be up to date. 22 is using r9, which appears to be more recent than the version available in the Android SDK Manager.
