### ISSUE TITLE
Who is actually running this project?

### ISSUE THREAD

**Issue by hzsweers** [robolectric/robolectric#2727]
What's the direction of this project? Who owns it? Is there a roadmap?

The current state of this project is pretty bad and it doesn't appear to be getting better. Contributions appear to come as needed from a select few on the outside, major outstanding issues (and regressions!) continue to go unfixed, and there's no roadmap. I think it's time to acknowledge there is a committer crisis with this project and that it's quickly becoming unsafe to rely on long term as a result.

**Comment by xian** [comment]
Huh, well I disagree with your characterization of the state of the project, though I agree we need to be more transparent about  Robolectric's roadmap and prioritization, and team. We'll address that in more detail soon; at the moment, our top priority is support for SDK 24.

**Comment by hzsweers** [comment]
Can you answer the two other questions? There have also been serious regressions in the last few releases (powermock interop, performance, memory leaks, etc) that continue to go unfixed, adding to characterization that contributions only come as needed from outside contributors for their own work.

**Comment by jongerrish** [comment]
Hi Zac. Up until recently you were correct, contributions did only come on an as needed basis. Xian and I have recently taken over working full time on Robolectric and right now we are focused on stabilizing the product whilst we are also thinking about longer term direction.

Our immediate priorities are reducing API lag between Robolectric and the SDK and fixing some critical bugs:-

* API 24 support (which we are close to landing, see https://github.com/robolectric/robolectric/tree/api_24)
* API 25 support
* Major resources issue: https://github.com/robolectric/robolectric/issues/2315 (We are close to landing this too see https://github.com/robolectric/robolectric/tree/resources).

My hope is we can land all three of these before the end of the year in a new major release.

The following bugs are also high on our list and could go out in a point release early next year.

https://github.com/robolectric/robolectric/issues/2566
https://github.com/robolectric/robolectric/issues/2429

Following this I think we'd be in a better position to publicly talk about longer term goals.

I am sorry that using Robolectric has been frustrating for you and others but know we are working hard to improve the experience and we'd welcome specific feedback and of course contributions.

**Comment by hzsweers** [comment]
Great to hear, thanks for the details @jongerrish! Looking forward to you guys' work
