### ISSUE TITLE
create Such as ShadowFile for java.io.File，but invalid

### ISSUE THREAD

**Issue by fuyuanjiangjun** [robolectric/robolectric#2728]
### 1.ShadowFile.java:
@Implements(File.class)
public class ShadowFile {
    @Implementation
    public boolean exists(){
        return false;
    }
}
2.FileTest.java:
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class,shadows = {ShadowFile.class})
public class FileTest {

    @Test
    public void test_tt(){
		//This folder is being
        File file = new File("D:\\123\\456");
        assertFalse(file.exists());
    }
}
3.run FileTest.java，but return fail

### Robolectric & Android Version
Robolectric:3.1.4
Android Version:23

**Comment by hoisie** [comment]
Only certain packages are instrumented by default: See https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/bytecode/InstrumentationConfiguration.java#L153

Technically you could instrument java.io if you use a custom test runner, but I would caution against that. What are you trying to do?

**Comment by fuyuanjiangjun** [comment]
Thank you for answer my question.I'm doing white-box testing, I will try to find another way to solve this problem now~
