### ISSUE TITLE
ShadowJobScheduler.cancel(jobId) does not remove job with ID?

### ISSUE THREAD

**Issue by hidroh** [robolectric/robolectric#2738]
Hi there, I'm wondering if it's a mistake or there is a reason that [`ShadowJobSchedulerImpl.cancel(jobId)`](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowJobScheduler.java#L56) does not remove the JobInfo with given ID from the map of scheduled jobs?

**Comment by jongerrish** [comment]
Looks like it just wasn't implemented. Do you want to send me a PR with a
fix and test? If so I'll merge it today.
