### ISSUE TITLE
Trouble replacing or extending base shadows using RAP

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#2744]
### Description

Let's assume I am using the Robolectric Annotation Processor (RAP) to load my custom shadows instead of using Config. If any of my custom shadows extend or replace Robolectric base shadows, they may not get used in tests, depending on the order of ShadowProviders returned by the class loader.

When Robolectric loads shadows using RAP, it loads them using ServiceLoader.load (in ShadowMap.java):

```java
  static {
    for (ShadowProvider provider : ServiceLoader.load(ShadowProvider.class)) {
      SHADOWS.putAll(provider.getShadowMap());
    }
  }
```

Because shadows are stored in a Map<String, String>, if multiple shadows implement a single class, the last one loaded will be used.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
