### ISSUE TITLE
ShadowMapView with gradle com.google.android.maps wrong import

### ISSUE THREAD

**Issue by spiritinlife** [robolectric/robolectric#2760]
### Description
I cannot seem to figure out how to use the ShadowMapView.
When using gradle the google MapView has a different package name than the ShadowMapView uses.
ShadowMapView uses com.google.android.maps import to get access to MapView but the MapView is not found because its under com.google.android.gms.maps .
### Steps to Reproduce
1) Use gradle 
2) Add compile google play services
3) Add compile shadows for maps
4) Go to ShadowMapView class and see the errors in imports and that the MapView is not found
### Robolectric & Android Version
Robolectric 3.1.4 using sdk 21 for the tests

Am i doing something wrong?

**Comment by abhaysood** [comment]
Same issue here, did anyone find a solution?

**Comment by utzcoz** [comment]
Hi @spiritinlife @abhaysood , Robolectric 3.1.4 is too old, please use latest Robolectric 4.9 to test it again. And feel free to reopen this issue if you find that this issue still exists. Thanks.
