### ISSUE TITLE
XmlUtils incorrectly parses objectAnimator attributes (java.lang.NumberFormatException)

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#2767]
### Description
If starting a fragment indirectly through Robolectric.buildActivity() it seems that AnimatorInflater.loadAnimator() incorrectly parses the XML (second argument) which causes a NumberFormatException. It seems like Robolectric expects the value to be in float literal format.

### Steps to Reproduce
An activity, FooActivity, that does something like:

```
public class FooActivity extends Activity {
  protected void onCreate(Bundle savedInstanceState) {
        setContentView(R.layout.activity_foo);
            final Fragment fragment = new FooFragment();
            final FragmentTransaction ft = getFragmentManager().beginTransaction();
            ft.replace(R.id.activity_foo, fragment, FooFragment.TAG);
            ft.commit();
 }
}
```

An xml, activity_foo.xml: 
```
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/activity_foo"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

</FrameLayout>
```

A fragment, FooFragment.java with something like:
```
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        fadeInAnimator = (ObjectAnimator) AnimatorInflater.loadAnimator(getActivity(), R.animator.fade_in_quick);
    }
```

and finally fade_in_quick.xml:

```
<?xml version="1.0" encoding="utf-8"?>

<objectAnimator
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:duration="20"
        android:propertyName="alpha"
        android:valueTo="255"
        android:valueType="intType"
        />

```
The test:
```
@Config(sdk = Build.VERSION_CODES.KITKAT, manifest = "./src/main/AndroidManifest.xml")
@RunWith(RobolectricTestRunner.class)
public class FooTest {

@Test
public void notWorking() {
Robolectric.buildActivity(FooActivity.class).create().visible().get();
}
}
```

This results in java.lang.NumberFormatException: For input string: "255.0"
Changing "255" to "255F" makes the test pass but will crash on an Android device

### Robolectric & Android Version
Robolectric 3.1.4
Android KITKAT

**Comment by usatf1290** [comment]
I am having the same exact issue. Any fix or update for this?

Robolectric 3.3.2
Android 8.0.0, DP4

**Comment by jongerrish** [comment]
Robolectric 4.0 with binary resource mode enabled should have fixed this. Please give it a try and reopen if its still an issue.

**Comment by alixwar** [comment]
I could not reproduce this using 4.0 (the examples I gave) so it seems to be working
