### ISSUE TITLE
Build.VERSION.SDK_INT return 0 

### ISSUE THREAD

**Issue by huewu** [robolectric/robolectric#277]
This Build.VERSION.SDK_INT value is set to 0 in adnroid.jar.
I use lated android SDK (version 15). 

So, when I test a some codes like below, 
it can't be tested correctly on robolectric.

if( Build.VERSION.SDK_INT > 15)
    bActionBar = true
else
   bActionBar = false;

Is there any workaround to handle this issue correctly? 
(to get a current SDK version code in robolectric)

**Comment by jiahaoliuliu** [comment]
Hi:
I am working on 3.0-Snapshot and when I try to get Build.VERSION.RELEASE it returns "unknown". I tried to find the method: Robolectric.Reflection.setFinalStaticField or RobolectricTestRunner.setStaticValue but it seems that it has been changed from 2.4 to 3.0.

What method should I call to set the Release name of the SDK? (currently 18)

**Comment by Lingviston** [comment]
For some reason at the moment:
ReflectionHelpers.setStaticField(Build.VERSION.class, "RELEASE", "4.4.3");

Doesn't work. Value remains 5.0.0_r2. Notice, that this way of setting doesn't work with ALL Build.VERSION class fields for me, but works with Build class itself.
