### ISSUE TITLE
Class.getResourceAsStream fails to return correct stream in M platform

### ISSUE THREAD

**Issue by motorro** [robolectric/robolectric#2773]
### Description
Class.getResourceAsStream seems to perform differently when using Build.VERSION_CODES.M and Build.VERSION_CODES.LOLLIPOP_MR1

My application uses [PhoneUtils](https://github.com/googlei18n/libphonenumber) library that loads its metadata using the following code:
```java
    static final MetadataLoader DEFAULT_METADATA_LOADER = new MetadataLoader() {
       @Override
       public InputStream loadMetadata(String metadataFileName) {
         return MetadataManager.class.getResourceAsStream(metadataFileName);
       }
    };
```

When configuring test with: 
```
    @Config(
            constants = BuildConfig::class,
            sdk = intArrayOf(Build.VERSION_CODES.M)
    )
```
resulting `JarUrlConnection` is set to:
```
sun.net.www.protocol.jar.JarURLConnection:jar:file:/C:/Users/motorro/.m2/repository/org/robolectric/android-all/6.0.0_r1-robolectric-0/android-all-6.0.0_r1-robolectric-0.jar!/com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_US
```
(refers roboelectric platform mock) and fails to read a file.

If configured with:
```
    @Config(
            constants = BuildConfig::class,
            sdk = intArrayOf(Build.VERSION_CODES.LOLLIPOP_MR1)
    )
```
resulting `JarUrlConnection` is set to:
```
 sun.net.www.protocol.jar.JarURLConnection:jar:file:/C:/Users/motorro/.gradle/caches/modules-2/files-2.1/com.googlecode.libphonenumber/libphonenumber/8.0.0/ce021971974ee6a26572e43eaba7edf184c3c63d/libphonenumber-8.0.0.jar!/com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_US
```
which points to correct library file (test passes).
Is it a roboelectric problem or do I miss some configuration here?

### Steps to Reproduce
Test class:
```kotlin
    @RunWith(RobolectricTestRunner::class)
    class ExampleUnitTest {
        companion object {
            private val PHONE: Phonenumber.PhoneNumber
    
            init {
                PHONE = Phonenumber.PhoneNumber()
                PHONE.countryCode = 7
                PHONE.nationalNumber = 4956360636
            }
        }
    
    
        @Test
        @Config(
                constants = BuildConfig::class,
                sdk = intArrayOf(Build.VERSION_CODES.LOLLIPOP_MR1)
        )
        fun withLollipop() {
            PhoneNumberUtil.getInstance().format(PHONE, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL)
        }
    
        @Test
        @Config(
                constants = BuildConfig::class,
                sdk = intArrayOf(Build.VERSION_CODES.M)
        )
        fun withM() {
            PhoneNumberUtil.getInstance().format(PHONE, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL)
        }
    }
```
You can get a complete sample project [here](https://github.com/motorro/RoboClassLoaderTest)

### Robolectric & Android Version
```
        compile 'com.googlecode.libphonenumber:libphonenumber:8.0.0'
        testCompile 'junit:junit:4.12'
        testCompile "org.robolectric:robolectric:3.1.4"
```

### Duct-tape
The duct-tape solution for now is to `@Config` all failing tests individually.

[StackOverflow](http://stackoverflow.com/questions/41246534/class-getresourceasstream-in-robolectric-environment-fails-to-return-correct-str)

**Comment by jongerrish** [comment]
InstrumentingClassLoader.getResourceAsStream() checks the platform jars first before jars on the system classpath such as libphonenumber.

Since com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_US has been included in the platform since API 23 and it finds the platform version first which is in a format that is incompatible with the libphonenumber library.

**Comment by jongerrish** [comment]
Reopened as the PR was rolled back to avoid risk of destabilizing 3.2.1, this will get rolled forward again for the 3.2.2 release.

**Comment by jongerrish** [comment]
OK, merged https://github.com/robolectric/robolectric/pull/2831 so this should be fixed
