### ISSUE TITLE
Memoize lookups in ReflectionHelpers methods

### ISSUE THREAD

**Issue by charlesmunger** [robolectric/robolectric#2774]
### Description
ReflectionHelpers is used all over robolectric, but it doesn't memoize its reflective operations - for example, this code in ShadowMessageQueue:
 `public Message getHead() {
    return getField(realQueue, "mMessages");
  }`

Does a new lookup of that field name on each call.

**Comment by utzcoz** [comment]
@hoisie @charlesmunger Looks like Robolectric removed many reflective operations. So I think this issue is obsolete, and feel free to reopen it if you think it is still necessary.
