### ISSUE TITLE
Provide configurable for using in-memory sqlite databases

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2784]
Add a configurable property that enables in-memory sqlite databases (see #2764).

**Comment by xian** [comment]
This could conceivably go on `@Config`, though I think we risk cluttering it up a bunch...

**Comment by utzcoz** [comment]
@hoisie Does `SQLite.Mode` work for this feature?

**Comment by utzcoz** [comment]
IMO, `SQLite.Mode` is used to configure the used sqlite shadow implementation, including legacy sqlite4java database and new native SQLite. So I will close this issue. cc @hoisie .
