### ISSUE TITLE
Warn if multiple Android SDKs are included in the classpath

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#2788]
### Description
Recently I ran into an issue where I unwittingly had multiple Android SDK's in the classpath during tests (specifically Android 25 and Android 16). The result was an error about a missing resource. If possible, it would be nice if Robolectric could warn if this situation occurs.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
