### ISSUE TITLE
Memory leak in ShadowLooper.loopingLoopers

### ISSUE THREAD

**Issue by davidburstromspotify** [robolectric/robolectric#2791]
### Description

After executing our 10k test cases, we have thousands of BackgroundThread instances retained on the heap. Looking closer at it, it appears as if ShadowLooper.loopingLoopers are retaining them. Even though it is a WeakHashMap, the Thread keys are referenced by the Looper.mThread field, meaning that the keys will never be GCd and the map will never be pruned. Unless I'm reading our HPROFs wrong.

### Robolectric & Android Version
Robolectric: 3.1.4
Android: any SDK

**Comment by davidburstromspotify** [comment]
More details here: http://stackoverflow.com/questions/8051912/will-a-weakhashmaps-entry-be-collected-if-the-value-contains-the-only-strong-re

**Comment by matthewhubblerose** [comment]
Is this fixed by https://github.com/robolectric/robolectric/pull/2963?

**Comment by davidburstromspotify** [comment]
No. I expect the loopingLoopers map to be explicitly cleared after all the loopers have been reset, because the Thread keys are still referenced by the Android Looper mThread field.

**Comment by KenVanHoeylandt** [comment]
All the memory leak issues we had in our project (with thousands of Robolectric tests) are fixed with version `3.4-rc2`.

**Comment by davidburstromspotify** [comment]
Looking at the latest source, I would say that loopingLoopers still leak.
http://docs.oracle.com/javase/6/docs/api/java/util/WeakHashMap.html (look at the "Implementation note:")

**Comment by utzcoz** [comment]
@davidburstromspotify Please try the latest Robolectric version, and feel free to reopen this issue if it still exists.
