### ISSUE TITLE
ShadowMotionEvent doesn't shadow all variants of #obtain

### ISSUE THREAD

**Issue by flederbaysian** [robolectric/robolectric#2796]
### Description
`android.view.MotionEvent` has 6 variants of the `obtain()` method. Right now, `org.robolectric.shadows.ShadowMotionEvent` only implements two of those.

This means that using any of the missing overloads ends up with 0 values for all fields in the `MotionEvent`.

### Steps to Reproduce
The following unit test fails:
```java
    MotionEvent event = MotionEvent.obtain(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);
    assertEquals(1, event.getDownTime());
```

### Robolectric & Android Version
robolectric-3.2-rc1

**Comment by utzcoz** [comment]
The latest robolectric removes shadow support for `MotionEvent#obtain`, and it recommends you to use [androidx test's MotionEventBuilder](https://cs.android.com/androidx/android-test/+/master:core/java/androidx/test/core/view/MotionEventBuilder.java), or use `MotionEvent#obtain` directly. Hi @hoisie, maybe this issue can be closed.

**Comment by hoisie** [comment]
Yeah it looks like there's been a lot of iteration on ShadowMotionEvent. I'm guessing all MotionEvent.obtain variants should work:
https://github.com/robolectric/robolectric/commits/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowMotionEvent.java
