### ISSUE TITLE
Shadow needed for SubscriptionManager APIs

### ISSUE THREAD

**Issue by jpd236** [robolectric/robolectric#2800]
(Checked with Robolectric 3.2-rc1)

[SubscriptionManager](https://developer.android.com/reference/android/telephony/SubscriptionManager.html) was added in API 22 but does not have a shadow. One should be created and returned in ShadowContextImpl when the TELEPHONY_SUBSCRIPTION_SERVICE service is requested.

**Comment by xian** [comment]
`Context.getSystemService(TELEPHONY_SUBSCRIPTION_SERVICE)` will now return a `SubscriptionManager`. As of 3.2 it has no shadow; if you write one, we'd love a pull request! Thanks!
