### ISSUE TITLE
ShadowNotification needs update to handle null contentView

### ISSUE THREAD

**Issue by jpd236** [robolectric/robolectric#2801]
I'm seeing the following NullPointerException upon upgrading to 3.2-rc2:

```
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowNotification.applyContentView(ShadowNotification.java:82)
	at org.robolectric.shadows.ShadowNotification.getContentTitle(ShadowNotification.java:33)
```

from a cursory look at things, the crash is because realNotification#contentView is null, and indeed, according to Notification's source, this became possible as of N:

```
     * As of N, this field may be null. The notification view is determined by the inputs
     * to {@link Notification.Builder}; a custom RemoteViews can optionally be
     * supplied with {@link Notification.Builder#setCustomContentView(RemoteViews)}.
```

which breaks what seems to be a pretty key underlying assumption in ShadowNotification.

**Comment by jongerrish** [comment]
The following test does not fail:-

  @Test
  @Config(minSdk = Build.VERSION_CODES.N)
  public void build_handlesNullContentView() throws Exception {
    Notification notification = builder.setContentTitle("Hello").setCustomContentView(null).build();
    assertThat(shadowOf(notification).getContentTitle().toString()).isEqualTo("Hello");
  }

Do you have a test case that illustrates this?

**Comment by jpd236** [comment]
contentView will be null iff targetSdkVersion >= N. See:

https://android.googlesource.com/platform/frameworks/base/+/7af536257107b9caaecee481095558db9eed320e/core/java/android/app/Notification.java#4005
