### ISSUE TITLE
Context#getExternalFilesDirs crashes

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#2818]
During tests, if a call is made to [Context#getExternalFilesDirs](https://developer.android.com/reference/android/content/Context.html#getExternalCacheDirs()), a crash happens on all SDK levels. Instead of crashing, it could return an empty file array.

**Comment by xian** [comment]
Fixed with 040174d8b13ca36d71d73c0eadd7dd90dca34afe.
