### ISSUE TITLE
Controller improvements

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2824]
- [ ] `@Deprecate` `attach()`
- [ ] Add `detach()` to `FragmentController`?

**Comment by jongerrish** [comment]
How about @Deprecate ActivityController.visible() also and have it called
after onResume() automatically maybe?

**Comment by MGaetan89** [comment]
Since `FragmentController` has been deprecated, maybe we can close this issue?
And what about deprecating `ActivityController` in favour of [`ActivityScenario`](https://developer.android.com/reference/androidx/test/core/app/ActivityScenario)?

**Comment by MGaetan89** [comment]
Closing this issue, since `FragmentController` is deprecated, and the `attach()` method no longer exists.
