### ISSUE TITLE
Where could I find Sqlite DB file?

### ISSUE THREAD

**Issue by Lonecy** [robolectric/robolectric#2835]
### Description
I found that each time I ran testing, the DB is a new one,  Can I specify the DB path? Let the data persistant?

### Robolectric & Android Version
robolectric:3.2.1

**Comment by jongerrish** [comment]
Tests are designed to be hermetic, so while you can open a db with any file name, the data directory for the  app is a new one for each test. If you change that then you run the risk of test pollution. I don't think changing this would be a priority for us, but if you can come up with a compelling use case and are willing to send us a PR its something we could consider.
