### ISSUE TITLE
FragmentController creates extra Fragment instance when savedInstanceState is provided

### ISSUE THREAD

**Issue by pbatg** [robolectric/robolectric#2841]
### Description
`FragmentController::create()` adds a Fragment unconditionally, but if the saved instance state passed to `create(Bundle)` was created using `FragmentController::saveInstanceState()`, then the Activity's `FragmentManager` will also create a Fragment instance of the same type, resulting in multiple Fragments with the same ID.

### Steps to Reproduce
```
FragmentController<MyFragment> controller1 = Robolectric.buildFragment(MyFragment.class)
    .create()
    .start()
    .resume()
    .visible();

Bundle state = new Bundle();
controller1.saveInstanceState(state)
    .pause()
    .stop()
    .destroy();

FragmentController<MyFragment> controller2 = Robolectric.buildFragment(MyFragment.class)
    .create(state)
    .start()
    .resume()
    .visible();
```

**Expected:**
Activity created by `controller2` has one instance of `MyFragment` with same state as `controller1`.

**Actual:**
Activity created by `controller2` has two instances of `MyFragment`, the fragment saved by `controller1` (deserialized by `FragmentManager`) and a new instance (added by `FragmentController`)

One solution might be to look-up the Fragment created by FragmentManager in `FragmentController::create(int, Bundle)` instead of adding a new one whenever the Bundle argument is non-null.

```
  public FragmentController<F> create(final int contentViewId, final Bundle bundle) {
    shadowMainLooper.runPaused(new Runnable() {
      @Override
      public void run() {
        activityController.create(bundle);
        FragmentManager fragmentManager = activityController.get().getFragmentManager();
        if (bundle == null) {
          fragmentManager.beginTransaction().add(contentViewId, fragment).commit();
        } else {
          fragment = fragmentManager.findFragmentById(contentViewId);
        }
      }
    });
    return this;
  }
```

### Robolectric & Android Version
`commit 7dbe030f3aa287975e0c07d72cb2da5b51c24a9e`

**Comment by MGaetan89** [comment]
`FragmentController` is now deprecated, and so is the underlying `android.app.Fragment` API.
The recommended alternative is to use [`FragmentScenario`](https://developer.android.com/guide/fragments/test).
We can probably close this issue?

**Comment by MGaetan89** [comment]
Closing this issue, since both `FragmentController` and `android.app.Fragment` are now deprecated.
You should be able to achieve what you want with `FragmentScenario`.
