### ISSUE TITLE
Global robolectric.properties file is not loaded

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#2843]
### Description
When using a global `robolectric.properties` file (ie, `robolectric.properties` defined in the root of `resources` folder) `ConfigMerger` will fail to load it.

### Steps to Reproduce
Create a `robolectric.properties` file under `resources` folder, and remove any `@Config` annotations or other `robolectric.properties` files. Run the tests. They will all fail. Probably.

### Robolectric & Android Version
Robolectric 3.2.1

**Comment by hidroh** [comment]
Robolectric expects `robolectric.properties` under a new location since 3.2. See https://github.com/robolectric/robolectric/wiki/3.1-to-3.2-Migration-Guide and http://robolectric.org/configuring/

**Comment by menny** [comment]
@hidroh according to the code (https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/ConfigMerger.java#L80) and the unit tests (https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/ConfigMergerTest.java#L108), the global package `robolectric.properties` file should work as before.
Also, this change might work for small projects, where all classes are under the same package name. But for more complex projects, where you have multiple base package names, or where the application-id does not match the filesystem, this change is completely wrong.

[this](https://github.com/robolectric/robolectric/pull/2844/commits/926f2c8a26a7376b5bd7e21e9bdc193db4d1d7eb) change will fix this.

**Comment by davidmigloz** [comment]
Hello,

In my case, I have a modular android project and I wanted to have a general `robolectric.properties` file, but I'm having a hard time making it work.

My structure looks like this:

```
📂/
 ┣ 📂app/src/
 ┃ ┣ 📂main/...
 ┃ ┗ 📂test/...
 ┣ 📂core/src/
 ┃ ┣ 📂main/...
 ┃ ┗ 📂test/...
 ┣ 📂module1/src/
 ┃ ┣ 📂main/...
 ┃ ┗ 📂test/...
 ┗ 📂...
```

- If I place my file in the root folder (`/robolectric.properties`), it doesn't work.
- But if I place a properties file per module it does work (`app/src/test/resources/robolectric.properties`, `core/src/test/resources/robolectric.properties`, etc.).

My `robolectric.properties` file is very simple:
```
sdk=28
```
I'm using Robolectric v4.3.1.

Am I doing something wrong? How can I make the root `robolectric.properties` file work for the whole project?

Thanks for your help.

**Comment by mishackee** [comment]
@davidmigloz Have you found a solution? I am facing the same issue 😞

**Comment by hoisie** [comment]
Does this issue only occur in Android Studio? Or does it also occur with
command line Gradle?

**Comment by ranjeetsinha13** [comment]
This occurs both ways. I get invalid symlink error when I create it this way
