### ISSUE TITLE
Tests fail with android-maven-plugin

### ISSUE THREAD

**Issue by hameno** [robolectric/robolectric#2847]
### Description

Test in a project with android-maven-plugin (4.4.3) fails with errors like this:

    IllegalArgumentException: class android.support.v7.appcompat.R contains final fields, these will be inlined by the compiler and cannot be remapped.

android-maven-plugin uses the SymbolWriter class from com.android.tools.build:builder:1.5.0 which always writes "public static final " for all fields

This is caused by the change in #2776 

### Steps to Reproduce

Use aar dependency inside aar library with tests.

### Robolectric & Android Version

Robolectric 3.2.1
android-maven-plugin 4.4.3

**Comment by hameno** [comment]
Seems to be a android-maven-plugin bug, I still created this issue as it may be useful for others...

**Comment by hameno** [comment]
A solution has been found, a fix will most likely be in the next release (https://github.com/simpligility/android-maven-plugin/pull/757)

**Comment by xian** [comment]
Thanks @hameno!

**Comment by scottkennedy** [comment]
I'm also seeing this and I am not using android-maven-plugin (directly, at least).

Is there any way to determine which of my dependencies may be causing this issue?

**Comment by xian** [comment]
Things have changed pretty significantly with the release of Robolectric 4.0; can you give it a try again and reopen this issue if the problem remains? Thanks!
