### ISSUE TITLE
Investigate replacing support V4 shadows with assertJ Robolectric extensions.

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2849]

**Comment by jongerrish** [comment]
As the support library grows, Robolectric needs to instrument more code causing a penalty of test run time.

**Comment by charlesmunger** [comment]
@alanv, robolectric is currently shadowing four APIs in the support library:
* ShadowAsyncTaskLoader.java & ShadowCursorLoader.java
* ShadowDrawerLayout.java & ShadowSwipeRefreshLayout.java
* ShadowLocalBroadcastManager.java

The loader shadows are replacing the underlying executor with a robolectric one, so those may not go away. 

The layout shadows are quite simple - all they're doing is exposing a registered listener, presumably so people can call it and ensure that their code takes some action when a refresh event happens. Those tests should be rewritten to call SwipeRefreshLayout.setRefreshing(true), but that method currently doesn't notify listeners; providing a version of it that did would allow us to remove this shadow. The same is true for DrawerLayout - calls to openDrawer() or closeDrawer() should suffice.

LocalBroadcastReceiver doesn't really need a shadow, tests could instead be written to simply register a receiver that checks for broadcasts being sent.

**Comment by utzcoz** [comment]
We have removed shadows for v4 from 4.9. So I will close this issue.
