### ISSUE TITLE
Make scheduler be paused by default.

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2851]
Caused problems because scheduler runs tasks inline by default which could cause certain things to be run out of order. If we change the default behaviour we'd require a configuration option to avoid breaking teams depending on the current behaviour.

- [ ] Default Scheduler state to PAUSED
- [ ] Generate list of failing tests in PAUSED
- [ ] Run marked tests in UNPAUSED

**Comment by virl** [comment]
See #2977

**Comment by utzcoz** [comment]
@brettchabot @hoisie I think you have made paused scheduler by default from 4.6 or a similar version. So I close this issue.
