### ISSUE TITLE
Cannot get custom Annotation instance in HelperTestRunner

### ISSUE THREAD

**Issue by kxfeng** [robolectric/robolectric#2852]
### Description
I want to use custom annotation named `CustomRule` to add custom TestRule to my unit test. When I override `getTestRules` methord in HelperTestRunner, I use `getTestClass().getAnnotation(CustomRule.class)`  but it return null, when iterate the the annotations return from `getTestClass().getAnnotations()`, there seem to be a CustomRule annotation but it's not instanceof CustomRule. This is strange. What type is the annotation? How can I get the CustomRule instance?

Howerver, everything whorks fine when override methord in RobolectricTestRunner. `getTestClass().getAnnotation(CustomRule.class)` renturn a CustomRule instance, and the iterator can find an annotation instanceof CustomRule.

### Steps to Reproduce
This is all my code:

**CustomRule.java**
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
public @interface CustomRule {
}
```

**ExampleUnitTest.java**
```java
@RunWith(CustomRobolectricRunner.class)
@Config(sdk = 24, manifest=Config.NONE)
@CustomRule
public class ExampleUnitTest {
    @Test
    public void addition_isCorrect() throws Exception {
        assertEquals(4, 2 + 2);
    }
}
```

**CustomRobolectricRunner.java**
```java
public class CustomRobolectricRunner extends RobolectricTestRunner {

    public CustomRobolectricRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    protected List<FrameworkMethod> getChildren() {
        CustomRule rule = getTestClass().getAnnotation(CustomRule.class);
        System.out.println("RobolectricTestRunner get CustomRule = " + rule);

        Annotation[] annotations = getTestClass().getAnnotations();
        for (Annotation annotation : annotations) {

            if (annotation instanceof RunWith) {
                System.out.println("RobolectricTestRunner Annotation RunWith = " + annotation);
                continue;
            }
            if (annotation instanceof Config) {
                System.out.println("RobolectricTestRunner Annotation Config = " + annotation);
                continue;
            }
            if (annotation instanceof CustomRule) {
                System.out.println("RobolectricTestRunner Annotation CustomRule =" + annotation);
                continue;
            }
            System.out.println("RobolectricTestRunner Annotation Unknown =" + annotation);
        }

        return super.getChildren();
    }

    @Override
    protected HelperTestRunner getHelperTestRunner(Class bootstrappedTestClass) {
        try {
            return new CustomHelperTestRunner(bootstrappedTestClass);
        } catch (InitializationError initializationError) {
            throw new RuntimeException(initializationError);
        }
    }

    public class CustomHelperTestRunner extends HelperTestRunner {
        public CustomHelperTestRunner(Class<?> testClass) throws InitializationError {
            super(testClass);
        }

        @Override
        protected List<TestRule> getTestRules(Object target) {
            List<TestRule> result = super.getTestRules(target);

            CustomRule rule = getTestClass().getAnnotation(CustomRule.class);
            System.out.println("HelperTestRunner get CustomRule = " + rule);

            Annotation[] annotations = getTestClass().getAnnotations();
            for (Annotation annotation : annotations) {

                if (annotation instanceof RunWith) {
                    System.out.println("HelperTestRunner Annotation RunWith = " + annotation);
                    continue;
                }
                if (annotation instanceof Config) {
                    System.out.println("HelperTestRunner Annotation Config = " + annotation);
                    continue;
                }
                if (annotation instanceof CustomRule) {
                    System.out.println("HelperTestRunner Annotation CustomRule =" + annotation);
                    continue;
                }
                System.out.println("HelperTestRunner Annotation Unknown =" + annotation);
            }

            return result;
        }
    }
}
```

The unit test running output is

> RobolectricTestRunner get CustomRule = @com.example.sample.CustomRule()
> RobolectricTestRunner Annotation RunWith = @org.junit.runner.RunWith(value=class com.example.sample.CustomRobolectricRunner)
> RobolectricTestRunner Annotation Config = @org.robolectric.annotation.Config(...)
> RobolectricTestRunner Annotation CustomRule =@com.example.sample.CustomRule()
> HelperTestRunner get CustomRule = null
> HelperTestRunner Annotation RunWith = @org.junit.runner.RunWith(value=class com.example.sample.CustomRobolectricRunner)
> HelperTestRunner Annotation Config = @org.robolectric.annotation.Config(...)
> HelperTestRunner Annotation Unknown =@com.example.sample.CustomRule()

### Robolectric & Android Version
Robolectric 3.2.2
Android 7.0

**Comment by xian** [comment]
This is happening because `HelperTestRunner.getTestClass()` returns a class from a special classloader which Robolectric uses to simulate the Android environment. That means the annotation class won't be assignment-compatible with `CustomRule.class` loaded from the main classloader. You might be able to work around this with code like:

```java
Class annotationClass = getTestClass().getClass().getClassLoader().findClass("CustomRule");
CustomRule rule = getTestClass().getAnnotation(annotationClass);
```

Unfortunately you won't be able to access it directly as a `CustomRule` probably, but you could still call methods on in reflectively.

Hope that helps!

**Comment by kxfeng** [comment]
@xian Thanks very much for you answer. But there's a small bug: `HelperTestRunner.getTestClass().getClass().getClassLoader()` is same to `RobolectricTestRunner.getTestClass().getClass().getClassLoader()`, they are both the main classloader. Just change it to `HelperTestRunner.getTestClass().getJavaClass().getClassLoader()`, this return the InstrumentingClassLoader. Now everything work fine to call methods on the annotation with reflection.

This is the final workable code. Hope it's useful to others:
```
Class annotationClass = getTestClass().getJavaClass().getClassLoader().loadClass(CustomRule.class.getName());
Annotation rule = getTestClass().getAnnotation(annotationClass);
```
