### ISSUE TITLE
Cannot get packageInfo.services and packageInfo.activities by call getPackageInfo()

### ISSUE THREAD

**Issue by fuyuanjiangjun** [robolectric/robolectric#2853]
### Description
Cannot get packageInfo.services and packageInfo.activities by call getPackageInfo()

### Steps to Reproduce
1.call such as:
PackageInfo packageInfo = RuntimeEnvironment.application.getApplicationContext().getPackageManager().getPackageInfo(packageName, PackageManager.GET_SERVICES);
2.packageInfo.services and packageInfo.activities always return null

ps.I found that addManifest(AndroidManifest androidManifest, int labelRes)  in the DefaultPackageManager class, there is no added packageInfo.services and packageInfo.activities。please help me~

### Robolectric & Android Version
Robolectric 3.2.2 & Android 23

**Comment by jhansche** [comment]
This appears to be fixed in 3.8

**Comment by jongerrish** [comment]
We've done a big over haul of PackageManager and we now also process the manifest using real Android framework code. Feel free to reopen if its still an issue.
