### ISSUE TITLE
Poor performance in version 3.2.1

### ISSUE THREAD

**Issue by mrtowel** [robolectric/robolectric#2854]
After migating from Robolectric 3.1 to 3.2.1 I've noticed that overall test execution time increased dramatically from 192 s to 360 s. There is over 1600 tests in nearly 200 test classes. 

Any tips on how to get better performance during tests execution?

**Comment by xian** [comment]
Hey @mrtowel -- are you running on jdk 7 or 8?

**Comment by mrtowel** [comment]
java version "1.8.0_74"

**Comment by xian** [comment]
We're planning to spend some time optimizing performance in the next few weeks. If you're comfortable using [YJP](https://www.yourkit.com/java/profiler/), a profile of your test suite against 3.1 and 3.2.1 would be helpful!
