### ISSUE TITLE
Shadow ActionBar's implemented methods not called

### ISSUE THREAD

**Issue by GAumala** [robolectric/robolectric#2858]
### Description

I have created a shadow for the support action bar. My goal is to assert that my activity always calls `getSupportActionBar().setDisplayHomeAsUpEnabled(true)` on the `onCreate()` callback. I have implemented `setDisplayHomeAsUpEnabled` in this class, but it is never called.

### Steps to Reproduce
Here's my Shadow Action Bar:

```java

import android.support.v7.app.ActionBar;

import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;

@Implements(ActionBar.class)
public class ShadowActionBar {

    private boolean showHomeAsUp = false;

    public boolean getShowHomeAsUp() {
        return this.showHomeAsUp;
    }

    @Implementation
    void setDisplayHomeAsUpEnabled(boolean showHomeAsUp) {
        System.out.println("shadow");
        this.showHomeAsUp = showHomeAsUp;
    }
}
```

And the activity to test:

```java
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.Toolbar;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    }
}
```

Now if I run this test, the assertion fails. In fact the word "shadow" is never printed to console.

```java

import android.support.v7.app.AppCompatActivity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import org.robolectric.internal.ShadowExtractor;
import org.robolectric.util.ActivityController;

import static org.junit.Assert.*;

@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, shadows={ShadowActionBar.class})
public class ExampleUnitTest {
    @Test
    public void homeUpIsEnabled() throws Exception {
        ActivityController controller = Robolectric.buildActivity(MainActivity.class)
        .create().start().visible();
        AppCompatActivity act = (AppCompatActivity) controller.get();
        ShadowActionBar sab = (ShadowActionBar) ShadowExtractor
                  .extract(act.getSupportActionBar());

        assertEquals(sab.getShowHomeAsUp(), true);
    }
}
```

### Robolectric & Android Version

Robolectric version 3.2 targetting Android 23

**Comment by xian** [comment]
Since `ActionBar.setDisplayHomeAsUpEnabled()` is an abstract method, you'll need to shadow the concrete class which overrides it. Looks like that's `WindowDecorActionBar`?

**Comment by GAumala** [comment]
I debugged the test and it shows that the actual class is `ToolbarActionBar`, which is private. I guess I'm out of luck. Thanks for the help.

**Comment by xian** [comment]
It's actually possible to shadow a private class, just use `@Implements(className=…)`:

```java
@Implements(className="com.android.internal.app.ToolbarActionBar")
public class ShadowToolbarActionBar {
}
```

**Comment by GAumala** [comment]
That's pretty sick. The class name is actually `android.support.v7.app.ToolbarActionBar`. I do get the shadow object with `ShadowExtractor.shadow` but the implementation is still never called.

**Comment by jongerrish** [comment]
One quirk is you have to make the shadow methods public if you haven't
already done that?

**Comment by GAumala** [comment]
Yes, that's what I was missing, the `public` keyword in the implementation method. Thank you so much.
