### ISSUE TITLE
Move shadows into android.* packages

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2867]
- [ ] Don't instrument shadow classes even though they're under `android.*`
- [ ] Don't instrument shadow tests.
- [ ] Mass shadow move.
- [ ] Mass test move.
- [ ] Backwards compat interfaces.
- [ ] Tool for user migration.

**Comment by xian** [comment]
@jongerrish let's move this to 3.4 yeah?

**Comment by jongerrish** [comment]
Sounds good.

**Comment by utzcoz** [comment]
@hoisie Looks like we don't use `android.*` packages for Shadows now, so I will close it. If you think it is necessary on the future plan, feel free to reopen it.
