### ISSUE TITLE
The ShadowContextWrapper::setPackageName(String packageName) is removed in Roboletric 3.2.2?

### ISSUE THREAD

**Issue by supernewbie1979** [robolectric/robolectric#2883]
Hi, I have updated the Roboletric from 3.0 to 3.2.2 and I found the method "setPackageName" in
Shadows.shadowOf(RuntimeEnvironment.application).setPackageName("another_package")
cannot be found? This method is to used change the package name during the runtime.
Is there any substitute method for it? Thanks!

**Comment by jongerrish** [comment]
Yes, you can use

@Config(packageName = "my.package")

Out of interest, why are you needing to change the package name of your
application? It comes from your AndroidManifest.xml by default.

**Comment by supernewbie1979** [comment]
@jongerrish, thanks for the reply, actually I have already tried that and that did not help. I am not sure I use it in a right way, this is how my app looks like:
1. the app originally has the package name like, "com.app.name1" defined in AndroidManifest.xml and the source/resource structures are followed.
2. later on the package name has been changed e.g. "com.app.name2" and that is changed only during the build time, e.g. via the build.gradle and the AndroidManifest.xml and project structure are still using the  "com.app.name1".

In Roboletric 3.0, we do with the (packageName = "com.app.name1") in order to let the Roboletric to find the source/resource and in order to test the code, we do
@BeforeClass
public void setup() {
Shadows.shadowOf(RuntimeEnvironment.application).setPackageName("com.app.name2");
}

So do you think the @Config(packageName = "my.package") can make it work? Thanks!

**Comment by supernewbie1979** [comment]
Hello, anyone can help?

**Comment by jongerrish** [comment]
Use @Config(packageName = "...") Instead

**Comment by supernewbie1979** [comment]
Thanks, I seems was got confused by the ApplicationId and Package name, now seems fine now,.
