### ISSUE TITLE
Remove classes @Deprecated in 3.3

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2886]
- [x] `org.robolectric.util.ActivityController`
- [x] `org.robolectric.util.ContentProviderController`
- [x] `org.robolectric.util.FragmentController`
- [x] `org.robolectric.util.IntentServiceController`
- [x] `org.robolectric.util.ServiceController`
- [x] `org.robolectric.util.Transcript`

**Comment by CoderSpinoza** [comment]
@xian 

What could be the alternative for transcript?

**Comment by hoisie** [comment]
@CoderSpinoza I believe just using a plain List<String>
