### ISSUE TITLE
Typeface.createFromAsset creates identical instances

### ISSUE THREAD

**Issue by roelvandun** [robolectric/robolectric#2895]
### Description
When creating a Typeface from asset, it always returns the same instance.

### Steps to Reproduce
	@RunWith(RobolectricTestRunner.class)
	@Config(constants = BuildConfig.class, sdk = 25, shadows = ShadowMultiDex.class)
	public class CustomFontUnitTest {
	
		@Test
		public void typefacesShouldNotBeIdentical() throws Exception {
			AssetManager assets = RuntimeEnvironment.application.getAssets();
	
			Typeface avenirLight = Typeface.createFromAsset(assets, "fonts/avenir_lt_35_light.ttf");
			Typeface avenirLightOblique = Typeface.createFromAsset(assets, "fonts/avenir_lt_35_light_oblique.ttf");
	
			assertThat(avenirLight, not(equalTo(avenirLightOblique)));
		}
	}

### Robolectric & Android Version
    testCompile 'org.robolectric:robolectric:3.2.2'
    testCompile 'org.robolectric:shadows-multidex:3.2.2'
compileSdkVersion 25
buildToolsVersion "25.0.2"
classpath 'com.android.tools.build:gradle:2.2.3'

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
