### ISSUE TITLE
ShadowToast.reset() does not have the Resetter annotation

### ISSUE THREAD

**Issue by BenHenning** [robolectric/robolectric#2899]
### Description
ShadowToast.reset() does not have the Resetter annotation. Is this by design? If so, what's the proper way to reset toasts or does it happen automatically? It would be nice if ShadowToast's documentation was clearer on this.

### Robolectric & Android Version
Latest

**Comment by xian** [comment]
Is this fixed by #2901?

**Comment by jongerrish** [comment]
Yes, documentation added.
