### ISSUE TITLE
OOM Memory Leak

### ISSUE THREAD

**Issue by setiawanp** [robolectric/robolectric#2902]
### Description
My current project has around ~1000 tests. When running the tests on Jenkins CI, sometimes we get OOM. I looked the memory usage in CI server by using `free -m`, the memory consumed kept going up and up upon starting the tests. Also, I tried to look at the heap dump of the process and found out some leak suspects which mostly are from Robolectric package. Leak suspects that reported in my case:
- `org.robolectric.res.PackageResourceTable` = occupied around 50% of memory
- `org.robolectric.shadows.ShadowContextImpl$1` = occupied around 20% of memory

### Steps to Reproduce
Create lot of tests and run it.

### Robolectric & Android Version
Robolectric 3.2.2
Compiled using Android SDK 25
Run the tests using Android 21

**Comment by jongerrish** [comment]
Can you post your profiling data please?

**Comment by setiawanp** [comment]
@jongerrish I cannot upload the full heap dump since the size is pretty big, but I posted some screenshots of heap dump opened in Eclipse Memory Analyzer.

Leak suspects:
![image](https://cloud.githubusercontent.com/assets/9279303/22870191/3788f148-f1e0-11e6-83b5-1f9018b1677d.png)

Top dominator tree:
![image](https://cloud.githubusercontent.com/assets/9279303/22870205/57b4258c-f1e0-11e6-8fd3-5bb13de3bcc5.png)

Merge shortest path to GC (exclude weak references) for `org.robolectric.res.PackageResourceTable` shows Test worker thread as the object who holds strong reference to `PackageResourceTable`:
![image](https://cloud.githubusercontent.com/assets/9279303/22870220/754e1dbe-f1e0-11e6-98a5-04ce2832ab81.png)

Any idea how to solve this problem? Do ask me for more profiling data if you need it. Thanks!

**Comment by ankushg** [comment]
@setiawanp Did you end up figuring this out?

**Comment by mreichelt** [comment]
I chatted a bit with @hoisie, and thanks to his good advice: turns out this might not be a leak after all, because Robolectric caches SDK versions once they are used, and will create a full `AndroidSandbox` for each of them (which is expensive), to make subsequent tests faster.

So my last comment might not be that valid :)

**Comment by utzcoz** [comment]
@mreichelt's issue has been fixed, and previous comments are old. If anyone has similar issue with latest Robolectric, please search the open issue list, and comment to these newer issues for OOM or memory leak.
