### ISSUE TITLE
Robolectric test for Android MQTT Service fails with NPE

### ISSUE THREAD

**Issue by Lokesh-K-Haralakatta** [robolectric/robolectric#2903]
### Description
We need to use a easy test framework for our Android Client Library development which underlying uses [Paho MQTT Android Service](https://github.com/eclipse/paho.mqtt.android). While searching for test framework, I come across about Robolectric framework. It's very simple to develop and run unit tests for Android using Robolectric framework. Hence, we decided to stick to Robolectric framework.
While trying out simple unit tests to check the connection to a broker using Paho MQTT Android Service, I"m seeing Java NULL Pointer Exception during shadowing of MQTT Service. Below pasted is the exception details:

     Running com.example.activity.MainActivityTest
     Exception thrown while connecting to broker:
     java.lang.NullPointerException
	    at       org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:105)
	at org.robolectric.shadows.ShadowApplication$1.run(ShadowApplication.java:236)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:312)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:152)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:277)
	at org.robolectric.shadows.ShadowApplication.bindService(ShadowApplication.java:225)
	at org.robolectric.shadows.ShadowContextImpl.bindService(ShadowContextImpl.java:227)
	at android.app.ContextImpl.bindService(ContextImpl.java)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
	at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:420)
	at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:330)
	at com.example.activity.MainActivity.Connect(MainActivity.java:37)
	at com.example.activity.MainActivityTest.testConnect(MainActivityTest.java:17)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:498)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
       Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.512 sec <<< FAILURE!

### Steps to Reproduce
Here are Maven dependencies and plugins I have used:

         <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.robolectric</groupId>
            <artifactId>robolectric</artifactId>
            <version>3.1.4</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>android</artifactId>
            <version>4.1.1.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.android.service</artifactId>
            <version>1.0.2</version>
        </dependency>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <version>4.0.0</version>
                <configuration>
                    <sdk>
                        <platform>21</platform>
                    </sdk>
                    <undeployBeforeDeploy>true</undeployBeforeDeploy>
                </configuration>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <excludes>
                        <exclude>**/Test*.java</exclude>
                    </excludes>
                    <argLine>-Xmx1024m</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

Here is my sample connectivity code in Java:

    package com.example.activity;
 
    import android.app.Activity; 
    import android.os.Bundle;
    import com.example.R;
    import java.util.Properties;

    import org.eclipse.paho.client.mqttv3.MqttException;
    import org.eclipse.paho.android.service.MqttAndroidClient;
    import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
    import org.eclipse.paho.client.mqttv3.IMqttToken;
    import org.eclipse.paho.client.mqttv3.IMqttActionListener;
 
    public class MainActivity extends Activity {
        private Properties options = new Properties();
        private MqttAndroidClient mqttClient = null;
        private MqttConnectOptions mqttConnOptions = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);
    setTitle("MQTTClientTest");

    mqttClient = new MqttAndroidClient(getApplicationContext(),
                 "ssl://xxxxxxx.messaging.internetofthings.ibmcloud.com:8883",
                 "a:xxxxxx:androidApp");
    mqttConnOptions = new MqttConnectOptions();
    mqttConnOptions.setUserName("a-xxxxxx-xxxxxxxx");
    mqttConnOptions.setPassword("yyyyyyyyyyyyyyyyyyyyyy".toCharArray());
    mqttConnOptions.setCleanSession(true);

    }

    public boolean Connect(){
          try {
                  IMqttToken token = mqttClient.connect(mqttConnOptions);
                  token.setActionCallback(new IMqttActionListener() {
                      @Override
                      public void onSuccess(IMqttToken asyncActionToken) {
                      // We are connected
                      System.out.println("MQTTClient Connected to broker");
                      }
                      @Override
                      public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                        System.out.println("MQTTClient connecting to broker failed");
                      }
                  });
                  return true;
          }
          catch(Exception e){
                 System.out.println("Exception thrown while connecting to broker:");
                 e.printStackTrace();
                 return false;
          }
     }
    }

Here is corresponding test:

     package com.example.activity;

     import android.app.Activity;
     import org.junit.runner.RunWith;
     import org.robolectric.Robolectric;
     import org.robolectric.RobolectricTestRunner;
     import org.robolectric.annotation.Config;

     import static org.junit.Assert.assertTrue;

     @RunWith(RobolectricTestRunner.class)
     @Config(manifest="./src/main/AndroidManifest.xml")
     public class MainActivityTest {

     @org.junit.Test
     public void testConnect() throws Exception {
          assertTrue(Robolectric.buildActivity(MainActivity.class).create().get().Connect());
     }
    }

Here is contents of AndroidManifest.xml file:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          android:versionCode="2"
          android:versionName="1.0.0-SNAPSHOT"
          package="com.example">

    <uses-sdk android:minSdkVersion="21"
              android:targetSdkVersion="21"/>

    <application android:name=".DeckardApplication">
            <service android:name="org.eclipse.paho.android.service.MqttService" >
            </service>
        <activity android:name=".activity.MainActivity" android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

    </application>
</manifest> 

### Robolectric & Android Version

Robolectric versions used: 3.1.4 & 3.2.2

Android versions tried out: 21,22,23,24,25

I have also tried using Paho MQTT Android Service using direct Android Activity Application, it just works awesome. The issue is seen when I try to simulate the tests using Robolectric framework, this makes me to suspect the issue with Robolectric framework.

Can you please have a look at this issue and get back ASAP???

**Comment by jongerrish** [comment]
Can you debug into your test and find out why the NPE is thrown?

**Comment by Lokesh-K-Haralakatta** [comment]
I"m not familiar with Robolectric code, that's why I have shared my code here for someone who is already familiar with Robolectric code and suggest if anything wrong am I doing or to confirm is there any issue in using Robolectric framework for testing with Paho Android MQTT Service?

**Comment by Lokesh-K-Haralakatta** [comment]
Can someone please have a look at this issue? If you can look t the way I'm using the Robolectric and confirm whether it's right way to use with MQTT Android Service or not? What I'm suspecting is that MQTT Android Service has to be started in the background as part if the testing activity, looks like that service instance is null when we run the tests using Robolectric framework, as a result, I"m seeing NPE. Can someone please have a look and suggest any work around/alternative way to proceed  further?

**Comment by jongerrish** [comment]
It looks like you need to bind a service in your tests.

Try

MqttServiceBinder yourBinder = ....
String yourServiceName = "org.eclipse.paho.android.service.MqttService";

ShadowApplication shadowApplication = shadowOf(myApplication);
shadowApplication.setComponentNameAndServiceForBindService(yourServiceName, yourBinder);

There is an overloaded version of setComponentNameAndServiceForBindService() that takes an intent for filtering also if you need that.

**Comment by Lokesh-K-Haralakatta** [comment]
As per the above suggestion, I tried below steps:

     import static org.robolectric.Shadows.shadowOf; 
     import org.robolectric.shadows.ShadowApplication;

     public class MainActivityTest {
          ShadowApplication shadowApplication;
         ComponentName expectedComponentName;
         Binder expectedBinder;

    @org.junit.Before
    public void setup(){
        shadowApplication = shadowOf(RuntimeEnvironment.application);
        expectedComponentName = new ComponentName("org.eclipse.paho.android.service", "MqttService");
        expectedBinder = new Binder();
    }

    @org.junit.Test
    public void testConnect() throws Exception {
        shadowApplication.setComponentNameAndServiceForBindService(expectedComponentName, expectedBinder);

     //assertTrue(Robolectric.buildActivity(MainActivity.class).create().get().Connect());

       }
     }

The same kind of implementation I do see in the file - https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowApplicationTest.java for the test - bindServiceShouldCallOnServiceConnectedWithDefaultValues

But, when I go for compiling my test, I"m seeing the error message as below:

     MainActivityTest.java:[26,28] error: cannot access AccessibilityAction

Any clue about anything I'm not doing right?

**Comment by f8full** [comment]
I have the same issue.
I tried the solution proposed by @jongerrish which seems to be the robolectric way.
Unfortunately, MqttServiceBinder is a type private to the library, so I'm not sure how I'm supposed to instanciate it before placing it in the ShadowApplication. Could anyone offer me some guidance ?

**Comment by f8full** [comment]
As a side note, I also tried the solution offered by @Lokesh-K-Haralakatta but unfortunately things fall appart when the library tries to cast the received object to a MqttServiceBinder.

**Comment by f8full** [comment]
Could make it work with the following belly dancing (a violent one though)

In case it could serve to anyone :)

` Binder binder = null;

        MqttService servicetruc = new MqttService();


        try {
            Class<?> c = Class.forName("org.eclipse.paho.android.service.MqttServiceBinder");

            Constructor<?>[] constructors = c.getDeclaredConstructors();
            Constructor<?> constructor = constructors[0];//c.getDeclaredConstructor();

            constructor.setAccessible(true);

            binder = (Binder)constructor.newInstance(servicetruc);

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }


        ShadowApplication.getInstance().setComponentNameAndServiceForBindService(new ComponentName("org.eclipse.paho.android.service", "MqttService"), binder);`

**Comment by f8full** [comment]
Kotlin version works too

`
        var binder: Binder? = null

        val servicetruc = MqttService()


        try {
            val c = Class.forName("org.eclipse.paho.android.service.MqttServiceBinder")

            val constructors = c.declaredConstructors
            val constructor = constructors[0]//c.getDeclaredConstructor();

            constructor.isAccessible = true

            binder = constructor.newInstance(servicetruc) as Binder

        } catch (e: ClassNotFoundException) {
            e.printStackTrace()
        } catch (e: IllegalAccessException) {
            e.printStackTrace()
        } catch (e: InstantiationException) {
            e.printStackTrace()
        } catch (e: InvocationTargetException) {
            e.printStackTrace()
        }


        ShadowApplication.getInstance().setComponentNameAndServiceForBindService(ComponentName("org.eclipse.paho.android.service", "MqttService"), binder)`

**Comment by utzcoz** [comment]
Please following the above sample with the latest Robolectric version, and feel free to reopen this issue if it still exists.
