### ISSUE TITLE
Error: Failed to resolve: org.robolectric:robolectric:3.3-SNAPSHOT 

### ISSUE THREAD

**Issue by storix** [robolectric/robolectric#2929]
Hi,

According to the [README](https://github.com/robolectric/robolectric/blob/master/README.md) to use `Robolectric` snapshots we must make the following changes to our Gradle configuration:

```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    testCompile "org.robolectric:robolectric:3.3-SNAPSHOT"
}
```

However Gradle sync fails with this message:
`
Error: Failed to resolve: org.robolectric:robolectric:3.3-SNAPSHOT
` 

Is it due to the wrong configuration or the robolectric 3.3 snapshots are just currently unavailable?

**Comment by ChristianBecker** [comment]
Looking at the [Travis log for the latest commit](https://travis-ci.org/robolectric/robolectric/jobs/206058528#L5734) the upload of the artifacts results in a **401 Unauthorized**.

It seems that the stored credentials became invalid and needs to be updated.

**Comment by xian** [comment]
Looks to me like this is working again? Please reopen if you're still having trouble... thanks!

**Comment by Chikrix** [comment]
I'm still having this issue
