### ISSUE TITLE
Text color is wrong on Material Borderless button on SDK 23

### ISSUE THREAD

**Issue by mauricelam** [robolectric/robolectric#2940]
### Description
Text color is wrong on Material Borderless button.
It shows the color "ffff00ff" (Magenta??) on SDK 23, but the actual color shown on device is teal (#ff009688).

The test passes on SDK 21 but fails on SDK 23.

### Steps to Reproduce
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = {21, 23})
public class StyleTest {

    private Context mContext;

    @Before
    public void setUp() {
        mContext = new ContextThemeWrapper(application, android.R.style.Theme_Material_Light);
    }

    @Test
    public void testBorderlessButton() {
        Button button = new Button(
                mContext,
                Robolectric.buildAttributeSet()
                        .setStyleAttribute(
                                "@android:style/Widget.Material.Button.Borderless.Colored")
                        .build());
        assertEquals("ff009688", Integer.toHexString(button.getTextColors().getDefaultColor()));
    }
}
```
### Robolectric & Android Version
Robolectric 3.2.2
Android SDK 23

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
