### ISSUE TITLE
 java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles

### ISSUE THREAD

**Issue by caltseng** [robolectric/robolectric#2941]
### Description
There is an issue inflating one of our activities which has a custom view which contains the below. It seems like there's an issue attempting to retrieve the appropriate Android style. 

    <ProgressBar
        android:id="@+id/blocking_progress_bar"
        style="?android:attr/indeterminateProgressStyle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:indeterminate="true"
        android:interpolator="@android:interpolator/cycle" />

```
Caused by: java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles: [Style android:Theme_DeviceDefault (and parents) (forced), Style ols.microsoft.com.shiftr:Theme_Shiftr (and parents) (forced)]
	at org.robolectric.shadows.ShadowAssetManager.buildAttribute(ShadowAssetManager.java:463)
	at org.robolectric.shadows.ShadowAssetManager.attrsToTypedArray(ShadowAssetManager.java:532)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:213)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:532)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 45 more
```

### Steps to Reproduce

Test fails when trying to build the activity. This crashes in the .create() method, inside of the onCreateView() of the Activity. 

      mActivity = Robolectric.buildActivity(ActivityTest.class)
                .withIntent(intent)
                .create()
                .get();

### Robolectric & Android Version

Robolectric Version 3.1.4
Testing against Android API 23.

**Comment by caltseng** [comment]
According to the following thread we need to create and run a bunch of complex gradle scripts before running tests. Is this the only way to fix the problem? 

https://github.com/robolectric/robolectric/issues/1737#issuecomment-121318761

**Comment by raviagarwal7** [comment]
@xian we are also encountering this issue. is there a workaround until this is fixed?

using `style="@android:attr/indeterminateProgressStyle"` in the xml works.

**Comment by xian** [comment]
WIP branch: issue-2941

**Comment by caltseng** [comment]
FYI, the workaround is to change the style from style="?android:attr/indeterminateProgressStyle" to style="@android:style/Widget.ProgressBar.Small" . 

https://stackoverflow.com/questions/42636612/robolectric-runtimeexception-when-applying-android-style-shadowassetmanager-bu

**Comment by caltseng** [comment]
Hi, is there any update to this?

**Comment by caltseng** [comment]
If not, are there any workarounds to this problem without needing to change the UI?

**Comment by KevinLeigh** [comment]
@caltseng I have found a workaround to getting the exception `java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles`. 

Step 1) Create a `ShadowTheme` class extending `org.robolectric.shadows.ShadowResources.ShadowTheme`, as seen below:

```java
import android.content.res.Resources;
import android.content.res.TypedArray;
import android.util.AttributeSet;
import org.robolectric.Robolectric;
import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;
import org.robolectric.shadows.ShadowResources;

@Implements(value = Resources.Theme.class)
public class ShadowTheme extends ShadowResources.ShadowTheme {


    @Implementation
    @Override
    public TypedArray obtainStyledAttributes(AttributeSet set, int[] attrs, int defStyleAttr, int defStyleRes) {
        try {
            return super.obtainStyledAttributes(set, attrs, defStyleAttr, defStyleRes);
        } catch (Throwable err) {
            AttributeSet attributeSet = Robolectric.buildAttributeSet()
                    .addAttribute(android.R.attr.layout_width, "0dp")
                    .addAttribute(android.R.attr.layout_height, "0dp")
                    .build();
            return super.obtainStyledAttributes(attributeSet, attrs, defStyleAttr, defStyleRes);
        }
    }
}
``` 

Step 2: Add shadow to `@RunWith` shadows annotation value, as seen below:

```java
import android.os.Build;
import com.superbalist.android.BuildConfig;
import com.superbalist.android.test.shadow.ShadowTheme;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class,
        sdk = Build.VERSION_CODES.N_MR1,
        shadows = {ShadowTheme.class})
public class MyUnitTest {

}
```

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by caltseng** [comment]
Please note that the Windows bug is blocking us from upgrading to the newest version of Robolectric.

**Comment by jongerrish** [comment]
@caltseng + @KevinLeigh - The missing style is a legit error I think. You are actually missing a style in your theme. Note that with binary resources the behavior mirrors real Android (which blows up with this error in these cases).... legacy raw resources would just silently ignore the issue. Note also, that on Android, your Application Context only has the platform theme (even though you'd think setting <application theme="..."> would set the them on the application... it does not. So you'll need to use a Theme'd context.... either an Activity will work, or create a new ContextThemeWrapper(getApplicationContext(), R.style.YourTheme) or just set the theme on your application context programatically.

The windows bug we are aware of and I'll work on that today. Then you can switch to binary resources.

**Comment by KevinLeigh** [comment]
Thank you for the help @jongerrish, unfortunately tried every conceivable way and there was not success to resolve issue `java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles`. 

The workaround I posted here works for Robolectric 3 ->  https://github.com/robolectric/robolectric/issues/2941#issuecomment-366252320

With Robolectric 4, there has been changes which prevent `obtainStyledAttributes` from been overridden :/
