### ISSUE TITLE
onViewCreated() invoked after onCreateOptionsMenu() - Wrong lifecycle?

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#2943]
### Description
`FragmentTestUtil.startFragment()` invokes the (listed) methods on `android.app.Fragment` in this order:
1. `onCreateView()`
2. `onCreateOptionsMenu()`
3. `onViewCreated()`

Testing on a real device shows the following order (note, I have verified the real behavior with more code than in the example below):
1. `onCreateView()`
2. `onViewCreated()`
3. `onCreateOptionsMenu()`

I can't seem to find any official information about when "onViewCreated()" is invoked though. If this is asynchronously, in which case this bug may be invalid, or synchronous after onCreateView(). It seems to be synchronous.

### Steps to Reproduce

FooFragment.java:

    import android.app.Fragment;

    public class FooFragment extends Fragment {
   
       public boolean correctOrder;
 
       @Override
       public void onViewCreated(View view, Bundle savedInstanceState) {
           correctOrder = false;
        }

       @Override
       public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
            correctOrder = true;
       }

    }

FooFragmentTest.java:

    import static org.junit.Assert.assertTrue;
    import org.robolectric.util.FragmentTestUtil;
    import org.robolectric.RobolectricTestRunner;
    
    @RunWith(RobolectricTestRunner.class)
    public class FooFragmentTest {

       @Test
       public void correctOrder() {
          FooFragment fragment = new FooFragment();
          FragmentTestUtil.startFragment(fragment);

          assertTrue(fragment.correctOrder);
       }

    }

### Robolectric & Android Version
Verified on robolectric 3.1.4 and behavior recorded on a device running Android 6.0.1

**Comment by MGaetan89** [comment]
`FragmentTestUtil` is now deprecated. The recommended alternative is to use [`FragmentScenario`](https://developer.android.com/reference/androidx/fragment/app/testing/FragmentScenario).
