### ISSUE TITLE
Parameters tests with CustomRobolectricTestsRunner

### ISSUE THREAD

**Issue by JeromeSallmann** [robolectric/robolectric#2945]
Using Robolectric 3.1.2, I've defined a custom RobolectricTestRunner to check from where I'm launcher tests (work or own server). If I'm home, Robolectric gets its dependencies from Internet, otherwise, it works offline.

Anyway, I'm trying to implement Parameterized tests but, I have to RunWith a specific Runner and I would loose the part about my location. I'm not able to make my custom Runner extend Parameterized one.

Is there a way to use my Runner AND implement parameterized tests?

**Comment by jongerrish** [comment]
What part of the runner are you trying to extend? We're looking at ways of
avoiding subclassing by allowing the runner to be more configurable.

**Comment by JeromeSallmann** [comment]
Thanks you for your answer.

At the moment, I extended the getJarResolver() method to be able to choose if the Runner gets its dependencies from network or localy.

But I'm trying to implement Parameterized tests and, if I'm right, I have to use ParameterizedRobolectricTestsRunner. But if I do so, my getJarResolver() method won't be used anymore...

**Comment by jongerrish** [comment]
Can you use

-Drobolectric.offline=true
-Drobolectric.dependency.dir=/path/to/your/local/jars

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L86

?

**Comment by JeromeSallmann** [comment]
The problem is that, depending on the place from where I run tests, the configuration may change:
- If I ping my proxy server, then I'm at work, then I want to work offline
- If I don't ping the proxy, I'm outside, si I can use network to cet dependencies.

I want the configuration to change dynamically depending on the result if the previous test. So I can't use configuration like the one you suggest ..

**Comment by utzcoz** [comment]
@JeromeSallmann you can use the [ParameterizedRobolectricTestRunner](https://github.com/robolectric/robolectric/blob/4c9d755d2c1b64b8f8299fa99f3d7ba7cdc24505/robolectric/src/main/java/org/robolectric/ParameterizedRobolectricTestRunner.java#L42) to run parameterized tests with Robolectric. If it can't fit your need, you can file a new issue for new feature requests.
