### ISSUE TITLE
Is it possible to run Robolectric with @RunWith(Enclosed.class)?

### ISSUE THREAD

**Issue by sureshjoshi** [robolectric/robolectric#2946]
In some JUnit tests, I would like to use the test runner Enclosed for nice grouping of tests in a file (and do be able to use a clean whenXYZ, shouldABC naming convention).

Would it be possible to do the same in Robo? If so, how would I go about it? Do I need to create a custom test runner ala ParameterizedRobolectricTestRunner?

**Comment by noelmansour** [comment]
It's pretty much the same as using the Enclosed test runner on its own. You just have to add @RunWith(RobolectrTestRunner.class) to one of the static inner classes. Here's an example of how you would do this.

`@RunWith(Enclosed.class)
public class FooServiceTest {

  // All tests will need to extend this one
  @Ignore
  @RunWith(RobolectricTestRunner.class)
  @Config(constants = BuildConfig.class)
  public abstract static class GivenRobolectricContext {
    RobolectricApp app;
    ServiceController<FooService> serviceController;

    @Before
    public void givenRobolectricContext() {
      serviceController = Robolectric.buildService(FooService.class).create();
    }
  }

  public static class GivenFooService extends GivenRobolectricContext {
    // put your context specific tests here.
  }
 `

**Comment by philbrown-mdt** [comment]
Any update on this?

**Comment by utzcoz** [comment]
See https://github.com/robolectric/robolectric/pull/7873.
