### ISSUE TITLE
No such manifest file: build/intermediates/bundles/debug/AndroidManifest.xml

### ISSUE THREAD

**Issue by storix** [robolectric/robolectric#2949]
### Description
All Robolectric tests failed with:

`No such manifest file: build/intermediates/bundles/debug/AndroidManifest.xml`

Funny thing, I tried to specify the manifest in _robolectric.properties_ (as suggested in the [docs](http://robolectric.org/configuring/)). However, it does not replace the path to the AndroidManifest.xml but appends it to the default one instead. For example, if I specify:

`manifest=some/build/path/AndroidManifest.xml`

The resulting path then becomes 

`build/intermediates/bundles/debug/some/build/path/AndroidManifest.xml`

I don't know whether this is intended behavior or not.

### Steps to Reproduce

Just run any Robolectric test, it can be as simple as:

```Java
@RunWith(RobolectricTestRunner.class)
public class RoboTest {
    @Test
    public void test() {
    }
}
```

### Robolectric & Android Version
Robolectric 3.3
Android Studio version 2.3
Gradle version 3.3
Android Gradle plugin 2.3.0

**Comment by storix** [comment]
Ok, solved by removing all test configurations (from _Edit Configurations_ menu) and regenerating them again. Probably after updating to Android Studio 2.3 the JUnit working directory was reset for some reason.

**Comment by MyDogTom** [comment]
@storix In case you are Mac/Linux user make sure to do "Note for Linux and Mac Users" from http://robolectric.org/getting-started/

**Comment by caltseng** [comment]
Removing the configurations did not fix the issue for me.

**Comment by storix** [comment]
@caltseng For me it works. My current os is macOS Sierra so I've also set the Android JUnit default working directory to `$MODULE_DIR$` 

![screen shot 2017-03-09 at 12 13 24 am](https://cloud.githubusercontent.com/assets/10479469/23726586/6b906d88-045d-11e7-92a1-6c33af4e4fdf.png)

**Comment by jakub-g** [comment]
Thx @storix, that helped me fixing the issue.

I've previously found somewhere else an advice to set working directory to `$MODULE_DIR$` in `Defaults > Android JUnit` but it's not enough - you need to also set `$MODULE_DIR$` in all existing Android JUnit configurations (expand `Android JUnit` part of the tree).

**Comment by IgorGanapolsky** [comment]
@jakub-g That doesn't fix the error.

**Comment by hoisie** [comment]
This should also be resolved by https://github.com/robolectric/robolectric/pull/3366.

**Comment by calvarez-ov** [comment]
Using robolectric 3.5.1.

I'm having an issue trying to use a merged manifest instead of the default manifest. We're using a library that adds an activity to the manifest (card.io), and we need this activity to be present for one particular test.

I'm trying to specify it like this:
```
@Config(manifest = "build/intermediates/manifests/full/debug/AndroidManifest.xml")
```
This fails with:
```
Caused by: java.lang.IllegalArgumentException: couldn't find 'build/intermediates/manifests/full/debug/AndroidManifest.xml'
	at org.robolectric.internal.DefaultManifestFactory.resolveFile(DefaultManifestFactory.java:58)
	at org.robolectric.internal.DefaultManifestFactory.identify(DefaultManifestFactory.java:32)
	at org.robolectric.RobolectricTestRunner.getAppManifest(RobolectricTestRunner.java:402)
```

If I add a breakpoint in `resolveFile`, it looks like the classloader's root is `$ANDROID_HOME/platforms/android-27/data/res/`

I've checked the configuration of my unit test, as well as default junit configuration, and both include `$MODULE_DIR` for the working directory.

Not sure if this broke since the last comment here, or if I'm missing something on my end.
Will update here later if I find a solution.

**Comment by gantz0** [comment]
Hey , Could you change grdle classpath ?

 dependencies in build.gradle   -> com.android.tools.build:gradle:3.0.1

**Comment by jongerrish** [comment]
I'd strongly recommend anyone still struggling with this issue to upgrade
to Robolectric 4.0 and AS 3.2 as the integration is seemless.

**Comment by gantz0** [comment]
Could you change 


from('build/intermediates/bundles/release/')
->
from('build/intermediates/intermediate-jars/release/')


Gradle changed jar export folder.
