### ISSUE TITLE
addPackage creates a session and never finishes it

### ISSUE THREAD

**Issue by faoustin** [robolectric/robolectric#2950]
### Description
DefaultPackageManager.addPackage creates a PackageInstaller session and never finishes it, therefore leaving phantom non-opened sessions.

I think this method shouldn't create a session, or at least finish it.

**Comment by jongerrish** [comment]
I'm not sure what the on device experience is but I agree if a session is created using addPackage() then that session should be completed, as the semantics of the method are really addInstalledPackage()

**Comment by faoustin** [comment]
If addPackage() is called before the test, it doesn't matter whether we create the session since we remove (finish) it before the test starts.
If addPackage() is called during the test, then maybe we should create a session in case the application is listening for install sessions.
