### ISSUE TITLE
SupportFragmentController onSaveInstanceState

### ISSUE THREAD

**Issue by fondesa** [robolectric/robolectric#2979]
Hi, I'm using Robolectric 3.3.1 and Robolectric Shadows Support 3.3.1 to test a support `Fragment`.
Is it possible to add the method `saveInstanceState(Bundle)` on `SupportFragmentController`?
It could be very useful to test the configuration changes on support Fragments.

Example with `android.app.Fragment`:

```
Robolectric.buildFragment(TestFragment.class)
        .create()
        .saveInstanceState(new Bundle())
        .get();
```

Theoretical example with `android.support.v4.app.Fragment`:

```
SupportFragmentController.of(fragment)
        .create()
        /* This method is currently missing */
        .saveInstanceState(new Bundle())
        .get();
```

Thanks in advance.

**Comment by jongerrish** [comment]
Sounds good. Would you be willing to submit a PR and we'll get it in?

**Comment by Fondesa** [comment]
Yes, in the next days I'll do it.

**Comment by slott** [comment]
When I call *SupportFragmentTestUtil.startVisibleFragment* to start a dialog fragment the method *setupDialog* for that fragment isn't called. Is this a limitation or am I doing something wrong ?

I tried setting up the fragment the regular way using the getSupportFragmentManager and what not - and that works just fine. However I was under the impression it would be more correct to use the method *startVisibleFragment*.

**Comment by MGaetan89** [comment]
`SupportFragmentController` is no longer part of Robolectric's API. The recommended alternative is to use [`FragmentScenario`](https://developer.android.com/reference/androidx/fragment/app/testing/FragmentScenario).
