### ISSUE TITLE
ConstraintLayout fails to load under test

### ISSUE THREAD

**Issue by ross-eskridge-lenovo** [robolectric/robolectric#2981]
### Description
Activity setContentView fails under Robolectric test when using ConstraintLayout

> android.view.InflateException: XML file app/src/main/res/layout/my_activity.xml line #-1 (sorry, not yet implemented): For input string: "parent"

### Steps to Reproduce
Add an android.support.constraint.ConstraintLayout with at least one constraint to parent such as `app:layout_constraintTop_toTopOf="parent"`

### Robolectric & Android Version
Tested with Robolectric 3.2.2 and 3.3.1
Android version 24

**Comment by ross-eskridge-lenovo** [comment]
Any suggestions for workarounds on this issue?

**Comment by hoisie** [comment]
Do you have a sample app that demonstrates this issue? I have a small app that uses ConstraintLayout and haven't noticed any issues, even on Robolectric 3.3.1.

**Comment by ross-eskridge-lenovo** [comment]
I tried making a trivial sample, and it's working there, which means it's my problem, so closing this issue.  Thanks for the response.

**Comment by falaksevak** [comment]
@ross-eskridge-lenovo were you able to find out what the issue was? I'm running into the same issue now. I'm using a beta version of constraint layout
`compile 'com.android.support.constraint:constraint-layout:1.1.0-beta1'`
