### ISSUE TITLE
when run JUnit method , it always in download progress and download forever

### ISSUE THREAD

**Issue by cxMax** [robolectric/robolectric#2987]
### Description
I know The Chinese Great Wall may case this situation,but I run my JUnit test via VPN,it performs perfect to surf google or youtube. Is there any useful solution to slove this problem.I will be full of appreciate.  
run log is following:
```
Downloading: com/ibm/icu/icu4j/53.1/icu4j-53.1.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
Downloading: org/robolectric/android-all/5.0.0_r2-robolectric-1/android-all-5.0.0_r2-robolectric-1.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
Transferring 41864K from sonatype
Transferring 9482K from sonatype
```
### Steps to Reproduce
just run with JUnit method can reproduce
### Robolectric & Android Version
the following is my project dependence in build.gradle
```
    testCompile 'junit:junit:4.12'
    testCompile "org.mockito:mockito-core:1.9.5"
    testCompile "org.robolectric:robolectric:3.0"
    testCompile 'org.robolectric:robolectric-annotations:3.0'
    testCompile "org.robolectric:shadows-support-v4:3.0"
```

**Comment by kingargyle** [comment]
You could try downloading what you need Manually, and putting robolectric into offline mode.

http://codeblast.com/2015/05/13/using-robolectric-in-offline-mode/

You'll need to adjust that for your particular build system.  You could use a testCompile with a file based input to point to where you have the files stored that robolectric needs.

**Comment by cxMax** [comment]
@kingargyle thx a lot , i will try it

**Comment by xian** [comment]
Additional instructions here: http://robolectric.org/blog/2017/03/01/hermetic-builds/

Feel free to reopen if we can help further. Thanks!
