### ISSUE TITLE
Robolectric 3.3.1 depends on assertj-core 2.6.0 which is not compatible with Android

### ISSUE THREAD

**Issue by MathieuCalba** [robolectric/robolectric#2993]
I bumped my Robolectric version from 3.2.2 to 3.3.1 and my use of `org.assertj.core.api.Assertions.assertThat()` now fails: 
```
error: cannot access Path
class file for java.nio.file.Path not found
```

I use the version 1.1.1 of assertj-android, which depends on version 1.7.1 of assertj-core:
```
\--- com.squareup.assertj:assertj-android:1.1.1
     \--- org.assertj:assertj-core:1.7.1
```

When bumping Robolectric to 3.3.1, I have this tree of dependence:
```
+--- org.robolectric:robolectric:3.3.1
|    +--- org.robolectric:robolectric-annotations:3.3.1
|    |    \--- org.robolectric:shadow-api:3.3.1
|    +--- org.robolectric:robolectric-junit:3.3.1
|    |    +--- org.robolectric:robolectric-annotations:3.3.1 (*)
|    |    +--- org.robolectric:robolectric-sandbox:3.3.1
|    |    |    +--- org.robolectric:robolectric-annotations:3.3.1 (*)
|    |    |    +--- org.robolectric:robolectric-utils:3.3.1
|    |    |    |    +--- org.robolectric:robolectric-annotations:3.3.1 (*)
|    |    |    |    \--- org.assertj:assertj-core:2.6.0
```

robolectric-utils 3.3.1 depends on assertj-core 2.6.0, and it bumps my dependence for it in my project. Sadly assertj-core 2.X is not compatible with Android as it uses classes that are not available in Android (https://github.com/joel-costigliola/assertj-core/issues/345).

Is the dependency against assertj-core 2.6.0 vital? Or could it be downgraded to version 1.X?

**Comment by GisoBartels** [comment]
just replace all imports of `org.assertj.core.api.Assertions` with `org.assertj.core.api.Java6Assertions` and you're good to go.

**Comment by MathieuCalba** [comment]
@GisoBartels Thanks, I didn’t knew about these new classes.
