### ISSUE TITLE
Add ShadowBatteryManager

### ISSUE THREAD

**Issue by jklein24** [robolectric/robolectric#2999]
A shadow for android.os.BatteryManager would be useful not that it has the [getIntProperty](https://developer.android.com/reference/android/os/BatteryManager.html#getIntProperty(int)) and [getLongProperty](https://developer.android.com/reference/android/os/BatteryManager.html#getLongProperty(int)) functions.

See http://stackoverflow.com/questions/3291655/get-battery-level-and-state-in-android/38509011#38509011

**Comment by jongerrish** [comment]
Would you be up for submitting a PR? We'll get it merged asap.

**Comment by jklein24** [comment]
I'd be happy to, but admittedly, it's not super high on my priority list at the moment. I may be able to get to it by the end of the week, though.

**Comment by jklein24** [comment]
+cc @inkwellsiesta
