### ISSUE TITLE
Test case fails to execute for testing AndroidKeystore related code

### ISSUE THREAD

**Issue by sharvaniharan** [robolectric/robolectric#3001]
### Description
I have used java.security.KeyStore to encrypt the user's access token in my Android app. When I write a jUnit test case through Robolectric, I am getting the following error : java.security.KeyStoreException: AndroidKeyStore not found

### Robolectric & Android Version
Robolectric version : 3.0 Android : Lollipop

**Comment by xian** [comment]
Dupe of #1518.
