### ISSUE TITLE
Load sqlite native libraries in a more standard way.

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#3003]
robolectric-shadows/shadows-core/build.gradle packages up the native libraries inside shadows-core.jar

SQLiteLibraryLoader extracts the library from shadows-core.jar into a temp directory and configures the Java wrapper library using: SQLite.setLibraryPath(...)

Feels like this was done to make configuration easier for users, but perhaps a build system like gradle / Bazel automatically handles putting the native libraries on the java.library.path ?

**Comment by utzcoz** [comment]
Looks like this issue has been fixed by https://github.com/robolectric/robolectric/blob/c385f9c05de728f3c8424fa0f33247ccc3a51c1a/shadows/framework/src/main/java/org/robolectric/shadows/util/SQLiteLibraryLoader.java#L94.
