### ISSUE TITLE
3.4-SNAPSHOT does not exist

### ISSUE THREAD

**Issue by KenVanHoeylandt** [robolectric/robolectric#3009]
### Description

`README.md` describes:

```groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    testCompile "org.robolectric:robolectric:3.4-SNAPSHOT"
}
```

However, the snapshot is not available at https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/

**Comment by achakra21** [comment]
Is it still working for you..

**Comment by Chikrix** [comment]
Still not working for me

**Comment by KenVanHoeylandt** [comment]
Still not working for me.
The mentioned URL is the easiest way to see if it's been published: https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
