### ISSUE TITLE
Robolectric should attach a base context to ContextWrapper

### ISSUE THREAD

**Issue by johnheroy** [robolectric/robolectric#3010]
### Description

Robolectric doesn't attach a base context to ContextWrapper subclasses (like BackupAgent), so under test by default calling `#getApplicationContext` on these instances returns null and can cause an NPE depending on the implementation of the class under test.

**Comment by jongerrish** [comment]
The two ways of attaching a base context are through the public constructor or the protected attachBaseContext() method so it seems this is the responsibility of the user in general if you're creating your own context wrappers.

In the case you mention, BackupAgent, this _is_ wired up through the framework and Robolectric doesn't have any support for it. Is this specifically what you are looking for?
