### ISSUE TITLE
Documentation for custom shadows out of date

### ISSUE THREAD

**Issue by gauthamchandra** [robolectric/robolectric#3013]
### Description

Here in the [documentation for custom shadows](http://robolectric.org/custom-shadows/), when you want to access the custom shadow instance in a test, it is recommended to use `Shadows.shadowOf_()` but this method doesn't exist in Robolectric 3.3+

Instead, the correct method is `Shadow.extract(instance)`

Can we update the docs to reflect this?

**Comment by xian** [comment]
Fixed, thanks @gauthamchandra!

BTW, you can send pull requests directly at https://github.com/robolectric/robolectric.github.io
