### ISSUE TITLE
ShadowPendingIntent's equals and hashcode do not agree with each other.

### ISSUE THREAD

**Issue by jklein24** [robolectric/robolectric#3021]
ShadowPendingIntent's hashcode function makes the mistake of using the savedIntent's hashCode instead of filterHashCode. This breaks anything which tests hashCode equality.

**Comment by jklein24** [comment]
I'll fix this.

**Comment by jfarfel** [comment]
Could we fix this at the same time?
https://github.com/robolectric/robolectric/issues/2117 (PendingIntent doesn't equals() itself)
