### ISSUE TITLE
How to setup test in multiple modules

### ISSUE THREAD

**Issue by rantianhua** [robolectric/robolectric#3029]
### Description
In my project, I have many modules. I have a custom Application on app module(main module), and many initial operations in it. Now, I want to setup test in a sub module named f_login, however, so many objects have not been initialized when run the test, in this case, it's very hard to continue my test. So, if I have many modules, how can I build a test environment for every module?

### Robolectric & Android Version
Robolectric 3.3.2
Android sdk = 25

**Comment by forntoh** [comment]
How do I set it up?
I have many modules and I want them to use api 33 instead of 34 which is currently not supported.
I added the file to the root of the project but it didn't work.
