### ISSUE TITLE
mock rest api using robolectric

### ISSUE THREAD

**Issue by pvrkchaitanya** [robolectric/robolectric#3035]
How could I mock web service request and response eg : retrofit using robolectric. I am using gradle dependency version 3.3.2.

**Comment by nikhilbalyan** [comment]
@pvrkchaitanya there are a lot of tools like okhttp, hoverfly and wiremock this is not an issue you better close this one

**Comment by utzcoz** [comment]
@pvrkchaitanya Retrofit has its mock server: https://github.com/square/retrofit/tree/master/retrofit-mock. IMO, it might be the best choice to mock API for Retrofit.
