### ISSUE TITLE
Static fields are reset

### ISSUE THREAD

**Issue by vRallev** [robolectric/robolectric#3048]
I have a custom runner to setup some classes before a test rule or anything else is called:
```kotlin
class MyRobolectricTestRunner(clazz: Class<*>) : RobolectricTestRunner(clazz) {
    override fun run(notifier: RunNotifier?) {
        logger.before()
        super.run(notifier)
        logger.after()
    }
}

// in logger
fun before() {
    ShadowLog.stream = System.out
    verbose = true
}
```

This works fine with normal JUnit tests, but with Robolectric those static fields are overwritten when the tests run. `stream` is null and `verbose` false again.

I didn't find a workaround. This sounds like some black magic to me :)

**Comment by jongerrish** [comment]
Robolectric cleanup static state of shadows / android framework in its @Resetter methods. This is WAI
