### ISSUE TITLE
ShadowMediaPlayer does not correctly handle instantiation off the UI thread

### ISSUE THREAD

**Issue by groakley** [robolectric/robolectric#3050]
### Description

Instantiating MediaPlayer from a from a thread that does not have a prepared Looper will cause a "java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()" to be thrown from ShadowMediaPlayer: https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowMediaPlayer.java#L540

The real MediaPlayer can be created from a thread without a prepared Looper without crashing; it will silently use the main thread Looper for posting events. Presumably the shadow should match this behavior.

**Comment by jongerrish** [comment]
Hey Grant,

That sounds accurate, would you be up for submitting a pull request?

J.

**Comment by hoisie** [comment]
Do you have some sample code that demonstrates this problem?

**Comment by groakley** [comment]
This is fixed by https://github.com/robolectric/robolectric/pull/3791
