### ISSUE TITLE
Performance Degradation by an average 10% when Upgrading from Robolectric 3.0 to 3.3.2

### ISSUE THREAD

**Issue by hazems** [robolectric/robolectric#3056]
### Description
Unfortunately, it has a slight performance degradation from Robolectric 3.0, around 10% performance degradation.

### Steps to Reproduce
Unfortunately, it has a slight performance degradation from Robolectric 3.0, around 10% performance degradation.

For example, running the following gradle command:
```
./gradlew :myproject:clean :myproject:test
```

1. First Run: Performance of the test degrades 12.5%:
- With Robolectric 3.3.2: Total time to run tests: 7 mins 50.634 secs (470 seconds)
- With Robolectric 3.0: Total time to run tests: 6 mins 58.988 secs (418 seconds)

2. Second Run: Performance of the test degrades 9%:
- With Robolectric 3.3.2: Total time to run tests: 7 mins 28.919 secs (449 seconds)
-  With Robolectric 3.0: Total time to run tests: 6 mins 52.602 secs (412 seconds)

### Robolectric & Android Version
Upgrading from Robolectric 3.0 to Robolectric 3.3.2 on target SDK 25.

Can you please advice? Are there any recommendations to speedup Robolectric 3.3.2 tests.

Thanks

**Comment by jongerrish** [comment]
Robolectric 4.0 and binary resource mode should improve test start up time and memory consumption significantly, can you try that and reopen if its still an issue
