### ISSUE TITLE
Setting locale using `Config(qualifiers='zh')` doesn't seem to work.

### ISSUE THREAD

**Issue by raviagarwal7** [robolectric/robolectric#3066]
### Description
As mentioned in http://robolectric.org/using-qualifiers/, setting `Config(qualifiers='zh')` should change the default locale to `zh` inside the test method block, but it is still stays as `en-US`.

### Steps to Reproduce
Use the snippet below:
```
@Config(qualifiers="zh", sdk=21)
@Test
public void test_qualifier() {
    Java6Assertions.assertThat(Locale.getDefault().toLanguageTag()).isEqualTo("zh");
}
```
Failure stacktrace:
```
FAILURE com.app.Test test_qualifier: expected:<"[zh]"> but was:<"[en-US]">
org.junit.ComparisonFailure: expected:<"[zh]"> but was:<"[en-US]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

### Robolectric & Android Version
Robolectric version 3.3.2
Android Version 21
Using buck runner for running tests

**Comment by raviagarwal7** [comment]
as a workaround we are setting the locale in the base test class
```
class TestBase {

    @Nullable private Locale mOldLocale;

    @Before
    public void setupGlobal() {
        String qualifiers = RuntimeEnvironment.getQualifiers();

        // qualifiers can start with 'v2x-' or 'v1x-' which don't represent a locale
        if (qualifiers.contains('-')
                && !qualifiers.startsWith("v2")
                && !qualifiers.startsWith("v1")) {

            String language = qualifiers.split('-')[0];
            mOldLocale = Locale.getDefault();
            Locale.setDefault(new Locale(language));
        }
    }

    @After
    public void tearDownGlobal() {
        if (mOldLocale != null) {
            Locale.setDefault(mOldLocale);
        }
    }
}
```

cc @xian

**Comment by jongerrish** [comment]
I think the right fix is to have Qualifiers extract the local, then set the
local based on that in ParallelUniverse. You can see code that does similar
stuff already for values from the qualifiers.

Would you be up for submitting a pull request?

**Comment by raviagarwal7** [comment]
thanks @jongerrish will create a pull request. 
wasn't sure if I was using the qualifiers correctly as the docs mentioned that it should work - http://robolectric.org/using-qualifiers/

**Comment by jongerrish** [comment]
Yeah, it kinda works... At least for resource selection, but you've found a
gap in that it should also set locale too.

Thanks 😃
