### ISSUE TITLE
Robolectric without JUnit (enhancement)

### ISSUE THREAD

**Issue by spifd** [robolectric/robolectric#3079]
Hi,
Would it be possible to use Robolectric from Java without JUnit?

My use case: I have an Android SDK for my product connected to a backend server. It would be very convenient to simulate this SDK on backend without a device and integrate that SDK in other tools in pure Java. For instance, I'd like to run this Android code as server-side validation/benchmarking tool, not in JUnit test suites.

I've actually tricked ParameterizedRobolectricTestRunner and used it as a wrapper in Java using JUnitCore but it is not very convenient and has serious limitations. 

Any suggestion?

Cheers,
Fab

**Comment by utzcoz** [comment]
@spifd I think is is not easy to run Robolectric without JUnit as the most common used Robolectric test runner is written in JUnit architecture. If you want to run Robolectric with other test suite or tools, you can check https://github.com/utzcoz/robolectric-with-junitparams or the implementation of `ParameterizedRobolectricTestRunner` to implement a new runner with other test tools but is compatible with Robolectric's critical process.
