### ISSUE TITLE
Allow creating test suites to load Robolectric classes only once

### ISSUE THREAD

**Issue by xgouchet** [robolectric/robolectric#3083]
### Description

In our project, we have hundreds of test classes using either the `RobolectricTestRunner` or `ParameterizedRobolectricTestRunner`. 

We run all tests on each new commit to ensure no regression is introduced. Our problem is that each test has a different Runner, meaning the first test always takes up several seconds (between 1 and 7 seconds) to setup the class loader and resources. 

Since (almost) all the tests share the same configuration (same sdk level, ...), it would be nice if we could create a test suite that would load the Robolectric dependencies only once and then call some simplified runners, which would greatly reduce our test time. 

### Robolectric & Android Version

Robolectric version : 3.3.2
Android Build Tools : 25.0.2
Gradle 3.4.1

**Comment by jongerrish** [comment]
Hey Xavier,

Robolectric does cache both the framework resources and the application
resources, so the while the first test does have an initial cost to parse
these, subsequent tests should be fast. Is this not what you are seeing?

Jonathan

**Comment by xgouchet** [comment]
My bad, it seems like there was some issues with my config, and it used an older version of robolectric.
