### ISSUE TITLE
RoboMenuItem doesn't support setting a title from a resId correctly.

### ISSUE THREAD

**Issue by tmtrademarked** [robolectric/robolectric#3085]
### Description

RoboMenuItem.setTitle(int resId) doesn't set the title - instead, it just returns this. Instead, it feels like it should, well, set the title using the stored context.

### Steps to Reproduce

Write a test that sets a title on a menu item, and observe it is not actually set. :-)

### Robolectric & Android Version

NA - the implementation is clearly visible here: https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/fakes/RoboMenuItem.java#L79

**Comment by MGaetan89** [comment]
@tmtrademarked This is now fixed via #9822. It will be available in a few minutes in a snapshot, or in a future release of Robolectric.
