### ISSUE TITLE
Not able to mock static methods and return a mock

### ISSUE THREAD

**Issue by ceduliocezar** [robolectric/robolectric#3115]
### Description
I was playing with **roboeletric 3.3.2** and wondering if would be possible to 'inject/mock' an controller while testing my activity. What first came to my mind was, have an static method on a 'injector' and then inside my tests mock the static call and return a mock object and on would be possible to mock other things.

However I'm getting this error when I try:

```
org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);

Also, this error might show up because:
1. you stub either of: final/private/equals()/hashCode() methods.
   Those methods *cannot* be stubbed/verified.
   Mocking methods declared on non-public parent classes is not supported.
2. inside when() you don't call method on mock but on some other object.
```

Using dependencies as [requested here](https://github.com/robolectric/robolectric/wiki/Using-PowerMock)

```
    testCompile "org.robolectric:robolectric:3.3.2"
    testCompile 'junit:junit:4.12'
    testCompile "org.powermock:powermock-module-junit4:1.6.4"
    testCompile "org.powermock:powermock-module-junit4-rule:1.6.4"
    testCompile "org.powermock:powermock-api-mockito:1.6.4"
    testCompile "org.powermock:powermock-classloading-xstream:1.6.4"
```

Activity code
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        dummyTextGenerator = DummyInjector.injectTextGenerator();
    }

```

Test code:

```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest(DummyInjector.class)
public class MainActivityTest {


    @Mock
    DummyTextGenerator dummyTextGenerator;

    @Before
    public void setUp() throws Exception {
        mockStatic(DummyInjector.class);
        when(DummyInjector.injectTextGenerator()).thenReturn(dummyTextGenerator);
    }

    @Test
    public void test_button_clicked() throws Exception {

        String mockedText = "MOCKED";

        when(dummyTextGenerator.getText()).thenReturn(mockedText);

        MainActivity activity = Robolectric.setupActivity(MainActivity.class);

        activity.findViewById(R.id.bt).performClick();

        assertEquals(mockedText, ((TextView) activity.findViewById(R.id.tv)).getText().toString());

    }
}
```

**If testing a regular class with PowerMockRunner.class  and the following dependencies it works.**

```
    testCompile 'junit:junit:4.12'
    testCompile 'org.greenrobot:eventbus:3.0.0'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    testCompile 'org.mockito:mockito-core:2.8.9'
    testCompile 'org.powermock:powermock-api-mockito2:1.7.0RC4'
    testCompile 'org.powermock:powermock-module-junit4-rule-agent:1.7.0RC4'
    testCompile 'org.powermock:powermock-module-junit4-rule:1.7.0RC4'
    testCompile 'org.powermock:powermock-module-junit4:1.7.0RC4'
```

**Comment by ceduliocezar** [comment]
This same error happens with PowerMockRunner if mockStatic(DummyInjector.class); do not gets called, however this is not the case.

This really looks like a problem, or am I missing something?

**Comment by mzelzoghbi** [comment]
any updates on this ?

**Comment by bkparse** [comment]
Bump getting the same error

**Comment by xian** [comment]
Not too familiar with PowerMock but if this is all code that you control, wouldn't it be more straightforward to just inject a test double using plain old Java testing patterns rather than mocking statics?

**Comment by cynthux** [comment]
I'm getting the same error.

**Comment by ceduliocezar** [comment]
@xian thanks for your answer, that would be an option.

But when I created this issue, was to clarify if this is an expected behavior, lac of coviguration, bug or an edge not covered yet.

**Comment by dmeng** [comment]
@ceduliocezar This is expected behavior. As per PowerMock's [docs](https://github.com/powermock/powermock/wiki/mockstatic):

> With PowerMock it's possible to expect the call to IdGenerator.generateNewId() just as you would with any other method using EasyMock once you've told PowerMock to prepare the IdGenerator class for testing. You do this by adding an annotation to the class-level of test case. This is simply done be using @PrepareForTest(IdGenerator.class). You also need to tell JUnit to execute the test using PowerMock which is done by using @RunWith(PowerMockRunner.class). Without these two annotations the test will fail.

They added [PowerMockRule](https://github.com/powermock/powermock/wiki/PowerMockRule) in 1.4 if you *really* need to mock statics while a runner other than PowerMockRunner, but I second @xian's question about test doubles.

**Comment by ceduliocezar** [comment]
Thanks @dmeng . 

This is what I was looking for.
