### ISSUE TITLE
Powermock conflicting Shadow Classes

### ISSUE THREAD

**Issue by mohib-irshad-10p** [robolectric/robolectric#3119]
Initially I would like to thank robolectric team for putting so much effort in fixing powermock compatibility for us. However, it seems like as soon as you put PowermockRule, shadow classes stops working. It doesn't matter if they are from robolectric's own shadow classes or custom ones, they stops working.

```
@RunWith( RobolectricTestRunner.class )
@Config(constants = BuildConfig.class, sdk = 21, shadows = { ShadowEventLoggingHelper.class, ShadowDeviceUtils.class })
@PrepareForTest( LocationManager.class )
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
public class TestingTests {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    @Test
    public void tempTest() throws Exception {
        GeofenceTable geofenceTable = GeofenceTable.getInstance();
        geofenceTable.addGeofence( Geofences.getGeofence() );

        assertTrue( geofenceTable.getGeofence().size() > 0);
    }

}
```
Exception produced by this code is as follows:
[exception.txt](https://github.com/robolectric/robolectric/files/1025378/exception.txt)

Also please note that it doesn't seem that it is an issue of Shadow classes of SQLite since not even custom shadow classes work. Just by removing the `PowerMockRule`, it starts working perfectly but now I can't mock static classes anymore which is my requirement. 

Second method mentioned on [documentation](https://github.com/robolectric/robolectric/wiki/Using-PowerMock) doesn't work either. By running with `PowerMockRunner` and setting `RobolectricTestRunner `as `PowerMockRunnerDelegate`, now shadow classes work but mocking static classes is disabled.

Below is the code which is using `PowerMockRunnerDelegate` :

```
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21, shadows = { ShadowEventLoggingHelper.class, ShadowDeviceUtils.class })
@PrepareForTest( LocationManager.class )
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
public class TestingTests {

    @Test
    public void tempTest() throws Exception {
        
        LocationManager locationManager = mock( LocationManager.class );
        PowerMockito.mockStatic( LocationManager.class );
        PowerMockito.when( LocationManager.getInstance() ).thenReturn( locationManager );
        
        GeofenceTable geofenceTable = GeofenceTable.getInstance();
        geofenceTable.addOrUpdateGeofence( Geofences.getGeofence() );

        assertTrue( geofenceTable.getGeofence().size() > 0);
    }

}

```
and following is exception produced by it:
[exception-powermockrunner.txt](https://github.com/robolectric/robolectric/files/1025206/exception-powermockrunner.txt)

It seems like a bug to me but if there is an issue in my implementation, please let me know. I'll be very grateful if someone could help me with this since there is not much documentation available.

I am using Robolectric version: 3.3.2 & PowerMock version 1.6.6

**Comment by Ardesco** [comment]
Seeing the same thing here

**Comment by ckitterl** [comment]
I have had the sample problem. Do you find way to walk around this issue.

I am using robolectric version 4.1 & powerMock version 1.7.4

**Comment by utzcoz** [comment]
@mohib-irshad-10p @ckitterl @Ardesco Please read the documentation(https://github.com/robolectric/robolectric/wiki/Using-PowerMock) about integrating Powermock with latest Robolectric to check whether this documentation can fix these issues. And feel free to reopen this issue if these problems still exist. Thanks.
