### ISSUE TITLE
Robolectric Config qualifiers for Plurals does not match pure android 

### ISSUE THREAD

**Issue by xMickeymikex** [robolectric/robolectric#3126]
Hello,

I have encountered problem while trying to test my plurals with robolectric.
These are important code parts:

`<plurals name="channel_package_channel_number">`
`        <item quantity="one">%d kanał</item>`
`        <item quantity="few">%d kanały</item>`
`        <item quantity="other">%d kanałów</item>`
` </plurals>`

`@RunWith(RobolectricTestRunner::class)`
`@Config(constants = BuildConfig::class, qualifiers = "pl")`
`class PluralsTest {`
`private val activity = Robolectric.setupActivity(Activity::class.java)`
`@Test`
`fun properSuffixForZero() {`
`       val string = activity.resources
                .getQuantityString(R.plurals.channel_package_channel_number, 0, 0)`

`        assertThat(string, `is`("0 kanałów"))`
`    }`
`}`

The result is "0 kanały" instead of "0 kanałów", but when i run it on real device the plurals work just fine.

Robolectric version: 3.4-rc2

**Comment by tomasznajda** [comment]
Hey! Any update of this issue?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
