### ISSUE TITLE
How to custom shadow for a android Class with private constructor 

### ISSUE THREAD

**Issue by yangxinQA** [robolectric/robolectric#3127]
### Description
In my Test case ,I need to custom shadow for TextUtils.class ,well ,the TextUtils is a class with private constructor . like this :   private TextUtils() { /* cannot be instantiated */ } 
when i read the guides ,i found a typically custom shadow ,should be used like this 
ShadowExtractor.extract(object)，but how to get a TextUtil`s object (it has a private constructor..)?
### Robolectric & Android Version
robolectric 3.3

**Comment by yangxinQA** [comment]
And i want to konw about what type of class can not be mock by robolectric`s shadow ?who konws the contraints of shadow?

**Comment by hoisie** [comment]
All methods in in TextUtils are pure static functions. The class itself maintains no state. Why would you want to create a custom shadow for it?
