### ISSUE TITLE
Robolectric doing nothing on setLayerType calls

### ISSUE THREAD

**Issue by dalewking** [robolectric/robolectric#3139]
### Description
Trying to migrate to Robolectric 3. We have a test to verify that on certain versions of Android we set the layer type to Software on a web view to work around a problem on KitKat. But it appears that Robolectric 3 does nothing when you call setLayerType including not updating the value for mLayerType that is returned in getLayerType

### Steps to Reproduce
Create a view, call setLayerType to set to software and verify that getLayerType is not changing.

### Robolectric & Android Version
3.2.2, KitKat

**Comment by jongerrish** [comment]
Hey Dale,

Sounds like a simple fix, would you be interested in sending us a PR? I'll
be happy to help you get it merged!

J

**Comment by dalewking** [comment]
I no longer work at the place where this was an issue, so I don't have the motivation to fix it

**Comment by utzcoz** [comment]
Close it as reporter didn't need it anymore.
