### ISSUE TITLE
Memory leak on static ThreadLocal of android.support.v7.widget.GapWorker

### ISSUE THREAD

**Issue by matthewhubblerose** [robolectric/robolectric#3181]
### Description

There seems to be a memory leak through the `sGapWorker` static field of `android.support.v7.widget.GapWorker`:
```
static final ThreadLocal<GapWorker> sGapWorker = new ThreadLocal<>();
```

That field holds onto a list of recycler views which have strong references to the application objects, so if it doesn't get reset between tests you end up leaking application instances.

Adding the following code to my test tear down method caused a significant reduction in retained memory:

```
Class clazz = ReflectionHelpers.loadClass(getClass().getClassLoader(), "android.support.v7.widget.GapWorker");
ThreadLocal<?> gapWorkerThreadLocal = ReflectionHelpers.getStaticField(clazz, "sGapWorker");
if (gapWorkerThreadLocal != null) {
    gapWorkerThreadLocal.remove();
}
ReflectionHelpers.setStaticField(clazz, "sGapWorker", new ThreadLocal<>());
```

### Steps to Reproduce

You'll need a test running on an activity which uses a `RecyclerView`

### Robolectric & Android Version

Robolectric - 3.4-rc2
Android Appcompat v7 - 25.2.0

**Comment by utzcoz** [comment]
@matthewhubblerose Please try the latest Robolectric to check whether this issue still exists. The attached Robolectric version is too old, and the team doesn't maintain it anymore. Feel free to reopen this issue if the latest Robolectric version still has this issue. Thanks.
