### ISSUE TITLE
Robolectric project should build with Android Studio 3.0

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#3184]
This means we'll build our own project using the same tools as the majority of our users.

1) We are able to test out the new build system API (and keep it from breaking) with future updates.
2) Can process + validate our own resources through the build tools for more accuracy (aapt) and remove build-resources.rb
3) Can use new gmaven repositories (and remove install-dependencies.sh)

**Comment by harishrpatel** [comment]
We just started a new project where we want to use it with Kotlin as well. So, if possible please address building project with src and test src both in Kotlin. Thanks.

**Comment by elye** [comment]
The test failure of Robolectric is stopping us progressing. We use Instant App, hence we need Android Studio 3.0. If Robolectric not supporting Android Studio 3.0 soon, we might have no choice but to abandon it.

**Comment by jongerrish** [comment]
@elye - Can you try the new build system integration that works with AS3.0+ instructions here:-

https://github.com/robolectric/robolectric/issues/3169

Let me know if that works. There were some other issues with resources in AS3.0 so if that doesn't work I'll check back with the AS team

**Comment by elye** [comment]
It is not working still. :(

**Comment by jongerrish** [comment]
How so? When you set the test options and remove the @Config(constants =
... what happens?

**Comment by elye** [comment]
Yes, it can't access the resource information

**Comment by jongerrish** [comment]
What version / build number of AS do you have?

What version of Robolectric?

Any errors?

Console log?

**Comment by elye** [comment]
It errors out as below whenever it tries to get resources

```
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0f0044 in packages [android, org.robolectric.default]

	at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:868)
	at org.robolectric.shadows.ShadowAssetManager.resolveResourceValue(ShadowAssetManager.java:676)
	at org.robolectric.shadows.ShadowAssetManager.resolve(ShadowAssetManager.java:636)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:630)
	at org.robolectric.shadows.ShadowAssetManager.getResourceTextArray(ShadowAssetManager.java:281)
	at org.robolectric.shadows.ShadowAssetManager.getResourceStringArray(ShadowAssetManager.java:238)
	at android.content.res.AssetManager.getResourceStringArray(AssetManager.java)
	at android.content.res.Resources.getStringArray(Resources.java:446)
```

I use Robolectric 3.2.2. Android Studio 3.0 (Canary 5), gradle-4.1-milestone-1-all.

**Comment by jongerrish** [comment]
The build system API was not introduced until Robolectric 3.3 so you'll need to upgrade to have that work.

**Comment by jongerrish** [comment]
You'll also need to disable aapt2 if you are writing tests in an application subproject, a library subproject will work just fine however.

**Comment by jongerrish** [comment]
In progress (currently failing though) https://github.com/robolectric/robolectric/pull/3217

**Comment by elye** [comment]
Moving to 3.3 is painful. Face the issue as per
https://stackoverflow.com/questions/41787774/class-file-for-java-nio-file-path-not-found

Have to manually change all
`import static org.assertj.core.api.Assertions.assertThat;`
to
`import static org.assertj.core.api.Java6Assertions.assertThat;`

**Comment by IgorGanapolsky** [comment]
What is the fix for **Resources$NotFoundException** error?  I am using AS 3.0 Beta3, com.android.tools.build:gradle:2.2.3

**Comment by jongerrish** [comment]
I think you want the latest version of the build tools. i.e: 3.0-beta4?

**Comment by realdeadfish** [comment]
Not sure if this is still valid, but the dreaded `android.content.res.Resources$NotFoundException` do no longer pop up even with Aapt2 enabled by default with Robolectric 3.8.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
