### ISSUE TITLE
signature-polymorphic method called without --min-sdk-version >= 26

### ISSUE THREAD

**Issue by Sebstyless** [robolectric/robolectric#3190]
### Description
I want to use Robolectric to do some Instrumentation Tests. 

Everything is like in the 'Get Started' section:

>LiveFeedFragmentTest.kt

```
@RunWith(RobolectricTestRunner::class)
@Config(constants = BuildConfig::class)
class LiveFeedFragmentTest {
    @Test
    fun fragmentWasCreated() {
        val liveFeedFragment: LiveFeedFragment = LiveFeedFragment.newInstance()
        
        SupportFragmentTestUtil.startFragment(liveFeedFragment)
        
        Assert.assertNotNull(liveFeedFragment)
    }
}
```

>live-feed module build.gradle

```
dependencies {
    //INSTRUMENTATION TESTING
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestImplementation "org.robolectric:robolectric:$robolectric_version"
    androidTestImplementation "org.robolectric:shadows-support-v4:$robolectric_version"

    //UNIT TESTING
    testImplementation 'junit:junit:4.12'

    //GENERAL
    //--APPCOMPAT
    implementation 'com.android.support:appcompat-v7:25.4.0'

    //--KOTLIN
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"

    //--LIFECYCLE
    implementation "android.arch.lifecycle:runtime:$arch_version"
    implementation "android.arch.lifecycle:extensions:$arch_version"
    annotationProcessor "android.arch.lifecycle:compiler:$arch_version"

    //CONSTRAINT LAYOUT
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
}
```

But when I try running the test I get this error

> Unable to pre-dex 'C:\Users\{username_here}\.gradle\caches\modules-2\files-2.1\org.robolectric\robolectric-sandbox\3.3.2\4d968978679b572e5993b3eea35cae88268f44ee\robolectric-sandbox-3.3.2.jar' to 'F:\{path_here}\live-feed\build\intermediates\transforms\dexBuilder\androidTest\debug\13.jar'
AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: signature-polymorphic method called without --min-sdk-version \u003e\u003d 26","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\nsignature-polymorphic method called without --min-sdk-version \u003e\u003d 26\n","tool":"Dex"}
AGPBI: {"kind":"error","text":"com.android.dx.cf.code.SimException: signature-polymorphic method called without --min-sdk-version \u003e\u003d 26","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilder.processOutputs(DexArchiveBuilder.java:110)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilder.convert(DexArchiveBuilder.java:91)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.lambda$cacheMissAction$0(DexArchiveBuilderTransformCallable.java:236)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.lambda$createFile$1(FileCache.java:260)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.lambda$null$5(FileCache.java:443)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.write(SynchronizedFile.java:232)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.lambda$queryCacheEntry$6(FileCache.java:415)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.SynchronizedFile.read(SynchronizedFile.java:215)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:391)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.utils.FileCache.createFile(FileCache.java:273)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.getFromCacheAndCreateIfMissing(DexArchiveBuilderTransformCallable.java:185)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:147)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:53)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)","sources":[{}]}
AGPBI: {"kind":"error","text":"Caused by: com.android.dx.cf.code.SimException: signature-polymorphic method called without --min-sdk-version \u003e\u003d 26","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.cf.code.Simulator$SimVisitor.visitConstant(Simulator.java:684)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:764)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.cf.code.Simulator.simulate(Simulator.java:101)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.cf.code.Ropper.processBlock(Ropper.java:790)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.cf.code.Ropper.doit(Ropper.java:745)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.cf.code.Ropper.convert(Ropper.java:350)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:285)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:141)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:95)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilderCallable.translateClass(DexArchiveBuilderCallable.java:93)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:74)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:43)","sources":[{}]}
AGPBI: {"kind":"error","text":"\t... 5 more","sources":[{}]}
AGPBI: {"kind":"error","text":"...at bytecode offset 00000011","sources":[{}]}
AGPBI: {"kind":"error","text":"locals[0000]: Lorg/robolectric/internal/bytecode/ProxyMaker$2;","sources":[{}]}
AGPBI: {"kind":"error","text":"locals[0001]: Ljava/lang/Class;","sources":[{}]}
AGPBI: {"kind":"error","text":"locals[0002]: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"locals[0003]: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"stack[0002]: Ljava/lang/invoke/MethodHandle;","sources":[{}]}
AGPBI: {"kind":"error","text":"stack[0001]: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"stack[top0]: Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"...while working on block 000f","sources":[{}]}
AGPBI: {"kind":"error","text":"...while working on method createProxy:(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"...while processing createProxy (Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;","sources":[{}]}
AGPBI: {"kind":"error","text":"...while processing org/robolectric/internal/bytecode/ProxyMaker$2.class","sources":[{}]}

>FAILED

>FAILURE: Build failed with an exception.

>* What went wrong:
>Execution failed for task ':live-feed:transformClassesWithDexBuilderForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.builder.dexing.DexArchiveBuilder$DexBuilderException: Unable to convert input to dex archive.

>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log >output.

>BUILD FAILED in 4s
>43 actionable tasks: 3 executed, 40 avoided (93%)

### Steps to Reproduce
You just put robolectric in the build.gradle file and write a test and when you want to run it, it will crash
### Robolectric & Android Version
Robolectric 3.3.2 but I tried with 3.3.1 and it does the same so I don't think it's something from the version

**Comment by xian** [comment]
Robolectric isn't intended for running instrumentation tests; it runs in a JVM rather than on a device or emulator. See instructions [here](http://robolectric.org/getting-started/).
