### ISSUE TITLE
Please update "Get Start" instruction for contributor

### ISSUE THREAD

**Issue by WilliamXi** [robolectric/robolectric#3194]
### Description
In http://robolectric.org/contributing/, below two scripts don't exist.

> Install all required dependencies:
> ./scripts/install-dependencies.sh
>
> Perform a full build of all shadows:
> ./scripts/install-robolectric.sh
> 

### Robolectric & Android Version
Bobolectric 3.3.2

**Comment by jongerrish** [comment]
Looks like the website isn't up to date. It should be pointing to the
latest instructions here:
https://github.com/robolectric/robolectric/blob/master/.github/CONTRIBUTING.md
