### ISSUE TITLE
Cannot get String resources when running from command line

### ISSUE THREAD

**Issue by ngarelimdex** [robolectric/robolectric#3200]
### Description
Running from Android Studio is fine. However when running gradlew test command, the test is failing due to incorrect path of the manifest file. It looking into the bundles folder:

No such manifest file: Gyrocompass\build\intermediates\bundles\debug\Gyrocompass\src\main\AndroidManifest.xml

instead of 
Gyrocompass\build\intermediates\manifests\full\debug\AndroidManifest.xml

My config annotation
@Config(constants = BuildConfig.class, buildDir = "Gyrocompass/build")

### Steps to Reproduce
Create a dummy unit test and call
String s = RuntimeEnvironment.application.getApplicationContext().getString(R.string.bla);

### Robolectric & Android Version
testCompile "org.robolectric:robolectric:3.3.2"
compileSdkVersion 23

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
