### ISSUE TITLE
DisplayManager.addAllDisplayLocked() NPE migrating from Robolectric 3.1.4 to 3.3.2

### ISSUE THREAD

**Issue by grimesmea** [robolectric/robolectric#3209]
### Description
I am upgrading a project from Robolectric 3.1.4 to 3.3.2. The project contains a number of dialog tests - checking whether a dialog exists, if it is showing, does the correct action when button are clicked, etc.

With Robolectric 3.3.2, all tests handling dialogs throw an NPE once the dialog is set to show due to null displayIds in the DisplayManager:

```
java.lang.NullPointerException
	at android.hardware.display.DisplayManager.addAllDisplaysLocked(DisplayManager.java:303)
	at android.hardware.display.DisplayManager.getDisplays(DisplayManager.java:288)
	at android.hardware.display.DisplayManager.getDisplays(DisplayManager.java:264)
	at android.support.v4.hardware.display.DisplayManagerJellybeanMr1.getDisplays(DisplayManagerJellybeanMr1.java:36)
	at android.support.v4.hardware.display.DisplayManagerCompat$JellybeanMr1Impl.getDisplays(DisplayManagerCompat.java:146)
```
Setup of the activity that is building and showing the dialogs:

```
     activity = Robolectric.buildActivity(MyActivity.class).create().start().visible().resume().get();

        ActivityManager activityManager = (ActivityManager) activity.getSystemService(Context.ACTIVITY_SERVICE);
        List<ActivityManager.RunningAppProcessInfo> appProcesses = activityManager.getRunningAppProcesses();

        ActivityManager.RunningAppProcessInfo appProcess = new ActivityManager.RunningAppProcessInfo();
        appProcess.processName = activity.getApplicationContext().getPackageName();

        appProcesses.add(appProcess);
```

### Robolectric & Android Version
```
testCompile('org.robolectric:robolectric:3.3.2') 
compileSdkVersion 25
```

**Comment by utzcoz** [comment]
@grimesmea Thanks for reporting this issue. But the Robolectric version of this issue attached is too old, and the team doesn't maintain this version anymore. Please try the latest Robolectric version to check this issue still exists, and feel free to reopen it if this issue still exists. Thanks.
