### ISSUE TITLE
Cannot extend ShadowApplicationPackageManager

### ISSUE THREAD

**Issue by davidburstromspotify** [robolectric/robolectric#3223]
### Description
It is currently not possible to add shadow extensions to e.g. ShadowApplicationPackageManager, since it relies on ApplicationPackageManager from internal Android sources. There is a mechanism in the annotation processor to provide the name of the class as opposed to a class instance ("className"), but due to the validators in RAP, it will just fail the compilation claiming it cannot find "android.app.ApplicationPackageManager".

One option is to have an argument for @Implements to turn off the validator, or that it shouldn't care about classes resolved through className.

### Steps to Reproduce

@Implements(className = "android.app.ApplicationPackageManager")
public class MyShadowApplicationPackageManager extends ShadowApplicationPackageManager {
}

This fails with the issue: @Implements: could not resolve class <android.app.ApplicationPackageManager>

### Robolectric & Android Version
Robolectric: 3.3.2
Android: N/A

**Comment by xian** [comment]
This would be fixed if we did validation against classes from various `android-all` jars rather than whatever's on the classpath. Created #3228.

**Comment by AppInstaller1** [comment]
Try annotating @SuppressWarnings("robolectric.internal.IgnoreMissingClass") to the shadow class.

**Comment by utzcoz** [comment]
@davidburstromspotify Looks like this issue has been fixed by one of Robolectric version as https://github.com/robolectric/robolectric/issues/3228#issuecomment-539205772 said, and you can use latest Robolectric 4.9 to validate it again. Feel free to reopen this issue if you can't extend `ShadowApplicationPackageManager` with latest Robolectric 4.9. Thanks.
