### ISSUE TITLE
Specifying Config.packageName does not set the app package name

### ISSUE THREAD

**Issue by roman-tikhonov** [robolectric/robolectric#3227]
### Description
I need to point Robolectric to a proper package of my R.java class. I use @Config.packageName for that.
```
@Config(sdk = Build.VERSION_CODES.LOLLIPOP, constants = BuildConfig.class,
        application = TestApplication.class, packageName = "com.some.package")
```

However, `RuntimeEnvironment.application.getPackageName()` still returns a default (unchanged) value.

While debugging, I found out that the Manifest object is created by `DefaultManifestFactory.create(ManifestIdentifier manifestIdentifier) `. This method is supposed to pass `manifestIdentifier.getPackageName()` to a constructor of AndroidManifest class, but it does not.

In other words, I think that `DefaultManifestFactory.create(ManifestIdentifier manifestIdentifier)` should call
`AndroidManifest(FsFile androidManifestFile, FsFile resDirectory, FsFile assetsDirectory, String overridePackageName)`
instead of 
`AndroidManifest(FsFile androidManifestFile, FsFile resDirectory, FsFile assetsDirectory)`

Have a look at https://github.com/robolectric/robolectric/blob/robolectric-3.3.2/robolectric/src/main/java/org/robolectric/internal/DefaultManifestFactory.java

### Steps to Reproduce

1. Create robolectric project with some string rewource
Create robolectric test for the application (in src/test directory). In the test, try access application resources via RuntimeEnvironment.application.getResources()
2. When the test is running, instead of obtaining correct resource value android.content.res.Resources$NotFoundException exception is thrown.

### Robolectric & Android Version
org.robolectric:robolectric:3.3.2
compileSdkVersion 25
@Config.sdk = Build.VERSION_CODES.LOLLIPOP
com.android.tools.build:gradle:3.0.0-alpha3

**Comment by roman-tikhonov** [comment]
To prove my idea of the problem's origin, I created a custom test runner that uses a modified version of DefaultManifestFactory, and the problem was solved.

```
public class CustomRobolectricTestRunner extends RobolectricTestRunner {

    /**
     * Creates a runner to run {@code testClass}. Looks in your working directory for your AndroidManifest.xml file
     * and res directory by default. Use the {@link Config} annotation to configure.
     *
     * @param testClass the test class to be run
     * @throws InitializationError if junit says so
     */
    public CustomRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    /**
     * Plugs in {@link CustomManifestFactory} instead of {@link DefaultManifestFactory}.
     * Based on code from {@link RobolectricTestRunner#getManifestFactory(Config)}.
     * @param config
     * @return
     */
    @Override
    protected ManifestFactory getManifestFactory(Config config) {
        // see super.getManifestFactory(config);
        Properties buildSystemApiProperties = getBuildSystemApiProperties();
        if (buildSystemApiProperties != null) {
            return new CustomManifestFactory(buildSystemApiProperties);
        } else {
            return super.getManifestFactory(config);
        }
    }

    public static class CustomManifestFactory extends DefaultManifestFactory {

        public CustomManifestFactory(Properties properties) {
            super(properties);
        }

        @Override
        public AndroidManifest create(ManifestIdentifier manifestIdentifier) {
            return new AndroidManifest(manifestIdentifier.getManifestFile(),
                    manifestIdentifier.getResDir(), manifestIdentifier.getAssetDir(),
                    manifestIdentifier.getPackageName());
        }
    }
}
```

**Comment by jongerrish** [comment]
Can you also give the new build system api a try, this might just fix the
issue for you, let me know if it works or not, instructions here...

https://github.com/robolectric/robolectric/issues/3169

**Comment by roman-tikhonov** [comment]
@jongerrish I already had aapt2 disabled and `includeAndroidResources = true` set when I reported the issue. 

Is this enough to switch to new build system?

**Comment by jongerrish** [comment]
Looks like we will need to include your changes to support cases where the R class package doesn't match the package defined in the manifest.

For reference I've updated the getting started instructions to document the new Gradle integration:-

https://github.com/robolectric/robolectric.github.io/blob/master/getting-started.md

**Comment by jongerrish** [comment]
I've created https://github.com/robolectric/robolectric/pull/3229 which I think will solve your problem.

**Comment by roman-tikhonov** [comment]
@jongerrish awesome, thx for the quick response!

**Comment by jongerrish** [comment]
We'll hopefully finally get the 3.4 release out this week :-)

**Comment by Alexander--** [comment]
@jongerrish This is a major issue, so is it possible to release a new RC with fix ASAP? The workaround exists, but having such essential functionality broken in all 3.3 versions isn't nice (and earlier versions are unusable for us due to broken PowerMock).

**Comment by joecks** [comment]
This is still happening in 3.7.1, why is it closed?
