### ISSUE TITLE
Specify buildSrc in the settings.gradle file

### ISSUE THREAD

**Issue by SalvatoreT** [robolectric/robolectric#3249]
### Description
If you open Robolectric in Android Studio, you will get the following error.
```
Error:The modules ['buildSrc', 'parent'] point to the same directory in the file system.
Each module must have a unique path.
```
### Steps to Reproduce
Pull latest master (`dec99ca4113a7fa5417456dfaa6b5337d991b7f1` at the moment) and open-up Android Studio 2.4 or 3.0 (canary 6).

Someone [posted this to the Google Group](https://groups.google.com/d/msg/robolectric/oFLtti3DUBs/AD1pDD-NCAAJ) a while back.

### Robolectric & Android Version
current master with Android Studio 2.4 or 3.0

**Comment by dmitrikudrenko** [comment]
Do you have a workaround? I opened the project in IntelliJ IDEA and received the same error. I deleted all .iml and made gradle resync but ```Error:The modules ['buildSrc', 'parent', 'github_projects-parent', 'robolectric-buildSrc'] point to same directory in the file system.
Each module has to have a unique path.```

**Comment by xian** [comment]
I think `buildSrc` is implicitly included, please reopen if there's still a problem. I've heard that reimporting gradle projects resolves this issue.
