### ISSUE TITLE
3.4-rc4 is missing artifacts on maven central

### ISSUE THREAD

**Issue by kageiit** [robolectric/robolectric#3251]
Seems like few artifacts are still at 3.4-rc2 specially the shadow artifacts. Is this expected?

<img width="1239" alt="screen shot 2017-07-17 at 3 21 54 pm" src="https://user-images.githubusercontent.com/291148/28292451-e0aa9a32-6b03-11e7-8ade-5b98de8d9484.png">

**Comment by hoisie** [comment]
`3.4-rc3` renamed a lot of artifacts by dropping the `roboletric-` prefix from some of them. e.g `robolectric-utils` was renamed `utils`. Have you seen any errors trying to use 3.4-rc4?

**Comment by kageiit** [comment]
Renaming the module names in gradle worked. Thanks!
