### ISSUE TITLE
Support FingerprintManager

### ISSUE THREAD

**Issue by andreszamoraglobant** [robolectric/robolectric#3266]
### Description
Hi Guys. 

I would like to emulate the fingerprint feature in my app. 
Please, Could you give me a hint for testing this new feature with robolectric? 
Thanks in advance.

Best Regards!!

**Comment by jongerrish** [comment]
What Android api are you specifically calling that you want to test?

**Comment by jongerrish** [comment]
I'm going to close this, please reopen if you can point to some APIs that you need implementing

**Comment by trustmub** [comment]
FingerprintManager API

**Comment by jongerrish** [comment]
Currently this is not supported, but I might be able to get this in for the next release potentially.

**Comment by jongerrish** [comment]
I've added support for test APIs to use all the public APIs of the FingerprintManager, let me know if that works for you or feel free to submit a PR with any enhancements :-)
