### ISSUE TITLE
Fully parse @Config(qualifiers = ...) and set the configuration of the device accordingly.

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#3282]
See https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources for full list

**Comment by jongerrish** [comment]
Some tests provided in https://github.com/robolectric/robolectric/issues/635 for Locale

**Comment by ubaierbhat** [comment]
What exactly is the solution? ```@Config(qualifiers = "en")  ``` still does not work, nor can we use ShadowConfiguration is also not available

**Comment by xian** [comment]
See #3504.
