### ISSUE TITLE
when robolectric builds, is It linux OS required?

### ISSUE THREAD

**Issue by wo4chenkewen** [robolectric/robolectric#3291]
### Description
I read the part "Building And Contributing" of robolectric,,  but do not understand this part "

**You will need to have portions of the Android SDK available in your local Maven artifact repository in order to build Robolectric. Copy all required Android dependencies to your local Maven repo by running:

./scripts/install-dependencies.rb**
"
this ruby script I run in windows  10, hower, it reports this error "can not find  android.jar of sdk api 26" something like this.  

please allow my foolish to ask this simple problem, I'm the beginner of this.

**Comment by hoisie** [comment]
Are you just trying to use Robolectric to write tests, or are you trying to build the Roboelctric project to modify it and contribute? If you just want to write tests, you don't have to run `./scripts/install-dependencies.rb`. All you need to do is add it to your build.gradle.

**Comment by wo4chenkewen** [comment]
If I want to contribute it, It must in linux environment, am I right?

**Comment by xian** [comment]
It's likely to be much easier to work in a linux environment, yes. We're hoping to get rid of the `install-dependencies.rb` script soon though, which may improve matters.
