### ISSUE TITLE
'includeAndroidResources' issues

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#3295]
### Description
Using the new property 'includeAndroidResources' causes compilation errors.

Compilation errors from alternative 1 (see below for details):

> Could not set unknown property 'includeAndroidResources' for task ':application:testDebugUnitTest' of type com.android.build.gradle.tasks.factory.AndroidUnitTest.

Compilation errors from alternative 2:

>  No such property: includeAndroidResources for class: com.android.build.gradle.internal.dsl.TestOptions$UnitTestOptions

This is nether working from command line nor from within Intellij IDEA Ultimate 2017.2

### Steps to Reproduce
Open command prompt (windows) and run:
`gradle testDebug`

Code (two alternatives, neither is working):

Alt 1:
```
...
    testOptions {
        unitTests.all {
            includeAndroidResources = true
            jacoco {
                includeNoLocationClasses = true
            }
            forkEvery = 40
            maxHeapSize = "2g"
        }
    }
```

Alt 2:
```
...
    testOptions {
        unitTests.includeAndroidResources  = true
        unitTests.all {
            jacoco {
                includeNoLocationClasses = true
            }
            forkEvery = 40
            maxHeapSize = "2g"
        }
    }
```

### Robolectric & Android Version
Robolectric: 3.4
Android: 19 (minimum), 25 (compile & target)

**Comment by jongerrish** [comment]
This is what I have:-

android { testOptions { unitTests { includeAndroidResources = true } } }

**Comment by alixwar** [comment]
`android { testOptions { unitTests { includeAndroidResources = true } } }`

That is the equivalent to what I have. What version of the Android Gradle plugin do you use? I have: 'com.android.tools.build:gradle:2.3.3'

**Comment by jongerrish** [comment]
The feature was only added in 3.0alpha. I just checked and its broken again
in alpha 8, but I think it was working in alpha 5. I'm trying to resolve
this with the Android Studio team

**Comment by alixwar** [comment]
> The feature was only added in 3.0alpha. I just checked and its broken again
in alpha 8, but I think it was working in alpha 5. I'm trying to resolve
this with the Android Studio team

Does this mean that the project could never compile from command line (as there is a dependency to Andriod Studio)?

**Comment by jongerrish** [comment]
There is no dependency on AS. AS 3.0 provides merged resources, manifest
and assets and passes the location via a properties file on the classpath.
This happens under the covers, so you just need to include those build
options, but they were only added in AS3.0 so not available on earlier
versions.

**Comment by alixwar** [comment]
If there is no dependency on AS, how come compiling from command line does not work? Android Gradle Plugin needs to understand this new property and I have the latest version. Is this feature not supported in the latest official version of the plugin?

**Comment by jongerrish** [comment]
Because you are using com.android.tools.build:gradle:2.3.3 and this DSL
option was only added in 3.0+

**Comment by alixwar** [comment]
Thanks for the explanation. I was not aware that the AS version and Android Gradle Plugin version were in sync. 

For the record, is there any publicly available Maven repository with the unreleased version of the 3.0 Android Gradle Plugin? Or I could just try changing the artifact name. `com.android.tools.build:gradle:3.0.0-alpha5` ?

**Comment by alixwar** [comment]
Are you sure you don't mean `2.4.0-alpha5`?

**Comment by jongerrish** [comment]
Sorry, I'm not at my desk right now, but here is the branch I'm working on
to convert our demo project to use the new integration.

https://github.com/robolectric/deckard/tree/build_with_as3.0?files=1

As I said, I think it's broken with alpha 8 and am working with the AS team
on this.

**Comment by jongerrish** [comment]
I just checked and this is working with AS3.0 alpha 8

**Comment by nesterov-n** [comment]
@jongerrish it doesn't work with AS3.0 beta 1 / beta 2.
Have same error while compiling

**Comment by IgorGanapolsky** [comment]
@jongerrish It is not working in AS3.0 Beta 2.  I get an error:
> Could not set unknown property 'includeAndroidResources' for task ':app:testProductionDebugUnitTest' of type com.android.build.gradle.tasks.factory.AndroidUnitTest. Open File

**Comment by nEdAy** [comment]
It is not working in AS3.0 Beta 2. I get an error:

Could not set unknown property 'includeAndroidResources' for task ':app:testProductionDebugUnitTest' of type com.android.build.gradle.tasks.factory.AndroidUnitTest. Open File

**Comment by jongerrish** [comment]
Please create an issue on the Android Studio tracker...

https://issuetracker.google.com/issues/new?component=192708&template=840533
