### ISSUE TITLE
Question: Testing fragments with arguments

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#3296]
### Description
In older versions of Robolectric you could do this:

```
FooFragment fragment = new FooFragment();
fragment.setArguments(...);
FragmentTestUtil.startFragment();
```

Now, FragmentTestUtil is deprecated so you need to:

```
Robolectric.buildFragment(FooFragment.class);
```

But how do you instantiated the builder with arguments? I want the arguments to be set before I actually start the fragment. I'm not supposed to get the fragment (from the controller) until I've actually set everything up, right?

**Comment by alwa** [comment]
Any comments?

**Comment by jongerrish** [comment]
Feel free to submit a PR to add to the FragmentController API. Looks like
it's just missing.

**Comment by alixwar** [comment]
@jongerrish I've made a PR ready for review
