### ISSUE TITLE
String resources starting with "@"

### ISSUE THREAD

**Issue by alecplumb** [robolectric/robolectric#3303]
### Description
When `@` is at the beginning of a string resource (with any escaping), the resource will not be found in Robolectric tests.

### Steps to Reproduce
Add a string resource resource with an escaped `@` at the beginning.
Examples:
```
    <string name="at1">\@ fails</string>
    <string name="at2">\u0040 fails</string>
    <string name="at3">"@ fails"</string>
    <string name="at4">This @ works fine</string>
    <string name="at5">This \u0040 works fine</string>
```
Run tests that access these string resources.

### Robolectric & Android Version
Robolectric 3.4 and 3.3.2
AGP 2.3.3 and AGP 3.0.0-alpha9

(In Robolectric 3.3.2, `at1` above is found, but the `\` is returned as part of the string, while `at2` and `at3` are not found)

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
