### ISSUE TITLE
Robolectric can't detect support library resource

### ISSUE THREAD

**Issue by huynhducloi** [robolectric/robolectric#3304]
### Description
If we happen to use support library in our app, Robolectric will have a hard time finding it. For my case, I have a theme that I set for my app that come from a support library. Therefore, Robolectric complains "java.lang.RunTimeException can not find any resource from ResName".

The work-around is to have another theme defined in the style.xml, which is a placeholder, called it as "TestingTheme" for example.
Then we can make a custom RobolectricTestRunner, and override the getThemeRef() method to return that theme.
More detail of this work-around can be found here:
https://stackoverflow.com/questions/26512839/android-lolipop-appcompat-problems-running-with-robolectric/29614632

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
