### ISSUE TITLE
Shadow-support-v4 not updated to 3.4.1

### ISSUE THREAD

**Issue by saschpe** [robolectric/robolectric#3308]
https://bintray.com/bintray/jcenter/org.robolectric%3Ashadows-support-v4/view is still at 3.4-rc2

**Comment by gkylafas** [comment]
Ditto for https://bintray.com/bintray/jcenter/org.robolectric%3Ashadows-play-services/view

**Comment by hoisie** [comment]
These packages have actually been renamed. Sorry for the confusion. See the `Misc` section here: https://github.com/robolectric/robolectric/releases/tag/robolectric-3.4

**Comment by saschpe** [comment]
Alright
