### ISSUE TITLE
After upgrading Robolectric from 3.1.2 to 3.4.2 Travis CI build became broken

### ISSUE THREAD

**Issue by pwittchen** [robolectric/robolectric#3310]
Hi,

In my project, I wanted to upgrade Robolectric from v. 3.1.2 to 3.4.2 (commit: https://github.com/pwittchen/ReactiveNetwork/commit/ff74c2ba7ceb965b8da9f53c7764d3686db4c446), but my Travis CI build failed after that (link: https://travis-ci.org/pwittchen/ReactiveNetwork/builds/260987465). 

After downgrading Robolectric to 3.1.2 again (commit: https://github.com/pwittchen/ReactiveNetwork/commit/86173fdda296601d821aaf1dfd61e995ed71b787) Travis CI build passed (https://travis-ci.org/pwittchen/ReactiveNetwork/builds/260997573). Moreover, unit tests were passing locally both with Robolectric v. 3.1.2 and v. 3.4.2.

Here are my project details:
-  minSdkVersion = 9
- compileSdkVersion = 25
- buildToolsVersion = '25.0.2'
- gradleVersion = '2.3.0'

I'm running the following command on Travis CI via my [.travis.yml](https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/.travis.yml) file:

```
./gradlew clean build test jacocoTestReport check
```

Do you know how to fix this issue to be able to use the latest Robolectric version on Travis CI?

Regards,
Piotr

**Comment by blipinsk** [comment]
Hi @pwittchen, did you figure out what was the issue (or what is the solution)?

I think I'm having similar issues. I see that you were trying to jump from robolectric 3.1.2 to 3.4, which would be in coherence to what I suspect to be the problem. 
Robolectric versions 3.2+ are using `org/robolectric/android-all/6.0.1_r3-robolectric-0/android-all-6.0.1_r3-robolectric-0.jar` (or other version of the `android-all` component). Versions lower than 3.2 weren't using that.
In my case (CircleCI instead of Travis) I get this:

    Downloading: org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Transferring 1K from sonatype
    Downloading: org/sonatype/oss/oss-parent/7/oss-parent-7.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Unable to locate resource in repository

`android-all` component is using oss-parent version 7, and this is not provided by sonatype (only versions 8 and 9 are available).

**Comment by pwittchen** [comment]
Hi, @blipinsk. I haven't solved that issue. Currently, I'm using older Robolectric version, which works fine on CI.

**Comment by Jtellez86** [comment]
@blipinsk Hey man, did you ever solve the problem on your end? We're having similar problems, but experiencing the exception: ```java.lang.RuntimeException
        Caused by: java.io.FileNotFoundException``` for all our tests that run robolectric in our CI deployment, but run fine on our machine.

**Comment by blipinsk** [comment]
@Jtellez86 Although I'm not using that at the moment, from what I remember what kinda-sorta fixed the issue was a custom runner:

```
public class CustomizedRobolectricTestRunner extends RobolectricTestRunner {

    static {
        // The default MavenRepositoryId and MavenRepositoryUrl point at Sonatype
        // which is missing crucial components for Robolectric to work properly.
        RoboSettings.setMavenRepositoryId("mavenCentral");
        RoboSettings.setMavenRepositoryUrl("https://repo1.maven.org/maven2");
    }

    public CustomizedRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }
}
```
and...

```
@RunWith(CustomizedRobolectricTestRunner.class)
```

**Comment by pwittchen** [comment]
In the version `4.0-alpha-3` it's working fine for my project.

Related PR: https://github.com/pwittchen/ReactiveNetwork/pull/292
