### ISSUE TITLE
NumberFormatException when inflating a valid layout having android:orientation

### ISSUE THREAD

**Issue by vincenzovitale** [robolectric/robolectric#3317]
### Description
We have a valid layout with a dimension looking like:

        <item name="view_menu_orientation" format="integer" type="dimen">1</item>

in the default dimension file and like:

        <item name="view_menu_orientation" format="integer" type="dimen">0</item>

for the landscape case.
The item is referenced in a LinearLayout:

      <LinearLayout
        android:id="@+id/view_buttons_container"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/view_menu_margin"
        android:padding="@dimen/view_menu_padding"
        android:orientation="@dimen/view_menu_orientation">

The application builds and starts normally but Robolectric fails with:

android.view.InflateException: XML file build/intermediates/res/merged/app/debug/layout/view_menu.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
...
**Caused by: java.lang.NumberFormatException: For input string: "1.0"**
...

Hardcoding horizontal or vertical in android:orientation makes the robolectric tests pass but of course it's not an option.

### Steps to Reproduce

Have android:orientation reference an integer dimension. 

### Robolectric & Android Version

    testCompile 'org.robolectric:robolectric:3.4.2'
    testCompile "org.robolectric:supportv4:3.4.2"

Android API 25

**Comment by vincenzovitale** [comment]
We solved the problems!

Changing:
                 
               <item name="view_menu_orientation" format="integer" type="dimen">1</item>

to
               <integer name="view_menu_orientation" >1</integer>

The first version works and compile fine, but the second one is the only documented way to define an integer in Android... or at least I could find the place where it is specified.

**Comment by jongerrish** [comment]
What did you change it to?

**Comment by jongerrish** [comment]
Should be fixed with Robolectric 4.0 and binary resource mode. Please give it a try and reopen if its still an issue.
