### ISSUE TITLE
No manifest file found at .\AndroidManifest.xml on Android Studio runner without @Config(constants = BuildConfig.class)

### ISSUE THREAD

**Issue by hugonardo** [robolectric/robolectric#3328]
### Description

Following [Robolectric's Getting Started](http://robolectric.org/getting-started/) instructions, I understood that `@Config(constants = BuildConfig.class)` is deprecated (as its javadoc says) and _"configure the default JUnit test runner configuration in order to work around a bug where Android Studio does not set the working directory to the module being tested [...] Defaults -> JUnit and changing the working directory value to $MODULE_DIR$"_ is only necessary for Linux and Mac users.

Without these configurations, my tests works fine through Gradle's test task (and in its variants). But run then inside Android Studio runner cause me the warning:

```
WARNING: No manifest file found at .\AndroidManifest.xml.
Falling back to the Android OS resources only.
To remove this warning, annotate your test class with @Config(manifest=Config.NONE).
```

And breaks some of my tests that read AndroidManifest metadata.

After configure `@Config(constants = BuildConfig.class)` and `$MODULE_DIR$`, the Android Studio runner works fine.

### Steps to Reproduce
1. Setup Robolectric as Getting Started instructions
2. Do not use deprecated `@Config(constants = BuildConfig.class)` configuration
3. Do not configure Android JUnit Working Directory to `$MODULE_DIR$` (leave blank)
4. Run some test case with RobolectricTestRunner

### Robolectric & Android Version
robolectric_version = 3.4.2

compile_sdk_version = 26
target_sdk_version = 26
min_sdk_version = 15
build_tools_version = 26.0.1

java_source_compatibility = 1.8
java_target_compatibility = 1.8

Android Studio 3.0 Beta 2
com.android.tools.build:gradle:3.0.0-beta2
gradle-4.1-rc-1-all

Windows 10 Pro (Version 1703 Build SO 15063.540)

**Comment by jongerrish** [comment]
It's a known issue with studio 3.0 beta 2 and should be fixed in the next release of AS

**Comment by AlienAsRoger** [comment]
Stills happens on AS 3.0 official and robolectric 3.5.1

**Comment by robross0606** [comment]
Still happening with AS 3.1.3 and Robolectric 3.8.

**Comment by bizkitj** [comment]
Still happening with AS 3.1.4 and Robolectric 3.8.

**Comment by bizkitj** [comment]
http://robolectric.org/getting-started/
```
android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

This solved my issue.

AS 3.1.4
Rob 3.8
