### ISSUE TITLE
ShadowAccountManager returns null when AccountManager.get(Context) is called in 3.4.2

### ISSUE THREAD

**Issue by BetaStrike** [robolectric/robolectric#3330]
https://github.com/robolectric/robolectric/blob/a78a819658e72c418fed1e6a14e54381e3b419d3/shadows/framework/src/main/java/org/robolectric/shadows/ShadowAccountManager.java#L66

Hi, I am running into a situation where a part of my code calls AccountManager.get(pContext), and when running under Robolectric 3.4.2 this returns null. When I go and debug the code, it appears that in the lines are directing towards ShadowAccountManager, and inside it the get method is deprecated but it is somehow overriding the call to AccountManager.get() with the one in ShadowAccountManager. Which has the deprecated tag and asking me to use AccountManager.get(). 

This isn't in the migration guide and I am wondering what to do in this instance, I have no additional config to specify the use of the ShadowAccountManager in my tests explicitly.

Note that we are using 

````
    testCompile 'org.robolectric:robolectric:3.4.2'
    testCompile 'org.robolectric:shadows-support-v4:3.2.2'
    testCompile 'org.robolectric:shadows-httpclient:3.2.2'
    testCompile 'org.robolectric:shadows-play-services:3.2.2'
````
 
as there isn't a stable version of the addons and we were on 3.2.2 before and is doing this upgrade for android O support. But I don't think this should impact android.accounts.AccountManager

Thanks for you time

**Comment by jongerrish** [comment]
This _should_ be fixed now as we're using real Android framework code to provide all of the system services.

Please verify with Robolectric 4.0 and reopen if its still an issue.
