### ISSUE TITLE
WARNING: unknown service ...

### ISSUE THREAD

**Issue by antucg** [robolectric/robolectric#3341]
Hello, in my app I am using NSD_SERVICE and MEDIA_PROJECTION_SERVICE, but when I run the test I get this two messages:

WARNING: unknown service servicediscovery
WARNING: unknown service media_projection

Is there any way of making this services available to the tests?
Thanks.

I am using Robolectric 3.4.2, in AS 2.3.3, and a min SDK version 21.

**Comment by jongerrish** [comment]
I guess they are new services? (Sorry on my phone so can't check)

Yes we can add them but we're pretty slammed right now. We really
appreciate a PR for this.

Take a look at ShadowContextImpl see how they are wired up. You'll then
want to create a shadow for each of them.

**Comment by jongerrish** [comment]
This should be fixed now as we use real Android framework code to provide all of the services.
