### ISSUE TITLE
Default Maven repository for runtime dependencies is missing needed dependencies

### ISSUE THREAD

**Issue by blipinsk** [robolectric/robolectric#3344]
### Description
If Robolectric needs to use the default Maven repository for Runtime dependencies, it uses `https://oss.sonatype.org/content/groups/public/` which is missing needed components for Robolectric. Making it impossible to run tests with Robolectric (because it fails during tests).

E.g.
[`org.robolectric:robolectric:3.4.2`](https://oss.sonatype.org/content/groups/public/org/robolectric/robolectric/3.4.2/robolectric-3.4.2.pom) expects `org.robolectric:android-all:o-preview-4-robolectric-0`
[`org.robolectric:android-all:o-preview-4-robolectric-0`](https://oss.sonatype.org/content/groups/public/org/robolectric/android-all/o-preview-4-robolectric-0/android-all-o-preview-4-robolectric-0.pom) expects `org.sonatype.oss:oss-parent:7`

this version (`7`) of `oss-parent` is missing in the default maven repository see [here](https://oss.sonatype.org/content/groups/public/org/sonatype/oss/oss-parent/)

### Steps to Reproduce

For me it happens during a CircleCI build with Robolectric-based tests.

### Robolectric & Android Version

`robolectric` 3.4.2, `shadows-multidex` 3.3.2, Tests runnning for Android SDK 21

**Comment by bonnyfone** [comment]
I'm having the same issue using version 3.4.2 while running on Jenkins CI, but for some unknown reason it doesn't fail locally on my machine.
Did you find any workaround different from using an older version of Robolectric on CI?

**Comment by soundcloudfrank** [comment]
Having the same issue here on local builds. I imagine if your maven cache has an older version (presumably downloaded when sonatype 7 was still in the repo) then it might work, but any new installations will have issues.

**Comment by blipinsk** [comment]
@bonnyfone Oh, I'm sorry I completely missed your question. I actually found a workaround.
I was using a custom `RobolectricTestRunner`.

```java
public class MavenCentralRobolectricTestRunner extends RobolectricTestRunner {
    static {
        // The default MavenRepositoryId and MavenRepositoryUrl point at Sonatype
        // which is missing crucial components for Robolectric to work properly.
        RoboSettings.setMavenRepositoryId("mavenCentral");
        RoboSettings.setMavenRepositoryUrl("https://repo1.maven.org/maven2");
    }

    public MavenCentralRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }
}

```

**Comment by bonnyfone** [comment]
@blipinsk thanks a lot for the follow up, I'll try!

**Comment by utzcoz** [comment]
Please try the latest Robolectric 4.9.2, and feel free to reopen this issue if this problem still exists. Thanks.
