### ISSUE TITLE
Shadows for support-v4 25.4.0?

### ISSUE THREAD

**Issue by Kisty** [robolectric/robolectric#3352]
### Description
Are there shadows for support-v4 and if not how could I build them myself? Getting version `3.4-rc2` breaks the build due to Fragment already doing transactions and other weird bugs.

### Robolectric & Android Version
Robolectric: `3.4.2`
Android Version: `25`

**Comment by Kisty** [comment]
Oh, so shadows artifact has changed from `shadows-support-v4` to `supportv4`. Could the ReadMe and website update and be clear about this change?

The intial issue still stands however.

**Comment by utzcoz** [comment]
Shadow for support-v3 has been removed from Robolectric 4.9, so this issue is not valid anymore. @Kisty Thanks for your reporting.
