### ISSUE TITLE
Robolectric not calling Applications on create

### ISSUE THREAD

**Issue by Humblefool97** [robolectric/robolectric#3378]
### Description
I am very much new to robolectric.I am facing these issues after migrating from robolectric v3.0  to v3.4.1.
a)Robolectric is not loading my Appcontroller class which extends application
b)I am getting class cast exception on casting to RuntimeEnvironment.application to my appcontroller,which shouldn't be the case as my appcontroller extends application and was working fine before migrating to latest version.please find the code below for my test

@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, manifest = "app/src/main/AndroidManifest.xml", sdk = 21)
public class FragmentTest {

    private ExampleFragment fragment = SupportFragmentController.of(new ExampleFragment()
    ).create().get();
    private Context mContext;

    @Before
    public void setUp() throws Exception {
       // RuntimeEnvironment.application.onCreate();
        mContext =RuntimeEnvironment.application ;
    }

    @Test
    public void testFragmentInstantiation() {
              ExampleFragment.mAppController = (AppController)mContext;

    }

### Steps to Reproduce
Run any test

### Robolectric & Android Version
Robolectric 3.4.1
Android:sdk 21,lollipop(Android 5.0)

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You no longer need to specify @Config(constants = ..., manifest = ....)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
