### ISSUE TITLE
How to mock packageManager.queryIntentActivities in Robolectric 3.4.2?

### ISSUE THREAD

**Issue by AmrutaSonaje66** [robolectric/robolectric#3382]
###I am having 
PackageManager packageManager = androidContext.getApplicationContext().getPackageManager();
        final List<ResolveInfo> appList = packageManager.queryIntentActivities(createIntentToLauncherActivity(), 0);

private Intent createIntentToLauncherActivity() {
        Intent intent = new Intent();
        intent.setAction(Intent.ACTION_MAIN);
        intent.addCategory(Intent.CATEGORY_LAUNCHER);
        return intent;
    }

in source code I can mock packageManager but I am getting exception for packageManager.queryIntentActivities(createIntentToLauncherActivity(), 0);

### I am getting empty applist but I need to set with details like
 log.d("Package Name: " + appInfo.activityInfo.packageName);
                log.d("Activity Name: " + appInfo.activityInfo.name);
                log.d("Process Name: " + appInfo.activityInfo.processName);

I used  List<ResolveInfo> appList=new ArrayList<ResolveInfo>();

        ResolveInfo resolveInfo = new ResolveInfo();
        resolveInfo.isDefault = true;
        ActivityInfo activityInfo=new ActivityInfo();
        activityInfo.packageName="jp.co.ricoh.advop.simplecopy";
        resolveInfo.activityInfo = new ActivityInfo();
        resolveInfo.activityInfo = activityInfo;
        resolveInfo.activityInfo.name = "Example";
appList.add(resolveInfo);
when(shadowApplicationPackageManager.queryIntentActivities(createIntentToLauncherActivity(), 0)).thenReturn(appList);
After setting this I am getting java.lang.reflect.InvocationTargetException
 org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
ArrayList cannot be returned by toString()
toString() should return String
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.

**Comment by jongerrish** [comment]
You should avoid mocking the Android framework.

You can control the results of PackageManager.queryIntentActivities() either from the contents of your AndroidManifest.xml (Robolectric behaves the same as Android), or if you need it, you can use org.robolectric.shadows.ShadowPackageManager#addResolveInfoForIntent(android.content.Intent, java.util.List<android.content.pm.ResolveInfo>) to add entries yourself outside of your manifest contents.
