### ISSUE TITLE
Class cast exception when using a custom view

### ISSUE THREAD

**Issue by ayyodengi** [robolectric/robolectric#3386]
### Description
I have a custom view which is being inflated in onCreate of an activity , i'm getting class cast exception when i do findViewById

### Steps to Reproduce
//code

public class MyActivity extends AppCompatActivity{
MyCustomView rootLayout;
@Override
protected void onCreate(Bundle savedInstanceState) {
setContentView(R.layout.mylayout);
rootLayout = (MyCustomView)findViewById(R.id.root_layout); // Class cast exception here
}
}

Test class
public class testActivity {
 @Before
    public void setUp() throws Exception {
     activityController = Robolectric.buildActivity(MyActivity.class);
        activityController.create().resume();  //this calls on create which causes the class cast exception
}
}
Exception : 

### Robolectric & Android Version
on all android version
Robolectric version : 3.4.2

**Comment by jongerrish** [comment]
There is not really enough information to investigate this. Are you sure you have a MyCustomView element with id being root_layout?

What does the ClassCastException look like?

**Comment by hasonguo** [comment]
I have also the question.when using my  custom view，cast exception appear.but both the class are the same.i don't kown reason.please help m.
