### ISSUE TITLE
Robolectric tests are not debuggable in Android Studio

### ISSUE THREAD

**Issue by virl** [robolectric/robolectric#3387]
At least in Android Studio 2.3.3, Robolectric tests are not debuggable: breakpoints set in test code are not triggered when running tests with debugger attached.

**Comment by jongerrish** [comment]
Yeah, this is a general problem with Android Studio, we'd need some plugin with APIs exposed by Android Studio or have this just baked into Android Studio directly to be able to switch the debugging source depending on the API level the test is executing. I believe this is a general problem when also debugging code on an emulator or real device.

**Comment by virl** [comment]
@jongerrish Just wanted to say that it is **very** needed feature, because major advantage of unit tests is ability to debug some parts of the code during their execution.

**Comment by jongerrish** [comment]
Couldn't agree more. I've created the following issue on the AS tracker:-

https://issuetracker.google.com/65752609

**Comment by virl** [comment]
@jongerrish Thanks!

**Comment by utzcoz** [comment]
@virl You can try latest Robolectric and Android Studio, I think you can debug Robolectric tests with built-in break points now.
