### ISSUE TITLE
Error:Failed to resolve: com.android.support:multidex:1.0.1

### ISSUE THREAD

**Issue by lufengdie** [robolectric/robolectric#3415]
Open [robolectric](https://github.com/robolectric/robolectric) in **Android Studio 3.0 Beta 5**:

build Project error:

```
Error:Failed to resolve: com.android.support:multidex:1.0.1

Failed to resolve: com.android.support:support-fragment:26.0.0-alpha1

Failed to resolve: com.google.android.gms:play-services-base:8.4.0 

...

```

After `Add Google Maven repository and sync project` still failed.

**Comment by jongerrish** [comment]
You're trying to open the Robolectric project with Android Studio? It doesn't work in AS yet, we need to switch over the gradle build files to use the AGP. I have a branch for this that was getting close but is probably a little out of date if you want to take it over?

https://github.com/robolectric/robolectric/tree/use_as3.0

**Comment by lufengdie** [comment]
I intend to give up for a while，

But still thank You .
