### ISSUE TITLE
Null pointer in ShadowPackageManager#getResolveInfo()

### ISSUE THREAD

**Issue by shafty023** [robolectric/robolectric#3437]
### Description
In ShadowApplicationPackageManager#queryIntentServices() while it is iterating over all services to add ResolveInfo and it finds an intentFilter it will then call #getResolveInfo() which iterates over the data types. The problem is intentFilter#typesIterator() can return null and you don't do a null check. This looks like a simple fix.

### Steps to Reproduce
Define this service in your manifest

```
<service android:name=".TestSyncAdapterService">
    <intent-filter>
        <action android:name="android.content.SyncAdapter"/>
    </intent-filter>
    <meta-data android:name="android.content.SyncAdapter"/>
</service>
```

The following code should be in production code so you can't go grabbing any shadow class. So put this in your test code as-is as it should mirror what would be in real production code.

```
final PackageManager pm = context.getPackageManager();
final Intent intent = new Intent("android.content.SyncAdapter").setPackage(context.getPackageName());
final List<ResolveInfo> intentServices = pm.queryIntentServices(intent,
                PackageManager.GET_SERVICES | PackageManager.GET_META_DATA);
```

When ShadowApplicationPackageManager hits the above service it will throw the NPE since IntentFilter#typesIterator() will return null.

### Suggested fix:

**ShadowApplicationPackageManager#getResolveInfo()**

```
if (intentFilter.typesIterator() != null) {
    for (Iterator<String> it = intentFilter.typesIterator(); it.hasNext(); ) {
        info.filter.addDataType(it.next());
    }
}
```

### Robolectric & Android Version
Robolectric 3.4.2
compileSdk 25
targetSdk 25

**Comment by shafty023** [comment]
Just as an fyi, I patched this locally and it does in fact fix the issue.

**Comment by jongerrish** [comment]
We've overhauled PackageManager support and also process the merged manifest using real Android framework code. Please feel free to reopen if its still an issue.
