### ISSUE TITLE
launcherapps system service not supported

### ISSUE THREAD

**Issue by tobdub** [robolectric/robolectric#3457]
### Description
The launcher apps system service is not supported.

### Steps to Reproduce
mLauncherApps = (LauncherApps) context.getSystemService(Context.LAUNCHER_APPS_SERVICE);

mLauncherApps is null

### Robolectric & Android Version
Robolectric 3.4.2, Android 8.0.0 (Oreo)

### Link to a public git repo demonstrating the problem:
-

**Comment by jongerrish** [comment]
We now use real Android framework code to provide system services so this should be fixed. Can you try v4.0 and reopen if the issue exists?
