### ISSUE TITLE
Getting started guide not up-to-date

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#3471]
### Description
http://robolectric.org/getting-started/ still refers to 3.4.2. Related, it seems that 3.5 is not available in Maven repos? At least I'm getting: `[16:53:14][Step 1/1]       > Could not find org.robolectric:supportv4:3.5.` Perhaps these dependencies don't exist in 3.5?

### Steps to Reproduce
Enter URL in browser and read

### Link to a public git repo demonstrating the problem:
http://robolectric.org/getting-started/

**Comment by keith30xi** [comment]
Neither is this http://robolectric.org/using-add-on-modules/  All of the shadows have been renamed to something else.  They were renamed in 3.4 and then again in 3.5.  I still cannot find the jar that contains the `ShadowGeocoder`.

**Comment by jongerrish** [comment]
ShadowGeocoder is now in the framework jar since it shadows a framework
class.

Feel free to send a PR to fix the docs

**Comment by xian** [comment]
Updated http://robolectric.org/using-add-on-modules/.
