### ISSUE TITLE
NPE in ShadowTypeface

### ISSUE THREAD

**Issue by jrodbx** [robolectric/robolectric#3473]
Related to the known issue with loading assets/fonts:
https://github.com/robolectric/robolectric/issues/2647
https://github.com/robolectric/robolectric/issues/3008
https://github.com/robolectric/robolectric/issues/3380

Except now in Robolectric 3.5, listFiles returns null which results in an NPE:

https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowTypeface.java#L72,L73

**Comment by jrodbx** [comment]
workaround is to copy the Shadow, replace the null array with an empty array and register the custom Shadow for the test classes that need it.

**Comment by mohitagrawal** [comment]
Happening in 3.5.1 as well. Should I revert to old version of roboelectric to make this work?

**Comment by jongerrish** [comment]
Can you try this with Robolectric 4.0.2 + binary resource mode enabled.

Resource handling and font support has been dramatically improved so I suspect this has been fixed.

If its still an issue on 4.0.2 with binary resources, please reopen and include a stack trace.
