### ISSUE TITLE
Integration with AndroidAnnotations 

### ISSUE THREAD

**Issue by MohamedGamalFci** [robolectric/robolectric#3474]
I tried to run this code into my robolectric test class:

@ViewById(R.id.name)
EditText nameEditText;

but it seems that the nameEditText still equals null after injection

**Comment by utzcoz** [comment]
@MohamedGamalFci Please try the latest Robolectric to check whether this issue still exists. But I think many folks don't use AndroidAnnotations recent years, and the AndroidAnnotations team deprecated the development, see https://github.com/androidannotations/androidannotations.
