### ISSUE TITLE
SQLite native binaries should be com.almworks.sqlite4java

### ISSUE THREAD

**Issue by jplemieux** [robolectric/robolectric#3480]
SQLite native libraries should come from
https://mvnrepository.com/artifact/com.almworks.sqlite4java

not from
https://mvnrepository.com/artifact/com.github.axet.litedb/libsqlite/0.282-3

See these lines in robolectric-shadows/shadows/framework/build.gradle:
    jni "com.github.axet.litedb:libsqlite:0.282-3:natives-mac-x86_64"
    jni "com.github.axet.litedb:libsqlite:0.282-3:natives-linux-x86"
    jni "com.github.axet.litedb:libsqlite:0.282-3:natives-linux-x86_64"
    jni "com.github.axet.litedb:libsqlite:0.282-3:natives-windows-x86"
    jni "com.github.axet.litedb:libsqlite:0.282-3:natives-windows-x86_64"

**Comment by guness** [comment]
I have managed to use almworks' library as following:
https://github.com/guness/RobolectricSQLite
however since I cannot run tests on my local (due to mismatching java version), cannot create PR for a while.

**Comment by guness** [comment]
We can close this one because a solution has been merged: https://github.com/robolectric/robolectric/pull/5216

**Comment by hoisie** [comment]
Thanks @guness
