### ISSUE TITLE
Problem with inflating CollapsingToolbarLayout

### ISSUE THREAD

**Issue by bartoszwilk** [robolectric/robolectric#3484]
Robolectric version: 3.5
CompileSdk version: 25

I have a problem with testing Activity that contains CollapsingToolbarLayout which is being triggered by RecyclerView's behavior "app:layout_behavior="string/appbar_scrolling_view_behavior".

When I try to setup my Activity with Robolectric, I get the following exception:

```
[android.view.InflateException: XML file build/intermediates/res/merged/programtvProd/debug/layout/viewholder_channels_selection.xml line #-1 (sorry, not yet implemented): Layout state should be one of 100 but it is 10

Caused by: java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
	at android.support.v7.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:11469)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3617)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3340)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3867)
...
```
I'm pretty sure that this error is caused by mentioned RecyclerView's layout_behavior.
When I delete it, everything works fine.

**Comment by mkoslacz** [comment]
I'm also encountering this issue. Any updates on this?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
