### ISSUE TITLE
Error inflating class info.hoang8f.widget.FButton

### ISSUE THREAD

**Issue by Abdulwahid80** [robolectric/robolectric#3488]
### Description
After updating android studio form 2.3.3 to 3.0 I faced this problem
my project was working properly with FButton. when I upgrade android studio then update my project
this problem appears.

**Comment by delabi** [comment]
Hey @Abdulwahid80 , how did you solve this? Did you have to downgrade gradle?

**Comment by eyildiz-ugoe** [comment]
I am facing the same problem still as of gradle 4.1 and plugin 3.0.1.
