### ISSUE TITLE
Please release a 3.5 compatible artifact for shadows-support-v4

### ISSUE THREAD

**Issue by vlazzle** [robolectric/robolectric#3490]

**Comment by nyarlathotep77** [comment]
Please fix shadows compatibility with 3.5 because that's blocking the migration to Android Studio 3

**Comment by tmtrademarked** [comment]
I'm pretty sure that "shadows-supportv4" exists for 3.5.1. (It looks like this artifact was "shadows-support-v4" in <3.4, "supportv4" in 3.4+, and "shadows-supportv4" in 3.5+)

**Comment by vlazzle** [comment]
Thanks @tmtrademarked , missing bit for me was that the artifact was renamed to shadows-supportv4 for 3.5.1.

**Comment by iamareebjamal** [comment]
This should be corrected in documentation -
