### ISSUE TITLE
Where is 3.5 jar containing org.robolectric.shadows.maps.ShadowGeocoder?

### ISSUE THREAD

**Issue by keith30xi** [robolectric/robolectric#3500]
### Description
Attempting to upgrade from 3.4.2 to 3.5.1.  Not sure why the shadow jars were renamed again but looks like there is at least one missing - `shadows-maps`

See https://github.com/robolectric/robolectric/blob/robolectric-3.5.1/shadows/framework/src/main/java/org/robolectric/shadows/ShadowGeocoder.java
See http://search.maven.org/#search%7Cga%7C1%7Cc%3A%22ShadowGeocoder%22

### Steps to Reproduce
Upgraded from 3.4.2 to 3.5.1.  
Unable to find `shadows-maps` jar (using the same naming convention as the other `shadows-`)
Code is still in the repository but does not appear to have been deployed to any maven repo.

### Robolectric & Android Version
Robolectric 3.5.1

**Comment by jongerrish** [comment]
The shadows maps project provided shadows for the old deprecated maps api.
You should be using the play services maps v2 API now.

The ShadowGeoCoder shadows a framework class but was in the wrong place, so
it's been moved into the shadow framework jar.

**Comment by keith30xi** [comment]
is that the name of the published artifact?

**Comment by keith30xi** [comment]
It appears to now be `shadows-framework`.  However, it was changed to `final` so we will have to copy the code to make use of it.  Any idea what it was made `final`?

**Comment by jongerrish** [comment]
No, I'm, not sure, but you can send us a PR with your changes in if they
will be generally useful and we'll get them integrated.
