### ISSUE TITLE
I have a custom view which is being inflated in onCreate of an activity , i'm getting class cast exception when i do findViewById

### ISSUE THREAD

**Issue by hasonguo** [robolectric/robolectric#3506]
### Description
xml:
 <com.hason.lib.view.TestView
        android:id="@+id/test_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

###code:

public class TestView extends TextView {
    public TestView(Context context) {
        super(context);
    }
    public TestView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
}

###on Activitity to initView

TestView view =  (TestView)findViewById(R.id.test_view);// Class cast exception here

exception descrition:

java.lang.ClassCastException: 
com.hason.lib.view.TestView cannot be cast to com.hason.lib.view.TestView

but if I don't use  custom view ,it works well.
###for example:

<TextView
        android:id="@+id/text_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

TextView view =  (TextView)findViewById(R.id.text_view);
no any exception
 
Beg for  help me!!
### Robolectric & Android Version
sdk verstion = 21
### Link to a public git repo demonstrating the problem:

-

**Comment by Blackhex** [comment]
Same issue here both with custom View and Android Data Binding parameter class. Using Robolectric 3.5.1.

**Comment by RunnerWhisky** [comment]
Get the same problem,has sovled this yet.I have no idea about this.

**Comment by hoisie** [comment]
Please check out https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues

Without a repro/sample project this isn't really actionable.

Maybe you are using a third.party mocking library and spying on an activity?

I will gladly reopen if there's a repro.
