### ISSUE TITLE
Update BouncyCastle to match Android's version

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#3509]
### Description
The version used by Robolectric is old (1.52).

I've created a PR to update it: https://github.com/robolectric/robolectric/pull/3508

**Comment by alixwar** [comment]
There seems to be a reason for not updating it: https://github.com/robolectric/robolectric/issues/3288#issuecomment-338658566

**Comment by xian** [comment]
Yeah, bouncycastle should stay at the same version Android uses internally.

**Comment by xian** [comment]
Actually it should be 1.57; see thee [Android source](https://android.googlesource.com/platform/external/bouncycastle/+/android-9.0.0_r16/bouncycastle.version)

**Comment by brandonweeks** [comment]
This was fixed in #6509.

**Comment by hoisie** [comment]
Thanks @brandonweeks
