### ISSUE TITLE
Robolectric 3.5.1 isn't working with nonstandard xmlns for apk/res/android namespace

### ISSUE THREAD

**Issue by yargray** [robolectric/robolectric#3516]
I have a layout view_oferta.xml with nonstandard xmlns:a for android attributes (Android system works well with it):
```xml
<?xml version="1.0" encoding="utf-8"?>
<TextView
	xmlns:a="http://schemas.android.com/apk/res/android"
	style="@style/TextView.Title.Medium"
	a:id="@+id/text_oferta"
	a:text="@string/oferta"
	a:textColor="@color/text"
/>
```

When I try to inflate this layout in Robolectric test, all attributes with custom ns has no proper values. Test like this is not green:
```java
@Test
public void test() throws Exception {
	final View view = LayoutInflater.from(RuntimeEnvironment.application)
			.inflate(R.layout.view_oferta, null);
	assertEquals(view.getId(), R.id.text_oferta); // now view.getId() returns -1
}
```

When I change ns to standard xmlns:android the test become green.
It would be nice if Robolectric took into account such cases.

Thanks a lot!

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
