### ISSUE TITLE
There is no documentation or API? there are too few websites...

### ISSUE THREAD

**Issue by liangxianshen** [robolectric/robolectric#3519]

**Comment by xian** [comment]
We're working to improve documentation. Have you checked out http://robolectric.org/ and the [Chrome Robolectric Extension](https://chrome.google.com/webstore/detail/robolectric/pjepcinimnfnaoopahdkpkefnefdkdgh)?

**Comment by liangxianshen** [comment]
thank you，
Long live the robolectric
