### ISSUE TITLE
Cannot find symbol "execute" compiling ShadowSQLiteConnections

### ISSUE THREAD

**Issue by huygee** [robolectric/robolectric#3520]
I'm getting a compiler error trying to upgrade beyond 3.3.2:

<android_path>/src/test/java/org/robolectric/shadows/ShadowSQLiteConnections.java:19: error: cannot find symbol
        execute("close connection", () -> {
        ^
  symbol:   method execute(String,()->{ SQLi[...]ll; })
  location: class ShadowSQLiteConnections

- I'm using Android Studio 3.0 and Gradle 4.1
- Tried 3.5.1 and 3.4.2. Both have the same issue. 
- Tried removing .gradle cache directories with no luck.

The only robolectric dependencies I have in my gradle files are:

    testImplementation "org.robolectric:robolectric:3.5.1"
    testImplementation "org.robolectric:shadows-support-v4:3.3.2"

**Comment by utzcoz** [comment]
@huygee Please try the latest Robolectric, and reopen this issue if this problem still exists. Thanks.
