### ISSUE TITLE
Running Robolectric in eclipse without Mavan or Gradle

### ISSUE THREAD

**Issue by ehsan-is-everything** [robolectric/robolectric#3524]
Hi,
I'm going to use Robolectric as mocking framework in my project. So I need to have it with all dependencies and as an offline java project in eclipse to do my work. I trying to build and use it. First I found Robolectric 3.5.1 with all Jar dependencies. Then I make a Java project in eclipse and then add all that Jar file in the build path of it. Then I made a package for Android class (e.g Activities and etc.). for building Android classes I should add android.supports libraries to my project. I've done it in a good way! After that, I write a class for running Robolectric in Junit as my main class of Project. 
When I run it, it starting to building my MainActivity but it needs my "manifest.xml" and "res" files. I override the RobolectricTestRunner class for this goal. I send my codes anyway. I run with new config and the error is "You need to use a Theme.AppCompat theme (or descendant) with this activity."
Is there any mistake in my configs and building dependencies? I would be grateful if anyone gives me information about this issue like the name of dependencies and location of necessary files and etc.
Is there anyone can help me?!
my main method:

`public static void main(String[] args){
		JUnitCore junit = new JUnitCore();
		Result result = junit.run(DummyMain.class);
		int resultInt = result.getFailureCount();
		if (resultInt != 0){
			System.out.println("Failed run! There were: "+resultInt+" failures!");

			for(Failure failure : result.getFailures()){
				System.out.println(failure.getMessage());
			}

			return;
		}
		System.out.println("Successful run!");

	}
`
my test class:

`
@RunWith(MyRobolectricTestRunner.class)
public class DummyMain {

	@Test
	public void theGreatTest(){
		System.out.println("Starting dummyMain");
		MainActivity ma=Robolectric.setupActivity(MainActivity.class);
		ma.findViewById(R.id.button).performClick();
        System.out.println("Finished with dummyMain");
	}
}
`

MyRobolectricTestRunner class:

`public class MyRobolectricTestRunner extends RobolectricTestRunner{
	private static final int MAX_SDK_SUPPORTED_BY_ROBOLECTRIC = 21;

	public MyRobolectricTestRunner(Class<?> arg0) throws InitializationError {
		super(arg0);
		// TODO Auto-generated constructor stub
	}
	@Override
    protected AndroidManifest getAppManifest(Config config) {
        final String manifestProperty = "/media/ehsan/a2c41319-a56d-4856-b979-aeaebaea4e50/Programs/SPF-Android/Ver 1.0.0/Testak-TextInput-button-sql-vul/app/src/main/AndroidManifest.xml";
        final String resProperty = "/media/ehsan/a2c41319-a56d-4856-b979-aeaebaea4e50/Programs/SPF-Android/Ver 1.0.0/Testak-TextInput-button-sql-vul/app/build/intermediates/res/merged/debug";
        //final String resProperty = "/media/ehsan/a2c41319-a56d-4856-b979-aeaebaea4e50/Programs/SPF-Android/Ver 1.0.0/Testak-TextInput-button-sql-vul/app/src/main/res/";
        final String assetProperty ="/media/ehsan/a2c41319-a56d-4856-b979-aeaebaea4e50/Programs/SPF-Android/Ver 1.0.0/Testak-TextInput-button-sql-vul/app/src/main/assets/";
        return new AndroidManifest(Fs.fileFromPath(manifestProperty), Fs.fileFromPath(resProperty), Fs.fileFromPath(assetProperty)) {
            @Override
            public int getTargetSdkVersion() {
                return MAX_SDK_SUPPORTED_BY_ROBOLECTRIC;
            }
        };
    }

}`
The whole project is here:
[myProject.zip](https://github.com/robolectric/robolectric/files/1470454/myProject.zip)

**Comment by ehsan-is-everything** [comment]
@daaku @avh4 @mag @developernotes @tanob

**Comment by jongerrish** [comment]
We're not actively supporting Eclipse or Maven any longer since its no longer supported by the Android team. We're happy to accept pull requests if you can make a fix however.
