### ISSUE TITLE
Current issues and thoughts

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#3532]
Hi guys,

since it is the best place to talk about Robolectric I decided to create questions here.

As my background, I use Robolectric for years, but since recently it looks like time to quit. But I still have hope I might find some inspiration here.

I have two major problems now:

1. With Android Studio 3.x I just can not run Robolectric tests. I think it runs tests in the not specified working directory. And so it is AS issue, but still, it blocks my workflow. I switched to IntelliJ community edition but this also has own drawbacks.

2. Android Gradle plugin 3.x just doesn't run Robolectric tests. And again it is dependent on Google team changes. But it is not on priority and will be not fixed anytime soon. I can not update plugin now unless I ignore a quite big portion of my tests.

So the question, how is on your side? Do you also suffer from these issues?

As for me, it looks like I should move boundaries of Android API usages even higher, write more abstractions and move all tests that are touching Android to instrumental tests. I don't like instrumental tests since it requires having device or emulator running, but speed wise they are comparable with Robolectric one. This also will require more tooling for mocking Kotlin, collecting test coverage, etc. That is massive re-think/change but more and more I think about leaving Robolectric.

Thanks for listening!

**Comment by jongerrish** [comment]
Hey Eugen,

Sorry that you are having problems, lets see if we can't figure out what is going wrong.

1) Have you followed the "Getting Started" guide for AS3.0? http://robolectric.org/getting-started/ - remember to remove @Config(constants = BuildConfig.class) as that will switch back to the old pre-3.0 integration.

2) What version of AS + Robolectric are you using? The integration had some bugs in earlier versions but the latest versions of each seem to be working just fine.

3) You can checkout the Deckard project as an example of how to set things up.

4) There are some known issues with AS3.0 - manifests are not merged or pre-processed (they were not previously either though) and neither are assets merged.

5) Can you let me know exactly what errors you are seeing?

6) Have you created any relevant bugs on Android Studio? I circle back with the team there and see what I can do.

Cheers, Jonathan

**Comment by emartynov** [comment]
Hi Jonathan,

much appreciated your reply and for the extra power to give a try one more time.

I sat yesterday and applied recommended config for Robolectric test runner configuration, updated gradle files. I started paying attention to all errors and crashes during tests and fixed them one by one.

As for now I have running unit tests with AGP 3.0 and looks like latest stable AS can run Robolectric tests without issues.

The last problem I have is not related to Robolectric but Dexguard/AGP and I'm trying to solve it today.

I appreciate your post with steps and especially words with the statement that it works for you. That gave me the power to continue.

I'm going to close the issue and spread learned knowledge to my Android team and SO.

The main learning I should not lose hope for any occasion! Thank you!

**Comment by jongerrish** [comment]
Hey,

Sorry for the delay, I was on vacation :-)

Glad you got things working, if there is any missing steps in the getting
started instructions or improvements in the docs please let us know.

Thanks, J.
