### ISSUE TITLE
Unable to create a VIRTUAL TABLE fts 

### ISSUE THREAD

**Issue by slott** [robolectric/robolectric#3556]
### Description
Part of my unit test is to initialise the DB and creating a VIRTUAL TABLE fails with the error:
```
Cannot execute for changed row count, base error code: 1
java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] step() [CREATE VIRTUAL TABLE  virt_CORRECTIONS USING fts4(tokenize=unicode61, content=CORRECTIONS, VINTAGE_YEAR,WINE_NAME,WINERY_NAME,REGION_NAME)]DB[1][C] [unknown tokenizer: unicode61]
```

### Steps to Reproduce
Execute a CREATE stement for a VIRTUAL TABLE ie.

```sql
CREATE VIRTUAL TABLE  virt_CORRECTIONS USING fts4(tokenize=unicode61, content=CORRECTIONS,
    VINTAGE_YEAR,WINE_NAME,WINERY_NAME,REGION_NAME)
```

### Robolectric & Android Version
3.5.1 and SDK target 27
unicode61 should be supported...

**Comment by AinisSK** [comment]
Hello @slott I've faces the same problem. Vote it! Waiting for a solution.

**Comment by xian** [comment]
Looks like we likely need to bump the linked version of sqlite, possibly https://mvnrepository.com/artifact/com.almworks.sqlite4java/sqlite4java/1.0.392

https://www.sqlite.org/fts3.html#compiling_and_enabling_fts3_and_fts4

**Comment by lukechi1219** [comment]
Hi there,
Today I also run into this issue. I try to add latest sqlite4java dependencies.

    testImplementation 'com.almworks.sqlite4java:sqlite4java:1.0.392'
    testImplementation 'org.robolectric:robolectric:4.1'

yet it seems unable to recognize 

CREATE VIRTUAL TABLE IF NOT EXISTS `${TABLE_NAME}` USING FTS4(`id` TEXT, `area` TEXT, `name` TEXT)

maybe it will recognize this?

CREATE VIRTUAL TABLE IF NOT EXISTS `${TABLE_NAME}` USING FTS4(`id`, `area`, `name` )

but I don't know how to force ROOM lib to not add "TEXT" after column name.....

**Comment by mikejonesguy** [comment]
Now that Room v2.1.0 has been released with official support for FTS, this going to affect anyone who wants to test their FTS-enabled database using unit tests. It looks like there is a PR that has been submitted to address this issue -- any reason why it hasn't been merged? (Anything I could do to help with that?)

**Comment by TWiStErRob** [comment]
There was an update a few days ago on the PR, the ball is with @ddrenjanac

**Comment by guness** [comment]
We can close this one because a solution has been merged: https://github.com/robolectric/robolectric/pull/5216
