### ISSUE TITLE
Robolectric crashes when loading Font from Resources.getFont or ResourceCompat.getFont

### ISSUE THREAD

**Issue by ankushg** [robolectric/robolectric#3590]
### Description
When using [`ResourceCompat.getFont`](https://github.com/ankushg/RobolectricFontResourcesTest/blob/master/app/src/main/java/com/ankushg/fonttest/CustomButton.java#L30) (and `Resources.getFont` on API 26+) with a valid `@FontRes`, Robolectric can't find the font resource and crashes. 

```
android.content.res.Resources$NotFoundException: Resource ID #0x7f040001
	at android.content.res.Resources.getValue(Resources.java:1233)
	at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:335)
	at android.support.v4.content.res.ResourcesCompat.getFont(ResourcesCompat.java:205)
```

The given Resource ID does map to a `font` resource in my debug configuration's `R.java`, and the corresponding ttf file is also present in `build/intermediates/res/merged/debug/font`.

Notably, Robolectric *does not* crash when [inflating a view that uses that same font as a `@font` value in XML](https://github.com/ankushg/RobolectricFontResourcesTest/blob/master/app/src/main/res/layout/activity_main_font_reference.xml#L12).

### Steps to Reproduce

Attempt to use `ResourcesCompat.getFont` with a valid `R.font` value

### Robolectric & Android Version
- Robolectric 3.5.1 (also tried with 3.6-alpha-1)
- Android Gradle Plugin 3.0.1 (also tried with 3.1.0-alpha-05)
- Android Studio 3.0.1 (also tried with 3.1 Canary 5)
- Android API 27

Other relevant configuration settings:

* I've turned on `includeAndroidResources` in `build.gradle` 
* I don't have `constants` set in the test config
* I've tried both with/without `enableAapt2` and `enableNewResourceProcessing`
* I've tried it with/without [making the Unit Test Sources task depend on Merging Assets](https://github.com/robolectric/robolectric/issues/2647#issuecomment-312652710).

### Link to a public git repo demonstrating the problem:

Here's a super barebones repo that demos this problem. 

- `CustomButton` is an `AppCompatButton` that simply tries to set its font when constructed. Calling the constructor via Robolectric crashes.
- `CustomViewActivity` is an `AppCompatActivity` whose layout xml simply contains a `CustomButton`. Attempting to create an instance of the Activity via Robolectric crashes on layout inflation.
- `FontReferenceActivity` is an `AppCompatActivity` whose layout xml uses a regular `Button`, but sets `android:fontFamily="@font/vt323_regular"`. This does *not* crash when run via Robolectric.

https://github.com/ankushg/RobolectricFontResourcesTest

Is this a known issue? Any ideas for how to try to chase it down or work around it?

**Comment by ankushg** [comment]
For the time being, shadowing `ResourcesCompat` to make `getFont` return `Typeface.DEFAULT` makes things at least run, but it's definitely not idea.

**Comment by bdh2991** [comment]
@ankushg Do you have an example of how you shadowed the ResourcesCompat to work around this issue?  It does not seem to use the shadow class I've created when running the tests.

**Comment by ankushg** [comment]
@bdh2991 this is more or less the code I'm using: https://gist.github.com/ankushg/72b7f8ed88d64bf16c079314f5cd29b2

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by evant** [comment]
Still seeing this on 4.0 with binary resources enabled.

**Comment by jongerrish** [comment]
Let's add a test to CTEsque ResourcesTest to ensure this works like the framework.

**Comment by neworld** [comment]
Tried 4.0.2 version (with binary resources) and targeting 28 API,  still crashing:
```
android.content.res.Resources$NotFoundException: Font resource ID #0x7f080001 could not be retrieved.
	at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:342)
	at android.support.v4.content.res.ResourcesCompat.getFont(ResourcesCompat.java:207)
	at com.vinted.extensions.TypographyKt$FONT_400$1.invoke(typography.kt:26)
```

Crashing code:
```kotlin
ResourcesCompat.getFont(context, R.font.xxx_book)
```

Fonts are in `otf` format and `family_xxx.xml` is also included.

Also, fonts are included in `apk-for-local-test.ap_`.

Failure reason: [FAIL_REASON_FONT_LOAD_ERROR](https://developer.android.com/reference/android/support/v4/provider/FontsContractCompat.FontRequestCallback.html#FAIL_REASON_FONT_LOAD_ERROR)
> Constant returned by onTypefaceRequestFailed(int) signaling that the font returned by the provider was not loaded properly.

Logs:
```
    DEBUG: Loading classes from: file:/home/asemionovas/.m2/repository/org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar
    [Robolectric] com.vinted.views.common.VintedToggleTest.onSetCheckedWithIgnoringCallback_callbackIsCalled: sdk=28; resources=binary
    Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28                                                                                                                             
    failed load font, reason: -3
```

Maybe I could help you? Where is the best point to begin an investigation with debugger?

**Comment by nicusorflorin** [comment]
any progress here? i am facing the same issue

**Comment by casadogg** [comment]
> For the time being, shadowing `ResourcesCompat` to make `getFont` return `Typeface.DEFAULT` makes things at least run, but it's definitely not ideal, since some of our test logic relies on `Typeface` equality/inequality to verify that we're using the right fonts in our custom views.

I tried doing this using Robolectric 4, to no avail. Does anyone know if it's possible to configure shadows for a test in version 4?

**Comment by evant** [comment]
Works for me fine, added
```java
@Config(shadows = ShadowREsourcesCompat.class)
```
to the test class
where:
```java
@Implements(ResourcesCompat.class)
public class ShadowResourcesCompat {

   @Implementation
   public static Typeface getFont(@NonNull Context context, @FontRes int id) {
       return Typeface.DEFAULT;
   }

   @Implementation
   public static Typeface getFont(@NonNull Context context, @FontRes int id, TypedValue value,
                                  int style, @Nullable ResourcesCompat.FontCallback fontCallback) throws Resources.NotFoundException {
       return Typeface.DEFAULT;
   }
}
```

**Comment by jongerrish** [comment]
Fixed at https://github.com/robolectric/robolectric/commit/3f905f6823e14ab8907cddda52f3d72f5ef737d8

**Comment by iRYO400** [comment]
Hi! Get same error with a bit different stacktrace:
```
android.content.res.Resources$NotFoundException: Resource ID #0x7f090001

	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
	at android.content.res.Resources.getValue(Resources.java:1331)
	at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:337)
	at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:207)
```

in the build.gradle have
```
    testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }
...
    testImplementation 'org.robolectric:robolectric:4.1'
```

**Comment by arnavzoman** [comment]
Still getting this error with 4.0

**Comment by arnavzoman** [comment]
Works on 4.1

**Comment by ansman** [comment]
This is broken again when running against SDK 29 since ResourceCompat uses the `Font` instead of the Typeface APIs to load fonts on API 29+
