### ISSUE TITLE
how to change the path to settings.xml for robolectric?

### ISSUE THREAD

**Issue by Zar86** [robolectric/robolectric#3601]
### Description
I'm building a project using JenkinsCI. ***$HOME=/var/lib/jenkins***. The ***.m2*** folder is in ***$HOME***, the permissions limit the entry to all (drwxr-xr-x 2 root root .m2) (the project requirement, as the multibranch pipeline build). There is no ***settings.xml*** file in the ***.m2*** folder. As a result I get an error (see below). If I change the environment variable ****$HOME=/var/lib/jenkins/worckspace/myproject@tmp/****, I also create the ***.m2*** folder and put the ***settings.xml*** file in it, I still get an error.
How to force robolectric to download dependencies and look for the ***settings.xml*** file, where do I want it?
```
com.yodhaapp.dailyhoroscope.server.ChangeSetParserTest > jsonOnlyTokenTest STANDARD_OUT
    [WARNING] Unable to get resource 'org.robolectric:android-all:jar:6.0.1_r3-robolectric-0' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Specified destination directory cannot be created: /var/lib/jenkins/.m2/repository/org/robolectric/android-all/6.0.1_r3-robolectric-0
com.yodhaapp.dailyhoroscope.server.ChangeSetParserTest > jsonOnlyTokenTest STANDARD_ERROR
    Downloading: org/robolectric/android-all/6.0.1_r3-robolectric-0/android-all-6.0.1_r3-robolectric-0.jar from repository central at http://repo1.maven.org/maven2
com.yodhaapp.dailyhoroscope.server.ChangeSetParserTest > jsonOnlyTokenTest STANDARD_OUT
    [WARNING] Unable to get resource 'org.robolectric:android-all:jar:6.0.1_r3-robolectric-0' from repository central (http://repo1.maven.org/maven2): Specified destination directory cannot be created: /var/lib/jenkins/.m2/repository/org/robolectric/android-all/6.0.1_r3-robolectric-0### Steps to Reproduce
```
And why does robolectric ignore the change in the variable environment ***$HOME*** ???
### Steps to Reproduce
remove the file ***settings.xml*** from the ***~/.m2*** or ***$HOME/.m2*** folder
### Robolectric & Android Version
Robolectric 3.5.1 (also tried with 3.6-alpha-1)
Android Gradle Plugin 3.0.1 (also tried with 3.1.0-alpha-05)
Android Studio 3.0.1 (also tried with 3.1 Canary 5)
Android API 27

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and feel free to reopen this issue if it still exists. Thanks.
