### ISSUE TITLE
java.lang.ClassNotFoundException: Class android.view.DisplayInfo not found

### ISSUE THREAD

**Issue by ramack** [robolectric/robolectric#3630]
### Description
With 
```
android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
dependencies {
    androidTestImplementation 'junit:junit:4.12'
    androidTestImplementation 'org.robolectric:robolectric:3.6.1'
}
```
I get the following exception on "running" the test.
```
Error:java.lang.ClassNotFoundException: Class android.view.DisplayInfo not found
Error:Execution failed for task ':app:transformClassesWithDesugarForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /home/r/ActivityDiary/app/build/intermediates/transforms/stackFramesFixer/androidTest/debug/37.jar --output /home/r/ActivityDiary/app/build/intermediates/transforms/desugar/androidTest/debug/29.jar
[...]
--bootclasspath_entry /home/r/Android/Sdk/platforms/android-26/android.jar --bootclasspath_entry /home/r/Android/Sdk/platforms/android-26/optional/org.apache.http.legacy.jar --bootclasspath_entry /home/r/Android_Studio/jre/jre/lib/resources.jar --bootclasspath_entry /home/r/Android_Studio/jre/jre/lib/rt.jar --bootclasspath_entry /home/r/Android_Studio/jre/jre/lib/jsse.jar --bootclasspath_entry /home/r/Android_Studio/jre/jre/lib/jce.jar --bootclasspath_entry /home/r/Android_Studio/jre/jre/lib/charsets.jar --min_sdk_version 16 --desugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}
```

### Steps to Reproduce
Try to run the test.

### Robolectric & Android Version
Android Studio 3.0.1
Gradle 3.0.1
robolectric 3.6.1

### Link to a public git repo demonstrating the problem:
https://github.com/ramack/ActivityDiary
androidTest / MainActivityInstrumentedTest

**Comment by jongerrish** [comment]
Its failing because AS is running the desugar tool on your unit test depedencies, no idea why it is doing this because this code isn't intended for a device. DisplayInfo is part of the framework and not part of the SDK which is why this fails.

**Comment by ramack** [comment]
Thanks for the fast feedback, but I don't really get it. I see the same exception if I run gradlew connectedAndroidTest in the console. - Do you mean desugar is applied to robolectric while it shouldn't? (it is similar to #3537).
Maybe my try to integrate robolectric is completely wrong I and should remove
```androidTestImplementation 'junit:junit:4.12'```
from build.gradle? - but then it doesn't find @RunWith and in the robolectric samples this is also there. Could you take a look at my repository and tell me in case I integrated robolectric wrong?

If i change from Java 1_8 to 1_7 (which seems the simplest/only way to remove the desugar step) I get a lot of warnings
```warning: Ignoring InnerClasses attribute for an anonymous inner class```
and finally some exception like
```
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/r/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric/3.6.1/26cfb22e682110716ccd516da2f2851016b3efae/robolectric-3.6.1.jar
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
[...]
```

Any idea how I could progress?

**Comment by jongerrish** [comment]
Sorry, running for a flight but....

Yes, desugar should not be running on Robolectric library or tests as they
run on the local host.


Try changing androidTestImplementation to just testImplementation.

I think that will work. You want RE to just be a dependency for regular JVM
based tests not Android based tests.

**Comment by ramack** [comment]
Got it, thx. Moving with Robolectric usage from androidTestImplementation to testImplmentation push me forward. Thanks and sorry for the noise.

**Comment by grndvl1** [comment]
What if I am writing it in androidTest for a visual UI test?  how do I get this to work?
