### ISSUE TITLE
The wiki page "Running tests in Android Studio" is old.

### ISSUE THREAD

**Issue by mmktomato** [robolectric/robolectric#3638]
https://github.com/robolectric/robolectric/wiki/Running-tests-in-Android-Studio
`RobolectricGradleTestRunner` has been removed, for example.

It seems that it duplicates with the official "Getting Started" page (http://robolectric.org/getting-started/). So I think it's better to rewrite the content to "This page has moved!" like this wiki page: "https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide".

**Comment by jongerrish** [comment]
Sounds good. Mind sending a pull request?

**Comment by mmktomato** [comment]
How to send a pull request to the wiki repository? Simply edit by "Edit" button?

![wiki](https://user-images.githubusercontent.com/1475850/34323473-c7198d32-e88d-11e7-8edc-0b73a00151c5.jpg)

**Comment by jongerrish** [comment]
Removed that page.
