### ISSUE TITLE
Resources$NotFoundException is thrown when it needs to load an SVG resource with Robolectric using a "flavorDimensions" and "productFlavors".

### ISSUE THREAD

**Issue by marcellogalhardo** [robolectric/robolectric#3647]
### Description

**Resources$NotFoundException** is thrown when loading an SVG resource with Robolectric using a `flavorDimensions` and `productFlavors`.

Obs: I'm not sure if this is a problem of the Robolectric or Gradle...

_Related issues?_
-  AOSP: https://issuetracker.google.com/issues/65550419
- Robolectric: https://github.com/robolectric/robolectric/issues/3169

### Steps to Reproduce

1. Create a new project in Android Studio 3+;
2. Setup a `flavorDimensions` and two or more `productFlavors`;
3. Setup Robolectric;
4. Create a simple view with a SVG:
```
<?xml version="1.0" encoding="utf-8"?>
<Button xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/button"
    style="@style/Button"
    android:drawableLeft="@drawable/svg_compat"
    android:drawableStart="@drawable/svg_compat" />
```
5. Create a simple test that inflates this view using the ActivityController:
```
@RunWith(RobolectricTestRunner.class)
public class SvgTest {
    @Test
    public void testViewWithSvg() throws Exception {
        ActivityController<Activity> controller = Robolectric.buildActivity(Activity.class);
        LayoutInflater.from(controller.get()).inflate(R.layout.view_with_svg, null);
    }
}
```
5. Try to run it and see the exception: `android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f04002f in packages [android, org.robolectric.default]`
6. Remove flavors configuration. See the tests works properly.

### Robolectric & Android Version

- robolectric: 3.6.1
- gradle: 3.0.1
- compileSdkVersion: 26
- buildToolsVersion: 26.0.2
- minSdkVersion: 15
- targetSdkVersion: 25

### Link to a public git repo demonstrating the problem:

1. Clone this repository: https://github.com/marcellogalhardo/Robolectric-Resource-Not-Found
2. Execute the tests in SvgTest.testViewWithSVG.
3. See the exception.

**Comment by krishnasajja** [comment]
I'm also facing this issue. Is there a solution for this issue? Or a planned upcoming release to address this?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
