### ISSUE TITLE
Unit test with WifiManager throws NPE.

### ISSUE THREAD

**Issue by qsjh898** [robolectric/robolectric#3655]
### Description
I have codes below in my activity.
`WifiManager wifi = (android.net.wifi.WifiManager) getApplicationContext().getSystemService(android.content.Context.WIFI_SERVICE);
lock = wifi.createMulticastLock("videogo_multicate_lock");
lock.setReferenceCounted(true);
lock.acquire();`

In my unit test, `lock.acquire()` throws NPE because WifiManager.mService = null

### Robolectric & Android Version
Robolectric3.2.2

**Comment by jongerrish** [comment]
Hi,

The quickest way to get this fixed would be if you could send us a pull
request, I'd be happy to merge and get into 3.7 if you can.

**Comment by qsjh898** [comment]
But I have no minds to fix this bug. I just simply catch this NPE in my codes.

**Comment by jongerrish** [comment]
You're going to catch the NPE thrown by Robolectric tests in your
production code? Ok.

We'll try and fix this, but honestly, something that is not on our critical
path we really rely on contributions.
