### ISSUE TITLE
Display::getMetrics crashes with NullPointerException in 3.6.1

### ISSUE THREAD

**Issue by krygin** [robolectric/robolectric#3664]
### Description
Some my robolectric tests began to fall after robolectric update 3.4.2 -> 3.6.1 with NPE on Display::getMetics

### Steps to Reproduce
```
display = Shadow.newInstanceOf(Display::class.java)
shadowDisplay = Shadows.shadowOf(display)
shadowDisplay.width = width
shadowDisplay.height = height
shadowDisplay.setRealWidth(realWidth)
shadowDisplay.setRealHeight(realHeight)
shadowDisplay.density = density
displayMetrics = DisplayMetrics()
display.getMetrics(displayMetrics) //falls here
```
### Robolectric & Android Version
Running on Android 21 SDK
"org.robolectric:robolectric:3.6.1"
"org.robolectric:shadows-multidex:3.6.1"
Android 21sdk

**Comment by jongerrish** [comment]
I think the correct way to work with displays is:-

int displayId = ShadowDisplayManager.addDisplay("320w480h");

Then....

Display display = displayManager.getDisplay(displayId)

We fixed a lot of issues with Displays and Configuration in the last release to make the behaviour more consistent.
