### ISSUE TITLE
Using Roboletric with Mockito causes ClassCastException when attempting to mock Kotlin's function interfaces

### ISSUE THREAD

**Issue by matejdro** [robolectric/robolectric#3688]
### Description

When using Roboletric as test runner, mocking any Kotlin's function interfaces (`Function`, `Function1`, `Function2` etc.) will crash the test with this error:

```
ClassCastException occurred while creating the mockito mock :
  class to mock : 'kotlin.Function', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@15db9742'
  created class : 'kotlin.Function$MockitoMock$1478786546', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@38bb9d7a'
  proxy instance class : 'kotlin.Function$MockitoMock$1478786546', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@38bb9d7a'
  instance creation by : ObjenesisInstantiator
```

### Steps to Reproduce

With Kotlin's stdlib in the classpath, Execute following test;

```java
@RunWith(RobolectricTestRunner.class)
public class MockitoTest {
    @Test
    public void testFunctionMock()  {
        Mockito.mock(kotlin.Function.class);
    }
}
```

If I make local extension of these interfaces, for example like this:

```java
public interface DummyFunctionExtension extends kotlin.Function {}

@Test
public void testThatPasses() {
    Mockito.mock(DummyFunctionExtension.class);
}
```

then crash does not happen. So something weird is going on in relation to how Roboletric loads Kotlin's interfaces. Removing `RunWith` line also fixes that crash (by removing Roboletric out of the picture), but then obviously tests fail because Android's runtime is not present.

(Code was in Java for simplicity's sake, but of course writing it in Kotlin also crashes).

### Library versions

```gradle
dependencies {
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.20"
    testImplementation 'junit:junit:4.12'
    testImplementation "org.mockito:mockito-core:2.13.0"
    testImplementation "org.robolectric:robolectric:3.6.1"
}
```

### Link to a public git repo demonstrating the problem:

https://github.com/matejdro/MockitoRoboletricCrashDemo

(Just barebones Hello World application with tests added in)

**Comment by jameswald** [comment]
This is still failing in 4.2.1 although instead of a crash, the `invoke()` method call is not being registered by Mockito.

```
package com.example.test

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.Mockito.mock
import org.mockito.Mockito.verify

@RunWith(AndroidJUnit4::class)
class Issue3688Test {

    @Suppress("UNCHECKED_CAST")
    private val function = mock(Function1::class.java) as (String) -> Unit

    @Test
    fun test1() {
        function.invoke("test")
        verify(function).invoke("test")
    }

    @Test
    fun test2() {
        function.invoke("test")
        verify(function).invoke("foo")
    }
}
```

When the entire test case is run at once, test 1 passes and test 2 fails:

```
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
[Robolectric] com.example.test.Issue3688Test.test2: sdk=28; resources=BINARY

org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at com.example.test.Issue3688Test.test1(Issue3688Test.kt:18)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.
```

Both test 1 and test 2 pass when they are run individually, but test 2 should be failing because the argument is different.

**Comment by jameswald** [comment]
I see a similar issue on Robolectric 4.2.1 and 4.3: https://github.com/robolectric/robolectric/issues/5076. It doesn't crash, but the `invoke()` call is not being observed by Mockito.

**Comment by ZSmallX** [comment]
I added a PR https://github.com/robolectric/robolectric/pull/7086 to add tests to verify this question.

This issue can be solved by upgrading software infra ( can be seen in PR).

@matejdro Could you please help checking if it's still an issue?

**Comment by utzcoz** [comment]
Duplicate it to https://github.com/robolectric/robolectric/issues/5076. Feel free to reopen it if this problem has different root cause.

**Comment by matejdro** [comment]
Sorry I do not use neither robolectric or mockito anymore, so I cannot check.

**Comment by utzcoz** [comment]
> Sorry I do not use neither robolectric or mockito anymore (this issue is from 2018), so I cannot check.

Thanks for your reply. It's sad to hear that Robolectric will not work for you.
