### ISSUE TITLE
Remove ability to shadow Object.equals/hashCode/toString on subclasses

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#3692]
Currently a shadow can `@Implement` `equals(Object)`, `hashCode()`, and `toString()`, even if the shadowed class doesn't override them. This is misleading, since e.g. object equality doesn't correspond to actual behavior on Android.

This is enabled by `ClassInstrumentor.instrumentInheritedObjectMethod()`.

**Comment by jongerrish** [comment]
Fixed.
