### ISSUE TITLE
robolectric tests fail on JDK 9

### ISSUE THREAD

**Issue by cushon** [robolectric/robolectric#3693]
`SandboxTestRunner` assumes the system classloader is an instance of `URLClassLoader`:

https://github.com/robolectric/robolectric/blob/09a9c50714f80e31bed0cdcfbca20f2e1f3e5f24/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java#L137

From the [JDK 9 release notes](http://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html):

> The application class loader is no longer an instance of `java.net.URLClassLoader` (an implementation detail that was never specified in previous releases). Code that assumes that `ClassLoader::getSytemClassLoader` returns a `URLClassLoader` object will need to be updated. Note that Java SE and the JDK do not provide an API for applications or libraries to dynamically augment the class path at run-time.

This causes failures like:

```
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.robolectric.internal.SandboxTestRunner.getSandbox(SandboxTestRunner.java:137)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:214)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
```

**Comment by xian** [comment]
Fixed with 27250aca26d2f4ca320367c834096a2f57a3613e (around 3.7).
