### ISSUE TITLE
Unable to test Fragments of type android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by sanat51289** [robolectric/robolectric#3732]
### Description
Robolectric.buildFragment is a replacement for FragmentTestUtil class, but whats the replacement for SupportFragmentTestUtil?
I cant seem to find it.

### Steps to Reproduce
When I write Robolectric.buildFragment and pass a SupportFragment I see compilation issue, "no suitable method found"

### Robolectric & Android Version
Robolectric version 3.6.1

### Link to a public git repo demonstrating the problem:
Its very apparent, dont really need to show a code snippet, just try writing 
> Robolectric.buildFragment(SomeSupportFragment.class, new Bundle()).create().get()

**Comment by sanat51289** [comment]
Resolved it, had to include the following library as well to see SupportFragmentTestUtil

> testImplementation "org.robolectric:shadows-supportv4:${3.6.1}"

**Comment by ketanmadane** [comment]
@sanat51289 :  I'm facing same issue with Robolectric version 3.8.

**Comment by sanat51289** [comment]
@ketanmadane my issue got resolved 
when i included the following library, after which i started seeing SupportFragmentTestUtil

> testImplementation "org.robolectric:shadows-supportv4:3.6.1"

If you already tried that, can you post more details about your issue like stacktrace and stuff?
