### ISSUE TITLE
Bitmap#getPixel always returns 0

### ISSUE THREAD

**Issue by Kisty** [robolectric/robolectric#3743]
### Description
getPixel always returns 0 when using `BitmapFactory.decodeStream(stream)`

### Steps to Reproduce
Add coloured PNG to `test/assets/` or `test/resources/`

```
@Test
    public void getPixel() throws IOException {
        InputStream resourceAsStream = RuntimeEnvironment.application.getAssets().open("test.png");
        Bitmap bitmap = BitmapFactory.decodeStream(resourceAsStream);
        assertTrue(bitmap.getPixel(0, 0) > 0);
    }
```

### Robolectric & Android Version
Robolectric: `3.6.1`
compileSdkVersion: `25`
targetSdkVersion: `25`
Gradle: 4.5
Android Studio 3.1 Beta 1

### Link to a public git repo demonstrating the problem:
https://github.com/Kisty/deckard/tree/bug-bitmap-getPixel

**Comment by remmel** [comment]
Get same problem with robolectric 4.4. Note that bitmap.getWidth() returns good value

**Comment by utzcoz** [comment]
From the code, the robolectric uses the default the color array when using `BitmapFactory.decode*`, and it doesn't initialize the color array with real value.

**Comment by remmel** [comment]
Yes, the array is initialized and that's it `shadowBitmap.setPixels(new int[p.x * p.y], 0, 0, 0, 0, p.x, p.y);` in [ShadowBitmapFactory.create(,,,)](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java#L238)
