### ISSUE TITLE
ShadowMediaPlayer::setDataSource(Context, Uri) missing

### ISSUE THREAD

**Issue by SiebelsTim** [robolectric/robolectric#3754]
### Description
It appears that the ShadowMediaPlayer has various of `setDataSource` functions. Such as `setDataSource(Context, Uri, Map<String, String>)`. However, the overload of that function without the `Map` is missing. 

### Steps to Reproduce
```
        val uri = Uri.parse("dummy-test")
        val info = ShadowMediaPlayer.MediaInfo()
        val ds = toDataSource(RuntimeEnvironment.application, uri)
        ShadowMediaPlayer.addMediaInfo(ds, info)

        val mediaPlayer = MediaPlayer()
        mediaPlayer.setDataSource(RuntimeEnvironment.application, uri) // Crashes
        // java.io.IOException: setDataSource failed.
```

### Robolectric & Android Version
Robolectric: 3.6.1
Android: SDK 26

### Link to a public git repo demonstrating the problem:

Is "Steps to Reproduce" enough?

**Comment by mrkostua** [comment]
I had experience same problem. Temporary solution for me was to create Custom Shadow that extend ShadowMediaPlayer and create missing method like this :
 `@Implements(MediaPlayer.class)
public class MyShadowMediaPlayer extends ShadowMediaPlayer {
    @Implementation
    public void setDataSource(Context context, Uri uri) throws IOException {
        setDataSource(toDataSource(context, uri));

    }`

**Comment by jongerrish** [comment]
Can you send a PR? We'll get it merged quick for you.

**Comment by mrkostua** [comment]
yes 👍

**Comment by mrkostua** [comment]
@jongerrish Hi I have created a PR "fixed Issue 3754.." and experienced a problem "Some checks haven’t completed yet" can you help me with it? the changes in code are very simple.

**Comment by Adimote** [comment]
I'm getting this issue too,
@jongerrish, https://github.com/robolectric/robolectric/pull/3914 seems to fix this, are you able to merge?

**Comment by utzcoz** [comment]
This issue is fixed by https://github.com/robolectric/robolectric/pull/5074.
