### ISSUE TITLE
ShadowAppWidgetManager tracks installed widgets based on the provider's package, not the application package

### ISSUE THREAD

**Issue by tgsergeant** [robolectric/robolectric#3763]
### Description

Pretend I have a application with the package `com.example.app`, and it has a homescreen widget with the provider `com.example.app.widget.WidgetProvider`.

When I want to access the installed `widgetIds` from application code, I do

```java
  ComponentName component = new ComponentName(context, WidgetProvider.class);
  int appWidgetIds = AppWidgetManager.getInstance(context).getAppWidgetIds(component);
```

Then, in my test code I want to be able to install a widget so that it shows up in `appWidgetIds`:

```java
ShadowAppWidgetManager = ...;
shadowAppWidgetManager.createWidget(WidgetProvider.class, R.layout.widget_layout);
triggerApplicationCode();
```

*However*, [`ShadowAppWidgetManager`](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowAppWidgetManager.java) tracks widgets based on the Provider's package:

```java
      String packageName = appWidgetProvider.getClass().getPackage().getName();
      String className = appWidgetProvider.getClass().getName();
      providerComponent = new ComponentName(packageName, className);
```

This means that the test code *creates* widgets in the `com.example.app.widget` package, but the application code reads the widgets from the `com.example.app` package. The result is that no widgets are found and the test fails.

I think the solution here is to change `ShadowAppWidgetManager` to construct `WidgetInfo` using the  `context` here: https://github.com/robolectric/robolectric/blob/86e6f8588b3de2b4b7ac7e24d39abb16d6227dc2/shadows/framework/src/main/java/org/robolectric/shadows/ShadowAppWidgetManager.java#L275

As far as I can tell, this is what the framework expects: It wants the package to be the application package, not the specific Java package.

I'm happy to send a CL for this myself, but wanted to check first: Is this the correct solution? Is this a safe change to make? Thanks!

### Robolectric & Android Version

Latest

### Link to a public git repo demonstrating the problem:

None, sorry

**Comment by mhozza** [comment]
+1
