### ISSUE TITLE
Make robolectric.bzl configurable 

### ISSUE THREAD

**Issue by dkelmer** [robolectric/robolectric#3769]
It's unlikely that Bazel users will want all API levels of the android-all jars. Create a way for them to select the ones they want. See here for a possible way to do this: https://github.com/swe-zzf/grpc-java/blob/29befc131d821347fb10a9c86eb3893fed2b18ff/repositories.bzl

**Comment by dkelmer** [comment]
I can't seem to assign this to me, but that was my intention :)

**Comment by utzcoz** [comment]
@dkelmer robolectric.bzl has been moved to https://github.com/robolectric/robolectric-bazel. If you have any questions about robolectric-bazel, please file a new issue at https://github.com/robolectric/robolectric-bazel.
