### ISSUE TITLE
Unable to find resource ID

### ISSUE THREAD

**Issue by geekanamika** [robolectric/robolectric#3776]
### Description
I have tried all the solution in #3169 . It still doesn't works for me.
Adding  *android.enableAapt2=false in gradle.properties works smoothly. 

## Steps 
1. `testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }`  in build.gradle (app) 
2. I am not using @config in my tests.
3. buildTypes doesn't contain debug (It means applicationSuffixId is not set to .debug )
  
`buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }` 

### Robolectric & Android Version
Robolectric version : 3.3.1
Android studio : 3.0.1 stable
Gradle : 3.0.1

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
