### ISSUE TITLE
ShadowAudioManager does not support STREAM_ACCESSIBILITY

### ISSUE THREAD

**Issue by mattmikolay** [robolectric/robolectric#3797]
### Description
`ShadowAudioManager` does not support the `STREAM_ACCESSIBILITY` type added in API 26, which means methods like `setStreamVolume` and `getStreamVolume` do not work as expected with `STREAM_ACCESSIBILITY`. This inhibits thorough testing of accessibility services which modify the device's accessibility audio volume.

The fix for this should be simple — I'll post a pull request shortly.

### Robolectric & Android Version
Robolectric 3.8-SNAPSHOT
Android 27

**Comment by MGaetan89** [comment]
I'm closing this issue, since it was implemented in Roboletric 4.12 via https://github.com/robolectric/robolectric/commit/d023d2463935eedded41f599b9b77f3fe65d38d2.
