### ISSUE TITLE
ShadowAudioManager does not support AudioFocusRequest

### ISSUE THREAD

**Issue by mattmikolay** [robolectric/robolectric#3799]
### Description
On API 26+, audio focus should be requested via [`AudioManager#requestAudioFocus(AudioFocusRequest)`](https://developer.android.com/reference/android/media/AudioManager.html#requestAudioFocus(android.media.AudioFocusRequest)), which accepts an [`android.media.AudioFocusRequest`](https://developer.android.com/reference/android/media/AudioFocusRequest.html) parameter. Robolectric's `ShadowAudioManager` does not shadow these focus request methods added in API 26, which makes testing certain audio-related code more difficult.

The following methods should be shadowed in `ShadowAudioManager`:
* [`AudioManager#requestAudioFocus(AudioFocusRequest)`](https://developer.android.com/reference/android/media/AudioManager.html#requestAudioFocus(android.media.AudioFocusRequest))
* [`AudioManager#abandonAudioFocusRequest(AudioFocusRequest)`](https://developer.android.com/reference/android/media/AudioManager.html#abandonAudioFocusRequest(android.media.AudioFocusRequest))

I will gladly work up a pull request for this, but I figure there needs to be some discussion regarding how these changes should be made. Currently, `ShadowAudioManager` defines [an inner class](https://github.com/robolectric/robolectric/blob/987936679a09285d5339a92524f63e7306e31c8f/shadows/framework/src/main/java/org/robolectric/shadows/ShadowAudioManager.java#L195-L205), also called `AudioFocusRequest`, and this name will conflict with `android.media.AudioFocusRequest`. This will make the expected return type of [`getLastAudioFocusRequest()`](https://github.com/robolectric/robolectric/blob/987936679a09285d5339a92524f63e7306e31c8f/shadows/framework/src/main/java/org/robolectric/shadows/ShadowAudioManager.java#L183-L185) unclear.

If possible, I believe we should modify `ShadowAudioManager` to keep track of requests for audio focus internally using `android.media.AudioFocusRequest`. When audio focus is requested via the [pre-API 26 requestAudioFocus][pre26], we can synthesize the corresponding instance of `android.media.AudioFocusRequest` and save its reference. We can then provide an API for pre-26 clients that does not expose `android.media.AudioFocusRequest`, but reads the stored request's attributes.

### Robolectric & Android Version
Robolectric 3.8-SNAPSHOT
Android 27

[pre26]: https://developer.android.com/reference/android/media/AudioManager.html#requestAudioFocus(android.media.AudioManager.OnAudioFocusChangeListener,%20int,%20int)

**Comment by jongerrish** [comment]
Looks like this support has been added now.
