### ISSUE TITLE
Caching robolectric initialization over multiple test classes

### ISSUE THREAD

**Issue by matejdro** [robolectric/robolectric#3800]
I have noticed that vast majority of the test time by Robolectric is spent in initializing the Robolectric itself (before the first test). After that, test methods inside that class are executed very fast.

However, for the next test class, Robolectric initialization starts again from scratch, resulting in pretty long test time if there are many different test classes.

I wonder if Robolectric instance could somehow be cached and reused on the next test class? Test isolation is already supposed to be per-method and all methods inside same class reuse same Robolectric, so I don't see that as an issue.

**Comment by xian** [comment]
Most of the initialization time is spent instrumenting the Android framework code and loading the system resources, which both happen once per API level and are cached for the rest of the tests. Maybe your test suite runs against multiple API levels and you're noticing the cost of loading each one?

Closing for now, feel free to reopen.

**Comment by xian** [comment]
@OleksandrKucherenko A lot of that time is actually spent in Robolectric's old custom resource loading, which will go away in 4.0.
