### ISSUE TITLE
how can i do test for singleton with robolectric

### ISSUE THREAD

**Issue by qiangxi** [robolectric/robolectric#3802]
### Description
i have some code like this:
```java
public class Singleton {
    private static Singleton INSTANCE;

    public static Singleton getInstance() {
        if (INSTANCE == null){
            synchronized (Singleton.class){
                if (INSTANCE==null){
                    INSTANCE = new Singleton();
                }
            }
        }
        return INSTANCE;
    }

    public static void someMethods1() {

    }

    public void someMethods2() {

    }
}
```
for some reason,i have to shadow the `Singleton`, my code like this :
```java
@Implements(value =Singleton.class)
public class ShadowSingleton {
    private static Singleton INSTANCE;

    @Implementation
    public static Singleton getInstance() {
       return Singleton.getInstance();
    }

    @Implementation
    public static void someMethods1() {

    }
    @Implementation
    public void someMethods2() {

    }
}
```
i want to rewrite `getInstance()` method ,but i don't know how to do ?   because i always get some error,like `StackOverflowError`.
 so ,who can help me ? thanks~

**Comment by qsjh898** [comment]
There is no need for you to rewrite `getInstance()`. After you shadow the Singleton, its default constructor has been replaced by `ShadowSingleton`. Which means `Singleton.getInstance()` will return an instance of ShadowSingleton in your unit test.

**Comment by xian** [comment]
We don't recommend that you shadow your own code; shadows are really intended only for Android framework code. What are you trying to accomplish with ShadowSingleton?

**Comment by hoisie** [comment]
Have you tried ReflectionHelpers?

```java
    @Implementation
    public static Singleton getInstance() {
       return ReflectionHelpers.newInstance(Singleton.class);
    }
```

Keep in mind that if you're shadowing non-Android code, you have to declare the package as being instrumented. That means all other classes with the same package will be instrumented.

**Comment by qiangxi** [comment]
it works ,thanks very much @hoisie  ,` ReflectionHelpers`  resolved `StackOverflowError` ,let me can shadow Singleton normally, very Grateful ~
