### ISSUE TITLE
ParallelUniverse.resetStaticState() is called before and after tests

### ISSUE THREAD

**Issue by cesar1000** [robolectric/robolectric#3804]
Resetting the static state before and after each test looks unnecessary, assuming that tests run in their own process (as it's the case with gradle). In what situation would it be relevant that the state is not reset after the last test?

In my profiling, I found the static state reset to take ~8% of the test execution time, so removing this call makes a noticeable difference.

**Comment by jongerrish** [comment]
Yeah, there's no way we need to do this twice. Which one did you remove and
did it have any side effects to your test corpus?

**Comment by cesar1000** [comment]
I removed the reset that happens after the test (https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L359), on the assumption that a subsequent test will reset state, and a reset after the last test won't matter anyway. I didn't see any side effect while running our tests, but in my profile the reset time went down from 8% to 3% :)
