### ISSUE TITLE
Robolectric doesn't work if Target to "P"

### ISSUE THREAD

**Issue by XinyueZ** [robolectric/robolectric#3812]
As the new preview of API "P" of Android has been released, the try with target-api "P" can not be used if Robolectric runs.

Some errors:

`    java.lang.NumberFormatException: For input string: "P"`
or
`java.lang.NoSuchMethodError: android.app.Application.getColor(I)I`

**Comment by jongerrish** [comment]
We'll have a release supporting the P dev preview out next week 😃

**Comment by XinyueZ** [comment]
OK, look forward

**Comment by jongerrish** [comment]
I'm not sure if we handle "P" as the target SDK, which is legit for
prerelease sdks. We use the framework manifest parsing code now (opt in)
but I'm not sure if that handles it, or the tool chain is supposed to
replace it. I'll check next week and make sure we have something usable.
