### ISSUE TITLE
Improve documentation on using robolectric.offline

### ISSUE THREAD

**Issue by markcerqueira** [robolectric/robolectric#3815]
### Description
The System Properties section of [Configuring Robolectric][1]  describes configuring Robolectric with `robolectric.offline` and `robolectric.dependency.dir` but there aren't clear steps as to how one would go about downloading all the required dependencies.

### Steps to Reproduce
N/A

### Robolectric & Android Version
N/A

### Link to a public git repo demonstrating the problem:
N/A

Thank you!

[1]: http://robolectric.org/configuring/

**Comment by utzcoz** [comment]
Duplicated to https://github.com/robolectric/robolectric.github.io/issues/117.
