### ISSUE TITLE
roboelectric-samples does not work

### ISSUE THREAD

**Issue by christopheblin** [robolectric/robolectric#3824]
### Description

After many hours trying to setup the roboelectric-samples, I successed !

This should be a lot simpler to setup as this is the official sample :)

### Steps to Reproduce
git clone https://github.com/robolectric/robolectric-samples.git

open the project in Android Studio 3.0.1 and run a test

I expect that the test run and pass the first time

Among the problems I had :
* needed to download all the SDKs and build tools -> I think that this can not be avoided but maybe a readme in the repo can provide more help
* needed to create a file gradle.properties with android.enableAapt2=false otherwise I had a strange java.lang.NullPointerException at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:39)
* $MODULE_DIR$ in Run configurations > Default > JUnit
* needed to upgrade gradle version to 4.1 which is supported by AS3.0.1

In the end, note that if you change 

    ext {
        robolectricVersion = "3.7.1"
    }

the project does not compile anymore (I've not investigated why)...

### Robolectric & Android Version

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

**Comment by utzcoz** [comment]
The robolectric-sample is not supported anymore. I will close it.
