### ISSUE TITLE
AutofillManager prevents test from running

### ISSUE THREAD

**Issue by ClaudeHangui** [robolectric/robolectric#3828]
### Description
I cannot get Roboelectric ShadowConnectivityManagerTest test to run. I stumble on the class AutofillManager which is inaccessible

### Steps to Reproduce
- Declare the ConnectivityManager, ShadowConnectivityManager, ShadowNetworkInfo as global variable in the test.
- Take the setUp() method as-is from the roboelctric repository
- Take the getActiveNetworkInfo_shouldInitializeItself() as-is from the Roboelectric repository
- Run the test using RobolectricTestRunner

### Robolectric & Android Version

Roboelectric version : 3.7.1
Android version : 

### Link to a public git repo demonstrating the problem:
[https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowConnectivityManagerTest.java](url)

**Comment by saadfarooq** [comment]
Robolectric 3.7 requires compileSdkVersion to be 27.
