### ISSUE TITLE
Hardware dependency

### ISSUE THREAD

**Issue by suzuesh** [robolectric/robolectric#3832]
import android.support.car.Car
This can not be new

Because there is hardware dependence.

I want to put fake hardware information in context.
Is it possible?

### Steps to Reproduce
[Test Target]
public void Target() {
        mCarApiClient = Car.createCar(this, mCarConnectionCallback);
        mCarApiClient.connect();
    }

[Car Class]    
private Car(Context context, CarConnectionCallback carConnectionCallback, @Nullable Handler handler) {
        this.mContext = context;
        this.mCarConnectionCallback = carConnectionCallback;
        if(handler == null) {
            Looper looper = Looper.getMainLooper();
            handler = new Handler(looper);
        }

        this.mEventHandler = handler;
        if(!this.mContext.getPackageManager().hasSystemFeature("android.hardware.type.automotive")) {
            this.mCarServiceLoader = new CarServiceLoaderEmbedded(context, this.mCarConnectionCallbackProxy, this.mEventHandler);
        } else {
            this.mCarServiceLoader = new CarServiceLoaderEmbedded(context, this.mCarConnectionCallbackProxy, this.mEventHandler);
        }

    }

**Comment by utzcoz** [comment]
@suzuesh You can use latest Robolectric and refer to https://cs.android.com/android/platform/superproject/+/master:packages/apps/Car/Settings/tests/robotests/src/com/android/car/settings/testutils/ShadowCar.java.
