### ISSUE TITLE
This method should only be called by Robolectric when running all tests

### ISSUE THREAD

**Issue by dbottillo** [robolectric/robolectric#3836]
### Tests fail when run from command line
I have a bunch of tests related to a database (so no UI) that are failing when I run through the command line. They all fail with:
```
java.lang.IllegalStateException: this method should only be called by Robolectric
	at org.robolectric.shadows.ShadowDisplayManager.configureDefaultDisplay(ShadowDisplayManager.java:43)
	at org.robolectric.android.Bootstrap.setUpDisplay(Bootstrap.java:19)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:159)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:335)
```

### Steps to Reproduce
If I run the tests from a specific class from AS they are all green. Also all those failing tests are inside the package `database` and if I run all the tests of that package in AS they are still green. It only doesn't work when I run `./gradlew testDebugUnitTest` of if I select `testDebugUnitTest` from AS.

### Robolectric & Android Version
```
testImplementation "junit:junit:4.12"
testImplementation "org.mockito:mockito-core:2.1.0"
testImplementation "org.robolectric:robolectric:3.8"
testImplementation "com.nhaarman:mockito-kotlin:1.5.0"
```

### Example
All the tests are very similar, they all test the database:
```
@RunWith(RobolectricTestRunner::class)
class SetDataSourceTest {

    private lateinit var underTest: SetDataSource
    private lateinit var databaseHelper: DatabaseHelper

    @Before
    fun setup() {
        mtgDatabaseHelper = DatabaseHelper(RuntimeEnvironment.application)
        underTest = SetDataSource(databaseHelper.writableDatabase)
    }

    @After
    fun close_data_helper() {
        databaseHelper.close()
    }
    @Test
    fun sets_can_be_retrieved_from_database() {
        val sets = underTest.sets
        assertNotNull(sets)
        assertThat(sets.size, `is`(100)
    }
}
```

**Comment by dbottillo** [comment]
I found the issue, when run from the command line they are using the real application class and there was a problem with `LeakCanary` library. I had to write a custom application and avoid to init that library, I guess when you run a single test on AS it doesn't use the real application. A better log from Robolectric would also have been better!

**Comment by bernardo-macedo** [comment]
I have a similar issue, it started after I upgraded the gradle to 4.4 and Android Studio to version 3.1.

But it runs fine from the command line, and fails when run from Android Studio

**Comment by Murtaza0xFF** [comment]
Any updates/workarounds for this?

**Comment by Murtaza0xFF** [comment]
For me the tests pass on AS, but they fail with this error when those exact same tests are run on Circleci.

**Comment by eschlenz** [comment]
I just ran across this issue as well, but found a solution. I had the exact same stack trace. I've been migrating our application from GCM to FCM, which involved removing GCM libraries and upgrading google play services dependencies. My tests were failing on the command line, but not from within AS.

We have a `TestApp` that extends from our `App` (Application) class, for our tests. In there, we've done a number of things to get our tests to play nicely with Robolectric.

On a hunch, I commented out this line:

```
GoogleAnalytics.getInstance(this).setAppOptOut(true);
```

**And.... it worked! All my tests pass now!** 

Gradle version: 2.2.1
Gradle Android build tools version: 3.1.2
Mockito: 2.18.3
Robolectric: 3.4-rc2

**Comment by neworld** [comment]
In latest Robolectric 4.0.2, I found, this exception appears if `TestMyApplication` crashes inside `onCreate()`. You could easily reproduce it by:

```java
class TestMyApplication(): MyApplication {
  @Override
  public void onCreate() {
    throw new IllegaleStateException("Random crash");
  }
}
```

I suppose, robolectric should crash with real cause, which would be very helpful.

**Comment by matpag** [comment]
If you have zero configuration to perform in your `Application` class the fastest solution is this:

```
@RunWith(AndroidJUnit4::class)
@Config(application = Application::class)
class MyFragmentTestRobo {
   //your tests
}
```
This information is useful for Roboelectric novices like me.

**Comment by vfediuchko** [comment]
My solution is next : 
1. create the function in MyApp class 
"protected open fun  initFirebase(){
//do all Firebase related initialization here
 }"
2. in TestApp class do override this fun with empty body:
override  fun initFirebase(){
//NOP
}
this is it , run your tests
