### ISSUE TITLE
NullPointerException, when the app project code invoke the Library module `s  method

### ISSUE THREAD

**Issue by 09xuanjian** [robolectric/robolectric#3854]
### 
Main
|_ mainProject

|_ Library

|_ Settings.gradle

I have included Robolectric 3.8 in my project and I've created a unit test.  The problem is that every test fails (NullPointerException)  because my project has  several Library codes and the mainProject will invoke the method from library module  .  but that cannot be invoking from the unit tests.  In the UI thread is OK ,  but invoke in the sub-thread, it throw NullPointerException.

with this problem, how can i do? 

Expect robolectric reply,   thank you very much.

**Comment by jongerrish** [comment]
You'll need to include more information ;-)   ... like the stack trace would be a good start.

Have you followed the instructions here for Gradle?:- http://robolectric.org/getting-started/
