### ISSUE TITLE
[gradle plugin] local maven/gradle Proxy settings won't work while robolectric execution.

### ISSUE THREAD

**Issue by marslo** [robolectric/robolectric#3856]
### Description
Due to our build machine situation. There's no internet connection. All plugins, dependencies and packages come from intranet cache/repo server. we are using the Artifactory for it.

### Steps to Reproduce
`$ gradle --full-stacktrace --refresh-dependencies clean assembleRelease testDebugUnitTest --debug --info`
Error shows as below:
```
...
Successfully started process 'Gradle Test Executor 1'
Initialized native services in: /home/myadmin/.gradle/native
Gradle Test Executor 1 started executing tests.

com.myfeature.ApiSignUnitTest > apiSign_isCorrect STANDARD_ERROR
    Downloading: org/robolectric/android-all/8.0.0_r4-robolectric-r1/android-all-8.0.0_r4-robolectric-r1.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
    Error transferring file: Connection timed out (Connection timed out)

com.myfeature.ApiSignUnitTest > apiSign_isCorrect STANDARD_OUT
    [WARNING] Unable to get resource 'org.robolectric:android-all:pom:8.0.0_r4-robolectric-r1' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: Connection timed out (Connection timed out)

com.myfeature.ApiSignUnitTest > apiSign_isCorrect STANDARD_ERROR
    Downloading: org/robolectric/android-all/8.0.0_r4-robolectric-r1/android-all-8.0.0_r4-robolectric-r1.pom from repository central at http://repo1.maven.org/maven2
    Error transferring file: Connection timed out (Connection timed out)

com.myfeature.ApiSignUnitTest > apiSign_isCorrect STANDARD_OUT
    [WARNING] Unable to get resource 'org.robolectric:android-all:pom:8.0.0_r4-robolectric-r1' from repository central (http://repo1.maven.org/maven2): Error transferring file: Connection timed out (Connection timed out)
...
com.myfeature.ApiSignUnitTest > apiSign_isCorrect FAILED
    Unable to resolve artifact: Missing:
    ----------
    1) org.robolectric:android-all:jar:8.0.0_r4-robolectric-r1

      Try downloading the file manually from the project website.

      Then, install it using the command:
          mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=8.0.0_r4-robolectric-r1 -Dpackaging=jar -Dfile=/path/to/file

      Alternatively, if you host your own repository you can deploy the file there:
          mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=8.0.0_r4-robolectric-r1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

      Path to dependency:
      	1) org.apache.maven:super-pom:pom:2.0
      	2) org.robolectric:android-all:jar:8.0.0_r4-robolectric-r1

    ----------
    1 required artifact is missing.

    for artifact:
      org.apache.maven:super-pom:pom:2.0

    from the specified remote repositories:
      central (http://repo1.maven.org/maven2),
      sonatype (https://oss.sonatype.org/content/groups/public/)

        Caused by:
        org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
        ----------
        1) org.robolectric:android-all:jar:8.0.0_r4-robolectric-r1

          Try downloading the file manually from the project website.

          Then, install it using the command:
              mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=8.0.0_r4-robolectric-r1 -Dpackaging=jar -Dfile=/path/to/file

          Alternatively, if you host your own repository you can deploy the file there:
              mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=8.0.0_r4-robolectric-r1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

          Path to dependency:
          	1) org.apache.maven:super-pom:pom:2.0
          	2) org.robolectric:android-all:jar:8.0.0_r4-robolectric-r1

        ----------
        1 required artifact is missing.

        for artifact:
          org.apache.maven:super-pom:pom:2.0

        from the specified remote repositories:
          central (http://repo1.maven.org/maven2),

2 tests completed, 1 failed
          sonatype (https://oss.sonatype.org/content/groups/public/)
```

The build.gradle as below:
```
buildscripts {
    repositories {
        maven {
            url 'http://my.artifactory.com/artifactory/gradle'
        }
    }
}
...
allprojects {
    repositories {
        maven {
            url 'http://my.artifactory.com/artifactory/gradle'
        }
    }
}
...
android {
    testCompile "org.robolectric:robolectric:3.6.1"
}
...
```

### Others:
The `~/.gradle/gradle.properties`:
```
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx2048M
systemProp.http.proxyHost=192.168.1.2
systemProp.http.proxyPort=123
systemProp.https.proxyHost=192.168.1.2
systemProp.https.proxyPort=123
systemProp.http.nonProxyHosts=*.mycompany.com|localhost
systemProp.https.nonProxyHosts=*.mycompany.com|localhost
artifactory_contextUrl=http://my.artifactory.com/artifactory
systemProp.sonar.host.url=http://my.sonar.com
systemProp.sonar.login=xxxxxxxxxxxxxxxxxxxxxxxxxx
```

robolectric in `~/.gradle`:
```
$ find ~/.gradle -name "*robolectric*"
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/8.0.0_r4-robolectric-r1
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/8.0.0_r4-robolectric-r1/30f97bebb50be3a1af9e12cb999360e1cdd2aaa5/android-all-8.0.0_r4-robolectric-r1.jar
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/8.0.0_r4-robolectric-r1/b6f839c158ec9d0044c95f1db5a540a9f5f248e3/android-all-8.0.0_r4-robolectric-r1.pom
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric/3.6.1/26cfb22e682110716ccd516da2f2851016b3efae/robolectric-3.6.1.jar
/home/myadmin/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric/3.6.1/cb01d1161d258693d5efe1a8fbc1e6185cecb76e/robolectric-3.6.1.pom
/home/myadmin/.gradle/caches/modules-2/metadata-2.23/descriptors/org.robolectric
/home/myadmin/.gradle/caches/modules-2/metadata-2.23/descriptors/org.robolectric/android-all/8.0.0_r4-robolectric-r1
/home/myadmin/.gradle/caches/modules-2/metadata-2.23/descriptors/org.robolectric/robolectric
```

The proxy settings:
```
$ echo $http_proxy
http://192.168.1.2:123
$ echo $https_proxy
http://192.168.1.2:123
$ echo $ftp_proxy
http://192.168.1.2:123
```

The connection situation:
```
$ curl https://oss.sonatype.org/content/groups/public/  | head -15
<html>
  <head>
    <title>Index of /groups/public</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="icon" type="image/png" href="https://oss.sonatype.org/favicon.png">
    <!--[if IE]>
    <link rel="SHORTCUT ICON" href="https://oss.sonatype.org/favicon.ico"/>
    <![endif]-->

    <link rel="stylesheet" href="https://oss.sonatype.org/static/css/Sonatype-content.css?2.14.8-01" type="text/css" media="screen" title="no title" charset="utf-8">
  </head>
  <body>
    <h1>Index of /groups/public</h1>

$ curl http://repo1.maven.org/maven2 | head -10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   313  100   313    0     0    944      0 --:--:-- --:--:-- --:--:--   942
<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<h1>302 Moved Temporarily</h1>
<ul>
<li>Code: Found</li>
<li>Message: Resource Found</li>
<li>RequestId: 198001E6C2630EF9</li>
<li>HostId: maq+i8mADh4Zv5phhVTStg2dukFigpgJTPBsNGiLvR4rpwTShYenqCt1XdSGWREUhTIcmD0L/VU=</li>
</ul>
```

Maven settings.xml for Artifactory:
```
$ grep -C 1 artifactory ~/.m2/settings.xml
          <name>libs-release</name>
          <url>http://my.artifactory.com/artifactory/libs-release</url>
        </repository>
--
          <name>libs-snapshot</name>
          <url>http://my.artifactory.com/artifactory/libs-snapshot</url>
        </repository>
--
          <name>libs-release</name>
          <url>http://my.artifactory.com/artifactory/libs-release</url>
        </pluginRepository>
--
          <name>libs-snapshot</name>
          <url>http://my.artifactory.com/artifactory/libs-snapshot</url>
        </pluginRepository>
      </pluginRepositories>
      <id>artifactory</id>
    </profile>
--
  <activeProfiles>
    <activeProfile>artifactory</activeProfile>
  </activeProfiles>
```

**Comment by emartynov** [comment]
Hey, we also use own maven repo.

Here is how we setup the Robolectric tests:
```  testOptions {
    unitTests {
      returnDefaultValues = true
      includeAndroidResources = true

      all {
        systemProperty 'robolectric.dependency.repo.url', <url to maven>
        systemProperty 'robolectric.dependency.repo.id', 'nexus'
      }
    }
```

The documentation about it is here http://robolectric.org/configuring/

**Comment by Marslo** [comment]
Thanks @emartynov , it works for me!!! You can close this issue.

**Comment by JehandadK** [comment]
I dont have a mirror. I want it to work with proxy. But .m2/settings.xml file is no avail. It gets ignored when I run tests.

**Comment by lgleasain** [comment]
I'm using Robolectric 4.2 and having an issue getting it to use the alternate URL Below are my configuration and the errors I'm getting.  From what I can see even-though I have the robolectric.dependency.repo.url defined it is still going to sonatype and maven.  Does anybody know what is causing this?

-------------------------------------------------------------------------------------------------------------------------------------

testOptions {

    unitTests {
        includeAndroidResources = true
        all {
            systemProperty 'robolectric.dependency.repo.url', 'https://svdlknxtgapp02.servers.global.prv/artifactory/maven-central'
            systemProperty 'robolectric.dependency.repo.id', 'local'
            systemProperty 'robolectric.offline', 'true'
        }
    }
}

 

 

Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/

Error transferring file: Operation timed out (Connection timed out)

[WARNING] Unable to get resource 'org.robolectric:android-all:pom:9-robolectric-4913185-2' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: Operation timed out (Connection timed out)

Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.pom from repository central at http://repo1.maven.org/maven2

Error transferring file: Operation timed out (Connection timed out)

[WARNING] Unable to get resource 'org.robolectric:android-all:pom:9-robolectric-4913185-2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Operation timed out (Connection timed out)

Downloading: org/robolectric/android-all/9-robolectric-4913185-2/android-all-9-robolectric-4913185-2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/

Transferring 118099K from sonatype

 

 

 

 

apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.elavon.threedstwo"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {

        unitTests {
            includeAndroidResources = true
            all {
                systemProperty 'robolectric.dependency.repo.url', 'https://svdlknxtgapp02.servers.global.prv/artifactory/maven-central'
                systemProperty 'robolectric.dependency.repo.id', 'local'
                systemProperty 'robolectric.offline', 'true'
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.1'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
    implementation project(':threedstwolib')

    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'

    testImplementation 'org.robolectric:robolectric:4.2'
    testImplementation 'androidx.test:runner:1.1.1'
    testImplementation 'androidx.test.ext:junit:1.1.0'
    testImplementation 'junit:junit:4.12'
    testImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

// dokka: comment this section out when generating Dokka documentation.
repositories {
    mavenLocal()
    maven {
        url 'https://svdlknxtgapp02.servers.global.prv/artifactory/plugins-release'
    }
    maven {
        url 'https://svdlknxtgapp02.servers.global.prv/artifactory/libs-release'
    }
    maven {
        url 'https://svdlknxtgapp02.servers.global.prv/artifactory/libs-snapshot'
    }
    maven {
        url 'https://svdlknxtgapp02.servers.global.prv/artifactory/maven-google'
    }
    maven {
        url 'https://svdlknxtgapp02.servers.global.prv/artifactory/jetbrains-remote'
    }
    maven {
        url 'https://svdlknxtgapp02.servers.global.prv/artifactory/maven-central'
    }
}

**Comment by mezpahlan** [comment]
@lgleasain Same with me. I'm running this on Windows using Android Studio 3.4, Android Gradle Plugin 3.4, Gradle 5.1.1, Robolectric 4.2.1. Whatever I do I can't get these system properties to work as they have been documented.

**Comment by antonkazakov** [comment]
Hi. Any updates on this? Using robolectric 3.8 - same issues

**Comment by wujingchao** [comment]
I found a solution:  (robolectric:4.3)

```
class MavenCentralRobolectricTestRunner(clazz : Class<Any>)  : RobolectricTestRunner(clazz) {


    companion object {
        init {
            MavenRoboSettings.setMavenRepositoryId("local")
            MavenRoboSettings.setMavenRepositoryUrl("https://maven.aliyun.com/nexus/content/groups/public/")
        }
    }

}
```

use this TestRunner for your Tester

**Comment by adamszewe** [comment]
Check my answer here in the other issue for a gradle-only solution that works both from command line and android studio:
https://github.com/robolectric/robolectric/issues/5305#issuecomment-774760930

**Comment by utzcoz** [comment]
IIRC, some friends have tried these proxy settings, and they worked fine. Please try the latest Robolectric, and feel free to reopen it if still exists.
