### ISSUE TITLE
AnnotationFormatError when migrating to 3.8

### ISSUE THREAD

**Issue by ycoupe** [robolectric/robolectric#3861]
### Description
When I run my test with the Run button, I got the error : 
`Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()`

When I run with the command ./gradlew test, the problem is not here.

### Steps to Reproduce
Run the test with the Run button.

Remove the .gradle directory not work for me.

### Robolectric & Android Version
robolectric                 : '3.8',
buildToolsVersion      : '27.0.3',
compileSdkVersion   : 27,
minSdkVersion          : 19,
targetSdkVersion      : 27

Thanks

**Comment by utzcoz** [comment]
Please try the latest Robolectric and feel free to reopen this issue if it still exists.
