### ISSUE TITLE
java.lang.RuntimeException Caused by: java.io.FileNotFoundException in Jenkins Pipeline

### ISSUE THREAD

**Issue by sys-cf-ghrn** [robolectric/robolectric#3890]
### Description
Hi! I am having an issue using Robolectric 3.6 through 3.8 in our Jenkins pipeline. 

All Robolectric tests fail with the following exception:

```
java.lang.RuntimeException Caused by: java.io.FileNotFoundException
```
The Robolectric configuration can not find the Manifest file which is weird because when we run our Robolectric tests locally with Android Studio, all of our tests pass.

Here is the configuration of a failing test:

```java
@RunWith(RobolectricTestRunner.class)
@Config( sdk = Build.VERSION_CODES.LOLLIPOP, constants = BuildConfig.class)
```

We have also attempted to add the manifest file location in the test, but got the same failing results, and all the Robolectric tests are all set up in a similar way.

### Robolectric & Android Version
Minimum SDK Version: 19
Compile SDK Version: 27
Target SDK Version: 27
Build Tools Version: 27.0.3
Robolectric: 3.8, (3.3 is the latest version that works)
Roboelectric Shadow Support-v4: 3.3
Android Studio 3.1.2

#### Dependencies:
Gradle Plugin 4.4
Gradle build: 3.1.2

**Comment by shadracktakealot** [comment]
@sys-cf-ghrn did you figure this out? having the same issue

**Comment by utzcoz** [comment]
Please try the latest Robolectric 4.9.2 or 4.10-alpha-1.
