### ISSUE TITLE
3.2 to 3.4 migration: New way of intalling custom PackageManager not workiong

### ISSUE THREAD

**Issue by avirdhe** [robolectric/robolectric#3913]
### Description
I am trying to follow the the migration guide http://robolectric.org/migrating/ to migrate existing project from Robolectric 3.2.2 to 3.4.
Having issues with these directions:

If you were using RuntimeEnvironment.setRobolectricPackageManager() to install a custom PackageManager, you should move your custom behavior to a subclass of ShadowApplicationPackageManager and install it as a shadow (using @Config() and possibly @Implements(inheritImplementationMethods=true)) instead.

I created a custom PackageManager and moved the custom behavior to it like so:

    @Implements(value = PackageManager.class, inheritImplementationMethods=true)
    public static class CustomShadowPackageManager extends ShadowApplicationPackageManager {
        @Implementation
        public String getNameForUid(int uid) {
            //Custom behavior here
        }
    }

I have added this custom shadow class in the @Config annotation on the test class like so

@Config(shadows = {CustomShadowPackageManager.class}
Public class MyTest{}

However, this does not work.
I tried setting a breakpoint in the custom behavior but that breakpoint is never hit.
Looks like the custom PackageManager is not getting set in the environment.

Am I missing something here?

### Robolectric & Android Version
Android API level 26. Robolectric 3.4

**Comment by hansonchar** [comment]
Any chance of providing an example of how to make this work?

**Comment by jongerrish** [comment]
I believe you need:-

@Implements(value = ApplicationPackageManager.class)

...and you don't need:-

inheritImplementationMethods=true

What custom logic are you adding? If it's missing functionality let's
upstream it too.

**Comment by hansonchar** [comment]
`android.app.ApplicationPackageManager` is package private so it won't even compile.  What am I missing?

**Comment by xian** [comment]
For non-visible classes, you can use `@Implements(classname = "android.app.ApplicationPackageManager")`.

**Comment by hansonchar** [comment]
`s/classname/className/` and it works.
```java
@Implements(className = "android.app.ApplicationPackageManager")
```
Problem solved.  Thanks!
