### ISSUE TITLE
Library version upgrade issue with roboelectric/blackduck

### ISSUE THREAD

**Issue by HighQMobile** [robolectric/robolectric#3916]
Hi Team,
We are using Blackduck to fix Security and license issues. 
While using roboelectric with version 4.3, blackduck shows few libraries which requires version update to their latest version. As there are security risks for it.
Following are the libraries list which require version update used with roboelectric:

**com.ibm.icu:icu4j:53.1 ( used in org.robolectric:shadows-framework:4.3)**
![icu4j](https://user-images.githubusercontent.com/39511180/63682648-0af25480-c816-11e9-8036-a6fb89859c56.PNG)

**org.codehaus.plexus:plexus-utils:1.5.15 (used in org.robolectric:pluginapi:4.3)** 

It would be great if you can update these libraries.

Attached screenshot of Blackduck showing one of the libraries which require version upgrade.

![blackduck_updated](https://user-images.githubusercontent.com/39511180/40345180-ca64e76e-5db5-11e8-9835-b9a28fd0bd57.png)

**Comment by IngoHaumann-TomTom** [comment]
Four years later(!) and this vulnerability still exists. Using version 70.1 of ICU4J should fix this issue.

**Comment by utzcoz** [comment]
> Four years later(!) and this vulnerability still exists. Using version 70.1 of ICU4J should fix this issue.

Thanks for mentioning this problem. I will send a PR to try fix it today.

**Comment by utzcoz** [comment]
@IngoHaumann-TomTom I have saw some vulnerability fixes after ICU4J 50.x, it's good to upgrade ICU4J version if there are other compatibility problems. I will send a PR to check it.

> org.codehaus.plexus:plexus-utils:1.5.15 (used in org.robolectric:pluginapi:4.3)

> It would be great if you can update these libraries.

@HighQMobile Looks like Robolectric pluginapi doesn't depend on it anymore. I will check dependency relationship locally.

**Comment by utzcoz** [comment]
> @HighQMobile Looks like Robolectric pluginapi doesn't depend on it anymore. I will check dependency relationship locally.

I have used `./gradlew :pluginapi:dependencies` to check dependencies of pluginapi, and it doesn't include plexus-utils anymore.
