### ISSUE TITLE
Overriding getActivityIntent in ActivityTestRule has no effect

### ISSUE THREAD

**Issue by kamilzych** [robolectric/robolectric#3918]
### Description
As in title. The activity that I want to test requires some extras to be present always so it throws an exception during `onCreate` when they are not found.
Expected behaviour: Intent contains extras passed to it in `getActivityIntent` method

### Steps to Reproduce
Create a test 

```
@RunWith(AndroidJUnit4::class)
class SomeActivityTest {

    @Rule
    @JvmField
    val activityRule = object : ActivityTestRule<SomeActivity>(SomeActivity::class.java) {

        override fun getActivityIntent(): Intent {
            return SomeActivity.getIntent(InstrumentationRegistry.getTargetContext(), "extrasValue")
        }
    }

    @Test
    fun start() {
        // do nothing
    }
}
```

Where SomeActivity looks like this
```
class SomeActivity : AppCompatActivity() {

    private lateinit var someExtras: String

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_article)
        if (!intent.hasExtra(KEY_SOME_EXTRAS)) {
            throw IllegalStateException("Missing [$KEY_SOME_EXTRAS] extra in Intent")
        }
    }
    companion object {

        internal const val KEY_SOME_EXTRAS = "keySomeExtras"

        fun getIntent(context: Context, someExtras: String) =
            Intent(context, SomeActivity::class.java).apply {
                putExtra(KEY_SOME_EXTRAS, someExtras)
            }
    }
}
```

### Robolectric & Android Version
Robolectric 4.0

**Comment by VictorAlbertos** [comment]
@kamilzych did you find any workaround to this limitation? 

@brettchabot, is there any plans in the short term (next release?) to support this?

**Comment by kamilzych** [comment]
@VictorAlbertos Nope. I've tried a lot of different things but no luck. I have one more idea that I will check tomorrow, I'll post it if it'll work.

**Comment by VictorAlbertos** [comment]
Thanks @kamilzych By the way, I just ended up using an indirection layer to mock the intent bundle. But this is of course an architecture dependent solution.

**Comment by kamilzych** [comment]
@VictorAlbertos in my case a workaround is to simply use old Robolectric API in my test, no changes required in actual production code. If you take a look at my example I posted in the original post, this is how I changed the test

```
@RunWith(AndroidJUnit4::class)
class SomeActivityTest {

    @Test
    fun start() {
        val context = InstrumentationRegistry.getTargetContext()
        val intent = SomeActivity.getIntent(context, "extrasValue")
        Robolectric.buildActivity(SomeActivity::class.java, intent).create().get()
    }
}

So I no longer use `ActivityTestRule`.

**Comment by kamilzych** [comment]
@VictorAlbertos in other tests, yes. I'm still on Robolectric 4.0 alpha 2, the old API is still there.

**Comment by setheclark** [comment]
I just submitted a PR that would fix this issue.  #3923

**Comment by jongerrish** [comment]
Looks like this has been merged. If its still an issue please reopen.

Also consider using the new ActivityScenario API:

https://developer.android.com/guide/components/activities/testing
