### ISSUE TITLE
Display used as a map key without an implementation of hashCode()

### ISSUE THREAD

**Issue by cesar1000** [robolectric/robolectric#3932]
The `ShadowWindowManagerImpl` uses `Display` as a key in a multimap of views. The `Display` class, however, doesn't implement `hashCode()` and `getDefaultDisplay()` returns a new instance of `Display` in each call. As a result, adding views to `views` always creates a new key, and looking up views doesn't work at all.

I'm not sure about the best way to implement the concept of identity for an instance of `Display`. I patched it by using `toString()`, but it's quite hacky :). This is the shadow I added:

```
@Implements(Display.class)
public class ShadowDisplay extends org.robolectric.shadows.ShadowDisplay {
    @RealObject private Display mRealObject;

    @Implementation
    @Override
    public boolean equals(@Nullable Object obj) {
        return obj instanceof Display && mRealObject.toString().equals(obj.toString());
    }

    @Implementation
    @Override
    public int hashCode() {
        return mRealObject.toString().hashCode();
    }
}
```

**Comment by cesar1000** [comment]
@jongerrish suggested using the display id. I updated my shadow to use that, and my test is passing using that. I'll put up a patch for `ShadowDisplay`.

**Comment by utzcoz** [comment]
Hi @cesar1000 , looks like related issue was fixed after reading https://github.com/robolectric/robolectric/pull/3934#issuecomment-437781424. Feel free to reopen this issue if you have any questions about this issue. Thanks.
