### ISSUE TITLE
Robolectric to support Android Automotive

### ISSUE THREAD

**Issue by yu-yokote** [robolectric/robolectric#3937]
### Description
We hope Robolectric to support Android Automotive

### Robolectric & Android Version
Robolectric 3.5.1
Android compileSdkVersion 26
AOSP Android-O
[Please modify Robolectric.pptx](https://github.com/robolectric/robolectric/files/2102511/Please.modify.Robolectric.pptx)

**Comment by utzcoz** [comment]
@yu-yokote could you try latest Robolectric 4.7.3? I noticed AOSP also uses Robolectric for car-lib's local-testing: https://cs.android.com/search?q=robolectric&sq=&ss=android%2Fplatform%2Fsuperproject:packages%2Fapps%2FCar%2F.

**Comment by utzcoz** [comment]
Robolectric's android-all has integrated `android.car` at commit https://cs.android.com/android/_/android/platform/external/robolectric-shadows/+/a42f68ebfd85605dd9b00ffa411154e95a3892af. Maybe we can think Robolectric has basic Android Automotive supporting from latest release. Hi @hoisie , is there any API restriction to use `android.car` libraries? And we can close this issue if my previous understanding is correct.

**Comment by utzcoz** [comment]
Looks like latest Robolectric can support Android Automotive testing as above comments said. Feel free to reopen this issue if you have other questions when using Robolectric for Android Automotive.
