### ISSUE TITLE
Android 28 solved however still problem maybe with "androidx"

### ISSUE THREAD

**Issue by XinyueZ** [robolectric/robolectric#3946]
With snapshot version I can play with Android SDK 28, however, when the app with `androidx.multidex.MultiDexApplication` the tests bring still crash:
```
java.lang.RuntimeException: MultiDex installation failed (/var/folders/22/31lx60sj1zjf2mc47k543kgh88c6gm/T/robolectric-Method_testAppExist2572574841807186300/...............app-sourceDir (Is a directory)).

	at androidx.multidex.MultiDex.install(MultiDex.java:121)
```

**Comment by jongerrish** [comment]
Looks like the shadows are still for the old package names.

**Comment by PhilippeBoisney** [comment]
Same issue...

**Comment by tbsandee** [comment]
This is still valid for 4.0-alpha-4.

**Comment by TristramN** [comment]
Same issue on 4.0 alpha-3

**Comment by DimaSkopiuk** [comment]
Saame issue on `4.0-beta-1`

**Comment by dbarwacz** [comment]
Bumping robolectric to `4.0-beta-1` while keeping multidex at `3.4.2` (apparently they can't be in sync as there are no beta artifacts for multidex?) fixed the issue for me.

**Comment by royspartyman** [comment]
Does anyone have this working that can list their gradle dependencies?

**Comment by dbarwacz** [comment]
`testImplementation org.robolectric:robolectric:4.0-beta-1 options: {
exclude module: 'classworlds'
                exclude module: 'commons-logging'
                exclude module: 'httpclient'
                exclude module: 'maven-artifact'
                exclude module: 'maven-artifact-manager'
                exclude module: 'maven-error-diagnostics'
                exclude module: 'maven-model'
                exclude module: 'maven-project'
                exclude module: 'maven-settings'
                exclude module: 'plexus-container-default'
                exclude module: 'plexus-interpolation'
                exclude module: 'plexus-utils'
                exclude module: 'wagon-file'
                exclude module: 'wagon-http-lightweight'
                exclude module: 'wagon-provider-api'} `,
 `testImplementation org.robolectric:multidex:3.4.2` 
Is there anything else you'd like to see @royspartyman?

**Comment by royspartyman** [comment]
@dbarwacz Not at the moment. I am still seeing the issue with my tests failing because of the multidex issues. ):

**Comment by nadirw91** [comment]
Same

**Comment by DimaSkopiuk** [comment]
That's not a fix rather workaround. But this could keep project working during waiting for fixed versions:
```
    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        workaroundToInstallMultidexOnlyIfRobolectricNotRun()
    }

    private fun workaroundToInstallMultidexOnlyIfRobolectricNotRun() {
        try {
            MultiDex.install(this)
        } catch (multiDexException: RuntimeException) {
            try {
                Class.forName("org.robolectric.Robolectric")
            } catch (e: ClassNotFoundException) {
                throw multiDexException
            }
        }
    }
```

**Comment by dbarwacz** [comment]
what is the reason for that crash? I wasn't able to check what exactly was
wrong, can you share troubleshooting guide?

**Comment by jongerrish** [comment]
Some background.

Originally MultiDex used to work out the box with Robolectric, it had a code path that depended on Context.getClassLoader() == null to short circuit in "test mode".

Robolectric's fidelity improved over time and at somepoint Context.getClassLoader() returned a real JVM ClassLoader. This broke the "test mode" in MultiDex.

At some point someone contributed ShadowMultiDex to Robolectric shadowing the old support library packages.

With the Jetpack androidx.* package rename that ShadowMultiDex does not work.

One option I considered was creating a ShadowAndroidXMultiDex (you can do this yourself by copying ShadowMultiDex and updating the package of the shadowed MultiDex class.

I'm working on fixing the actual MultiDex class to work with Robolectric again and hopefully can get that pushed out soon, that way you won't need a ShadowMultiDex at all.

More details here: https://issuetracker.google.com/117224552

**Comment by DimaSkopiuk** [comment]
Creating my own `ShadowAndroidXMultiDex` helped. Thank you, @jongerrish

**Comment by royspartyman** [comment]
@DimaSkopiuk can you show me how you created your own as a workaround, that would be super helpful 
(-:

**Comment by DimaSkopiuk** [comment]
@royspartyman sure
**ShadowAndroidXMultiDex**
```Kotlin
import android.content.Context
import androidx.multidex.MultiDex
import org.robolectric.annotation.Implementation
import org.robolectric.annotation.Implements

@Implements(MultiDex::class)
object ShadowAndroidXMultiDex{

    @JvmStatic
    @Implementation
    fun install(context: Context) {}
}
```

Then you need to register this shadow. Simple way is to do it inside `@Config`
```Kotlin
@RunWith(RobolectricTestRunner::class)
@Config(application = YourCustomApp::class, shadows = [ShadowAndroidXMultiDex::class])
class YourTestClass {}
```
Or create custom `RobolectricTestRunner`.
Or inside `annotationProcessorOptions`
It depends on your realization.

**Comment by senthilsivanath** [comment]
@DimaSkopiuk 
You saved my day. 

If you are pre androidx. Shadow class would be 

`import android.content.Context
import android.support.multidex.MultiDex
import org.robolectric.annotation.Implementation
import org.robolectric.annotation.Implements

@Implements(MultiDex::class)
object ShadowAndroidMultiDex{

    @JvmStatic
    @Implementation
    fun install(context: Context) {}
}`

And don't forget to add 
`testImplementation 'com.android.support:multidex:1.0.3'`

**Comment by xian** [comment]
Still not working; `org.robolectric.shadows.multidex.Shadows.SHADOW_MAP` doesn't have a reference.

**Comment by xian** [comment]
This will be fixed in 4.0-beta-3 or final (747f38d5cc080ed7aa1ba7325528e246d9ea9821).

**Comment by AlejandroHCruz** [comment]
Hi, I'm seeing this very same problem using Robolectric 4.0.2 on Android Studio 3.3 with minSdk 18, target & compile SDKs set to 28. Has anyone else seen this issue after 4.0 too?

**Comment by pharkinkFD** [comment]
I'm also still seeing this problem with 
```
    testImplementation "org.robolectric:robolectric:4.0.2"
    testImplementation "org.robolectric:multidex:3.4.2"
```
and had to apply the workaround from @DimaSkopiuk above.
FYI, the java version of the same class would be:
```
import android.content.Context;

import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;

import androidx.multidex.MultiDex;

@Implements(MultiDex.class)
public class ShadowAndroidXMultiDex {

    @Implementation
    public static void install(Context context) {

    }

}

```
