### ISSUE TITLE
Unable to build support fragment using Robolectric.buildFragment(fragment);

### ISSUE THREAD

**Issue by ketanmadane** [robolectric/robolectric#3950]
### Description
Robolectric.buildFragment requires class of android.app.Fragment. I've tried #3732 but it doesn't works.

### Steps to Reproduce
Robolectric.buildFragment(SampleFragment.class);
- where SampleFragment is of type android.support.v4.app.Fragment

### Robolectric & Android Version
Robolectric -  3.8
Android - 26

### Link to a public git repo demonstrating the problem:
Error - Inferred type 'com.example.SampleFragment' of type parameter 'T' is not within its bound; should extend android.app.Fragment

**Comment by sanat51289** [comment]
@ketanmadane looks like your SampleFragment extends from 
> android.support.v4.app.Fragment

Thats why you can't use Robolectric.buildFragment, that takes a Fragment of type > android.app.Fragment type 

So  instead you can try using following options:

> SupportFragmentTestUtil.startVisibleFragment(<passInYourFragmentsInstance>) OR SupportFragmentTestUtil.startFragment(<passInYourFragmentsInstance>);

OR
> SupportFragmentController.of(<passInYourFragmentsInstance>).create().start().resume();

also make sure you include the following before trying that: 
> testImplementation "org.robolectric:shadows-supportv4:{latest_version}"

Let us know whether it helped.

Happy testing!

**Comment by ketanmadane** [comment]
@sanat51289: I'm having a fragment hosted on Activity that getArgument(bundle) from previous Activity.

I'm trying to test button onClick() inside that fragment. I tried as below-
// onClick method
```
void onClick(){
    ...
    ((MainActivity)getActivity()).performSomeAction();
    ...
}
```

// Started fragment using startFragment
```
SampleFragment fragment = new SampleFragment();
startFragment(fragment);
```

It works but then If I call that onClick() using fragment instance then it gives error as below
**SupportFragmentTestUtil cannot be cast to MainActivity**

for above problem I did as below-
`startFragment(fragment, SampleActivity.Class);`
It creates a SampleActivity instance internally but with empty parameter intent that are required in SampleActivity.

I can create an SampleActivity with required parameters, but then I'm not able to figure out how to link the started SampleFragment with that SampleActivity; as startFragment will use SupportFragmentTestUtil or Activity but not the SampleActivity.

**Comment by sanat51289** [comment]
@ketanmadane try exploring `SupportFragmentController` class as well, it has few methods that might help you. For e.g. `SupportFragmentController<F> of(F fragment, Class<? extends FragmentActivity> activityClass, Intent intent)`

so you could do something like this:

```
Intent intent = new Intent();
intent.putExtra("testK", "testV");

SupportFragmentController<SampleFragment> controller = SupportFragmentController.of(fragment, SampleActivity.class, intent);
```

and then you can use the `controller` to simulate what `startFragment` does for you.

so something like:

```
...
controller.create().start().resume().visible()

...
//and then maybe in tear down the reverse 
controller.pause().stop().destroy()

```

Happy testing!

PS: If your issue gets resolved lets close this github issue.

**Comment by ketanmadane** [comment]
@sanat51289 : when the below line is executed-
`controller.create().start().resume.visible();`

I'm getting below error-
No view found for id 0x1 (unknown) for fragment SampleFragment{f9cab00 #0 id=0x1}

**Comment by niceone548** [comment]
@sanat51289 
Since fragments are deprecated now... https://developer.android.com/reference/android/app/Fragment Isn't it better to move over to the support fragment? (or overload with both)

**Comment by sanat51289** [comment]
@niceone548 correct, and `SupportFragmentController` of Robolectric expects a support fragment.

**Comment by sanat51289** [comment]
@ketanmadane you could also use the following overridden method
`controller.create(R.id.content (an id that your activity has), new Bundle()).start().resume();`

**Comment by ketanmadane** [comment]
@sanat51289 : I've tried that already, doesn't works. I'll close this issue.

**Comment by sanat51289** [comment]
@Narayane @ketanmadane if you guys can post a link to a sample project on Github that recreates the issue that you guys are seeing then I can take a look at it.

Because when i had this issue i was able to resolve it by passing a valid view id (from my activity's layout) and using the following variant of `SupportFragmentController`:

```
controller.create(R.id.content (an id that your activity has), new Bundle()).start().resume();
```

**Comment by SanjayMallur** [comment]
@sanat51289 Thank you very much, the above solution really helped me alot.

**Comment by ketanmadane** [comment]
@sanat51289 : It worked :) 
Just needed to create fragment instance before passing it to SupportFragmentController. 

**Intent passed to the SampleActivity**
```
Intent intent = new Intent();
intent.putExtra("testK", "testV");
```

**Fragment Instance**
`SampleFragment fragment = new SampleFragment();`

**Passing _intent_, _sampleFragment_ and _SampleActivity_ to _SupportFragmentController_**
```
SupportFragmentController<SampleFragment> controller = SupportFragmentController.of(sampleFragment, SampleActivity.class, intent);
controller.create(R.id.container_body, new Bundle()).start().resume();
```
