### ISSUE TITLE
Feature Request: Implement ShadowMediaSessionCompat and ShadowMediaControllerCompat

### ISSUE THREAD

**Issue by noahluddy** [robolectric/robolectric#3962]
### Description
These Shadow files will help accurately test Android apps that use media. Also please include functionality for MediaSessionCompat.Token.

**Comment by jongerrish** [comment]
We don't actually want to support shadows for support libraries, if these don't currently meet your testing needs please create a bug on the Google Issue tracker for Media Compat, details here:-

https://source.android.com/setup/contribute/report-bugs

We do have support for the built in MediaSession however.
