### ISSUE TITLE
DeprecatedMethods ErrorProne check has wrong description

### ISSUE THREAD

**Issue by wesleym** [robolectric/robolectric#3964]
### Description
The DeprecatedMethods check has the summary "Robolectric shadows shouldn't be stored to variables or fields." This is the same summary as ShadowUsageCheck. This summary should not be the same between checks, and this summary is misleading for DeprecatedMethods.

See the following:

* Incorrect usage: https://github.com/robolectric/robolectric/blob/83407e9a4c6e7f48774c86438f8e8bf5151bc25d/errorprone/src/main/java/org/robolectric/errorprone/bugpatterns/DeprecatedMethodsCheck.java#L32
* Correct usage: https://github.com/robolectric/robolectric/blob/83407e9a4c6e7f48774c86438f8e8bf5151bc25d/errorprone/src/main/java/org/robolectric/errorprone/bugpatterns/ShadowUsageCheck.java#L82

### Steps to Reproduce
Run an ErrorProne check on code that includes `ShadowApplication.getInstance()`.

### Robolectric & Android Version
robolectric/robolectric at HEAD

### Link to a public git repo demonstrating the problem:
I don't have one handy, but can make one if necessary.

**Comment by MGaetan89** [comment]
Hey @wesleym,

It seems that this was fixed a long time ago, but no one updated this ticket. Sorry about that!

Here's the fix: https://github.com/robolectric/robolectric/commit/63ef277e919862429d206e346da5496675d4b9ce

It has been released since Robolectric 4.4.
