### ISSUE TITLE
Issue with Robolectric tests on Android API 26 target

### ISSUE THREAD

**Issue by L7ColWinters** [robolectric/robolectric#3965]
Hi, Before moving to API 26 we were targeting API 22 to avoid runtime permissions. Now that we’ve upgraded our app an interesting issue is occuring with our Robolectric tests. When running them on Jenkins the test run will Hang, again this only happens when targeting API 26 or above. Another thing to note is that on our local machines the tests are running fine.

I’m unsure how to debug this issue or how to move forward. Any help would be appreciated or if anyone else is experiencing the same problems.

Currently we’re running Robolectric version 3.8 and Jenkins 2.88

Again, thanks for any help!

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and feel free to reopen it when still exists.
