### ISSUE TITLE
LegacyManifestParser parses all metadata as Strings

### ISSUE THREAD

**Issue by petrcermak** [robolectric/robolectric#3971]
### Description
[`LegacyManifestParser`](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/LegacyManifestParser.java)`#`[`metaDataToBundle()`](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/LegacyManifestParser.java#L503) parses all metadata tags as Strings.

### Steps to Reproduce
1) Add a metadata with a boolean value to your manifest:
```xml
<meta-data android:name="key" android:value="true"/>
```
2) Read the value at runtime:
```java
context.getActivityInfo(componentName, PackageManager.GET_META_DATA).metadata.getBoolean("key", /* defaultValue= */ false)
```

#### Expected behavior
The expression should evaluate to `true`.

#### Observed behavior
The expression evaluates to `false`

### Robolectric & Android Version
Robolectric version: master
Android version: 28 (P)

Robolectric needs to replicate the [platform logic](https://android.googlesource.com/platform/frameworks/base/+/10c593cf7f30ddea32889361c81ef06eabaeb6b3/libs/androidfw/ResourceTypes.cpp#5560).

**Comment by xian** [comment]
`LegacyManifestParser` and `resourcesMode=legacy` are deprecated in Robolectric 4.0; this works correctly when using `resourcesMode=binary`. See http://robolectric.org/migrating/ for help switching to binary mode.
