### ISSUE TITLE
How can write a custom shadow by Kotlin?

### ISSUE THREAD

**Issue by thuypt** [robolectric/robolectric#3976]
### Description
Writing a custom shadow class using Kotlin, these annotation `@RealObject`, `@Implement` are Java annotation, they aren't recognized by Kotlin so the shadow class doesn't work properly. 

### Steps to Reproduce
This is Kotlin snippet
```
@Implements(MyManager::class)
class TestCustomShadowByKotlin {
    
    @RealObject
    private val realMyManager: MyManager
}
```
### Robolectric & Android Version
Robolectric 4.0
Android API 28

**Comment by nic0lette** [comment]
I wonder if you might be running into another problem that's being masked by this. I tried creating a custom shadow in Kotlin to see what was going on. I'm using the import `testImplementation 'org.robolectric:robolectric:4.0.2'`

With that, I wrote this shadow:

```
@Implements(ImageView::class)
class ShadowImageView {
    @RealObject
    public lateinit var realImageView: ImageView

    @DrawableRes
    var setImageResource: Int = 0
        private set

    @Implementation
    protected fun setImageResource(resId: Int) {
        setImageResource = resId
    }
}
```

Everything (including the `realImageView` object being set) is working for me?

I know this is probably a silly question, but you see the imports at the top of your file?

```
import org.robolectric.annotation.Implements
import org.robolectric.annotation.RealObject
```

**Comment by xian** [comment]
Do you have a dependency to `robolectric-annotations` in your `build.gradle`?

```groovy
dependencies {
  testApi 'org.robolectric:robolectric-annotations:4.0.2'
}

**Comment by utzcoz** [comment]
@thuypt I confirm that we can write custom shadow with Kotlin likes https://github.com/robolectric/robolectric/pull/7901, modified from https://github.com/robolectric/robolectric/issues/3976#issuecomment-439210263. As `org.robolectric:robolectric` has necessary dependencies including `robolectric-annotations`, see https://search.maven.org/artifact/org.robolectric/robolectric/4.9.2/jar, so you can just include `testImplementation 'org.robolectric:robolectric:4.9.2'` to integrate Robolectric and write custom shadow in your test directory.
