### ISSUE TITLE
NumberFormatException in LegacyManifestParser with @integer

### ISSUE THREAD

**Issue by calvarez-ov** [robolectric/robolectric#3978]
### Description
If the `AndroidManifest` contains an integer reference `@integer/some_integer` in an `<intent-filter>` `<data>` `port` attribute, Robolectric's `LegacyManifestParser` receives a `NumberFormatException` parsing this value.

### Steps to Reproduce
Define an integer resource in `res/values/strings.xml`:
```xml
    <integer name="port">8000</integer>
```
Add this receiver to the `AndroidManifest.xml` of the app:
```xml
        <receiver
            android:name=".SMSReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.DATA_SMS_RECEIVED" />

                <data
                    android:host="*"
                    android:port="@integer/port"
                    android:scheme="port" />
            </intent-filter>
        </receiver>
```
Create a unit test which does nothing interesting.  The one generated by Android Studio when you create a new project is ok to reproduce this:
```java
@RunWith(RobolectricTestRunner.class)
public class ExampleUnitTest {
    @Test
    public void addition_isCorrect() {
        assertEquals(4, 2 + 2);
    }
}
```
Run `./gradlew clean testDebugUnitTest`.

Expected behavior: the test passes
Actual behavior: an exception occurs:
```
java.lang.NumberFormatException: For input string: "@integer/port"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at android.content.IntentFilter$AuthorityEntry.__constructor__(IntentFilter.java:904)
	at android.content.IntentFilter$AuthorityEntry.<init>(IntentFilter.java)
	at android.content.IntentFilter.addDataAuthority(IntentFilter.java:1108)
	at org.robolectric.shadows.LegacyManifestParser.populateIntentInfo(LegacyManifestParser.java:338)
	at org.robolectric.shadows.LegacyManifestParser.createPackage(LegacyManifestParser.java:245)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:122)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:335)
```

### Robolectric & Android Version
Robolectric 3.8 and 4.0-alpha-3
Android 27

### Link to a public git repo demonstrating the problem:
https://github.com/calvarez-ov/RobolectricManifestBug

### Additional info
The following workaround makes the test pass with robolectric 3.8, but not 4.0:
```groovy
tasks.withType(Test) {
    jvmArgs("-Duse_framework_manifest_parser=true")
}
```

Note that there's no crash on a real device. On a real device, this integer reference is resolved.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
