### ISSUE TITLE
Error on click test using Espresso

### ISSUE THREAD

**Issue by rafaeltoledo** [robolectric/robolectric#3987]
### Description
A simple test clicking on a menu item throw this exception:
`java.lang.IllegalAccessException: Class androidx.test.espresso.base.ThreadPoolExecutorExtractor$2 can not access a member of class androidx.loader.content.ModernAsyncTask with modifiers "public static final"`

### Steps to Reproduce
Clone [this repo](https://github.com/rafaeltoledo/android-testing) and run the `testDebug` task

### Robolectric & Android Version
Using Robolectric 4.0-alpha-3, AGP 3.3.0-alpha08, Espresso 3.1.0-alpha04 and ATSL 1.1.0-alpha04

### Link to a public git repo demonstrating the problem:
https://github.com/rafaeltoledo/android-testing

**Comment by jereksel** [comment]
Caused by: https://issuetracker.google.com/issues/37068381

**Comment by rafaeltoledo** [comment]
Seems to be fixed with Espresso-3.1.0-beta01
