### ISSUE TITLE
java.lang.IllegalAccessException: no such method: org.robolectric.shadows.ShadowApplicationPackageManager.lambda$getPackageSizeInfo$0(Object,PackageStats)void/invokeStatic

### ISSUE THREAD

**Issue by Suguiqiang** [robolectric/robolectric#3997]
### Description
- java call:
//module_name/src/androidTest/module_package_name/MyServiceTest
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23)
public class MyServiceTest {

    private ServiceController<MyService> controller;
    private MyService mService;

    @Before
    public void setUp() throws Exception {
        ShadowLog.stream = System.out;
        controller = Robolectric.buildService(MyService.class);
        mService = controller.get();
    }

    @Test
    public void testServiceLifecycle() throws Exception {
        controller.create();
        controller.startCommand(0, 0);
        controller.bind();
        controller.unbind();
        controller.destroy();
    }
}
- Exception:
Caused by: java.lang.IllegalAccessException: no such method: org.robolectric.shadows.ShadowApplicationPackageManager.lambda$getPackageSizeInfo$0(Object,PackageStats)void/invokeStatic

### Steps to Reproduce
Run the method of testServiceLifecycle below. 
### Robolectric & Android Version
Robolectric 3.8
Android target SDK: 27

**Comment by utzcoz** [comment]
@Suguiqiang Please try the latest Robolectric. If it still exists, please attach a minimal reproducable app for this issue for later investigation. Thanks.
