### ISSUE TITLE
Data Schemes not parsed correctly from BroadcastReceivers in manifest

### ISSUE THREAD

**Issue by steviek** [robolectric/robolectric#4001]
Given the following manifest

```
<receiver android:name=".MyReceiver">                  
  <intent-filter>
    <action android:name="android.intent.action.PACKAGE_FULLY_REMOVED"/>
    <data android:scheme="package"/>
  </intent-filter>
</receiver>
```

The following call does not invoke the receiver:
```
RuntimeEnvironment.application.sendBroadcast(
    new Intent(Intent.Action_PACKAGE_FULLY_REMOVED)
         .setData(Uri.parse("package:com.example.app"));
```

This is because the IntentFilter created for the broadcast receiver does not have the schemes set and so it does not match intent.

**Comment by jongerrish** [comment]
What version of Robolectric are you using?

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
