### ISSUE TITLE
Questions: setPermissionPolicy method missing

### ISSUE THREAD

**Issue by rentzzz** [robolectric/robolectric#4002]
### Description

ShadowDevicePolicyManagerTest.java is not including DevicePolicyManager method 

`public void setPermissionPolicy (ComponentName admin,  int policy)
`
[Android Developer](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setPermissionPolicy(android.content.ComponentName,%20int))

Will is there an implementation planned or is there any easy workaround?

**Comment by jongerrish** [comment]
Its unlikely we would prioritize this ourselves but we'd welcome contributions as we'd love to add this functionality :-)

As a work around you can create your own shadow, see: http://robolectric.org/extending/

You can make something like

class MyCustomShadowDevicePolicyManager extends ShadowDevicePolicyManager {

}
