### ISSUE TITLE
Robolectric hanging in some instances with Android databinding

### ISSUE THREAD

**Issue by jonathan-caryl** [robolectric/robolectric#4027]
### Description

We have a large app that uses Android Data Binding, and is currently on `com.android.tools.build:gradle:2.1.3`, with Robolectric 3.8. The time has come to upgrade to newer `build:gradle`, but when we do that we find that some of our tests hang.

### Steps to Reproduce

I've created a very stripped-down app available [here](https://github.com/jonathan-caryl/RobolectricDatabindingHang). The `master` branch uses 2.1.3, and the Robolectric test completes ok. The `upgrade_build_gradle` branch hangs on the same test — inside the call to `activityController.setup()` it seems to get stuck in a loop.

I can 'fix' the problem by removing one of the included layouts, in the real app this would involve substantial amounts of rework, so I'm hoping there's another option. I wondered if this was really a data binding issue rather than a Robolectric one, but as it seems to work ok outside of Robolectric, that seems less likely.

### Robolectric & Android Version

We're using Robolectric version 3.8, although I tried the 4.0-alpha and it didn't seem to make any difference. Android version is 27.

### Link to a public git repo demonstrating the problem:

https://github.com/jonathan-caryl/RobolectricDatabindingHang

**Comment by jonathan-caryl** [comment]
Thanks @xian I don't care if it's hacky, it does the job and lets us keep our tests without having to change a bunch of our code. I look forward to Robolectric 4.1, but for now this is just magic!

**Comment by DDihanov** [comment]
Still having this issue on robolectric 4.2. Test used to hang on DataBindingUtil.setContentView(this, R.layout.activity_main) in MainActivity. I used the hack and the activity was created but as soon as I got to the test which called onVIew().click the test hung again.
