### ISSUE TITLE
ShadowBitmapFactory.decodeByteArray() always returns a 100x100 Bitmap

### ISSUE THREAD

**Issue by tryal-leaf** [robolectric/robolectric#4028]
### Description
I'm attempting to test code that converts and downsizes an image in byte[] format into a bitmap. However, it seems impossible to add the correct sizes to the widthAndHeightMap. decodeByteArray() creates a convoluted "name" from the byte[] array, which none of the current provideWidthAndHeightHints() methods handle. As a result, selectWidthAndHeight() will always return the default new Point(100, 100), and the Bitmap returned by decodeByteArray() will always be size 100x100.

### Link to a public git repo demonstrating the problem:
https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java

**Comment by jongerrish** [comment]
I have a fix for this or at least some of this which I hope will solve your issue. Should be available in 4.0.2 hopefully by the end of this week

**Comment by jongerrish** [comment]
Fixed in https://github.com/robolectric/robolectric/commit/1c1fe55966698564643a1ba62f3760083b287ec1

**Comment by zzmingo** [comment]
Hi, I found that decodeFile did the same thing, returning a 100x100 bitmap. The version of robolectric is 4.3.1.

**Comment by jbruchanov** [comment]
+1 `decodeFile` has this bug as well...
please reopen

**Comment by hoisie** [comment]
Is there a simple repro case?

**Comment by jbruchanov** [comment]
@hoisie 
```
    @Test
    fun `test decodeFile`() {
        val bitmap = Bitmap.createBitmap(500, 600, Bitmap.Config.ARGB_8888)
        assertEquals(500, bitmap.width)
        assertEquals(600, bitmap.height)
        val file = File("test.jpg")
        println("Size:${file.length()}")
        FileOutputStream(file).use { bitmap.compress(Bitmap.CompressFormat.JPEG, 80, it) }
        bitmap.recycle()

        val loadedBitmap = BitmapFactory.decodeFile(file.absolutePath)
        assertEquals(500, loadedBitmap.width)
        assertEquals(600, loadedBitmap.height)
        loadedBitmap.recycle()
    }
```

output
```
"C:\Program Files\Java\jdk1.8.0_162\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:C:\Utils\Android\android-studio-4.0\lib\idea_rt.jar=10844:C:\Utils\Android\android-studio-4.0\bin -Dfile.encoding=UTF-8 -classpath C:\Users\Username\AppData\Local\Temp\classpath1819011837.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 "com.flamingointernational.core.android.media.BitmapUtilsTest,test decodeFile"
[Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.
[Robolectric] com.flamingointernational.core.android.media.BitmapUtilsTest.test decodeFile: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
Size:5491

java.lang.AssertionError: 
Expected :500
Actual   :100
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.scurab.Test.test decodeFile(BitmapUtilsTest.kt:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Process finished with exit code -1

```

**Comment by hoisie** [comment]
Does this issue still exist with 4.4-alpha-1?

**Comment by jbruchanov** [comment]
Yes, same issue 4.3.1, 4.4-alpha-1

**Comment by hoisie** [comment]
Thanks for the repro @jbruchanov. Filed a new issue  at #5774

**Comment by hoisie** [comment]
https://github.com/robolectric/robolectric/pull/5777 should fix the issue with decodeFile. In theory it could cause issues with the previous legacy SDK which doesn't even check for the existence of the file. I'll run some more tests and see how much of an issue this could be.

**Comment by tdhamal1590** [comment]
> @hoisie
> 
> ```
>     @Test
>     fun `test decodeFile`() {
>         val bitmap = Bitmap.createBitmap(500, 600, Bitmap.Config.ARGB_8888)
>         assertEquals(500, bitmap.width)
>         assertEquals(600, bitmap.height)
>         val file = File("test.jpg")
>         FileOutputStream(file).use { bitmap.compress(Bitmap.CompressFormat.JPEG, 80, it) }
>         println("Size:${file.length()}")
>         bitmap.recycle()
> 
>         val loadedBitmap = BitmapFactory.decodeFile(file.absolutePath)
>         assertEquals(500, loadedBitmap.width)
>         assertEquals(600, loadedBitmap.height)
>         loadedBitmap.recycle()
>     }
> ```
> 
> output
> 
> ```
> "C:\Program Files\Java\jdk1.8.0_162\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:C:\Utils\Android\android-studio-4.0\lib\idea_rt.jar=10844:C:\Utils\Android\android-studio-4.0\bin -Dfile.encoding=UTF-8 -classpath C:\Users\Username\AppData\Local\Temp\classpath1819011837.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 "com.flamingointernational.core.android.media.BitmapUtilsTest,test decodeFile"
> [Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.
> [Robolectric] com.flamingointernational.core.android.media.BitmapUtilsTest.test decodeFile: sdk=28; resources=BINARY
> Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
> Size:5491
> 
> java.lang.AssertionError: 
> Expected :500
> Actual   :100
> <Click to see difference>
> 
> 
> 	at org.junit.Assert.fail(Assert.java:88)
> 	at org.junit.Assert.failNotEquals(Assert.java:834)
> 	at org.junit.Assert.assertEquals(Assert.java:118)
> 	at org.junit.Assert.assertEquals(Assert.java:144)
> 	at com.scurab.Test.test decodeFile(BitmapUtilsTest.kt:50)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
> 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
> 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 
> Process finished with exit code -1
> ```

does this issue solves ? i face same issue on 4.10 too
