### ISSUE TITLE
Comparing drawables results in assertion failure

### ISSUE THREAD

**Issue by santoshastagi** [robolectric/robolectric#4037]
### Description
If one does an `assertEquals()` for drawables, an assertion failure, drawables don't match is returned.
This is working in 3.8, but 4.0 onwards has stopped working.

### Steps to Reproduce
Write a robolectric test, and test drawables like this:
```
assertEquals(activity.findViewById<ImageView>(R.id.imageOne).background, ContextCompat.getDrawable(mainActivity.baseContext,
            R.drawable.ic_launcher_foreground))
```

### Robolectric & Android Version
Robolectric version: 4.0-beta-1, 4.0-beta-2-SNAPSHOT
Android version: 28

**Comment by borwoj** [comment]
Unfortunately the above solution does not work for me and all the `Drawable` comparison assertions still fail. As mentioned, the issue appeared after migrating from 3.8 to 4.0.1

For example:
``` kotlin
view.background = ContextCompat.getDrawable(ApplicationProvider.getApplicationContext(), R.drawable.some_bg)

assertEquals(
      shadowOf(view.background).createdFromResId,
      shadowOf(view.background).createdFromResId)
```
Result: false

**Comment by iRYO400** [comment]
> Older versions of Robolectric modified the behavior of `Drawable.equals()` (which Android leaves undefined, so it returns true only for identity-equal objects). In Robolectric 4.0, we try to match real Android behavior as closely as possible, so this special case has been removed.
> 
> Equivalent code that should work:
> 
> ```java
> assertThat(shadowOf(drawable).getCreatedFromResId())
>     .isEqualTo(shadowOf(expectedDrawable).getCreatedFromResId());
> ```

Thanks! Exactly what I needed!
