### ISSUE TITLE
Activity.getLifecycle().getCurrentState()==CREATED although activity is resumed

### ISSUE THREAD

**Issue by lsuski** [robolectric/robolectric#4038]
### Description

According to doc `ActivityScenario.launch` should bring activity to resumed state. However `activity.getLifecycle().getCurrentState()` returns CREATED but activity is in state resumed. It is strange but I think that methods Activity.performResume and performStart are not called

### Steps to Reproduce

```
val launch = ActivityScenario.launch(FragmentActivity::class.java)
launch.onActivity {
       assertEquals(Lifecycle.State.RESUMED, it.lifecycle.currentState)
}
```

### Robolectric & Android Version

Robolectric 4.0-beta-2, sdk 28

**Comment by xian** [comment]
We have a fix for this underway at #4053, it'll be in 4.0.1. Thanks!
