### ISSUE TITLE
Add ability to exclude individual shadows

### ISSUE THREAD

**Issue by thenuge** [robolectric/robolectric#4050]
It would be great if there was a @Config option to allow excluding a list of shadows from a test. Some canonical shadows exhibit unrealistic behavior -- the motivating example here is ShadowMatrix, which does always does something reasonable whatever you throw at it. This is in contrast to Android API 19 and below, which will sometimes hand back the IDENTITY_MATRIX when you ask an ImageView for its Matrix. IDENTITY_MATRIX throws an IllegalStateException on all method calls, which I now cannot reproduce due to ShadowMatrix changing the behavior.

**Comment by xian** [comment]
You can disable individual shadows like this:

```java
@Config(shadows = NoOpShadowMatrix.class)
public class MyTest {
  @Implements(Matrix.class)
  public static class NoOpShadowMatrix { }
}
```

Not the prettiest solution, sorry.

**Comment by xian** [comment]
If you'd like though, you could open an issue regarding ShadowMatrix with a failing sample test? I'll try to prioritize a fix.
