### ISSUE TITLE
Failed to resolve: multidex

### ISSUE THREAD

**Issue by rajalingam771** [robolectric/robolectric#4054]
### Description
Failed to resolve: multidex
Failed to resolve: multidex-instrumentation

**Comment by rajalingam771** [comment]
https://raw.github.com/iFixit/ark/master/releases/

**Comment by rajalingam771** [comment]
above link is not available

**Comment by xian** [comment]
@rajalingam771 -- is this an issue with Robolectric? If so, please reopen this issue and include the `dependencies` section of your `build.gradle`.
