### ISSUE TITLE
Feature request: add mapRadius of ShadowMatrix

### ISSUE THREAD

**Issue by crupest** [robolectric/robolectric#4055]
### Description
I hava a application that uses `Matrix.mapRadius` method. But I find that it always return `0`.
Then I check the source code, I find there is no implementation of `mapRadius`.
Could you please add the method?
Though there is a simple workaround that we can write the simple method manually.

### Steps to Reproduce
Here is the code to demonstrate it.
```
@RunWith(RobolectricTestRunner::class)
class UnitTest {
    @Test
    fun matrixMapRadiusTest() {
        assertThat(Matrix().apply { postScale(2.0f, 2.0f) }.mapRadius(1.0f).toDouble(),
                closeTo(2.0, 0.01))
    }
}
```
### Robolectric & Android Version
Robolectric version: `4.0`
Android api level: `27`

**Comment by crupest** [comment]
Here is the code I find in `skia`.

```
SkScalar SkMatrix::mapRadius(SkScalar radius) const {
    SkVector    vec[2];

    vec[0].set(radius, 0);
    vec[1].set(0, radius);
    this->mapVectors(vec, 2);

    SkScalar d0 = vec[0].length();
    SkScalar d1 = vec[1].length();

    // return geometric mean
    return SkScalarSqrt(d0 * d1);
}
```

It seems that we can add the method based on current mathods.

I think I can make a pull request. But I don't have a linux machine to develop.

**Comment by jongerrish** [comment]
Fixed
