### ISSUE TITLE
Low contrast for code examples

### ISSUE THREAD

**Issue by kurthuwig** [robolectric/robolectric#4062]
### Description

The robolectric homepage uses a low contrast for code examples that makes them hard to read. The background has 1,8% black and the writing 24,7% black, so less that 1/4th of the possible contrast. I suggest to increase the contrast to improve readability.

Here is a screenshot how it looks on my screen:

![low-constrast](https://user-images.githubusercontent.com/2757758/47698727-ba6b9400-dc10-11e8-8e43-5d224fd50cac.png)

### Steps to Reproduce

Open the page

http://robolectric.org/migrating/

and read the first code example

### Robolectric & Android Version

4.0

### Link to a public git repo demonstrating the problem:

See screenshot above.

**Comment by xian** [comment]
You're totally right. I've increased the contrast:

![image](https://user-images.githubusercontent.com/40298/47743118-8063b780-dc3b-11e8-9643-08a59f1aeb36.png)

**Comment by kurthuwig** [comment]
Thanks a lot it is much better readable now!

But where the method references like this before?

![docs](https://user-images.githubusercontent.com/2757758/47907425-864fd780-de8b-11e8-8f47-c476dae31fa3.png)

now the capital "I" of "getInstance" has the same height as the lowercase letters. And all letters are squeezed together.
