### ISSUE TITLE
upgraded to robolectric:4.0 and get error Module 'org.robolectric:robolectric:4.0' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by chuksleo** [robolectric/robolectric#4066]
### Description
upgraded to robolectric:4.0 and get error Module 'org.robolectric:robolectric:4.0' depends on one or more Android Libraries but is a jar"
am using android studio 3.0.1
compileSdkVersion 27
buildToolsVersion "25.0.3"
### Steps to Reproduce
Upgraded to Robolectric 4.0

### Robolectric & Android Version
4.0

**Comment by xian** [comment]
@chuksleo -- can you make sure you're using the latest [Android Gradle Plugin](https://developer.android.com/studio/releases/gradle-plugin#updating-plugin), and reopen if that doesn't resolve the issue? Thanks!
