### ISSUE TITLE
java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.inflate

### ISSUE THREAD

**Issue by Doctoror** [robolectric/robolectric#4086]
### Description
Robolectric does not contain `inflate` method for `Drawable`.

### Robolectric & Android Version
Robolectric 4.0

### Use case demonstrating the problem:
```
@Test
fun reproduce() {
    val resources: Resources = mock()
    val xmlPullParser: XmlPullParser = mock()
    val attrs: AttributeSet = mock()

    AnyClassThatExtendsDrawable().inflate(resources, xmlPullParser, attrs, null)
```

Output:
```
java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.inflate(Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;Landroid/util/AttributeSet;Landroid/content/res/Resources$Theme;)V

	at your.package.name.YourDrawable.inflate(YourDrawable.java:lineOfInflate)
```

**Comment by xian** [comment]
@Doctoror — does that happen if you pass all `null`s or real objects rather than mocks?

**Comment by Doctoror** [comment]
@xian I don't know if that's even possible to create all those real for tests, and I cannot pass null since the Drawable can't accept them in Kotlin, but anyway, this will make no difference. Clearly, the method is missing.

I have discovered that the Drawable has two overloads for `inflate`
```
public void inflate(
    @NonNull Resources r,
    @NonNull XmlPullParser parser,
    @NonNull AttributeSet attrs) {

    inflate(r, parser, attrs, null);
}

public void inflate(
    @NonNull Resources r,
    @NonNull XmlPullParser parser,
    @NonNull AttributeSet attrs,
    @Nullable Theme theme)
```

Robolectric has the triad overload, but it does not provide quad overload.
In my Drawable, I've overridden the quad overload and I want to test it, however, if I change the test to use triad overload, which Robolectric has, it (obviously) will never call quad overload, as it doesn't know about this method.

The quad overload should be added to Robolectric.

**Comment by xian** [comment]
I wouldn't expect an error message like the one you saw though:
`java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.inflate(Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;Landroid/util/AttributeSet;Landroid/content/res/Resources$Theme;)V`

That sounds like the Android SDK itself lacks the method. The quad arg overload was added in SDK 21; is it possible you're trying to run the test against an earlier SDK?

**Comment by jongerrish** [comment]
Also,

Do not mock AttributeSet prefer using a real object instead. You can create
an empty  AttributeSet using Robolectric.buildAttributeSet().build()

**Comment by Doctoror** [comment]
@xian this is exactly the case. I was using the SDK whatever was configured by default, and I totally forgot Robolectric needs this configured. Thank you and sorry for this false report.
