### ISSUE TITLE
Unresolved reference using Kotlin

### ISSUE THREAD

**Issue by bj0** [robolectric/robolectric#4087]
### Description

I have a java app with some unit tests written in Kotlin.  The code uses `android.util.Pair`, and to test it before I had created my own stub of it.  I wanted to try and switch to Robolectric so I can use it for more tests.

After removing my stub, I can write a test in java:

```
import android.util.Pair;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;

import static org.junit.Assert.assertEquals;

@RunWith(RobolectricTestRunner.class)
public class Test
{
    @org.junit.Test
    public void test()
    {
        Pair<String, String> p = Pair.create("Foo", "Bar");
        assertEquals("Foo", p.first);
        assertEquals("Bar", p.second);
    }
}
```
and it works fine, but if I write the same test in Kotlin:
```
import android.util.Pair
import org.junit.Assert.assertEquals
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class TestK {
    @org.junit.Test
    fun testk() {
        val p = Pair.create("Foo", "Bar")
        assertEquals("Foo", p.first)
        assertEquals("Bar", p.second)
    }
}
```
Then it fails with:
```
:app:mockableAndroidJar UP-TO-DATE
e: E:\code\...\TestK.kt: (3, 21): Unresolved reference: Pair
e: E:\code\...\TestK.kt: (12, 22): Unresolved reference: create
:app:compileDebugUnitTestKotlin FAILED
```

I have the following in my build.gradle:
```
    testImplementation 'junit:junit:4.12'
    testImplementation "org.robolectric:robolectric:4.0.1"
    testImplementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

```

I can't find any kotlin examples or documentation, but I've seen a couple (old) blog posts saying that it's possible to use robolectric with kotlin.  Am I missing some kotlin-specific setup?

**Comment by braczkow** [comment]
I have very similar error:
```
e: C:\Users\...\StorageTest.kt: (5, 24): Unresolved reference: test
e: C:\Users\...\StorageTest.kt: (22, 10): Unresolved reference: AndroidJUnit4
```


```
testImplementation "androidx.test.ext:junit:1.0.0"
testImplementation "androidx.test:rules:1.1.0"
testImplementation 'androidx.test:core:1.0.0'
```

and:
```
@RunWith(AndroidJUnit4::class)
class StorageTest { ... }
```

**Comment by bj0** [comment]
I figured it out.  

I had originally stub'd it by creating my own `android.util.Pair` file/class.  When I switched to Robolectric, I commented out everything in that file but left the file.  I don't know why this would cause the problem, or why it would only cause the problem in Kotlin, but after I deleted this file completely, everything worked correctly.
