### ISSUE TITLE
Execution failed for task ':prepareDebugUnitTestDependencies'. error

### ISSUE THREAD

**Issue by yiran163** [robolectric/robolectric#4093]
gradle plugin：2.3.3
gradle version: 3.3
testCompile 'com.android.support.test:runner:1.0.2-alpha1'
testCompile 'com.android.support.test:rules:1.0.2-alpha1'
testCompile 'org.robolectric:robolectric:3.6.1'

when it is built, have the error tip as follow , 

Error:Execution failed for task ':prepareDebugUnitTestDependencies'.
> Dependency Error. See console for details.

can anyone help ?
Thanks
![image](https://user-images.githubusercontent.com/25677633/48258239-977e8280-e44f-11e8-849b-c220177b850a.png)
![image](https://user-images.githubusercontent.com/25677633/48258294-b54be780-e44f-11e8-9fea-3d802a7cae0a.png)

**Comment by xian** [comment]
Can you try with the latest release of Robolectric (currently 4.0.1)? If there's still an issue, can you reopen this issue, try running it from the command line, and include the console output?

```bash
./gradlew prepareDebugUnitTestDependencies
```

**Comment by yiran163** [comment]
> Can you try with the latest release of Robolectric (currently 4.0.1)? If there's still an issue, can you reopen this issue, try running it from the command line, and include the console output?
> 
> ```shell
> ./gradlew prepareDebugUnitTestDependencies
> ```

it works. 
then I change SDK=23 to SDK =21, no error tips
