### ISSUE TITLE
Multiple instances of custom Application class created in the same process

### ISSUE THREAD

**Issue by Egorand** [robolectric/robolectric#4114]
(I'm aware of this being a duplicate of previously reported issues, that date back to 2013. I want to reopen the discussion around this though, especially in the light of the [Write Once, Run Everywhere](https://medium.com/androiddevelopers/write-once-run-everywhere-tests-on-android-88adb2ba20c5) strategy that should make it easy to run the same test suite on a local JVM or on a real device interchangeably.)

### Description

Robolectric creates new instances of the `Application` class for each test method, reusing the same process. This upsets Leak Canary, which is being setup in my `Application` class's `onCreate()` method and doesn't expect initialization to happen twice in the same application process. This is a reasonable expectation, since in the real world the OS will not be creating multiple instances of the `Application` class in the same process.

### Steps to Reproduce

Download the test project (see link below) and run the tests from the command line, e.g. `./gradlew testDebugUnitTest`.

### Robolectric & Android Version

Robolectric: 4.0.2
Android: minSdk = 21, targetSdk = 28, compileSdk = 28

### Link to a public git repo demonstrating the problem:

https://github.com/Egorand/robolectric-leak-canary-integration

**Comment by xian** [comment]
IMO, test isolation is the clear winner here, but I am of course open to being convinced otherwise. Is there value in running LeakCanary in unit tests?

**Comment by Egorand** [comment]
Nope, there's not. The issue is actually having to work around the fact that the way Robolectric sets up the universe is different from what happens in the real world. I completely support the idea of hermetic tests, however in this case, as we're integrating with the Android SDK, where the `Application` class is by design a per-process singleton, it doesn't make sense to modify `Application` setup code to satisfy Robolectric.

**Comment by xian** [comment]
Can't you just use the `leakcanary-android-no-op` dependency for unit tests as LeakCanary suggests? No change to your production code necessary.

**Comment by xian** [comment]
That seems like an issue in LeakCanary, no?

I agree that putting conditionals in production code to work around testing issues sucks. I strongly disagree that all tests should share an `Application` instance because of some implicit guarantee that it's a per-process singleton; that will definitely lead to test pollution. This seems like a natural spot to use a test double if necessary to provide different behavior for unit tests.

**Comment by Egorand** [comment]
Makes sense, I don't disagree. Reusing instances between test invocations is definitely an anti-pattern, too bad that many Android libraries (such as LeakCanary) rely on this behavior of SDK classes, which makes them a huge pain under test.
