### ISSUE TITLE
Test execution with Robolectric 4.0.2 much slower compared to Robolectric 3.8

### ISSUE THREAD

**Issue by christopheblin** [robolectric/robolectric#4142]
### Description
We have quite a few robolectric tests that we migrated from robolectric 3.8 to robolectric 4.0.2. 

We witnessed that the test execution is much slower: around 3min 10s versus 1min 20s before.

Not to say that the dev experience is quite degraded !

### Steps to Reproduce
You have a bunch of test running with robolectric 3.8

You change the version in the gradle file and then in the tests you replace 
```
@RunWith(RobolectricTestRunner::class)
@Config(constants = BuildConfig::class)
```
By
```
@RunWith(AndroidJUnit4::class)
```

And you witness the execution time has increased

Do we miss something when we do our migration ?

Please, do not hesitate to ask me more details if needed

**Comment by jaredsburrows** [comment]
Are you using `includeAndroidResources` in `testOptions`?
```
testOptions {
    unitTests {
        includeAndroidResources = true
    }
}
```

**Comment by christopheblin** [comment]
Yes we are using include Android Resources in the graddle file.
Is this a problem?

**Comment by xian** [comment]
Do you see a line like this in the test `STDOUT`?

`[Robolectric] com.whatever.TestName.methodName: sdk=__; resources=_______`

What's the string after `resources`?

**Comment by jaredsburrows** [comment]
@christopheblin 

An easy way to see this output is to check your HTML test results here: `<project>/build/reports/tests`

If you are using `android.enableUnitTestBinaryResources=true` in your `gradle.properties` file, your then it will be: `resources=binary`. See http://robolectric.org/getting-started/#building-with-android-studiogradle.

**Comment by xian** [comment]
Also, are you seeing an increase in the actual test's runtime, or does that extra couple minutes include the time to compile resources? You can get profiling info from gradle using the `--profile` command line option; look for a URL in `STDOUT`, then under the "Task Execution" tab.

Robolectric 4's binary mode uses the Android build toolchain to prepare resources (using `aapt`). This can cause some extra up-front processing time, but it's only incurred when resources change. (If your build is using `aapt2` it's a smaller cost even when resources do change.)

**Comment by jongerrish** [comment]
Also, we now support Android P so if you're running against all API levels you're running against one more now.

**Comment by christopheblin** [comment]
Thanks guys for all your comments !

Here is an extract from my reports that should answer the questions (I only obfuscated the class names) :

```
[Robolectric] com.xxx1: sdk=28; resources=binary
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
[Robolectric] com.xxx2: sdk=28; resources=binary
[Robolectric] com.xxx3: sdk=28; resources=binary
[Robolectric] com.xxx4: sdk=28; resources=binary
```

Regarding @xian question : yes it is an increase only for actual test's runtime as shown in Android studio Run window
If I fallback to master (which used roblectric 3.8), I see 1min 20s (more or less, it varies a little between test runs)
If I used my robolectric4 branch, I see 3min 10s (here again, more or less)

**Comment by keith30xi** [comment]
We ran into similar test performance issues.  It has been the same for 4.0, 4.0.1, and 4.0.2.  Our test suite increased execution time by about 25% no matter what Android API level we configure.  We followed all upgrade instructions in regards to gradle.properties & build.gradle changes.

**Comment by jongerrish** [comment]
Christian, do you think we should provide an implementation of our
performance collection for open source? Feels like it could be useful

**Comment by christopheblin** [comment]
I've run other "benchmarks" (not really instrumented like a pro) and it seems that 
* the "internal" of test methods did not change between 3.8 and 4.0 
* each test method takes 100ms more to start in 4.0 compared to 3.8 (I have around 200 methods)
* the first method of each test class takes 3 additional seconds to start in 4.0 compared to 3.8 (I have around 30 classes, thus around 90s more)

To arrive at that conclusion, I've modified each method of some test classes to be like
@Test
fun my_test() {  
    val start = System.nanoTime()
    ...    
    val end = System.nanoTime()
    System.out.println("elapsed = ${(end-start)/1000000}ms")
}

Looking at stdout, there is (more or less) no difference between 3.8 and 4.0 in the "elapsed = xxxms". 
However, the whole execution tooks longer (3s for each class and 100ms for each method) which (more or less) stands true for the whole test suite.

Be warned, these are numbers that I have on MY machine with a very manual setup and not a scientific conclusion. If you have a better method to propose, please do not hesitate I will do my best to try it.

However, I would definitely say that something has changed in the robolectric internals to start a test and that change has a non negligible impact on a "big" scale

Does someone else observe such behavior ?

**Comment by jankowskib** [comment]
We got same issue, on 3.8 our test suite has lasted 22 minutes, now after switch to 4.0.2 and removing constants = BuildConfig::class, tests completes in 36 minutes. Thats a big performance drop.

**Comment by konyavic** [comment]
Experiencing the same issue. We also observed that the memory footprint jumps to 2x of the amount used by robolectric 3.1.

**Comment by Jordan-Turgeon** [comment]
I am also experiencing this.

311 Activity tests that used to take 40s to run would now take ~2min 20secs to run. It seemed each individual test was taking a minimum of 300ms more to run.

Our entire test suite of 1860 tests went from 1min 30 secs to something like 7min 30 secs to run after the update.

I get this output after doing the required changes

`[Robolectric] com.xxx3: sdk=28; resources=binary`

and

`testOptions {
    unitTests {
        includeAndroidResources = true
    }
}`

**Comment by mpost** [comment]
We are also observing a similar degradation in test performance.

We have a test suite of 2150 tests which took 3:50 min to run with robolectric 3.8. With 4.1 (on windows) we are seeing execution times of around 8 minutes. Additionally the CPU load goes up drastically (nearly 100%) when approaching the last quarter of the the test suite, slowing down even further towards the end.

We are using the binary resource mode and target sdk 28.

That is really unfortunate since in general the promise of better resource resolution with 4.x is keeped. We are able to test scenarios which where not possible before (eg resolve fraction resource values).

**Comment by cesar1000** [comment]
We're seeing similar regressions in our larger module, with test execution times going from 8 minutes in 3.8 to 13 minutes in 4.x. I investigated the regression and found that it's caused by the invalidation of the shadow pickers. Removing this line in `ShadowMap` resolves the regression - at the cost of disabling the shadow picker mechanism:

https://github.com/robolectric/robolectric/commit/b15df5ac202015ed59062a2cbdcb86c2a90c3870#diff-d1301cabaebaa472b1513bda415686d1R164

The problem is that invalidating all classes that use shadow pickers causes them to be re-instrumented on every single test. This shows up in a profile as a huge spike in the instrumentation for all methods in any of those classes:

![image](https://user-images.githubusercontent.com/2517200/52146048-82ad2780-2617-11e9-943b-aaf4eb2ad87d.png)

Also, the classes that are being re-instrumented in all tests happen to be particularly expensive:

```
android.content.res.ApkAssets
android.content.res.AssetManager
android.content.res.AssetManager$AssetInputStream
android.content.res.Resources$Theme
android.content.res.ResourcesImpl
android.content.res.ResourcesImpl$ThemeImpl
```

I think that, ideally, the invalidation mechanism should be smart enough to determine whether the shadow that was used when instrumenting a class is still valid, and only invalidate it otherwise.

**Comment by xian** [comment]
I think I was being overly defensive; `ShadowPicker` is deterministic per sandbox and shouldn't need to trigger invalidation. @cesar1000, do you see any fails/issues when you remove that line?

**Comment by cesar1000** [comment]
Thanks, @xian! We've been running in master since last Friday and haven't seen any issues - we're only using legacy resources in all projects though.

**Comment by christopheblin** [comment]
I can confirm this is much better now (around 1 min 50 instead of 3 min 30s)

**Comment by esafirm** [comment]
> We're seeing similar regressions in our larger module, with test execution times going from 8 minutes in 3.8 to 13 minutes in 4.x. I investigated the regression and found that it's caused by the invalidation of the shadow pickers. Removing this line in `ShadowMap` resolves the regression - at the cost of disabling the shadow picker mechanism:
> 
> [b15df5a#diff-d1301cabaebaa472b1513bda415686d1R164](https://github.com/robolectric/robolectric/commit/b15df5ac202015ed59062a2cbdcb86c2a90c3870#diff-d1301cabaebaa472b1513bda415686d1R164)
> 
> The problem is that invalidating all classes that use shadow pickers causes them to be re-instrumented on every single test. This shows up in a profile as a huge spike in the instrumentation for all methods in any of those classes:
> 
> ![image](https://user-images.githubusercontent.com/2517200/52146048-82ad2780-2617-11e9-943b-aaf4eb2ad87d.png)
> 
> Also, the classes that are being re-instrumented in all tests happen to be particularly expensive:
> 
> ```
> android.content.res.ApkAssets
> android.content.res.AssetManager
> android.content.res.AssetManager$AssetInputStream
> android.content.res.Resources$Theme
> android.content.res.ResourcesImpl
> android.content.res.ResourcesImpl$ThemeImpl
> ```
> 
> I think that, ideally, the invalidation mechanism should be smart enough to determine whether the shadow that was used when instrumenting a class is still valid, and only invalidate it otherwise.

Hi @cesar1000 what profiler did you use on this one?

**Comment by cesar1000** [comment]
That was YourKit running on a Gradle test executor.

**Comment by esafirm** [comment]
Thanks @cesar1000
