### ISSUE TITLE
Automatic migration doesn't work with kapt

### ISSUE THREAD

**Issue by Kisty** [robolectric/robolectric#4144]
### Description
First off, thanks for the migration tool and the amazing work that you're doing for on and off device tests! The migration tool promises a lot and is going to help with the migration. 

Using the migration tool doesn't work when using kapt due to issue with error prone Gradle plugin. Tried with gradle `4.6`, `4.10`. Keeps saying `plugin ErrorProne not found`. Looks like this is fixed in Gradle `5.0-rc-1`, though I need to double check. 
See https://github.com/tbroyer/gradle-errorprone-plugin/issues/11 

### Steps to Reproduce
Open https://github.com/Kisty/android-boilerplate.
Change gradle-wrapper.properties to gradle 4.10.

### Robolectric & Android Version
Robolectric: `3.8`
Android: `26`

### Link to a public git repo demonstrating the problem:
https://github.com/Kisty/android-boilerplate/tree/robolectric-kapt-migration-issue

**Comment by xian** [comment]
Unfortunately, even if you get past that issue, the migration tool isn't going to be able to help with Kotlin files... we'd love to support it but ErrorProne's refactoring only supports Java code so far. Sorry!

**Comment by Kisty** [comment]
No worries. Thanks!
