### ISSUE TITLE
Room migration tests failed because SQLite version doesn't match sdk version

### ISSUE THREAD

**Issue by romankivalin** [robolectric/robolectric#4209]
### Description
When running Room migration tests with robolectric, they run on SQLite version 3.7.10 regardless of sdk version. If we have entities with compound primary key, Room cannot validate their integrity because it relies on `pk` column from `pragma table_info(...)`, which was changed in SQLite 3.7.16.2. It gives the following error:
```
java.lang.IllegalStateException: Migration failed.
Expected:TableInfo{name='todo_items', columns={list_id=Column{name='list_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1}, item_id=Column{name='item_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=2}, completed=Column{name='completed', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0}, title=Column{name='title', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]} 
found:TableInfo{name='todo_items', columns={list_id=Column{name='list_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1}, item_id=Column{name='item_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1}, completed=Column{name='completed', type='integer', affinity='3', notNull=true, primaryKeyPosition=0}, title=Column{name='title', type='text', affinity='2', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=null}
```

Normally, Room handles this by testing android sdk version: if it's 20+, then Room assumes new behavior of `pk` column.

### Steps to Reproduce
1. Setup room database and entity with compound primary key;
1. Make some changes to entity, increment schema version and add migration;
1. Test this migration with room's MigrationTestHelper;

### Robolectric & Android Version
4.1-SNAPSHOT; sdk=28; resources=binary;
DEBUG: SQLite version: library 282 / core 3.7.10

### Link to a public git repo demonstrating the problem:
https://github.com/romankivalin/robolectric-room-migration

**Comment by musooff** [comment]
Any solution? I also came with across this issue. 
It is Robolectric problem or Room problem?

**Comment by PaulWoitaschek** [comment]
I think it's a robolectric issue as it doesn't match the framework behavior.

The only solution is to run sql tests on real devices / or emulators.

**Comment by remvst** [comment]
Is it possible to bump the SQLite version that Robolectric uses? It'd make it much easier to test migrations, because other than this `pk` column, everything seems to work.

**Comment by jongerrish** [comment]
From: https://developer.android.com/training/data-storage/room/testing-db

For testing on your host machine: """Note: Even though this setup allows your tests to run very quickly, it isn't recommended because the version of SQLite running on your device—and your users' devices—might not match the version on your host machine."""

At the lest we should bump the SqlLite version to latest used by the platform.

Best, provide a version of SqLite that matches each version of Android we support correctly.

**Comment by jongerrish** [comment]
List of Android Versions to SqLite Versions:-

https://developer.android.com/reference/android/database/sqlite/package-summary

**Comment by guness** [comment]
I have created a utility library to fix this issue.
https://github.com/guness/RobolectricSQLite
for newer versions of Robolectric, I plan to create a PR. however cannot run tests on my local.

**Comment by pm-coffee** [comment]
And what happened then?

**Comment by guness** [comment]
@pm-coffee 

I think we can close this. a solution has been merged already:

#5216

**Comment by hoisie** [comment]
Thanks! In the process of pushing out 4.5, so this will be available. soon   .
