### ISSUE TITLE
Can't remove user with ShadowUserManager

### ISSUE THREAD

**Issue by JesusFreke** [robolectric/robolectric#4302]
### Description
There are a few related issues:

1. There is no public API to remove a user from the shadow user manager
2. The protected removeUser API doesn't completely remove a user. It only deletes it from userInfoMap, but not from userProfiles, so something like getUserForSerialNumber() still returns a non-null value for a removed user.
3. The static reset() method doesn't reset user state.

### Steps to Reproduce

shadowOf(userManager).addUser(10, "secondary", 0);
ShadowUserManager.reset();
// still returns the old user handle
UserHandle userHandle = userManager.getUserForSerialNumber(10);

### Robolectric & Android Version
as of commit 9e2b663f2dec96ac202da12c4bb472703ba52d1f

**Comment by hoisie** [comment]
Seems to have been fixed in #5353
