### ISSUE TITLE
sorry, not supporting public abstract android.content.pm.PackageInfo android.content.pm.IPackageManager.getPackageInfoVersioned(android.content.pm.VersionedPackage,int,int) throws android.os.RemoteException yet!

### ISSUE THREAD

**Issue by mruppaner** [robolectric/robolectric#4318]
### Description
Looks like ShadowApplicationPackageManager needs to shadow "PackageInfo getPackageInfo(VersionedPackage versionedPackage, int flags)"

### Steps to Reproduce
Try to write test for https://developer.android.com/reference/android/content/pm/PackageManager.html#getPackageInfo(android.content.pm.VersionedPackage,%20int)

**Comment by hoisie** [comment]
That method is shadowed now: https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java#L408
