### ISSUE TITLE
Robolectric Shadows fails with Jetiffier Transformation with Android Gradle 

### ISSUE THREAD

**Issue by ashmosaheb** [robolectric/robolectric#4324]
Robolectric Shadows fails with Jetiffier Transformation with Android Gradle 

### Steps to Reproduce
Add Robolectric Shadows and gradle sync project

### Robolectric & Android Version
Android Gradle Build Tools: 3.3.0-rc02
Build Tools Version 28.0.3
Robolectric 4.1 (happens on 3.8 too with the Android Gradle Build 3.3.0)

**Comment by rvoortman** [comment]
Have you tried to invalidate the cache? File -> Invalidate Cache and Restart worked for me in Android Studio.

**Comment by ashmosaheb** [comment]
This happened on command line

**Comment by KITSBurakEregar** [comment]
I've got the same issue. Has anyone found any workaround or an actual fix, please?

**Comment by burakeregar** [comment]
I've got the same issue. Has anyone found any workaround or an actual fix, please?

**Comment by huangyz0918** [comment]
> I've got the same issue. Has anyone found any workaround or an actual fix, please?
+1

**Comment by sterlingwes** [comment]
Workaround by adding

`android.jetifier.blacklist=shadows` to gradle.properties

The suggestion over in https://github.com/robolectric/robolectric/issues/4491#issuecomment-498603341 led to this fix for me

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and I think it can work great with jetiffier without extra configurations except adding bouncy castle to blacklist. Feel free to reopen this issue if it still exists.
