### ISSUE TITLE
TextPaint.getTextBounds always returns 0

### ISSUE THREAD

**Issue by chebum** [robolectric/robolectric#4343]
### Description
TextPaint.getTextBounds("123", 0, 3, bounds) always returns empty rect (all coordinates are zero). I tried loading typeface from a file using Typeface.createFromFile and also tried Typeface.create("roboto", Typeface.BOLD). The result is the same. TextPaint.measureText("123") returns 3.0.

Are these methods supposed to work in robolectric unit tests?
If these should work, I'll prepare a test project.

### Robolectric & Android Version
4.1, Android SDK 27, legacy resources

**Comment by utzcoz** [comment]
@chebum Please try the latest Robolectric and use native graphics mode for your tests, and I think it can support `getTextBounds` with real rendering.
