### ISSUE TITLE
UserManager.isUserUnlocked(UserHandle) is not supported

### ISSUE THREAD

**Issue by JesusFreke** [robolectric/robolectric#4376]
### Description
ShadowUserManager has a shadow implementation for isUserUnlocked(), but not isUserUnlocked(UserHandle)

### Robolectric & Android Version

robolectric version: 9e2b663f2dec96ac202da12c4bb472703ba52d1f

**Comment by utzcoz** [comment]
@JesusFreke it is fixed by commit https://github.com/robolectric/robolectric/commit/159a2fd308c169a791acfc1599b0f291571996a2, you can use the latest stable release. @hoisie maybe this issue can be closed.

**Comment by utzcoz** [comment]
The PR is here: https://github.com/robolectric/robolectric/pull/5323.

**Comment by hoisie** [comment]
Thanks @utzcoz
