### ISSUE TITLE
How can I run the same test for both landscape and potrait layout.

### ISSUE THREAD

**Issue by vishalvisd** [robolectric/robolectric#440]
Is there a way to write a test that will test both landscape and portrait layout. For example, I have layout files for both landscape and portrait orientation. Instead of writing two test like the following, what is the other way to test both layout in one test.

```
@Test
@org.robolectric.annotation.Values(qualifiers = "en-port")
public void shouldPerformTestCaseOne() 

}       
@Test
@org.robolectric.annotation.Values(qualifiers = "en-land")
public void shouldPerformTestCaseOneLand() {

}
```

**Comment by jaredsburrows** [comment]
@visdgithub  Does the `@Config(constants = BuildConfig.class, qualifiers = "port")` still work for you?

**Comment by ArunYogeshwaran** [comment]
@Config(qualifiers = "en-land") works now
