### ISSUE TITLE
java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout

### ISSUE THREAD

**Issue by GitHubMurt** [robolectric/robolectric#4508]
### Description
I'm getting `java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout` when try to run test

`activity = Robolectric.setupActivity(ConvergedWrapperActivity::class.java)` <- that line causes exception

### Steps to Reproduce
```java
@RunWith(RobolectricTestRunner ::class)
@Config(packageName = "xxx",
        sdk = [24],
        manifest = "AndroidManifest.xml")
@PowerMockIgnore("org.mockito.*", "org.robolectric.*", "android.*","javax.xml.*", "org.xml.sax.*", "org.w3c.dom.*",  "org.springframework.context.*", "org.apache.log4j.*")

@Ignore
open class MyRobolectric {

    @get:Rule
    val rule = PowerMockRule()

    lateinit var activity: MyActivity
    lateinit var context: Context

    @Before
    fun setupData(){
        activity = Robolectric.setupActivity(MyActivity::class.java)
}
...
}
```
### Robolectric & Android Version
```groovy
androidTestImplementation 'androidx.test:runner:1.1.1'
testImplementation "org.robolectric:robolectric:4.1"
android.enableUnitTestBinaryResources=true
```

```xml
<uses-library android:name="android.test.runner"
                      android:required="false" />
```

**Comment by xian** [comment]
I suspect this is related to your use of PowerMock; is it necessary for this test?

**Comment by GitHubMurt** [comment]
Finally we stay by configuration, that is working on.
There is some inconviniency in roboelectric .jar file so it doesn't refresh, You have to first downgrade to  `testImplementation "org.robolectric:robolectric:4.0"` then upgrade to  `testImplementation "org.robolectric:robolectric:4.1"`

`    testImplementation "org.mockito:mockito-core:2.8.9"
    String powerMockito = "1.7.4"
    testImplementation "org.powermock:powermock-core:$powerMockito"
    testImplementation "org.powermock:powermock-module-junit4:$powerMockito"
    testImplementation "org.powermock:powermock-api-mockito2:$powerMockito"
    testImplementation "org.powermock:powermock-module-junit4-rule:$powerMockito"
    testImplementation "org.powermock:powermock-classloading-xstream:$powerMockito"
    testImplementation 'androidx.test:core:1.1.0'

    testImplementation "org.robolectric:robolectric:4.1"`

Add new element **androidx.*** to @PowerMockitoIgnore

`@RunWith(RobolectricTestRunner ::class)
@Config(packageName = "xxx",
        sdk = [24],
        manifest = "AndroidManifest.xml")
@PowerMockIgnore("org.mockito.*", "org.robolectric.*", "android.*", "androidx.*")
@Ignore
abstract class MyRobolectric {

    @get:Rule
    val rule = PowerMockRule()

    lateinit var activity: ConvergedWrapperActivity
    lateinit var context: Context

    @Before
    fun setupData(){
        activity = Robolectric.setupActivity(ConvergedWrapperActivity::class.java)
        activity.setContentView(R.layout.converged_activity_main)
        context = ApplicationProvider.getApplicationContext()
        Manager.setActivity(activity)
    }

    protected fun findViewById(id: Int) = activity.findViewById<View>(id)!!
}`
