### ISSUE TITLE
android_local_test should use Java 9 by default if available

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4529]
b/123195372

**Comment by danielesegato** [comment]
on what ground?

**Comment by utzcoz** [comment]
Looks like `android_local_test` can run tests with JDK 9 and above JDK versions now, see https://github.com/bazelbuild/rules_jvm_external/tree/master/examples/android_local_test. Hi @hoisie , could you help to check whether internal b/123195372 was fixed already? Thanks.
