### ISSUE TITLE
Build failure when using shadowOf with ContentResolver

### ISSUE THREAD

**Issue by guillaume-roche** [robolectric/robolectric#4544]
### Description

When I try to use `shadowOf()` with my activity ContentResolver passed as parameter, I get the following build error:
```
error: cannot access AccessibilityButtonController
class file for android.accessibilityservice.AccessibilityButtonController not found
```

### Steps to Reproduce

Create the following setup method, in a test class and build it:

```java
@Config(sdk=android.os.Build.VERSION_CODES.LOLLIPOP_MR1)
@RunWith(RobolectricTestRunner.class)
public class MyTest {

    private MainActivity activity;
    private ShadowContentResolver shadowContentResolver;

    @Before
    public void setup() throws Exception {
        activity = Robolectric.setupActivity(MainActivity.class);
        shadowContentResolver = shadowOf(activity.getContentResolver());
    }
}
```

### Robolectric & Android Version

targetSdk 25
Gradle 3.3.0
Robolectric 4.1

**Comment by xian** [comment]
Yep, you generally want to be compiling against the latest version of the API.

**Comment by guillaume-roche** [comment]
Agreed. That's not my case though, as my work targets specific devices that have sdk version 22.

Anyway, the build failure is related to the use of `shadowOf()`, so there must be some bug here. I don't really understand why there is this limitation on the latest sdk. Is there any documentation somewhere about this?
