### ISSUE TITLE
How Safe are Robolectric Tests?

### ISSUE THREAD

**Issue by gchallen** [robolectric/robolectric#4557]
(Not using the standard issue template because this is not a bug report.)

I teach a large introductory programming course and would like to use Robolectric for testing small pieces of API design on Android programming assignments. We usually factor things so that student are working on a library that can be compiled and tested separately, mainly to avoid the overhead of Android UI testing. But then we found Robolectric and are excited that we can start to also include UI tests in our grading suites.

One thing I'm concerned about, however, is safety. Our automated testing runs on a single machine. I've been using ProGrade to enforce a restrictive Java security policy, meaning that at this point our testing isn't containerized. And even that can't necessarily stop clever students from doing things like writing directly to the test output files.

I've spent a few hours trying to get ProGrade or any kind of Java security policy to work for the JVM that runs Robolectric and at this point am declaring defeat. But it occurred to me that Robolectric probably provides its own sandbox of sorts as part of trying to emulate an Android device.

So my question is how restrictive is that sandbox? Assume that we trust the test suite since we copy over a known good copy. Assume we _don't_ trust anything in `app/src/main`, including `MainActivity.java` and other app-specific files. What could malicious code in those files do? Read, write, or remove arbitrary files on the host filesystem? Generate tons of network traffic? Run forever? (We do enforce timeouts in several places, which I think work.)

Thanks in advance for the advice.

**Comment by xian** [comment]
Hey @gchallen — sorry for the lag getting back to you.

Robolectric's idea of sandboxing is a bit different from what you're hoping for, unfortunately: test and framework classes are isolated from each other for each SDK levels, but we don't restrict access to the local filesystem in any way. Definitely nothing that would stop nefarious actors.

It seems possible we could get ProGrade working *inside* a Robolectric sandbox though; I'd be happy to take a stab at getting that working if you could give me a starting point?

**Comment by hoisie** [comment]
Closing this as there is nothing here that seems actionable. If you want to make Robolectric work with ProGrade we'd be happy to review PRs.

I should say that if you want the additional security nothing really beats running each student's tests in something like a separate docker container. Students would be able to do whatever malicious thing they want without having consequences on the host system.

**Comment by gchallen** [comment]
Thanks! We already run tests in Docker containers. However, the test has to produce trusted output (example: a file) that leaves the container, so there's still the opportunity for student code to attack that part of the grading process even inside a container. But I'm not super concerned about that.
