### ISSUE TITLE
No coverage in Android Studio

### ISSUE THREAD

**Issue by SauliusTheBlack** [robolectric/robolectric#4576]
### Description
When using the built in "Run with coverage" the tests with RobolectricRunner don't generate any coverage with the built in jacoco coverage generator

### Steps to Reproduce
Class Under Test:
```
public class Bogo {
    public static int showCoverage(int a, int b){
        if(a > b) {
            return a - b;
        } else {
            return a + b;
        }
    }
}
```
test
```
@RunWith(RobolectricTestRunner.class)
public class AnyTest {
    @Test
    public void someTest(){
        Assert.assertEquals(3, Bogo.showCoverage(1, 2));
        Assert.assertEquals(1, Bogo.showCoverage(2,1));
        Assert.assertEquals(4, Bogo.showCoverage(2,2));
    }
}
```
### Robolectric & Android Version
Android Studio 3.3
default jacoco version
Robolectric 4.0.1

**Comment by bilal-** [comment]
Is this issue valid or actually open? I do not see any discussion. We are facing something very similar with Android Studio 3.4.2 using Robolectric 4.1.

After migrating to Gradle 5.x and Android Gradle Plugin 3.4.2, we’re facing some issues with our jacoco coverage report. The coverage % dropped significantly and after some inspection, we’ve noticed that our Robolectric tests are not being included in the report. Specifically, the unit tests that are annotated with @RunWith(RobolectricTestRunner.class) simply do not get included in the execution data. These tests are showing up just fine in the Test Summary section so gradle did run them.

**Comment by sonphan12** [comment]
Any update on this issue? I'm facing the same thing.

**Comment by utzcoz** [comment]
Duplicate to https://github.com/robolectric/robolectric/issues/3023. Feel free to reopen it if you think it has different root cause.
