### ISSUE TITLE
Sync with android repo fork

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4598]
- [ ] Reconcile with https://android.googlesource.com/platform/external/robolectric-shadows/

**Comment by utzcoz** [comment]
@hoisie Does google branch do similar things?

**Comment by utzcoz** [comment]
Now the google branch as the purpose to sync code between GitHub master branch and Google's branches, and folks from AOSP to sync google branch into https://android.googlesource.com/platform/external/robolectric. IMO, it's stable and good enough to sync code between AOSP and GitHub. cc @hoisie @brettchabot .
