### ISSUE TITLE
./gradlew testDebug: failed test in PermissionsTest. permissionCheck 

### ISSUE THREAD

**Issue by wbagais** [robolectric/robolectric#4620]
Software and hardware versions
Collect v1.2.0, Android v3.2.1, mac

### Description
after cloning the project, I tried to run the test command `./gradlew testDebug` in mac terminal, and I get below errors:

#### in Test Summary:
PermissionsTest. permissionCheck:
- java.lang.AssertionError: Expected permission android.permission.READ_PHONE_STATE is missing from AndroidManifest.xml

Stander error:
- No such manifest file: build/intermediates/manifests/full/debug/AndroidManifest.xml No such manifest file: build/intermediates/manifests/full/debug/AndroidManifest.xml

#### in AndroidManifest.xml code:
Missing URL
Ensure the URL is supported by your app, to get installs and traffic to your app from Google Search.  Issue id: AppLinkUrlError 
            `<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <action android:name="android.intent.action.EDIT" />
                <action android:name="android.intent.action.PICK" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="vnd.android.cursor.dir/vnd.odk.form" />
            </intent-filter>`

#### in IDE Fatal Errors:
java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: List is empty.
Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException: List is empty.

What is the problem and how can I fix it?

**Comment by xian** [comment]
@wbagais — I'm not sure which project you're referring to, but generally `testDebug` isn't used with Robolectric. I'm happy to point you in the right direction if you can give me a little more detail though.

**Comment by wbagais** [comment]
@xian sorry I post the issue in a wrong place
