### ISSUE TITLE
CDATA whitespace is not preserved

### ISSUE THREAD

**Issue by TWiStErRob** [robolectric/robolectric#4685]
### Description
https://github.com/robolectric/robolectric/pull/3791/commits/ad40a23a02b0347f63d31a8abd54ea58ae0bdaee (released first in 3.8) changed how `CDATA` is read. This doesn't match how Android works.
/cc @jongerrish @brettchabot

### Steps to Reproduce
Run a Robolectric test where the production code does `resources.getString(R.string.query)` and observe the characters in the String. It should have spaces/tabs/newlines as laid out below.
```xml
	<string name="query" translatable="false"><![CDATA["
		select
			x_id         as _id,
			x.name       as name,
--			y.parent     as parent,
			y.value      as value
		from X x
		join Y y on x.foo = y.bar
	"]]></string>
```
I have a live app with many users that uses this pattern for every DB query it does.
Some unit tests broke when I update to 3.8/4.x, because the `--` is till the end of the line, which eats the whole rest of the string instead of just the line in the source code.

### Robolectric & Android Version
Robolectric 3.8 and up collapses, <3.8 it was working the same as Android.

### Link to a public git repo demonstrating the problem:
will do if necessary.

**Comment by jongerrish** [comment]
Sorry about the breakage.

We're not investing in legacy resources any more. Can you try with binary resources?

http://robolectric.org/blog/2018/10/25/robolectric-4-0/

This avoids bugs like the one you came into as we no longer need to emulate the behavior of aapt.

**Comment by TWiStErRob** [comment]
I can't use Robolectric 4.x with binary resources, because it doesn't work on Windows... kind of an in between position... 3.8 is broken, 4.x is broken; so staying 3.7 for now. Also 4.2/binary resources seems to require using AGP 3.4+ which is not stable yet.

**Comment by jongerrish** [comment]
Ah, man I'm sorry :-/

I think @xian has a fix for the Windows issue which _should_ make it into 4.2.1 hopefully that will unblock you.

**Comment by TWiStErRob** [comment]
That would be nice, not having to wait for the next major AGP.
