### ISSUE TITLE
Cannot use JUnit 4.12 single parameter syntax

### ISSUE THREAD

**Issue by rudym87** [robolectric/robolectric#4718]
### Description
ParameterizedRobolectricTestRunner does not support single parameter syntax defined [here](https://github.com/junit-team/junit4/wiki/parameterized-tests#tests-with-single-parameter).
### Steps to Reproduce
Run a test class with `ParameterizedRobolectricTestRunner` and define the parameters like this:
````java
@ParameterizedRobolectricTestRunner.Parameters
public static Iterable<? extends Object> data() {
    return Arrays.asList("first test", "second test");
}
````
or
````Java
@ParameterizedRobolectricTestRunner.Parameters
public static Object[] data() {
    return new Object[] { "first test", "second test" };
}
````
First one fails with
````java
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
	at org.robolectric.ParameterizedRobolectricTestRunner.<init>(ParameterizedRobolectricTestRunner.java:283)
...
````
Second one fails with
````java
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.List
	at org.robolectric.ParameterizedRobolectricTestRunner.getParametersList(ParameterizedRobolectricTestRunner.java:298)
	at org.robolectric.ParameterizedRobolectricTestRunner.<init>(ParameterizedRobolectricTestRunner.java:281)
...
````
### Robolectric & Android Version
Robolectric 4.2

**Comment by jongerrish** [comment]
Hey @rudym87 is this something you'd be willing to have a go with a contribution. I'd say honestly that's the best way of getting quick progress on this issue.

**Comment by utzcoz** [comment]
Hi @rudym87 , the next release of `Robolectric` after `4.6.1` will contain PR to support this feature. You can try it after release.
