### ISSUE TITLE
AGP should merge test AndroidManifest.xml

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4726]
Bazel's `android_local_test` provides the ability to merge a test `AndroidManifest.xml` but AGP doesn't.

Since #4489, Robolectric no longer automatically creates manifest entries for unknown activities, which has led to issues like #4649 and #4640. That's the desired behavior; however, it should be possible for test authors to declare test-only activities in a test manifest.

**Comment by xian** [comment]
Work on AGP will be tracked here: http://issuetracker.google.com/issues/127986458

**Comment by MGaetan89** [comment]
> Work on AGP will be tracked here: http://issuetracker.google.com/issues/127986458

Closing this issue, since it appears to be supported in AGP now.

**Comment by utzcoz** [comment]
Officially fixed at https://issuetracker.google.com/issues/127986458. See https://androidstudio.googleblog.com/2025/06/android-studio-narwhal-feature-drop_13.html.
