### ISSUE TITLE
ava.lang.NoSuchMethodError: android.os.HandlerThread.quitSafely()Z

### ISSUE THREAD

**Issue by IceCubeDev** [robolectric/robolectric#4732]
### Description
I have a class that internally calls quitSafely() on a HandleThread. When I try to mock the return value of the quitSafely() method I get an exception "ava.lang.NoSuchMethodError: android.os.HandlerThread.quitSafely()Z".

### Steps to Reproduce
```
public class TestClass {
    private HandlerThread m_handlerThread;

    ...
    
    public TestClass() {
        m_handleThread = createHandlerThread();
    }


    HandlerThread createHandlerThread() {
        return new HandlerThread("HandlerThread");
    }

    public void termiante() {
       ...
       m_handleThread.quitSafely();
    }
}
.....
@Config(manifest=Config.NONE)
@RunWith(RobolectricTestRunner.class)
public class TestClassTest{

	private TestClass m_testClassInstance = spy(new TestClas());

	@Mock
	private HandlerThread m_mockHandlerThread;

	@Before
	public void setUp() {
        	MockitoAnnotations.initMocks(this);
        
		doReturn(m_mockHandlerThread)
                	.when(m_testClassInstance)
                	.createHandlerThread();

                when(m_mockHandlerThread.quitSafely()).thenReturn(true);
	}

	@Test
	public void terminate_Scenario_ExpectedResult() {
     		.....
	}

}
```
When running the terminate_Scenario_ExpectedResult test case the following exception is raised:

> java.lang.NoSuchMethodError: android.os.HandlerThread.quitSafely()Z
> 
> 	at com.example.TestClassTest.setUp(TestClassTest.java:60)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
> 	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
> 	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
> 	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

### Robolectric & Android Version
Roboelectric version: org.robolectric:robolectric:3.0,org.robolectric:robolectric:4.1
Mockito version: org.mockito:mockito-core:2.25.0 
Android Version: Oreo (Android 8.0)

**Comment by hoisie** [comment]
quitSafely was added in API level 18, so this test was likely running in API < 18.
