### ISSUE TITLE
Roboelectric don't run anything

### ISSUE THREAD

**Issue by afaucogney** [robolectric/robolectric#4733]
### Description

On a big project with many functional and test dependencies + legacy, I just try to integrate Roboelectric. When I started a void test case, it simply run forever without doing anything.

### Steps to Reproduce

This is due to:

```
testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```

When I removed it to use, this is running, but the resources required in the test is not found anymore !

### Robolectric & Android Version

Roboelectric 4.2
```
ext.projectBuildToolsVersion = '28.0.3'
ext.projectCompileSdkVersion = 27
ext.projectMinSdkVersion = 21
ext.projectTargetSdkVersion = 27
ext.supportVersion = "27.1.1"
```

App is multi-module

### Link to a public git repo demonstrating the problem:

```
import junit.framework.Assert.assertTrue
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment

@RunWith(RobolectricTestRunner::class)
class TryTest {

    @Test
    fun tretre() {
        val context = RuntimeEnvironment.application
        assertThat(context.getString(R.string.tutu)).isEqualTo("Consommation annuelle")
        assertTrue(true)
    }
}
```

```
WARNING: No manifest file found at ./AndroidManifest.xml.
No such manifest file: ./AndroidManifest.xml
Falling back to the Android OS resources only.
To remove this warning, annotate your test class with @Config(manifest=Config.NONE).[Robolectric] com.edf.edfetmoi.domain.usecase.conso.breakdown.Efewrfew.tretre: sdk=16; resources=LEGACY
[Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40

android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0668

	at org.robolectric.shadows.ShadowLegacyAssetManager.getResName(ShadowLegacyAssetManager.java:1259)
	at org.robolectric.shadows.ShadowLegacyAssetManager.resolveResourceValue(ShadowLegacyAssetManager.java:1042)
	at org.robolectric.shadows.ShadowLegacyAssetManager.resolve(ShadowLegacyAssetManager.java:1002)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:996)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceText(ShadowLegacyAssetManager.java:281)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:225)
	at android.content.res.Resources.getString(Resources.java:313)
	at android.content.Context.getString(Context.java:292)
```

**Comment by xian** [comment]
What version of `com.android.tools.build:gradle` are you using?

Do you have this line in your `gradle.properties`?

`android.enableUnitTestBinaryResources=true`

**Comment by afaucogney** [comment]
@xian sorry for the delay, but yes this is in !
As writen, this is a multi module apps, so I think it loose the "res" reference.

**Comment by Wy-Nasty** [comment]
I have this same issue. Can't get 4.2.1 to work.

grade version: 3.3.2
compileSDK: 28
minSDK: 18
Robolectric: 4.2.1

Also I have the following set in my gradle.properties file

android.enableUnitTestBinaryResources=true

(also tried with it off). I also have the proper resources flag set to true in my gradle file (includeAndroidResources). Either I get the Resources$NotFoundException as mentioned above or I get inflation errors. I'm coming from 3.0 so... Big leap but I've tried moving to versions 4.0.2-4.2.1 with the same issues. Also tried downgrading gradle but that did not work either.

**Comment by kalinichenkogleb** [comment]
@afaucogney Hi, do you find any solution for your problem? Because I have the same issue as you.

**Comment by 4face-studi0** [comment]
Same here with **AGP 3.6.0** and **Robolectric 4.3.1**

**Comment by niltonvasques** [comment]
Same issue here. When I set `includeAndroidResources = true` the tests disappear, if I remove it, the tests are executed but resources are not found.

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and feel free to reopen this issue if it still exists.
