### ISSUE TITLE
Tests annoted with @RunWith(RobolectricTestRunner.class) are skipped on Jenkins

### ISSUE THREAD

**Issue by martiwi** [robolectric/robolectric#4739]
### Description
All my tests which are annoted with @RunWith(RobolectricTestRunner.class) are skipped only when run on the Jenkins slave.
For unknown reason, I could not reproduce it when run locally on the same slave machine using terminal.
It is also running fine on my local machine.

Here the Gradle version and OS information of the Slave machine:
> ------------------------------------------------------------
> Gradle 4.10.1
> ------------------------------------------------------------
> 
> Build time:   2018-09-12 11:33:27 UTC
> Revision:     76c9179ea9bddc32810f9125ad97c3315c544919
> 
> Kotlin DSL:   1.0-rc-6
> Kotlin:       1.2.61
> Groovy:       2.4.15
> Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
> JVM:          10 ("Oracle Corporation" 10+46)
> OS:           Mac OS X 10.13.6 x86_64

Jenkins Version:
> Jenkins ver. 2.156

It is not linked to any Gradle caching issue as I've tried to also clean, and remove Gradle cache from both the project and the `~/.gradle/cache` folder.
This issue is a complete mystery for me, if you need anything else, please let me know.

### Steps to Reproduce
Unknown.

### Robolectric & Android Version
>     robolectricVersion          = '4.2'
>     androidBuildToolsVersion    = '28.0.3'
>     androidMinSdkVersion        = 21
>     androidTargetSdkVersion     = 24
>     androidCompileSdkVersion    = 28

**Comment by martiwi** [comment]
FYI: I've managed to have it fixed by using this plugin: https://github.com/bjoernQ/unmock-plugin

**Comment by jongerrish** [comment]
I think we'd need some more help investigating this issue to narrow it down further since we don't have a Jenkins continuous build set up.

**Comment by martiwi** [comment]
@jongerrish you've closed this issue because you won't fix it? 
I'm willing to give you whatever information you need to debug this, I'm not a big fan of my current solution as it requires an additional plugin...
