### ISSUE TITLE
"Building And Contributing" in README.md is out of date

### ISSUE THREAD

**Issue by ngbravo** [robolectric/robolectric#4783]
### Description
The top-level [README.md](https://github.com/robolectric/robolectric/blob/master/README.md) is out of date. Particularly, [Building And Contributing](https://github.com/robolectric/robolectric/blob/master/README.md#building-and-contributing) references `./scripts/install-dependencies.rb`, which no longer exists.

### Steps to Reproduce
N/A

### Robolectric & Android Version
N/A

### Link to a public git repo demonstrating the problem:
N/A

**Comment by xian** [comment]
Removed, thanks!
