### ISSUE TITLE
Render layouts

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4804]
It'd be peachy if Robolectric could render a realistic representation of arbitrary layouts.

**Comment by nikwotton** [comment]
Hey @xian, any chance you can provide an update on this?

**Comment by nikwotton** [comment]
🙏 Or better yet, an updated timeline scale (weeks vs months vs years) 🙏

**Comment by nikwotton** [comment]
Maybe even just a confirmation that it's still being worked on? @xian

**Comment by nikwotton** [comment]
...how about confirmation anyone sees these notifications and that they want me to shut up? @xian or @anyone ?

**Comment by nikwotton** [comment]
😭

**Comment by ming13** [comment]
@nikwotton, dude, please stop. This went from curiosity to notification harassment. Also, wait [for Square to release their thing](https://twitter.com/arturdryomov/status/1148464625832402944).

**Comment by nikwotton** [comment]
@ming13 First off I would like to apologize - I realize this was a bit more than I should've done. I'm happy waiting for the feature to be released, I just didn't know if it was even still being worked on or if waiting was pointless. I didn't know how else to find out other than to harass a bit, considering nothing had been said on the matter for 4 months (that I'd known of). Also, I had not seen that video by square! Thank you so much for bringing that to my attention! Again, I apologize for the annoyance, and hope I haven't bugged you too much.

**Comment by sebaslogen** [comment]
> @nikwotton, dude, please stop. This went from curiosity to notification harassment. Also, wait [for Square to release their thing](https://twitter.com/arturdryomov/status/1148464625832402944).

The thing was released, a library to render Android screens without a physical device or emulator.
Maybe useful for Robolectric to build this feature?
https://github.com/cashapp/paparazzi

**Comment by utzcoz** [comment]
@hoisie I think latest native graphics mode does.
