### ISSUE TITLE
use robolectric with powermock doNothing not work  

### ISSUE THREAD

**Issue by ZhouShowfew** [robolectric/robolectric#4836]
### Description
when I use robolectric with PowerMockRule I Wirite test doNothing.when(viewmodel).doSomeX();  will reduce error org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here....
but when I comment PowermockRule line and use PowerMockRunner it works.
### Steps to Reproduce
this is my code:
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, application = TestApplication.class)
@PowerMockIgnore({ "org.mockito.*", "org.robolectric.*", "android.*", "org.powermock.*" })
public class ReceiptViewModelUnitTest {
    @Inject
    ReceiptViewModel viewModel;
    @Inject
    GlobalDataSource globalDataSource;

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    @Before
    public void setup() {
        TestInjector.getComponent().inject(this);
        viewModel = spy(viewModel);
    }

    @Test
    public void onCreate_X_ShouldWork() {
        doNothing().when(viewModel).initValue();
        doNothing().when(viewModel).getUser();

        viewModel.onCreate();

        verify(viewModel).initValue();
        verify(viewModel).getUser();
    }
}
### Robolectric & Android Version
robolectric 3.4.2
powermock 1.7.1
mockito 2.8.9
android SDK 25 
gradle  3.1.0
android studio 3.0

**Comment by dmeng** [comment]
@ZhouShowfew In order to reproduce what you're seeing, we need more than just the one test file. What exactly are ReceiptViewModel, GlobalDataSource, and TestInjector? 

In particular, how does TestInjector.getComponent().inject(this) work? Without knowing exactly how you're populating viewModel before the doNothing() calls, there just isn't enough information to diagnose anything.

**Comment by ZhouShowfew** [comment]
thank you, Sorry for reply so later.
This is ReceiptViewModel:

 @Inject
    GlobalDataSource globalDataSource;
    @Inject
    Application context;
    @Inject
    UserRepository userRepository;

    public MutableLiveData<UserInfoDataHolder> userInfoDataHolder = new CustomMutableLiveData<>();
    public NonStickyStore<PopupEvent<BasePopup>> popupEvent = new NonStickyStore<>();
    // Todo: migrate this to data binding once we remove the hidden api stuff
    // Current hidden api is not working with data binding lib
    public MutableLiveData<Boolean> enableSendReceipt = new MutableLiveData<>();
    public MutableLiveData<Boolean> showEmailError = new MutableLiveData<>();
    public MutableLiveData<Boolean> showTextError = new MutableLiveData<>();
    public MutableLiveData<Boolean> showKeyBoard = new MutableLiveData<>();
    public CustomMutableLiveData<GoToActivityEvent> goToActivityType = new CustomMutableLiveData<>();

    @Inject
    public ReceiptViewModel() {}

    @Override
    public void onCreate() {
        initValue();
        getUser();
    }

    void initValue() {
        enableSendReceipt.setValue(true);
        showEmailError.setValue(false);
        showTextError.setValue(false);
        userInfoDataHolder.setValue(UserInfoDataHolder.builder().build());
    }

    void getUser() {
        userRepository.getUser()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(user -> handleUser(user), err -> {});
    }
TestInjector.class:
public class TestInjector {
    public static TestComponent getComponent() {
        return DaggerTestComponent.builder()
                .testModule(new TestModule())
                .testProxyModule(new TestProxyModule())
                .testRepositoryModule(new TestRepositoryModule())
                .testUseCaseModule(new TestUseCaseModule())
                .build();
    }
}
TestComponent.class:
@Singleton
@Component(modules = {TestModule.class, TestProxyModule.class, TestRepositoryModule.class, TestUseCaseModule.class})
public interface TestComponent {
    void inject(ReceiptViewModelUnitTest receiptViewModelUnitTest);
}
GlobalDataSource.class:
public class GlobalDataSource {
    private static volatile GlobalDataSource defaultInstance;

    private Variant currentVariant = null;
    private volatile double lastWeight = -Double.MAX_VALUE;
    private volatile double lastStableWeight = -Double.MAX_VALUE;
    private volatile double initialWeight = -Double.MAX_VALUE;
    private Order order = null;
    private int produceCount = 0;
    private double produceWeight = 0;
    private double totalWeight = 0;
    private boolean ageVerified = false;
    private Map<String, String> paymentInfo = null;
    private int userRating = 0;
    private Device currentDevice = null;
    private boolean finalChecked = false;
    private DeviceState deviceState = DeviceState.IDLE;
    private Map<Long, Variant> cachedVariants = null;
    private boolean produceAddPopupShown = false;
    private EnumMap<Tutorials, Boolean> tutorialStates = new EnumMap<>(Tutorials.class);
    private Customer currentCustomer = null;
    private PaymentToken currentPaymentToken = null;
    private AtomicBoolean isUpdatePageOn = new AtomicBoolean(false);
    private boolean isReset = false;
    private User currentUser = null;

    public enum DeviceState {
        IDLE,
        IN_PROGRESS,
        PAID_LEGAL,
        PAID_PENDING
    }
    public enum Tutorials {
        PER_UNIT_ITEMS(false),
        ADD_PRODUCE(true);

        private final boolean defaultEnabled;

        Tutorials(boolean defaultEnabled) {
            this.defaultEnabled = defaultEnabled;
        }

        public boolean getDefaultEnabled() {
            return defaultEnabled;
        }
    }

    public static GlobalDataSource getDefault() {
        if (defaultInstance == null) {
            Class c = GlobalDataSource.class;
            synchronized (GlobalDataSource.class) {
                if (defaultInstance == null) {
                    defaultInstance = new GlobalDataSource();
                }
            }
        }
        return defaultInstance;
    }

    private GlobalDataSource() {}

    public void resetData() {
        currentVariant = null;
        lastWeight = -Double.MAX_VALUE;
        lastStableWeight = -Double.MAX_VALUE;
        initialWeight = -Double.MAX_VALUE;
        order = null;
        produceCount = 0;
        produceWeight = 0;
        totalWeight = 0;
        ageVerified = false;
        paymentInfo = null;
        userRating = 0;
        finalChecked = false;
        deviceState = DeviceState.IDLE;
        cachedVariants = null;
        resetTutorials();
        produceAddPopupShown = false;
        currentPaymentToken = null;
        isReset = false;
        currentUser = null;
        currentCustomer = null;
    }

    public Map<Long, Variant> getCachedVariants() {
        if (cachedVariants == null) {
            cachedVariants = new HashMap<>();
        }
        return cachedVariants;
    }

    public Variant getCachedVariantById(Long variantId) {
        Variant variant = null;
        if (cachedVariants != null) {
            variant = cachedVariants.get(variantId);
        }
        return variant;
    }

    public void setCachedVariants(Map<Long, Variant> cachedVariants) {
        this.cachedVariants = cachedVariants;
    }

    public Variant getCurrentVariant() {
        return currentVariant;
    }

    public void setCurrentVariant(Variant currentVariant) {
        this.currentVariant = currentVariant;
    }
.........
Is these information enough？

**Comment by ZhouShowfew** [comment]
It may cause PowerMock and Robolectric 's compatibility, finally I abandon use powermock with robolectric.
