### ISSUE TITLE
NullPointerException on sendOrderedIntent with a null receiver

### ISSUE THREAD

**Issue by goj** [robolectric/robolectric#4884]
### Description
Android [is happy](https://developer.android.com/reference/android/content/Context.html#sendOrderedBroadcast(android.content.Intent,%20java.lang.String,%20android.content.BroadcastReceiver,%20android.os.Handler,%20int,%20java.lang.String,%20android.os.Bundle)) with null BroadcastReceivers in sendOrderedBroadcast, but they cause `NullPointerException`s when tested.

### Steps to Reproduce
1. Have this in the application code:

```java
    context.sendOrderedBroadcast(
        intent,
        /* receiverPermission= */ null,
        /* resultReceiver= */ null, // ← this is important
        /* scheduler= */ null,
        /* initialCode= */ Activity.RESULT_CANCELED,
        /* initialData= */ null,
        /* initialExtras= */ null);
```

2. Write a  Robolectric test that executes the code above

3. See the `NullPointerException` caused by a null `wrapper.broadcastReceiver` in [ShadowInstrumentation.java:358](https://github.com/robolectric/robolectric/blob/acb7af7fa09c86677baa07e1db986c760e4b70f3/shadows/framework/src/main/java/org/robolectric/shadows/ShadowInstrumentation.java#L358)
### Robolectric & Android Version
Roboelectric: https://github.com/robolectric/robolectric/commit/f710d2f7b10eada32238364d03bfee146329808a
Android P

### Link to a public git repo demonstrating the problem:
n/a

**Comment by utzcoz** [comment]
This is already fixed by commit https://github.com/robolectric/robolectric/commit/18e1b0067ec0ae769dc09b8a5500777c0f2db41c , you can use the latest release to check it. Hi @hoisie , this issue could be closed.

**Comment by utzcoz** [comment]
The PR is here: https://github.com/robolectric/robolectric/pull/5063.

**Comment by hoisie** [comment]
Thanks @utzcoz
