### ISSUE TITLE
NOTICE: legacy resources mode is deprecated

### ISSUE THREAD

**Issue by sebamena** [robolectric/robolectric#4890]
### Description
I upgrade my lib to 4.2.1 and my test are showing warnings "NOTICE: legacy resources mode is deprecated". I see the docs but i don't get the fix for this warnings.

### Link to a public git repo demonstrating the problem:

**Comment by 4mr0m3r0** [comment]
I manually upgraded Robolectric version from 3.8 to 4.2.1
I have the same problem: "[Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40"
And: "[Robolectric] [path/to/the/test/class]: sdk=28; resources=LEGACY"

Android Studio Version: 3.3.2
Gradle Version: 4.10.1
Android Plugin Version: 3.3.2
Robolectric Version: 4.2.1

**Comment by jongerrish** [comment]
You need to add android.enableUnitTestBinaryResources=true to your gradle.properties unless you are using build tools 3.4 then there is no need.

http://robolectric.org/getting-started/

**Comment by alixwar** [comment]
> You need to add android.enableUnitTestBinaryResources=true to your gradle.properties unless you are using build tools 3.4 then there is no need.

I still see this warning using AGP 3.5.2. 
Note: I have not set `android.enableUnitTestBinaryResources=true`
