### ISSUE TITLE
Very slow startup time with codelab

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#4952]
12 seconds on an i7 carbon, 6 seconds on my eng laptop, 2 seconds on my eng work station.

**Comment by dmeng** [comment]
Running TasksFragmentTest on eng workstation, currently getting 6s on the first test it runs.

Looks like RoboMonitoringInstrumentation#startActivitySyncInternal is pretty consistently taking about half of that time. The parts of it that appear to be slower on the first test are
- About 0.5s getting to and past Robolectric.buildActivity
- About 1.2s just on TasksActivity.onCreate
- Another 0.6s on TasksActivity.onStart
- Another 0.3s on TasksActivity.makeVisible

I haven't yet pegged exactly what parts of each of those are so slow the first time around, but I'm also probably going to try this again on a weaker machine to make sure that I'm not underestimating some other source of slowness

**Comment by utzcoz** [comment]
Hi @dmeng @hoisie is this issue still need to be investigated? It might be similar to https://github.com/robolectric/robolectric/issues/7895.

**Comment by hoisie** [comment]
This seems to have been more of an issue with the Google infrastructure.
