### ISSUE TITLE
unknown tokenizer: unicode61

### ISSUE THREAD

**Issue by slott** [robolectric/robolectric#5038]
### Description
A table update during the onUpgrade triggers the following exception

com.almworks.sqlite4java.SQLiteException: [1] DB[3] prepare() UPDATE review SET LOCAL_USER_VINTAGE_ID = (SELECT local_id FROM user_vintage WHERE user_vintage.ID = review.user_vintage_id) [unknown tokenizer: unicode61]

### Steps to Reproduce
For me this happens when calling a raw sql update like this:

db.execSQL("UPDATE review SET " + ReviewDao.Properties.LocalUserVintageId.columnName + " = (SELECT local_id FROM user_vintage WHERE user_vintage.ID = review.user_vintage_id)")

### Robolectric & Android Version
Running version 4.2.1 and latest android SDK

### Link to a public git repo demonstrating the problem:
It's a private company project - but its easy to setup and see fail.

**Comment by hoisie** [comment]
My guess is that a custom sqlite library is linked. Unless there are more details (sample code, logs, etc..), this will not be possible to debug.
