### ISSUE TITLE
ShadowActivity.requestPermissions's behavior should be closer to the real implementation

### ISSUE THREAD

**Issue by severinh** [robolectric/robolectric#5051]
### Behavior of `Activity.requestPermissions` (the real implementation)
The real implementation `Activity.requestPermissions` calls `Activity.onRequestPermissionsResult` once the user grants or denies the requested permissions. There is also a special case where it immediately calls that callback with empty arrays if there is already an ongoing permission request, to indicate cancellation.

### Current behavior `ShadowActivity.requestPermissions`
It does nothing expect store the requested permission into a field.
Unit tests have to directly call `onRequestPermissionsResult` on the activity.
`ShadowContextWrapper.(grant|deny)Permissions()` has no effect on `requestPermissions` calls.

### Expected behavior of `ShadowActivity.requestPermissions`

IMO, it should be possible to trigger the `onRequestPermissionsResult` with a call to `grantPermissions` or `denyPermissions`:

```
activityUnderTest.requestPermissions(new String[] { permission.RECORD_AUDIO }, REQUEST_CODE);
shadowOf(RuntimeEnvironment.application).denyPermissions(permission.RECORD_AUDIO);
// Should trigger the activityUnderTest's `onRequestPermissionsResult` callback with appropriate arguments.
```

### Robolectric & Android Version
Robolectric 4.0

**Comment by utzcoz** [comment]
Hi @severinh , looks like https://github.com/robolectric/robolectric/pull/5707 has fixed this problem. And it has been integrated into Robolectric 4.4 and later version. You can check new `Activity#requestPermissions` behavior with those versions, and feel free to reopen it when it doesn't meet your requirement.
