### ISSUE TITLE
Please support semicolon-separated content providers

### ISSUE THREAD

**Issue by AstralStorm** [robolectric/robolectric#5079]
I've hit the todo in this case:
https://github.com/robolectric/robolectric/blob/77a87c41b9ab7a357f1cf8d4d22913c308138a3a/shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java#L364

We're using semicolon separated providers in our Manifest and it's not supported even in current master. Should be relatively trivial to add.

**Comment by jongerrish** [comment]
@AstralStorm - would you mind sending a PR for this including a test? I'll make sure we get it merged asap for you.

**Comment by jongerrish** [comment]
Hi @AstaralStorm

**Comment by AstralStorm** [comment]
Could've given me a while, some people actually work using this thing. :) I'll cook a tiny example next weekend and reopen.
