### ISSUE TITLE
Dynamic module activity test issue

### ISSUE THREAD

**Issue by deividasstr** [robolectric/robolectric#5105]
### Description
2 modules - app (base module) and dynamic_feature (com.android.dynamic-feature).
dynamic_feature build.gradle contains implementation project(':app'), app knows nothing about dynamic_feature.

When robolectric tests are run on activities defined in dynamic_feature module (manifest as well), error is thrown. 
```

(java.lang.RuntimeException: Unable to resolve activity for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.dynamicrobolectrictest/com.example.dynamic_feature.DynamicActivity } -- see robolectric/robolectric#4736 for details)
```
### Steps to Reproduce

```
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.rule.ActivityTestRule
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ActivityTest {

@get:Rule
val actRule = ActivityTestRule(DynamicActivity::class.java)

@Before
fun before() {}

@Test
fun test() {}
}
```

this test lies in a dynamic feature module. DynamicActivity as well.
Test should pass, it fails with the mentioned exception.

### Robolectric & Android Version
Robolectric 4.3
Android - any?

### Link to a public git repo demonstrating the problem:
https://github.com/deividasstr/robolectric-dynamic-module run ActivityTest class in dynamic_feature module.

**Comment by jongerrish** [comment]
What manifest is your DynamicActivity defined in?

Can you can put a breakpoint in DefaultManifestFactory and then inspect the property for the manifest that AGP is passing to Robolectric?

I'm guessing that the manifest doesn't have that entry present for some reason, so either you are not declaring the activity in the right manifest, or for some reason with dynamic modules AGP is passing us an incorrect manifest.

**Comment by deividasstr** [comment]
> What manifest is your DynamicActivity defined in?
In the manifest of the dynamic module.

>  breakpoint in DefaultManifestFactory
resourcesDir = null

I have found out that simple unit tests fail with dynamic features, maybe due to `apply plugin: 'com.android.dynamic-feature'`. Issue here https://issuetracker.google.com/issues/123441249

**Comment by seviu** [comment]
I was able to solve this problem on one of my projects. I left some feedback about it on google's issue tracker with instructions how to run it.

**Comment by jaysondc** [comment]
@seviu Care to post your solution? I'm having the same issue running simple unit tests in Dynamic Feature Modules.

In this case I'm trying to run my `MainActivity` from my `app` module. My custom `SplitCompatApplication` runs which does some setup grabbing classes from my dynamic feature modules via reflection. In the app this works fine but during unit tests I get `ClassNotFoundException`s. I ran a breakpoint and asked SplitCompatManager for the currently installed modules and the result is 0.

**Comment by utzcoz** [comment]
Duplicate this issue to https://github.com/robolectric/robolectric/issues/5597,  because it has more discussion. Feel free to reopen it if you think this issue has different root cause.
