### ISSUE TITLE
Create API to remove sensor after it is added

### ISSUE THREAD

**Issue by pablobaxter** [robolectric/robolectric#5154]
### Description
As it is today, there is no way to remove a sensor from the ShadowSensorManager using the new `ShadowSensorManager.addSensor(Sensor sensor)` API. With the deprecated API  `ShadowSensorManager.addSensor(int type, Sensor sensor)`, it was possible to remove a sensor with the following:

```
SensorManager sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
ShadowSensorManager shadowSensorManager = shadowOf(sensorManager);
shadowSensorManager.addSensor(Sensor.TYPE_ACCELEROMETER, null);
```

Given that not all Android devices are created equal, a `removeSensor(Sensor sensor)` API would be helpful.

### Robolectric & Android Version 
Robolectric 4.3

**Comment by hoisie** [comment]
Sounds good to me, can you send a PR to add it, along with a test?

**Comment by utzcoz** [comment]
Because @pablobaxter doesn't response it after some months, so I send a PR to add API for this issue.
