### ISSUE TITLE
Slow robolectric tests with dependency to Stripe 9.3.5

### ISSUE THREAD

**Issue by romainpiel** [robolectric/robolectric#5156]
I have already reported this on the Stripe Github project: https://github.com/stripe/stripe-android/issues/1141

### Description
Robolectric tests are very slow when the latest version of the Stripe SDK (9.3.5) is included. Digging a bit more into the issue, I found that the Stripe SDK now includes the dependency `org.bouncycastle:bcprov-jdk15on:1.61`. As Robolectric 4.2.1 includes version 1.52 of that dependency, Gradle forces it to use version 1.61. It looks like that version slows down a lot the tests (a few minutes instead of a few seconds in my experience.

In order to fix that, I had to force to use version 1.52, which is a bit hacky.

### Steps to Reproduce
- include dependency `implementation 'com.stripe:stripe-android:9.3.5'` and robolectric 4.2.1
- create a simple robolectric test
- run the test

### Robolectric & Android Version
4.2.1, any

**Comment by RomainPiel** [comment]
I have tried to reproduce the issue on the latest version 4.3 but faced that other issue https://github.com/robolectric/robolectric/issues/4621#issuecomment-499080171

**Comment by utzcoz** [comment]
@romainpiel Could you try the latest Robolectric 4.9.2. Actually there are many performance improvements from 4.5 to 4.9.2.

**Comment by utzcoz** [comment]
Oh, stripe-android already uses [4.9](https://github.com/stripe/stripe-android/blob/cb3cd68ff3a8ae67d19f7be5fcaa5bd31dd3a69e/build.gradle#L101). Feel free to reopen this issue if you think there still exists performance problems that related to Robolectric. Thanks.
