### ISSUE TITLE
java.lang.IllegalStateException: Illegal connection pointer x, after migrating from Robolectric 3.0-rc2 to Robolectric 4.3

### ISSUE THREAD

**Issue by marijalukaroska1** [robolectric/robolectric#5171]
I migrated from Robolectric 3.0-rc2 to Robolectric 4.3.

After migration my tests started failing with the following error: java.lang.IllegalStateException: Illegal connection pointer 1.

In the tests that are failing I am not testing the SQLite database, in fact I make an instances to classes that are actually using the database.

I use Robolectric 4.3 and android sdk 28.

I read in the following link https://www.bountysource.com/issues/32208329-java-lang-runtimeexception-java-lang-illegalstateexception-illegal-connection-pointer-1-with-content-provider that the SQL database should be closed after each test in the @After method, but in some tests the exception still appears.

The exception only appears if I run all the tests at ones. If I rn them individually, they pass.

**Comment by hoisie** [comment]
Is this issue still happening? Can you provide a sample app or snippet of code that demonstrates the problem?
