### ISSUE TITLE
OutOfMemoryError after adding AutoService in 4.3

### ISSUE THREAD

**Issue by KenVanHoeylandt** [robolectric/robolectric#5187]
### Description
I upgraded to 4.3, and after some minor fixes here and there everything ran fine.
Then I replaced the deprecated `buildGlobalConfig()` method with an `@AutoService` and I got out of memory after running only a few hundred tests.

From the `RobolectricTestRunner` source code:

```
  /**
   * [...]
   * @return global {@link Config} object
   * @deprecated Provide a service implementation of {@link GlobalConfigProvider} instead. See
   *     [Migration Notes](http://robolectric.org/migrating/#migrating-to-40) for details. This
   *     method will be removed in Robolectric 4.3.
   * @since 3.1.3
   */
  @Deprecated
  protected Config buildGlobalConfig() {
    return new Config.Builder().build();
  }
```

I then implemented an `@AutoService` in my custom test runner:

```java
    @AutoService(GlobalConfigProvider.class)
    public class SomeConfigProvider implements GlobalConfigProvider {
        @Override
        public Config get() {  return ... ; }
    }
```

And I configured the annotation processor with `rc4` (and later also `rc6`). That's when tests start failing:

```bash
java.lang.OutOfMemoryError: Java heap space
```

And basically running tests were grinding to a halt with this.

### Steps to Reproduce

- Add `@AutoService` with annotation processor
- Run a couple of hundreds of tests (I was at test 200 out of 2000+)
- Observe how JVM goes out of memory

### Robolectric & Android Version

- Robolectric 4.3
- Android Target SDK 28
- Android Gradle Plugin 3.4.2

### Comments

- I shouldn't be required to run an annotation processor for this single sub-feature.
- There is [no documentation](https://github.com/robolectric/robolectric/issues/4770) for this feature.
- Robolectric using release candidates in its production builds.
- Robolectric states "This method will be removed in Robolectric 4.3." which implies that semantic versioning principles are not taken into account.

**Comment by KenVanHoeylandt** [comment]
Might or might not be related to https://github.com/robolectric/robolectric/issues/5131
I opened a new issue because I found a more specific cause.
Even without `@AutoService`, I still have over `3 GB` of RAM in use by Robolectric Java processes after a few hundred tests.

**Comment by utzcoz** [comment]
@KenVanHoeylandt Please try the latest Robolectric. And feel free to file a new issue if you found the latest Robolectric also has a OutOfMemoryError. Thanks.
