### ISSUE TITLE
Duplicate class found in modules modules maven-ant-tasks-2.1.3.jar (org.apache.maven:maven-ant-tasks:2.1.3) and maven-artifact-2.2.1.jar (org.apache.maven:maven-artifact:2.2.1)

### ISSUE THREAD

**Issue by efinder2** [robolectric/robolectric#5235]
### Description
I tried to add start testing my app with robolectric. But on the first build I got a duplicated class error (see [log.txt](https://github.com/robolectric/robolectric/files/3529572/log.txt))

[dependency_tree.txt](https://github.com/robolectric/robolectric/files/3529573/dependency_tree.txt)

### Steps to Reproduce
Create a new Project in Android studio, add robolectric 4.3 to the dependencies (or use the Code from the repo) and try to Start ExampleInstrumentation Test.

[build.gradle.txt](https://github.com/robolectric/robolectric/files/3529589/build.gradle.txt)

### Robolectric & Android Version
Tried to test on an Android 8.1 and use Robolectric 4.3

### Link to a public git repo demonstrating the problem:
https://github.com/efinder2/RobolectricSample

P.S. 
see this StackOverflow [post ](https://stackoverflow.com/questions/57594179/how-to-resolve-duplicated-gradle-dependency-issues)

**Comment by Prafulla-Nair** [comment]
I've the same issue

**Comment by fejd** [comment]
I suddenly ran into this issue in an existing app with working tests. No changes in the build files or tests, the tests started failing suddenly.
My only guess is that the artifact in the Gradle cache was synced and updated. I'm using Robolectric 4.2 though.

**Comment by kacso** [comment]
I'm experiencing same issue when running gradle assembleAndroidTest task (executed by jitpack CI), but when gradle build or gradle install (to install library locally) is performed, everything works fine.

Any info on how to resolve this?

**Comment by efinder2** [comment]
Finally solved it by removing the duplicated libraries manually: https://stackoverflow.com/a/57819278/4140943
Could this be added in the library? The library with the problem (org.apache.maven:maven-ant-tasks:2.1.3) is no longer maintained.

**Comment by Pozzoooo** [comment]
+1, facing the issue using Robolectric `4.0.2`

**Comment by ibcoleman** [comment]
Same issue on 4.3.1

**Comment by mochadwi** [comment]
you are a lifesaver @efinder2 excluding the dependency works for me for `4.3.1`. But I'm curious why you reopened this issue?

**Comment by hoisie** [comment]
maven-ant-tasks is no longer a dependency for Robolectric 4.4
