### ISSUE TITLE
ContentProvider's onCreate is invoked twice

### ISSUE THREAD

**Issue by DevDengChao** [robolectric/robolectric#5242]
### Description
I'm testing my ContentProvider then I noticed the log in `onCreate` appares twice.

### Steps to Reproduce
+ Create a simple ContentProvider named MyContentProvider and register it into Manifest.xml.
+ Add a simple log in onCreate.
+ Create a test case that is calling MyContentProvider.

### Robolectric & Android Version
Robolectric 4.3, Android version unspecified, Android Studio 3.6 Canary 8.

### Link to a public git repo demonstrating the problem:
None.

### What causes the problem
https://github.com/robolectric/robolectric/blob/62be3a162707c762232335de3f28204c8d8939f6/shadows/framework/src/main/java/org/robolectric/shadows/ShadowContentResolver.java#L860-L864

Provider's `onCreate` is invoked after `attachInfo`, while `onCreate` is invoked inside `attachInfo`.

### Reference
http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/app/ActivityThread.java#6379

Provider's `onCreate` is not invoked after `attachInfo`.

**Comment by vidhithakrar** [comment]
Any update on this?

**Comment by hoisie** [comment]
This was fixed in #5393
