### ISSUE TITLE
`NativeInput.MAX_SAMPLES` is wrong

### ISSUE THREAD

**Issue by cushon** [robolectric/robolectric#5276]
https://github.com/robolectric/robolectric/blob/1f787cf53414d2892018eb9177392155cde91e0a/shadows/framework/src/main/java/org/robolectric/shadows/NativeInput.java#L52

I think this should probably be

```diff
-  private static final int MAX_SAMPLES = 2 ^ 16; /* UINT16_MAX */
+  private static final int MAX_SAMPLES = 1 << 16; /* UINT16_MAX */
```

In `2 ^ 16` the `^` is bitwise exclusive or, not a power operator, so that value is `18` and not the maximum value of a 16 bit unsigned int. Either the implementation or the comment is wrong.

See also http://errorprone.info/bugpattern/XorPower.

**Comment by dmeng** [comment]
Ooh yeah, looks like that got copied over incorrectly. Feel free to make a PR changing it to 0xffff
