### ISSUE TITLE
Can I shadow System.loadLibrary() ?    

### ISSUE THREAD

**Issue by Chaoyang0201** [robolectric/robolectric#5286]
I am using a third-part library at my project, it's call System.loadLibary inside, I can't simply remove it, so my test will be interrupted by UnsatisfiedLinkError.

Is there any way to shadow System.loadLibrary() to let it do nothing?

**Comment by dmeng** [comment]
Shadowing general java classes/libraries is not supported; the shadow has to be covering something specific to Android internals.
