### ISSUE TITLE
Cannot set system properties

### ISSUE THREAD

**Issue by jameswald** [robolectric/robolectric#5305]
### Description

The system properties section in http://robolectric.org/configuring/ explains how to set system properties with the Android Gradle Plugin DSL:

```
android {
  testOptions {
    unitTests.all {
      systemProperty 'robolectric.dependency.repo.url', 'https://local-mirror/repo'
      systemProperty 'robolectric.dependency.repo.id', 'local'
    }
  }
}
```

Unfortunately these properties are not set when running unit tests. I also tried `robolectric.enabledSdks` but it is not present in the `Properties` list that gets passed to `DefaultSdkPicker`.

### Steps to Reproduce

1) Add system property configuration as described above.
2) Run unit tests.
3) Either debug with breakpoints to see missing properties or observe default behavior despite the system property configuration.

### Robolectric & Android Version

Robolectric 4.2, Android Gradle Plugin 3.4.1 and 3.5.1.

**Comment by jameswald** [comment]
It looks like Robolectric also encountered this problem and created a workaround:
https://github.com/robolectric/robolectric/blob/master/buildSrc/src/main/groovy/org/robolectric/gradle/AndroidProjectConfigPlugin.groovy#L27-L30

**Comment by Plastix** [comment]
I am also having this problem. Using Robolectric `4.3.1`, Gradle `4.10.2` and AGP `3.3.1`.

@jameswald Is there anything I need to do to use Robolectric's `AndroidProjectConfigPlugin`?

**Comment by jameswald** [comment]
I ended up using `robolectric.properties` to set `sdk=28`. I couldn't get system properties to work even with that forwarding logic from the Robolectric plugin.

**Comment by Plastix** [comment]
@jameswald Good to know. I tried using a global `robolectric.properties` (in root directory) with `sdk=27` but that didn't work for me. My project has many Gradle modules and I want to avoid needing to have multiple `robolectric.properties` one for each module.

**Comment by jameswald** [comment]
If you create a core module that all the others depend on then you can create `{core}/src/main/resources/robolectric.properties` and that file will automatically apply to all the other modules. I'm not sure but you may also need this in each module:

```
android {
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}
```

I have a centralized Gradle property that has that and it gets applied to every module.

**Comment by Plastix** [comment]
Ah that is a neat trick but unfortunately our core module isn't an Android one so we can't inherit `robolectric.properties`. I already have a custom Gradle plugin which sets `includeAndroidResources = true` in every module.

I am setting Robolectric's SDK in our custom Gradle Plugin (via system properties) but it looks like it ignores system properties only when running inside of Android Studio. That is:

- `./gradlew :myModule:testDevDebug` works fine.
- Inside Android Studio: `Right Click -> Run test` does not obey the Robolectric settings.

**Comment by jameswald** [comment]
I think it will work because `src/main/resources` is from the Java Gradle plugin, not the Android Gradle plugin.

https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout

**Comment by Plastix** [comment]
This is a good point. I'll see if I can get this to work for me.

**Comment by Plastix** [comment]
Running into this problem again... Android studio does not seem to want to inherit `robolectric.properties` but running from the commandline is fine.

**Comment by hoisie** [comment]
Interestingly system properties work when running tests using gradle in the terminal, but only does not work when running tests in Android Studio. I filed a bug here: https://b.corp.google.com/issues/163718756.

**Comment by snepalnetflix** [comment]
I'm running into the same issue. I have a robolectric.properties file in a common library. It gets picked up correctly when run from the command line but not through Android Studio.

**Comment by Plastix** [comment]
@snepalnetflix I solved this problem using Robolectric's new global config API (See: https://github.com/robolectric/robolectric/issues/4770). Unfortunately this requires Autoservice as a dependency but at least the runtime is consistent.

**Comment by adamszewe** [comment]
Solved by applying this in the `<project root>/build.gradle.kts`:
```
allprojects {
    tasks.withType<Test> {
        systemProperty("robolectric.dependency.repo.id", "CustomMavenRepo-Robolectric")
        systemProperty("robolectric.dependency.repo.url", "http://localhost:8081/repository/MavenGroup/")
        systemProperty("javax.net.ssl.trustStoreType", "JKS")  // required for Robolectric 4.3.1 and JDK11
        systemProperty("robolectric.logging", "stdout")
    }
}
```

Tested locally with a Nexus Maven Proxy repository pointing to: `https://repo1.maven.org/maven2` (which is hard-coded in the Robolectic library).
Works both from command line and from Android Studio:
![Screenshot from 2021-02-07 21-46-57](https://user-images.githubusercontent.com/6529875/107159112-5f4bae80-698e-11eb-9e7c-684fc1338190.png)
With:
* JDK11
* AS 4.1.2
* Robolectric 4.3.1

You can make sure that it works by removing the cached dependencies under `~/.m2/repository/org/robolectric` and running again the tests (if you provide an invalid repository URL, it will fail).


If your repository requires authorization (example: Artifactory) :
```
allprojects {
    tasks.withType<Test> {
        systemProperty("robolectric.dependency.repo.id", "CustomMavenRepo-Robolectric")
        systemProperty("robolectric.dependency.repo.url", "http://localhost:8081/repository/MavenGroup/")
        systemProperty("javax.net.ssl.trustStoreType", "JKS")  // required for Robolectric 4.3.1 and JDK11
        systemProperty("robolectric.logging", "stdout")
        val artifactory_user: String? = properties["artifactory_user"] as? String
        val artifactory_key: String? = properties["artifactory_key"] as? String
        if (!artifactory_user.isNullOrBlank() && !artifactory_key.isNullOrBlank()) {
            systemProperty("robolectric.dependency.repo.username", artifactory_user)
            systemProperty("robolectric.dependency.repo.password", artifactory_key)
        }
    }
}
```

**Comment by jsharp80** [comment]
I was never able to get the system properties to work in Android Studio.  Like others, they worked from the command line, but not the IDE.  Limiting the test execution to the command line was not an option for me, so I was able to get it work in Android Studio by doing the following - 

- Create a file named `robolectric-deps.properties` and place it in `src/test/resources`

- Add an entry similar to the following.  The entry will vary based on which runtime you need and where you've stored the JAR. 
 `org.robolectric\:android-all\:9-robolectric-4913185-2=<path-to-Robolectric-runtime-jar>`

To assist you with finding the correct name for the property, set breakpoints in `LegacyDependencyResolver` (line 73 in Robolectric 4.5.1) and in `PropertiesDependencyResolver`.  You should be able to see how Robolectric uses this properties file to resolve the offline runtime JAR dependency.  

This solution is not ideal and I HATE having the dependency checked into my VCS, but it's a stop-gap that can be used until the AS bug with passing system properties into tests is resolved.

**Comment by hoisie** [comment]
I'll try to follow up about this issue internally.

**Comment by hoisie** [comment]
I am not too familiar with the Android Studio code base, but it appears to be open source: https://android.googlesource.com/platform/tools/base/+/studio-master-dev/source.md. I'm running a repo sync right now.

**Comment by jsharp80** [comment]
> I am not too familiar with the Android Studio code base, but it's open source: https://android.googlesource.com/platform/tools/base/+/studio-master-dev/source.md. I'm running a repo sync right now.

Thanks for taking a look!

**Comment by hoisie** [comment]
Apparently this has been fixed in the Android Studio 'arctic fox canary' version here that can be downloaded here: https://developer.android.com/studio/preview. I am trying this out now to verify. 

Also https://b.corp.google.com/issues/163718756 was marked as fixed. Apparently Arctic Fox defers to gradle to a larger extent to run tests.

**Comment by hoisie** [comment]
Confirms that this works on 'Android Studio 'arctic fox canary' available from https://developer.android.com/studio/preview. This is definitely not ideal to require a canary, so for teams that cannot use the canary version, I'd recommend the workaround in https://github.com/robolectric/robolectric/issues/5305#issuecomment-774760930.
