### ISSUE TITLE
SQLiteDatabase insertWithOnConflict() with CONFLICT_IGNORE always returns 0 on conflict instead of return -1

### ISSUE THREAD

**Issue by yingding** [robolectric/robolectric#5320]
### Description
While testing the SQLiteDatabase.insertWithOnConflict(TABLE.NAME, null, values, SQLiteDatabase.CONFLICT_IGNORE); this method always returns 0 instead of returns -1.
please refer to the android doc: [insertWithOnConflict()]( https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#insertWithOnConflict(java.lang.String,%20java.lang.String,%20android.content.ContentValues,%20int))

The same test run as instrumented test on an Android Q Emulator, the inserWithOnConfilict() returns as desired -1 for CONFLICT_IGNORE on conflict.

It is considerable that the robolectric doesn't simulate the proper behaviour.

### Steps to Reproduce
* call insertWithOnConflict with CONFICT_IGNORE two times for the same insert values.
* The first time returns value 0, because the inserted row id is 0;
* The second time returns also value 0, since the conflict is ignored and no exception is raised. But it shall actual return -1 to indicate conflict or error happens for further handling. Otherwise it is not clear, if the row is inserted successfully or a conflict has been raised. 

### Robolectric & Android Version
Robolectric: 4.3.1
Android: 28

**Comment by warting** [comment]
This is still a thing
public git repo demonstrating the problem: https://github.com/warting/roboelectric_insert_with_conflict_ignore_bug

**Comment by erikeelde** [comment]
Also an issue when using room - My response however was a static "4" - I'm guessing because CONFICT_IGNORE is mapped to "4" in sqlite. Tested sdk 22 and 27 with same result.

**Comment by hoisie** [comment]
The -1 comes from JNI code here:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/jni/android_database_SQLiteConnection.cpp;l=549-557;drc=master?q=frameworks%2Fbase%2Fcore%2Fjni%2Fandroid_database_SQLiteConnection.cpp&ss=android

The logic is:
```cpp
    int err = executeNonQuery(env, connection, statement);
    return err == SQLITE_DONE && sqlite3_changes(connection->db) > 0
            ? sqlite3_last_insert_rowid(connection->db) : -1;
```

Perhaps we should modify https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowSQLiteConnection.java#L275-L278 to add a check for `SQLiteConnection.getLastInsertId()`?

Would someone be interested in send a PR to do this?

**Comment by hoisie** [comment]
Looks like this function would need to be modified:

https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowSQLiteConnection.java#L739-L752

**Comment by warting** [comment]
On it: https://github.com/robolectric/robolectric/pull/5985

**Comment by hoisie** [comment]
@erikeelde this fix should be available in the latest 4.5-SNAPSHOT. Can you give that a try? I'm not sure if this is the same issue as Room or if it is different.

**Comment by erikeelde** [comment]
@hoisie Huge thanks for the investigation effort. I'll try that snapshot out and give a shout back here. 👍

**Comment by erikeelde** [comment]
added a pr to the previous repo demonstrating the fix working: https://github.com/warting/robolectric_insertWithOnConflict_ignore_bug/pulls
Curiously sdk 26, 27 and 28 ran out of memory on the 4.4 PR (also the 4.5 PR before I removed those sdks from the tests.)

**Comment by hoisie** [comment]
The reason you are seeing OOM is because `@Config(minSdk = 16, maxSdk =
28)`. I think at this point muti-SDK with all SDKs don't work well due to
OOMs.

**Comment by hoisie** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/5985
