### ISSUE TITLE
android.enableSeparateAnnotationProcessing conflicts with GlobalConfigProvider

### ISSUE THREAD

**Issue by maxim-pandra** [robolectric/robolectric#5354]
### Description
I am trying to use new GlobalConfigProvider along with android.enableSeparateAnnotationProcessing = true.

When I enable flag, global configuration stops working. 

Fortunately it still works with deprecated RobolectricTestRunner extending method via overriding buildGlobalConfig() method. But this method will be removed soon.

### Steps to Reproduce

```
@AutoService(GlobalConfigProvider.class)
public class CustomRobolectricConfigProvider implements GlobalConfigProvider {

    private static final String RU_LOCALE = "ru";

    @Override
    public Config get() {
        return new Config.Builder()
                .setQualifiers(RU_LOCALE)
                .build();
    }
}
```

 ```
@RunWith(RobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.O_MR1)
public class WelcomeActivityTest {

 @Test
  public void clickingLogin_shouldStartLoginActivity() {
    MainActivity activity = Robolectric.setupActivity(MainActivity.class);

    String actual = activity.getResources().getString(R.string.action_settings);

    assertThat(actual, CoreMatchers.equalTo("Настройки"));
  }
}
```

`android.enableSeparateAnnotationProcessing = true
`

 ```
    testImplementation "org.robolectric:robolectric:4.3.1"
    testImplementation 'org.hamcrest:hamcrest:2.2'


    testAnnotationProcessor  group: 'com.google.auto.service', name: 'auto-service', version: '1.0-rc4'
    testCompileOnly  group: 'com.google.auto.service', name: 'auto-service', version: '1.0-rc4'
```
### Robolectric & Android Version

Robolectric 4.3.1

### Link to a public git repo demonstrating the problem:

https://github.com/maxim-pandra/RobolectricSeparateAnnotationProcessor

**Comment by ZacSweers** [comment]
Opened a PR to fix this here #5432. I'm not sure if Google is actively maintaining the external version of Robolectric anymore though.
