### ISSUE TITLE
Make website HTTPS-only

### ISSUE THREAD

**Issue by LouisCAD** [robolectric/robolectric#5358]

**Comment by utzcoz** [comment]
Maybe we can enforce HTTPS for robolectric.org firstly by following https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https. /cc @hoisie .

**Comment by hoisie** [comment]
That does not seem possible at the moment :(

We need to update the DNS settings, but I believe the domain is owned by Pivotal, which is now part of VMWare.

![image](https://user-images.githubusercontent.com/125547/153068628-f97e9bbd-661b-4752-b30d-aa2321906215.png)

I can try reaching out to someone there.

**Comment by utzcoz** [comment]
Latest Chrome prevents me to view robolectric.org with https protocol on Android phone. I can visit it with http protocol. Everything works correctly on Linux's Chrome and Firefox.

**Comment by LouisCAD** [comment]
Can you simply ask folks at Pivotal/VMWare to hand back the domain?

**Comment by utzcoz** [comment]
@LouisCAD You can check @hoisie comment at https://github.com/robolectric/robolectric/issues/7676#issuecomment-1274805813. Looks like Robolectric can use https without any warnings now.

**Comment by utzcoz** [comment]
@LouisCAD I have checked settings, and `Enforce HTTPS` is opened. Feel free to reopen this issue if you have any questions. Thanks.
