### ISSUE TITLE
Java version strings with two digits and no dots or dashes unsupported

### ISSUE THREAD

**Issue by niqueco** [robolectric/robolectric#5382]
Robolectric fails if the JVM reports something like 11 as a version.

The issue is that `Util.getJavaVersion()` will return 1 instead of 11, and then the "greater than X" check will obviously fail.

I've created a PR with a fix for this issue here: #5381

**Comment by niqueco** [comment]
For reference (and prople searching) the error you get is:

```
java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9 (have Java 1)
```

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/5381.
