### ISSUE TITLE
Tests are failing when executed in parallel on Windows

### ISSUE THREAD

**Issue by arazabishov** [robolectric/robolectric#5397]
### Description
When running parallel builds on Windows (CI machine in this case), the roboelectric tests fail sometimes. I assume that this is a some sort of race condition, as parallel builds use the same Temp folder. 

```
GuardTest > testParameterIsNotNull FAILED
    java.lang.ExceptionInInitializerError

        Caused by:
        java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Users\Administrator\AppData\Local\Temp\robolectric-no-test-yet7636895440768246211: The file or directory is corrupted and unreadable.

            Caused by:
            java.nio.file.FileSystemException: C:\Users\Administrator\AppData\Local\Temp\robolectric-no-test-yet7636895440768246211: The file or directory is corrupted and unreadable.
```
### Steps to Reproduce
Run roboelectric tests in parallel until you hit the problem. 

### Robolectric & Android Version
roboelectric=4.3.1, android=28

Is there any way to mitigate this issue? For example, to tell roboelectric to use another folder for temporary files on windows?

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and feel free to reopen this issue if it still exists.
