### ISSUE TITLE
org.apache.maven:maven-ant-tasks is retired and unmaintained

### ISSUE THREAD

**Issue by bandyguy** [robolectric/robolectric#5422]
### Description
The dependency of the "plugins" module "org.apache.maven:maven-ant-tasks" is retired and unmaintained: https://maven.apache.org/ant-tasks/index.html . This has many transitive dependencies that have severe bugs. I haven't dug deep enough yet to figure out why this library is needed, but it seems like something that should be removed if possible .

### Robolectric & Android Version
Robolectric 4.3.1

**Comment by mochadwi** [comment]
Agreed, there's a lot of conflicted dependency as well when using roboelectric 4.3.1, here's the issue #5235

**Comment by hoisie** [comment]
This has been fixed in 4.4 (no more dependency on maven-ant-tasks).
