### ISSUE TITLE
Tests hang intermittently when ran from Gradle

### ISSUE THREAD

**Issue by roudyirany** [robolectric/robolectric#5433]
### Description
When running unit tests using Gradle commands, Robolectric unit tests will intermittently hang and then never complete. This makes our CI setup timeout after a while and fail. Running the tests another time will usually make them proceed normally.

### Steps to Reproduce
Run `./gradlew test` in terminal

### Robolectric & Android Version

Component | Version
-- | --
Robolectric | 4.3.1
Gradle wrapper | gradle-6.1-rc-1-all
Android build plugin | 4.0.0-alpha09

Android Studio:

Android Studio 4.0 Canary 9
Build #AI-193.5233.102.40.6137316, built on January 15, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: 

### Link to a public git repo demonstrating the problem:
N/A

**Comment by hoisie** [comment]
I'm not seeing anything actionable here (e.g. no debug logs or anything). Closing this for now.
