### ISSUE TITLE
Android R asset manager changed the signature of nativeGetAssignedPackageIdentifiers 

### ISSUE THREAD

**Issue by PierreBdR-google** [robolectric/robolectric#5487]
### Description

Android R changed nativeGetAssignedPackageIdentifiers to be now:

    private static native @NonNull SparseArray<String> nativeGetAssignedPackageIdentifiers(
            long ptr, boolean includeOverlays, boolean includeLoaders);

The main issue is the interpretation of the two new booleans `includeOverlays` and `includeLoaders`. `LoadedPackage`, in [`frameworks/base/libs/androidfw/include/androidfw/LoadedArsc.h`](https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/include/androidfw/LoadedArsc.h) now has flags, which should be added and, I guess, used in the right places.

Without this, the method [`AssetManager.getLastResourceResolution`](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/content/res/AssetManager.java#778) returns null, crashing tests that load resources via this path (which is a lot of our tests).

### Robolectric & Android Version

Android R, all robolectric versions.

**Comment by hoisie** [comment]
This has been implemented in [ShadowArscAssetManager10.java](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowArscAssetManager10.java#L640-L644)
