### ISSUE TITLE
java.lang.NullPointerException: could not find build.prop

### ISSUE THREAD

**Issue by hbzhzw** [robolectric/robolectric#5492]
### Description
 

  [Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.

   java.lang.ExceptionInInitializerError

        Caused by:
        java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

            Caused by:
            java.lang.reflect.InvocationTargetException

                Caused by:
                java.lang.NullPointerException: could not find build.prop

### Robolectric & Android Version

> robolectric_version = "4.3.1"
> {
>          robolectric_android  : 'org.robolectric:android-all:9-robolectric-4913185-2',
>              robolectric          : "org.robolectric:robolectric:${robolectric_version}",
>              robolectric_client   : "org.robolectric:shadows-httpclient:${robolectric_version}",
>              robolectric_play     : "org.robolectric:shadows-playservices:${robolectric_version}",
> 	        robolectric_support  : "org.robolectric:shadows-supportv4:${robolectric_version}",
> }
>

**Comment by hoisie** [comment]
See https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues
