### ISSUE TITLE
Fragment in  packge androidx.fragment.app.Fragment ,how to test

### ISSUE THREAD

**Issue by iYoullloveGitHub** [robolectric/robolectric#5509]
code:
    @Test
    public void onCreateFragment() {
        FragmentController<MusicShowFragment2> tFragmentController = Robolectric.buildFragment(MusicShowFragment2.class);
}
 if MusicShowFragment2 extends Fragment  is in package   android.app, that's ok,
 but now I use  'androidx.appcompat:appcompat:1.1.0',Fragment   is in androidx.fragment.app, 
FragmentController only support android.app.Fragment, so how to resolve it?

**Comment by LitterSun** [comment]
This link may help you
https://developer.android.com/training/basics/fragments/testing
If you solve the problem, please close this issue, thank you.

**Comment by MGaetan89** [comment]
As said above, `FragmentScenario` is the new recommend way of testing `Fragment`s, so I'm closing this issue.
