### ISSUE TITLE
Can't find robolectric-samples.

### ISSUE THREAD

**Issue by Enzo-Fight** [robolectric/robolectric#5511]
### Description
I can't find the subdirectory robolectric-samples.
Could you please tell me where is it?
The entire url: https://github.com/robolectric/robolectric-samples

**Comment by hoisie** [comment]
I believe that project was removed in https://github.com/robolectric/robolectric.github.io/commit/e16d68bafd4d8d20c9dd94b59c1ed205897f91d1. I would recommend doing a Github Code Search for Robolectric samples.
