### ISSUE TITLE
FragmentController vs FragmentScenario

### ISSUE THREAD

**Issue by emmano** [robolectric/robolectric#5526]
### Description
`FragmentController` allowed us to drive the lifecycle of the `Fragment` to a desired state. It seems that `FragmentScenario` always takes the `Fragment` under test to its resumed state. One would assume that calling `moveToState(CREATED)` would take the `Fragment` back to through `onCreate()`, but in reality, as per the [docs](https://developer.android.com/training/basics/fragments/testing#drive-fragment-new-state), `moveToState()` simulates an external app interacting with the `Fragment` under test. This means that `moveToState(CREATED)` moves the `Fragment` under test through `onPause()` and `onStop()` as it would happen when a new `Activity` is launched.

> To drive the fragment to a different lifecycle state, call moveToState(). This methods supports the following states as arguments: CREATED, STARTED, RESUMED, and DESTROYED. This action simulates a situation where the activity containing your fragment changes its state because it's interrupted by another app or a system action.

Would it be possible to somehow direct `FragmentScenario` to drive the `Fragment` to a desired state instead of always going through `onResume()`? How do we test that something happened inside `onCreate()` and not inside `onResume()` using `FragmentScenario`? Am I missing something here?

### Steps to Reproduce

1. `val scenario = launchFragmentInContainer<MyFragment>()`
2. `scenario.moveToState(CREATED)`

### Robolectric & Android Version
Robolectric = 4.3.1
Android = 28
androidx.fragment:fragment-testining version: 1.2.2

**Comment by emmano** [comment]
Currently I came up with this, but it feels hacky:

```kotlin
inline fun <reified F : Fragment, reified A : AppCompatActivity> launchInActivity(
        crossinline fragmentFactory: () -> F,
        state: Lifecycle.State = Lifecycle.State.RESUMED,
        layoutId: Int = android.R.id.content,
        isTestOnlyActivity: Boolean = false
    ) : ActivityScenario<A> {

        //Manually register test only Activity since manifest merging is broken for test resources https://github.com/robolectric/robolectric/issues/4725
        if(isTestOnlyActivity) {
            val appContext = ApplicationProvider.getApplicationContext<Application>()
            val activityInfo = ActivityInfo().apply {
                name = A::class.java.name
                packageName = appContext.packageName
            }
            shadowOf(appContext.packageManager).addOrUpdateActivity(activityInfo)
        }

        val activityScenario = ActivityScenario.launch(A::class.java)

        activityScenario.onActivity {
            val fragment = fragmentFactory()
            it.supportFragmentManager
                .beginTransaction()
                .replace(layoutId, fragment, F::class.java.name)
                .setMaxLifecycle(fragment, state)
                .commitNow()
        }

        return activityScenario
    }
```

**Comment by MGaetan89** [comment]
It seems that the newer versions of `FragmentScenario` behave as you expected:
> This method simulates a situation where the fragment or activity containing your fragment changes its state for any reason.

You can also pass an `initialState` to your `launchFragmentInContainer` if needed.

**Comment by MGaetan89** [comment]
I'm closing this, since `FragmentScenario` seems to be working as you want to.
Feel free to reopen if you think that it needs more discussion.
