### ISSUE TITLE
More documentation regarding usage of shadows

### ISSUE THREAD

**Issue by KartikShankhavaram** [robolectric/robolectric#5535]
### Description
There aren't enough resources on how to use Shadows in tests, or how they work. Some more documentation would really be helpful to understand and use them quicker.
### Steps to Reproduce
None
### Robolectric & Android Version
Robolectric 4.3
### Link to a public git repo demonstrating the problem:
None

**Comment by hoisie** [comment]
See http://robolectric.org/extending/ for some pretty good docs about shadows. I'd definitely encourage you to make PRs to https://github.com/robolectric/robolectric.github.io if you want to improve the docs.
