### ISSUE TITLE
com.almworks.sqlite4java.SQLiteException: [no such function: INSTR]

### ISSUE THREAD

**Issue by vidhithakrar** [robolectric/robolectric#5544]
Robolectric is not able to execute a sqlite query which contains 'INSTR' function. 

After digging a bit, it seems `sqlite4java version:1.0.392` has upgraded support for `SQLite version:3.8.7` which has 'INSTR' function. Refer [this](https://bitbucket.org/almworks/sqlite4java/wiki/ChangeLog).

Robolectric version: 4.3
Android version: 28

**Comment by hoisie** [comment]
This is fixed in Robolectric -master. See https://github.com/robolectric/robolectric/pull/5216.
