### ISSUE TITLE
ShadowRemoteCallbackList getRegisteredCallbackCount is always zero

### ISSUE THREAD

**Issue by qiurudong** [robolectric/robolectric#5563]
### 
        RemoteCallbackList<IClientHandler> handlers = new RemoteCallbackList<>();
        handlers.register(clientHandler);
        handlers.getRegisteredCallbackCount();

**Comment by utzcoz** [comment]
@qiurudong , It has been fixed by [commit  Add getRegisteredCallbackCount() in ShadowRemoteCallbackList ](https://github.com/robolectric/robolectric/commit/7c6ca1541e8d19b05639d0583acde02718600c67), and the tag `robolectric-4.5-alpha-1` contains this commit. Maybe you can try this version.

**Comment by utzcoz** [comment]
@hoisie this issue also can be closed.
