### ISSUE TITLE
 com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare()  [no such function: char]

### ISSUE THREAD

**Issue by orchingly** [robolectric/robolectric#5596]
#### As title shown, I get error when create table with sql satements contains char(3)
`Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() INSERT INTO table  [no such function: char]`

#### The sql was dumpd  by sqlite3 
`SQLite version 3.28.0 2019-04-16 19:49:53`

**Comment by hoisie** [comment]
Can you provide a sample app or snippet of code that demonstrates the problem?

**Comment by hoisie** [comment]
Closing as this is not actionable. I'll re-open if there is a sample app orr code snippet.

**Comment by hoisie** [comment]
We also updated the version of sqlite in Robolectric -master 1.0.392, so it's possible this works now in -master. See https://github.com/robolectric/robolectric/pull/5216
