### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a ‪276824056‬ byte allocation with ‪25165824‬ free bytes and 117MB until OOM, max allowed footprint ‪170196328‬, growth limit ‪268435456

### ISSUE THREAD

**Issue by znhooom** [robolectric/robolectric#5627]
hi, I have this log

ANDROID_VERSION=9
BRAND=samsung
PHONE_MODEL=SM-A750F
CUSTOM_DATA=
STACK_TRACE=java.lang.OutOfMemoryError: Failed to allocate a ‪276824056‬ byte allocation with ‪25165824‬ free bytes and 117MB until OOM, max allowed footprint ‪170196328‬, growth limit ‪268435456‬
at dalvik.system.VMRuntime.newUnpaddedArray(Native Method)
at com.android.internal.util.ArrayUtils.newUnpaddedCharArray(ArrayUtils.java:51)
at android.text.SpannableStringBuilder.resizeFor(SpannableStringBuilder.java:145)
at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:378)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:548)
at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:269)

my code is

public static CharSequence c(android.view.ViewGroup r6, TextEmojiLabel textEmojiLabel, java.lang.Object r8, StringBuilder sb) {
        if (!getBoolTrue(textEmojiLabel.getContext(), "show_mod_groups_check")) {
            return sb.toString();
        }
        if (f(r6, r8, z)) {
            SpannableStringBuilder spannableStringBuilder = new SpannableStringBuilder();
            SpannableString spannableString = new SpannableString(getString(textEmojiLabel.getContext(), group_mod()));
            if (getBool(textEmojiLabel.getContext(), "show_mod_in_groups_color_picker")) {
                spannableString.setSpan(new ForegroundColorSpan(getIntfromKey(textEmojiLabel.getContext(), "show_mod_in_groups_color_picker")), 0, spannableString.length(), 0);
            } else if (getBool(textEmojiLabel.getContext(), "participant_name_color_picker")) {
                spannableString.setSpan(new ForegroundColorSpan(getIntfromKey(textEmojiLabel.getContext(), "participant_name_color_picker")), 0, spannableString.length(), 0);
            }
            if (getLanguage()) {
                String str = r8.A0N;
                if (!TextUtils.isEmpty(str)) {
                    spannableStringBuilder.append(str).append("~").append(" - ").append(spannableString);
                }
            } else {
                SpannableStringBuilder append = spannableStringBuilder.append("~");
                String str2 = r8.A0N;
                if (!TextUtils.isEmpty(str2)) {
                    append.append(str2).append(" - ").append(spannableString);
                }
            }
            return spannableStringBuilder;
        }
        return sb.toString();
    }

how to fix it

**Comment by SergejIsbrecht** [comment]
It loos like, you are trying to allocate way to much memory at once (263,999992371MiB). 

You could probably fiddle with some runtime settings (e.g. https://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio ), but in the end I would suggest changing your code, by reducing the array to allocate or chose a streaming solution.

**Comment by hoisie** [comment]
Closing this for now since it isn't really actionable. I'd suggest setting a breakpoint and verifying that you aren't trying to allocate a massive string for the text view. If the issue persists, and you can provide a more complete repro (e.g. sample app), I'll happily re-open and take a look.
