### ISSUE TITLE
Calling ContentResolver's insert() and query() methods throws MockitoException.

### ISSUE THREAD

**Issue by Isira-Seneviratne** [robolectric/robolectric#5632]
### Description
Attempting to execute `ContentResolver`'s `insert()` and `query()` methods during testing results in a `MockitoException` being thrown with the following messages:

```
Methods called on mock must exist in delegated instance.
When calling: public android.net.Uri android.content.ContentResolver.insert(android.net.Uri,android.content.ContentValues) on mock: contentResolver
no such method was found.
Check that the instance passed to delegatesTo() is of the correct type or contains compatible methods
(delegate instance had type: ShadowContentResolver)
```

```
Methods called on mock must exist in delegated instance.
When calling: public android.database.Cursor android.content.ContentResolver.query(android.net.Uri,java.lang.String[],java.lang.String,java.lang.String[],java.lang.String) on mock: contentResolver
no such method was found.
Check that the instance passed to delegatesTo() is of the correct type or contains compatible methods
(delegate instance had type: ShadowContentResolver)
```

### Steps to Reproduce
Run the unit tests included in the GitLab repo given below.

### Robolectric & Android Version
Robolectric version - 4.3.1
Android SDK version - 29

### Link to a public git repo demonstrating the problem:
https://gitlab.com/Isira-Seneviratne/fdroidclient/-/tree/Upgrade_from_Robolectric_3.8_to_4.3.1

**Comment by hoisie** [comment]
Does this issue still exist on 4.4? I'm seeing a 404 error on that git repo.

**Comment by hoisie** [comment]
Closing as this is not actionable at the moment (no code samples).
