### ISSUE TITLE
Support for Android R

### ISSUE THREAD

**Issue by codingclemo** [robolectric/robolectric#5644]
### Description
Hi, we are trying to run tests with a setup targeting Android R (Developer Preview 4) and ran into issues we cannot solve. 
When running the Robolectric tests I get the following exception:
`Caused by: android.content.pm.PackageParser$PackageParserException at PackageParser.java:1340`

The app runs on Java 8, but we also tried to update to Java 9 without success in fixing this problem. We also tried upgrading to Android Gradle Plugin 4, also without success.

Therefore we are curious when/if there will be a patch to enable Android R support. Maybe it is also something in the setup for Android R that we are missing. So we are grateful for any help in this regard 🙇 

### Steps to Reproduce
Run tests

### Robolectric & Android Version
Android R - Developer Preview 4 (May 2020)
```
'org.robolectric:robolectric:4.3.1'
'androidx.test.ext:junit:1.1.2-beta01'
```

```
minSdkVersion = 21
targetSdkVersion = 'R'
compileSdkVersion = 'android-R'
buildToolsVersion = '30.0.0 rc4'
```

**Comment by simonschiller** [comment]
Please note that we did NOT try to run Robolectric tests using API version 30 (Android R), we simply upgraded the Android version. Our Robolectric tests are still running on SDK 26.

Could it be that the letter instead of the number (`R` instead of `30`) is causing this issue?

**Comment by kingargyle** [comment]
You probably want to check the Robolectric 4.4 Snapshots, I think those are target for R.

**Comment by hoisie** [comment]
4.4 still targets Q actually. Once R is officially released (not just RCs) we'll try to make some updates to target R.

**Comment by matpag** [comment]
Android R has been released yesterday :)

**Comment by hoisie** [comment]
Android R support has been added and should be in Robolectric 4.5-SNAPSHOT. Check out https://github.com/robolectric/robolectric/pull/5939.

After a couple more changes, I will try to push out 4.5-alpha-1.

**Comment by hoisie** [comment]
[4.5-alpha-1](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.5-alpha-1) is now available which supports Android R (sdk 30). Please give it a shot and let me know if there are any issues!
