### ISSUE TITLE
RunSettingsRoboTests: java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to read manifest 

### ISSUE THREAD

**Issue by taotaodong527** [robolectric/robolectric#5647]
### Description
RunSettingsRoboTests test failed，the error info as below：
RunSettingsRoboTests: java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to read manifest 
### Steps to Reproduce
make RunSettingsRoboTests ROBOTEST_FILTER=WifiSettingsTest
### Robolectric & Android Version
Robolectric：4.0
Android Version：android-10.0.0_r33，sdk=29

**Comment by hoisie** [comment]
This seems like you are trying to run the version of Robolectric that is in the Android platform. Unfortunately the version of Robolectric in the Android platform is derived from Robolectric 4.0, which is very old, and has a lot of customizations. I wish I could offer more help but this is likely something you need to file with the Android platform.

**Comment by AntonLearnsCS** [comment]
@taotaodong527 was there a resolution to this issue?
Robolectric: 4.9.1
sdk=29

java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to read manifest
