### ISSUE TITLE
Custom @Config for each test method

### ISSUE THREAD

**Issue by fondesa** [robolectric/robolectric#5656]
### Description
In Robolectric 4.3.1, how can I provide a custom `@Config` for a specific test method? (e.g. the deprecated `RobolectricTestRunner.getConfig()`?

I found a way to workaround it but I'd like to know if there's a better way.

Currently I'm providing my own implementation of `HierarchicalConfigurationStrategy` and `ConfigConfigurer` using the service providers in `org.robolectric.pluginapi.config.ConfigurationStrategy` and `org.robolectric.pluginapi.config.Configurer` but I think it's a lot of work for it compared to the old `getConfig`.

### Robolectric & Android Version
Robolectric 4.3.1

**Comment by dkarv** [comment]
We're using `@Config` annotations on test methods which works great:
```
@Test
@Config(minSdk = Build.VERSION_CODES.N)
public void testAndroidNAndUp() {
```

It overwrites parts of the class `@Config` values.

**Comment by utzcoz** [comment]
`@Config` works fine for single test method, and @dkarv provides a great example at https://github.com/robolectric/robolectric/issues/5656#issuecomment-663478274. I will close this issue because it is not a problem. Feel free to reopen it if I misunderstand something.
