### ISSUE TITLE
Run unit test case for Android Settings, it promoted errors "PackageParserException"

### ISSUE THREAD

**Issue by xin10pan** [robolectric/robolectric#5662]
### **Description**
when I run unit test case for Android Settings, it promoted errors as shown below.

> RunSettingsRoboTests: at com.android.junitxml.JUnitXmlRunner.main(JUnitXmlRunner.java:98) RunSettingsRoboTests: Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from aosp_r33/out/target/product/generic_x86_64/obj/APPS/SettingsRoboTestStub_intermediates/package.apk

> …

> …

> RunSettingsRoboTests: Caused by: java.lang.UnsupportedOperationException: sorry, not supporting public abstract java.util.List android.content.pm.IPackageManager.getSplitPermissions() throws android.os.RemoteException yet!

> RunSettingsRoboTests: at org.robolectric.shadows.ShadowActivityThread$1.invoke(ShadowActivityThread.java:55)

> RunSettingsRoboTests: at com.sun.proxy.$Proxy15.getSplitPermissions(Unknown Source)

### Steps to Reproduce
Android Version：android-10.0.0_r33，sdk=29 
(https://source.android.google.cn/setup/start/build-numbers)
Roboletric: 4.0
Test procedure:
  source build/envsetup.sh
  lunch aosp_x86_64-eng
  croot
make RunSettingsRoboTests ROBOTEST_FILTER=SettingsActivityTest
After excute the steps above, the error appears as descripted in “Description”
### Robolectric & Android Version
Android Version：android-10.0.0_r33，sdk=29 
(https://source.android.google.cn/setup/start/build-numbers)
Roboletric: 4.0
### Link to a public git repo demonstrating the problem:
I download the released branch on https://source.android.google.cn/setup/start/build-numbers , the version is “QQ2A.200405.005  android-10.0.0_r33”

**Comment by hoisie** [comment]
Unfortunately I don't think any of the Robolectric maintainers here on Github really understand the Robolectric set up in the Android platform tree. The Android platform tree contains a fork of Robolectric 4.0 (quite ancient) with a lot of modifications. I wish we could help but you may have better luck filing an issue against the Android framework.
