### ISSUE TITLE
NullPointerException in ShadowPendingIntent.create() when using FLAG_UPDATE_CURRENT

### ISSUE THREAD

**Issue by pocmo** [robolectric/robolectric#5673]
### Description

In a unit test that sets a notification with a pending intent using `FLAG_UPDATE_CURRENT` I see the following `NullPointerException` coming out of `ShadowPendingIntent.create`:

```
Exception in thread "pool-10-thread-1 @coroutine#17" java.lang.NullPointerException
at org.robolectric.shadows.ShadowPendingIntent.create(ShadowPendingIntent.java:369)
at org.robolectric.shadows.ShadowPendingIntent.getActivity(ShadowPendingIntent.java:69)
at android.app.PendingIntent.getActivity(PendingIntent.java)
[..]
```

The same test passes without the crash when `FLAG_UPDATE_CURRENT` is not used.

Test case:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/test/java/mozilla/components/feature/media/service/MediaServiceDelegateTest.kt#L104-L141
Line in code where adding the flag breaks the test:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/main/java/mozilla/components/feature/media/notification/MediaNotification.kt#L116

Related Robolectric code:
https://github.com/robolectric/robolectric/blob/ede5c7e48bdc35f487d87fb0d54639496e3d2d79/shadows/framework/src/main/java/org/robolectric/shadows/ShadowPendingIntent.java#L394-L403

It seems like `shadowPendingIntent.getSavedIntent()` returns null and then accessing `intent.getExtras()` causes the crash.

### Robolectric & Android Version

We are currently on Robolectric 4.1 (with SDK 28), but I get the same result with newer versions up to 4.4-SNAPSHOT.

**Comment by hoisie** [comment]
Would you be able to send a PR to fix this issue?

**Comment by pocmo** [comment]
Sure. I'll try later today if this is still an issue and then will open a PR.

**Comment by utzcoz** [comment]
i @pocmo, thanks for reporting this problem. Feel free to reopen this issue if you find reproduce pattern or you think we should add NPE protection for `ShadowPendingIntent` for this issue.
