### ISSUE TITLE
JavadocJsonGenerator annotation processing through Gradle breaks on JDK 11

### ISSUE THREAD

**Issue by davidburstromspotify** [robolectric/robolectric#5688]
### Description

In Gradle executions on JDK 11, the current directory is not consistent between file operations. 
It can be `~/.gradle/daemon/x.y/` or the Gradle project root directory depending on context, see https://github.com/gradle/gradle/issues/5187

In https://github.com/robolectric/robolectric/blob/4764281a89e63e0cac4ccc685d2ec825e49209c7/processor/src/main/java/org/robolectric/annotation/processing/generator/JavadocJsonGenerator.java#L66
the call to `mkdirs` will create `build/docs/json` in `~/.gradle/daemon/x.y` but it will be opened in `<rootDir>/build/docs/json` which fails with a `FileNotFoundException`.

### Steps to Reproduce

Run any Robolectric annotation processing in a Gradle project with JDK 11

### Robolectric & Android Version

Robolectric 4.3.1

**Comment by hoisie** [comment]
Any recommendations for a fix?

**Comment by davidburstromspotify** [comment]
A side issue is that the JSON file is being output in the root of the project, which would break if two modules uses the same annotation processor as they would clobber each other.
To get a file reference in a safer way, the `Filer` API https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Filer.html should be used instead, but that doesn't allow for writing files in an arbitrary location.

My suggestion would be to change it to opt in (my preferred option) or out from docs generation, while you're figuring out how you want it to be written.

**Comment by hoisie** [comment]
Can you clarify what command you are trying to run (I'm guessing `./gradlew aggregatedocs`?)? Are you just not seeing the `build/docs/jsondocs` being output? I am running Java 11 and can't seem to repro the problem.

**Comment by davidburstromspotify** [comment]
[bug-robolectric-5688.zip](https://github.com/robolectric/robolectric/files/5188785/bug-robolectric-5688.zip)

I've created a repository that reproduces the problem. Please check the README.md for instructions. Some setup might be required, like the Android SDK.

**Comment by hoisie** [comment]
Ah, this is for a custom shadow package. I'd be okay with disabling building jsondocs by default. I am not sure if it is intended to be used outside of the Robolectric project anyway.

**Comment by davidburstromspotify** [comment]
Yeah, it could possibly be used outside, but I highly doubt it.

**Comment by hoisie** [comment]
Would you be interested in sending a PR to fix this? As far as I know it should be as simple as adding an additional param to RobolectricProcessor.java:

```java
  static final String JSON_DOCS_ENABLED = "org.robolectric.annotation.processing.jsonDocsEnabled";
```


and then adding
```java
options.compilerArgs.add("-Aorg.robolectric.annotation.processing.jsonDocsEnabled=true")
```

to ShadowsPlugin.groovy.

**Comment by davidburstromspotify** [comment]
Seems straightforward, but I'd prefer if a Robolectric maintainer did this change. I need to prioritize differently.
