### ISSUE TITLE
PackageManager$NameNotFoundException With WebView method

### ISSUE THREAD

**Issue by cj1ne** [robolectric/robolectric#5694]
### Description
In my project, I need to call **WebView.enableSlowWholeDocumentDraw** method above SDK 21 when application onCreate. 

When I run unit test with Robolectric, 
I got  **`[ PackageManager$NameNotFoundException: com.android.webview ]
at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
	at android.webkit.WebView.getFactory(WebView.java:2185)
	at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1640)
`**

If I call another WebView method (e.g. WebView.setWebContentsDebuggingEnabled), this error is not occurred. I've tried to find cause of problem, but I couldn't find the answer.

### Steps to Reproduce
Insert WebView.enableSlowWholeDocumentDraw() to Application Class onCreate
```
class MyApplication: Application() {
    override fun onCreate() {
        super.onCreate()
        WebView.enableSlowWholeDocumentDraw() 
    }
}
```

### Robolectric & Android Version
Robolectric 4.3.1

**Comment by hoisie** [comment]
Can you send a PR to fix this? You can add a shadow method for enableSlowWholeDocumentDraw ShadowWebView.java.

**Comment by utzcoz** [comment]
@hoisie The CL was merged, maybe this issue can be closed.

**Comment by hoisie** [comment]
Awesome, thanks!
