### ISSUE TITLE
AnimatorSet.start() hangs the test

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#5710]
### Description
When programmatically starting an animation (AnimatorSet) the test hangs.

### Steps to Reproduce
This is the code that hangs (gets stuck on animatorSet.start())
```java
        final AnimatorSet animatorSet = (AnimatorSet) AnimatorInflater.loadAnimator(context, R.animator.animation_key);
        final int startDelayInMillis = context.getResources()
                .getInteger(R.integer.add_pd_key_animation_delay_in_millis);
        animatorSet.setStartDelay(startDelayInMillis);
        animatorSet.setTarget(target);
        animatorSet.addListener(new OnAnimationDoneAnimatorListener() {
            @Override
            protected void onAnimationDone(Animator animation) {
                animation.start();
            }
        });
        animatorSet.start();
```

### Robolectric & Android Version
Robolectric: 4.2.1
Android Version: Min Api: 21, Target API: 29, @Config(sdk = Build.VERSION_CODES.LOLLIPOP)

### Workaround

I created a custom shadow:

```java
/**
 * Workaround for: https://github.com/robolectric/robolectric/issues/5710
 */
@Implements(AnimatorSet.class)
public class AnimatorSetShadow {

    @Implementation
    public void start() {
    }

}
```

**Comment by hoisie** [comment]
Does this happen with the new PAUSED looper mode?

**Comment by alixwar** [comment]
@hoisie I can confirm that adding

`@LooperMode(PAUSED)` in the class declaration solved it for me.
I had to upgrade to Robolectric 4.3 first. The problem was still reproducible in 4.3 before adding the annotation.

**Comment by hoisie** [comment]
Marking this as closed. In general infinite animations are an achilles heel of robolectric.
