### ISSUE TITLE
ShadowSharedMemory.map() can randomly throw IllegalStateException

### ISSUE THREAD

**Issue by jdcormie** [robolectric/robolectric#5757]
### Description
https://github.com/robolectric/robolectric/pull/5612 introduced a race between GC of entries in ShadowSharedMemory.filesById and calls to ShadowSharedMemory#map().

Before this change, the FileDescriptor instance used as the map key had the same lifetime as the shadowed instance of SharedMemory object, because of its strong mFileDescriptor member. With this change, the map key became the java.lang.Integer object created to auto-box a local "fd" int variable. After create() returns, that object is no longer strongly reachable and so the entry in filesByFd can disappear the next time the garbage collector runs, even though the associated SharedMemory object may still exist.

### Steps to Reproduce
SharedMemory shm = SharedMemory.create(...)
java.lang.System.gc();
shm.map(...); // May incorrectly throw IllegalStateException("Cannot find the backing file from fd")

**Comment by hoisie** [comment]
This is fixed here:
https://github.com/robolectric/robolectric/pull/5756
