### ISSUE TITLE
Conscrypt raise error when it is registered as SecurityProvider on Robolectric

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#5778]
### Description
I tried to replace Security Provider of robolectric, because bouncycastle has several compatibility issues on JDK9+ such as #5115 and  #5496
And I met strange exception, because isConscrypt() seems to return false
But, as exception message, trustManager.getClass().getName() is org.conscrypt.TrustManagerImpl

### Steps to Reproduce
Just run sample project with `./gradlew :app:testDevelopDebugUnitTest`

### Robolectric & Android Version
 * OpenJDK 11 (from AOSP or openjdk.net)
 * Robolectric 4.3.1
 * OkHttp 4.8.0
 * Conscrypt 2.4.0

### Link to a public git repo demonstrating the problem:

Github: https://github.com/ganadist/VersionCodeDemo/blob/ConscryptTest/
TestCode: https://github.com/ganadist/VersionCodeDemo/blob/ConscryptTest/app/src/test/java/com/example/myapplication/OkhttpClientTest.kt

#### Test result:
https://scans.gradle.com/s/bkchpw7ad7lvw/tests

#### Exception log:
https://scans.gradle.com/s/bkchpw7ad7lvw/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.OkhttpLoadingTest/testOkHttpClientBulid%5B28%5D#1

Strange thing is first unittest(testOkHttpClientBulid[21]) was passed, and others were failed.

x-posting with https://github.com/google/conscrypt/issues/863

**Comment by hoisie** [comment]
Removing and re-adding conscrypt seems to make it work

```kt
  @Test
  fun testOkHttpClientBulid() {
    Security.removeProvider("BC");
    Security.removeProvider("Conscrypt")
    Security.insertProviderAt(OpenSSLProvider(), 1);
    val client: OkHttpClient = OkHttpClient.Builder().build()
  }
```

At each SDK level there is a new classloaders. Maybe Security Providers cannot work across classloaders?

If this is the case we need to update how Robolectric instantiates BC as well.
