### ISSUE TITLE
JVMS says PRIVATE is not a valid class access flag

### ISSUE THREAD

**Issue by ephemient** [robolectric/robolectric#5840]
### Description

https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.1-200-E.1 includes
ACC_PUBLIC ACC_FINAL ACC_SUPER ACC_INTERFACE ACC_ABSTRACT ACC_SYNTHETIC ACC_ANNOTATION ACC_ENUM ACC_MODULE
but not ACC_PRIVATE.

ReflectorClassWriter is happy to produce it,
https://github.com/robolectric/robolectric/blob/d7b04e1a07b9b0d7be3bd24400a415aaca8ffa14/utils/reflector/src/main/java/org/robolectric/util/reflector/ReflectorClassWriter.java#L83

This causes issues when running Robolectric tests with a Java agent which uses [org.objectweb.asm.util.CheckClassAdapter](https://asm.ow2.io/javadoc/org/objectweb/asm/util/CheckClassAdapter.html). It will throw

    java.lang.IllegalArgumentException: Invalid access flags: 50
        at org.objectweb.asm.util.CheckClassAdapter.checkAccess(CheckClassAdapter.java:553)
        at org.objectweb.asm.util.CheckClassAdapter.visit(CheckClassAdapter.java:218)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:113)

### Link to a public git repo demonstrating the problem:

https://github.com/ephemient/robolectric-issue-5840

**Comment by hoisie** [comment]
Can you send a PR to fix this?
