### ISSUE TITLE
Global TestRunner for all modules

### ISSUE THREAD

**Issue by AndreBausLe** [robolectric/robolectric#5847]
### Description
I have many modules in a big Android Studio Project
Each module defines there own Tests.

By Executing alle Tests in the Project (gradle task: "testDebungUnitTest" from root), Robolectric (Test Runner ?) will be initialized for each module again and again. That initialization consumes many time. the tests it self are running very fast.

### Robolectric & Android Version
robolectric_version = '4.3'

### Question
Is there a way to have only one Robolectric Test environment over all modules to save time?

**Comment by hoisie** [comment]
Robolectric doesn't have any control of this -- the test processes are created and run by Gradle. Also, from Gradle's perspective, I don't think it would be feasible to use the same test process for all projects, given that each process may require different configurations. I would recommend consolidating the number of projects if you want this to happen.
