### ISSUE TITLE
I got a NullPointerException error when i was runing junit with RobolectricTestRunner on Android Studio

### ISSUE THREAD

**Issue by yaoki-prosper-s** [robolectric/robolectric#5861]
### Description
I got a NullPointerException error when i was runing junit with RobolectricTestRunner on Android Studio

i checked test_config.properties file.

#Generated by the Android Gradle plugin
android_custom_package=com.zdc.navigation
android_merged_assets=build\\intermediates\\merged_assets\\arm8Debug\\out
android_merged_manifest=build\\intermediates\\merged_manifests\\arm8Debug\\AndroidManifest.xml
android_resource_apk=build\\intermediates\\apk_for_local_test\\arm8DebugUnitTest\\apk-for-local-test.ap_

android_merged_resources is not included in properties 
but android_resource_apk is included.

i am setting following property in build.gradle, grade.properties.

testOptions {
    unitTests {
        includeAndroidResources true
    }
}

android.enableUnitTestBinaryResources=false

thanks you.

### Robolectric & Android Version
Robolectric 3.8
gradle plugin 4.0.1
gradle 6.1.1
Android Studio 4.0.1
Android SDK 27

**Comment by hoisie** [comment]
3.8 is an ancient version of Robolectric and does not support binary resources. I would recommend 4.4-beta-1. If the issue persists please post full stack traces and preferably small apps that demonstrate the issue.
