### ISSUE TITLE
Multidex generation when attempting to update to androidx

### ISSUE THREAD

**Issue by amadib** [robolectric/robolectric#5877]
### Description
I am attempting to update robolectric off of the last released version to use androidx over the support libraries and running into a compilation error:

```
> Task :shadows:multidex:compileJava FAILED
/Users/me/development/android-libraries/robolectric/shadows/multidex/build/generated/src/apt/main/org/robolectric/shadows/multidex/Shadows.java:28: error: method shadowOf(MultiDex) is already defined in class Shadows
  public static ShadowMultiDex shadowOf(MultiDex actual) {
                               ^
warning: The following options were not recognized by any processor: '[org.robolectric.annotation.processing.jsonDocsDir, org.robolectric.annotation.processing.sdkCheckMode]'
1 error
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shadows:multidex:compileJava'.
> Compilation failed; see the compiler error output for details.
```

### Steps to Reproduce

updating `compileOnly "com.android.support:multidex:1.0.1"` to `compileOnly "androidx.multidex:multidex:2.0.1"` will generate the following `Shadows.java` and the error above when running the assemble task.

```
public class Shadows implements ShadowProvider {
  private static final Map<String, String> SHADOW_MAP = new HashMap<>(2);

  static {
    SHADOW_MAP.put("androidx.multidex.MultiDex", "org.robolectric.shadows.multidex.ShadowAndroidXMultiDex");
    SHADOW_MAP.put("androidx.multidex.MultiDex", "org.robolectric.shadows.multidex.ShadowMultiDex");
  }

  public static ShadowAndroidXMultiDex shadowOf(MultiDex actual) {
    return (ShadowAndroidXMultiDex) Shadow.extract(actual);
  }

  public static ShadowMultiDex shadowOf(MultiDex actual) {
    return (ShadowMultiDex) Shadow.extract(actual);
  }
...
```

### Robolectric & Android Version
branched off `4.3.1` and updated AGP version to `3.6.3` and gradle wrapper to `5.6.4`

### Link to a public git repo demonstrating the problem:
No public repo at this time.

**Comment by hoisie** [comment]
Did you do a clean first, e.g. `./gradlew clean :shadows:multidex:build`?

Can you send a PR to fix it? Change ShadowMultiDex.java to be 
```
@Implements(className="android.support.multidex.MultiDex")
```

And make sure the AndroidX variant it is not imported  in ShadowMultiDex.java.

**Comment by hoisie** [comment]
Out of curiosity what was the original motivation for doing this?

**Comment by amadib** [comment]
The original motivation spurred from looking at jetifier and an exercise to take a large project and convert it to androidx.

**Comment by utzcoz** [comment]
This problem was fixed by https://github.com/robolectric/robolectric/commit/9eaf0e42bfdcca4785c38b9c9871acf8d49d3b7c. After it is been merged into master branch, we can close this issue.
