### ISSUE TITLE
QUESTION: Replacement for ShadowContentResolver cursor methods

### ISSUE THREAD

**Issue by Jordan-Turgeon** [robolectric/robolectric#5945]
### Description

I am wondering what the replacement is for setting up data to be returned from the `Content Resolver` for a particular URI. I had a handful of tests that were doing this before and now in Robocalls. The deprecation note on the method just simply states it doesn't work with `android.content.ContentResolver#acquireContentProviderClient` and doesn't provide any indication what we should do instead.

### Robolectric & Android Version

Robolectric 4.4
Android Version: N/A

### Code sample
```kotlin
val cursor = RoboCursor().apply {
    setColumnNames(ALL_COLUMNS.toList())
    setResults(arrayOf(arrayOf("", "host", "")))
}

val shadowContentResolver = Shadows.shadowOf(application.contentResolver)
shadowContentResolver.setCursor(CONTENT_URI, cursor)
```

**Comment by hoisie** [comment]
The replacement is to use a real Content Provider and return data through that. It should be fairly easy to set up a fake/stub content provider that returns the data that you need.

**Comment by hoisie** [comment]
We should probably have a blog post explaining this, though. It's definitely unclear what the recommended approach is.

**Comment by Jordan-Turgeon** [comment]
Ah ok I see that makes sense. Digging a bit more into the content resolve code I see the note on the method `registerProviderInternal()`. It states to do the following:
```java
ProviderInfo info = new ProviderInfo();
info.authority = authority;
Robolectric.buildContentProvider(ContentProvider.class).create(info);
```

Where I'm guessing the `authority` would be the `Uri.authority` of the thing I am querying that I want to get results for.

If this is right I would just create a mock content provider in my test class and create it using the above. It could then be configured to return whatever scenario I want.

Does this sound correct?

**Comment by hoisie** [comment]
Yes, that sounds about right.

+ @charlesmunger who may have more context

I think the original intent of this deprecation was to that ShadowContentResolver was not 100% compatible with [ContentProviderClient](https://developer.android.com/reference/android/content/ContentProviderClient).

By registering a fake content provider client, and removing some of the contentprovider-related shadows, we can end up using a lot more real Android content provider code.

**Comment by Jordan-Turgeon** [comment]
I'll give it a go sometime and see if I can remove the deprecated code.

Appreciate your feedback guiding me in the right direction.

**Comment by hoisie** [comment]
Awesome, let me know how it goes or if there are any issues with this approach.

**Comment by Jordan-Turgeon** [comment]
@hoisie Thanks for your feedback this appears to work just fine.

```kotlin
class TestContentProvider : ContentProvider() {

    companion object {

        fun create(uri: Uri): TestContentProvider = Robolectric.buildContentProvider(TestContentProvider::class.java).create(uri.authority).get()
    }

    private val results = mutableListOf<Cursor>()

    fun addResults(cursor: Cursor) {
        results.add(cursor)
    }

    override fun onCreate(): Boolean = true

    override fun query(uri: Uri, projection: Array<out String>?, selection: String?, selectionArgs: Array<out String>?, sortOrder: String?): Cursor? = results.pop()

    override fun getType(uri: Uri): String? = null

    override fun insert(uri: Uri, values: ContentValues?): Uri? = null

    override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0

    override fun update(uri: Uri, values: ContentValues?, selection: String?, selectionArgs: Array<out String>?): Int = 0
}
```

```kotlin
TestContentProvider.create(CONTENT_URI).also {
    it.addResults(MatrixCursor(...))
}
```
