### ISSUE TITLE
documents

### ISSUE THREAD

**Issue by momochenxx** [robolectric/robolectric#5952]
There are detailed usage documents, because I don't know how to use it

**Comment by hoisie** [comment]
Please see http://robolectric.org/getting-started/. Let me know if there is any confusion or if any part of that article does not work. Closing this for now since there isn't really anything actionable here.

**Comment by hoisie** [comment]
Whoops, realized the docs were a little out of date (they were using 4.3). I bumped the docs to point to 4.4.
