### ISSUE TITLE
Robolectric creates WidgetProvider (and may be BroadcastReceiver) before Application

### ISSUE THREAD

**Issue by serso** [robolectric/robolectric#596]
WidgetProvider is created before Application is created which causes crashes in some cases. Application should always be created first and Application#onCreate() method must be invoked before anything else.

**Comment by ubuntudroid** [comment]
I can confirm this issue for BroadcastReceivers as well: I'm using dependency injection in the receivers which is set up in the applications onCreate() method. Creating the BroadcastReceivers before the applications onCreate() method is called causes the receivers initialization to fail.

**Comment by tcw48** [comment]
Any updates on this?

**Comment by tmtrademarked** [comment]
This remains a problem in 3.4.2 - is this something that's on any roadmap to fix?

**Comment by xian** [comment]
Robolectric 4.0 fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
