### ISSUE TITLE
Unable to get shadow instance of SubscriptionManager

### ISSUE THREAD

**Issue by w2ji** [robolectric/robolectric#5989]
### Description
I am trying to create a robolectric test that would use the Android SubscriptionManager service. When I run my test, mContext.getSystemService(TELEPHONY_SUBSCRIPTION_SERVICE) returns null instead of the actual SubscriptionManager. I'm not sure if there's additional configuration I need to provide to enable this in my test.

### Steps to Reproduce

@RunWith(RobolectricTestRunner.class)
public class SampleTest {

    @Before
    public void setUp() {
        Context mContext = ApplicationProvider.getApplicationContext();
        SubscriptionManager subscriptionManager =
                (SubscriptionManager) mContext.getSystemService(TELEPHONY_SUBSCRIPTION_SERVICE);
        ShadowSubscriptionManager shadowSubscriptionManager = Shadow.extract(subscriptionManager);
    }
}

In the code above subscriptionManager is null and I am unable to extract the ShadowSubscriptionManager

### Robolectric & Android Version
"org.robolectric:robolectric:4.4"
"org.robolectric:shadows-multidex:4.4"
 "androidx.test:core:1.3.0"
 "androidx.test:monitor:1.3.0"

**Comment by hoisie** [comment]
What SDK version is this? SubscriptionManager is requires at least Android N (24).

**Comment by w2ji** [comment]
My app target SDK version is 30
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.test.testing"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

**Comment by hoisie** [comment]
Can you put up a sample app on GitHub that demonstrates the issue?

**Comment by hoisie** [comment]
My guess is that the test is running at SDK level 23 (you can check by doing
`System.out.println(Build.VERSION.SDK_INT);` at the start of the failing test. This is unlikely a Robolectric issue. If you want to  provide a complete report by following https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues I'll be happy to reopen.
