### ISSUE TITLE
Robolectric.setDefaultDisplay doesn't feed into WindowManager

### ISSUE THREAD

**Issue by andymstone** [robolectric/robolectric#605]
Robolectric.setDefaultDisplay(mydisplay) only sets the display in ShadowResources (so you get the specified display metrics if you call activity.getResources().getDisplayMetrics()).  But you can also call activity.getWindowManager().getDefaultDisplay(), and since setDefaultDisplay didn't affect the RoboWindowManager instance, you get back a different Display than you set in setDefaultDisplay.

One way to fix this is to update RoboWindowManager.getDefaultDisplay so that it checks if there is a display set in ShadowResources, which would require adding a getDisplay method to ShadowResources.  Or the other way around - setDefaultDisplay sets tthe display in RoboWindowManager and then ShadowResources gets its display from RoboWindowManager.

**Comment by xian** [comment]
Robolectric's handling of simulated displays and [device configuration](http://robolectric.org/device-configuration/) in general has significantly improved; please try with Robolectric 4.0.

If you feel this has been closed in error please feel free to reopen. Sample code running against 4.0 would make it easiest for us to diagnose any issues. Thanks!
