### ISSUE TITLE
ShadowResources: fail to decode escaped strings

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#606]
This is robolectric 1.2. Given the following resource entry that describes a regular expression

<pre>
&lt;resources>
   &lt;string name="foo">\\bfoo\\b&lt;/string>
&lt;/resources>
</pre>

the Android system returns the string "\bfoo\b" while robolectric gives me the escaped version "\bfoo\b". This is also a problem in the string array processor.

An overview of other "quirky" characters that can popup is given here: http://androidcookbook.com/Recipe.seam?recipeId=2219

By looking at the code I think robolectric especially does not support quoted strings like this (which would otherwise work in Android):

<pre>
&lt;resources>
   &lt;string name="foo">"\bfoo\b"&lt;/string>
&lt;/resources>
</pre>

**Comment by Ridermansb** [comment]
For `org.robolectric:robolectric:2.4`, I'm having the same problem. This bug was fixed in which version?
