### ISSUE TITLE
WebView.clearClientCertPreferences throw UnsupportedOperationException

### ISSUE THREAD

**Issue by RicardoTen** [robolectric/robolectric#6093]
When I test WebView.clearClientCertPreferences(null); throw UnsupportedOperationException with robolectric:4.4

Caused by: java.lang.UnsupportedOperationException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:241)
	at android.webkit.WebView.getFactory(WebView.java:2426)
	at android.webkit.WebView.clearClientCertPreferences(WebView.java:1430)

I see that it has been solved in the latest alpha version. How can I ignore this error in version 4.4 and whether it will cause problems if I inherit shadowWebview to implement this method

@Implements(value = WebView.class)
public class XShadowWebView extends ShadowWebView {

    @Implementation
    public static void clearClientCertPreferences(@Nullable Runnable onCleared) {
        // donothing
    }
}

**Comment by utzcoz** [comment]
Your method maybe work. And then you should add `XShadowWebView` to your test class or test method with `@Config(shadows = {XShadowWebView.class})`. If you need more information, you can see [Robolectric Official Shadows document](http://robolectric.org/extending/).

**Comment by utzcoz** [comment]
@RicardoTen The stable version 4.5.1 has been released, you can try it to fix this problem without custom shadow.

**Comment by utzcoz** [comment]
@RicardoTen you can follow https://github.com/robolectric/robolectric/issues/6093#issuecomment-737118487 to try add your shadow `WebView` to your test to avoid this problem on lower version. I will close this issue, and you can add commend or reopen it if you have more question.
