### ISSUE TITLE
(Spurious?) CloseGuard warnings for ParcelFileDescriptor

### ISSUE THREAD

**Issue by dominikpaulus** [robolectric/robolectric#6096]
### Description
In `ShadowParcelFileDescriptor.open()`, a new `ParcelFileDescriptor` [is created](https://cs.android.com/android/platform/superproject/+/master:external/robolectric-shadows/shadows/framework/src/main/java/org/robolectric/shadows/ShadowParcelFileDescriptor.java;l=47-49). The `ParcelFileDescriptor` implementation from Android uses `CloseGuard` to audit for resource leaks [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/ParcelFileDescriptor.java;l=111;drc=f5eebf9fe6caeaf80fdc716e22e5536e21943167).
However, the [implementation of close() for `ShadowParcelFileDescriptor`](https://cs.android.com/android/platform/superproject/+/master:external/robolectric-shadows/shadows/framework/src/main/java/org/robolectric/shadows/ShadowParcelFileDescriptor.java;l=115-118) never calls `close()` on its underlying `realObject`.
Note that the underlying `RandomAccessFile` is never passed to the `realObject`, so this is not leaking the real filedescriptor, and at most a dummy `FileDescriptor`-object to pass to the constructor of the underlying object.
However, code using the shadow ParcelFileDescriptor will still print (spurious? - I'm actually not sure if a default-constructed `FileDescriptor` consumes any resources that are not deleted on GC) warnings from CloseGuard:

```
System.logW: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.java.lang.Throwable: Explicit termination method 'close' not called
System.logW: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.java.lang.Throwable: Explicit termination method 'close' not called
```

### Steps to Reproduce

```java
package com.google.robolectric;

import android.os.ParcelFileDescriptor;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import java.io.File;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AndroidJUnit4.class)
public final class RobolectricTest {

  @Test
  public void testLeak() throws Exception {
    for (int i = 0; i < 10; ++i) {
      ParcelFileDescriptor fd =
          ParcelFileDescriptor.open(new File("/dev/null"), ParcelFileDescriptor.MODE_READ_ONLY);
      fd.close();
      System.gc();
    }
  }
}
```

Running this test will (most likely) report leaked objects as shown above, even though it should not.

### Robolectric & Android Version
I've tested with target SDK version 28.

### Link to a public git repo demonstrating the problem:
None. FWIW, Google-internal reference for above code snippet: cl/345446385 .

### Other
I thought about including an
```java
Shadow.directlyOn(realObject, ParcelFileDescriptor.class).close();
```
in the close()-method of `ShadowParcelFileDescriptor`, but it seems that doesn't work, as this would then call close() on `libcore.io.IOUtils`, which [relies on the nonstandard API `java.io.FileDescriptor.release$()` to be present](https://cs.android.com/android/platform/superproject/+/master:libcore/luni/src/main/java/libcore/io/IoBridge.java;l=252;drc=80189e24e79f2809407427203818e56d91d5abcf), which doesn't seem to be a valid assumption for all Robolectric tests. I haven't investigated further. Internal reference of this: cl/343477750 .

**Comment by hoisie** [comment]
Thank you for looking into this! These warnings are very annoying. There is a mechanism of intercepting calls to libcore's extensions to the Java public API. See https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/android/AndroidInterceptors.java

**Comment by hoisie** [comment]
This issue was fixed
