### ISSUE TITLE
Question: Extending existing shadows?

### ISSUE THREAD

**Issue by Jordan-Turgeon** [robolectric/robolectric#6099]
### Description
I'm wondering if there is a way to accomplish extending an existing shadow to alter just a particular behaviour slightly. An example of where I might want to do this is as follows:

I've found dealing with the `Fragment Manager` being sometimes painful during unit tests. To get around this, I've used reflection to inject a mocked fragment manager onto the activity instance.

What I've wondered is if there's an easy way to extend the existing `ShadowActivity` without necessarily needing all my Activities extending some custom class that would match this new shadow.

If this just isn't possible that's fine as I'm suspecting it's not. I could always go the route of just making all my activities extending a blank custom Activity to write a shadow against.

### Steps to Reproduce
N/A

### Robolectric & Android Version
**Robolectric:** 4.4

### Link to a public git repo demonstrating the problem:
N/A

**Comment by hoisie** [comment]
Yes it is, see http://robolectric.org/extending/

Closing this as it is not really an issue.
