### ISSUE TITLE
Newly added function in Android R(SQLiteDatabase.setCustomScalarFunction()) is not working on 4.5-alpha-3

### ISSUE THREAD

**Issue by MinseongPark** [robolectric/robolectric#6108]
### Description
When I add custom function and try to use it by query, it doesn't work on robolectric environment. But this function works on Android R device.

### Steps to Reproduce
```
@Config(sdk = [30])
@RunWith(AndroidJUnit4::class)
class CustomFunctionTest {

    @Test
    fun test() {
        val db = object :SQLiteOpenHelper(RuntimeEnvironment.application, null, null, 1) {
            override fun onCreate(db: SQLiteDatabase) {
                db.execSQL("CREATE TABLE person (name TEXT NOT NULL)")
            }

            override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
            }
        }
            .writableDatabase

        // Add '_CUSTOM' function which converts "value" to "#value#"
        db.setCustomScalarFunction("_CUSTOM") { "#$it#" }

        // And here I got an error; 
        // Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() SELECT _CUSTOM(name) FROM person [no such function: _CUSTOM]
        db.rawQuery("SELECT _CUSTOM(name) FROM person", null).use {
            // ...
        }
    }
}
```

### Robolectric & Android Version
4.5-alpha-3, Android R

**Comment by hoisie** [comment]
You may need to add a shadow implementation for SQLiteConnection.nativeRegisterCustomScalarFunction `https://source.corp.google.com/android/frameworks/base/core/java/android/database/sqlite/SQLiteConnection.java;l=132-133?q=customScalarFunctions&ss=piper%2FGoogle%2Fandroid`

**Comment by hoisie** [comment]
This actually would not be trivial. It's possible you may need to add support in sqlite4java for scalar functions.

**Comment by utzcoz** [comment]
@MinseongPark Please try the latest Robolectric with native SQLite mode, and feel free to reopen this issue if it still exists.
