### ISSUE TITLE
Tests fail with NoSuchMethodError: android.app.Activity.isDestroyed()

### ISSUE THREAD

**Issue by sahityadubey** [robolectric/robolectric#6115]
### Description
Tests fail on 4.3 with
java.lang.NoSuchMethodError: android.app.Activity.isDestroyed()Z

### Steps to Reproduce
Passing activity context through this-
`Activity activity  = Robolectric.buildActivity(Activity.class).create().start().resume().get();`
When I am trying to get the state through this `activity.isDestroyed()`, getting **NoSuchMethodError**.

### Robolectric & Android Version
Roboelectric: 4.3
Android Version: 28

**Comment by hoisie** [comment]
Sorry this is not really actionable without a code snippet or sample app. Also, 4.3 is highly outdated, please try with 4.5-alpha-3. If the issue persists I will happily reopen.
