### ISSUE TITLE
Test process not finish after all test complete

### ISSUE THREAD

**Issue by MohammadRezaei92** [robolectric/robolectric#6122]
### Description
I have a test class with 5 tests. Everything is ok if I run tests individually, but when I run all of them, tests passed but the test process still running and not finish.
![Screenshot 2020-12-20 102956](https://user-images.githubusercontent.com/14319444/102707402-cebaf100-42af-11eb-941e-a93a425ae80e.png)
It seems something wrong with this nativePollOnce function
![Screenshot 2020-12-20 103029](https://user-images.githubusercontent.com/14319444/102707420-0164e980-42b0-11eb-99d8-2244f70849fc.png)

### Robolectric & Android Version
Robolectric version: 4.5-alpha-3
Android version: sdk30

**Comment by alsutton** [comment]
Are you able to share the tests in a public repo which others can clone and reproduce the problem?

**Comment by utzcoz** [comment]
Please try the latest Robolectric to check whether this issue still exists, and feel free to reopen this issue if yes, and attach the minimal reproducible app/sample for it.
