### ISSUE TITLE
 Does robolectric support native libraries in tests now?

### ISSUE THREAD

**Issue by seebigsea** [robolectric/robolectric#6123]
### Description
Hello, My APP use NDK build native libraries, when I run the unit test, errors got as follow:
java.lang.UnsatisfiedLinkError: no mytestlib in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]

	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
### Steps to Reproduce
N/A
### Robolectric & Android Version
robolectric: '4.5-alpha-3' & targetSdkVersion 30 on Android Studio 4.1.1
### Link to a public git repo demonstrating the problem:
N/A

**Comment by hoisie** [comment]
Robolectric tests run on the JVM, don't will not support libraries compiled
against the NDK. That being said, cross platform native libraries could
work in Robolectric, but you have to have special logic that manages the
loading path.

**Comment by alandoni** [comment]
Since he is asking about supporting stuff, and I don't want to annoy you with another issue opened just to ask a question

Does robolectric support WebView.createPrintDocumentAdapter() ?

**Comment by hoisie** [comment]
It depends what you mean by support :) In Robolectric a real webview is not
used. All webview methods are shadowed. This means that you can interact
with Android webview code but you are just interacting with a fake. I'm not
sure specifically about createPrintDocumentAdapter, but you are welcome to
try it and see if it works. If it does not please file a new issue.

**Comment by alandoni** [comment]
I tried but got a NullPointerException, but by your explanation, it seems that what I was trying to do is impossible, since I needed the actual implementation, I will keep it running with Espresso

**Comment by hoisie** [comment]
Closing this since it's more of a general question about Robolectric.

**Comment by nikitph** [comment]
we would love to know if we can still support loading  .so files via cmake

**Comment by hoisie** [comment]
If the .so is compiled against the Android NDK, it will *not* work in Robolectric. Otherwise, you can try to use Java JNI: https://docs.oracle.com/javase/8/docs/technotes/guides/jni/. Robolectric itself uses some native code (sqlite4java), so it is possible.
