### ISSUE TITLE
Migrate CI checks from CircleCI to GitHub actions

### ISSUE THREAD

**Issue by LitterSun** [robolectric/robolectric#6133]
Currently Robolectric is still using CircleCI for PR checks.
Should we migrate to GitHub actions ？

**Comment by hoisie** [comment]
Sure, that sounds good to me! I'm not too attached to CircleCI. Would you be able to give it a try on a fork and evaluate if it works or not?

I know Robolectric CI tends to use a lot of memory (8-16 GB). CircleCI workers are 16GB I believe. There's some hacks in our CircleCI config to reduce the chance for OOMS. This shards tests among 5 workers, each of which running a small range of SDK levels. Not sure to what extent this would be necessary in Github CI.

**Comment by utzcoz** [comment]
If migrating CI checks to GitHub actions, we can get more detail information for test check information.
