### ISSUE TITLE
OOM issue!!

### ISSUE THREAD

**Issue by hhhhhardy** [robolectric/robolectric#6134]
### Description
My current project has only 110+ testcases, but getting OOM issues sometimes when running on Jenkins CI. I have tried many methods like finishing and destroying any activities created in the teardown method, and no luck. 
The attachment is my JProfiler usage, I saw char[] and String consuming large amount of memory. 
Can I have some suggestions on that?

![1111](https://user-images.githubusercontent.com/44079686/103651312-5dac5680-4f9c-11eb-8edc-80fbbe3649cb.png)

### Steps to Reproduce
Run the test

### Robolectric & Android Version
Robolectric 4.4
Android SDK Version 28

**Comment by hoisie** [comment]
Seems like it could be
https://github.com/robolectric/robolectric/issues/5530, which has been
fixed, but may not have been released yet. Do your tests do things like
create dozens of activities in the same test? If not, you may be leaking
activities across tests.

**Comment by hoisie** [comment]
Actually the [fix](https://github.com/robolectric/robolectric/commit/dab2c3bb93529738e0fa2560a5904ee6b49e8acf) is in 4.5-alpha-3, can you give that a try?

If it still fails, try to do GC root analysis on test activities.

**Comment by hhhhhardy** [comment]
@hoisie Thanks for the reply. Yeah, I created activities in every single test, and destroy them in the teardown method. Will this cause leaks across tests?

**Comment by hoisie** [comment]
4.5 is released, give it a try, and if the problem persists, comment and I'll reopen.
