### ISSUE TITLE
ShadowApplication.setSystemService non-deprecated replacement

### ISSUE THREAD

**Issue by matpag** [robolectric/robolectric#6167]
The documentation for `ShadowApplicaption.setSystemService` says it is deprecated and will be removed in future updates.
Check here:
https://github.com/robolectric/robolectric/blob/8b06548f0e8f339d3d29533180135dbbc7d04987/shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplication.java#L356-L364
What should be the correct alternatives for replacing system services?
I found myself in situations where I had to test services methods returning custom values.

For example I had to return null for `getActiveNetworkInfo` of `ConnectivityManager`, and I proceeded like this:
```
val context: Context = ApplicationProvider.getApplicationContext()
val spiedCM = Mockito.spy(context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager)
doReturn(null).`when`(spiedCM).activeNetworkInfo
val shadowApp: ShadowApplication = shadowOf(context as Application)
shadowApp.setSystemService(Context.CONNECTIVITY_SERVICE, spiedCM)
```
What should be the non deprecated replacement?
Thank you

**Comment by hoisie** [comment]
You should be able to create a custom shadow:

```java
public class MyShadowConnectivityManager extends ShadowConnectivityManager {
  @Implementation
  protected NetworkInfo getActiveNetworkInfo() {
    return null;
  }
}
```

And then in your test, specify:
`@Config (shadows={MyShadowConnectivityManager.class})`

**Comment by matpag** [comment]
I've created this class:
```
@Implements
class MyShadowConnectivityManager : ShadowConnectivityManager() {
  @Implementation
  override fun getActiveNetworkInfo(): NetworkInfo? {
    return null
  }
}
```
and this test method
```
@Config(shadows = [MyShadowConnectivityManager::class])
@Test
fun testNullActiveNetworkInfo() {
  val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
  assertNull(cm.activeNetworkInfo)
}
```
but it gives me this error:
`java.lang.AssertionError: expected null, but was:<[type: null[null], state: null/null, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false]>`

I'm doing something wrong?

**Comment by hoisie** [comment]
Whoops you need `@Implements(ConnectivityManager.class)` as a class annotation (also updated my example).

**Comment by matpag** [comment]
It's working fine.
Thank you for your help 👍

**Comment by reactormonk** [comment]
> You should be able to create a custom shadow:
> 
> ```java
> @Implements(ConnectivityManager.class)
> public class MyShadowConnectivityManager extends ShadowConnectivityManager {
>   @Implementation
>   protected NetworkInfo getActiveNetworkInfo() {
>     return null;
>   }
> }
> ```
> 
> And then in your test, specify: `@Config (shadows={MyShadowConnectivityManager.class})`

What can I do if the original `Manager` is `final` (e.g. `MediaMetricsManager`)?
