### ISSUE TITLE
Use of RoboExecutorService causes "java.lang.IllegalStateException: this action is not supported in PAUSED mode."

### ISSUE THREAD

**Issue by alwa** [robolectric/robolectric#6169]
### Description
Instantiating RoboExecutorService() when running test in PAUSED looper mode causes an IllegalStateException.

### Steps to Reproduce
```
import androidx.test.ext.junit.runners.AndroidJUnit4;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.android.util.concurrent.RoboExecutorService;
import org.robolectric.annotation.Config;
import org.robolectric.annotation.LooperMode;
import org.robolectric.shadows.ShadowLooper;

@Config(sdk = Build.VERSION_CODES.N)
@RunWith(AndroidJUnit4.class)
@LooperMode(LooperMode.Mode.PAUSED)
public class FooTest {

@Test
public void test() {
    new RoboExecutorService()
}
```

### Robolectric & Android Version
Robolectric 4.4
Android minSdkVersion 24, compileSdkVersion 30, targetSdkVersion 30

### Link to a public git repo demonstrating the problem:
Repo not public

**Comment by alwa** [comment]
If we're not supposed to use RoboExecutorService then I think it should be deprecated

**Comment by hoisie** [comment]
Looks like it was already deprecated and removed here:

https://github.com/robolectric/robolectric/commit/c010b75690b63accb6b72391a4ea150b3d203b28

Would one of these work:
https://source.corp.google.com/piper///depot/google3/third_party/java_src/robolectric/shadows/framework/src/main/java/org/robolectric/android/util/concurrent/
?

**Comment by hoisie** [comment]
My mistake (typo in grep), it is still here: https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/android/util/concurrent/RoboExecutorService.java

@brettchabot should this be deprected?
