### ISSUE TITLE
[Bazel] ASWB plugin fails to sync with Robolectric + Bazel 4.0.0 

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#6242]
### Description

Android Studio w/ Bazel plugin fails when syncing a project with `android_local_test` targets in Bazel 4.0.0.

This is the failure message:

```
 error: missing required annotation argument: <clinit>
@Config(sdk={LOLLIPOP})
```

### Steps to Reproduce

The following command is the smallest stripped down command that the IDE issues. Note that `intellij-resolve-java` is the key output group since this is what triggers Turbine. Note, that it is possible to build and run tests because Turbine isn't invoked for a target in these cases. It's the aspect that triggers Turbine.

```
bazel build --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/jgerrish/Library/Application Support/Google/AndroidStudio4.1/plugins/aswb/aspect" --output_groups=intellij-resolve-java -- //foo/bar/baz:test
```

This has already been reported here, but looks like they just worked around the issue by pegging at Bazel 3.7.
https://github.com/google/dagger/commit/1b5b0757a08d40b27595995a8f0830aa2c1802d3

The actual part of Turbine that is making this check was introduced here: https://github.com/google/turbine/commit/8bbf4cbe2c55254d828c9b76ff472cd1d789ebdc

I'm unsure why its reporting `clinit` as the missing attribute however.

### Robolectric & Android Version

Robolectric 4.2.1
Bazel 4.0.0 (Works in 3.7.x)

**Comment by jongerrish** [comment]
Still an issue with Robolectric 4.5.1

**Comment by jongerrish** [comment]
Created this issue to track on the Bazel side: https://github.com/bazelbuild/bazel/issues/13144

**Comment by jongerrish** [comment]
Looks like it is fixed in Turbine. Liam included a refactoring you can do to `@Config` to avoid the error too.

**Comment by hoisie** [comment]
Closing for this as the problem seems to be in turbine. Since it's been fixed in Turbine I don't think it's necessary to work around it on Robolectric.
