### ISSUE TITLE
Memory leak when using FragmentScenario

### ISSUE THREAD

**Issue by vn01971** [robolectric/robolectric#6262]
### Description
My issue might be related to https://github.com/android/android-test/issues/457.

My tests make heavy use of `FragmentScenario`s and it looks like the OOM error doesn't occur (or at least doesn't occur as often) when I move the fragment to the destroyed state after each test. Do you know if you're expected to move it to the destroyed state for test cleanup? Note that `MyCustomFragment` is a complex fragment in my app, so potentially it could have a memory leak (though I haven't seen any from LeakCanary)

### Without moving to destroyed state
```kotlin
    @Test
    // This test does result in OOM error
    fun launchMyCustomFragment_DontMoveToDestroyed(){
        for (i in 0 until 1000) {
            val scenario = launchFragmentInContainer<MyCustomFragment>(null, R.style.MyTheme)
        }
    }
```
![Screen Shot 2021-03-03 at 3 23 16 PM](https://user-images.githubusercontent.com/60491415/110033404-f3473680-7cfe-11eb-98ac-6c0b89a452cd.png)

### With moving to destroyed state
```kotlin
    @Test
    // This test doesn't result in OOM error
    fun launchMyCustomFragment_MoveToDestroyed(){
        for (i in 0 until 1000) {
            val scenario = launchFragmentInContainer<MyCustomFragment>(null, R.style.MyTheme)
            scenario.moveToState(Lifecycle.State.DESTROYED)
        }
    }
```
![Screen Shot 2021-03-03 at 3 23 05 PM](https://user-images.githubusercontent.com/60491415/110033430-fc380800-7cfe-11eb-98d0-55957a97c8f1.png)

It _seemed_ like it was a memory leak in my code since the following test didn't result in an OOM error (note that `EmptyFragment` is a fragment I made with just a textview):
```kotlin
    @Test
    // This test doesn't result in OOM error
    fun launchEmptyFragment_MoveToDestroyed(){
        for (i in 0 until 1000) {
            val scenario = launchFragmentInContainer<EmptyFragment>(null, R.style.MyTheme)
        }
    }
```

However, that `launchEmptyFragment_MoveToDestroyed` test does result in an OOM error if I change the loop iterations to 10,000. Futhermore, the following test also results in an OOM error, which makes me concerned that moving to the destroyed state isn't the solution:
```kotlin
    @Test
    // This test does result in an OOM error
    fun launchEmpty_MoveToDestroyed(){
        for (i in 0 until 10000) {
            val scenario = launchFragmentInContainer<EmptyFragment>(null, R.style.MyTheme)
            scenario.moveToState(Lifecycle.State.DESTROYED)
        }
    }
```

It does look like a lot of`FragmentScenario$EmptyFragmentActivity` instances are sticking around (this image is from the last example test above), which is why I think it might be related to https://github.com/android/android-test/issues/457.
<img width="1099" alt="Screen Shot 2021-03-04 at 3 45 44 PM" src="https://user-images.githubusercontent.com/60491415/110035082-d14eb380-7d00-11eb-8b56-334a8800fef8.png">

<img width="1577" alt="Screen Shot 2021-03-04 at 3 51 34 PM" src="https://user-images.githubusercontent.com/60491415/110035655-900ad380-7d01-11eb-977a-675fae9e7a0d.png">

_Originally posted by @vn01971 in https://github.com/robolectric/robolectric/issues/5530#issuecomment-790971746_

**Comment by hoisie** [comment]
Thank you for all the helpful details, it will make it a lot easier to
investigate.

**Comment by hoisie** [comment]
In the test, is `close()` being called on FragmentScenario? This ends up calling the underlying `ActivityScenario.close`:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment-testing/src/main/java/androidx/fragment/app/testing/FragmentScenario.kt;l=407?q=fragmentscenario&ss=androidx

Although not explicitly stated in the FragmentScenario docs, if you want to clean up the activity state, you need to `close()` an ActivityScenario:

https://developer.android.com/reference/androidx/test/core/app/ActivityScenario

```
ActivityScenario does't clean up device state automatically and may leave the activity keep running after the test finishes. Call close() in your test to clean up the state or use try-with-resources statement. This is optional but highly recommended to improve the stability of your tests. Also, consider using ActivityScenarioRule.
```

**Comment by vn01971** [comment]
@hoisie `close()` is not being called in this test because I don't believe the latest fragment-testing version (1.3.0) has the `close()` function yet. I'll plan on checking if that fixes things when it's released and then I'll update this MR accordingly.

**Comment by gekylafas** [comment]
Until this is released, I ended up using:

```kotlin
fun <T: Fragment> FragmentScenario<T>.close() {
    FragmentScenario::class.memberProperties
        .find { it.name == "activityScenario"}
        ?.let {
            it.isAccessible = true
            (it.get(this) as ActivityScenario<*>).close()
        }
}
```

**Comment by scottdweber** [comment]
Awesome, thanks @gekylafas ! I took your idea and added a `withAutoClose()` function that can be used instead of `with()` in the `with(launchFragment(...)) { ... }` pattern:

```kotlin
fun <F : Fragment, R> withAutoClose(
    fragmentScenario: FragmentScenario<F>,
    block: FragmentScenario<F>.() -> R
): R {
    val result = fragmentScenario.block()
    fragmentScenario.close()
    return result
}
```

e.g.

```kotlin
withAutoClose(launchFragment<MyFragment>()) {
    onFragment {
        // assert, etc.
    }
}
```

**Comment by utzcoz** [comment]
@vn01971 The latest `fragment-testing` version is [1.4.1](https://developer.android.com/jetpack/androidx/releases/fragment), what about giving a try?
