### ISSUE TITLE
Bitmap.createScaledBitmap doesn't modify colors array

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#6273]
```java
  @Test
  public void createScaledBitmap_modifiesPixels() {
    Bitmap bitmap = Bitmap.createBitmap(100, 100, Bitmap.Config.ARGB_8888);
    bitmap.eraseColor(Color.BLUE);
    Bitmap scaledBitmap = Bitmap.createScaledBitmap(bitmap, 50, 50, /* filter= */ false);
    assertThat(scaledBitmap.getPixel(0, 0)).isEqualTo(Color.BLUE);
  }
```

```
value of: getPixel(...)
expected: -16776961
but was : 0
Expected :-16776961
Actual   :0
```

**Comment by hoisie** [comment]
@utzcoz in theory would it be possible to keep the BufferedImage around (perhaps as a member of ShadowBitmap) and potentially use it for scaling? Alternatively we could do crop-scaling, but that would not mimic the interpolation done by Android.

**Comment by utzcoz** [comment]
In theory, we can keep `BufferedImage` as a member of `ShadowBitmap` as other members. But I don't know whether there are other methods need to use `BufferedImage` to do some work directly. I can try to crop scale it directly based on current color array, and if it is difficult for me, I will try to cache `BufferedImage` to do it.

**Comment by utzcoz** [comment]
If we can remove color array, keep the `BufferedImage` as the member could be good. What I know that can got from `BufferedImage` is width, height, pixel, color space.

**Comment by utzcoz** [comment]
Hi @hoisie, I send a PR to use `BufferedImage` to scale bitmap, it is here: https://github.com/robolectric/robolectric/pull/6280.
