### ISSUE TITLE
ShadowBitmap's setPixels and setPixel are not consistent with mutable checking

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6281]
```java
  @Implementation
  protected void setPixels(
      int[] pixels, int offset, int stride, int x, int y, int width, int height) {
    this.colors = pixels;
  }
```

```java
  @Implementation
  protected void setPixel(int x, int y, int color) {
    if (isRecycled()) {
      throw new IllegalStateException("Can't call setPixel() on a recycled bitmap");
    } else if (!isMutable()) {
      throw new IllegalStateException("Bitmap is immutable");
    }
    internalCheckPixelAccess(x, y);
    if (colors == null) {
      colors = new int[getWidth() * getHeight()];
    }
    colors[y * getWidth() + x] = color;
  }
```

I can use `ShadowBitmap.setPixels` to replace pixels directly, although this `Bitmap` is not mutable. But the `ShadowBitmap.setPixel` throws exception for me if this `Bitmap` is not mutable. The source code of `setPixels` and `setPixel` actually use different mechanism to process mutable flag as the above code showing. @hoisie is this behavior expected?

**Comment by hoisie** [comment]
Seems like this is inconsistent with real Android. Real Android throws an IllegalStateException if setPixels is called and the Bitmap is immutable:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/graphics/java/android/graphics/Bitmap.java;l=2086?q=setpixels

Confirmed with this test, which throws an IllegalStateException on an emulator:
```java
  @Test
  public void setPixels_mutable() {
    BitmapFactory.Options options = new Options();
    options.inMutable = false;
    Bitmap bitmap = BitmapFactory.decodeResource(resources, R.drawable.an_image, options);
    bitmap.setPixels(new int[] { Color.RED }, 0, 0, 0, 0, 1, 1);
  }
```

**Comment by utzcoz** [comment]
If need, I can try to fix it with a PR.
