### ISSUE TITLE
Use bulk BufferedImage.setRGB in Bitmap.compress

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#6298]
This should be a lot faster than individual setRGB pixel-by-pixel.

https://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html#setRGB(int,%20int,%20int,%20int,%20int[],%20int,%20int)

**Comment by hoisie** [comment]
@utzcoz want to check this out?

**Comment by utzcoz** [comment]
Thanks. I will try to use it to speed up `setRGB`.

**Comment by utzcoz** [comment]
The `ShadowBitmapFactory.decode*` maybe can use `setPixels` to speed up too.
