### ISSUE TITLE
How to set a system service to null without using ShadowApplication.setSystemService

### ISSUE THREAD

**Issue by matpag** [robolectric/robolectric#6331]
For example, I just want to test if a getSystemService returns a null service, i did something like this for NfcManager:

```kotlin
@RunWith(AndroidJUnit4::class)
@Config(sdk = [Build.VERSION_CODES.P])
class ExampleUnitTest {

    private val context: Context = ApplicationProvider.getApplicationContext()

    @Test
    fun checkNfcManagerIsNull() {
        val shadowApp: ShadowApplication = shadowOf(context as Application)
        @Suppress("DEPRECATION")
        shadowApp.setSystemService(Context.NFC_SERVICE, null)
        //some utility class which checks for NfcManager availability
        assertNull(context.getSystemService(Context.NFC_SERVICE))
    }
}
```
Is there an alternative without using a deprecated API?
This is somehow connected to my previous (and resolved) question [here](https://github.com/robolectric/robolectric/issues/6167)

Thank you

**Comment by utzcoz** [comment]
You can use the method such as https://github.com/robolectric/robolectric/issues/6167#issuecomment-765534249 to create a shadow `NfcManager`, and returns null for its service method. And then you can create two test methods, one uses your custom shadow `NfcManager` to test null returns of `context.getSystemService(Context.NFC_SERVICE)` with adding your custom shadow class by `@Config`, and another test method uses normal `@Config` without your custom shadow class to test normal returns of `context.getSystemService(Context.NFC_SERVICE)`.

**Comment by matpag** [comment]
I have some questions related to your answer:
1) There is no `ShadowNfcManager` to extend like I did for the `ShadowConnectivityManager`
2) In the previous issue I had to set to null a property of the service, in this case I need the service to be null

> create a shadow `NfcManager`, and returns null for its service method.
How to achieve what you described?

Thank you

**Comment by utzcoz** [comment]
I have achieved this need with adding custom `ShadowContextImpl`.

Firstly, we can create a custom `ShadowContextImpl` name `CustomShadowContextImpl`:

```kotlin
@Implements(className = ShadowContextImpl.CLASS_NAME)
class CustomShadowContextImpl: ShadowContextImpl() {
    @Implementation
    override fun getSystemService(name: String): Any? {
        if (Context.NFC_SERVICE == name) {
            return null;
        }
        return super.getSystemService(name);
    }
}
```

And then use `@Config(shadows = [CustomShadowContextImpl::class])` to annotate your test for null `NfcManager`:

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [Build.VERSION_CODES.P])
class ExampleUnitTest {
    private val context: Context = ApplicationProvider.getApplicationContext()

    @Test
    fun checkNfcManagerIsNotNull() {
        assertNotNull(context.getSystemService(Context.NFC_SERVICE))
    }

    @Test
    @Config(shadows = [CustomShadowContextImpl::class])
    fun checkNfcManagerIsNull() {
        assertNull(context.getSystemService(Context.NFC_SERVICE))
    }
}
```

I have tested above code with 4.6.1. In Robolectric site, http://robolectric.org/extending/, there is a section called `Custom Shadows` to show the detail to shadow class to simulate behavior what you want that Robolectric doesn't support.

Also, you can use mockito to mock `getSystemService` to simulate your behavior, such as https://cs.android.com/android/platform/superproject/+/master:packages/apps/Settings/tests/robotests/src/com/android/settings/connecteddevice/NfcAndPaymentFragmentControllerTest.java;l=69?q=NfcManager .

IMHO, I recommend the second method to use mockito to simulate your behavior. Although we can extend and add custom shadow for `ShadowContextImpl`, `ShadowContextImpl` is used to shadow `ContextImpl`, what is not public on Android SDK, and it should be used carefully.

**Comment by utzcoz** [comment]
@matpag you can try https://github.com/robolectric/robolectric/issues/6331#issuecomment-874938497 to set null for `NfcManager` without `ShadowApplication#setSystemService`. Feel free to reopen this issue if you have any problem.
