### ISSUE TITLE
How to idle android view.post

### ISSUE THREAD

**Issue by poldz123** [robolectric/robolectric#6337]
### Description
How do I trigger the view's post when using LooperMode.PAUSE? It seems that using LEGACY will trigger it whereas PAUSE does not, also even calling `shadowOf(Looper.getMainLooper)).idle()` does not work.

### Steps to Reproduce

```
@Test
fun test() {
    val framelayout = FrameLayout(context)
    framelayout.post {
         println("triggered") <-- Does not triggered
    }
    shadowOf(Looper.getMainLooper)).idle
}

```

### Robolectric & Android Version

SDK 28
Robolectric 4.5

**Comment by Tarball** [comment]
+1. I'm running into the same issue on Robolectric 4.4. My current workaround is to add `@LooperMode(Mode.LEGACY)` to these tests, but I'm interested in learning the "correct" way to do this without depending on a deprecated mode.

**Comment by hoisie** [comment]
What is the 'context' in this case? Is the view attached to an Activity? Can you post a more complete example?

When you post something to a view, it requires the view to be attached to something:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/View.java;l=18757-18767?q=view.java&ss=android

**Comment by poldz123** [comment]
@hoisie The context is either from an activity or a fragment that was lunch in a scenario. Being in a scenario should walk through those lifecycles.

```kotlin
activityScenario = ActivityScenario.launch(AccountActivity::class.java).onActivity { activity ->
    val framelayout = FrameLayout(activity)
    framelayout.post {
         println("triggered") <-- Does not triggered
    }
    shadowOf(Looper.getMainLooper)).idle()
}
```

**Comment by nak411** [comment]
Any update on this?

**Comment by hoisie** [comment]
`View.post` will not work is the view is not attached to the view hierarchy. If a View is created dynamically in a test, something has to call `addView` on it. You can see this directly in the code for View.post.

@poldz123 that example should be something like:

```kt
activityScenario = ActivityScenario.launch(AccountActivity::class.java).onActivity { activity ->
    val framelayout = FrameLayout(activity)
    ((ViewGroup)activity.findViewById(android.R.id.content)).addView(framelayout);
    framelayout.post {
         println("triggered") <-- Does not triggered
    }
    shadowOf(Looper.getMainLooper)).idle()
}
```
