### ISSUE TITLE
Creating SQLiteDatabase column with "NOT NULL" but schema has "notNull=false".

### ISSUE THREAD

**Issue by le-kamba** [robolectric/robolectric#6411]
### Description
I'm trying to migrate this Google's sample project's androidTest to robolectric.
https://github.com/android/architecture-components-samples/tree/master/PersistenceMigrationsSample

When run tests on device, tests pass.
When run with robolectric, test failed with error like below.

```
java.lang.IllegalStateException: Migration didn't properly handle: users
Expected: TableInfo{name='users', columns={userid=Column{name='userid', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, username=Column{name='username', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]} 
found: TableInfo{name='users', columns={userid=Column{name='userid', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1, defaultValue='null'}, username=Column{name='username', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=null}
```

In test code, old database was created with:

```
db.execSQL("CREATE TABLE IF NOT EXISTS users (userid INTEGER PRIMARY KEY NOT NULL,"
                + " username TEXT )");
```

But it seems making a column with "NOT NULL" doesn't work.(Error message says userid column has "notNull=false" attribute.)

Is this a bug?
Is there any workaround to fix this?

### Steps to Reproduce
1. Define entity which has non-null property as primary key.
2. Define classes dao, database, repository with Room. Be sure to make database version is 2.
3. Create table using SQLiteDatabaseHelper and SQLiteDatabase in test code for database version 1.
4. Run migration test in unit test with robolectric.

### Robolectric & Android Version
robolectric 4.5.1
android target 29
openjdk version "11.0.10"

### Link to a public git repo demonstrating the problem:
https://github.com/le-kamba/KotlinRoomMigrationSample/tree/robolectric

**Comment by hoisie** [comment]
This is most likely a bug in Room. I am not sure we can do anything about it on the Robolectric side.

**Comment by le-kamba** [comment]
No, I don't think it is a bug of Room.
Because, when I run tests in androidTests, the schema which created by SQLiteDatabaseTestHelper is correct.
Only running with Robolectric, the schema is not correct.

**Comment by hoisie** [comment]
It would be great if this issue could be reduced down to a sequence of
SQLiteDatabase statements that do not produce a result that is consistent
with real Android. It's possible that Robolectric version of sqlite jni
(sqlite4java) has some slightly different behavior than what Room expects.

**Comment by utzcoz** [comment]
@le-kamba could you help to re-test it with Robolectric 4.7.3? It introduces a native SQLite mode with better performance and more accurate behavior.

**Comment by githubgist123** [comment]
@le-kamba did you solve your problem?
I also want migrate this sample https://github.com/android/architecture-components-samples/tree/master/PersistenceMigrationsSample to local unit test but have problem.
Here is my code https://gist.github.com/githubgist123/3bab7013088c47858c496a8044be99f5
Here is error log https://gist.github.com/githubgist123/94be3e8da3b61d2a957916ff67afe2ad

**Comment by githubgist123** [comment]
everything works fine in latest version(4.9). Thank you.

**Comment by utzcoz** [comment]
@githubgist123 Thanks for your feedback. @le-kamba Feel free to reopen this issue if you have other questions.
