### ISSUE TITLE
Jetifier fails on bcprov-jdk15on-1.68.jar / Robolectric 4.6-alpha-2

### ISSUE THREAD

**Issue by ogolberg** [robolectric/robolectric#6521]
### Description

When building an Android project with a testImplementation dependency on Robolectric 4.6-alpha-2, the build fails with

```
Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/runner/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.
         > Failed to transform '/home/runner/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
```

Note that Bouncycastle was bumped to 1.68 in alpha-2. The error is likely due to Bouncycastle jars being multi-release and Bouncycastle 1.68 including classes targeting Java 15 (and probably Jetifier being unaware of multi-release jars).

As a workaround, It's possible to manually exclude bcprov-jdk15on from jetifying, but I think this still counts as a regression.

### Steps to Reproduce

Set up a boilerplate Android project with Robolectric 4.6-alpha-2 and try to build it using JDK 11 or lower.

### Robolectric & Android Version

Robolectic 4.6-alpha-2, AGP 7.0-beta3, Java 11 used in the project below

### Link to a public git repo demonstrating the problem:

See https://github.com/ogolberg/robolectric-integration-tests/runs/2711507099?check_suite_focus=true

**Comment by utzcoz** [comment]
I will check whether lower version but with CVE fixed commit has the same problem.

**Comment by hoisie** [comment]
This is a pretty bad bug in jetifier I believe.

I think to fix this issue you can add to your gradle.properties:

```
android.jetifier.blacklist=bcprov
```

or perhaps

```
android.enableJetifier=false
```

**Comment by hoisie** [comment]
More context:

https://github.com/bcgit/bc-java/issues/762
https://issuetracker.google.com/issues/172784894?pli=1
https://issuetracker.google.com/issues/159151549

**Comment by nikitph** [comment]
I kinda fixed it by upgrading the gradle plugin to latest. may be it will work for u

**Comment by ogolberg** [comment]
ok I think we can call it a bug in jetifier and close

**Comment by hoisie** [comment]
There are also revived efforts to bump the ASM version in Jetifier (https://issuetracker.google.com/issues/159151549).

**Comment by IgorGanapolsky** [comment]
This error is still occurring in robolectric 4.6.1.  What is the fix?

**Comment by hoisie** [comment]
@IgorGanapolsky https://github.com/robolectric/robolectric/issues/6521#issuecomment-851736355

Add 
`android.jetifier.blacklist=bcprov` or
`android.enableJetifier=false` to gradle.properties. or upgrade to 7.1.x of AGP.

**Comment by DanielWaiguru91** [comment]
> I kinda fixed it by upgrading the gradle plugin to latest. may be it will work for u

This worked for me. Thanks

**Comment by cioccarellia** [comment]
Blacklisting it worked: `android.jetifier.blacklist=bcprov`

**Comment by JagadishaIncture** [comment]
> android.enableJetifier=false

worked

**Comment by raoadnanjafar** [comment]
i have face same issue. first you open your build.properties and then add this "android.jetifier.blacklist=bcprov-jdk15on" "android.enableJetifier=true"
