### ISSUE TITLE
Using Robolectric outside of JUnit? (Not a bug)

### ISSUE THREAD

**Issue by gedgygedgy** [robolectric/robolectric#6552]
Sorry if this is the wrong place to ask questions, I'm not sure where else to ask - the Google Group for Robolectric appears to have been dead for some time.

I'm writing some Rust code to integrate with Android, and I need to write unit tests to ensure that it works correctly. I would prefer to use the Rust testing framework and spin up a JVM using the invocation API, rather than use JUnit. Is it possible to inject Robolectric into a JVM without using JUnit, so that code that depends on the Android APIs will use the Robolectric implementation? My initial glance at the Robolectric sandbox code shows a lot of classes with `internal` in their package names that look rather difficult to use outside of JUnit.

**Comment by hoisie** [comment]
This is not possible at the moment. Robolectric is highly coupled to JUnit. There have been some efforts in this area in the past (e.g. support Spek), but they have unfortunately stalled due to other priorities.

**Comment by utzcoz** [comment]
> Sorry if this is the wrong place to ask questions, I'm not sure where else to ask - the Google Group for Robolectric appears to have been dead for some time.

Hi @hoisie, what about opening [GitHub Discussions](https://docs.github.com/en/discussions) for `Robolectric`? This feature is open for projects now, and it can be used for non-bug problems/questions. If there is a feature discussed at GitHub Discussions widely, we can consider move it to issue to track and implement it. 

Hi @gedgygedgy , the `Robolectric` is highly coupled to JUnit as @hoisie said, and I will close this issue. You can feel free to reopen it if you have any question.
