### ISSUE TITLE
I am getting cannot access Font class file for android.graphics.fonts.Font not found

### ISSUE THREAD

**Issue by jobinj15** [robolectric/robolectric#6591]
### Description

Trying to use the following code and running the test file gives me "Cannot access Font class file for android.graphics.fonts.Font not found"

AlertDialog alertDialog = ShadowAlertDialog.getLatestAlertDialog();
ShadowAlertDialog shadowAlertDialog = shadowOf(alertDialog);

### Steps to Reproduce
1. Implement Roboelectric 4.5.1 
2. Create a test case with the below lines and run:

AlertDialog alertDialog = ShadowAlertDialog.getLatestAlertDialog();
ShadowAlertDialog shadowAlertDialog = shadowOf(alertDialog);

Reproducible on both test and AndroidTest

### Robolectric & Android Version
Roboelectric 4.5.1
Android 10
Gradle plugin version 4.1.2
Gradle version 6.5

### Link to a public git repo demonstrating the problem:
https://github.com/jobinj15/roboAndroidx

In the shared repo , to reproduce the issue , from the test folder [here](https://github.com/jobinj15/roboAndroidx/tree/main/app/src/test/java/com/example/androidxmigrate) , Run the file MainActivityTestJ in Android Studio

**Comment by utzcoz** [comment]
Hi @jobinj15 , you can upgrade your `compileSDK` and `targetSDK` to 29 and above to fix this problem. After that, you maybe encounter the problem related `AndroidTestEnvironment`, it is the problem you used the non exist `MyApplication` in your `AndroidManifest.xml`. You can create your `MyApplication`, and the problem related to `AndroidTestEnvironment` will disappear. Of course, you also should fix your tests in `MainActivityTestJ`.
Hi @hoisie , it is another problem that user uses low `compileSDK`, but `Robolectric` uses class added on higher SDK directly. The generated `Shadows.java` uses `Font` added from SDK 29 (https://developer.android.com/reference/android/graphics/fonts/Font) directly:
```java
  public static ShadowFontBuilder shadowOf(Font.Builder actual) {
    return (ShadowFontBuilder) Shadow.extract(actual);
  }
```

**Comment by jobinj15** [comment]
Thanks for the reply , I could get a step further with that . But then I get the error mentioned [here](https://github.com/robolectric/robolectric/issues/5307)

Is JDK 9 required to be able to use Roboelectric?

**Comment by utzcoz** [comment]
> Thanks for the reply , I could get a step further with that . But then I get the error mentioned [here](https://github.com/robolectric/robolectric/issues/5307)
> 
> Is JDK 9 required to be able to use Roboelectric?

Yes. From Android 10, `AOSP` uses JDK 9 to generate instrumented jar used by `Robolectric`.

**Comment by hoisie** [comment]
I believe Robolectric 4.4, combined with targeting SDK less than 29, works
with Java 8. The Android 29+ framework jars themselves require Java 9, so
there's really nothing we can do to support Java 8 in SDK 29 and above.

**Comment by hoisie** [comment]
We could try turning off shadowOf generation for ShadowFontBuilder (it doesn't any public APIs anyway, so it doesn't matter). However it would not really get you past the Java 9 issue,

**Comment by jobinj15** [comment]
Thanks a lot , Java 9 works . Closing the issue
