### ISSUE TITLE
UnitTest fail with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by leaves7984** [robolectric/robolectric#6596]
We are currently facing this NoSuchMethod Error when we want to create the unit test with Robolectric version 4.3.1 and Mockito version 2.18.3

Exceptions:
```
java.lang.NoSuchMethodError: 'void com.android.webview.chromium.WebViewChromium.<init>(com.android.webview.chromium.WebViewChromiumFactoryProvider, android.webkit.WebView, android.webkit.WebView$PrivateAccess, boolean)'
```

Here is the code we did:

```
mWebView = Mockito.spy(
            new WebviewChromium(
                mockWebViewChromiumProvider, webView, webView.new PrivateAccess(), false));
```
In BUILD.gn, we have included the `//android_webview/glue:glue_java` as dependency, we can successfully compile the code but it sounds like in the runtime, it refers to the another wrong jar, does someone know how to config the build file to use the correct jar or any ideas about how to solve this error?

**Comment by leaves7984** [comment]
I'm on Androidx Test 1.2.0, so the solution mentioned in the [previous ticket](https://github.com/robolectric/robolectric/issues/5092) doesn't help. I checked my open jdk version, the version is 8, but I didn't use the android studio and I use the terminal to build and run the test.

**Comment by hoisie** [comment]
Is this code in the Chromium tree? Unfortunately i have no context into how that integration works. This repo is for the Gradle/Maven version of Robolectric. Also 4.3 is over two years old.

Looks like you are missing the WebviewChromium constructor. My guess is that it's a classpath issue. Sorry I can't really help much here.

**Comment by leaves7984** [comment]
Ok, thanks for response, I will post it in the right place.

**Comment by utzcoz** [comment]
Close it because it looks like not related with Robolectric. Hi @leaves7984, you can reopen it freely if you find some clue related to Robolectric.
