### ISSUE TITLE
Accessing LocationManager fails with 4.6.1 using a robolectric test

### ISSUE THREAD

**Issue by mattinger** [robolectric/robolectric#6604]
### Description

I'm accessing a location manager in my fragment.  When upgrading from 4.5.1 to 4.6.1, I now get the following error:

```
Caused by: java.lang.ClassNotFoundException: android.location.GnssAntennaInfo$Listener
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:182)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:140)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:126)
```

downgrading all the org.robolectric dependencies back to 4.5.1 and the error goes away.

### Steps to Reproduce

TestFragment.kt:

```
class TestFragment: Fragment() {
    val locationManager by lazy {
        requireContext().getSystemService(Context.LOCATION_SERVICE) as LocationManager
    }

    override fun onResume() {
        super.onResume()
        locationManager.allProviders
    }
}
```

TestFragmentTest.kt:

```
@RunWith(RobolectricTestRunner::class)
@Config(sdk=[Build.VERSION_CODES.O])
class TestFragmentTest {
    @Test
    fun testLocation() {
        val scenario =
            FragmentScenario.launchInContainer(TestFragment::class.java, null, null)
        scenario.onFragment { fragment ->
            fragment.locationManager
        }

    }
}
```

### Robolectric & Android Version

Robolectric 4.6.1
Android 
  MinSdk = 24
  TargetSdk = 29
  CompileSdk = 29

### Link to a public git repo demonstrating the problem:

Code is in a private company repo.  I can create a sample project if needed.

**Comment by mattinger** [comment]
FYI:  This was produced with a minimal set of dependencies in a brand new android project

```
dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("androidx.core:core-ktx:1.5.0")
    implementation("androidx.appcompat:appcompat:1.3.0")
    implementation("com.google.android.material:material:1.3.0")
    implementation("androidx.constraintlayout:constraintlayout:2.0.4")
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.robolectric:robolectric:4.6.1")
    debugImplementation("androidx.fragment:fragment-testing:1.3.4")
    androidTestImplementation("androidx.test.ext:junit:1.1.2")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.3.0")
}
```

**Comment by utzcoz** [comment]
Hi @mattinger , thanks for reporting this problem. I can confirm it locally. The [`GnssAntennaInfo` is added from API 30](https://developer.android.com/reference/android/location/GnssAntennaInfo), and this commit [Update ShadowLocationManager with R APIs. ](https://github.com/robolectric/robolectric/commit/44d9a918abfe74c836747e732eb7ef29714b75a2) added it to `ShadowLocationManager`. If we set sdk less than R for your test with `LocationManager` usage, the test fails with the same reason. Hi @hoisie , it is another compatibility problem for tests with lower SDK.

**Comment by utzcoz** [comment]
Hi @mattinger , you can bump your `compileSdkVersion` and `targetSdkVersion` to 30 to avoid this problem before we fix it. This is my local configuration:
```groovy
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 24
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```
