### ISSUE TITLE
How to assert drawable in ImageView?

### ISSUE THREAD

**Issue by vidhithakrar** [robolectric/robolectric#6620]
I am using vector drawables in an ImageView and changing it on click. I have written a custom matcher which creates a bitmap from drawable and then compare them using `Bitmap.sameAs(other)` API. While running it on machine, it creates 0 pixel bitmap and hence it can be compared with wrong vector drawables as well. Is there any way to compare drawables on local?

The custom matcher looks like below:
```
fun withDrawableRes(@DrawableRes id: Int) =
    object : BoundedMatcher<View, ImageView>(ImageView::class.java) {
        override fun describeTo(description: Description) {
            description.appendText("has drawable resource: $id")
        }

        override fun matchesSafely(item: ImageView): Boolean {
            val expectedBitmap = item.context.getDrawable(id)?.toBitmap()
            val actualBitmap = item.drawable.toBitmap()
            return actualBitmap.sameAs(expectedBitmap)
        }

    }
```

Robolectric version: 4.5.1
Espresso version(used for assertions): 3.3.0

**Comment by utzcoz** [comment]
Hi @vidhithakrar , what about trying 4.6.1? The new version improved massive fidelity for Bitmap and BitmapFactory.

**Comment by vidhithakrar** [comment]
Thanks @utzcoz for the response. I tried with 4.6.1 and it is not working on it as well.

**Comment by utzcoz** [comment]
> Thanks @utzcoz for the response. I tried with 4.6.1 and it is not working on it as well.

Could you help to provide a minimized reproduce sample app for this problem?

**Comment by vidhithakrar** [comment]
Please find the sample [here](https://github.com/vidhithakrar/robolectric-image-drawable-test). The test is passing with wrong drawable, ideally it should fail.

**Comment by utzcoz** [comment]
> Please find the sample [here](https://github.com/vidhithakrar/robolectric-image-drawable-test). The test is passing with wrong drawable, where it should fail.

Thanks. I can confirm this problem with your sample app. The `Bitmap` pixels are both zero for `VectorDrawable`. Looks like there is problem of Robolectric to load `VectorDrawable`.

**Comment by utzcoz** [comment]
Hi @vidhithakrar , it's sorry that Robolectric doesn't support those asset drawable images defined with xml correctly, and it maybe need many work to support it. You can use Instrumentation test to test those related code on Android emulator or real Android device before Robolectric supports it correctly.

**Comment by vidhithakrar** [comment]
Ok, Thanks @utzcoz !

**Comment by EduardoDornel** [comment]
this works for me:

fun withDrawableOnImageView(expectedId: Int): Matcher<View?>? {
	return object : BoundedMatcher<View?, ImageView>(ImageView::class.java) {
		override fun matchesSafely(imageView: ImageView): Boolean {
			val drawable = ContextCompat.getDrawable(imageView.context, expectedId)
			return imageView.drawable.constantState == drawable?.constantState
		}

		override fun describeTo(description: Description) {
			description.appendText("with drawable: ")
			description.appendValue(expectedId)
		}
	}
}

**Comment by utzcoz** [comment]
> this works for me:
> 
> ```
> fun withDrawableOnImageView(expectedId: Int): Matcher<View?>? {
> 	return object : BoundedMatcher<View?, ImageView>(ImageView::class.java) {
> 		override fun matchesSafely(imageView: ImageView): Boolean {
> 			val drawable = ContextCompat.getDrawable(imageView.context, expectedId)
> 			return imageView.drawable.constantState == drawable?.constantState
> 		}
> 
> 		override fun describeTo(description: Description) {
> 			description.appendText("with drawable: ")
> 			description.appendValue(expectedId)
> 		}
> 	}
> }
> ```

Hi @vidhithakrar , if you can accept to compare drawable state only of `ImageView`, you can try @EduardoDornel 's implementation to avoid asset xml drawable pixel support problem temporarily.

**Comment by vidhithakrar** [comment]
Thanks @EduardoDornel and @utzcoz! It works as expected! :)
