### ISSUE TITLE
Can't use Robolectric with Android version 12 API 31 stable 31.0.0

### ISSUE THREAD

**Issue by Velinken** [robolectric/robolectric#6635]
**Can't use Robolectric with Android version 12 API 31 stable 31.0.0:**

### Description

failed to configure com.dinadurykina.eventtest.ui.fragment.FragmentViewModelTest.onToast: Package **targetSdkVersion=31 > maxSdkVersion=30**
java.lang.IllegalArgumentException: failed to configure com.dinadurykina.eventtest.ui.fragment.FragmentViewModelTest.onToast: Package targetSdkVersion=31 > maxSdkVersion=30
	at org.robolectric**.RobolectricTestRunner**.getChildren(RobolectricTestRunner.java:256)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:534)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:400)

### Steps to Reproduce

@RunWith(AndroidJUnit4::class)
@Config(manifest= Config.NONE)
class FragmentViewModelTest {

### Robolectric & Android Version

org.robolectric:robolectric**:4.6.1**
compileSdk 31
    **compileSdkVersion 31
    buildToolsVersion "31.0.0"**

### Note
 compileSdkVersion 30
    buildToolsVersion "30.0.3"
passed OK

### Link to a public git repo demonstrating the problem:
https://gist.github.com/Velinken/4dde3c79930104bd6dda255f4a140bd5
https://github.com/Velinken/EventTest

**How to run on API 31?**
Where to get the version from?

**Comment by hoisie** [comment]
Robolectric does not support the prerelease Android S. We will support it when it launches.

**Comment by igor-khrupin-life360** [comment]
@hoisie Android 12 is available. No more Android S.
<img width="739" alt="Screen Shot 2021-07-27 at 1 35 14 PM" src="https://user-images.githubusercontent.com/70171201/127223700-2dd6324b-ca90-4774-bd7d-76535a8e5166.png">

**Comment by muthuraj57** [comment]
Is there any way to at least work around the issue for now? I'm using splash screen jetpack library which needs the targetSdk to 31. But I can't run tests because of this issue.

**Comment by hoisie** [comment]
@muthuraj57 have you tried using `@Config(SDK=30)` in tests to fallback to SDK 30?

**Comment by muthuraj57** [comment]
I fixed the issue in the splash screen library usage by setting `compileSdk` to 31 and setting `targetSdk` as 30.

**Comment by kuzdu** [comment]
`@Config(sdk = [30])` did the trick 🙇‍♂️

**Comment by osrl** [comment]
I'm trying to run multiplatform common tests for android platform. `Config` annotation is not available on common tests. I had to set `targetSdk` to 30 but that's not ideal.

**Comment by chrisbanes** [comment]
> I'm trying to run multiplatform common tests for android platform. `Config` annotation is not available on common tests. I had to set `targetSdk` to 30 but that's not ideal.

Using `robolectric.properties` is the probably the easiest way for MP projects: http://robolectric.org/configuring/

**Comment by hoisie** [comment]
Re-opening for now, I am planning to do a 4.7-alpha-1 release with Android S support tomorrow. It will be a tricky release due to having to build the native SQLite libraries for Mac M1. I'll close it then.

**Comment by hoisie** [comment]
4.7-alpha-1 was just released, so people should be able to target SDK 31 (Android S) using `@Config(sdk=31)`. If there are any problems please file new issues :)

**Comment by utzcoz** [comment]
> 4.7-alpha-1 was just released, so people should be able to target SDK 31 (Android S) using `@Config(sdk=31)`. If there are any problems please file new issues :)

@Velinken Latest Robolectric 4.7.3 has stable SDK 31 supporting, I will close this issue. Feel free to file new issues as @hoisie said if you have any problem for SDK 31 supporting.

**Comment by DHosseiny** [comment]
Now, when robolectric works with target 33?
