### ISSUE TITLE
Databinding Unit Tests are failing with AGP 4.1.x or higher and Robolectric 4.6.x

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#6657]
### Description

Running tests with AGP 4.1.x, is causing preventing any DataBinding test from working as expected.  In general, it says it can't find the BR generated file, due to the following behavior change:

https://developer.android.com/studio/releases/gradle-plugin#library-unit-tests

### Steps to Reproduce

Any data binding test will fail.

### Robolectric & Android Version

4.6.1

### Link to a public git repo demonstrating the problem:

Unfortunately this is a private corporate repo, but should be easily producable with 4.2.x as they say they changed the behavior.

**Comment by utzcoz** [comment]
@kingargyle I saw your comment https://github.com/robolectric/robolectric/issues/3789#issuecomment-961162402 about databanding with Robolectric. Looks like https://issuetracker.google.com/issues/126775542#comment31 uses similar solution to fix databading with unit test. Could this solution fix this problem?

**Comment by kingargyle** [comment]
Yes, it should work:

kaptTest "androidx.databinding:databinding-compiler:4.1.x"

just replace with the version of AGP you are using.

**Comment by utzcoz** [comment]
@kingargyle Thanks for your confirmation.
