### ISSUE TITLE
ShadowMediaMuxer.writeSampleData behavior difference

### ISSUE THREAD

**Issue by monkeyswarm** [robolectric/robolectric#6676]
### Description

`ShadowMediaMuxer.writeSampleData(int trackIndex, @NonNull ByteBuffer byteBuf, @NonNull BufferInfo bufferInfo)`

has different behavior than its 'real' `MediaMuxer` equivalent. It seems that the real `MediaMuxer` will, based on `BufferInfo` offset and size, use an absolute data getter (ignoring the `ByteBuffer` position), wheras `ShadowMediaMuxer` uses a relative getter (which starts to read at the `ByteBuffer` position).

### Steps to Reproduce
Have real code under test like this (adapted from https://android.googlesource.com/platform/packages/apps/Gallery2/+/master/src/com/android/gallery3d/app/VideoUtils.java)

```
ByteBuffer dstBuf = ByteBuffer.allocate(512);
BufferInfo bufferInfo = new BufferInfo();

bufferInfo.offset = 0;
bufferInfo.size = extractor.readSampleData(dstBuf, 0);
muxer.writeSampleData(0, dstBuf, bufferInfo);
```

Note that at the last line, the `ByteBuffer` has position 512.
The `BufferInfo` has offset zero and size 512.

`MediaMuxer` (real class) will work just fine, as it reads the first (absolute, not relative) 512 bytes from the `ByteBuffer`.
`ShadowMediaMuxer` will not work, and will write all zeroes, since it attempts to read 512 bytes from the `ByteBuffer` **starting at position 512** (past the content).

### Robolectric & Android Version
Uses internal google top of tree, testing with `@Config(minSdk = LOLLIPOP)`

**Comment by utzcoz** [comment]
@monkeyswarm Thank you to report this problem. [After some analyzing](https://github.com/robolectric/robolectric/pull/6695#issue-727367684), I think current `ShadowMediaMuxer#nativeWriteSampleData` implementation doesn't process offset correctly. I sent a PR to fix it. It also needs related tests on official Emulator, and there is a related PR for it. I will rebase and modify it after that PR merged. So, the PR related to this problem will wait some time.

**Comment by hoisie** [comment]
Thanks, looking into this.

**Comment by utzcoz** [comment]
Hi @monkeyswarm , related change was merged, and you can check it when new version released.
