### ISSUE TITLE
ShadowCursorWindow allocates a large Object array on creation, which can lead to running out of memory

### ISSUE THREAD

**Issue by al-broco** [robolectric/robolectric#6704]
### Description

Short version: `ShadowCursorWindow` allocates a large array (~2 million entries) upon creation.

Long version: `ShadowCursorWindow` has an internal class `Data` with the constructor (line 240):

````
    public Data(String name, int cursorWindowSize) {
      this.name = name;
      this.rows = new ArrayList<Row>(cursorWindowSize);
    }
````

which allocates an `ArrayList` with initial capacity `cursorWindowSize` - which in turn is backed by a Java array of `Object` of size `cursorWindowSize`.

The `Data` constructor gets called from `ShadowCursorWindow.create` (line 368):

````
    public long create(String name, int cursorWindowSize) {
      long ptr = windowPtrCounter.incrementAndGet();
      dataMap.put(ptr, new Data(name, cursorWindowSize));
      return ptr;
    }
````

which in turn gets called from Android's `CursorWindow` constructor (skipping some calls here):

````
    public CursorWindow(String name) {
        this(name, getCursorWindowSize());
    }
````

where `getCursorWindowSize()` is implemented as

````
    private static int getCursorWindowSize() {
        if (sCursorWindowSize < 0) {
            // The cursor window size. resource xml file specifies the value in kB.
            // convert it to bytes here by multiplying with 1024.
            sCursorWindowSize = Resources.getSystem().getInteger(
                    com.android.internal.R.integer.config_cursorWindowSize) * 1024;
        }
        return sCursorWindowSize;
    }
````

where `config_cursorWindowSize` is defined as:

````
    <!-- When a database query is executed, the results returned are paginated
         in pages of size (in KB) indicated by this value -->
    <integer name="config_cursorWindowSize">2048</integer>
````

This means that the `cursorWindowSize` passed to the `Data` constructor is 2048 * 1024 = 2097152.

I believe this is a mistake. The `cursorWindowSize` is the pagination size (in bytes), and it does not make sense to reserve space for that many rows.

I believe changing the `Data` constructor to

````
    public Data(String name, int cursorWindowSize) {
      this.name = name;
      this.rows = new ArrayList<Row>();
    }
````

would be a performance improvement and decrease the risk of running out of memory. Let me know if you would be interested in a PR with this change.

### Steps to Reproduce

Create a test with an in-memory Room database and make a query to it to trigger the allocation.

Let me know if it would be helpful if I created a project with such a test.

### Robolectric & Android Version

Robolectric: 4.6.1.
targetSdkVersion: 30.

### Link to a public git repo demonstrating the problem:

See "Steps to Reproduce" above.

**Comment by hoisie** [comment]
Thanks for the awesome investigation. Please do send a PR for this change.
