### ISSUE TITLE
Database shuffled list (version 4.6)

### ISSUE THREAD

**Issue by denya568** [robolectric/robolectric#6708]
### Description
```SELECT id FROM table``` returns shuffled array with two items:
id = 2
id = 1

but table contains:
id = 1
id = 2

### Robolectric & Android Version
robolectric 4.6
android O_MR1 (api 27)

**Comment by hoisie** [comment]
This result comes directly from SQLite, Robolectric does not alter the results. If you want them ordered in a certain way you need to specify that in the query, e.g. "SELECT id FROM table ORDER BY id"

**Comment by denya568** [comment]
> This result comes directly from SQLite, Robolectric does not alter the results. If you want them ordered in a certain way you need to specify that in the query, e.g. "SELECT id FROM table ORDER BY id"

If I perform ``SELECT id FROM table`` request on real sqlite database, I receve:
id = 1
id = 2

Same (correct) result returns debugger in android studio.

I understand that ```ORDER BY id``` can solve my problem, but I think it's a robolectric's bug

**Comment by hoisie** [comment]
From https://www.sqlite.org/lang_select.html#orderby:

`If a SELECT statement that returns more than one row does not have an ORDER BY clause, the order in which the rows are returned is undefined. `

If you think it's a Robolectric bug, feel free to poke around in https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowSQLiteConnection.java and let me know what you find :) Robolectric leverages sqlite4java, you could also try using sqlite4java directly and seeing what you get.

**Comment by denya568** [comment]
> From https://www.sqlite.org/lang_select.html#orderby:
> 
> `If a SELECT statement that returns more than one row does not have an ORDER BY clause, the order in which the rows are returned is undefined. `
> 
> If you think it's a Robolectric bug, feel free to poke around in https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowSQLiteConnection.java and let me know what you find :) Robolectric leverages sqlite4java, you could also try using sqlite4java directly and seeing what you get.

Oh! I didn't know. Thank u so much! And sorry!
