### ISSUE TITLE
This Tool can't work on Java8

### ISSUE THREAD

**Issue by zouchanglin** [robolectric/robolectric#6713]
### Description
This Tool can't work on Java8，if to use this tool，must switchover my javaversion 8 to 9 or 11，error log：
[Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.
[Robolectric] WARN: Android SDK 30 requires Java 9 (have Java 8). Tests won't be run on SDK 30 unless explicitly requested.
![image](https://user-images.githubusercontent.com/29838710/133190514-4697b397-77c1-4e2f-b691-da4508b3246c.png)

**Comment by utzcoz** [comment]
@zouchanglin , it is a breaking change created by `Robolectric` to support Android 10. The more detailed information you can found here https://github.com/robolectric/robolectric/issues/5258. It is duplicated, and I will close it. If you have question about it, you can comment at https://github.com/robolectric/robolectric/issues/5258.

**Comment by hoisie** [comment]
It is not the Robolectric framework that requires Java 9+ for Q+, it is the Android framework impl itself. See https://github.com/robolectric/robolectric/issues/5258#issuecomment-658343587.

**Comment by zouchanglin** [comment]
I tried it again. The reason why it couldn’t run was that I set the running environment to the default JVM of Android Studio. Although it could run, there were still warnings, so I switched to JDK11 directly.

**Comment by utzcoz** [comment]
> I tried it again. The reason why it couldn’t run was that I set the running environment to the default JVM of Android Studio. Although it could run, there were still warnings, so I switched to JDK11 directly.

Bumping your JDK to 11 is recommend, because the AGP 7.x and Android Studio from Arctic Fox needs JDK 11 to developing and building Android app.
