### ISSUE TITLE
LocalUiController does not inject events to the correct Window

### ISSUE THREAD

**Issue by wesalvaro** [robolectric/robolectric#6741]
### Description

`LocalUiController` always selects the top-most `Window` to deliver `MotionEvent`s and `KeyEvent`s. The top-most `Window` is not the correct heuristic to use as it can be non-interactable. This creates confusing issues when interacting with the main application when a tooltip-like `PopupWindow` is showing. Events seem to simply disappear/never be delivered.

I would propose improving the heuristic in the `LocalUiController`. At least to take into account the `Window` flags (e.g. `FLAG_NOT_TOUCHABLE` and `FLAG_NOT_FOCUSABLE`). Ideally we could further look at which `Window` should receive the event; the `WindowManager.LayoutParams` do contain location and sizing information but that would require measuring the `Window` contents (as in the case of `WRAP_CONTENT`).

The current workaround is to:

1. Realize the problem
2. Verify the behavior is erroneous
3. Create one's own `UiController` that may look like:
    ```
    private class WorkaroundUiController(private val view: View) : UiController {
      override fun injectMotionEvent(event: MotionEvent?): Boolean {
        requireNotNull(event)
        view.rootView.dispatchTouchEvent(event)
        return true
      }
    
      override fun injectKeyEvent(event: KeyEvent?): Boolean {
        requireNotNull(event)
        view.rootView.dispatchKeyEvent(event)
        return true
      }
    
      override fun injectString(str: String?): Boolean {
        TODO("Not yet implemented")
      }
    
      override fun loopMainThreadUntilIdle() = idleMainLooper()
      override fun loopMainThreadForAtLeast(millis: Long) = idleMainLooper(millis, MILLISECONDS)
    }
    ```
4. Create one's own `ViewAction` that may look like:
    ```
    fun click() = viewAction("click in the view's window") {
      _, view ->
      ViewActions.click().perform(WorkaroundUiController(view), view)
    }
    ```

### Steps to Reproduce

1. Show a small, non-focusable, non-touchable `PopupWindow`.
2. Use Espresso to click on a view in the main application `Window`:
    ```
    onView(withId(R.id.foo)).perform(click())
    ```

Expected: Click is delivered to the main application `Window`
Observed: Click is delivered to the `PopupWindow`

The same can be said for a variety of situations.

### Robolectric & Android Version

Current Robolectric.  
Android Version does not apply.

### Link to a public git repo demonstrating the problem:

Internal b/199994449 has more details, discussion, and examples.

**Comment by hoisie** [comment]
👍 to adding some heuristics to LocalUiController to select a more appropriate window. @wesalvaro would you be able to send a PR for that change?

**Comment by wesalvaro** [comment]
lol. I'm not sure what's up with that copybara patch.  
Doesn't look like what I thought it would...

**Comment by utzcoz** [comment]
> lol. I'm not sure what's up with that copybara patch. Doesn't look like what I thought it would...

If you add your Google email to your GitHub account, I think the GitHub will show you as author. What I learnt from those copybara PRs is that it will copy and send a PR if internal has a commit, and it contains previous commits copied by copybara to `Robolectric` GitHub with PRs, that not been merged. So your related commit contains many changes that not you did. @hoisie will merge those PRs with sent sequence one by one, and you PRs will contain your change only when it is merged. For more details about copybara, I think @hoisie can provide more insights.

And @wesalvaro could you add `Fix: this issue link` to link that PR to this issue? When it is merged, this issue will be closed automatically.

**Comment by hoisie** [comment]
@wesalvaro sorry about that, the way we use Copybara is totally broken. The PRs from copybra are effectively meaningless, it displays the last N commits since the last time Google contributions are synced to GitHub. It is high on our TODO list to improve this situation.

**Comment by wesalvaro** [comment]
@utzcoz
Interesting! I do have _my_ email address setup on my account... Hmm...
I intentionally left off the `Fix` because I'd also like to try a more intelligent heuristic based on the size/location as well before calling this bug fixed. As-is with my tweak, it'll allow for a workaround on the side of the developer (having the correct flags set) but it's not a great final solution.

**Comment by utzcoz** [comment]
@wesalvaro https://github.com/robolectric/robolectric/commit/52cc2fd6832f723fc33530250501fbd328c6b1f6.patch from this commit message, it shows author is Googler <noreply@google.com>. Maybe it is a problem of copybara. If the author email is your linked emails at GitHub account, it will show you at GitHub commit page and other locations at GitHub.

**Comment by wesalvaro** [comment]
@utzcoz Maybe it's because that's a compound patch with more than just my change?

**Comment by utzcoz** [comment]
> @utzcoz Maybe it's because that's a compound patch with more than just my change?

Sorry, I don't know details about copybara-service. Maybe @hoisie can help explain this problem for you.

**Comment by utzcoz** [comment]
@wesalvaro Looks like related PR is merged. I will close this issue. If you have any problem about it, feel free to reopen it. Thanks.
