### ISSUE TITLE
test/res is not getting merged while running unit test

### ISSUE THREAD

**Issue by vidhithakrar** [robolectric/robolectric#6742]
If resource is overridden in test/res, it is not getting picked up while running the test with AndroidX.

Environment:
Robolectric : 4.6.1
AGP: 4.0.0
Android: 29

Is there any way to override the resource in test/res?

**Comment by utzcoz** [comment]
What about add following config to your `build.gradle`:

```groovy
android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
``` 

See official [Get Started](http://robolectric.org/getting-started/).

**Comment by vidhithakrar** [comment]
It is already there but still not working.

**Comment by utzcoz** [comment]
What about adding this directory to `sourceSet` directly:

```groovy
    sourceSets {
        test.resources.srcDirs += 'test/res or your real test directory`
    }
```

**Comment by vidhithakrar** [comment]
This also did not work. Will create a sample app and post a link here. Thanks!

**Comment by hoisie** [comment]
Closing until there is an app that demonstrates the problem.
