### ISSUE TITLE
Delete NO_REBUILD option in Robolectric's gradle

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#6753]

**Comment by Abdulrahman1890** [comment]
Can you please provide me more details about this issue

**Comment by utzcoz** [comment]
@Abdulrahman1890 The `NO_REBUILD` is gradle option added by Robolectric plugin to avoid rebuild module. Looks like it doesn't be used now. Maybe @hoisie can provide more information about it.

**Comment by Abdulrahman1890** [comment]
Hi @hoisie can you provide more information for me plz?

**Comment by Umesh-01** [comment]
I think @Abdulrahman1890 is not working on this issue. I would like to pick this, Can I @hoisie @utzcoz ??

**Comment by utzcoz** [comment]
@Umesh-01 no problem. Just resolving it locally and sending PR.

**Comment by hoisie** [comment]
You can see which files need to be modified:

```
$ git grep -l NO_REBUILD
buildSrc/src/main/groovy/org/robolectric/gradle/RoboJavaModulePlugin.groovy
```

And then just remove the NO_REBUILD references from that file.
