### ISSUE TITLE
ConfigurationChange doesn't follow documented Activity Lifecycle

### ISSUE THREAD

**Issue by hborders** [robolectric/robolectric#6754]
### Description
[`ActivityController#configurationChange` says](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/android/controller/ActivityController.java#L345-L355):
```
            // The order of onPause/onStop/onSaveInstanceState is undefined, but is usually:
            // onPause -> onSaveInstanceState -> onStop
            _component_.performPause();
            _component_.performSaveInstanceState(outState);
            if (RuntimeEnvironment.getApiLevel() <= M) {
              _component_.performStop();
            } else if (RuntimeEnvironment.getApiLevel() <= O_MR1) {
              _component_.performStop(true);
            } else {
              _component_.performStop(true, "configurationChange");
            }
```

But the [`Activity#onSaveInstanceState(Bundle)` docs](https://developer.android.com/reference/android/app/Activity#onSaveInstanceState(android.os.Bundle)) say:

> If called, this method will occur after [`onStop()`](https://developer.android.com/reference/android/app/Activity#onStop()) for applications targeting platforms starting with [`Build.VERSION_CODES.P`](https://developer.android.com/reference/android/os/Build.VERSION_CODES#P). For applications targeting earlier platform versions this method will occur before [`onStop()`](https://developer.android.com/reference/android/app/Activity#onStop()) and there are no guarantees about whether it will occur before or after [`onPause()`](https://developer.android.com/reference/android/app/Activity#onPause()).

Thus, Robolectric will call `onSaveInstanceState` incorrectly on API >= 28.

### Robolectric & Android Version

Robolectric 4.6.1
Android API 21 - 31

**Comment by utzcoz** [comment]
@hborders Thanks for reporting this problem. I saw related code for this restriction at https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/ActivityThread.java;l=5136-5163?q=ActivityThread.java&ss=android. I will send a PR for it.
