### ISSUE TITLE
Jetpack Compose Screenshot Tooling

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#6756]
I'm using Robolectric 4.5.1 to test my Jetpack Compose UI. Due to the nature of Compose Testing, one does not get access to a full-blown "view-alike" tree, but only a "semantic tree", that is built alongside with the actual visible elements. This semantic tree is not only used for testing, but also accessibility support, so testing in Compose is a little more like UIAutomator testing (in comparison to the whitebox-alike instrumented Espresso Testing what one is used to).

The semantic tree, as the name suggests, does not hold any visual information about what is seen on screen, no colors, no icons, nothing. So to properly test a Compose implementation, one has to reside on screen snapshotting, e.g. by utilizing [`SemanticsNodeInteraction.captureToImage()`](https://developer.android.com/reference/kotlin/androidx/compose/ui/test/SemanticsNodeInteraction#(androidx.compose.ui.test.SemanticsNodeInteraction).captureToImage()). This internally uses `PixelCopy.request()` to create an offscreen buffer of what's drawn on screen, after a draw call happened.

However, when called from Robolectric, this`PixelCopy` is never triggered, as it fails to register the "first" draw on screen, i.e. `drawDone` is never `true` (tested with sdk = 28 and sdk = 29):

```kotlin
 val decorView = windowToCapture.decorView
    handler.post {
        if (Build.VERSION.SDK_INT >= 29 && decorView.isHardwareAccelerated) {
            FrameCommitCallbackHelper.registerFrameCommitCallback(decorView.viewTreeObserver) {
                drawDone = true
            }
        } else {
            decorView.viewTreeObserver.addOnDrawListener(object : ViewTreeObserver.OnDrawListener {
                var handled = false
                override fun onDraw() {
                    if (!handled) {
                        handled = true
                        handler.post {
                            drawDone = true
                            decorView.viewTreeObserver.removeOnDrawListener(this)
                        }
                    }
                }
            })
        }
        decorView.invalidate()
    }
```
(`WindowCapture.android.kt` from `androidx.compose.ui:ui-test:1.0.1`)

On previous occasions I tried to use `PixelCopy` myself to capture screen contents within Robolectric, which always resulted in a black screen.

Is there any support for screenshot making on the horizon for Robolectric or is this impossible to do?

**Comment by Debdutta-Panda** [comment]
It is 4.9 already, issue not fixed right?

**Comment by yschimke** [comment]
Now supported ?

https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10-alpha-1

**Comment by utzcoz** [comment]
@realdadfish From Robolectric 4.10, it is possible to use Robolectric as Jetpack Compose Screenshot Tooling. There are some community work: https://github.com/takahirom/roborazzi and https://github.com/sergio-sastre/AndroidUiTestingUtils.
