### ISSUE TITLE
Fragile reference to private synthetic this$ field

### ISSUE THREAD

**Issue by cushon** [robolectric/robolectric#6757]
The following code is using reflection to access a field with a name starting with `this$`:

https://github.com/robolectric/robolectric/blob/bf1b23e594f733fdb88f52adddd095c5d990d178/shadows/framework/src/main/java/org/robolectric/shadows/ShadowResources.java#L311

The OpenJDK javac generates private synthetic fields with names starting with `this$` as an implementation detail of inner classes. In the future that implementation detail may be changing, and the `this$` field will no longer be generated for all inner classes. For more information about the proposed change, see: https://bugs.openjdk.java.net/browse/JDK-8271717

Please consider alternatives to accessing the private synthetic `this$` field to ensure this code continues to work after the change. For example, consider passing an explicit copy of the enclosing instance to code that needs access to it, or adding an explicit getter to the inner class.

For example, given:

```java
class Outer {
  int x;
  class Inner1 {
    int f() {
      return x;
    }
  }
  class Inner2 {
    void g() {
      System.err.println("hello");
    }
  }
}
```

Currently `Inner` and `Inner2` both have a synthetic field named `this$0` that stores a reference to `Outer`.

In the future the implementation detail might be changing to omit the field from classes that don't reference the enclosing instance. So in the example, `Inner1` would still have the synthetic field because it accesses the field `x` in the enclosing instance `Outer`. However `Inner2` would no longer have a synthetic field, because it doesn't access any state from its enclosing instance.

**Comment by utzcoz** [comment]
> Note that most of the Android jars that Robolectric instruments have been compiled many years ago, and future Android jars will likely be compiled with javac that is many versions behind the one that will incorporate the this$0 change. So for all intents and purposes it may be several years until Robolectric sees a jar without this$0 references.

What about using `Resources.Theme#getResources()` to replace reflection implementation with `this$0` for SDK 21+, and keeping reflection with `this$0` for old SDKs?
