### ISSUE TITLE
How can I test some classes which are weaved by transformers?

### ISSUE THREAD

**Issue by williamfzc** [robolectric/robolectric#6762]
Hi there, what a powerful tool

We build a gradle plugin for weaving some classes in tranform tasks, with ASM.
For example:

before:

```java
public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView((int) R.layout.activity_main);
    }
}
```

after:

```java
public void onCreate(Bundle savedInstanceState) {
        SOME_METHOD_CALL();
        super.onCreate(savedInstanceState);
        setContentView((int) R.layout.activity_main);
    }
}
```

And our goal is testing those methods we have injected in transformers.

I have no idea about what i can do. 
This PR (https://github.com/robolectric/robolectric/pull/1240) looks like something I want but it looks deprecated for a long time.

Thanks

**Comment by williamfzc** [comment]
Thank u guys. I will explain what I have done here.

1. Write a gradle plugin and apply it in app build.gradle 

```gradle
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

// APPLY
apply plugin: 'callreco'


android {
    ......
```

2. And this plugin will register a transformer:

```gradle
class CrGradlePlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.extensions.findByType(TestedExtension::class.java)?.let { ext ->
            println("found ext in ${target.project.path}")
            ext.registerTransform(CrTransformer(target))
        }
......
```

3.  This transformer will do the regular things just like the other ones (just like what jacoco-plugin does). We get a weaved apk after build. I decompiled it with jadx, everything inside looks fine.

![image](https://user-images.githubusercontent.com/13421694/136830261-1c151677-311f-49c2-b074-e8f9fd4668ce.png)

After that, I decided to create some test cases in CI and found this problem. I tried to print all its methods out:

```kotlin
@RunWith(AndroidJUnit4::class)
@Config(manifest = Config.NONE)
class ExampleUnitTest {
    @Test
    fun clickingButton_shouldChangeResultsViewText() {
        MainActivity::class.java.declaredMethods.forEach {
            println(it.toGenericString())
        }
    }
}
```

and found nothing about my injected code. This class looks just like the origin one.

So I guess:

- maybe transformer did not work in test?
- or it works but robolectric still used the origin one?

**Comment by wangprofessor** [comment]
me too

**Comment by utzcoz** [comment]
Anyone wants to test classes generated by compiler with Gradle, please check https://github.com/robolectric/robolectric/issues/6762#issuecomment-940219447. Also you might need to enable `includeAndroidResoures` to let AGP generate test apk with necessary resources if your classes need. If it doesn't work, feel free to reopen this issue and attach your reproducible app/sample.
