### ISSUE TITLE
HttpUrlConnection not shadowed & fails on PATCH requests

### ISSUE THREAD

**Issue by phil-brown** [robolectric/robolectric#6769]
### Description
I am working on implementing integration tests against real server endpoints. The app code uses HttpUrlConnection, which is a java class. This class does not support PATCH requests. Android libcore provides its own implementation of HttpUrlConnection that replaces this java version. So when I run the test as an android instrumentation test without robolectric, it works as expected.

### Steps to Reproduce

1. Write Android code that creates a connection to a URL using the PATCH method.
2. Verify that it works fine either running the app or by writing an AndroidTest to verify.
3. Move the test to the test/ directory and configure for Robolectric.
4. Observe that the robolectric test fails, because PATCH is not a supported HTTP method.

### Robolectric & Android Version

Android: compile(31), minSdk(16), targetSdk(31)
Robolectric: 4.5.1

**Comment by utzcoz** [comment]
@phil-brown you can check https://github.com/google/ExoPlayer/commit/df0e89c1678ff0dda00bb187be05b8198bd31567 to migrate your `HttpURLConnection` related tests that need `PATCH` request to instrumentation tests under `androidTest`.

**Comment by utzcoz** [comment]
@phil-brown IMO Robolectric can't do much for PATCH request, and sorry for that. Feel free to reopen it you think we can discuss more about it. cc /@hoisie.
