### ISSUE TITLE
Robolectric 4.5.1 ignores unit tests targetting API29

### ISSUE THREAD

**Issue by ymikorcmy** [robolectric/robolectric#6783]
### Description
Hi. I'm using Robolectric 4.5.1 to run unit tests from minSdk = 26 to maxSdk = 29, but the result shows tests targeting 29 are ignored. 

![image](https://user-images.githubusercontent.com/56063807/138154854-4c79e500-5bb1-441f-b140-23a71b296df5.png)

I've upgraded to JDK11 but the issue is still observed. 

Any help would be appreciated!

**Comment by christianb** [comment]
@hoisie Why was it colsed? Can you please explain the solution to this problem.
