### ISSUE TITLE
Supporting nativeruntime building for Windows

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6791]
This issue is used to track Windows building support for nativeruntime. 

Previous discussions are here:
https://github.com/robolectric/robolectric/issues/6311#issuecomment-942452585
https://github.com/robolectric/robolectric/issues/6311#issuecomment-942479536
https://github.com/robolectric/robolectric/issues/6311#issuecomment-942575846
https://github.com/robolectric/robolectric/issues/6311#issuecomment-950137940
https://github.com/robolectric/robolectric/issues/6311#issuecomment-950179187
https://github.com/robolectric/robolectric/issues/6311#issuecomment-950181749

**Comment by utzcoz** [comment]
Looks like there are many type errors with MSVC tools. I am trying to finding headers of Windows version for some files.

**Comment by utzcoz** [comment]
> Looks like there are many type errors with MSVC tools. I am trying to finding headers of Windows version for some files.

I have fixed some building errors with using Windows header or redefining some data types based on Windows data types. There is one difficult thing to resolved: `__attribute__` and `__attribute`. The `String8.h` use the first one and `CursorWindow.h` uses the second. I have searched some articles, and it is difficult to find equivalent thing on Windows. The `String8.h` uses `__attribute__` for format method, and I can comment those usages for building. But I don't know how to replace `__attribute` for `CursorWindow.h`. Sorry, I'm not familiar with C++ too much.

**Comment by utzcoz** [comment]
Looks like 

```C++
#ifdef __GNUC__
#define PACK( __Declaration__ ) __Declaration__ __attribute__((__packed__))
#endif

#ifdef _MSC_VER
#define PACK( __Declaration__ ) __pragma( pack(push, 1) ) __Declaration__ __pragma( pack(pop))
#endif
```
can fix `__attribute(pack)` error on Windows.

Looks like

```C++
#if defined(_MSC_VER)
#define DLL_PUBLIC __declspec(dllexport) // Note: actually gcc seems to also supports this syntax.
#else
#if defined(__GNUC__)
#define DLL_PUBLIC __attribute__ ((dllexport))
#endif
```
can fix normal `__attribute__` problems. I can continue to fix other errors now, at least.

**Comment by utzcoz** [comment]
The sad thing is that `external/sqlite` uses header files not supported by Windows:

```
your-robolectric-directory\robolectric\nativeruntime\external\sqlite\android\sqlite3_android.cpp(22): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [your-robolectric-directory\nativeruntime\build\cpp\androidsqlite.vcxproj]
```

I think it means we can't use MSVC tools to build nativeruntime, because we can modify our added C++ code, but we can't modify `external/sqlite` source code(I know we can add it to our source code directly and modify it, but I don't think it is a good choice, and we should avoid it). :(

**Comment by utzcoz** [comment]
@hoisie `FindICU` of cmake doesn't work correctly for Windows 10 64bit. What I did to make it work is to download icu4c-70_1-Win64-MSVC2019.zip from https://github.com/unicode-org/icu/releases/tag/release-70-1, unzip it and add it directly to system/user environment with name `ICU_ROOT`. I don't need to set `ICU_LIBRARY` or other components `NoNeeded` anymore. At least, it works when I use mingw + cmake. Looks like there are some headers need to be wrapped for different host OS.

**Comment by utzcoz** [comment]
> @hoisie `FindICU` of cmake doesn't work correctly for Windows 10 64bit. What I did to make it work is to download icu4c-70_1-Win64-MSVC2019.zip from https://github.com/unicode-org/icu/releases/tag/release-70-1, unzip it and add it directly to system/user environment with name `ICU_ROOT`. I don't need to set `ICU_LIBRARY` or other components `NoNeeded` anymore. At least, it works when I use mingw + cmake. Looks like there are some headers need to be wrapped for different host OS.

What I'm facing is unresolved `sys/mman.h`, there is article to say it not available on Windows(https://www.quora.com/How-do-I-solve-the-error-sys-mman-h-No-such-file-or-directory-in-Windows). It is recommend to use cygwin. If I can't find alternative for `sys/mman.h`, I must switch to the cygwin, the first try. :(

**Comment by hoisie** [comment]
What is trying to include sys/mman.h? Is it SQLite or libicu?

**Comment by utzcoz** [comment]
> What is trying to include sys/mman.h? Is it SQLite or libicu?

It's here https://github.com/robolectric/robolectric/blob/master/nativeruntime/cpp/androidfw/CursorWindow.cpp#L30.

**Comment by hoisie** [comment]
This approach that CursorWindow takes will not work for Windows. We will probably need a separate implementation for Windows. If you comment that out does it progress?

**Comment by utzcoz** [comment]
> This approach that CursorWindow takes will not work for Windows. We will probably need a separate implementation for Windows. If you comment that out does it progress?

I think it's not. I can't comment include out directly, because it is used by code. And I think tests will fail, if I comment `CursorWindow`  source code out.  Anyway I will give it a try today.

**Comment by hoisie** [comment]
I think the current CursorWindow implementation is overkill for the purposes of Robolectric. It does not really need to use a shared memory buffer. I think the design is meant for multi-process support in Android (i.e. sharing a cursor across processes).

One option is to potentially use something more minimal for CursorWindow (e.g. an in-memory buffer)?

**Comment by utzcoz** [comment]
> I think the current CursorWindow implementation is overkill for the purposes of Robolectric. It does not really need to use a shared memory buffer. I think the design is meant for multi-process support in Android (i.e. sharing a cursor across processes).
> 
> One option is to potentially use something more minimal for CursorWindow (e.g. an in-memory buffer)?

Looks like `ashmem` only used by `CursorWindow`. If we can use in-memory buffer for `CursorWindow`, we also can delete `ashemem` from our dependencies too.

**Comment by utzcoz** [comment]
After applying my dirty in-memory data for CursorWindow, the building can go further, and been blocked by strerror_r not found problem.

**Comment by utzcoz** [comment]
> After applying my dirty in-memory data for CursorWindow, the building can go further, and been blocked by strerror_r not found problem.

I can following patch to fix this problem by following https://dev.gnupg.org/rEcd49ee71887cb2e7f2ca422fbc5c28f4bd92b3ca:

```
+#ifdef _WIN32
+static int
+strerror_r (int no, char *buf, size_t buflen)
+{
+  return strerror_s (buf, buflen, no);
+}
+#endif
```
Looks like `robo_android_database_SQLiteConnection.cpp` also use `sys/mman.h`. I will try to use in-memory data for it to remove `sys/mman.h` too.

**Comment by utzcoz** [comment]
Okay, I should build new libicu on Windows firstly. The Window's building document of icu says it needs Microsoft C++, and its CI script(https://github.com/unicode-org/icu/blob/main/.ci-builds/.azure-pipelines.yml#L467-L500) shows that maybe we should use msys to run MinGW to build icu on Windows.

**Comment by hoisie** [comment]
I may have some time this week to set up aa Windows machine and help out with this.

**Comment by utzcoz** [comment]
> I may have some time this week to set up a Windows machine and help out with this.

Thanks. I'm sorry, this week is also busy to come back to this problem. I have pushed current progress to https://github.com/robolectric/robolectric/pull/6801. It needs mingw environment on Windows machine. After mingw installed, we should use mingw to install gcc and g++ as building tools. If cmake says it can't find build tools for mingw, we should add gcc and g++ installed by mingw to Windows' system environment named with paramenters cmake needs for building tools.

**Comment by hoisie** [comment]
I spent today trying to get this working in Windows, and I managed to get it building. However, when I try to load the dll, I get the following error:

```
org.robolectric.plugins.SQLiteModeConfigurerClassTest > shouldUseRealisticShadows[17] FAILED
    java.lang.UnsatisfiedLinkError: C:\Users\hoisie\AppData\Local\Temp\6454301322212969560robolectric-nativeruntime.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.robolectric.nativeruntime.NativeRuntimeLoader.ensureLoaded(NativeRuntimeLoader.java:40)
        at org.robolectric.nativeruntime.NativeRuntimeLoader.<clinit>(NativeRuntimeLoader.java:20)
        at org.robolectric.nativeruntime.CursorWindowNatives.<clinit>(CursorWindowNatives.java:29)
        at org.robolectric.shadows.ShadowNativeCursorWindow.nativeCreate(ShadowNativeCursorWindow.java:20)
        at android.database.CursorWindow.nativeCreate(CursorWindow.java)
        at android.database.CursorWindow.__constructor__(CursorWindow.java:102)
        at android.database.CursorWindow.<init>(CursorWindow.java)
        at org.robolectric.plugins.SQLiteModeConfigurerClassTest.shouldUseRealisticShadows(SQLiteModeConfigurerClassTest.java:49)
```

When I look at the dll dependencies, I get that there are a bunch of missing shared library dependencies:

![image](https://user-images.githubusercontent.com/125547/144353904-e46310da-5e4f-418c-b139-dffca0558908.png)

This is strange because I try to static link everything, but for some reason MinGW doesn't seem to do the static linking.

**Comment by utzcoz** [comment]
https://stackoverflow.com/questions/13768515/how-to-do-static-linking-of-libwinpthread-1-dll-in-mingw looks like there are some link options we can try.

**Comment by hoisie** [comment]
Interesting, thanks for sharing that post.

FYI this is my WIP branch:
https://github.com/robolectric/robolectric/compare/master...hoisie:test-windows?expand=1

I tried some of those static linking options and nothing seemed to work so far.

**Comment by hoisie** [comment]
OK this is interesting:

seems like the library is loading now, despite me seeing undefined library references.

I am seeing:
```
org.robolectric.plugins.SQLiteModeConfigurerClassTest > shouldUseRealisticShadows FAILED
    android.database.CursorWindowAllocationException: Could not allocate CursorWindow '2' of size 2097152 due to error -2.
        at org.robolectric.nativeruntime.CursorWindowNatives.nativeCreate(Native Method)
        at org.robolectric.shadows.ShadowNativeCursorWindow.nativeCreate(ShadowNativeCursorWindow.java:20)
        at android.database.CursorWindow.nativeCreate(CursorWindow.java)
        at android.database.CursorWindow.__constructor__(CursorWindow.java:141)
        at android.database.CursorWindow.<init>(CursorWindow.java)
        at org.robolectric.plugins.SQLiteModeConfigurerClassTest.shouldUseRealisticShadows(SQLiteModeConfigurerClassTest.java:49)
```

**Comment by utzcoz** [comment]
>     android.database.CursorWindowAllocationException: Could not allocate CursorWindow '2' of size 2097152 due to error -2.

Looks like it is problem related to code that removed `mmap`.

**Comment by hoisie** [comment]
Yeah, it does seem like it's related to the in-memory CursorWIndow.

This exception is coming from native code -- which is progress! Seems like those undefined library references were spurious? Anyway I can take a closer look tomorrow.

**Comment by hoisie** [comment]
Good news, I got some CursorWindow tests passing, but some SQLiteDatabase tests fail with the error:

```
org.robolectric.shadows.SQLiteDatabaseTest > testExecSQLInsertNull FAILED
    android.database.sqlite.SQLiteException: not an error (code 0 SQLITE_OK): Could not register Android SQL functions.
        at org.robolectric.nativeruntime.SQLiteConnectionNatives.nativeOpen(Native Method)
        at org.robolectric.shadows.ShadowNativeSQLiteConnection.lambda$nativeOpen$0(ShadowNativeSQLiteConnection.java:30)
        at app//org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
        at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:26)
        at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:48)
        at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:807)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:799)
        at org.robolectric.shadows.SQLiteDatabaseTest.openOrCreateDatabase(SQLiteDatabaseTest.java:1005)
        at org.robolectric.shadows.SQLiteDatabaseTest.setUp(SQLiteDatabaseTest.java:40)

```

I have a feeling this is related to ICU :(

**Comment by hoisie** [comment]
Something else to consider -- on Windows, the `make` that comes with msys has issues w/ cmake. You cannot run make twice due to the error: `libcutils/CMakeFiles/cutils.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.`. I may switch to ninja and see if that works. Perhaps we can switch everything to Ninja.

**Comment by utzcoz** [comment]
> Oh yeah, ninja works much better

That's cool. I don't know the real reason that I don't try ninja.

**Comment by utzcoz** [comment]
@hoisie could you share your config for icu on Windows?

**Comment by hoisie** [comment]
I believe it was `./runConfigureICU MinGW --enable-static --prefix=$HOME/icu-bin`

**Comment by hoisie** [comment]
Then I pass ICU_ROOT_DIR=$HOME/icu-bin when I run cmake

**Comment by utzcoz** [comment]
> I believe it was `./runConfigureICU MinGW --enable-static --prefix=$HOME/icu-bin`

I can run it directly on `msys2` environment at `icu4c/source`. But it doesn't work correctly with `commandline` from `build.gradle`. Looks like we need to pass `msys2` related environment for gradle.

**Comment by hoisie** [comment]
We may be able to run
`msys2_shell.cmd -mingw64 -c "runConfigureICU"`

Source: https://stackoverflow.com/questions/47438779/executing-a-script-in-msys2-mingw

**Comment by utzcoz** [comment]
> We may be able to run `msys2_shell.cmd -mingw64 -c "runConfigureICU"`
> 
> Source: https://stackoverflow.com/questions/47438779/executing-a-script-in-msys2-mingw

I can run all `gradlew` command at `msys2-mingw64` shell window without adding `msys2_shell.cmd` to gradle's `commandline`.

**Comment by utzcoz** [comment]
> Yeah, it does seem like it's related to the in-memory CursorWIndow.
> 
> This exception is coming from native code -- which is progress! Seems like those undefined library references were spurious? Anyway I can take a closer look tomorrow.

Does it related to `ashmem_create_region`? I am facing this problem, and the invoking of `ashmem_create_region` gives me a errno.

**Comment by utzcoz** [comment]
> > Yeah, it does seem like it's related to the in-memory CursorWIndow.
> > This exception is coming from native code -- which is progress! Seems like those undefined library references were spurious? Anyway I can take a closer look tomorrow.
> 
> Does it related to `ashmem_create_region`? I am facing this problem, and the invoking of `ashmem_create_region` gives me a errno.

Looks like it is related to temp file name pattern. I removed `/tmp/` from temp file name, the `mktemp` works fine.

**Comment by utzcoz** [comment]
Related PRs including CI job with cache are merged, so this issue can be closed. The left things about improving CI scripts and updating wiki for SNAPSHOT  can be done with new issues.
