### ISSUE TITLE
Calling methods of AccountManager leads to NPE -> service is null

### ISSUE THREAD

**Issue by ljanzik** [robolectric/robolectric#680]
I tried to test a AbstractThreadedSyncAdapter, therefore I need a AccountManager instance but when I call a method of AccountManager (e.g. getPassword or addAccountExplicitly) I get a NullPointerException in line 308 (android 4.1.2_r1) of AccountManager

return mService.getPassword(account);

so it seems the service is null in Robolectric

I tried to initialize AccountManager like this: AccountManager.get(Robolectric.application);

**Comment by jaredsburrows** [comment]
@coreydowning @ljanzik Is this still the case? I am getting NPEs from `AccountManager.get(this)`.

**Comment by hidroh** [comment]
I'm using `ShadowAccountManager` in my tests and it's working fine.

**Comment by jaredsburrows** [comment]
@coreydowning @ljanzik @hidroh Yes. I should have been more clear. In my `onResume`, I have `accountManager.addOnAccountsUpdatedListener(this, null, true);`. The robolectric tests fail with a `NullPointerException` in the `onPause` when I call `accountManager.removeOnAccountUpdatedListener(this);`. I see your project: https://github.com/hidroh/materialistic is not using that method.

**Comment by hidroh** [comment]
Ah yes, `ShadowAccountManager` does not have `removeOnAccountUpdatedListener()`. I only add listener in `Application.onCreate()` so I never remove it.
