### ISSUE TITLE
Support native SQLite in the SNAPSHOTS repo

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#6803]

**Comment by hoisie** [comment]
@mreichelt what platform are you developing on? Linux, or Mac? It would be easy to get native SQLite in snapshots up and running in Linux-only mode for now. Supporting Mac would be more complex as it would involve coordinating GitHub Actions artifacts.

**Comment by mreichelt** [comment]
Locally we use Mac, on CI we use Linux. So I guess we need both 😅

**Comment by hoisie** [comment]
There is actually light at the end of the tunnel for this issue.

The way that native code will be built for Robolectric will be significantly different shortly.

Robolectric will soon support native graphics (i.e. use native Android libraries for rendering, such as Skia/Minikin). Because of this, building the native libraries used by Robolectric will happen in a custom AOSP branch, and those native artifacts will be released and versioned separately on Maven.

This means that GitHub actions won't be responsible for building native code any more, so it will significantly reduce the complexity of the GitHub actions workflows. This will make it a lot easier to publish to SNAPSHOTS and GitHub actions will only be building Java code. The native artifacts will already be built by a separate process in AOSP.

**Comment by mreichelt** [comment]
That sounds amazing! Can't wait for the new changes to arrive :)
Let's see how we'll work around in the meantime. Maybe we just hold off of using the new API goodies for now, until the latest stable has shipped.

Thank you very much for the detailed feedback! 🙂

**Comment by hoisie** [comment]
@mreichelt are there some changes in SNAPSHOTS that you'd like to use? We can also do a minor release.

**Comment by mreichelt** [comment]
The new Bluetooth Gatt APIs are interesting to us - thanks for asking :)

**Comment by utzcoz** [comment]
@mreichelt Could you post specific commits at https://github.com/robolectric/robolectric/discussions/7864?

**Comment by mreichelt** [comment]
@utzcoz Thanks! The commit we'll need seems to be:
https://github.com/robolectric/robolectric/commit/a79467937408eb23287ae971dd9fb4bdd13ce58a

**Comment by utzcoz** [comment]
@hoisie I think we can close this issue now.

**Comment by utzcoz** [comment]
@hoisie We don't build native SQLite from GitHub Actions now. We can close this issue and focus on normal snapshot updating.
