### ISSUE TITLE
Ability to detect non-Android-friendly libraries?

### ISSUE THREAD

**Issue by jkwatson** [robolectric/robolectric#6804]
### Description
I work on an Android library that uses other libraries. Occasionally those libraries will accidentally include classes that are not available on Android (such as `java.lang.ClassValue`). I had hoped that the robolectric runner would allow me to write unit tests that would make sure that those libraries will function correctly, but it appears that usage (for example) of `java.lang.ClassValue` does not make the tests fail, even when targeting older API versions.

Is this something that is possible with robolectric? Is it a feature that could be added somehow?

**Comment by hoisie** [comment]
This seems like something that the Android Lint tool is designed to address.

Out of curiosity can you provide a snippet of code that works in the JVM but not with Android Java core classes (libcore)?

**Comment by jkwatson** [comment]
> This seems like something that the Android Lint tool is designed to address.

Will the lint tool find these things in libraries I depend on, not just in my own code? AnimalSniffer will also suss this out in the source library, but I was hoping to put a check in my own app code to catch the issue when it happens upstream of me.
 
> Out of curiosity can you provide a snippet of code that works in the JVM but not with Android Java core classes (libcore)?

On API level 21, there are many such snippets, that use CompletableFuture, or ClassValue. I was bit, in particular, by this bit in the OpenTelemetry instrumentation api: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/RuntimeVirtualFieldSupplier.java#L42-L55

**Comment by hoisie** [comment]
To me this sounds slightly out of scope for Robolectric. 

I generally see Robolectric as responsible for two things:

1) Instrumenting the Android framework JARs to support being run on the JVM and support shadowing
2) Providing useful testing APIs that are otherwise not available from public Android APIs

Also, Robolectric does not analyze or instrument app and test code by default (only Android framework code).

When it comes to validating app and library code I could see a separate tool being used here.

**Comment by jkwatson** [comment]
> When it comes to validating app and library code I could see a separate tool being used here.

Do you know of anything that exists today for this? I'd just like to find problems at build time, where possible, rather than having to wait for runtime for things to fail. :)

**Comment by hoisie** [comment]
Sorry I am not aware of such as tool. I'd imagine that it's something that could be caught by Android Studio when APKs are packaged and built. There's a step in the build where all the Java classes are converted to dex format. That seems like the best place to surface issues like this.

**Comment by jkwatson** [comment]
> Sorry I am not aware of such as tool. I'd imagine that it's something that could be caught by Android Studio when APKs are packaged and built. There's a step in the build where all the Java classes are converted to dex format. That seems like the best place to surface issues like this.

ok, thanks. Yes, the dexing step does catch some things already. I wonder if my particular issue with ClassValue is just something that's missing from that bit in the AGP? 

Anyway, feel free to close this is you think this is never something robolectric will attempt to provide. 👍🏽

**Comment by utzcoz** [comment]
Hi @jkwatson , I also think lint is a good choice for your purpose as @hoisie said at https://github.com/robolectric/robolectric/issues/6804#issuecomment-956329697. Looks like current lint rules don't cover this situation, but you can try to write your custom lint rules for your purpose. There are some useful links about link tool and how to write custom lint rules: https://developer.android.com/studio/write/lint https://github.com/googlesamples/android-custom-lint-rules http://tools.android.com/tips/lint/writing-a-lint-check. I will close this issue, and please feel free to reopen it if you have any question.

**Comment by jkwatson** [comment]
I don't see that Android lint has any way to examine the classes in *dependent libraries*, so I'm not sure it's really the right tool for the job, but I accept that robolectric also isn't the right tool. Thanks for the thoughts.

**Comment by hoisie** [comment]
I also want to mention that this issue has an element of the halting problem associated with it. For instance, let's say that the opentelemetry library has code like this:

```
if (System.getProperty("java.vm.name", "").toLowerCase(Locale.US).equals("dalvik")) {
 // android-specific logic
} else {
 // logic that uses ClassValue
}
```

So it would be technically possible to have class files that reference ClassValue but not actually use them. Having a tool figure out if that logic gets used seems to reduce to the halting problem :)

**Comment by utzcoz** [comment]
> I don't see that Android lint has any way to examine the classes in dependent libraries

`lintOptions` has a parameter called `checkDependencies`, used to check dependencies(https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/LintOptions):

```
         // Normally lint will analyze all dependencies along with each module; this ensures
         // that lint can correctly (for example) determine if a resource declared in a library
         // is unused; checking only the library in isolation would not be able to identify this
         // problem. However, this leads to quite a bit of extra computation; a library is
         // analyzed repeatedly, for each module that it is used in.
         checkDependencies false
```
From the comment, looks like it is used to analyze dependencies' resource. Maybe it can be modified for source code too. Just maybe.

**Comment by jkwatson** [comment]
> I also want to mention that this issue has an element of the halting problem associated with it. For instance, let's say that the opentelemetry library has code like this:
> 
> ```
> if (System.getProperty("java.vm.name", "").toLowerCase(Locale.US).equals("dalvik")) {
>  // android-specific logic
> } else {
>  // logic that uses ClassValue
> }
> ```
> 
> So it would be technically possible to have class files that reference ClassValue but not actually use them. Having a tool figure out if that logic gets used seems to reduce to the halting problem :)

This is precisely why I was interested in a runtime tool, not a build/compile time tool. If an app or library has good unit test coverage, a runtime tool that mimics in some way the Android runtime environment would fail when running into cases that weren't properly implemented, or used Android-unsupported classes. This can probably also be done with on-device testing, but that is significantly more expensive (in time/configuration at least) than unit tests.
