### ISSUE TITLE
BitmapFactory.decodeFile raised javax.imageio.IIOException since Robolectric 4.6

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#6812]
### Steps to Reproduce
```
$ git clone https://github.com/ganadist/VersionCodeDemo -b png_decode_robolectric_451
$ cd VersionCodeDemo
$ ./gradlew :app:testDevelopDebug

$ git checkout origin/png_decode_robolectric_461
$ ./gradlew :app:testDevelopDebug
```

png_decode_robolectric_451 : https://scans.gradle.com/s/vv2uoy56iezdc/tests/overview
png_decode_robolectric_461 : https://scans.gradle.com/s/x76vkmhvpsuea/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.ExampleUnitTest/decode_png

### Robolectric & Android Version
Android Gradle Plugin : 7.0.2
TargetSdkVersion : 30
Robolectric : 4.6.1

### Link to a public git repo demonstrating the problem:
https://github.com/ganadist/VersionCodeDemo/commits/png_decode_robolectric_461

### Additional Info
It seems this issue is related with #6286

**Comment by ganadist** [comment]
There is similar issue on JDK : https://bugs.openjdk.java.net/browse/JDK-8211422

But I can get same issue with Java 8 (Also adjusted with AGP 4.2 , TargetSdk 28)

https://scans.gradle.com/s/q4isg5j5ccbwq/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.ExampleUnitTest/decode_png

**Comment by utzcoz** [comment]
> There is similar issue on JDK : https://bugs.openjdk.java.net/browse/JDK-8211422
> 
> But I can get same issue with Java 8 (Also adjusted with AGP 4.2 , TargetSdk 28)
> 
> https://scans.gradle.com/s/q4isg5j5ccbwq/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.ExampleUnitTest/decode_png

Thanks for your reporting this problem. It's nice to see you again. Could you run it with JDK 12+? The issue link you provided says this problem is fixed at JDK 12. I think Robolectric can run with JDK 12-16. I can check whether we have workaround to avoid it.

**Comment by ganadist** [comment]
[Same error](https://scans.gradle.com/s/gpo4w44n4yin6/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.ExampleUnitTest/decode_png) on [JDK 16](https://scans.gradle.com/s/gpo4w44n4yin6#infrastructure)

And JDK 12~16 versions are [end of life](https://endoflife.date/java)
So, it's hard to recommend for use by companies.

Also, kotlin stable version(1.5.x) has some issues on JDK 16/17. 
https://youtrack.jetbrains.com/issue/KT-45545
So, it is not easy to adapt JDK16+ on general cases.

**Comment by utzcoz** [comment]
@ganadist Thanks for sharing those restrictions to adopting different JDK versions. I can reproduce this problem with your demo app. I checked the Robolectric test again, and I found there is a test to use `BitmapFactory#decodeFile` to decode png file(https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/robolectric/src/test/java/org/robolectric/shadows/ShadowBitmapFactoryTest.java#L400-L407). This test has been run hundred of times, it's weird. I will check the different between your test and Robolectric's one.

**Comment by utzcoz** [comment]
There is a related fix commit(http://hg.openjdk.java.net/jdk/client/rev/abed2967ec3a) for your mentioned JDK-issue(https://bugs.openjdk.java.net/browse/JDK-8211422). I also confirm that this fix also exists at JDK17: https://github.com/openjdk/jdk17u/blob/20f3576cd1bbe516360b0d9f7deaacdad94df4d7/src/java.desktop/share/classes/com/sun/imageio/plugins/png/PNGImageReader.java#L772-L785

> As per PNG specification all chunks should have 4 byte CRC. But there are some images where CRC is not present/corrupt for IEND chunk. And these type of images are supported by other decoders. So as soon as we hit chunk type for IEND chunk stop reading metadata.

It's comment is very interesting. It shows that all PNG specs says an valid PNG file has a 4byte CRC chunk. But there are some PNG images doesn't follow this rule. And those PNG images can be supported by other decoders. Maybe jpeg decoder can support it. Maybe your PNG image used by your demo is this type PNG image. I think there are two things Robolectric can do, one is to try-catch this error and print debug information to user; second is fallback to other decoder, for example jpeg decoder, when there is a similar exception of PNG decoder.

**Comment by utzcoz** [comment]
I use https://github.com/sherlly/PCRT to check `archlinux-logo.png` in your demo, it detected an error about its chunk:

```
[Finished] Correct PNG header
[Finished] Correct IHDR CRC (offset: 0x1D): 5C72A866
[Finished] IHDR chunk check complete (offset: 0x8)
[Finished] Correct IDAT chunk data length (offset: 0x5B length: 2000)
[Finished] Correct IDAT CRC (offset: 0x2063): 784757E2
[Detected] Error IDAT chunk data length! (offset: 0x2067)
```

**Comment by ganadist** [comment]
Thank you for detailed description, @utzcoz 
In my case, most of png files have IDAT chunk data length issue.
But image resource are used on unittest only, and it is okay to convert them by `PCRT`.

IMHO, it would be nice that robolectric prints debug information when png decoder failed and suggests to convert image resource with `PCRT`

**Comment by utzcoz** [comment]
> Thank you for detailed description, @utzcoz In my case, most of png files have IDAT chunk data length issue. But image resource are used on unittest only, and it is okay to convert them by `PCRT`.
> 
> IMHO, it would be nice that robolectric prints debug information when png decoder failed and suggests to convert image resource with `PCRT`

Thanks your response. I will prepare PR for debug information this weekend firstly. PCRT is a tool got by Google Search, and I will check whether there is a more suitable tool. If possible, I will check whether Robolectric can use a fallback decoder for those PNG images. Before that, you can use PCRT to convert your images and make your tests going on.

**Comment by ganadist** [comment]
I can get solution log which we intended.
https://scans.gradle.com/s/le4fg7434vs7w/console-log#L56

Thank you very much.

**Comment by utzcoz** [comment]
> I can get solution log which we intended. https://scans.gradle.com/s/le4fg7434vs7w/console-log#L56
> 
> Thank you very much.

Thanks for your testing. This PR is one the reviewing state, and we will merge it if it doesn't have other problems.

**Comment by anirudhkanathala** [comment]
Any update on this? This issue is still present in robolectric 4.7.2

**Comment by hoisie** [comment]
@anirudhkanathala try using 4.8-SNAPSHOT. 4.8-alpha-1 will be release shortly.
