### ISSUE TITLE
Support `android.utils.SparseArray.put` for Robolectric tests with `sdk` < 31

### ISSUE THREAD

**Issue by sgjesse** [robolectric/robolectric#6840]
As part of Android S the method `android.utils.SparseArray.put` was added to Android to support the Kotlin `[]` operator without using extension functions, see https://issuetracker.google.com/185547135.

As [issue 185547135](https://issuetracker.google.com/185547135), explains backporting of this method was added to D8/R8 when compiling to DEX by just rewriting `android.utils.SparseArray.put` to `android.utils.SparseArray.set`.

However, as the bug continues in [comment #4](https://issuetracker.google.com/185547135#comment4) this backporting is not present for Robolectric tests, as nothing is compiled to DEX in that case. With the newly landed support for Android S in Robolectric, code using `android.utils.SparseArray.put` now works when running tests with `sdk` set to 31.

For Robolectric tests to be as close as possible to device tests, this issue is about introducing a similar backport in Robolectric for `sdk` less than 31.

I did try to add a custom shadow for `android.utils.SparseArray`, but that can only intercept the `put` method if the method is already present, so only for `sdk` 31 and above - where it already works.

For the other sparse arrays `android.utils.SparseBooleanArray`, `android.utils.SparseIntArray` and `android.utils.SparseLongArray` the `set` method was not added, and this issue does not exist for these classes. Many developers will use the [Core Kotlin Extensions library](https://mvnrepository.com/artifact/androidx.core/core-ktx), which has extension functions to add `set` to Android sparse arrays.

### Steps to Reproduce
The Android Studio project [SparseArrayIssue.tar.gz](https://github.com/robolectric/robolectric/files/7510984/SparseArrayIssue.tar.gz) reproduces the issue (after updating the `sdk.dir`in `local.properties` by running:
```
./gradlew :app:testDebugUnitTest
```

**Comment by utzcoz** [comment]
Hi @sgjesse , what about trying [AndroidInterceptors](https://github.com/robolectric/robolectric/blob/9fd4b152d41ad05d2abd608ef1ef1f653d9270fa/sandbox/src/main/java/org/robolectric/interceptors/AndroidInterceptors.java)? Looks like it can be used to intercept methods of libcore/JDK.

**Comment by hoisie** [comment]
The issue is that the problematic calls to `SparseArray.put` will exist in app code, not framework code, so AndroidInterceptors won't be able to hook into things.

We will likely need a custom piece of instrumentation that adds the 'SparseArray.put' method to SparseArray for all previous SDK versions.

There are a couple of other bits of custom instrumentation, e.g. https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/internal/bytecode/ClassInstrumentor.java#L548.
