### ISSUE TITLE
`OutOfMemoryError` comes back when targeting android 31

### ISSUE THREAD

**Issue by calvarez-ov** [robolectric/robolectric#6872]
### Description

We had issue #2584.

We had this workaround for that issue, on every test tearDown:

```kotlin
        // https://github.com/robolectric/robolectric/issues/2584
        val windowData = Reflection.staticField("WINDOW_DATA").ofType(Any::class.java)
            .`in`(ShadowCursorWindow::class.java).get()
        val dataMap =
            Reflection.field("dataMap").ofType(MutableMap::class.java).`in`(windowData).get()
        dataMap.clear()
```

With robolectric 4.7.1, if we set `sdk=31` in `robolectric.properties`, this workaround causes reflection exceptions when running tests.

I removed the workaround, and I have `OutOfMemoryError`s once again.

### Steps to Reproduce
See #2584

### Robolectric & Android Version
* robolectric: 4.7.1
* compileSdkVersion: 31
* targetSdkVersion: 30
* robolectric.properties: `sdk`: 31

~Note: with robolectric 4.7.1, if stay with `sdk` of `30` and keep the workaround, there aren't `OutOfMemoryError`s~
Not so sure about this statement. I need to double check.

**Comment by calvarez-ov** [comment]
If I make the following change the workaround, I still have `OutOfMemoryError`s:

```patch
         // https://github.com/robolectric/robolectric/issues/2584
         val windowData = Reflection.staticField("WINDOW_DATA").ofType(Any::class.java)
-            .`in`(ShadowCursorWindow::class.java).get()
+            .`in`(ShadowLegacyCursorWindow::class.java).get()
         val dataMap =
             Reflection.field("dataMap").ofType(MutableMap::class.java).`in`(windowData).get()
         dataMap.clear()
```

**Comment by hoisie** [comment]
Can you add `-XX:+HeapDumpOnOutOfMemoryError` to your project's JVM flags? You could either upload the hprof file or use VisualVM to analyze it.

**Comment by calvarez-ov** [comment]
I'll check those jvm flags in a moment.

I just wanted to also note here that I tried setting the following, and it didn't solve the problem:
```gradle
     testOptions {
         unitTests {
             all {
                 ...
                 systemProperty 'robolectric.sqliteMode', "NATIVE"
             }
         }
     }
```

**Comment by calvarez-ov** [comment]
I had almost your settings, but in a comment:
```gradle
#org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError
```

I'll uncomment it and try again

**Comment by calvarez-ov** [comment]
Ok, I found the config to enable these options:
```gradle
 tasks.configureEach { theTask ->
     def taskName = theTask.name.toString()
     if (taskName =~ /test.*DebugUnitTest/) {
-        theTask.jvmArgs('-ea', '-noverify')
+        theTask.jvmArgs('-ea', '-noverify', '-Xmx4G', '-XX:+HeapDumpOnOutOfMemoryError')
     }
 }
```

I now have a 2G heap file! I'll check out VisualVM

**Comment by calvarez-ov** [comment]
![image](https://user-images.githubusercontent.com/9365138/142686666-450502d3-e281-451e-af10-b6b3d7b845d8.png)

**Comment by calvarez-ov** [comment]
![image](https://user-images.githubusercontent.com/9365138/142687064-ab8d0c74-527e-454b-b79f-c7ef3c47fad2.png)

**Comment by hoisie** [comment]
Can you search for `Activity`? When you see resources like that, it typically involves Activities that leak across tests.

**Comment by calvarez-ov** [comment]
For info, doing this at the end of each test makes the `OutOfMemoryError`s go away:

```kotlin
Registries.NATIVE_THEME9_REGISTRY.clear()
```

**Comment by calvarez-ov** [comment]
I'll look for activites though

**Comment by calvarez-ov** [comment]
Possibly related: #5530

**Comment by hoisie** [comment]
Thanks for reporting this. Looking at this further, it does seem like the logic that frees themes does not seem to run in Android S:

https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowArscAssetManager10.java#L1585

This seems to be the logic for releasing themes now:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/res/AssetManager.java;l=1180-1184

This ends up calling nativeDestroy.

**Comment by hoisie** [comment]
Just pushed 4.7.2 which should hopefully contain a fix for this issue. Reopening for now. @calvarez-ov when you get a chance can you check if it worked?

**Comment by caarmen** [comment]
Yes, it works!  

I updated to `4.7.2`, removed my `Registries.NATIVE_THEME9_REGISTRY.clear()` workaround, and ran the test suite without any `OutOfMemoryError`.

Thanks so much! 🙏
