### ISSUE TITLE
WindowManager.getCurrentWindowMetrics returns Rect(0,0,0,0) 

### ISSUE THREAD

**Issue by lsuski** [robolectric/robolectric#6887]
### Description

`WindowManager.getCurrentWindowMetrics().getBounds` is the new way to obtain window size however in Robolectric it returns empty `Rect`

### Steps to Reproduce

```
@RunWith(RobolectricTestRunner::class)
@Config(qualifiers = "w360dp-h640dp")
class WindowSizeKtTest {

 @Test
    fun `test size on R`() {

        ActivityScenario.launch(FragmentActivity::class.java).onActivity {

            assertNotEquals(0, it.getSystemService<WindowManager>()?.currentWindowMetrics?.bounds?.width())

        }.close()
    }

}
```

### Robolectric & Android Version

Robolectric 4.7.2
targetSdk 31

**Comment by hoisie** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/6922
