### ISSUE TITLE
Feature Request: publish artifacts for running tests in JVM-only Gradle modules

### ISSUE THREAD

**Issue by kenyee** [robolectric/robolectric#6913]
### Description
We have some JVM only Gradle modules in our project that ran tests using this jar file (undocumented, but it worked):
.gradle/caches/modules-2/files-2.1/org.robolectric/android-all-instrumented/11-robolectric-6757853-i1/1b10f2a8f4abf22cfc86a2d23a09cc4fc4e22332/android-all-instrumented-11-robolectric-6757853-i1.jar
But as of 4.6.x with pre-instrumented AAR files, this is no longer possible so we're stuck on 4.5.1.

Please publish artifacts that can be run against JVM only modules (non-Android).
Our use case is we have tests for Sqlite (these modules are mostly DB access modules) and would like to run these using Robolectric.  Rebuilding these as Android modules would slow our builds down and require a good amount of restructuring.

### Steps to Reproduce
N.A.

### Robolectric & Android Version
Robolectric 4.7.3

### Link to a public git repo demonstrating the problem:
N.A.

**Comment by hoisie** [comment]
What error message or stack trace are you seeing? All of the android-all JAR files are just regular JAR files that are built specifically for Robolectric and are all run on the JVM.

**Comment by hoisie** [comment]
> 4.6.x with pre-instrumented AAR files

There may be a misunderstanding, Robolectric does not work with AAR files.

Are the instrumented android-all jars being included in the compile-time classpath? This should not happen, and I have seen this cause issues before.

**Comment by kenyee** [comment]
ahh...they are published here:
https://mvnrepository.com/artifact/org.robolectric/android-all

<img width="1298" alt="Screen Shot 2021-12-06 at 1 28 58 PM" src="https://user-images.githubusercontent.com/586670/144901848-4ed543b6-359a-430b-abaa-ffa1af2d1aac.png">

Sorry...thought that might have been the reason I'm seeing a weird resourceTable field being null issue, but using the latest android-all jar (I was using an older one but switched to the 12-robolectric-7732740 one) still has the same problem when coupled with Robolectric 4.7.3's test runner (dropping to 4.5.1 works fine).  
It's hit when doing SQLiteCursor.getCount(). I'll see if I can put together a separate repro.

**Comment by hoisie** [comment]
It looks like your test is not using binary resources (I am seeing ShadowLegacyAssetManager).

Do you have this set?

```gradle
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```

**Comment by kenyee** [comment]
This is a pure JVM gradle module...there's no "android {}" block :-(
I did try adding this to my system props for Robolectric w/o luck:

    systemProperty("robolectric.resourcesMode", "binary")

It's still kicking in the legacy asset manager...

**Comment by kenyee** [comment]
FYI: https://github.com/robolectric/robolectric/issues/6916
