### ISSUE TITLE
default value of robolectric.dependency.repo.id is MavenCentral, but document points SonaType

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#6930]
### Description

On http://robolectric.org/configuring/#system-properties, default value of `robolectric.dependency.repo.id` is `sonatype` and `robolectric.dependency.repo.url` is `https://oss.sonatype.org/content/groups/public`.
But actual implementation was changed to `Maven Central` by #5833

It needs to update documents.

**Comment by utzcoz** [comment]
@ganadist Thanks for pointing this out. I will send a PR for robolectric.github.io to update documents today.

**Comment by utzcoz** [comment]
@ganadist you can check website again, and it has updated with new correct `mavenCentral` information.
