### ISSUE TITLE
Migrate compileSdkVersion to compileSdk for Robolectric's tests

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6950]
### Description

Robolectric uses AGP 7.1.0, and it deprecated `compileSdkVersion`, and wants users to use `compileSdk` to replace it. 

See:
https://cs.android.com/android-studio/platform/tools/base/+/7d1121c1a3d727748d6693a56ba8822b04ed9d8f, 
https://stackoverflow.com/questions/67250362/what-is-difference-between-compilesdk-and-compilesdkversion-in-android-studio-gr,
https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-api/src/main/java/com/android/build/api/dsl/CommonExtension.kt;l=806-808;bpv=1;bpt=0

### Steps to Reproduce

Use latest Android Studio beta to open Robolectric project, and will see  `compileSdkVersion` is marked deprecated in Android Studio.

### Robolectric & Android Version

Robolectric master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by Akshay2131** [comment]
PR: #7233
