### ISSUE TITLE
Remove `targetSdk` from AndroidManifest.xml for tests

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6966]
### Description

AndroidStudio shows following warnings:

> The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Remove targetSdkVersion and sync project
Affected Modules: parent.integration_tests.androidx, parent.integration_tests.androidx_test, parent.integration_tests.ctesque, parent.integration_tests.memoryleaks, parent.testapp

### Steps to Reproduce

`./gradlew lint` can generate lint problems of current modules, including above mentioned problems.

### Robolectric & Android Version

Current master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by Umesh-01** [comment]
@utzcoz I want to work on this issue, if you can guide me a little bit.

**Comment by utzcoz** [comment]
> @utzcoz I want to work on this issue, if you can guide me a little bit.

The issue description is clear for what we should do. The AGP will omit target SDK in AndroidManifest.xml, and use one in build.gradle. This issue wants to remove targetSdk in AndroidManifest.xml to remove building warnings. It's recommend to read Android official documentation to learn those concepts.

**Comment by Umesh-01** [comment]
So, for this I have to set up JDK 11, Android Studio and other tools written in `README.md` file. And then I have to move `targetSdk version` from Android manifest to build.gradle (app). Am I right??

**Comment by utzcoz** [comment]
> So, for this I have to set up JDK 11, Android Studio and other tools written in `README.md` file. And then I have to move `targetSdk version` from Android manifest to build.gradle (app). Am I right??

Yup. The README.md also links a building page of robolectric.org, and you can follow it to build Robilectric locally. After that, you can run lint command as issue said to check warnings of targetSdk and follow its suggestion to fix it and evaluate it locally again with lint command. If the warnings disappeared and related tests passed, please send a PR for reviewing. Thanks.

**Comment by Umesh-01** [comment]
@utzcoz With `./gradlew clean assemble` command I am getting this error: "No such file or directory" while Building process.

![image](https://user-images.githubusercontent.com/83420185/161590530-4e2ff965-bd07-473a-8092-d06f5d7ac140.png)

**Comment by utzcoz** [comment]
@Umesh-01 Please run this command under Robolectric source code top directory.

**Comment by Umesh-01** [comment]
Not it is showing **Build failed with an exception**

![image](https://user-images.githubusercontent.com/83420185/161719188-8514c173-d5ad-465a-a069-154ed1f9f034.png)

**Comment by utzcoz** [comment]
@Umesh-01 Please read http://robolectric.org/building-robolectric/ and follow it to setup development environment on Windows. Before that, please ensure you have downloaded/cloned source code with recursive mode to fetch icu and sqlite correctly, because they are used with git-sub-module.

**Comment by Umesh-01** [comment]
> @Umesh-01 Please read http://robolectric.org/building-robolectric/ and follow it to setup development environment on Windows. Before that, please ensure you have downloaded/cloned source code with recursive mode to fetch icu and sqlite correctly, because they are used with git-sub-module.

Sure !!

I think my system is using older version of gradle, let me check it first.

**Comment by Umesh-01** [comment]
I am getting this in Build window "The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file." and a warning with Lint.

Should I remove it using "Remove targetSdkVersion and sync project" option in Build window??


![image](https://user-images.githubusercontent.com/83420185/161732861-b9de36c3-dc4d-46d3-85f1-496f906c03f7.png)

![image](https://user-images.githubusercontent.com/83420185/161732942-fc39807b-fa48-4739-909e-438729e9e472.png)

**Comment by Umesh-01** [comment]
> Now, it is showing **Build failed with an exception**
> 
> ![image](https://user-images.githubusercontent.com/83420185/161719188-8514c173-d5ad-465a-a069-154ed1f9f034.png)

This is still showing the same error, with Build failed message but when I opened the project with android studio, Build process is showing successful with the same warnings. IDK what's the problem now. 

![image](https://user-images.githubusercontent.com/83420185/161734671-ddd86fb1-832c-498b-8fa8-2915f3635ba3.png)

**Comment by utzcoz** [comment]
You can use `./gradlew assemble --stacktrace` to get detailed build log. Maybe it will be useful to spot out real problem.

**Comment by Umesh-01** [comment]
> I am getting this in Build window "The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file." and a warning with Lint.
> 
> Should I remove it using "Remove targetSdkVersion and sync project" option in Build window??
> 
> ![image](https://user-images.githubusercontent.com/83420185/161732861-b9de36c3-dc4d-46d3-85f1-496f906c03f7.png)
> 
> ![image](https://user-images.githubusercontent.com/83420185/161732942-fc39807b-fa48-4739-909e-438729e9e472.png)


Can't I do this from Android Studio??

**Comment by Umesh-01** [comment]
Is this fine??

![image](https://user-images.githubusercontent.com/83420185/161787079-a5a3a230-3a0c-4b5d-bd77-e35e75ebd98e.png)

**Comment by Umesh-01** [comment]
Now, `./gradlew --scan` `./gradlew --stacktrace` and `./gradlew --warning-mode all` all of them are showing BUILD SUCCESSFUL, only `./gradlew clean assemble` is showing BUILD FAILED.

**Comment by Umesh-01** [comment]
I am not able to find out the solution for this error, what I found is not related to this on stackoverflow and other websites. The problem is only with `.gradlew assemble` command. 

And error is: 
```
Execution failed for task ':nativeruntime:configureICU'.
> A problem occurred starting process 'command './runConfigureICU''
```

**Comment by utzcoz** [comment]
@Umesh-01 What I found about this error is related to JDK: https://www.youtube.com/watch?v=90UB4vhoIaI. Which real path of your installed JDK and what's your `JAVA_HOME` on your terminal before running `./gradlew assemble`?

**Comment by Umesh-01** [comment]
> @Umesh-01 What I found about this error is related to JDK: https://www.youtube.com/watch?v=90UB4vhoIaI. Which real path of your installed JDK and what's your `JAVA_HOME` on your terminal before running `./gradlew assemble`?

Yes firstly the path of JDK 11 was in Path variable with all the other paths and then I have created 'JAVA_HOME' environment variable for JDK 11, but I think now both paths are same. I faced this error when you told me about this [command](https://github.com/robolectric/robolectric/issues/6966#issuecomment-1088582502) and I got this [result](https://github.com/robolectric/robolectric/issues/6966#issuecomment-1088747447). 

Now, the error is [this](https://github.com/robolectric/robolectric/issues/6966#issuecomment-1088870532).

**Comment by Umesh-01** [comment]
Sorry, I was wrong. This `./gradlew assemble --stacktrace` command is still giving [same](https://github.com/robolectric/robolectric/issues/6966#issuecomment-1088747447) error. I got confused between `./gradlew assemble --stacktrace` and `./gradlew --stacktrace`

**Comment by Umesh-01** [comment]
> @Umesh-01 What I found about this error is related to JDK: https://www.youtube.com/watch?v=90UB4vhoIaI. Which real path of your installed JDK and what's your `JAVA_HOME` on your terminal before running `./gradlew assemble`?

I don't know what was `JAVA_HOME` on my terminal before running this command but I have added it to environment variables manually. It didn't exist before that.

**Comment by Umesh-01** [comment]
> @Umesh-01 What I found about this error is related to JDK: https://www.youtube.com/watch?v=90UB4vhoIaI. Which real path of your installed JDK and what's your `JAVA_HOME` on your terminal before running `./gradlew assemble`?

And also I am not using the embedded JDK like it was shown in the video.  

![image](https://user-images.githubusercontent.com/83420185/162044189-f0e59abc-ee57-4018-814a-29650db3c7c3.png)

**Comment by utzcoz** [comment]
Sorry, I don't have other idea about it.Hi @hoisie , do you have any idea about it?

**Comment by Umesh-01** [comment]
Hello @hoisie can you guide me on this issue..!!

**Comment by utzcoz** [comment]
@Umesh-01 you also can do this task directly, and send PR for it. It's very simple, and we can push its progress directly.

**Comment by Umesh-01** [comment]
Yes, I have opened the PR, @utzcoz can you pls review it. 

I will try again to build the project from scratch by following the guidelines given on the robolectric.org web page. And I will try to figure out the problem that I am facing.

**Comment by Umesh-01** [comment]
@utzcoz which one I have to install from these??

Previously I had installed all of them.

![image](https://user-images.githubusercontent.com/83420185/162808124-d8ecc781-d7bf-4a5d-8029-3d6c7f3eeed7.png)

**Comment by utzcoz** [comment]
@Umesh-01 I think you use following commands to install directly:

```
pacman -Syu # Update system
pacman -Sy base-devel mingw-w64-x86_64-toolchain # Install the ming-w64-x86_64 package group
pacman -Sy git mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja
```

Those commands are listed in http://robolectric.org/building-robolectric/.

**Comment by Umesh-01** [comment]
> @Umesh-01 I think you use following commands to install directly:

Yes, I tried but it didn't work either. 

Can you review my project proposal??

**Comment by hoisie** [comment]
@utzcoz should disable the native runtime build for Windows at the moment? It causes too many complications to build, and the sqlite calls don't even work due to dll issues.

Also, I would like to move towards having the native runtime shared objects be separate artifacts on maven so they can just be pulled from maven during the build.

**Comment by hoisie** [comment]
Sorry for the late reply to this thread.

@Umesh-01 first of all I would encourage you to use an Ubuntu VM if possible to build Robolectric. Windows support is not great, and none of the maintainers work in Windows (we use Linux + Mac).

In the Robolectric root directory, did you run `git submodule update --init`? It appears that you may not have the submodules checked out (sqlite and icu).

Once you have them checked out, I would recommend running this:

1) `mkdir $HOME/icu-bin`
2) go the the Robolectric root and run `cd nativeruntime/external/icu/icu4c/source`
3) run ` ./runConfigureICU MinGW --prefix=$HOME/icu-bin --enable-static`
4) run `make && make install`
5) Then from the Robolectric root run `ICU_ROOT_DIR=$HOME/icu-bin  SKIP_PREINSTRUMENTED_BUILD=true ./gradlew assemble`

**Comment by hoisie** [comment]
@Umesh-01 can you  also send the proposal to hoisie+gsoc@google.com? Is this for Conscrypt?

**Comment by utzcoz** [comment]
@Umesh-01 if you have problem to setup Windows environment, please file a new issue or discussion to discuss it. I will close this issue because you PR merged. Thanks for contribution.

> @Umesh-01 can you also send the proposal to [hoisie+gsoc@google.com](mailto:hoisie+gsoc@google.com)? Is this for Conscrypt?

@hoisie What about moving discussion to https://github.com/robolectric/robolectric/discussions/7199?
