### ISSUE TITLE
ShadowBitmapFactory create with options does not set createdFromBytes

### ISSUE THREAD

**Issue by edwinvanderham** [robolectric/robolectric#6971]
### Description

When I create a new Bitmap using "BitmapFactory.decodeByteArray(byte[] data, int offset, int length)", the shadow implementation of the BitmapFactory sets the createdFromBytes field so I can easily get the original bytes that were used when creating the Bitmap. This is not the case for the overload "Bitmap decodeByteArray(byte[] data, int offset, int length, BitmapFactory.Options opts)"

### Steps to Reproduce

byte[] bytes = new byte[10];
ShadowBitmap sb = shadowOf(Bitmap decodeByteArray(byte[] data, int offset, int length, BitmapFactory.Options opts));
assertEquals(bytes, sb.getCreatedFromBytes());

### Robolectric & Android Version

robolectric 4.7.3

**Comment by edwinvanderham** [comment]
I think this can be very easily solved by adding 
```
ShadowBitmap shadowBitmap = Shadow.extract(bitmap);
shadowBitmap.createdFromBytes = data;
```
at the end of `protected static Bitmap decodeByteArray(byte[] data, int offset, int length, BitmapFactory.Options opts)`

**Comment by utzcoz** [comment]
@edwinvanderham Thanks for pointing out this problem. Could you help to send a PR to fix it?
