### ISSUE TITLE
Kotlin Examples

### ISSUE THREAD

**Issue by reymalahay** [robolectric/robolectric#6976]
Hi all,

Firstly, `Robolectric` is an awesome testing framework. I've been using it for many years.

Just a quick question, is there a plan to also include examples using `kotlin`? After all, `kotlin` has become the _de facto_ language for developing `Android` [applications](https://kotlinlang.org/docs/android-overview.html)

Please advise.

Thanks in advance and kind regards,
rey malahay

**Comment by hoisie** [comment]
We definitely could use more examples. The [deckard-gradle ](https://github.com/robolectric/deckard-gradle233) example is quite outdated and obsolete. Contributions welcome on this front.

**Comment by utzcoz** [comment]
> We definitely could use more examples. The [deckard-gradle ](https://github.com/robolectric/deckard-gradle233) example is quite outdated and obsolete. Contributions welcome on this front.

We also can write new tests of integration_tests with Kotlin and migrate current tests of integration_tests to Kotlin too. I always learn usage of Robolectric from those tests.

**Comment by utzcoz** [comment]
@reymalahay IMO, this issue is a common problem about Robolectric samples, including Kotlin samples. We can move this discussion to https://github.com/robolectric/robolectric/discussions/7111. Feel free to reopen it if you think this issue should exist here.
