### ISSUE TITLE
Snapshots are not released

### ISSUE THREAD

**Issue by carlonzo** [robolectric/robolectric#6982]
Hi, looking at the snapshots repository [https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/](https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/) looks like last released snapshot was on November 5.

Did you stop releasing snapshots or something is broken?
I came here because I tried to use 4.8-SNAPSHOT as stated here https://github.com/robolectric/robolectric/blob/master/README.md?plain=1#L64 but the artifacts are not uploaded

**Comment by utzcoz** [comment]
I think it is related to https://github.com/robolectric/robolectric/issues/6803. From 4.7, Robolectric started to support nativeruntime for SQLite, and SNAPSHOT is broken from that release. Previous mentioned issue is used to track this problem.

**Comment by utzcoz** [comment]
@carlonzo you can show your need for SNAPSHOT at https://github.com/robolectric/robolectric/issues/6803, and I will close this issue. Feel free to reopen it if you have any problem.

**Comment by yschimke** [comment]
~Could we update the readme to not advertise the snapshots then?~

Activity since then, so maybe they are published.

**Comment by utzcoz** [comment]
@yschimke Yeah. We have fixed issues, and enabled it.
