### ISSUE TITLE
Android started to use WeakReference.refersTo() in T and it breaks Robolectric

### ISSUE THREAD

**Issue by romkal** [robolectric/robolectric#7048]
### Description
In https://cs.android.com/android/_/android/platform/frameworks/base/+/3492061b6de0de3ad0cdb7f40d41ffd0f51a28a2 Android changed some code to use [WeakReference.refersTo()](https://cs.android.com/android/platform/superproject/+/master:libcore/ojluni/src/main/java/java/lang/ref/Reference.java;l=126;drc=ff15772f3de82c6a439fe1bed6df0e4605b6002e) method that is non-standard and doesn't exist in JVM.

This means that running this class will blow up with `java.lang.NoSuchMethodError: 'boolean java.lang.ref.WeakReference.refersTo(java.lang.Object)`

### Robolectric & Android Version
Android T.

**Comment by hoisie** [comment]
We can fix this using an AndroidInterceptor, but what should the implementation of refersTo be when using Java < 16?

Is `WeakReference.refersTo(obj)` equivalent to `Objects.equal(WeakReference.get()`, obj)?

**Comment by utzcoz** [comment]
> Is WeakReference.refersTo(obj) equivalent to Objects.equal(WeakReference.get(), obj)?

There is an occasion that object's `equals` returns true, but different instance maybe have different result between two methods.

**Comment by utzcoz** [comment]
> All the uses I've introduced are for WeakReference, where it could be replaced by .get() == in for short-running tests, though that may effectively introduce a leak if e.g. null checks are frequent enough.

I found related changes at https://github.com/openjdk/jdk/commit/6023f6b1bf99de413e78c6373674649cbd68fae8#diff-e3ca3ae9699a1a2395f20c60a6c199d4c0eed1545477794f36d194f5643f071dR328-R338. @hoisie As @hboehm said, maybe we can use `obj == WeakReference.get()` as a fallback to ignore potential memory leak.

**Comment by hoisie** [comment]
You're right it should be `obj == WeakReference.get()` to check physical equality.

**Comment by hboehm** [comment]
Note that this only works for WeakReference (and SoftReference, which should be avoided on Android). Unless you know exactly where the calls are coming from, you may want to check that this is not being invoked on a PhantomReference. I haven't encountered a great use case for PhantomReference.refersTo(), but the OpenJDK folks seem to have something in mind.

**Comment by utzcoz** [comment]
@hoisie I found a related AOSP CL(https://android-review.googlesource.com/c/platform/frameworks/base/+/1971039) for this problem. I think Robolectric on GitHub will not support it because the lack of Android T supporting(looks like it will be release at June officially). What about fixing it internal at AOSP's robolectric-shadow(I only found this related repo), and keep it internal without syncing until Robolectric on GitHub has official Android T supporting?

**Comment by hoisie** [comment]
Hi @utzcoz 

Interesting find, thanks. I commented on that CL. There actually was a fix to robolectric-shadows but not sure if it was CPd to aosp yet. I can try to do that.

**Comment by utzcoz** [comment]
Does it existed in internal branch? I have saw delayed sync of robolectric-shadows before at https://android-review.googlesource.com/c/platform/external/robolectric-shadows/+/1512632 that caused AOSP master tests broken(https://android-review.googlesource.com/c/platform/frameworks/base/+/1491416). From your comments at Gerrit, I know Robolectric tests are omitted for AOSP master, what about enabling it for master? Maybe it will help to catch broken tests early.
