### ISSUE TITLE
Need declare prerequisites in contributing guidelines for building and testing

### ISSUE THREAD

**Issue by ZSmallX** [robolectric/robolectric#7069]
### Description

Building and running test well on my MacBook, but with compile error on my Linux Debian 9.

I follow the commands in `tests.yml` file.

For MacOS:  
```
brew install cmake
brew install ninja
```

For Linux:  
```
sudo apt-get install cmake
sudo apt-get install ninja-build
```

Build & Testing:  

```
git submodule init
git submodule update --init --depth=1

cd nativeruntime/external/icu/icu4c/source
CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./runConfigureICU Linux --enable-static --prefix=$HOME/icu-bin
make -j4
make install

ICU_ROOT_DIR=$HOME/icu-bin SKIP_ERRORPRONE=true SKIP_JAVADOC=true ./gradlew clean assemble testClasses --parallel --stacktrace --no-watch-fs

ICU_ROOT_DIR=$HOME/icu-bin SKIP_ERRORPRONE=true SKIP_JAVADOC=true ./gradlew test --info --stacktrace --continue \
  --parallel \
  --no-watch-fs \
  -Drobolectric.enabledSdks=26,27,28 \
  -Drobolectric.alwaysIncludeVariantMarkersInTestName=true \
  -Dorg.gradle.workers.max=2
```

#### Envs

LInux Debain 9  
cmake == 3.7.2   
ninja == 1.7.2  
gcc == 6.3.0  
JDK 11  

MacOS Monterey  12.1 (21C52)
cmake == 3.22.2  
ninja == 1.10.2  
gcc == 12.0.0  
JDK 11  

### Robolectric & Android Version

lastest master.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by ZSmallX** [comment]
Shall we make those sofeware prerequisites more clear for

**Comment by hoisie** [comment]
This sounds great, it can even go in the Readme.md. We also try to give informative errors if people try to build without these modules installed. I know that currently if 'ninja' is not installed, it will not give a good error message.

**Comment by utzcoz** [comment]
Maybe off-topic: we can improve developer/contributor documentation at README.md firstly, and discuss whether we should improve robolectrico.org too after that.
