### ISSUE TITLE
Unable to access setUri method through Robolectric test runner

### ISSUE THREAD

**Issue by gsnayma01** [robolectric/robolectric#7112]
Hi,

I am using ExoPlayer for my media app in AOSP code and I have used PlayerView in my layout file.

I am trying to write the Unit tests for my app but when I run the robolectric tests it gives android.view.InflateException on PlayerView.

**I am able to access the setUri method in my main code but robolectric not able to find the setUri method when I run unit tests using robolectric.**

```

 There was 1 failure:
RunMyMediaTest: 1) initComponentsTest(com.gs.mymedia.MainActivityTest)
RunMyMediaTest: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class com.google.android.exoplayer2.ui.PlayerView
RunMyMediaTest: Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.google.android.exoplayer2.ui.PlayerView
RunMyMediaTest: Caused by: java.lang.reflect.InvocationTargetException
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
RunMyMediaTest:    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
RunMyMediaTest:    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:852)
RunMyMediaTest:    at android.view.LayoutInflater.createView(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:1004)
RunMyMediaTest:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:959)
RunMyMediaTest:    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:1121)
RunMyMediaTest:    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:1082)
RunMyMediaTest:    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:680)
RunMyMediaTest:    at android.view.LayoutInflater.inflate(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:532)
RunMyMediaTest:    at android.view.LayoutInflater.inflate(LayoutInflater.java)
RunMyMediaTest:    at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:479)
RunMyMediaTest:    at android.view.LayoutInflater.inflate(LayoutInflater.java)
RunMyMediaTest:    at com.gs.mymedia.MainActivityTest.setUp(MainActivityTest.java:77)
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
RunMyMediaTest:    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
RunMyMediaTest:    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
RunMyMediaTest:    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
RunMyMediaTest:    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
RunMyMediaTest:    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
RunMyMediaTest:    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
RunMyMediaTest:    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
RunMyMediaTest:    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
RunMyMediaTest:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
RunMyMediaTest:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
RunMyMediaTest:    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
RunMyMediaTest:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
RunMyMediaTest:    at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
RunMyMediaTest:    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
RunMyMediaTest:    at org.junit.runners.Suite.runChild(Suite.java:128)
RunMyMediaTest:    at org.junit.runners.Suite.runChild(Suite.java:27)
RunMyMediaTest:    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
RunMyMediaTest:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
RunMyMediaTest:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
RunMyMediaTest:    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
RunMyMediaTest:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
RunMyMediaTest:    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
RunMyMediaTest:    at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
RunMyMediaTest:    at com.android.junitxml.JUnitXmlRunner.main(JUnitXmlRunner.java:98)
RunMyMediaTest: Caused by: java.lang.NoSuchMethodError: com.google.android.exoplayer2.MediaItem$Builder.setUri(Landroid/net/Uri;)Lcom/google/android/exoplayer2/MediaItem$Builder;
RunMyMediaTest:    at com.google.android.exoplayer2.Timeline$Window.<clinit>(Timeline.java:160)
RunMyMediaTest:    at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:410)
RunMyMediaTest:    at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:498)
RunMyMediaTest:    at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:318)
RunMyMediaTest:    ... 52 more
RunMyMediaTest:
RunMyMediaTest: FAILURES!!!
RunMyMediaTest: Tests run: 1,  Failures: 1
RunMyMediaTest:
build completed successfully (01:20 (mm:ss))
```

`
@RunWith(RobolectricTestRunner.class)
public class MainActivityTest { 

    private Context mContext;

    private MainActivity mActivity;
    
    @Before
    public void setUp() throws NoSuchFieldException {
        MockitoAnnotations.initMocks(this);
        mContext = RuntimeEnvironment.application;
        mActivity = Robolectric.buildActivity(MainActivity.class).create().resume().get();
    }

    @Test
    public void initComponentsTest() {
        assertNotNull(mActivity);
    }

}`

**And here is my XML**

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/root_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal|top"
    android:background="@color/activityBackground">

    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/player_view"
        app:use_controller="false"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resize_mode="fill"/>

    </FrameLayout>`

### Robolectric & Android Version
Android Version- Android 11
Robolectric Vesion : 4.2

Can anyone help me with this issue or any link of similar fix ?

**Comment by gsnayma01** [comment]
@hoisie Could you please have a look into this ?

**Comment by ZSmallX** [comment]
Hi @gsnayma01 look like you're using an old version of robolectric. 
Have you tried the latest version(4.7.3) of robolectric? Does it lead to the same result?

If so, could you please provide a demo project on GitHub and provide more context (like: ExoPlayer version, project configurations etc) for verification convenience.  It's good for investigation.

**Comment by gsnayma01** [comment]
> @gsnayma01 could you share your `Android.mk` or `Android.bp` for Robolectric test?

Below is my Android.bp file for tests

```
android_robolectric_test {
    name: "MyModuleNameTest",
    srcs: ["src/**/*.java",],
    java_resource_dirs: ["config", "resources"],
    instrumentation_for: "MyModuleName",
    
    libs: [
        "android.test.base.stubs",
        "android.test.mock.stubs",
        "android.test.runner.stubs",
    ],

    static_libs: [
        "mockito-robolectric-prebuilt",
        "platform-test-annotations",
        "testng",
        "truth-prebuilt",
    ],

     test_options: {
            timeout: 36000,
    },
}
```

**Comment by gsnayma01** [comment]
> Hi @gsnayma01 look like you're using an old version of robolectric. Have you tried the latest version(4.7.3) of robolectric? Does it lead to the same result?
> 
> If so, could you please provide a demo project on GitHub and provide more context (like: ExoPlayer version, project configurations etc) for verification convenience. It's good for investigation.

I haven't try with latest version 4.7.3 as this will affect other modules tests in my AOSP workspace. I will try to share you the GitHub link with sample code

**Comment by gsnayma01** [comment]
@utzcoz I have a separate module called ExoPlayer (my own module in AOSP) where all the required dependencies added (source code added) like ui, core, common, dash etc and added all the related dependencies in ExoPlayer's Android.bp under tag android_library.
here library is a directory where I copied all the modules of ExoPlayer.

**ExoPlayer Module's Android.bp** 
`
android_library {
    name: "exoplayer2-whole",
    manifest: "library/all/src/main/AndroidManifest.xml",
    resource_dirs: [
        "library/ui/src/main/res",
        "library/core/src/main/res",
    ],
    platform_apis: true,

    static_libs: [

        "androidx.media_media",
        "androidx.annotation_annotation-exoplayer",

        "androidx.recyclerview_recyclerview",

        "error_prone_core",
        "error_prone_annotations-exoplayer",
        "checkerframework-exoplayer",
        "exoplayer2-annotation-stubs",
            ],

    optimize: {
        enabled: false,
    },
    
    srcs: [
        "library/**/*.java",
    ],

    exclude_srcs: [
        "library/tests/**/*.java",
    ],

    visibility: ["//visibility:public"],

    aaptflags: [
        "--auto-add-overlay",
        "--extra-packages",
        "com.google.android.exoplayer2.ui",
        "--extra-packages",
        "com.google.android.exoplayer2.core",
    ],
}`


Here is part of **MyModuleName's Android.bp**

`android_app {
    name: "MyModuleName",
    manifest: "app/src/main/AndroidManifest.xml",
    srcs: ["app/src/main/java/**/*.java" ,
],
    resource_dirs: ["app/src/main/res"],
    privileged: true,
    aapt_include_all_resources: true,
    platform_apis: true,
    certificate: "platform",
    java_version: "1.8",
    
    optimize: {
        enabled: false,
    },


    static_libs: [
        "exoplayer2-whole",
        "androidx.annotation_annotation",
    	"androidx.appcompat_appcompat",
    ],

     aaptflags: [
        "--auto-add-overlay",
        "--extra-packages",
        "com.google.android.exoplayer2.ui",
    ],
}
`


I hope this info will give you more clear picture.

I am using below code in my main logic which is working fine

` MediaItem item = new MediaItem.Builder().setUri(url).build();`

But the same is not accessible to Robolectric test runner.

I am using ExoPlayer's 2.16.1 version

**Comment by utzcoz** [comment]
There is one thing we can do: build `exoplayer2-whole` with command `make exoplayer2-whole`, and check whether its generated result contains your needed class(`MediaItem` with `setUri`). If it contains your needed classes, it is not your `exoplayer2-whole` problem. If not, please validate your `exoplayer2-whole` `Android.bp` again to ensure it contains correct source code list. If `exoplayer2-whole` contains correct class, you can build `MyModuleName` later to check whether `MyModuleName` generated apk/jar/aar contains correct class.

**Comment by hoisie** [comment]
@gsnayma01 I wish we could help more, but unfortunately this issue tracker is not the place to receive support for the AOSP/Android framework version of Robolectric. That version of Robolectric was forked off an extremely old version of Robolectric and has evolved separately. I would make sure there aren't two versions of exoplayer in the classpath (e.g. you can try to print the classpath and see what's on there).

**Comment by gsnayma01** [comment]
This issue was partially fixed by creating shadow class of PlayerView and by adding the shadow config to each test method in my test class.

Here is the example of ShadowPlayerView 

```
package com.xxx.xxx.xxx.shadows;


import android.content.Context;
import android.util.AttributeSet;
import android.widget.FrameLayout;

import androidx.annotation.Nullable;

import com.google.android.exoplayer2.ui.PlayerView;

import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;
import org.robolectric.shadows.ShadowView;

@Implements(PlayerView.class)
public class ShadowPlayerView extends ShadowView {

    private static boolean mController;
    private static FrameLayout mFrameLayout;

    public void __constructor__(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
    }

    public static void setUseController(boolean controller) {
        mController = controller;
    }

    @Implementation
    public static boolean getUseController() {
        return mController;
    }
}
```


and use shadow config for each method including setUp method like below

 ```
 @Test
    @Config(shadows = {ShadowPlayerView.class})
    public void onMethodTest()
    {
          //your test code
    }
```
