### ISSUE TITLE
Referencing Android Library (apklib) resource files

### ISSUE THREAD

**Issue by blundell** [robolectric/robolectric#713]
So I've found out we need project.properties and to declare the apklib like so:

```
# File used by Eclipse to determine the target system
# Project target.
target=android-16
android.library.reference.1=gen-external-apklibs/com.actionbarsherlock_actionbarsherlock_4.4.0
```

However the issue now is IntelliJ needs them referencing in the folder

`android.library.reference.1=gen-external-apklibs/com.actionbarsherlock_actionbarsherlock_4.4.0`

and maven (ci) needs them referencing in the folder

`android.library.reference.1=target/unpack/apklibs/com.actionbarsherlock_actionbarsherlock_4.4.0`

Is there somewhere I can hook into the Robolectric java code to toggle this path? i.e. when Robolectric is looking for this path I could hook in and programmatically change the path rather than relying on the project.properties default

This has kind of been discussed by JetBrains already: http://youtrack.jetbrains.com/issue/IDEA-102296

**Comment by athkalia** [comment]
Someone seriously needs to documents issues like this, I spent 2 days trying to figure out what's going on

**Comment by erd** [comment]
Docs do exist: http://robolectric.org/using-libraries/

**Comment by athkalia** [comment]
yeah I noticed that. piece of documentation, but I don't find it to be sufficient. I can send an improved version if you like for you to upload ?

**Comment by erd** [comment]
You're welcome to send a pull request. The docs live in the `robolectric/robolectric.github.io` repository.
