### ISSUE TITLE
Getting illegalStateException when trying to lunch an activity using robolectric

### ISSUE THREAD

**Issue by riyadatik** [robolectric/robolectric#7173]
### Steps to Reproduce:
Case 1: 
ActivityController<A>con;
con = Robolectric.buildActivity(A.class);
Intent intent = con.get().getIntent();
intent.setAction(xyz);
intent.putExtra("abc", 1);
con.setup();

Here A is my target activity class which I want to lunch. But after run this code I got  illegalStateException. What is the reason for this error. Can anyone give any solution??

Case 2: 
ActivityController<Activity>con;
Intent intent = new Intent(xyz);
intent.putExtra("abc", 1);
con = Robolectric.buildActivity(Activity.class);
con.get().startActivity(intent);

In this case my target Activity is not lunched.

Can anypne give any solution how to fix this problem?

### Robolectric & Android Version
Robolectric version: 4.5.1
Android Version: R

**Comment by utzcoz** [comment]
Hi @riyadatik, could you try Robolectric 4.7.3 again? If you also encounter this problem with 4.7.3, could you follow https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues to provide a minimum reproduce demo for it?

**Comment by hoisie** [comment]
For case 1, maybe try using `Robolectric.buildActivity(Class<T> activityClass, Intent intent)`?

For case 2 -- in Robolectric, when `startActivity` is called, it does not actually start an activity. You can try getting the started activities by calling `Shadows.shadowOf(activity).getNextStartedActivity();`

These are just guesses though -- there are no real code samples or sample apps, and no complete stack traces. Closing this for now -- unfortunately there's nothing actionable here.
