### ISSUE TITLE
Investigate gradle/gradle-build-action@v2 to improve CI speed

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7174]
### Description

I have noticed some open-source projects started to use [gradle/gradle-build-action@v2](https://github.com/gradle/gradle-build-action) to fix cache problems and speed up CI, e.g. https://github.com/detekt/detekt/pull/3723. It will be great if we can investigate whether it can help Robolectric to reduce CI time.

### Steps to Reproduce

None.

### Robolectric & Android Version

Latest master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by Goooler** [comment]
Can I send a PR?

**Comment by hoisie** [comment]
We would appreciate anything that can make the build faster 😄 

I think there are more fundamental issues though. For instance build caching seems to be kind of broken (e.g. doing gradlew compile twice in a row causes things to be rebuilt). I never root caused that but it would be interesting to track those down.

**Comment by Goooler** [comment]
Addressed to #7195.
