### ISSUE TITLE
Remove unnecessary/redundant public shadow APIs

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7182]
For example, ShadowCompoundButton has a getButtonDrawable method: 'https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowCompoundButton.java#L38'

This does not need to be public -- it can just be protected, and getButtonDrawable can just be called on CompoundButton.

To be honest, maybe this entire shadow does not need to exist, but for now it would be good to just focus on getting rid of non-essential public shadow APIs.

**Comment by hoisie** [comment]
For example, ShadowCompoundButton has a `getButtonDrawable` method: 'https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowCompoundButton.java#L38'

This does not need to be `public` -- it can just be `protected`, and `getButtonDrawable` can just be called on CompoundButton.

To be honest, maybe this entire shadow does not need to exist, but for now it would be good to just focus on getting rid of non-essential public shadow APIs.

**Comment by hoisie** [comment]
Nevermind, I don't think this is particularly prevalent.

**Comment by utzcoz** [comment]
@hoisie What about renaming this issue to adding a task to identify those APIs in code base? For example, `./gradlew spotPublicShadowAPI`. It will be helpful for us to evaluate current status of public Shadow APIs, and find public Shadow APIs we should make them to protected again. I think it can be a task in annotation processor with clear rule for starter to do.
