### ISSUE TITLE
Bitmap-backed canvas.drawRect fails with paint

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7188]
```java
  @Test
  public void drawRect_toCanvas() {
    Bitmap bitmap = Bitmap.createBitmap(10, 10, Bitmap.Config.ARGB_8888);
    bitmap.eraseColor(Color.BLACK);
    assertThat(bitmap.getPixel(0, 0)).isEqualTo(Color.BLACK);

    Canvas canvas = new Canvas(bitmap);
    Paint paint = new Paint();
    paint.setStyle(Style.FILL);
    paint.setAntiAlias(true);
    paint.setColor(Color.WHITE);
    canvas.drawRect(0, 0, 10, 10, paint);
    assertThat(bitmap.getPixel(0, 0)).isEqualTo(Color.WHITE);
  }
```

**Comment by hoisie** [comment]
This test passes on an emulator, but fails in Robolectric with:

```
assertThat(bitmap.getPixel(0, 0)).isEqualTo(Color.WHITE);
Expected :-1
Actual   :-16777216
```

**Comment by s-deepak-kumar** [comment]
Please Assign It With Me.

**Comment by Akshay2131** [comment]
@hoisie i looked into it.. As output is coming as -16777216. In binary form, -16777216=11111111 00000000 00000000 00000000
 Here, representation of bits is as: first 8-bits: Alpha, second 8-bits: Red, third 8-bits: green and last 8-bits: blue.
Here, in -16777216 RGB bits are all 0. It means it represents fully opaque black color.
for white color, RGB should be all 1.
what u think @hoisie

**Comment by utzcoz** [comment]
@Akshay2131 you can use https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#toHexString(int) to identify different more convenient, e.g.

```Java
assertThat(Integer.toHexString(bitmap.getPixel(0,0)).isEqualsTo(Integer.toHexString(Color.WHITE));
```

>  Here, in -16777216 RGB bits are all 0. It means it represents fully opaque black color.

It represents `Bitmap-backed canvas.drawRect fails with paint`. It's recommend to see what Robolectric does to support Bitmap backed Canvas.

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/7210.
