### ISSUE TITLE
Migrate ProxyMaker to use Lookup.defineHiddenClass

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7190]
Currently [ProxyMaker](https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/internal/bytecode/ProxyMaker.java) uses Unsafe.defineAnonymousClass, which has been removed in JDK 17.

Robolectric itself does not use ProxyMaker much any more, but it is a public API, so some tests may use it.

It would be great to migrate it to Lookup.defineHiddenClass.

Guice recently did this migration as well: https://github.com/google/guice/pull/1529

**Comment by utzcoz** [comment]
We might need to improve the priority of this task to get better JDK 17 supporting for Robolectric.

**Comment by hoisie** [comment]
@utzcoz This has actually been fixed in AOSP in aosp/2146022:
https://cs.android.com/android/platform/superproject/+/master:external/robolectric-shadows/sandbox/src/main/java/org/robolectric/internal/bytecode/ProxyMaker.java

Do you want to copy and replace that file here?

**Comment by utzcoz** [comment]
@hoisie No problem. I will update it this weekend.
