### ISSUE TITLE
Add getCurrentSyncs() in ShadowContentResolver

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7191]
getCurrentSyncs, which is a static method, is not included in the ShadowContentResolver.

**Comment by Akshay2131** [comment]
Here, the method will be addded as : 
`@Implementation
  protected static List<SyncInfo> getCurrentSyncs() {
    ...
  }`
Now, in getCurrentSyncs() method do we need to get all the active syncs or could you suggest anything about it?

**Comment by Akshay2131** [comment]
`
@Implementation
  protected static List<SyncInfo> getCurrentSyncs()  {

    List<SyncInfo> list = new ArrayList<>();

    for(Map.Entry<String, Map<Account, Status>> map: syncableAccounts.entrySet()) {

      for(Map.Entry<Account, Status> mp: map.getValue().entrySet()) {

        if(isSyncActive(mp.getKey(), map.getKey())) {

            SyncInfo si = new SyncInfo(0, mp.getKey(), map.getKey(), 0);

            list.add(si);
        }
      }
    }
    return list;
  }
`

Here, SyncInfo' s object will contain Account and Authority fields as provided and authorityId along with startTime will be set to 0.

@hoisie what you think about this code?

**Comment by hoisie** [comment]
Thanks @Akshay2131. This approach seems about right to me. Whenever `ContentResolver.requestSync` is called, this should be included in the result from `ContentResolver.getCurrentSyncs`.

**Comment by hoisie** [comment]
Let's take the discussion to the PR.
