### ISSUE TITLE
Un-deprecate ActivityController

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7193]
Robolectric's ActivityController was deprecated in favor of ActivityScenario. While we should encourage uses of ActivityScenario, there are some legitimate reasons to keep ActivityController:

* ActivityController does not require adding an Activity to the manifest, which has a lot less boilerplate.
* ActivityController is idiomatic and consistent with how other components are initialized in Robolectric, e.g. services, content providers, backup agents, etc.. 
* ActivityController provides the ability to simulate potential bugs in Activities and other lifecycle events not present in ActivityScenario. For example, there could be a way to call the getDIrectActions method from Activity.

**Comment by utzcoz** [comment]
@hoisie Looks like `ActivityController`'s deprecation was removed: https://robolectric.org/javadoc/4.10/org/robolectric/android/controller/ActivityController.html.
