### ISSUE TITLE
ReflectionUtil broken on MacOS (on M1)?

### ISSUE THREAD

**Issue by alwa** [robolectric/robolectric#7212]
### Description
I have unit tests that pass on Windows and Linux but fail on MacOS Monterey 12.3 on the M1.

Crash:
```
Caused by:
            java.lang.IllegalAccessException: Can not set static final java.lang.String field com.mycompany.BuildConfig.BUILD_TYPE to java.lang.String
                at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
                at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
                at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
                at java.base/java.lang.reflect.Field.set(Field.java:799)
                at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:214)
                ... 2 more
```

### Steps to Reproduce

```kotlin
@Config(sdk = [Build.VERSION_CODES.P])
@RunWith(AndroidJUnit4::class)
class SomeFragmentTest {

    private lateinit var fragmentScenario: FragmentScenario<SomeFragment>

    @Before
    fun setUp() {
        MockitoAnnotations.openMocks(this)
        fragmentScenario = FragmentScenario.launch(SomeFragment::class.java)
    }

    @Test
    fun `this test crashes`() {
        ReflectionHelpers.setStaticField(BuildConfig::class.java, "BUILD_TYPE", "debug")
    }
```
### Robolectric & Android Version
Robolectric 4.7.3

**Comment by utzcoz** [comment]
@alwa The most related to `RelfectionHelpers` failed case is JDK version. Could you check and show your JDK versions on your different OS?

**Comment by alwa** [comment]
> @alwa The most related to `RelfectionHelpers` failed case is JDK version. Could you check and show your JDK versions on your different OS?

Hi, JDK versions below:
- 11.0.11 (OpenJDK) on Windows
- openjdk:11 docker image on CentOS / Red Hat Linux
- JDK 11 on MacOS as well. I have asked for the exact version... Will update this post when I know for sure

**Comment by hoisie** [comment]
If you are seeing this error in JDK 11, you are probably not actually using JDK 11. The restriction of setting static final fields was added in JDK 12:
http://mail.openjdk.java.net/pipermail/core-libs-dev/2018-November/056486.html

Ensure that the PATH and JAVA_HOME are set up properly.

There was a test for this in Robolectric:
https://github.com/robolectric/robolectric/blob/master/shadowapi/src/test/java/org/robolectric/util/ReflectionHelpersTest.java#L124-L136

And it has never failed in JDK 11.x.

That being said, this is an issue in JDK 12+, so if you are running into this, there are a couple of options:
1) If possible, refactor your code to avoid depending on setting static final fields. For instance, make them non-final `@VisibleForTesting`, or just use Dagger to inject named constants.
2) If you cannot change the code, you can use Robolectric instrumentation on your custom package to strip `final`. This involves adding `@Config(..., instrumentedPackages={"com.mycompany"})`. This is a crutch, though, and will slow down your tests. It is highly discouraged to use Robolectric instrumentation on your own code.
3) Use some Java agent-based approach to remove finals from your code. I am not sure what kind of options exist for that.

From Robolectric's perspective, we should probably just remove the logic from ReflectionHelpers that sets final static fields. Maybe we can do this for JDK 12+. This way the stack trace won't be in Robolectric.

**Comment by alwa** [comment]
OK, thanks. I'm afraid I cannot verify this so let's assume I was running JDK 12+ then.
Closing this...
