### ISSUE TITLE
NativeInput.MotionEvent.copyFrom does not make a deep copy of PointerProperties[]

### ISSUE THREAD

**Issue by jfresen** [robolectric/robolectric#7242]
### Description

When using `val copy = MotionEvent.obtain(event)`, the PointerProperties are not deep copied. When the source event is subsequently recycled, reused and repopulated, the copy's pointer properties are changed. I believe the problem is in the assignment `mPointerProperties = other.mPointerProperties` in [NativeInput.MotionEvent.copyFrom](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/NativeInput.java#L604)

### Steps to Reproduce

```
import android.view.MotionEvent
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

@RunWith(AndroidJUnit4::class)
@Config(minSdk = 21)
class RobolectricTest {
    @Test
    fun test() {
        val event1 = obtainFor(toolType = 1)
        assertEquals("ToolType of event1 must be 1", 1, event1.getToolType(0))

        val event1Copy = MotionEvent.obtain(event1)
        assertEquals("ToolType of event1Copy must be 1", 1, event1Copy.getToolType(0))

        event1.recycle()
        assertEquals("ToolType of event1Copy must be 1 after event1 is recycled", 1, event1Copy.getToolType(0))

        val event2 = obtainFor(toolType = 2)
        assertEquals("ToolType of event2 must be 2", 2, event2.getToolType(0))
        assertEquals("ToolType of event1Copy must be 1 after event2 is obtained", 1, event1Copy.getToolType(0))
    }

    private fun obtainFor(toolType: Int): MotionEvent = MotionEvent.obtain(
        /* downTime = */ 0,
        /* eventTime = */ 0,
        /* action = */ MotionEvent.ACTION_DOWN,
        /* pointerCount = */ 1,
        /* pointerProperties = */ arrayOf(
            MotionEvent.PointerProperties().apply {
                this.id = 0
                this.toolType = toolType
            }
        ),
        /* pointerCoords = */ arrayOf(
            MotionEvent.PointerCoords().apply {
                x = 0f
                y = 0f
            }
        ),
        /* metaState = */ 0,
        /* buttonState = */ 0,
        /* xPrecision = */ 1f,
        /* yPrecision = */ 1f,
        /* deviceId = */ 0,
        /* edgeFlags = */ 0,
        /* source = */ 0,
        /* flags = */ 0
    )
}
```

### Robolectric & Android Version

Robolectric: 4.7.3
Android: observed on 21+, but assuming it happens on any version

**Comment by utzcoz** [comment]
@jfresen Thanks for pointing out this problem. Looks like we can use [new MotionEvent.PointerProperties(other.mPointerProperties)](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/MotionEvent.java;l=4225-4227;drc=0d0f86c204f48493abf8eade995465872d1be565?q=MotionEvent.java&ss=android) directly to make a deep copy of `PointerProperties`. Could you help to send a PR for it if you have interested in this problem? Thanks.

**Comment by utzcoz** [comment]
@jfresen I sent a PR at https://github.com/robolectric/robolectric/pull/7251 for this issue.
