### ISSUE TITLE
Robolectric is silently skipping tests if includeAndroidResources = false

### ISSUE THREAD

**Issue by neworld** [robolectric/robolectric#7249]
### Description

According to build scans merging resources are not an easy task. For optimizing builds I disabled `includeAndroidResources` for some modules. The build was a success and a bit faster. However, after a few days, my coworker found some tests were skipped. Logs:
```
WARNING: No manifest file found at ./AndroidManifest.xml.
Falling back to the Android OS resources only.
To remove this warning, annotate your test class with @Config(manifest=Config.NONE).
No such manifest file: ./AndroidManifest.xml
```

So, I was surprised that I had broken tests and had no idea about it. 

Would be great to have a flag for enabling strict mode to avoid future accidents. It will enable us for disabling the `includeAndroidResources` for some modules and be sure nothing will be skipped by accident. 

### Robolectric & Android Version

Robolectric: 4.7.2
AGP: 7.1.2

**Comment by utzcoz** [comment]
@neworld Maybe this issue is duplicated to https://github.com/robolectric/robolectric/issues/6934.

**Comment by neworld** [comment]
Yes, it is related and could be a duplicate. My idea is to have build failures in something that is missing. Always. But https://github.com/robolectric/robolectric/issues/6934 is more like fixing a robolectric build issue, or [as stated in this comment](https://github.com/robolectric/robolectric/issues/6934#issuecomment-1001062064) failback to empty manifest, which covers some cases.

**Comment by hoisie** [comment]
I would be in favor of having the test process fail if no tests are run. I am not sure if this logic should be contained in AGP or in Robolectric though.

**Comment by neworld** [comment]
@hoisie, I am not sure if I understand your idea. The problem with Roboletric is that some tests are skipped if some problems occur. From my point of view, it is unusual and unexpected behavior. So, from AGP or Gradle side checking skipped tests will not help much, because we have some tests skipped for good reasons (for example long tests), and even some modules have all tests skipped. 

I believe tests are skipped for good reason, so my proposal is to implement a strict mode. The flag is enough for us:
```
systemProperty 'robolectric.runner.mode', 'strict'
```

**Comment by inkredusk** [comment]
I am using roboelectric version 4.9. Is this flag **systemProperty 'robolectric.runner.mode', 'strict'** a part of the recent version or will it be implemented in future ?
