### ISSUE TITLE
`requestDisallowInterceptTouchEvent` doesn't propagate

### ISSUE THREAD

**Issue by wesalvaro** [robolectric/robolectric#7266]
### Description
The `ViewGroupShadow` does not propagate `requestDisallowInterceptTouchEvent`. This leads to bugs in testing when that feature is needed.

### Robolectric & Android Version
head & any

**Comment by wesalvaro** [comment]
I have an internal cl/443649582 to fix this.

**Comment by utzcoz** [comment]
Hi @wesalvaro Could you contact @hoisie internally to sync it to public repo? Thanks.

**Comment by wesalvaro** [comment]
Roger roger.

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/commit/ea3e5d1a15c352e600ea54fa4fafc70611f8db1d. It will be merged into master branch at next period.
