### ISSUE TITLE
Description is different in bitmap when use `decodeByteArray` method to generate bitmap

### ISSUE THREAD

**Issue by charlesng** [robolectric/robolectric#7281]
### Description

I have 1 feature to convert the encoded base64 string to bitmap  so I used the following testcase to check if my encoded base64 string `Hello, world` can be decoded successfully and then verified in bitmap description. But after i upgraded to 4.8 today i got fail in this test case. Does the behaviour changed in bitmap in robolectric 4.8? 🤔 

Appreciate any comment / advise if i didn't use it properly.

```
   @Test
    fun should_return_correct_bitmap_from_base64_string() {
        // given
        val imageString = "Prefix,SGVsbG8sIFdvcmxk"

        // when
        val encodedImage = imageString.substring(imageString.indexOf(",") + 1)
        val decodedBytes: ByteArray = Base64.decode(encodedImage, Base64.DEFAULT)
        val bitmap = BitmapFactory.decodeByteArray(decodedBytes, 0, decodedBytes.size)
        val shadow = shadowOf(bitmap)

        // then
        assertEquals("Bitmap for Hello, World", shadow.description)
    }

```

### Steps to Reproduce

As above

Now the result is 
<img width="590" alt="Screenshot 2022-04-29 at 11 05 31 PM" src="https://user-images.githubusercontent.com/5112837/165972165-9e7f6259-17f6-43b0-9155-e7b27c4ca4c2.png">

### Robolectric & Android Version
Robolectric 4.8 , Android SDK = 32, AGP 7.1.2

### Link to a public git repo demonstrating the problem:
N/A

**Comment by utzcoz** [comment]
@charlesng Thanks for reporting this problem. This behavior is brought in by commit https://github.com/robolectric/robolectric/commit/f86d4b125e8cf197b428dc02a8c7320339736f3e. Looks like it is an expected behavior, @hoisie is that right?

**Comment by hoisie** [comment]
@paulsowden 

Yeah, the idea of putting the image bytes in the bitmap description is simply not possible when real bitmap data is used (e.g. using BitmapFactory.decode(...) with real image data, the string is just a jumbled mess. I think the reason for this change was performance-related for large images. @paulsowden has more details I believe.

**Comment by paulsowden** [comment]
Yeah, decoding bitmap bytes as UTF-8 encoded string was causing allocation issues with large bitmap byte arrays, and as this behavior is not representative of what real Android does we had to alter the shadow behavior to support the real case.

So in practice your test is not really asserting correct Android behavior, Android will never decode a byte array passed in to `BitmapFactory` as a string. If you wish to exercise this test case you can change your assert to something like:

```java
assertThat(new String(shadowOf(bitmap).getCreatedFromBytes(), UTF_8)).isEqualTo("Hello, World");
```

(sorry, not so familiar with Kotlin syntax), but this will do what your test was previously asserting but keeps the assumption that the bitmap bytes are string encoded bytes in the test case.

**Comment by paulsowden** [comment]
I would say in general as well that it should be considered legacy behavior to pass in non-bitmap data to a `BitmapFactory`, for example some code under test may wish to assert that `BitmapFactory` doesn't produce a valid `Bitmap` when it is given garbelled bytes, today `BitmapFactory` happily returns a `Bitmap`, but this is a limitation of the shadow rather than correct behavior. So I would encourage you to consider alternative method for asserting correctness than passing in string encoded bytes to `BitmapFactory`.

**Comment by utzcoz** [comment]
@charlesng Looks like previous explanation solves your problem. Feel free to reopen this issue if you have other problems.
