### ISSUE TITLE
Shadows.shadowOf() raise compile error since Robolectric 4.8

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#7286]
### Steps to Reproduce
1. clone sample source
  ```
  $ git clone https://github.com/ganadist/VersionCodeDemo -b robo48_compile_error
  $ cd VersionCodeDemo 
  $ ./gradlew :app:testDevelopDebugUnitTest
  > Task :app:compileDevelopDebugUnitTestJavaWithJavac FAILED
  app/src/test/java/com/example/myapplication/TelephonyTest.java:24: error: cannot access BackdropFrameRenderer
      ShadowTelephonyManager shadow = Shadows.shadowOf(tM);
                                               ^
   class file for com.android.internal.policy.BackdropFrameRenderer not found
   1 error

   FAILURE: Build failed with an exception.
  ```

### Robolectric & Android Version
* Robolectric 4.8
* CompileSdk/TargetSdk 32

### Link to a public git repo demonstrating the problem:
* https://github.com/ganadist/VersionCodeDemo/tree/robo48_compile_error

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/7284.

**Comment by utzcoz** [comment]
Hi @ganadist , could you test 4.8.1 to check whether it fixes your problem? Thanks.

**Comment by ganadist** [comment]
@utzcoz , 
Sure, I already tested, and `4.8.1` fixed my problem.
Thank you very much!

**Comment by utzcoz** [comment]
@ganadist Thanks for testing.

**Comment by jhwsx** [comment]
4.8.1 REALLY works.
