### ISSUE TITLE
Skips tests apove api 29 in Kotlin Multiplatform

### ISSUE THREAD

**Issue by Nailik** [robolectric/robolectric#7306]
### Description
I am using robolectric in Koltin Multiplatform to have a context.
When i set maxSDK to above 28 i see that for api API that's > 28 all my tests show
```
STARTED
SKIPPED
```

without any information why it does this.

### Steps to Reproduce
in commonTest i use 
`expect abstract class UsingContextTest() { } `
that's then implemented in androidTest as
```
@RunWith(RobolectricTestRunner::class)
@Config(maxSdk = 30, minSdk = 27)
actual abstract class UsingContextTest { } 
```

The implementation in commonTest for tests is:
```
class TestFile : UsingContextTest() {
    @Test
    fun checkTest() {

    }
}
```

When i run the test my result is

```
TestFile > checkTest[27] STARTED
TestFile > checkTest[27] PASSED
TestFile > checkTest[28] STARTED
TestFile > checkTest[28] PASSED
TestFile > checkTest[29] STARTED
TestFile > checkTest[29] SKIPPED
TestFile > checkTest STARTED
TestFile > checkTest SKIPPED

```

When i use the same Code inside an android projects test folder everything works as expected (all tests are executed)

### Robolectric & Android Version
V 4.8.1

**Comment by utzcoz** [comment]
@Nailik If you want to run all your tests, you can set `maxSdk=30`.

**Comment by Nailik** [comment]
setting `maxSdk=30` in `robolectric.properties` results in the same issue.
The tests from API 16 until API 28 are all successfull and the tests above all getting skipped.
 ```
compileSdk = 32
    defaultConfig {
        minSdk = 21
        targetSdk = 32
    }
```

i will create a minimal reproduce app

**Comment by Nailik** [comment]
There it is, see `commonTest/kotlin/.../commonTest` the `testExample `
i also added an output to show that the tests are not executed above api 28

https://github.com/Nailik/HelloKMM

**Comment by utzcoz** [comment]
@Nailik Feel free to  reopen this issue if you have other problem/issue.

**Comment by Nailik** [comment]
@utzcoz first tests look good for now, thank you for the fast response.
Maybe it would be nice to add WHY a test was Skipped in the log output.
Or adding some information to the Getting Started page like "without ... your tests might be skipped above api 29".

**Comment by utzcoz** [comment]
@Nailik Thanks for suggestion. I will try to add a log for it.
