### ISSUE TITLE
RXJava & RXAndroid Problem  

### ISSUE THREAD

**Issue by Nodrex** [robolectric/robolectric#7326]
### I am using RXJava  like this:
```
class MyInteractor {
    fun myF() {
        myInteractor.signIn()
              .observeOn(AndroidSchedulers.mainThread())
              .compose(errorDialogTransformer())
              .subscribe(Consumer {
                //Do some stuff
         }
    }
}
```
`signIn()` is suspend function which returns `Single<Account>`
and then I am testing it with roboelectric like this:

```
@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE, application = TestApp::class)
class MyTestClass {

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()
    
    lateinit var myInteractor: MyInteractor

   @Before
    fun setUp() {
        MockKAnnotations.init(this)
        myInteractor= MyInteractor()
    }

    @Test
    fun myTest() {
        coEvery {
                    myInteractor.signIn()
                } returns Single.just(account)
        
        myF()
    }
}
```
and unfortunately `Consumer` is not called on the latest 4.8.1  version, however, it works on older 4.2.1 version

> Robolectric version 4.8.1 
RXAndroid version 2.1.1
RXJava version 2.2.19
kotlin version 1.5.21
Junit version 4.13.2
mockk version 1.10.6

**Comment by utzcoz** [comment]
@Nodrex Could you try `@LooperMode(LEGACY)` to your test, and run it with 4.8.1? Maybe your problem is related to http://robolectric.org/blog/2019/06/04/paused-looper/.

**Comment by hoisie** [comment]
@Nodrex maybe you need to use `Shadows.shadowOf(Looper.getMainLooper()).idle();`. I would not recommend using LEGACY looper mode, it breaks everything in subtle ways, such as AndroidX fragments.

Can you put up a sample app that demonstrates the issue? RxJava is mostly a Java library that does not rely on many Android specific features so it should work fine in a Robolectric environment.

**Comment by Nodrex** [comment]
Thanks for the answers @utzcoz @hoisie 
We already fixed it by injecting `TestScheduler()` and calling `testScheduler.triggerActions()` after function call.
So I am closing this issue
