### ISSUE TITLE
When does Robolectric support Android 13 ?

### ISSUE THREAD

**Issue by simple-kss** [robolectric/robolectric#7333]
### Description
Dear developers,  

Can I ask for when robolectric supports Android 13 (Andorid T) ?
Currently, I'm making application on Android 13.
And, I want to test the app using robolectric framework.
But, I believe that robolectric framework doesn't support Android 13.

so, I want to know when robolectric supports Android 13. 
Thank you.

**Comment by utzcoz** [comment]
@hoisie This type of problem is very common. What about opening a new question discussion, you answer it, selecting your answer as final answer and pin it to discussion top.

**Comment by hoisie** [comment]
Added a new discussion: https://github.com/robolectric/robolectric/discussions/7338
