### ISSUE TITLE
Rename top project's name from "parent" to "robolectric"

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7346]
### Description

As @ZSmallX suggested, we can use "robolectric" for top project's name when importing from Android Studio. And some folks have been confused by current "parent" name many times when switching recent projects from Android Studio's menu. It's better if we can change its name and reduce this annoying thing.

### Steps to Reproduce

Importing current source code from Android Studio.

### Robolectric & Android Version

Latest master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by hellosagar** [comment]
Can I raise the PR for this?

**Comment by hellosagar** [comment]
https://github.com/robolectric/robolectric/pull/7347

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/7347.
