### ISSUE TITLE
File.separator is incorrect when running unit test on windows

### ISSUE THREAD

**Issue by jnhyperion** [robolectric/robolectric#7390]
### Steps to Reproduce
Method to be tested:
```
public static void readAssetFile(String folderName, String fileName) throws IOException { 
         ApplicationProvider.getApplicationContext().getAssets().open(folderName + File.separator + fileName); 
}
```
Add assets in test:
test/assets/foo/bar.txt

Run test in windows:

```
@RunWith(AndroidJUnit4.class) 
@Config(sdk = Build.VERSION_CODES.P) 
public class ExampleUnitTest {     
@Test     
public void testExample() throws Throwable {         
       Utils.readAssetFile("foo", "bar.txt");     
} 
}
```

Test will fail:

java.io.FileNotFoundException: foo\bar.txt

	at org.robolectric.shadows.ShadowArscAssetManager9.nativeOpenAsset(ShadowArscAssetManager9.java:733)
	at android.content.res.AssetManager.nativeOpenAsset(AssetManager.java)
	at android.content.res.AssetManager.open(AssetManager.java:744)
	at android.content.res.AssetManager.open(AssetManager.java:721)

### Robolectric & Android Version
Robolectric 4.6.1
### Link to a public git repo demonstrating the problem:

**Comment by utzcoz** [comment]
@jnhyperion could you provide a minimal demo that can reproduce this problem?

**Comment by jnhyperion** [comment]
@utzcoz https://github.com/jnhyperion/RobolectricDemo

unit test: robolectric.demo.test.ExampleTest#testExample

will pass on Mac and fail on windows

**Comment by utzcoz** [comment]
@jnhyperion You can replace `File.separator` with "/" when creating path for Android's assets, because Robolectric stores file path with "/" as path separator. I have tested your test with "/" on Windows, and it can work.

> will pass on Mac and fail on windows

The test can pass on macOS because macOS is *NIX system, and it uses "/" as file separator, the same as Linux and Android.

@hoisie Should we add support Window's `File.separator` in `ZipFileRO#findEntryByName` ?

**Comment by utzcoz** [comment]
@jnhyperion you can write a util method to use `/` as file separator, and it can work on all platforms, including Windows. Feel free to reopen this issue if you have any questions. Thanks.
