### ISSUE TITLE
Cannot restart SQLite connection on Apple M1

### ISSUE THREAD

**Issue by wu-hui** [robolectric/robolectric#7413]
### Description
A exception is thrown when trying to get a connection to a DB even after a previous connection is closed. This only happens on M1 hardware, other platforms are all ok.

### Steps to Reproduce
Simply run the test from the repo below

### Robolectric & Android Version
See below link

### Link to a public git repo demonstrating the problem:

https://github.com/wu-hui/RobolectricSqlite

**Comment by utzcoz** [comment]
@wu-hui M1 uses native SQLite mode default, and other arch machines uses legacy SQLite mode default. Maybe it is a problem of native SQLite mode. Thanks for reporting this problem, and I will check it this weekend.

**Comment by hoisie** [comment]
What happens when that test is run on real Android?

Not sure if this is related, but in Robolectric, the default sync mode is set to OFF (equivalent to`PRAGMA synchronous=OFF`). This is because all dbs are blown away after each test method, so it is not imperative to wait for a fsync when writing data. It is also a MASSIVE performance improvement (50%)? See #6687 and #6690

**Comment by utzcoz** [comment]
I sent a PR to add test for EXCLUSIVE mode, and [it](https://github.com/robolectric/robolectric/pull/7416) can confirm that close and then open database by `SQLiteOpenHelper` can work with EXCLUSIVE mode on Emulator and Robolectric's legacy SQLite mode, but failed on native SQLite mode. It can be used for later investigation.

**Comment by hoisie** [comment]
I think I have a fix for this.

I believe that [ShadowNativeSQLiteConnection](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowNativeSQLiteConnection.java) was missing the `nativeClose` method. This means that the native side of the database was never relased. Yikes. Thanks for pointing this out.

A PR to fix this will be forthcoming.

**Comment by wu-hui** [comment]
Can I get a release version and a date (if not yet released)? Thank you!

**Comment by hoisie** [comment]
I am willing to do a minor release, 4.8.2, with this fix and possibly a few others

**Comment by wu-hui** [comment]
Do we know roughly when 4.8.2 will be out yet? Thanks!

**Comment by utzcoz** [comment]
> Do we know roughly when 4.8.2 will be out yet? Thanks!

Sorry for delaying. Maybe we can cc @hoisie and @JuliaSullivanGoogle.

**Comment by hoisie** [comment]
FYI 4.8.2 was just released that contains this fix.

**Comment by wu-hui** [comment]
Thank you!
