### ISSUE TITLE
How about migrating the project from java to kotlin.

### ISSUE THREAD

**Issue by adicoder95** [robolectric/robolectric#7420]
Kotlin based apps can perform better, thus making the app smoother.
I am a Kotlin developer and I would love to contribute in this project.

**Comment by utzcoz** [comment]
We don't want to convert the entire project to Kotlin with now compatibility concerning. And @hellosagar is trying to migrating some tests from Java to Kotlin for testing purpose at GSoC 2022 project. We will decide to whether to continue converting other tests from Java to Kotlin after GSoC project finished based on this project's experiment. Before that, we're caution to convert files from Java to Kotlin. If you have interested in this topic, you can pay attention to later discussion after GSoC 2022. Thanks for your suggestion.
