### ISSUE TITLE
Call Robolectric.buildActivity in ShadowActivityTest with Java's try-with-resource grammer to close ActivityController after test

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7439]
### Description

There are some direct callings of `Robolectric.buildActivity` in `ShadowActivityTest` without `try-with-resource` grammer to close `ActivityController` after usage, and the Android Studio shows some warnings for us. It's better if we can use `try-with-resource` to auto-close `ActivityController` after test.

### Steps to Reproduce

Using Android Studio to open Robolectric's `ShadowActivityTest`, and we can see above warnings.

### Robolectric & Android Version

Robolectric latest master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by arinmodi** [comment]
@utzcoz, I opened a PR for this, please review,

Thanks.
