### ISSUE TITLE
RoboCookieManager.removeSessionCookies(null) causes NPE

### ISSUE THREAD

**Issue by tinsukE** [robolectric/robolectric#7472]
### Description
Calling `RoboCookieManager.removeSessionCookies(ValueCallBack)` with a null `ValueCallback` results in a `NullPointerException`.

`CookieManager`s doc is quite clear that it is a valid use case:
> You can pass null as the callback if you don't need to know when the operation completes or whether any cookie were removed, and in this case it is safe to call the method from a thread without a Looper.

https://developer.android.com/reference/android/webkit/CookieManager#removeSessionCookies(android.webkit.ValueCallback%3Cjava.lang.Boolean%3E)

One could argue that there is a `CookieManager.removeSessionCookie()` (no callback) that could be used instead, but that method is deprecated.

In fact, all the methods that receive a `ValueCallback` should accept null values.

### Steps to Reproduce

Call `RoboCookieManager.removeSessionCookies(null)`

### Robolectric & Android Version

Current master code:
https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/android/webkit/RoboCookieManager.java#L62

**Comment by utzcoz** [comment]
@tinsukE Good catch. Could you help to send a PR to fix it? I think it is easy to apply a null checking for this method.
