### ISSUE TITLE
ShadowCountDownTimer not work

### ISSUE THREAD

**Issue by WingsII** [robolectric/robolectric#7479]
### Description

If CountDownTimer is used in the code, robolectric will automatically use ShadowCountDownTimer, I found that it cannot trigger onTick() callback. And its internal data (mHandler, etc.) are empty.
![image](https://user-images.githubusercontent.com/35595855/182993221-eabab3c3-f4d0-4842-a74b-f2f38ea736b8.png)
![image](https://user-images.githubusercontent.com/35595855/182993264-a7eb8dc8-72e8-46c7-afa0-bd270e840fa5.png)

If I use the original CountDownTimer object, or a custom empty Shadow object, this problem does not occur. Member variables are also normal.
![image](https://user-images.githubusercontent.com/35595855/182993454-2ab617e3-a20e-4b5d-9640-798c1059c50a.png)
![image](https://user-images.githubusercontent.com/35595855/182993649-343c354f-2dbe-495b-9a7d-3ef40ae4c609.png)

### Steps to Reproduce
Create a CountDownTimer in the Test case and run timer.start(), its member variables are empty, and will not trigger onTick.

### Robolectric & Android Version
Robolectric : 4.2.1
JDK 1.8.0_332

### Link to a public git repo demonstrating the problem:
NA

**Comment by utzcoz** [comment]
Hi @WingsII , 4.2.1 is old in a sense. Could you try latest 4.8.1 to check whether this problem was fixed? I remember there are some fixes were checked in for time. Looking forward your feedback. Thanks.

**Comment by WingsII** [comment]
> Hi @WingsII , 4.2.1 is old in a sense. Could you try latest 4.8.1 to check whether this problem was fixed? I remember there are some fixes were checked in for time. Looking forward your feedback. Thanks.


After testing, this problem still exists on the latest version.

### Robolectric & Android Version
Robolectric : 4.8.1
JDK 11.0.11

**Comment by hoisie** [comment]
Ah good catch. I notice that ShadowCountDownTimer's `__constructor__` shadow method does not invoke the original constructor. This ruins the normal object initialization process and leaves a lot of the members uninitialized. It should have a call to Shadow.invokeConstructor.

https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowCountDownTimer.java

**Comment by hoisie** [comment]
@WingsII from the shadow API it appears thata you have to call ShadowCountDownTimer.invokeTick:

https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowCountDownTimer.java#L34-L36

**Comment by hoisie** [comment]
Looks like the real code uses SystemClock.elapsedRealtime(), which gives a virtual/fake time in Robolectric. However, it should be possible to idle the scheduler to invoke the ticks.

**Comment by WingsII** [comment]
> 看起来真实的代码使用 SystemClock.elapsedRealtime()，它在 Robolectric 中提供了虚拟/假时间。但是，应该可以让调度程序空闲来调用滴答声。

There are several points:
1. In the real environment, CountDownTimer is a local variable and cannot be called directly.

2. I tried to write ShadowLooper.idleMainLooper(*); but it still doesn't work actually.

3. According to the source code, as long as it is initialized correctly, when CountDownTimer::start() is used, onTick() will be called once.

4. Now the core question is, why after the ShadowCountDownTimer is initialized, the member variables are all empty? I think this is the main reason why it can't work.
![image](https://user-images.githubusercontent.com/35595855/183228391-3a016d0a-d593-40e6-80d1-374a9d4e248e.png)

**Comment by hoisie** [comment]
> Why doesn't ShadowCountDownTimer invoke the original constructor when it initializes. Is this a bug or is there some reason? Will it be fixed later?

It is because the constructor of CountDownTimer is shadowed in ShadowCountDownTimer (the `__constructor__` method). I would agree that this is a bug. The `__constructor__` method should call the original constructor as well.

**Comment by hoisie** [comment]
Specifically, the constructor should probably be doing this:


```java
  @Implementation
  protected void __constructor__(long millisInFuture, long countDownInterval) {
    this.countDownInterval = countDownInterval;
    this.millisInFuture = millisInFuture;
    this.started = false;
    Shadow.invokeConstructor(
        CountDownTimer.class,
        countDownTimer,
        ClassParameter.from(long.class, millisInFuture),
        ClassParameter.from(long.class, countDownInterval));
  }
```

**Comment by WingsII** [comment]
> Specifically, the constructor should probably be doing this:
> 
> ```java
>   @Implementation
>   protected void __constructor__(long millisInFuture, long countDownInterval) {
>     this.countDownInterval = countDownInterval;
>     this.millisInFuture = millisInFuture;
>     this.started = false;
>     // call the original constructor
>     Shadow.invokeConstructor(
>         CountDownTimer.class,
>         countDownTimer,
>         ClassParameter.from(long.class, millisInFuture),
>         ClassParameter.from(long.class, countDownInterval));
>   }
> ```

It works, great!
