### ISSUE TITLE
Testing Async Http calls using Robelectric

### ISSUE THREAD

**Issue by timsaunders** [robolectric/robolectric#748]
Hi I am trying to test a async http request using Robelectric, however am having trouble. I am making the following calls

```
    AsyncHttpClient client = new AsyncHttpClient();

    client.post("http://www.example.com", someRequestParams, new AsyncHttpResponseHandler()
    {
        @Override
        public void onSuccess(String response) {
               System.out.println("Success");        
        }

        @Override
        public void onFailure(Throwable t, String error)
        {
               System.out.println("Failed");
        }
    });
```

Can you give me some direction on how to test a call. I would like to be able to test that it makes it into the response handler and confirm that the callback is being made.

**Comment by missrezai8-lgtm** [comment]
AsyncHttpClient client = new AsyncHttpClient();

client.post("http://www.example.com", someRequestParams, new AsyncHttpResponseHandler()
{
    @Override
    public void onSuccess(String response) {
           System.out.println("Success");
    }

    @Override
    public void onFailure(Throwable t, String error)
    {
           System.out.println("Failed");
    }
});
