### ISSUE TITLE
Android API 31 Dependency issues 

### ISSUE THREAD

**Issue by matthewfinn** [robolectric/robolectric#7595]
### Description

Tests using RobolectricTestRunner fail to run when targeting Android API 31 fail to fetch dependencies from Maven

Each time the error returned is 
```
ERROR: Failed to fetch maven artifact org.robolectric:android-all-instrumented:9-robolectric-4913185-2-i4
java.util.concurrent.ExecutionException: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"
```

### Steps to Reproduce

Run any test that uses RobolectricTestRunner test in an Android application

### Robolectric & Android Version

Android Version 12
Robolectric version 4.8.2

**Comment by hoisie** [comment]
If you are seeing this error it means your Robolectric process is configured to use a proxy server for some reason (i.e. setting `http.proxyHost`). If this is the case it is not really possible for us to debug your HTTP proxy settings. I would ensure that the proxy host and port are valid.

**Comment by hoisie** [comment]
I would recommend taking a glance at https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html to determine which environment variables may be set.
