### ISSUE TITLE
Robolectric is incompatible with Java 19

### ISSUE THREAD

**Issue by colinrtwhite** [robolectric/robolectric#7642]
### Description
Robolectric tests fail when using a Java 19 JDK. Java 19 was released as stable on September 20th, 2022.

### Steps to Reproduce
Run `brew install zulu` and update your `JAVA_HOME` environment variable to the Java 19 JDK.

Create a basic Robolectric test that uses any Android framework class. E.g.:

```kotlin
@Test
fun test() {
    android.util.Size(0, 0)
}
```

When the test is run it fails with the following exception:

```kotlin
java.lang.NoClassDefFoundError at Shadows.java:2539
    Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
        Caused by: java.lang.IllegalArgumentException at ClassReader.java:199
```

### Robolectric & Android Version
Robolectric `4.8.2`, though it also fails with `4.9-alpha-1`
Any Android version, though I tested with `sdk=32`

### Link to a public git repo demonstrating the problem:
The tests in [this repo](https://github.com/coil-kt/coil) reproduce the issue if you're using a Java 19 JDK. Run `./gradlew test` to execute the Robolectric tests.

**Comment by utzcoz** [comment]
@colinrtwhite I updated ASM to 9.3 to support Opcodes.V19 at https://github.com/robolectric/robolectric/issues/7620, and I will check local snapshot of latest master branch of Robolectric to check whether I can run simple tests with Robolectric and JDK 19.

**Comment by utzcoz** [comment]
Hi @colinrtwhite , I tested coil with latest Robolectric master branch, and I can run all coli tests with JDK 19 with following modification:

```Kotlin
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            all {
                it.jvmArgs(listOf(
                    "--add-opens=java.base/java.lang=ALL-UNNAMED",
                    "--add-opens=java.base/java.util=ALL-UNNAMED"
                ))
            }
        }
    }
```

You can wait the next alpha/stable release of Robolectric for JDK 19 supporting. Hi @hoisie what about releasing another alpha release next week?

**Comment by utzcoz** [comment]
I sent a PR(https://github.com/coil-kt/coil/pull/1475) for coil to open these modules.

**Comment by hoisie** [comment]
Let's just release 4.9 next week, no more alphas. I just have 2 or 3 more changes I'd like to get in.

Also we should file a big against AGP to add those `add-opens` by default. It would be a massive amount of confusion to force everyone to add it.

**Comment by hoisie** [comment]
Thanks @utzcoz for the investigation.

**Comment by colinrtwhite** [comment]
@utzcoz Thanks for looking into this so quickly + the work-around! If the plan is to release 4.9 next week I'll wait for the release, else I can use the work-around. Thanks again!

**Comment by hoisie** [comment]
Filed https://issuetracker.google.com/issues/248929512 for AGP.

**Comment by hoisie** [comment]
FYI 4.9 is released which should resolve this specific issue.

**Comment by colinrtwhite** [comment]
Awesome, thanks for the quick turnaround! Closing this since it's now resolved.

**Comment by utzcoz** [comment]
@colinrtwhite Looks like you don't need to add 

```Groovy
                it.jvmArgs(listOf(
                    "--add-opens=java.base/java.lang=ALL-UNNAMED",
                    "--add-opens=java.base/java.util=ALL-UNNAMED"
                ))
```

when updating CI's JDK to 19.  I don't know find related commit from coil for it. Is that right?

**Comment by colinrtwhite** [comment]
@utzcoz Yep, looks like it doesn't need it. This commit (and all new commits on `main`) is built with the latest Zulu JDK 19 and Robolectric 4.9.

**Comment by colinrtwhite** [comment]
Interesting! Maybe it's related to the distribution? I run Zulu locally + on CI.

**Comment by utzcoz** [comment]
> Interesting! Maybe it's related to the distribution? I run Zulu locally + on CI.

I also use Zulu locally. If someone encountered similar problem, he/she can pick similar add-opens for projects. It's great that coil doesn't need it.

**Comment by MaderaJan** [comment]
Increase Robolectric version to **2.51.1** fix the issue for me.
