### ISSUE TITLE
Security warning on https://robolectric.org

### ISSUE THREAD

**Issue by TonyTangAndroid** [robolectric/robolectric#7676]
This is what I see when I open the link from Chrome Android browser.

https://robolectric.org/blog/2022/09/06/Umesh-GSoC-on-ConscryptMode/

![Screenshot_20221003-120142.jpg](https://user-images.githubusercontent.com/8612724/193657758-f8e57c72-e050-4f59-9cd3-3b75561644e1.jpg)

**Comment by hoisie** [comment]
More context here:
https://github.com/robolectric/robolectric/issues/5358

Currently the robolectric.org domain name is owned by Pivotal/VMWare, so I am unable to make updates to it.

I have reached out to someone who works there, so hopefully we can do something about this. It may take some time though.

**Comment by hoisie** [comment]
I think this is fixed now. Can you check again?

**Comment by utzcoz** [comment]
@hoisie Cool. Firefox and Chrome don't show warnings any more.
