### ISSUE TITLE
Migrate if statement with useLegacy() to assumeTrue/assumeFalse

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7689]
Using `assumeTrue/assumeFalse` to skip tests when using legacy resource/not using legacy resource is more clear than current `if (!useLegacy()) return` and `if (useLegacy()) return` or similar logic.

**Comment by Gairick52** [comment]
@utzcoz i am new to open source can you suggest me some beginner friendly issues

**Comment by utzcoz** [comment]
@Gairick52 IMO, this issue is great for beginner. You can search and learn what `assumeTrue/assumeFlase` of junit do, and search Robolectric's code repository to find `if (!useLegacy()) return` and `if (useLegacy()) return` or similar patterns, and use `assumeTrue/assumeFalse` to refactor them. You can follow http://robolectric.org/building-robolectric/ to setup Robolectric's local development environment firstly. And following http://robolectric.org/contributing/ to ensure your code meets Robolectric's code style before pusing code with PR.

**Comment by Gairick52** [comment]
@utzcoz thanks you very much for your guidance
