### ISSUE TITLE
LocaleManager.getSystemLocales() returns null on api 33

### ISSUE THREAD

**Issue by lsuski** [robolectric/robolectric#7803]
### Description
I have such simple tests
```
 @Test
    @Config(qualifiers = "de")
    fun `test getSystemLanguage`() {
        assertEquals("de", application.getSystemService<LocaleManager>()?.systemLocales?.get(0)?.language)
    }
```
and it fails because systemLocales are null

### Robolectric & Android Version
Android 13, api 33

Robolectric 4.9

**Comment by utzcoz** [comment]
@lsuski Thanks for reporting this issue. Looks like `ShadowLocaleManager` doesn't support the shadow of `getSystemLocales()`.  Would you like to support it with a new PR?

**Comment by lsuski** [comment]
I don't know fully how shadows work but my guessing was that whatever is not overriden should work the same or in reasonable default and shadowing is mainly for easier testing. I don't need to override default system locale. I would expect that `getSystemLocales()` should return some reasonable value. If it's not possible then I can add PR

**Comment by utzcoz** [comment]
@lsuski I sent a PR at https://github.com/robolectric/robolectric/pull/7804 to try to fix this issue.
