### ISSUE TITLE
Still get java.lang.RuntimeException: Stub! in Robolectric 2.2

### ISSUE THREAD

**Issue by cliff76** [robolectric/robolectric#781]
I have a fairly complicated app that I'm trying to use with Robolectric 2.2. I've added the robolectric jar to the top of my classpath in IntelliJ but I still get:

Caused by: java.lang.RuntimeException: Stub!
    at com.amazon.device.messaging.ADMMessageReceiver.<init>(Unknown Source)
    at com.my.android.push.adm.ADMPushMessageReceiver.<init>(ADMPushMessageReceiver.java:15)
    ... 31 more

My classpath is:
robolectric
junit-4.10
app dependencies

I've also tried:
junit-4.10
robolectric
app dependencies

I use this ivv.xml to retreive my dependencies:

```
<ivy-module version="2.0">
    <info organisation="com.my.android" module="unit-test" />
    <configurations>
        <conf name="binaries" description="binary jars" />
    </configurations>
    <dependencies>
        <dependency org="org.robolectric" name="robolectric" rev="2.2" conf="binaries->default" />
        <dependency org="jmock" name="jmock" rev="1.2.0" conf="binaries->default" />
    </dependencies>
</ivy-module>
```

and that brings down all of these jars which I add to my class path:

```
ant-launcher.jar        commons-codec.jar       maven-artifact-manager.jar  nekohtml.jar            wagon-file.jar
ant.jar             commons-logging.jar     maven-artifact.jar      objenesis.jar           wagon-http-lightweight.jar
asm-analysis.jar        fest-reflect.jar        maven-error-diagnostics.jar plexus-container-default.jar    wagon-http-shared.jar
asm-commons.jar         fest-util.jar           maven-model.jar         plexus-interpolation.jar    wagon-provider-api.jar
asm-tree.jar            httpclient.jar          maven-plugin-registry.jar   plexus-utils.jar        xercesMinimal.jar
asm-util.jar            httpcore.jar            maven-profile.jar       robolectric.jar
asm.jar             jmock.jar           maven-project.jar       sqlite-jdbc.jar
backport-util-concurrent.jar    junit.jar           maven-repository-metadata.jar   support-v4.jar
classworlds.jar         maven-ant-tasks.jar     maven-settings.jar      vtd-xml.jar
```

I'm using Robolectric 2.2 with the latest EAP IntelliJ. I noted that IntelliJ EAP was using the project root as a default for the working dir and have fixed this to use the module dir. Prior to that I could run my test without getting this error but it was having trouble finding resources. Please help!

**Comment by sweetleon** [comment]
@erd While using `RobolectricTestRunner` and having Robolectric ahead of Android in the `classpath` are necessary, this problem (`RuntimeException: Stub!` in `com.amazon.device.messaging.ADMMessageReceiver`) still occurs when those conditions are satisfied. @sneuberger-amazon has a working solution.

I can show this to you in person if you'd like to see it.

**Comment by erd** [comment]
@sweetleon Oh, I see. That makes sense now.

**Comment by banie** [comment]
Could you share what is the solution? I am getting the same problem too with "java.lang.Exception: No runnable method at org.robolectric.RobolectricTestRunner" even though I've already put the robolectric ahead of the android

**Comment by sweetleon** [comment]
@banie It depends in the exact situation you're in. If it's related to ADM like the post at the top of this thread then the solution @sneuberger-amazon offered will fix it. But if your stack trace is different you'll need to post that before anyone can help.

**Comment by banie** [comment]
@sweetleon thanks for the reply, I actually managed to figure it out yesterday but lost the link to this site so I couldn't post an update. My mistake on that no runnable methods was simply not putting @Test annotation before my test method and have either @Before or @Ignore on the rest of the other methods. 

FYI I'm using Android Studio 1.1.0 and robolectric 1.0.0, and I found that there's no need to have the robolectric jar before android on the app.iml. The other key solution to run robolectric tests was to have the test folder side by side the main folder. I found that to be necessary even though technically we could do setRoot on the sourceSets of build.gradle

In case it could anyone, having the project structure like this will make it work
https://github.com/robolectric/deckard-gradle

**Comment by sweetleon** [comment]
Robolectric 1.0.0? Really? 3.0 is in release candidates and 2.4 is stable.
Upgrade!

On Wednesday, April 1, 2015, banie <notifications@github.com> wrote:

> @sweetleon <https://github.com/sweetleon> thanks for the reply, I
> actually managed to figure it out yesterday but lost the link to this site
> so I couldn't post an update. My mistake on that no runnable methods was
> simply not putting @Test <https://github.com/Test> annotation before my
> test method and have either @Before <https://github.com/Before> or @Ignore
> <https://github.com/Ignore> on the rest of the other methods.
>
> FYI I'm using Android Studio 1.1.0 and robolectric 1.0.0, and I found that
> there's no need to have the robolectric jar before android on the app.iml.
> The other key solution to run robolectric tests was to have the test folder
> side by side the main folder. I found that to be necessary even though
> technically we could do setRoot on the sourceSets of build.gradle
>
> In case it could anyone, having the project structure like this will make
> it work
> https://github.com/robolectric/deckard-gradle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robolectric/robolectric/issues/781#issuecomment-88506724>
> .
>


-- 
--
Snet form a tiny keybord

**Comment by banie** [comment]
Oops my bad, I meant 2.4. Thanks for that. I will correct my reply too

**Comment by Yadunath** [comment]
@sneuberger-amazon 
I am facing same issue in robolectric:4.3 .And Setup createSetup overridden method is not available in latest roboelectric version.Is there any other solution for this issue.
@sweetleon

**Comment by sweetleon** [comment]
@Yadunath Have a look at Issue #1832 & PR https://github.com/robolectric/robolectric/pull/1836
