### ISSUE TITLE
unknown error (code 14 SQLITE_CANTOPEN): Could not open database

### ISSUE THREAD

**Issue by dengshiwei** [robolectric/robolectric#7812]
### Description
unknown error (code 14 SQLITE_CANTOPEN): Could not open database
### Steps to Reproduce
mDB = SQLiteDatabase.openDatabase(dbPath, null, SQLiteDatabase.OPEN_READONLY);
### Robolectric & Android Version
Robolectric version is v4.9, Android Version is 31

**Comment by dengshiwei** [comment]
example：
```java
public class DatabaseUtilsTest {
    private static SQLiteDatabase mDB;

    public static String loadEventFromDb(Application application) {
        try {
            String dbPath = application.getDatabasePath(DbParams.DATABASE_NAME).getAbsolutePath();
            openDB(dbPath);
            if (mDB != null) {
                Cursor cursor = mDB.rawQuery("select * from events", null);
                assertNotNull(cursor);
                assertEquals(1, cursor.getCount());
                cursor.moveToFirst();
                String data = parseData(cursor.getString(cursor.getColumnIndexOrThrow(DbParams.KEY_DATA)));
                cursor.close();
                return data;
            }
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
        return "";
    }

    private static void openDB(String dbPath) {
        if (mDB == null || !mDB.isOpen()) {
            mDB = SQLiteDatabase.openDatabase(dbPath, null, SQLiteDatabase.OPEN_READONLY);
        }
    }
}
```

**Comment by utzcoz** [comment]
@dengshiwei Thanks for reporting this issue. Which OS do you use? And which mode of SQLite do you use? If you use macOS(including M1/M2) and Linux, you can try to use `NATIVE` SQLiteMode such as https://github.com/robolectric/robolectric/blob/c385f9c05de728f3c8424fa0f33247ccc3a51c1a/robolectric/src/test/java/org/robolectric/plugins/SQLiteModeConfigurerClassTest.java#L30-L33.

**Comment by utzcoz** [comment]
@dengshiwei Please try the `NATIVE` SQLiteMode, and feel free to reopen this issue this it still exists with `NATIVE` SQLiteMode.
