### ISSUE TITLE
Robolectric problem with includeAndroidResources = true

### ISSUE THREAD

**Issue by mharam** [robolectric/robolectric#7813]
### Description

In a Windows 10 PC with Android Studio Chipmunk | 2021.2.1, whenever I set `includeAndroidResources = true` in build.gradle file the test with `@RunWith(AndroidJUnit4::class)` produces the following error:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> No tests found for given includes: [com.takaapoo.myapplication.ExampleUnitTest.addition_isCorrect](filter.includeTestsMatching)
```

### Steps to Reproduce

I pushed a simple project in my github with following address:  https://github.com/mharam/Robolectric-Problem
You can produce it yourself by creating a project in Android Studio Chipmunk | 2021.2.1 and adding `@RunWith(AndroidJUnit4::class)` to `ExampleUnitTest` class. Of course you have to add necessary dependencies.

`.\gradlew -version` output:
Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.2 (Oracle Corporation 11.0.2+7-LTS)
OS:           Windows 10 10.0 amd64
  
### Robolectric & Android Version

Robolectric version: 4.6.1
Android version: API 33

### Link to a public git repo demonstrating the problem:

https://github.com/mharam/Robolectric-Problem

**Comment by mharam** [comment]
As I updated Robolectric version to 4.8 the problem resolved.

**Comment by utzcoz** [comment]
@mharam Thanks for your confirmation. It's recommended to use latest Robolectric for your app/library, becuase latest Robolectric often brings many great improvments.
