### ISSUE TITLE
Espresso click() fails if view has also a long click listener set

### ISSUE THREAD

**Issue by filipebatista** [robolectric/robolectric#7816]
### Description
When performing the espresso action, click on a view that has `onClick` and `onLongClick`, the `onLongClick` is triggered instead of the `onClick`

Example:
```
myView.setOnLongClickListener(dialPadLongPressListener)
myView.setOnClickListener(dialPadButtonListener)
```

`onView(withText(R.id.myView)).perform(click())`

Until version 4.3 seems to be working fine. From 4.4 I've started to see this behavior.

### Robolectric & Android Version
Robolectric Version >= 4.4

**Comment by utzcoz** [comment]
@filipebatista Have you tried latest Robolectric 4.9? I add a test at https://github.com/robolectric/robolectric/pull/7857, and the scenario that you reported can work without error. You can attach a reprodcuable sample if you still have this problem when using Robolectric 4.9.
