### ISSUE TITLE
Not all values in `android.system.OsConstants` are shadowed

### ISSUE THREAD

**Issue by MuntashirAkon** [robolectric/robolectric#7829]
### Description
`OsConstants` have a lot of values, but not all of them seem to have shadowed. Examples of such constants are `F_OK`, `R_OK` and `W_OK`. These values are located in `unistd.h` header file.

### Robolectric Version
4.9

### Useful links
1. https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/shadows/framework/src/main/java/org/robolectric/shadows/ShadowOsConstants.java
2. https://cs.android.com/android/platform/superproject/+/master:libcore/luni/src/main/java/android/system/OsConstants.java

**Comment by utzcoz** [comment]
@MuntashirAkon Thanks for reporting this issue. If you need other constants to be shadowed, would you like to send a PR to support it?

**Comment by MuntashirAkon** [comment]
> If you need other constants to be shadowed, would you like to send a PR to support it?

May be shadowing **all** the values in `OsConstants` would be a better choice because all those unshadowed values have the value `0` and the flag checks using bitwise AND operation always return `0` meaning that unless you're careful, you will have headache debugging your code only to find that the problem was with Robolectric's default shadow implementation.

If you agree with me, you can assign this issue to me.

**Comment by utzcoz** [comment]
@MuntashirAkon Thanks. I assigned this issue to you. Looking forward to your PR for this issue.

**Comment by utzcoz** [comment]
@MuntashirAkon Sorry, I didn't receive any updates for this issue. So I decide to close this issue as no other people show the need for these constants shadowed. If you still need more constants to be shadowed, feel free to reopen this issue and send a PR for it.
