### ISSUE TITLE
Make a realease 4.9.1 with Espresso 3.5.0 (stable)?

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#7831]
### Description
Release 4.9 includes an alpha dependency to Espresso:

> Bump Espresso to 3.5.0-alpha07 by @utzcoz in https://github.com/robolectric/robolectric/pull/7429

3.5.0 has been released: https://developer.android.com/jetpack/androidx/releases/test#espresso-3.5.0

**Comment by utzcoz** [comment]
@alixwar You can add your needed PRs/fixes to https://github.com/robolectric/robolectric/discussions/7864. I will ping @hoisie to help release a 4.9.1 release if possible.

**Comment by alwa** [comment]
> @alixwar You can add your needed PRs/fixes to #7864. I will ping @hoisie to help release a 4.9.1 release if possible.

Seems to have been fixed already in https://github.com/robolectric/robolectric/pull/7785/files
