### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7869]
Current `CONTRIBUTING.md` looks like out-dated, and latest contributing building guide in https://robolectric.org/building-robolectric/ is better. We need to discuss whether we need to update `CONTRIBUTING.md` directly, or combine multi-places resource to one place, and other places use the link.

**Comment by tajbaba999** [comment]
Hey @utzcoz, Can I Work on this issue of continuing the readme file?

**Comment by utzcoz** [comment]
@tajbaba999 Sorry, I think this issue is not for first-time contributor. You can find other issues that need help by https://github.com/robolectric/robolectric/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22.

**Comment by satvik2131** [comment]
I guess we update the CONTRIBUTING.md because it is easy for first time users to understand and also can pass the link of the website

**Comment by MGaetan89** [comment]
I guess we can clone this issue now: the contributor guide has been updated, and the same version is used on this repo and on https://robolectric.org.

@utzcoz feel free to reopen if you think there are still improvements to be done.
