### ISSUE TITLE
android-all not downloaded as part of robolectric, or is it a separate dependency? 

### ISSUE THREAD

**Issue by cooperkong** [robolectric/robolectric#7886]
### Description
as per title says, it seems `android-all` is not downloaded as part of robolectric, or do I need to declare it separately?
### Steps to Reproduce
N/A
### Robolectric & Android Version
4.9, android version is not related in thie issue
### Link to a public git repo demonstrating the problem:
N/A

**Comment by hoisie** [comment]
android-all jars are downloaded during runtime, lazily (when they are needed), using https://github.com/robolectric/robolectric/blob/master/plugins/maven-dependency-resolver/src/main/java/org/robolectric/internal/dependency/MavenDependencyResolver.java. They are downloaded from MavenCentral to your  `$HOME/.m2` directory

**Comment by cooperkong** [comment]
yeah, that's what I thought too. We recently upgraded our `wearable` dependency and somehow wear unit tests start to fail due to missing `libcore` unless we add `android-all` manually, very strange.

**Comment by hoisie** [comment]
Yeah it is not recommended to depend on the android-all jars. They are only designed for robolectrics use. Those jars contain the framework implementation code, which includes hidden classes and methods. If you depend on it you will likely get broken across Sdk levels.
