### ISSUE TITLE
OutOfMemoryError when too many test sdks [ with Reproduce Step codes ]

### ISSUE THREAD

**Issue by DonaldDu** [robolectric/robolectric#7909]
### Steps to Reproduce

//sdk in [21, 33], OutOfMemoryError
@Config(minSdk = 21, manifest = Config.NONE, application = Application::class)
@RunWith(RobolectricTestRunner::class)
open class SplitInstallerTest {}

//sdk in [29, 33], no error when less test sdks
@Config(minSdk = 29, manifest = Config.NONE, application = Application::class)
@RunWith(RobolectricTestRunner::class)
class SplitInstallerTest2 : SplitInstallerTest()

### Robolectric & Android Version
'org.robolectric:robolectric:4.9'
### Link to a public git repo demonstrating the problem:
https://github.com/DonaldDu/SplitInstaller/blob/test/SplitInstaller/src/test/java/com/donalddu/splitinstaller/SplitInstallerTest.kt

**Comment by utzcoz** [comment]
@DonaldDu It's recommended to give larger size of memory that Gradle uses.

**Comment by utzcoz** [comment]
Duplicated to https://github.com/robolectric/robolectric/issues/7702.
