### ISSUE TITLE
[OffsetDateTime.format]  Different result between robolectric and emulator

### ISSUE THREAD

**Issue by likai79511** [robolectric/robolectric#7910]
### Description
When i execute `OffsetDateTime.format`, different results will occur between Robolectric and Device/Emulator. 

### Steps to Reproduce
    @Test
    fun test() {
        Locale.setDefault(Locale("en", "AU"))

        val time = OffsetDateTime.parse("2023-01-01T10:00:00Z")
        val formatter = DateTimeFormatter.ofPattern("d MMM yyyy")

        println("FINGERPRINT: ${Build.FINGERPRINT}\nresult:${time.format(formatter)}")
    }

| Robolectric | device/emulator |
|  ----  | ----  |
<img width="374" alt="image" src="https://user-images.githubusercontent.com/16486494/210735677-b9f89b2e-1f3e-47f7-82d6-235123d87637.png"> | <img width="1351" alt="image" src="https://user-images.githubusercontent.com/16486494/210736794-26c4a18c-0a86-42f0-ab68-5020389ebcc4.png">

Robolectric : 1 Jan. 2023 (with a ".")
Device/Emulator: 1 Jan 2023

### Robolectric & Android Version
org.robolectric:robolectric:4.9.2
junit:junit:4.13.2

### Link to a public git repo demonstrating the problem:

**Comment by hoisie** [comment]
Unfortunately OffsetDateTime is a Java core class, so any differences are due to the implementation differences between the JDK and Libcore (Android's implementation of the Java core classes).

This is the Android version:
https://cs.android.com/android/platform/superproject/+/master:libcore/ojluni/src/main/java/java/time/OffsetDateTime.java;l=122?q=OffsetDateTime&sq=

**Comment by okamayana-tinyspeck** [comment]
> Unfortunately OffsetDateTime is a Java core class, so any differences are due to the implementation differences between the JDK and Libcore (Android's implementation of the Java core classes).
> 
> This is the Android version: https://cs.android.com/android/platform/superproject/+/master:libcore/ojluni/src/main/java/java/time/OffsetDateTime.java;l=122?q=OffsetDateTime&sq=

Is this also the case for `DateTimeFormatter`? Also, are there any workarounds?

**Comment by MGaetan89** [comment]
We've added a section on Robolectric's website for this case: https://robolectric.org/best-practices/#month-names
As @hoisie pointed out, these classes are part of the Java API, and Robolectric cannot alter their behavior.
You can run your tests on an Android device to get the correct result.
