### ISSUE TITLE
Using roboelectric for commonTests in kotlin multiplatform modules

### ISSUE THREAD

**Issue by Burtan** [robolectric/robolectric#7942]
Hi,
is there any way to use roboelectric for the android part of commonTests in a kotlin multiplatform module? For instance when using kotlin-test as the testing environment. Alternatively kotest could be used?
Thanks!

**Comment by Aadijindal07** [comment]
Yes, you can use RoboElectric for the Android part of common tests in a Kotlin multiplatform module. To do this, you will need to write tests in RoboElectric and use a test runner that supports RoboElectric, such as the Android JUnit Runner.

For example, you can write the tests in Kotlin, use the KotlinTest library, and run the tests using the Android JUnit Runner. To use RoboElectric, you will need to annotate your tests with the @RunWith(RobolectricTestRunner::class) annotation and configure RoboElectric in your build.gradle file.

Alternatively, you can use kotest, a comprehensive testing library for Kotlin, and run your tests using RoboElectric. To do this, you will need to configure kotest to use RoboElectric as the test runner.

In either case, it's important to keep in mind that RoboElectric does have some limitations and may not be able to fully emulate the Android environment, so it's a good idea to also test on actual devices.

by the way see i want to be very from i have very less contribution and gsoc is coming any work you want to assign me pleasee
i have experience in web,add dev, python, js,java etc

**Comment by Burtan** [comment]
Can you give an example? I think you misunderstood my question. I do not mean the android tests for the android code in kotlin multiplatform modules. I mean the commonTest part, which can run on all platforms but should be run with roboelectric only in the android part.

**Comment by utzcoz** [comment]
@Burtan You can check the example app of https://github.com/robolectric/robolectric/issues/7306 for Robolectric with Kotlin commonTest.

**Comment by Burtan** [comment]
Oh, cool. That's clever to extend an expected class. Thanks!
