### ISSUE TITLE
Unable to build external native lib ICU on Windows 

### ISSUE THREAD

**Issue by jsoberg** [robolectric/robolectric#7963]
### Description
Hey all! After following the available documentation on building on Windows and trying various combinations, I'm still unable to build the project. For reference, I've been looking at:
- [The main building page](https://robolectric.org/building-robolectric/)
- [The initial issue getting Windows builds working](https://github.com/robolectric/robolectric/issues/6791)

#### Steps I've taken thus far
- Installed required Android SDK tools and Java 11 described [here](https://robolectric.org/building-robolectric/)
    - Added the JDK install directory and base Android sdk dir (as well as `tools`/`platform-tools`) to my Windows PATH
- Installed MSYS2 MINGW64 and packages as described [here](https://robolectric.org/building-robolectric/), and also installed [this libicu package](https://packages.msys2.org/package/mingw-w64-x86_64-icu) after looking into the build failure initially.
    - Added `mingw64\bin` to my Windows PATH
    - Exported `ANDROID_SDK_ROOT` and `JAVA_HOME` in the expected `/c/...` format in MING64
    
#### Build issues
My build always fails while running the `:nativeruntime:buildICU` (`:nativeruntime:configureICU` seems to run alright and create the expected `Makefile` as far as I can tell). The issue appears to be from the `dl` step:
```
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:81: ../../bin/makeconv.exe] Error 1
make[2]: Leaving directory '/c/GIT/robolectric/nativeruntime/external/icu/icu4c/source/tools/makeconv'
make[1]: *** [Makefile:47: all-recursive] Error 2
make[1]: Leaving directory '/c/GIT/robolectric/nativeruntime/external/icu/icu4c/source/tools'
make: *** [Makefile:153: all-recursive] Error 2
```
Where there seems to be quite a few undefined references:
```
...
undefined reference to `icu_69::StringPiece::StringPiece(char const*)'
undefined reference to `icu_69::CharString::append(char const*, int, UErrorCode&)'
undefined reference to `icu_69::CharString::ensureEndsWithFileSeparator(UErrorCode&)'
undefined reference to `uprv_free_69'
undefined reference to `uprv_free_69'
```

[This](https://github.com/robolectric/robolectric/files/10716589/windows_buildICUFailure-02-12-2023.txt) is the `--stacktrace` output from running `:nativeruntime:buildICU`, and [this](https://scans.gradle.com/s/dtw7pwjomkyu6) is an example buildscan. Note that I'm building from my forked repository here, but it's matching the current `master` as I just forked it yesterday.

I'll keep investigating, but if anyone sees something simple that I might be missing here please let me know; any help would be appreciated. Thanks!

### Robolectric Version
master, f2e3204225d

**Comment by utzcoz** [comment]
@jsoberg Thanks for reporting this issue. I can reproduce this problem with a re-cloning and building. I will investigate it.

**Comment by utzcoz** [comment]
In Linux environment, there are some files generated at `robolectric/nativeruntime/external/icu/icu4c/source/lib`:

```
libicudata.a  libicui18n.a  libicuio.a  libicutu.a  libicuuc.a
```

And these files will be used by `makeconv` building with parameters like `-licutu`. From https://man7.org/linux/man-pages/man1/g++.1.html we know that:

```
           Static libraries are archives of object files, and have file
           names like liblibrary.a.  Some targets also support shared
           libraries, which typically have names like liblibrary.so.  If
           both static and shared libraries are found, the linker gives
           preference to linking with the shared library unless the
           -static option is used.
```

In another world, `g++` will try to find files called `libicutu.a` or other similar names in `icu4c/source/lib`. But in Windows' msys2 MingW64 environment, these files are:

```
MINGW64 ~/robolectric/nativeruntime/external/icu/icu4c/source/lib
$ ls
libsicuin.a  libsicuio.a  libsicutu.a  libsicuuc.a
``` 

Looks like previous building progress added an extra `s` to file name, and `g++` can't find these files in `source/lib` directory. We can grep these undefined functions from these .a files.

**Comment by utzcoz** [comment]
Okay, after some investigation with online successful Windows CI building, the library name likes `libsicuin.a` are correct because icu project uses this name type for MinGW64 environment. After multiple attempts, the root cause of building failure in Windows' MinGW64 environment is `--disable-shared` building parameter in MinGW64 environment. We can remove it from `nativeruntime/build.gradle` for Windows building, remove `nativeruntime/external/icu/icu4c/source/Makefile` locally, and re-run `./gradle assemble` to build the project in Windows' MinGW64 environment. The CI only uses `--enable-static` without `disable-shared` to build nativeruntime and ICU libraries, so it can still pass the building in MinGW64 environment. I think it might be ICU's problem because I saw some MinGW compatibility problems at ICU's issue lists. Before I can find a perfect solution for it, I will send a PR to remove `--disable-shared` for nativeruntime's Gradle building config for Windows. cc @hoisie .

**Comment by utzcoz** [comment]
I also tried building latest `https://github.com/unicode-org/icu` with following command in Windows' MinGW environment:

```
cd icu/icu4c/source
./runConfigureICU --enable-static --disable-shared
make -j4
```

And I also got the above building failures. So it might be ICU's compatibility problem with latest MinGW GCC.

**Comment by utzcoz** [comment]
@jsoberg Please sync your Robolectric source code to the latest, remove `nativeruntime/external/icu/icu4c/source/Makefile` and run `./gradlew assemble` again to check whether you can build Robolectric in Windows' MinGW environment now.
