### ISSUE TITLE
getAttributeName returns NodeName instead of LocalName

### ISSUE THREAD

**Issue by aax** [robolectric/robolectric#806]
Method getAttributeName(int index) in class XmlResourceParserImpl should only return the "local name" of the attribute (without namespace), not the full name.

E.g., currently it returns "android:id" for an attribute android:id="..." in the XML being parsed. I think, it should only return "id" instead.

My claim is backed by the fact, that the real Android (at least 4.1.2) seems to have this behaviour. And also, the API documentation of the interface XmlPullParser [1] states that the local name is returned. The documentation of the interface AttributeSet [2] does not specify this. Both interfaces are implemented by class XmlResourceParserImpl.

The fix is easy, just return attr.getLocalName() instead of attr.getNodeName(). But if I change this, a test fails (ResoucesTest.testGetColorStateList), and I am unable to find the reason for this.

So it would be nice, if someone could have a look at this!

[1] http://developer.android.com/reference/org/xmlpull/v1/XmlPullParser.html#getAttributeName(int)
[2] http://developer.android.com/reference/android/util/AttributeSet.html#getAttributeName(int)

**Comment by jongerrish** [comment]
We've overhauled resources in Robolectric 4.0, in binary resource mode behavior should be very close to the framework behavior.

Please give this a try and if its still an issue feel free to reopen
