### ISSUE TITLE
API for configure a Wear OS round display

### ISSUE THREAD

**Issue by yschimke** [robolectric/robolectric#8072]
Not a blocking issue, but there doesn't seem to be a simple API for configuring a display to match Wear OS.

Should the following work?

```
    @Before
    fun setUp() {
        val display = ShadowDisplay.getDefaultDisplay()
        ShadowDisplayManager.changeDisplay(display.displayId, "+round")
        shadowOf(display).apply {
            setXdpi(320f)
            setYdpi(320f)
            setHeight(454)
            setWidth(454)
        }
    }
```

**Comment by utzcoz** [comment]
@yschimke Could you try `@Config` with `round` + size qualifier to your test file or test method?

**Comment by yschimke** [comment]
I'll try tonight, thanks.

**Comment by yschimke** [comment]
Should I close this?

**Comment by utzcoz** [comment]
@yschimke You can try it first. If it can resolve this issue, you can close it. If not, we can investigate it.

**Comment by yschimke** [comment]
I tried with this and it changed the resolution, but still not round.

With this config

```
@RunWith(RobolectricTestRunner::class)
@Config(application = KoinTestApp::class, sdk = [30], qualifiers = "w454dp-h454dp-round-xhdpi-nokeys")
@GraphicsMode(NATIVE)
class ConferenceScreenTest : KoinTest {
```

I get

![image](https://user-images.githubusercontent.com/231923/226200745-7253438e-acd0-4497-9968-a0ed4d455165.png)

**Comment by hoisie** [comment]
cc @JuliaSullivanGoogle 

@yschimke you are are veering into somewhat uncharted territory, we really haven't looked into how RNG behaves when using the round qualifier. I do not have a high level grasp of everything that goes into rendering a watch/round screen. There may be a lot of moving parts involved, some of which may not be simulated yet in Robolectric.

**Comment by yschimke** [comment]
@hoisie Yep - no problem.

I can simulate this easily with Accompanist TestHarness, so not blocked.  I just want Configuration.isScreenRound to be true, which causes Wear Compose to draw for a round screen

**Comment by hoisie** [comment]
It's definitely something we would be interested in supporting, maybe the first step would to set up side by side screenshot test with an emulator.

**Comment by yschimke** [comment]
Yep, I've got it working with instrumentation tests, then sped things up with paparazzi.

Now trying it with robolectric.  So far working well.  https://github.com/joreilly/Confetti/pull/361/files#diff-4b1fad37b744d46f614c709c8b2f0b9637e4f3ab550c0f2572095f80f049f2e2

**Comment by yschimke** [comment]
Working now with 

qualifiers = "w221dp-h221dp-small-notlong-round-watch-xhdpi-keyshidden-nonav"

So closing.
