### ISSUE TITLE
Robolectric NATIVE GraphicsMode fails on mixing with LEGACY

### ISSUE THREAD

**Issue by yschimke** [robolectric/robolectric#8073]
### Description

Running a single test passes, but running a test suite with multiple has failures.
I'm possibly missing some cleanup, but not sure what.

```
> Task :wearApp:testDebugUnitTest
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f11d37695a0, pid=2450, tid=2486
#
# JRE version: OpenJDK Runtime Environment Zulu17.40+19-CA (17.0.6+10) (build 17.0.6+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu17.40+19-CA (17.0.6+10-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [librobolectric-nativeruntime.so+0x8325a0]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/runner/work/Confetti/Confetti/wearApp/core.2450)
#
# An error report file with more information is saved as:
# /home/runner/work/Confetti/Confetti/wearApp/hs_err_pid2450.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

### Steps to Reproduce

Test on https://github.com/joreilly/Confetti/pull/361 including CI

`./gradlew wearApp:test`

### Robolectric & Android Version

4.10-alpha-1
API 30

### Link to a public git repo demonstrating the problem:

https://github.com/joreilly/Confetti/pull/361

**Comment by hoisie** [comment]
Do all tests in this project run with native graphics or just some of them?

If tests go from non-native graphics to native graphics within the same test process, I can see this happening when graphics objects are garbage collected.

**Comment by yschimke** [comment]
All run with native graphics. Is there some extra cleanup I need to do?

**Comment by hoisie** [comment]
Was an `hs_err_pid. log` file generated? That contains more details related to the native crash. How do you repro this crash?

The most common type of native crashes are things like BitmapFactory APIs that generate invalid bitmaps, or custom graphics shadows that skip native initialization.

**Comment by yschimke** [comment]
If you check out that project, and edit wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/AppTest.kt to use Legacy

Then `./gradlew wearApp:testDebugUnitTest`

**Comment by yschimke** [comment]
Sent hs_err_pid via google chat

**Comment by ZacSweers** [comment]
@hoisie I've sent you another log via slack

**Comment by utzcoz** [comment]
@ZacSweers @yschimke The 4.10 stable release contains the commit https://github.com/robolectric/robolectric/commit/2ca4753490663454a0694a5819531241316e9319 (created by @hoisie) to try to fix this issue, could you try it and give the feedback? Thanks.
