### ISSUE TITLE
Different behavior in ReflectionHelpers.setStaticField() in Robolectric 4.10-alpha1 vs. 4.8

### ISSUE THREAD

**Issue by kenyee** [robolectric/robolectric#8085]
### Description
I tried to upgrade to 4.10-alpha1 to test out the new RNG support and using the ReflectionsHelpers.setStaticField() method on BuildConfig.DEBUG now throws this exception:
"java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot set the value of final field public static"

This was used in our tests to test release build behavior in some of the code.
If this is intended behavior, it should be documented.

### Steps to Reproduce
Create any Robolectric test and put this in the code to see the exception:
```
        ReflectionHelpers.setStaticField(
            BuildConfig::class.java,
            "DEBUG",
            false
        )
```

### Robolectric & Android Version
Robolectric 4.10-alpha1

**Comment by hoisie** [comment]
You can see the reasoning in this commit:

https://github.com/robolectric/robolectric/commit/139bc9735ede7577badd5b28289e4c96ddd862f0

Starting in Java 17, it is not possible to set final static fields using reflection. Maybe we could have perpetuated the existing code for Java < 17, but we did not want to be the library people used to remove final from fields.

Note it is still possible to change the value of final fields using an instrumentation-based approach. I would look into mockito-inline.

**Comment by kenyee** [comment]
Thanks for the explanation on why (and definitely fair to do given it'll be disabled in Java18 given the comments in that commit)...I thought it was a bit of an odd thing for this old legacy testing code to do as well (didn't know you could even change a static final via reflection).

Probably still a good thing to mention in the release notes for 4.10?  If no, we can close this issue and folks can find this if they hit it :-)

**Comment by hoisie** [comment]
Updated https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10-alpha-1
