### ISSUE TITLE
Unable to test functions that access Parcelable in API 33 (with mockk)

### ISSUE THREAD

**Issue by dazza5000** [robolectric/robolectric#8136]
### Description

Unable to test functions that access Parcelable in API 33 (with mockk). API 32 works just fine.

Get the following exception:

```
class java.lang.Object cannot be cast to class android.os.Parcelable (java.lang.Object is in module java.base of loader 'bootstrap'; android.os.Parcelable is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @63798ca7)
java.lang.ClassCastException: class java.lang.Object cannot be cast to class android.os.Parcelable (java.lang.Object is in module java.base of loader 'bootstrap'; android.os.Parcelable is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @63798ca7)
```

Here is the code that is being accessed:

```
inline fun <reified T : Parcelable> Bundle.parcelable(key: String): T? = when {
    SDK_INT >= Build.VERSION_CODES.TIRAMISU -> getParcelable(key, T::class.java)
    else -> {
        // https://issuetracker.google.com/issues/242048899
        @Suppress("DEPRECATION")
        getParcelable(key) as? T
    }
}
```
	

### Steps to Reproduce

Run the following test in the attached project `greeting_with_mock_bundle`

https://github.com/dazza5000/robolectric_parcelable_api_33/blob/d526e8dcf8a655674d3d247678c52bbb9004160e/app/src/test/java/com/example/myapplication/ExampleUnitTest.kt#L23

### Robolectric & Android Version

Robolectric 4.10 / Android API 33

### Link to a public git repo demonstrating the problem:

https://github.com/dazza5000/robolectric_parcelable_api_33

**Comment by hoisie** [comment]
Why are you mocking a Bundle? Why not use a real Bundle? The real Bundle is more or less supported pretty well in a Robolectric environment. You can use the real Android methods to define a bundle and then pass it into your Compose widget.

When you mock Android objects with MockK (or any other mocking framework), you are essentially combining the bytecode instrumentation of both Robolectric and MockK. None of the Robolectric maintainers know MockK instrumentation works, and debugging these type of issues are incredibly complicated. This is why you should avoid mocking Android objects and just use Robolectric to modify the behavior of your Android objects if you need.

**Comment by dazza5000** [comment]
That worked - using Bundle.Empty fixed the issue
