### ISSUE TITLE
regex is not available on sqlite since robolectric 4.10

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#8163]
### Description
* Since robolectric 4.10, some SQL statement got error like this
```
android.database.sqlite.SQLiteException: no such function: regexp (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM contacts WHERE name regexp ? ORDER BY name COLLATE NOCASE ASC	
	at org.robolectric.nativeruntime.SQLiteConnectionNatives.nativePrepareStatement(Native Method)	
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.lambda$nativePrepareStatement$2(ShadowNativeSQLiteConnection.java:75)	
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)	
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativePrepareStatement(ShadowNativeSQLiteConnection.java:73)	
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
```
### Steps to Reproduce
```
$ git clone https://github.com/ganadist/VersionCodeDemo -b robolectric_410_sqlite
$ cd VersionCodeDemo
$ ./gradlew :app:testDevelopDebugUnitTest  # run with robolectric 4.10
> Task :app:testDevelopDebugUnitTest
com.example.myapplication.SqliteTest > testSqliteRegex FAILED
    android.database.sqlite.SQLiteException at SqliteTest.kt:70

$ git checkout HEAD~1 
$ ./gradlew :app:testDevelopDebugUnitTest  # run with robolectric 4.9.2
> Task :app:testDevelopDebugUnitTest
com.example.myapplication.SqliteTest > testSqliteRegex PASSED
```

### Robolectric & Android Version
* Robolectric 4.10
* Android 13 (API Level 33)

### Link to a public git repo demonstrating the problem:
* https://github.com/ganadist/VersionCodeDemo/blob/robolectric_410_sqlite/app/src/test/java/com/example/myapplication/SqliteTest.kt#L64

### Context

* I'm guessing this error was occured by 216f65061d
* On robolectric 4.9, sqlite was compiled with ICU (with `-DSQLITE_ENABLE_ICU=1` option) : https://github.com/robolectric/robolectric/blob/robolectric-4.9.x/nativeruntime/cpp/CMakeLists.txt#L99
* On robolectric 4.10, sqlite was compiled [from android12-hostruntime-dev branch with host configuration](https://android.googlesource.com/platform/external/sqlite/+/refs/heads/android12-hostruntime-dev/dist/Android.bp#120)
  * On `sqlite.c`
    ```
     * An implementation of the SQL regexp() function (and hence REGEXP
      operator) using the ICU uregex_XX() APIs.
    ```
  * On build script, `-DSQLITE_ENABLE_ICU=1` was [enabled for target devices only](https://github.com/aosp-mirror/platform_external_sqlite/blob/android12-hostruntime-dev/dist/Android.bp#L113-L124), but [not enabled for host configuration](https://github.com/aosp-mirror/platform_external_sqlite/blob/android12-hostruntime-dev/dist/Android.bp#L125-L129)
  * Also, I'm guessing other unicode related functions should not be working.

**Comment by hoisie** [comment]
Thank you for the detailed report 🙏 . It's odd that some unicode functions work (e.g. collate UNICODE and collate LOCALIZED) but not regexp.

**Comment by ganadist** [comment]
I found icu extensions on sqlite3.c L194186

```
  /*
  ** Register the ICU extension functions with database db.
  */
  SQLITE_PRIVATE int sqlite3IcuInit(sqlite3 *db){
  # define SQLITEICU_EXTRAFLAGS (SQLITE_DETERMINISTIC|SQLITE_INNOCUOUS)
    static const struct IcuScalar {
      const char *zName;                        /* Function name */
      unsigned char nArg;                       /* Number of arguments */
      unsigned int enc;                         /* Optimal text encoding */
      unsigned char iContext;                   /* sqlite3_user_data() context */
      void (*xFunc)(sqlite3_context*,int,sqlite3_value**);
    } scalars[] = {
      {"icu_load_collation",2,SQLITE_UTF8|SQLITE_DIRECTONLY,1, icuLoadCollation},
  #if !defined(SQLITE_CORE) || defined(SQLITE_ENABLE_ICU)
      {"regexp", 2, SQLITE_ANY|SQLITEICU_EXTRAFLAGS,         0, icuRegexpFunc},
      {"lower",  1, SQLITE_UTF16|SQLITEICU_EXTRAFLAGS,       0, icuCaseFunc16},
      {"lower",  2, SQLITE_UTF16|SQLITEICU_EXTRAFLAGS,       0, icuCaseFunc16},
      {"upper",  1, SQLITE_UTF16|SQLITEICU_EXTRAFLAGS,       1, icuCaseFunc16},
      {"upper",  2, SQLITE_UTF16|SQLITEICU_EXTRAFLAGS,       1, icuCaseFunc16},
      {"lower",  1, SQLITE_UTF8|SQLITEICU_EXTRAFLAGS,        0, icuCaseFunc16},
      {"lower",  2, SQLITE_UTF8|SQLITEICU_EXTRAFLAGS,        0, icuCaseFunc16},
      {"upper",  1, SQLITE_UTF8|SQLITEICU_EXTRAFLAGS,        1, icuCaseFunc16},
      {"upper",  2, SQLITE_UTF8|SQLITEICU_EXTRAFLAGS,        1, icuCaseFunc16},
      {"like",   2, SQLITE_UTF8|SQLITEICU_EXTRAFLAGS,        0, icuLikeFunc},
      {"like",   3, SQLITE_UTF8|SQLITEICU_EXTRAFLAGS,        0, icuLikeFunc},
  #endif
```

And I'm guession these functions are not available at robolectric 4.10

**Comment by hoisie** [comment]
Sent out https://android-review.git.corp.google.com/c/platform/external/sqlite/+/2572310 to fix this issue. When that gets merged we can do a 4.10.1 release.

**Comment by utzcoz** [comment]
@ganadist Before @hoisie releases 4.10.1, you can use `org.robolectric:nativeruntime-dist-compat` 1.0.1 as your dependency to fix this issue as a workaround.

**Comment by ganadist** [comment]
@utzcoz 
Thanks for sharing.
I can confirm that my unittests are passed which are using `regex` statement with `org.robolectric:nativeruntime-dist-compat` 1.0.1

**Comment by utzcoz** [comment]
@ganadist Thanks for your confirmation. I will close this issue, and you can use this workaround until 4.10.1 released.
