### ISSUE TITLE
All my tests fails on java.lang.NoClassDefFoundError: org/conscrypt/OpenSSLProvider

### ISSUE THREAD

**Issue by renetik** [robolectric/robolectric#8165]
### Description
All my tests fails on` java.lang.NoClassDefFoundError: org/conscrypt/OpenSSLProvider`
```
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.base/java.lang.Class.getConstructors(Unknown Source)
	at org.robolectric.util.inject.Injector.findConstructor(Injector.java:262)
	at org.robolectric.util.inject.Injector.inject(Injector.java:243)
	at org.robolectric.util.inject.Injector.lambda$new$0(Injector.java:126)
...

```

org.robolectric:robolectric:4.10
com.android.tools.build:gradle:8.0.0
kotlin_version = '1.8.20'
SDK 33 
Android Studio Flamingo | 2022.2.1
Using bundled AS Java

**Comment by utzcoz** [comment]
@renetik It's strange. Please attaching a sample to reproduce this issue, we can investigate it. Before that, you need to ensure you have correct conscrypt dependency in your test implementation tree. And you also can use [`ConscrytMode` with `OFF`](https://robolectric.org/configuring/) to disable conscrypt to avoid this issue temporarily.

**Comment by renetik** [comment]
Ok so look like this is Android Studio issue.. 

I see those failures just when i run using android studio:
![Uploading Screenshot 2023-04-22 at 15.45.00.png…]()

But I am sure this was working.. but nothing special that it broke in studio.

**Comment by utzcoz** [comment]
@renetik What about filing an issue to Android Studio at https://issuetracker.google.com/issues?

**Comment by renetik** [comment]
That would be a waste of time obviously. I believe this can be closed then...

**Comment by lupaulus** [comment]
@renetik Did you find a way to run the tests in Android Studio at the end ?

**Comment by renetik** [comment]
Hi, no its the same , there was the time whanit was able to create unit test configuration for a whole multi module project:
Now it gives me that exception for all roboelectric tests. So now not much benefit of using roboelectric instead of instrumented tests as each have its own limitations. Still they work when run individually per module as I reported. Not sure what is cause of this bug. Also I am puzzled why noone support while module testing in android studio but I have to resort to comnad line gradle for this, its less readable and test runner in studio is far more conveniety but spport for multi module project is wague. But testing works, this was just nice to have.

**Comment by Kyle-Falconer** [comment]
This issue is still happening, and seems to be the same one that's been marked as "merged"/closed:

https://github.com/google/conscrypt/issues/649

Using `ConscryptMode.Mode.OFF` does not help.

```java 
import static org.junit.Assert.assertEquals;

import android.content.Intent;
import android.database.MatrixCursor;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.ConscryptMode;

@RunWith(RobolectricTestRunner.class)
@ConscryptMode(ConscryptMode.Mode.OFF)
public class NewApiTest {

    @Test
    public void test() {
        int foo = Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION;
        foo++;
    }

    @Test
    public void testMatrixBuilder() {
        try (MatrixCursor cursor = new MatrixCursor(new String[]{"one", "two"})) {
            cursor.newRow()
                    .add("one", "val1")
                    .add("two", "val1");
            int count = cursor.getCount();
            assertEquals(count, 2);
        }

    }
}
```

**Comment by 1fexd** [comment]
> I figured it out, and should have seen it sooner. I'm not sure if the OP had the same or similar cause, but for me, it was the [HiddenApiRefinePlugin](https://github.com/RikkaApps/HiddenApiRefinePlugin), and this was already documented in their issues:
>
> https://github.com/RikkaApps/HiddenApiRefinePlugin/issues/20

+1, downgrading to `4.0.0` as suggested in the linked issue fixed the error
