### ISSUE TITLE
Migrate GitHub Actions' macos runner to faster one

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#8174]
See https://github.blog/changelog/2023-04-24-github-actions-faster-macos-runners-are-now-available-in-open-public-beta/. cc @brettchabot as I think AXT also can benefit from it.

**Comment by utzcoz** [comment]
> The macos-latest and macos-latest-xl workflow labels currently uses the macOS 12 runner image. For information about macOS XL runner (12-core) per-minute pricing, see "About billing for GitHub Actions."

Does XL runner need us to pay for it?

**Comment by hoisie** [comment]
Yeah I believe all larger runner instances use metered pricing, even for open source projects.

**Comment by utzcoz** [comment]
@hoisie It's sad. I decide to close this issue because I raise it with the expectation that it is free.
