### ISSUE TITLE
View height and width are always zero

### ISSUE THREAD

**Issue by christopherperry** [robolectric/robolectric#819]
Failing test:

```java
@Test
public void heightAndWidth_shouldNotBeZero() {
  TestActivity testActivity =
    Robolectric.buildActivity(TestActivity.class)
      .create().start().resume().visible().get();

  View contentView = testActivity.findViewById(69);
  assertThat(contentView.getWidth()).isNotZero();
  assertThat(contentView.getHeight()).isNotZero();
}

private static class TestActivity extends Activity {  
  @Override 
  protected void onCreate(Bundle savedInstanceState) {  
      super.onCreate(savedInstanceState);  
      LinearLayout contentView = new LinearLayout(this);  
      contentView.setId(69);    
      contentView.setLayoutParams(new LayoutParams(666, 666));
      setContentView(contentView);  
  }  
}  
```

**Comment by erd** [comment]
Thank you for the suggestion, but I don't think we're going to implement this.

**Comment by jpshelley** [comment]
@erd Do you have a good way to accomplish this? Would you recommend the mockito suggestion or the .measure and .layout approach?

**Comment by jongerrish** [comment]
Could we make Robolectric call into doTraversals() as part of the activity
life cycle?

**Comment by erd** [comment]
> Would you recommend the mockito suggestion or the .measure and .layout approach?

I would go with the measure and layout approach if you really need to have your components sized / positioned correctly.

> Could we make Robolectric call into doTraversals() as part of the activity life cycle?

It would make tests slower. Is it worth the trade-off?
