### ISSUE TITLE
Set clipboard timestamp when creating clipboard.

### ISSUE THREAD

**Issue by mhozza** [robolectric/robolectric#8263]
The ClipDescription should have a timestamp set to the time when the clipboard was created. Currently it's 0. 
This makes it hard to test logic that depends on clipboard timestamp.

ClipDescription has a hidden method setTimestamp. This should still be accessible via reflection in Robolectric.

**Comment by utzcoz** [comment]
@mhozza Would you like to send a PR to fix it?

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/8285, and it will be synced to master branch very soon. @mhozza Thanks for your contribution.
