### ISSUE TITLE
Color.HSVToColor method parameters should be pinned

### ISSUE THREAD

**Issue by mlebedy** [robolectric/robolectric#8275]
### Description

The hsv[1] and hsv[2] values for Color.HSVToColor method should be pinned according to the Android SDK documentation ("If hsv values are out of range, they are pinned.")

https://developer.android.com/reference/android/graphics/Color#HSVToColor(float[])

### Steps to Reproduce

The following tests are failing:

```
  @Test
  public void HSVToColorValueShouldBePinned() {
    assertThat(Color.HSVToColor(new float[] { 0f, 0f, -1.0f })).isEqualTo(Color.BLACK);
    assertThat(Color.HSVToColor(new float[] { 0f, 0f, 2.0f })).isEqualTo(Color.WHITE);
  }

  @Test
  public void HSVToColorSaturationShouldBePinned() {
    assertThat(Color.HSVToColor(new float[] { 0f, -1.0f, 0.5f })).isEqualTo(0xff808080);
    assertThat(Color.HSVToColor(new float[] { 0f, 2.0f, 0.5f })).isEqualTo(0xff800000);
  }

```

### Link to a public git repo demonstrating the problem:

https://github.com/mlebedy/robolectric/blob/colorpinning/robolectric/src/test/java/org/robolectric/shadows/ShadowColorTest.java

**Comment by utzcoz** [comment]
Fixed by https://github.com/robolectric/robolectric/pull/8277.
