### ISSUE TITLE
Bitmap.compress does not write to specified file outputstream

### ISSUE THREAD

**Issue by jdckr** [robolectric/robolectric#8290]
### Description
I am trying to test code which reads a bitmap, scales it and saves it using bitmap.compress. This code successfully runs in production, but when trying to implement a test after calling compress, no file is written.
I debugged through ImageUtil and didn't spot something particular wrong. When stepping the write part also takes some time. So seems like something is happening. But in the end I don't have a file.

Any idea what could be wrong?

### Steps to Reproduce
I have written a small test case which encapsulates the logic:
```
    @Test
    public void TestBitmap() throws FileNotFoundException {
        ContentResolver contentResolver = RuntimeEnvironment.getApplication().getContentResolver();
        File imageFile = new File("/path/to/image.jpg");
        Uri uri = Uri.fromFile(imageFile);
        InputStream inputStream = contentResolver.openInputStream(uri);
        Bitmap bitmap = BitmapFactory.decodeStream(inputStream);

        File outputFile = new File(App.getTempMediaFolder(), "test.jpg");

        OutputStream outputStream = contentResolver.openOutputStream(Uri.fromFile(outputFile));

        bitmap.compress(Bitmap.CompressFormat.JPEG, 50, outputStream);

        assertTrue(outputFile.exists());
    }
```
`App.getTempMediaFolder` returns a folder on the internal sd card. I have another function which verifies that writing to that folder using an outputsream works in general.

### Robolectric & Android Version
As it is a legacy project I am still on some old version:
Robolectric 4.9
targetSdkVersion 29

### Link to a public git repo demonstrating the problem:
n/a

**Comment by jdckr** [comment]
When specifiying the mode for openOutputStream it works.
Is this the desired behavior? The api description states that without mode "w" is used by default:
https://www.android-doc.com/reference/android/content/ContentResolver.html#openOutputStream(android.net.Uri)

**Comment by utzcoz** [comment]
@jdckr I think Robolectric 4.10+ can work without specifying the mode of `openOutputStream` as https://github.com/robolectric/robolectric/commit/2c0aa7b2494b6d6bd4668b91095ca168e821634c fixed it.

**Comment by utzcoz** [comment]
@jdckr Please try the Robolectric 4.10+, and feel free to reopen this issue if it doesn't work to you.
