### ISSUE TITLE
Constructor-injected Activities are not supported in `Robolectric.buildActivity()`

### ISSUE THREAD

**Issue by ZacSweers** [robolectric/robolectric#8335]
### Description

Related to #8004, but robolectric's `Robolectric.buildActivity()` API (which is used internally by `ActivityScenario` does not support appcomponentfactory, which prevents use of constructor-injected activities in tests.

Another alternative to this could be to expose a factory parameter to allow tests to provide their own means of constructing the activity, and expose this all the way up to the `ActivityScenario` APIs.

### Steps to Reproduce

Use a constructor-injected activity as the target to an `ActivityScenario` or `Robolectric.buildActivity()` call.

### Robolectric & Android Version

Robolectric `4.10.3`, Android SDK 28 or later

**Comment by sergio-sastre** [comment]
I actually did sth like that for Screenshot testing with Robolectric.

Just in case you find it useful, the [implementation is here](
https://github.com/sergio-sastre/AndroidUiTestingUtils/blob/master/robolectric/src/main/java/sergio/sastre/uitesting/robolectric/activityscenario/RobolectricActivityScenarioConfigurator.kt)

which is used in form of ActivityScenarios for [Activities, Views, Fragments and Composables here](robolectric/src/main/java/sergio/sastre/uitesting/robolectric/activityscenario)

**Comment by ZacSweers** [comment]
See https://github.com/robolectric/robolectric/issues/7581#issuecomment-3579232827
