### ISSUE TITLE
ServiceConnection#onServiceConnected() gives null IBinder

### ISSUE THREAD

**Issue by ghost** [robolectric/robolectric#834]
With an Activity that binds a Service with

``` java
@Override
protected void onResume() {
    super.onResume();
    bindService(new Intent(this, MyService.class), mServiceConnection, Context.BIND_AUTO_CREATE);
}
```

the resulting `onServiceConnected` callback in mServiceConnection:

``` java
protected ServiceConnection mServiceConnection = new ServiceConnection() {
   @Override
    public void onServiceConnected(ComponentName name, IBinder service) {
        mServiceBinder = (MyServiceBinder)service;
    }

    @Override
    public void onServiceDisconnected(ComponentName name) {
        mServiceBinder = null;
    }
};
```

has a null `IBinder service` parameter even though the Service's `onBind` function is

``` java
@Override
public IBinder onBind(Intent intent) {
    if (mBinder == null) {
        mBinder = new MyServiceBinder();
    }
    return mBinder;
}
```

So when doing

``` java
Activity activity = Robolectric.buildActivity(LandingActivity.class).create().start().resume().get();
```

in a Robolectric test, I get an NPE whenever `mServiceBinder` is accessed in the code and the test fails because of an unexpected exception.

If I take out all accesses of `mServiceBinder` in the activity, this test passes

``` java
@Test
public void landingBindsOktaService() {
    Activity activity = Robolectric.buildActivity(LandingActivity.class).create().start().resume().get();
    ShadowActivity shadowActivity = Robolectric.shadowOf(activity);

    Intent nextServiceIntent = shadowActivity.peekNextStartedService();
    ShadowIntent shadowIntent = Robolectric.shadowOf(nextServiceIntent);

    Assertions.assertThat(shadowIntent.getIntentClass().getName()).isEqualTo(MyService.class.getName());
}
```

Are services sufficiently mocked out that they don't actually get bound correctly?

Happy to provide more code if needed.

**Comment by padmajadav** [comment]
Is this issue has been fixed ? 

How can I write testcase for remote service locally ?

**Comment by erd** [comment]
> Is this issue has been fixed ?

Robolectric, by design, does not try and emulate service binding functionality. What you should do depends on what you're trying to test. You can use @SuperJugy's work-around if you just need to get past the NPE. If you are actually trying to test activity-service interaction, you test it with an integration test (e.g. Espresso).
