### ISSUE TITLE
ShadowDialog.getLatestDialog() returns null

### ISSUE THREAD

**Issue by Thorn1089** [robolectric/robolectric#836]
I assume this is something rather simple I'm missing. I have a test as follows:

```
View screen = launchScreen.findViewById(R.id.main_layout);
screen.performClick();
Dialog dialog = ShadowDialog.getLatestDialog();
assertThat("The dialog should be displayed", dialog, is(notNullValue()));
```

And in the activity's onClickListener:

```
FragmentManager fragmentManager = getSupportFragmentManager();
DialogFragment dialog = new FragmentFoo();
dialog.show(fragmentManager, "dialog");
```

Is this like Selenium where I should sleep() for a bit after clicking to give the system time to render content? Any ideas why that ShadowDialog call doesn't give me the dialog created by FragmentFoo's onCreateDialog call?

**Comment by vlazzle** [comment]
`fragmentManager.executePendingTransactions()` was the missing piece for me.
