### ISSUE TITLE
Matrix.setValues doesn't accept value array with size >9

### ISSUE THREAD

**Issue by zach-klippenstein** [robolectric/robolectric#8369]
### Description

If you call `android.graphics.Matrix.setValues` with an array of more than 9 elements, it throws an `ArrayIndexOutOfBoundsException`. This does not happen [on Android, where it throws](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/graphics/java/android/graphics/Matrix.java;l=763;drc=3b8b654519d76f1bc159e4c1c211b2dd413ec5a1) for _less than_ 9 values, but accepts >9 values.

This prevents an optimization [in Jetpack Compose where](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-graphics/src/androidMain/kotlin/androidx/compose/ui/graphics/AndroidMatrixConversions.android.kt;l=69-99;drc=dc1308e9d97c2f2f0b44abaef1f02939c62f0d27) we re-use a 4x4 array when converting between Compose's `Matrix` type and the system one.

### Steps to Reproduce

Create an `android.graphics.Matrix`, a 16-element array, and pass it to `setValues`.

### Robolectric & Android Version

Robolectric: 4.9.2, 4.10.3
Android: Every version Jetpack Compose tests on: 21, 26, 28, 30, 33.

### Link to a public git repo demonstrating the problem:

https://r.android.com/2647564

**Comment by zach-klippenstein** [comment]
Thanks for the suggestion, TIL! That could solve my immediate problem, but I also don't want to break downstream users of Compose who are running their own Robolectric tests and might be using Windows.

**Comment by zach-klippenstein** [comment]
Just talked to Aurimas, we're finally on 4.10.3. It's not super urgent to have this fix available, we just need it for part of the implementation of the new Compose text field rewrite. Do you know roughly when 4.11 is targeting release? If it's some time in the next couple months we can probably wait for that.

**Comment by zach-klippenstein** [comment]
I believe Android 14 source has been released. Do you have a rough ETA for when Robolectric might integrate it?

**Comment by hoisie** [comment]
We are in the process of releasing support for Android 14 (U).

**Comment by MGaetan89** [comment]
There were a couple of Robolectric releases since last October. Is there still something to do regarding this issue, or can it be closed=

**Comment by hoisie** [comment]
I think it can be closed, this issue was fixed nearly one year ago.
