### ISSUE TITLE
How to make Robolectric work with Powermock when the latter is used as an agent

### ISSUE THREAD

**Issue by nimeacuerdo** [robolectric/robolectric#837]
Hi,

I have a test that needs to run with the Robolectric test runner but I have a collision class issue between Robolectric dependency on asm and the powermock javaagent one.

I know this is not a Robolectric issue itself, but maybe you've come across this scenario at some point.

More info here: http://stackoverflow.com/questions/19998398/class-loading-collision-between-robolectric-and-powermock

**Comment by jaredsburrows** [comment]
@coreydowning Why did you close this without an explanation?
