### ISSUE TITLE
IllegalStateException during androidx.fragment.app.FragmentStateManager.addViewToContainer

### ISSUE THREAD

**Issue by fllaryora** [robolectric/robolectric#8399]
### Description
Hello I am having IllegalStateException. The issue is simular to https://github.com/robolectric/robolectric/issues/851

>System.logW: No Compatibility callbacks set! Querying change 210923482
>System.logW: No Compatibility callbacks set! Querying change 210923482
>
> The specified child already has a parent. You must call removeView() on the child's parent first.
> java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
> 
> The specified child already has a parent. You must call removeView() on the child's parent first.
> java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
> 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5248)
> 	at android.view.ViewGroup.addView(ViewGroup.java:5077)
> 	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at org.robolectric.shadows.ShadowViewGroup$ViewGroupReflector$$Reflector17.addView(Unknown Source)
> 	at org.robolectric.shadows.ShadowViewGroup.lambda$addView$0(ShadowViewGroup.java:30)
> 	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:33)
> 	at android.view.ViewGroup.addView(ViewGroup.java)
> 	at android.view.ViewGroup.addView(ViewGroup.java:5017)
> 	at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:881)
> 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:565)
> 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
> 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
> 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
> 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
> 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
> 	at androidx.fragment.app.testing.FragmentScenario$Companion.internalLaunch$lambda$2(FragmentScenario.kt:552)
> 	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$androidx-test-core-app-ActivityScenario(ActivityScenario.java:789)
> 	at androidx.test.core.app.ActivityScenario$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
> 	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:799)
> 	at androidx.fragment.app.testing.FragmentScenario$Companion.internalLaunch$fragment_testing_release(FragmentScenario.kt:525)
> 	at androidx.fragment.app.testing.FragmentScenario$Companion.launchInContainer(FragmentScenario.kt:492)

### Steps to Reproduce
- In test folder I create a kotlin class
XXXFragment is a type of DialogFragment.

```
private lateinit var scenario : FragmentScenario<XXXFragment>
private lateinit var factory: XXXFactory
@RunWith(RobolectricTestRunner::class)
@Config(
    manifest=Config.NONE,
    instrumentedPackages = [
        // required to access final members on androidx.loader.content.ModernAsyncTask
        "androidx.loader.content"
    ])

class XXXXXFragmentTest {
@Before
    fun setUp() {
       factory = XXXFactory("xxxx")
       assertNotNull(factory)
       scenario =  launchFragmentInContainer<XXXFragment>() {
            //instantiate
            println("Getting the Fragment...")
            return@launchFragmentInContainer factory.getFragment()
        }
}
@Test
    @Throws(Exception::class)
    fun shouldNotBeNull() {

        //GIVEN
        scenario.onFragment{ fragment ->
            assertNotNull(fragment)
        }
        
    }
}
```

### Robolectric & Android Version
 "org.robolectric:robolectric:4.10"
   compile Sdk  33
   target Sdk  33
   min Sdk  21

### Link to a public git repo demonstrating the problem:
No, I can not share it is private repo.

**Comment by fllaryora** [comment]
The issue is presented even in 4.10.3
And after to re-write the onCreateView of the fragment using:
-  layout inflaters:
- - with parent / without parent
- - rootAttach = true and false
- 
- or just return a new View, 
- 
I think the anormal behabior is in at org.robolectric.shadows. **ShadowViewGroup** addView
There is some work-arround with this component?

**Comment by hoisie** [comment]
`ShadowViewGroup. addView` just calls the real `ViewGroup. addView` code. This issue has nothing to do with Robolectric. Ensure that when a View is added to another ViewGroup, it doesn't already have a parent.

**Comment by fllaryora** [comment]
Hi Hoisie, I appreciate your read over the stack trace.
I will keep finding the root cause. Because I have almost a bare dialog Fragment.
Thanks !
