### ISSUE TITLE
App rejected: Violation of Device and Network Abuse policy

### ISSUE THREAD

**Issue by felixh10r** [robolectric/robolectric#8563]
### Description

Google Play rejected my app today on grounds of their [Device and Network Abuse policy](https://support.google.com/googleplay/android-developer/answer/9888379):

> We reviewed SDKs used by your app and found noncompliant versio n(s) of SDK(s) which contains code to download executable code (for example, dex, JAR, .so files) from a source other than Google Play.

I don't know a lot about the native Android release process so I hope it's not because of my build config but maybe this does/will affect other developers as well.

Indeed, Expo EAS Build includes `base/root/native/mac/aarch64/librobolectric-nativeruntime.dylib` in the .aab, even though it is listed as a `testImplementation`.

The frustrating part is that I seem to be the first person on the Internet with this problem. I've looked for any mention of this non-compliance in this repo and the libraries that reference it in my project. Also, they misspelled it as "roboelectric" one time 🤷 I tried to appeal the decision, but to no avail. If this is not an issue with Robolectic, I would be really glad if someone could point my in _any_ direction, thanks!

### Steps to Reproduce

The way this happens for me is:

`npx create-expo-app StickerSmash`

`npx expo prebuild`

`eas build --platform android`

The resulting .aab file includes the `librobolectric-nativeruntime.dylib`, because of which Google Play rejected my app update.

### Robolectric & Android Version

My dependencies include different versions of Robolectric:

4.7.3, 4.9.2, 4.10

**Comment by hoisie** [comment]
Under no circumstances should the Robolectric Jar files be present in a production app. It is designed to only be used in a test environment. If somehow Robolectric is being bundled in a production app, it means something is wrong with your build configuration. I do not have any experience with npx, so you should probably file an issue with that.

**Comment by felixh10r** [comment]
I see, thanks for the info 🙏

**Comment by GrilloLuca** [comment]
Happened the same exact thing to me, even with the misspelling "roboElectric".
I was using implementation instead of testImplementation.
