### ISSUE TITLE
Try dropbox/dependency-guard to avoid unexpected dependency changes

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#8631]
See https://github.com/dropbox/dependency-guard.

**Comment by MGaetan89** [comment]
What do you think about also using the following plugin: https://github.com/autonomousapps/dependency-analysis-gradle-plugin?
It reports unused plugins/dependencies, and warn if the wrong configuration is used (for example, `api` vs `implementation`).

**Comment by MGaetan89** [comment]
@utzcoz now that we have updated Guava, do we still have a need for this?
