### ISSUE TITLE
SDK 34: NfcAdapter.getDefaultAdapter() sometimes returns null

### ISSUE THREAD

**Issue by bvschaik** [robolectric/robolectric#8661]
### Description

When using `NfcAdapter` in a Robolectric test, it sometimes returns `null` for NfcAdapter.getDefaultAdapter(), only on SDK 34. SDK 33 and below always return a non-null object.

It looks like some sort of initialization problem.

When you just enable NFC and don't do anything with the default adapter, it will return non-null the first time, `null` the second time, and non-null for any subsequent calls:

```kotlin
val context: Context = ApplicationProvider.getApplicationContext()
Shadows.shadowOf(context.packageManager).setSystemFeature(PackageManager.FEATURE_NFC, true)

NfcAdapter.getDefaultAdapter(ApplicationProvider.getApplicationContext()) // non-null
NfcAdapter.getDefaultAdapter(ApplicationProvider.getApplicationContext()) // null on SDK 34, non-null on 33 and below
NfcAdapter.getDefaultAdapter(ApplicationProvider.getApplicationContext()) // again non-null
```

When you enable the default adapter through the nfc manager before calling NfcAdapter.getDefaultAdapter(), it returns `null` the first time, and non-null for any subsequent calls:

```kotlin
val context: Context = ApplicationProvider.getApplicationContext()
Shadows.shadowOf(context.packageManager).setSystemFeature(PackageManager.FEATURE_NFC, true)
Shadows.shadowOf((context.getSystemService("nfc") as NfcManager).defaultAdapter).setEnabled(true)

NfcAdapter.getDefaultAdapter(ApplicationProvider.getApplicationContext()) // null on SDK 34, non-null on 33 and below
NfcAdapter.getDefaultAdapter(ApplicationProvider.getApplicationContext()) // non-null
```

### Steps to Reproduce
1. Clone this project: https://github.com/bvschaik/robolectric-nfc-test
2. Run the unit test, note it fails on the second `assertNotNull` statement

Setting the SDK to 33 makes the test succeed.

### Robolectric & Android Version

Robolectric 4.11.1
Running with `sdk=34`

### Link to a public git repo demonstrating the problem:
https://github.com/bvschaik/robolectric-nfc-test

**Comment by MGaetan89** [comment]
@bvschaik Robolectric 4.13 introduced some changes to `NfcAdapter` to prevent `getDefaultAdapter()` from returning `null` (see https://github.com/robolectric/robolectric/pull/8897).
Can you give it a try to see if it fixes your issue?

**Comment by bvschaik** [comment]
Looks like it's fixed indeed, thanks!
