### ISSUE TITLE
[Robolectric 2.2] ShadowBitmapFactory not setting Config in ShadowBitmap causing NPE

### ISSUE THREAD

**Issue by hayribakici** [robolectric/robolectric#876]
Hi,
I want to test my program code which adds bitmaps into my LRU bitmap cache. My test fails at the bitmap.getByteCount() call when a bitmap is added to the cache.

```java
protected int sizeOf(final String key, final Bitmap bitmap) {
    // The cache size will be measured in bytes rather than number of items.
    return bitmap.getByteCount();
}
```

The stacktrace is the following:

```
java.lang.NullPointerException: Bitmap config was null. at org.robolectric.shadows.ShadowBitmap.getBytesPerPixel(ShadowBitmap.java:343)
    at org.robolectric.shadows.ShadowBitmap.getRowBytes(ShadowBitmap.java:230)
    at org.robolectric.shadows.ShadowBitmap.getByteCount(ShadowBitmap.java:235)
...
```

In my program code I am creating a bitmap with BitmapFactory.decodeStream(...) and add it to the cache. While stepping through the robolectric code, I found out that the Config for the newly created ShadowBitmap in ShadowBitmapFactory.create(String name, BitmapFactory.Options options) is never set, causing my test to fail. 

I think that the shadowBitmap.setConfig() call is missing in this method.

my workaround is the following

```java
@Implements(Bitmap.class)
public class MyShadowBitmap extends ShadowBitmap {

    public MyShadowBitmap() {
       // can also be some other config value
        setConfig(Bitmap.Config.ARGB_8888);
    }
}
```

cheers

**Comment by hameno** [comment]
There is still (in 3.0) a case where config is not set: createScaledBitmap
