### ISSUE TITLE
Shared preferences folder not consistent across tests

### ISSUE THREAD

**Issue by guillaume-tgl** [robolectric/robolectric#8765]
### Description

Within the same test class, the shared preferences folder is not always present depending on the different tests within that class.

### Steps to Reproduce

```
@RunWith(RobolectricTestRunner::class)
class SharedPrefsTest {

    @Test
    fun testSharedPrefsFolder() {
        val context: Context = ApplicationProvider.getApplicationContext()
        Assert.assertTrue(File(context.applicationInfo.dataDir, "shared_prefs").exists())
    }

    @Test
    fun testSharedPrefsFolder2() {
        val context: Context = ApplicationProvider.getApplicationContext()
        Assert.assertTrue(File(context.applicationInfo.dataDir, "shared_prefs").exists())
    }
}
```

Test results:
<img width="552" alt="Screenshot 2024-01-22 at 11 14 53" src="https://github.com/robolectric/robolectric/assets/2244170/5c2ed492-c94a-40f3-b833-1963c8c70c40">

### Robolectric & Android Version

Robolectric 4.11.1

**Comment by MGaetan89** [comment]
Hey @guillaume-tgl,
On my side, both tests return `false`. I tried with Robolectric 4.11.1, AndroidX Test Core 1.5.0, and Java 8.
Can you share more details about your setup? Or maybe try with the latest dependencies version?

**Comment by guillaume-tgl** [comment]
I get `false` for both tests now too. At least it's consistent 👍
