### ISSUE TITLE
Extract spotless configurations into a single SpotlessPlugin

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#8867]
1. Extract spotless configurations into a single `SpotlessPlugin`.
2. Applying this plugin for all existed modules that use Spotless already.

**Comment by Devashishbasu** [comment]
> 1. Extract spotless configurations into a single `SpotlessPlugin`.
> 2. Applying this plugin for all existed modules that use Spotless already.

Hi, @utzcoz could you please guide me more on how can i solve this issue?

**Comment by shashankiitbhu** [comment]
I think I can solve this issue and understand how it works, can you assign it to me @utzcoz

**Comment by Devashishbasu** [comment]
> @Devashishbasu I think you need to learn what is [spotless](https://github.com/diffplug/spotless), and how to write Gradle plugin: https://docs.gradle.org/current/userguide/custom_plugins.html first. This task just wants to extract current spotless configurations in different modules to a single Gradle plugin, like SpotlessPlugin, and apply it to modules that want Spotless for its module's code formatting.

Thank you ...please assign this issue to me

**Comment by Devashishbasu** [comment]
Hi @utzcoz ....do i have to create SpotlessPlugin class in this folder org.robolectric.internal.dependency?
