### ISSUE TITLE
publish-to-snapshot task always failed if the merged commit is created by dependabot

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#8906]
1. If the latest merged commit is created and merged by dependabot, the `publish-to-snapshot` task is always failed.
2. If the latest merged commit is from other people instead of dependabot, the `publish-to-snapshot` task will work as expected.

Maybe there are some limitations for dependabot, and we need to find it and fix it.

**Comment by MGaetan89** [comment]
Here's the error when the `publish-to-snapshots` step fails:
```
> Task :annotations:publishMavenJavaPublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':annotations:publishMavenJavaPublicationToMavenRepository'.
> Failed to publish publication 'mavenJava' to repository 'maven'
   > Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/annotations/4.12-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```

And the corresponding GitHub Actions step:
https://github.com/robolectric/robolectric/blob/1476881ea5a0fa6d70f42ab485d9d118a79d690b/.github/workflows/tests.yml#L165-L185

**Comment by MGaetan89** [comment]
I think the secrets needs to be configured for Dependabot too, not only for GitHub Actions.
Here's a screenshot of a successful build on `main` for `publish-to-snapshots`:
<img width="441" alt="Screenshot 2024-03-11 at 14 39 40" src="https://github.com/robolectric/robolectric/assets/1009664/38077ce0-927f-4ca2-9d93-3b4d48365c18">

And here's a screenshot for a failing build triggered by Dependabot:
<img width="441" alt="Screenshot 2024-03-11 at 14 40 10" src="https://github.com/robolectric/robolectric/assets/1009664/5265b7a0-3f84-4aba-aea4-f7cc2f4756e7">

So I think that adding the `SONATYPE_LOGIN` and `SONATYPE_PASSWORD` secrets to [settings/secrets/dependabot](https://github.com/robolectric/robolectric/settings/secrets/dependabot) might fix the issue.

**Comment by MGaetan89** [comment]
Since it only runs when a push is made on `main`, why not move it into a dedicated workflow, with the trigger:
```yml
on:
  push:
    branches:
      - main
```

But I don't know if that (or using `pull_request_target`) will fix the issue

**Comment by MGaetan89** [comment]
@utzcoz now that a new PR from Dependabot has been merged, it reminded me of this issue.
I've had a look at [the documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions), and if I understood correctly, using `pull_request_template` won't work either:
> For workflows initiated by Dependabot (`github.actor == 'dependabot[bot]'`) using the `pull_request_target` event, if the base ref of the pull request was created by Dependabot (`github.actor == 'dependabot[bot]'`), the `GITHUB_TOKEN` will be read-only and secrets are not available.

For our current case (ie. using the `pull_request` event):
> Secrets are populated from Dependabot secrets. GitHub Actions secrets are not available.

So I think that my initial suggestion of adding the necessary secrets to Dependabot's config is the way to go:
> When a Dependabot event triggers a workflow, the only secrets available to the workflow are Dependabot secrets. GitHub Actions secrets are not available. Consequently, you must store any secrets that are used by a workflow triggered by Dependabot events as Dependabot secrets.

**Comment by hoisie** [comment]
Thanks for the investigation. I will look to see if I am able to add a a dependabot secret.
