### ISSUE TITLE
Bouncycastle dependency vulnerability

### ISSUE THREAD

**Issue by binpower93** [robolectric/robolectric#8992]
### Description
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6612984

Version of bouncy castle 1.77 has a vulnerability according to Snyk, whereas 1.78 doesn't. I believe that develop branch is using 1.78, but isn't yet included in a release

**Comment by MGaetan89** [comment]
I don't know when the next release of Robolectric is scheduled, but if this a blocker for you, you can try one of the following:
- [Use a snapshot](https://github.com/robolectric/robolectric?tab=readme-ov-file#using-snapshots) of Robolectric
- Include BouncyCastle 1.78 in your repository directly (no changes were necessary inside Robolectric for this update, as per https://github.com/robolectric/robolectric/pull/8975)

**Comment by MGaetan89** [comment]
We have released Robolectric 4.13, which contains BouncyCastle 1.78.1:
https://github.com/robolectric/robolectric/blob/79bc3034b38b94ed8b4317b666edb42f093358cd/gradle/libs.versions.toml#L13

So I'm closing this issue. Thanks for reporting it.
