### ISSUE TITLE
Robolectric does not return a hardware accelerated canvas for Surface#lockHardwareCanvas

### ISSUE THREAD

**Issue by nadewad** [robolectric/robolectric#9081]
### Description

According to the docs, [Surface#lockHardwareCanvas](https://developer.android.com/reference/android/view/Surface#lockHardwareCanvas()) is guaranteed to return a a hardware-accelerated Canvas.

However, in Robolectric based testing environments the Canvas that is returned is a software backed canvas, that is [Canvas#isHardwareAccelerated](https://developer.android.com/reference/android/graphics/Canvas#isHardwareAccelerated()) returns false

### Steps to Reproduce

1) Obtain a Surface instance
2) Call Surface#lockHardwareCanvas
3) Call isHardwareAccelerated on the returned canvas

### Robolectric & Android Version

Any

This causes a number of testing related issues as software rendering on Android is an increasingly deprecated code path. Newer graphics APIs are only backed with hardware acceleration and there will not be software backed alternatives.

**Comment by hoisie** [comment]
Hi @nadewad,

Thanks for reporting this issue.

Do you know if this just occurs with LEGACY graphics mode (`@GraphicsMode(LEGACY)`), or with NATIVE graphics mode as well ((`@GraphicsMode(NATIVE)`).

> This causes a number of testing related issues as software rendering on Android is an increasingly deprecated code path

NATIVE graphics mode is high-fidelity and uses native Android graphics libraries. Starting in Android V, it will use the same libandroid_runtime libraries that LayoutLib uses. This includes support for HW graphics effects. We are planning to do another point release (4.11.2) which makes further improvements to HW rendering.

**Comment by hoisie** [comment]
Hi @nadewad,

What version of Robolectric are you using?

Looking at Robolectric's tests, I believe the `isHardwareAccelerated` should work:
https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowSurfaceTest.java#L72-L77

This is the test case:
```
  @Test
  @Config(minSdk = M)
  public void lockHardwareCanvas_returnsCanvas() {
    Canvas canvas = surface.lockHardwareCanvas();
    assertThat(canvas.isHardwareAccelerated()).isTrue();
  }

```

**Comment by MGaetan89** [comment]
@nadewad is this still an issue for you? If so, can you answer to @hoisie questions (Robolectric version, graphics mode used)

**Comment by MGaetan89** [comment]
I'm closing this, since it seems to be working as expected, and we didn't receive any updates in a few months.
@nadewad feel free to reopen this issue if you still encounter problems using the latest Robolectric version (currently 4.14.1).
