### ISSUE TITLE
ShadowContextWrapper doesn't implement sendOrderedBroadcast(...)

### ISSUE THREAD

**Issue by robertoandrade** [robolectric/robolectric#912]
I had to resort to creating my own shadow given I use both in my code to be able to test code. Would be nice if this was part of Robolectric's default implementation.

```
@Implements(ContextWrapper.class)
public class ShadowOrderedBroadcastContextWrapper extends ShadowContextWrapper {

    @RealObject Context context;

    @Implementation
    public void sendOrderedBroadcast( Intent intent, String receiverPermissions )
    {
        sendBroadcast( intent );
    }
}
```

I guess it could pass the string down to checkCallingPermission(String) but wasn't too sure if that was necessary.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
