### ISSUE TITLE
Update `google-java-format` to its latest version

### ISSUE THREAD

**Issue by MGaetan89** [robolectric/robolectric#9163]
# Context

Currently, the [`check_code_style.yml`](https://github.com/robolectric/robolectric/blob/master/.github/workflows/check_code_style.yml) workflow uses [`google-java-format` v1.15.0](https://github.com/google/google-java-format/releases/tag/v1.15.0):
https://github.com/robolectric/robolectric/blob/1bd807f26f2ba3182fb3b0232ddf08728a27d7a5/.github/workflows/check_code_style.yml#L36-L40

Also, the name of the step still refers to an old version of `google-java-format` (1.9).

# Tasks

- Update the `check_code_style.yml` workflow to use the latest version of `google-java-format` (currently [v1.22.0](https://github.com/google/google-java-format/releases/tag/v1.22.0)).
- Fix new warnings reported by the tool, if any.
- Remove the version reference from the step name.

**Comment by MGaetan89** [comment]
I'll have time to work on that later, if no one picks it up first

**Comment by MGaetan89** [comment]
@utzcoz I've updated `google-java-format` to 1.22.0 locally, and reformatted the whole project with it, and it triggers a lot of changes (about 700 files, and 15k additions/deletions).
I've rollbacked my changed, and reformatted the project with `google-java-format` 1.15.0, and I already have about 45 files changed, with ~1 +/-.

How do you prefer to proceed? Should I:
1. Send a first PR to reformat the project with `google-java-format` 1.15.0, then an other one to update `google-java-format` to 1.22.0 and reformat the project again?
2. Send a PR to update directly `google-java-format` to 1.22.0, with the whole project reformatted?
3. Send a PR that only updates `google-java-format` to 1.22.0, and we'll reformat the project as we modify Java files?

@hoisie any input as to what might be easier for compatibility with the `google` branch?

**Comment by MGaetan89** [comment]
Friendly ping @hoisie and @utzcoz.
I've added an other approach: bump one version at a time, with a reformat with each PR.

**Comment by hoisie** [comment]
How about start with (3), and then put up a PR to update everything. I will try to run that against the Google internal tools to see if anything went wrong.

Btw some files, like the `processor` test resources, should not be formatted because they can be regenerated and the formatting will be reversed.
