### ISSUE TITLE
[Suggestion] Allow setting global dependency injector

### ISSUE THREAD

**Issue by davidshen84** [robolectric/robolectric#920]
When creating Activity using the ActivityController<>, the `setContent` method will inflate the layout, if the layout contains *Fragment*, the **real** fragment class will be created and initialized. But some of the fragments are very heavy, it is too expensive to create it for every test case; or I want to mock some of its behavior to make testing on the Activity easier.

I think if we can intercept the `inflate` process while it is parsing the XML, and return mock fragment instance, it would simplify testing a lot.

**Comment by erd** [comment]
Thank you for the suggestion, but I don't think we're going to implement this.
