### ISSUE TITLE
Make finding of Application configurable

### ISSUE THREAD

**Issue by saemmy** [robolectric/robolectric#921]
In the Blog is described how Robolectric searches for the Application:

> Finding Your Application
>By default, Robolectric first looks in your AndroidManifest.xml for the class to load >as your application:
>
><manifest xmlns:android="http://schemas.android.com/apk/res/android"
>   package="com.myapp">
>  <application android:name=".Application"/>
></manifest>
>
>That will cause a class called com.myapp.Application to be loaded. However, if >you create a class with the same name and package, but with "Test" prepended >to the class name, Robolectric will load that instead.
>
>package com.myapp;
>class TestApplication extends Application {
>}

But if I use the TestApplication it is not possible to use com.myapp.Application for a single test, e.g. if I want to write a test for com.myapp.Application.

Config.DEFAULT gives me the TestApplication
Config.NONE gives me the android.app.Application

Finding application should be improved in this way, that it is possible to get com.maypp.Application for a single test.

**Comment by erd** [comment]
This was fixed in 9cc9bde8928b83e5de9cd1c521e157e1a584b2fd

You should now be able to specify the application via the `@Config` annotation which takes precedence over any of the other mechanisms.
