### ISSUE TITLE
publish-to-snapshot always fails on current CI

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#9212]
There is an case: https://github.com/robolectric/robolectric/actions/runs/9677170816/job/26698767672.

@hoisie I think it might require your help. I don't know whether we need update credential for snapshot.

**Comment by MGaetan89** [comment]
Maybe it's not specific to Robolectric, as I see the same failure on this repo: https://github.com/autonomousapps/dependency-analysis-gradle-plugin/actions/runs/9688967507/job/26736451807

**Comment by hoisie** [comment]
I can reproduce this error locally when I try to publish:

```
> Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/annotations/4.13-SNAPSHOT/annotations-4.13-20240630.070547-52.jar'. Received status code 401 from server: Content access is protected by token
```

I will try to enable signing and see if that fixes it locally.

**Comment by hoisie** [comment]
FWIW signing did not fix the issue.

**Comment by MGaetan89** [comment]
My understanding of the link provided by @utzcoz (https://central.sonatype.org/news/20240617_migration_of_accounts/#publishing-with-username-password) is that we should update the upload process to use a token, instead of a username/password:
https://github.com/robolectric/robolectric/blob/e1b88ec90d8b94cdc441b5498851444e96735ee2/.github/workflows/tests.yml#L174-L175

**Comment by hoisie** [comment]
@MGaetan89 yes that appears to be the case. I am going to generate a user token now and see what happens.

**Comment by MGaetan89** [comment]
It seems to be used in other places too:
https://github.com/search?q=repo%3Arobolectric%2Frobolectric%20SONATYPE_LOGIN&type=code

**Comment by hoisie** [comment]
I have generated a user token and updated the github actions secrets with the new l/p. Seems to be working (I am re-running the latest failed publish task).
