### ISSUE TITLE
missing readBoolean writeBoolean in shadowParcel class

### ISSUE THREAD

**Issue by salmen** [robolectric/robolectric#9281]
Hello,
### Description
We are using in the source code under test two methods readBoolean and writeBoolean from Parcel 
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/Parcel.java#1198
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/Parcel.java#3280

When we run Unit Test, we got this error : java.lang.NoSuchMethodError: 'boolean android.os.Parcel.readBoolean()'

Calling readInt instead of readBoolean makes the test run successfully 

### Robolectric & Android Version

Android 14
robolectic 4.8.2

Best Regards,

Salmen

**Comment by MGaetan89** [comment]
Indeed, the `readBoolean()` and `writeBoolean()` are missing from the shadow `Parcel` implementation.
I'll work on submitting a PR to support them.

**Comment by hoisie** [comment]
readBoolean was added in API level 29:

https://developer.android.com/reference/android/os/Parcel#readBoolean()

You need to run your tests in API levels >= 29.

**Comment by MGaetan89** [comment]
Good catch!

I've added the following test to `ShadowParcelTest`:
```java
@Test
public void testReadBooleanWhenEmpty() {
  assertThat(parcel.readBoolean()).isFalse();
  assertThat(parcel.dataPosition()).isEqualTo(0);
  assertInvariants();
}
```

And it seems to work on API 26+ (instead of API 29+):
<img width="307" alt="Screenshot 2024-07-11 at 15 46 05" src="https://github.com/robolectric/robolectric/assets/1009664/415c36ea-08eb-4cec-aa08-ff22330b9ec7">

**Comment by hoisie** [comment]
Because there is no method `{read,write}Boolean` on `ShadowParcel`, the real Android code is used instead by default. So Robolectric will try to invoke the real `Parcel.readBoolean` and `Parcel.writeBoolean`. It appears that these also exist on API 26-28, but perhaps were marked `@hide`.

**Comment by salmen** [comment]
Hello @MGaetan89 ,
When I add  @Config(minSdk = 29) the test is just ignored.
In my settings.gradle.kts 
android {
    minSdk = 32
    compileSdk = 34
}

Regards,

**Comment by hoisie** [comment]
@salmen 

Please see https://robolectric.org/configuring/ for more details about configuring Robolectric to run on specific SDK levels.

I think `minSdk = 32` is very restrictive, it means your app won't run on 60% of devices.

<img width="797" alt="image" src="https://github.com/user-attachments/assets/59950031-5859-41ae-82b0-3c6b0dacb2bf">
