### ISSUE TITLE
SharedPreferences#contains doesn't follow the official Android docs

### ISSUE THREAD

**Issue by andrew-k-21-12** [robolectric/robolectric#9286]
### Description
From the [docs](https://developer.android.com/reference/android/content/SharedPreferences.Editor#putString(java.lang.String,%20java.lang.String)) for `android.content.SharedPreferences.Editor#putString`:
```java
/**
 * ...
 * @param value The new value for the preference.  Passing {@code null}
 *    for this argument is equivalent to calling {@link #remove(String)} with
 *    this key.
 * ...
 */
```
But passing `null` as `value` for this method makes the further check done with `android.content.SharedPreferences#contains` return `true` in the Robolectric environment. At the same time everything works according to the mentioned docs when no Robolectric is used.

### Steps to Reproduce
```kotlin
@RunWith(RobolectricTestRunner::class)
class SharedPreferencesTest {

	@Test
	fun testContains() {
		val key = "key"
		val value = "value"
		val default = "default"
		val sharedPreferences =
			ApplicationProvider.getApplicationContext<Context>().getSharedPreferences("test", Context.MODE_PRIVATE)
		sharedPreferences.edit().putString(key, value).commit()
		assertEquals(value, sharedPreferences.getString(key, default)) // the value is saved
		sharedPreferences.edit().putString(key, null).commit()
		assertEquals(default, sharedPreferences.getString(key, default)) // the value is removed, a default one is returned
		assertEquals(false, sharedPreferences.contains(key)) // but `contains` claims it's still here

		// At the same time `remove` works as expected.
		sharedPreferences.edit().remove(key).commit()
		assertEquals(false, sharedPreferences.contains(key))
	}

}
```

### Robolectric & Android Version
Robolectric - 4.11.1, 4.12.2.
Android - did not specify any particular version in my tests.

**Comment by MGaetan89** [comment]
I tried to reproduce this locally from the Robolectric project (latest `master` https://github.com/robolectric/robolectric/commit/e84541a05e52a3427734a87d7563420dd8d573be), and it worked fine.
I then tried from the 4.12.2 tag, and I was able to reproduce it.
Can you try using the latest 4.13 version of Robolectric?

**Comment by andrew-k-21-12** [comment]
Yes, I can confirm it too - `SharedPreferences` works correctly with the latest 4.13 version of Robolectric. Thank you.
