### ISSUE TITLE
DrawerLayout issues

### ISSUE THREAD

**Issue by coreydowning** [robolectric/robolectric#932]
Noticed a few "gotchas" with the `DrawerLayout` and Robolectric and seems worth investigating.

`ActivityController.visible()` breaks `isDrawerOpen()` and `isDrawerVisible()`. These methods will never return true if you've called `visible()` on the activity controller.

`DrawerLayout.closeDrawers()` does not work. Closing individual drawers with `closeDrawer()` does

**Comment by jaredsburrows** [comment]
@coreydowning How are you unit testing the drawer? `isDrawerOpen` does not work for me.
