### ISSUE TITLE
NPE on DataFormat.format static method.

### ISSUE THREAD

**Issue by arichiardi** [robolectric/robolectric#941]
Try to add the following to org.robolectric.shadows.DateFormatTest:
```
@Test
public void getDateFormat_formatShouldNotThrowNPE() {
    Time time = new Time();
    time.setToNow();
    
    DateFormat.format("h:mm AA", time.toMillis(false));
}
```

The problem seems to be in ```ShadowLocaleData``` where the ```get()``` method is just returning ```return newInstanceOf(REAL_CLASS_NAME)```.
This triggers the static initializer of the original class which is:
```
package libcore.icu;
...
public final class LocaleData {
...
static {
    // Ensure that we pull in the locale data for the root locale, en_US, and the
    // user's default locale. (All devices must support the root locale and en_US,
    // and they're used for various system things like HTTP headers.) Pre-populating
    // the cache is especially useful on Android because we'll share this via the Zygote.
    get(Locale.ROOT);
    get(Locale.US);
    get(Locale.getDefault());
}
```
I don't know if this cause infinite recursion or not, I am still investigating, has anyone noticed this as well?

EDIT: I cloned the last snapshot and haven't tried 2.2.

**Comment by erd** [comment]
This should be fixed by d7c87e4a951f2e1e38cc65a2af7ddf31844abd4c. Keep in mind that robolectric only contains locale data for en_US.
