### ISSUE TITLE
MavenArtifactFetcher ignores nonProxyHosts setting

### ISSUE THREAD

**Issue by pfei5** [robolectric/robolectric#9482]
I have defined `systemProp.https.nonProxyHosts` and `systemProp.http.nonProxyHosts` in my `gradle.properties` file.
org.robolectric.internal.dependency.MavenArtifactFetcher ignores this setting however.

We have an internal corporate Nexus server that hosts our artifacts which is inaccessible through our proxy.
MavenArtifactFetcher tries to go through the proxy to get to our Nexus which is impossible.
`nonProxyHosts` would be the ideal option to define non-proxy URLs.

### Robolectric & Android Version
Android Api Level 34
Roboelectric 4.13

**Comment by MGaetan89** [comment]
Hey @pfei5,
Can you check [this page](https://robolectric.org/blog/2023/11/11/improving-android-all-downloading/#setting-custom-proxy-for-mavenartifactfetcher) to this if it helps?

**Comment by MGaetan89** [comment]
@pfei5 do you need more help regarding this issue, or can we close it?

**Comment by pfei5** [comment]
@MGaetan89 yes that helped, thank you very much. You can close this issue.
