### ISSUE TITLE
Use resources when running JUnit tests from Java command line

### ISSUE THREAD

**Issue by Guywash-Ka** [robolectric/robolectric#9612]
**Is your feature request related to a problem? Please describe.**
I'm trying to run my unit tests via `java -cp myClasses.jar:R.jar:libs.jar org.junit.runner.JUnitCore com.example.project.ExampleUnitTest`
following this [doc](https://github.com/junit-team/junit4/wiki/Getting-started#run-the-test). It works when I do not use resources. When I use in my test something like `ApplicationProvider.getApplicationContext<Context>().resources.getString(id)` I get the following error: android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0034

**Describe the solution you'd like**
I would like to know, what is the solution to pass the resource files so that robolectric sees them

**Additional context**
My test class:
```
@RunWith(RobolectricTestRunner::class)
class ExampleUnitTest {
    @Test
    fun testResource() {
        val id = R.string.hello_world
        Assert.assertEquals(ApplicationProvider.getApplicationContext<Context>().resources.getString(id), "Hello, World!")
    }
}
```

**Comment by MGaetan89** [comment]
Have you tried to set the right properties to tell Robolectric where to find the compiled resources?
You can check [this page](https://robolectric.org/build-system-integration/) for more information

**Comment by Guywash-Ka** [comment]
It works. Thank you!
