### ISSUE TITLE
Robolectric should escape strings.XML like android does

### ISSUE THREAD

**Issue by coreydowning** [robolectric/robolectric#962]
Android requires you escape characters like `'` in strings.xml but robolectric doesn't so you end up asserting like so:

``` java
assertThat(myTextView.getText()).isEqualTo("corey\\'s issue");
```

(Typographical errors courtesy of the android keyboard.)

**Comment by manjubex** [comment]
'm running some tests to check if the data is filled right in the fields. In the name field, I've a input filter with this regex "[A-ZÀ-ÚA-Za-zà-úûÛ-Üa-zä\\s’]*", but when the field is filled in test environment, the regex is not matching the name ("Bruno Pinto").

I get the regex from the XML inside my custom view. To do that I use:

 TypedArray a = context.getTheme().obtainStyledAttributes(
            attrs,
            R.styleable.FloatLabelLayout,
            0, 0);
If I debug this line in test environment:

        final String regex = a.getString(R.styleable.FloatLabelLayout_regex);
regex = "[A-ZÀ-ÚA-Za-zà-úûÛ-Üa-zä\s’]"

If I debug the same line in normal run environment:

regex = "[A-ZÀ-ÚA-Za-zà-úûÛ-Üa-zä\s’]"

Someone knows what I've to do to make this works?

InputFilter

```java
InputFilter[] inputFilter = new InputFilter[]{
            new InputFilter.LengthFilter(maxLength),
            new InputFilter() {
                public CharSequence filter(CharSequence src, int start, int end, Spanned dst, int dstart, int dend) {
                    if (src.equals("") || regex == null) { // for backspace
                        return src;
                    }
                    if (src.toString().matches(regex)) {
                        return src;
                    }
                    return "";
                }
            }
    }; 
```
Test

  ```java
@Test
public void testFillName() {
    fragment.setData(getUser());
    assertEquals("Name right", getUser().fullName, ((FloatLabelLayout) fragment.getView().findViewById(R.id.personal_name)).getText());
}
```

**Comment by vgrichina** [comment]
@erd @zofrex the fix for this issue is incomplete, as it only handles few special cases properly (like quotes). 

However there could be Unicode character codes escaped in strings, e.g.
      <string name="bad_example">This\u0020will fail</string>

I think it is better to use something like https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#unescapeJson(java.lang.String) to unescape strings properly.
