### ISSUE TITLE
Thread safety issue with XResourceLoader 

### ISSUE THREAD

**Issue by eric-kampf** [robolectric/robolectric#968]
I have experienced a threading issue with org.robolectric.res.XResourceLoader.  Observe the initialize method:

```
 void initialize() {
        if (isInitialized) return; 
        doInitialize();
        isInitialized = true;
        makeImmutable();
 }
```

Note that the "isInitialized" flag, which appears to prevent multiple initializations, does not provide full protection.  It is possible that 2 or more threads could call the "doInitialize()" method.  In fact, I have seen that in my Android application.  When this occurs, bad things happen (concurrent modification of data structures) that break the Robolectric test.

My recommendation is that the "initialize" method of this class be synchronized.

**Comment by pohh** [comment]
I believe #1083 could be related to this.  I'm able to consistently repro something similiar in 2 environments:

- osx 10.10.1, Java(TM) SE Runtime Environment (build 1.8.0_25-b17), build tools 21.1.2

- ubuntu 12 .04, Java(TM) SE Runtime Environment (build 1.7.0_72-b14), build tools 21.1.2

I tried to get a 3.0-SNAPSHOT build running locally to implement the fix described by @eric-kampf but I am running into some issues setting up my local maven repo to resolve dependencies.

OSX environment seems to run tests, ubuntu misses 90% of the time.

**Comment by jponsvega** [comment]
I'm trying to work around this issue, besides modifying the code to synchronize that piece, has anyone found a way to resolve it? I'm seeing the issue appear intermittently in OSX, and recurrently on a Ubuntu environment.

**Comment by xian** [comment]
Resource loading now happens before the test starts, so this issue is resolved.
