### ISSUE TITLE
bcprov-jdk18on-1.78.1.jar in 4.13

### ISSUE THREAD

**Issue by icegood** [robolectric/robolectric#9684]
### Description

Execution failed for task ':lintAnalyzeDebug'.
> Could not resolve all files for configuration ':debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk18on-1.78.1.jar (org.bouncycastle:bcprov-jdk18on:1.78.1) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

### Steps to Reproduce
gradle build. Works against 4.12

### Robolectric & Android Version

testImplementation 'org.robolectric:robolectric:4.13'

compileSdk 33
    minSdkVersion 30
    targetSdkVersion 30

### Link to a public git repo demonstrating the problem:

none

**Comment by hoisie** [comment]
@icegood this appears to be more of an AGP issue, Robolectric has zero control over what `lintAnalyzeDebug` does.
