### ISSUE TITLE
cannot swizzle value of type 'shader' when using Runtime Shader with child shader

### ISSUE THREAD

**Issue by chrisbanes** [robolectric/robolectric#9691]
### Description

I'm currently playing with runtime shaders, and hitting an exception when trying to use a child shader:

```
cannot swizzle value of type 'shader'
```

### Steps to Reproduce

``` kotlin
@Test
fun test() {
  val shader = RuntimeShader(
    """
      uniform shader mask;

      vec4 main(vec2 coord) {
        float intensity = mask.eval(coord).a;
        return vec4(1.0, 1.0, 1.0, intensity);
      }
    """.trimIndent()
  )
}
```

### Robolectric & Android Version

Android SDK 33
Robolectric 4.13

**Comment by hoisie** [comment]
If you are running on SDK levels 26-34 in Robolectric, all of the RuntimeShader code is coming from Android S (SDK 31). So if this RuntimeShader script is not supported in Android S, it will also fail when running in T.

Could you try the 4.14-beta-1 release and see if it works on Android V (SDK 35)?

**Comment by chrisbanes** [comment]
Ahh, I didn't realise it was based on SDK 31. I'll give the beta a try and report back. Thanks!

**Comment by chrisbanes** [comment]
Ah ignore me. I forgot to update the tests to use SDK 35. It works! 🎉
