### ISSUE TITLE
Remove use of androidx.multidex

### ISSUE THREAD

**Issue by liutikas** [robolectric/robolectric#9723]
### Description

Minimum supported version in robolectric is API 21, once you use that version androidx.multidex is no longer useful. It is now just unused code in robolectric.

### Steps to Reproduce

N/A

### Robolectric & Android Version

Latest

### Link to a public git repo demonstrating the problem:

N/A

**Comment by MGaetan89** [comment]
@hoisie are you ok with deprecating the [`shadows-multidex`](https://github.com/robolectric/robolectric/tree/master/shadows/multidex) module?
It could be done in the 4.14 release, and removed in the 4.15 version. What do you think?

**Comment by liutikas** [comment]
It is not urgent, just something I spotted
