### ISSUE TITLE
Database does not support cascade deletions for foreign keys

### ISSUE THREAD

**Issue by ikravchenko** [robolectric/robolectric#980]
When trying to perform `ON DELETE CASCADE` operations for tables connected with foreign keys, no action is performed.
Example:

CREATION:

    CREATE TABLE DOCS (DOCID TEXT PRIMARY KEY);
    CREATE TABLE PAGES(
       DOCID_FOR_PAGE TEXT NOT NULL,
       PAGEID TEXT NOT NULL,
       PRIMARY KEY (DOCID_FOR_PAGE, PAGE_ID),
       FOREIGN KEY (DOCID_FOR_PAGE) REFERENCES DOCS(DOCID) ON DELETE CASCADE);

DELETION:

    DELETE FROM DOCS; 

EXPECTED:

pages with the corresponding doc ids should be deleted

RESULT:

pages are not deleted

**Comment by erd** [comment]
This should be fixed when we switched over to using a real version of SQLite. Try upgrading to the most recent release (2.4 or 3.0-rc2) and see if it works.
