### ISSUE TITLE
Test execution much slower compared to Robolectric 1.x

### ISSUE THREAD

**Issue by mpost** [robolectric/robolectric#982]
We have quite a few robolectric tests that we migrated from robolectric 1.x to robolectric 2 (2.3-SNAPSHOT). We witnessed that the test execution is much slower compared to robolectric 1.x.

Our 2000+ tests take 3-4 times as long to execute. Eg from 30-40 seconds up to 2 minutes and more. Combined with the gradle startup time the development experience is subpar.

Can we expect to see better robolectric performance in the future? 

Is there anything that can be done to speed up the execution? Or any robolectric patterns to avoid?

**Comment by shubhamchaudhary** [comment]
Similar problem with 3.0. First test in every suite taking long time. It's like:
class AbcTest:
  test1: 18sec
  test2: 50ms
  test3: 41ms . . .

Is this usual? I don't remember tests taking so much last time I worked with 2.4 tests!

**Comment by bolatug** [comment]
My first test on newly created project and I am just trying to robolectric "writing your first test" example. It takes 16 seconds which scares me. Fast feed back is the first reason for TDD.  Is there any thing I can do?

org.robolectric:robolectric:3.2.2
targetSdk 24
minSdk 15
my computer is window 8.1 with some Intel i7 processor and 16GB ram

**Comment by jongerrish** [comment]
That feels very long, compared to robolectrics own tests, which
individually run sub-one-second.

How big are your unit tests? Do you do a lot of work in your
Application.onCreate()?

You can profile using YourKit profiler and see where the work is done.
Attach your profiler report and if it's robolectric itself we'll take a
look and see what can be done.

**Comment by bolatug** [comment]
I just created the project with an empty activity called MainActivity and just added a Button in to the layout. And created another activity and tried to implement the test case in the site http://robolectric.org/writing-a-test/ 
So there is only one unit test. And the only logic the project contains is calling activityStart method to open other empty activity. 

I couldn't find any resources about how to profile a unit test, can any one provide me some pointers. I am using Android Studio 2.2.3

**Comment by mpost** [comment]
The instantiation of an Activity takes very very long. Therefore it is advised to reuse an activity throughout multiple tests.
